-- Cannibalisation clusters
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('d7216281-21e5-4430-90f8-6b5413b5503c'::uuid, 'apprentice-electrician-salary', 'guide', '/guides/apprentice-electrician-salary', '{"/guides/apprentice-electrician-salary","/guides/apprentice-electrician-salary-uk"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('0a25bf68-72ba-40c1-8cff-ca07f474de13'::uuid, 'battery-storage-installation', 'guide', '/guides/battery-storage-installation', '{"/guides/battery-storage-installation","/battery-storage-installation"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('0e1c04f7-3c1c-438b-bc73-c3f4d9bf9e8f'::uuid, 'consumer-unit-types', 'guide', '/guides/consumer-unit-types', '{"/consumer-unit-types-guide","/guides/consumer-unit-types"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('c6f06c5a-2e0b-461a-a648-0d83c800f943'::uuid, 'data-centre-electrical-installation', 'guide', '/guides/data-centre-electrical-installation', '{"/guides/data-centre-electrical-installation","/data-centre-electrical-installation"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('eb347991-f2a4-421e-8ab3-e3d7a3a21e88'::uuid, 'ev-charger-installation', 'training', '/guides/ev-charger-installation', '{"/guides/ev-charger-installation","/training/ev-charger-installation"}'::text[], 'auto-canonicalised');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('f92eb78f-e446-4879-af4d-508e61d5be6a'::uuid, 'earth-electrode-testing', 'guide', '/guides/earth-electrode-testing', '{"/guides/earth-electrode-testing","/earth-electrode-testing"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('593c4c76-9b2b-4a4b-a05a-bd48d0f76f39'::uuid, 'electrical-handover-documentation', 'guide', '/guides/electrical-handover-documentation', '{"/guides/electrical-handover-documentation-guide","/guides/electrical-handover-documentation"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('0260b4fb-aa09-4d2f-a919-1e8f980e32cb'::uuid, 'electrician-tool-insurance', 'tool', '/electrician-tool-insurance-2025', '{"/electrician-tool-insurance-2025","/guides/electrician-tool-insurance"}'::text[], 'auto-canonicalised');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('b7455fc2-aed4-4ef0-ab1e-26f169b85e4e'::uuid, 'electrician-working-abroad', 'guide', '/guides/electrician-working-abroad', '{"/guides/electrician-working-abroad","/guides/electrician-working-abroad-uk"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('f4bbcc15-ef24-4d12-8f09-b2ee4dacc8ec'::uuid, 'electrician-van-setup', 'guide', '/guides/electrician-van-setup', '{"/guides/electrician-van-setup-guide","/guides/electrician-van-setup"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('1398342d-1144-49d2-a329-a0cc5f547f87'::uuid, 'emergency-lighting-certificate', 'cert', '/emergency-lighting-certificate', '{"/guides/emergency-lighting-certificate-guide","/emergency-lighting-certificate"}'::text[], 'auto-canonicalised');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('5d2c7ea2-abd1-4554-9eb9-bfae57a97941'::uuid, 'house-extension-electrical-cost', 'guide', '/guides/house-extension-electrical-cost', '{"/guides/house-extension-electrical-cost","/house-extension-electrical-cost"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('a365570e-8e4a-415a-9f6b-b24e876d68f3'::uuid, 'insulation-resistance-testing', 'guide', '/guides/insulation-resistance-testing', '{"/guides/insulation-resistance-testing","/insulation-resistance-testing-guide"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('7dbf6cf9-098e-4886-bf05-eca78d8795f4'::uuid, 'spd-surge-protection', 'guide', '/guides/spd-surge-protection', '{"/guides/spd-surge-protection-guide","/guides/spd-surge-protection"}'::text[], 'namespace_match:/guides/');
INSERT INTO seo_cannibalisation_cluster (id, cluster_topic, intent_class, canonical_slug, member_slugs, decided_reason) VALUES ('286f6553-dcf5-4f52-b064-a6a19cee533a'::uuid, 'testing-sequence', 'guide', '/guides/testing-sequence-guide', '{"/testing-sequence-guide","/guides/testing-sequence-guide"}'::text[], 'namespace_match:/guides/');