
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { CPDEntry, CPDStats, CPDGoal } from './cpdDataService';

export interface ExportOptions {
  includeEvidence?: boolean;
  includeGoals?: boolean;
  dateRange?: {
    start: string;
    end: string;
  };
  categories?: string[];
  format: 'pdf' | 'csv' | 'summary';
}

class CPDExportService {
  
  exportToPDF(entries: CPDEntry[], stats: CPDStats, goals: CPDGoal[], options: ExportOptions = { format: 'pdf' }): void {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(0, 102, 204);
    doc.text('CPD Training Report', 105, 15, { align: 'center' });
    
    // Report metadata
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 20, 30);
    doc.text(`Report Period: ${options.dateRange ? `${options.dateRange.start} to ${options.dateRange.end}` : 'All Time'}`, 20, 40);
    
    // Summary statistics
    doc.setFontSize(14);
    doc.setTextColor(0, 102, 204);
    doc.text('CPD Summary', 20, 60);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Hours This Year: ${stats.hoursThisYear}`, 20, 75);
    doc.text(`Target Hours: ${stats.targetHours}`, 20, 85);
    doc.text(`Completion: ${stats.completionPercentage}%`, 20, 95);
    doc.text(`Days Remaining: ${stats.daysRemaining}`, 20, 105);
    
    // Filter entries if date range specified
    let filteredEntries = entries;
    if (options.dateRange) {
      filteredEntries = entries.filter(entry => {
        const entryDate = new Date(entry.date);
        const startDate = new Date(options.dateRange!.start);
        const endDate = new Date(options.dateRange!.end);
        return entryDate >= startDate && entryDate <= endDate;
      });
    }
    
    if (options.categories && options.categories.length > 0) {
      filteredEntries = filteredEntries.filter(entry => 
        options.categories!.includes(entry.category)
      );
    }
    
    // CPD Entries table
    const tableData = filteredEntries.map(entry => [
      format(new Date(entry.date), 'dd/MM/yyyy'),
      entry.activity,
      entry.category,
      entry.hours.toString(),
      entry.provider,
      entry.status,
    ]);
    
    autoTable(doc, {
      startY: 120,
      head: [['Date', 'Activity', 'Category', 'Hours', 'Provider', 'Status']],
      body: tableData,
      headStyles: {
        fillColor: [0, 102, 204],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240],
      },
      styles: {
        fontSize: 8,
      },
    });
    
    // Goals section if requested
    if (options.includeGoals && goals.length > 0) {
      const finalY = (doc as any).lastAutoTable.finalY + 20;
      
      doc.setFontSize(14);
      doc.setTextColor(0, 102, 204);
      doc.text('CPD Goals', 20, finalY);
      
      const goalsData = goals.map(goal => [
        goal.title,
        goal.targetHours.toString(),
        goal.currentHours.toString(),
        `${Math.round((goal.currentHours / goal.targetHours) * 100)}%`,
        format(new Date(goal.deadline), 'dd/MM/yyyy'),
        goal.status,
      ]);
      
      autoTable(doc, {
        startY: finalY + 10,
        head: [['Goal', 'Target Hours', 'Current Hours', 'Progress', 'Deadline', 'Status']],
        body: goalsData,
        headStyles: {
          fillColor: [0, 102, 204],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        styles: {
          fontSize: 8,
        },
      });
    }
    
    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(
        `Page ${i} of ${pageCount} - Generated by Elec-Mate CPD Tracker`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
    
    doc.save(`cpd-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  }
  
  exportToCSV(entries: CPDEntry[], options: ExportOptions = { format: 'csv' }): void {
    let filteredEntries = entries;
    
    if (options.dateRange) {
      filteredEntries = entries.filter(entry => {
        const entryDate = new Date(entry.date);
        const startDate = new Date(options.dateRange!.start);
        const endDate = new Date(options.dateRange!.end);
        return entryDate >= startDate && entryDate <= endDate;
      });
    }
    
    if (options.categories && options.categories.length > 0) {
      filteredEntries = filteredEntries.filter(entry => 
        options.categories!.includes(entry.category)
      );
    }
    
    const headers = [
      'Date',
      'Activity',
      'Category',
      'Type',
      'Hours',
      'Provider',
      'Description',
      'Learning Outcomes',
      'Certificate',
      'Status',
      'Auto Tracked',
    ];
    
    const csvData = filteredEntries.map(entry => [
      entry.date,
      entry.activity,
      entry.category,
      entry.type,
      entry.hours.toString(),
      entry.provider,
      entry.description || '',
      entry.learningOutcomes || '',
      entry.certificate || '',
      entry.status,
      entry.isAutomatic ? 'Yes' : 'No',
    ]);
    
    const csvContent = [headers, ...csvData]
      .map(row => row.map(field => `"${field}"`).join(','))
      .join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `cpd-entries-${format(new Date(), 'yyyy-MM-dd')}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  }
  
  generateSummaryReport(entries: CPDEntry[], stats: CPDStats, goals: CPDGoal[]): string {
    const currentYear = new Date().getFullYear();
    
    return `
CPD SUMMARY REPORT
Generated: ${format(new Date(), 'PPP')}

OVERVIEW
========
Total Hours This Year: ${stats.hoursThisYear}
Target Hours: ${stats.targetHours}
Completion Rate: ${stats.completionPercentage}%
Days Remaining: ${stats.daysRemaining}
Average Hours/Month: ${stats.averageHoursPerMonth.toFixed(1)}

CATEGORY BREAKDOWN
==================
${stats.categoryBreakdown.map(cat => 
  `${cat.category}: ${cat.hours} hours (${cat.percentage}%)`
).join('\n')}

RECENT ACTIVITIES
=================
${entries.slice(0, 5).map(entry => 
  `${entry.date} - ${entry.activity} (${entry.hours}h)`
).join('\n')}

GOALS PROGRESS
==============
${goals.map(goal => 
  `${goal.title}: ${goal.currentHours}/${goal.targetHours} hours (${Math.round((goal.currentHours / goal.targetHours) * 100)}%)`
).join('\n')}

COMPLIANCE STATUS
=================
Professional Body Requirements: ${stats.completionPercentage >= 80 ? 'ON TRACK' : 'ATTENTION NEEDED'}
Recommended Actions: ${stats.completionPercentage < 80 ? 
  'Increase learning activities to meet annual target' : 
  'Continue current learning pace'}
    `.trim();
  }
}

export const cpdExportService = new CPDExportService();
