
import jsPDF from 'jspdf';

interface PortfolioTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  sections: string[];
}

export const generatePortfolioTemplate = (template: PortfolioTemplate) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  let yPosition = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text(template.name, margin, yPosition);
  yPosition += 15;

  // Description
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  const descriptionLines = pdf.splitTextToSize(template.description, pageWidth - 2 * margin);
  pdf.text(descriptionLines, margin, yPosition);
  yPosition += descriptionLines.length * 6 + 10;

  // Sections
  template.sections.forEach((section, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = margin;
    }

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${index + 1}. ${section}`, margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text("Instructions:", margin, yPosition);
    yPosition += 6;
    pdf.text("• Document your work with clear, high-quality evidence", margin + 5, yPosition);
    yPosition += 5;
    pdf.text("• Include photos, written reflections, and assessor feedback", margin + 5, yPosition);
    yPosition += 5;
    pdf.text("• Reference relevant standards and regulations", margin + 5, yPosition);
    yPosition += 10;

    pdf.text("Evidence Required:", margin, yPosition);
    yPosition += 6;
    pdf.text("• Photographic evidence of work completed", margin + 5, yPosition);
    yPosition += 5;
    pdf.text("• Written reflection on learning outcomes", margin + 5, yPosition);
    yPosition += 5;
    pdf.text("• Supervisor/assessor feedback and signatures", margin + 5, yPosition);
    yPosition += 15;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "italic");
  pdf.text("Generated by Elec-Mate Portfolio Builder", margin, pdf.internal.pageSize.height - 10);

  return pdf;
};

export const downloadTemplate = (template: PortfolioTemplate) => {
  const pdf = generatePortfolioTemplate(template);
  pdf.save(`${template.name.replace(/\s+/g, '_')}_template.pdf`);
};
