import jsPDF from 'jspdf';
import { saveOrSharePdf } from '@/utils/save-or-share-pdf';
import { getBrandColour, ensureSpace, addAccentBar } from '@/utils/pdfBrand';

interface PortfolioTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  sections: string[];
  /** Optional saved company accent colour (hex). Falls back to Elec-Mate navy. */
  brandColour?: string;
}

export const generatePortfolioTemplate = (template: PortfolioTemplate) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  const bulletIndent = margin + 5;
  const brand = getBrandColour(template.brandColour);
  let yPosition = margin;

  // Brand accent strip + top margin offset
  addAccentBar(pdf, brand);

  // Title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(brand[0], brand[1], brand[2]);
  pdf.text(template.name, margin, yPosition);
  pdf.setTextColor(0, 0, 0);
  yPosition += 15;

  // Description
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  const descriptionLines = pdf.splitTextToSize(template.description, pageWidth - 2 * margin);
  pdf.text(descriptionLines, margin, yPosition);
  yPosition += descriptionLines.length * 6 + 10;

  // Sections
  template.sections.forEach((section, index) => {
    // Keep the whole section block (heading + both bullet groups) together so
    // sections don't split mid-bullet. Total height ≈ 10 + 6 + 3×5 + 10 + 6 + 3×5 + 15.
    yPosition = ensureSpace(pdf, yPosition, 92, { bottomMargin: 20, topAfterBreak: margin });

    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(brand[0], brand[1], brand[2]);
    pdf.text(`${index + 1}. ${section}`, margin, yPosition);
    pdf.setTextColor(0, 0, 0);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Instructions:', margin, yPosition);
    yPosition += 6;
    pdf.text('• Document your work with clear, high-quality evidence', bulletIndent, yPosition);
    yPosition += 5;
    pdf.text('• Include photos, written reflections, and assessor feedback', bulletIndent, yPosition);
    yPosition += 5;
    pdf.text('• Reference relevant standards and regulations', bulletIndent, yPosition);
    yPosition += 10;

    pdf.text('Evidence Required:', margin, yPosition);
    yPosition += 6;
    pdf.text('• Photographic evidence of work completed', bulletIndent, yPosition);
    yPosition += 5;
    pdf.text('• Written reflection on learning outcomes', bulletIndent, yPosition);
    yPosition += 5;
    pdf.text('• Supervisor/assessor feedback and signatures', bulletIndent, yPosition);
    yPosition += 15;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Generated by Elec-Mate Portfolio Builder', margin, pdf.internal.pageSize.height - 10);

  return pdf;
};

export const downloadTemplate = async (template: PortfolioTemplate) => {
  const pdf = generatePortfolioTemplate(template);
  await saveOrSharePdf(pdf, `${template.name.replace(/\s+/g, '_')}_template.pdf`);
};
