import { chromium, devices } from 'playwright';
import { createClient } from '@supabase/supabase-js';
import fs from 'node:fs';
const [fixturePath, outDir, mode, url] = process.argv.slice(2);
const SUPABASE_URL = 'https://jtwygbeceundfgnkirof.supabase.co';
const src = fs.readFileSync('scripts/college-demo/shoot.mjs', 'utf8');
const ANON = src.match(/'(eyJ[^']+)'/)[1];
const fx = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));
const sb = createClient(SUPABASE_URL, ANON, { auth: { persistSession: false } });
const { data } = await sb.auth.signInWithPassword({ email: fx.email, password: fx.password });
const browser = await chromium.launch();
const ctx = await browser.newContext(mode === 'phone' ? { ...devices['iPhone 14'], locale: 'en-GB' } : { viewport: { width: 1440, height: 900 }, locale: 'en-GB' });
await ctx.addInitScript(([k, v]) => { try { if (!localStorage.getItem(k)) localStorage.setItem(k, v); localStorage.setItem('cookie-consent', JSON.stringify({necessary:true,analytics:false,marketing:false,timestamp:Date.now()})); } catch {} }, ['sb-jtwygbeceundfgnkirof-auth-token', JSON.stringify(data.session)]);
const page = await ctx.newPage();
const errs = []; page.on('pageerror', e => errs.push(String(e)));
await page.goto('http://localhost:8080' + url, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await page.waitForTimeout(3000);
await page.getByRole('button', { name: 'Essential only' }).click({ timeout: 4000 }).catch(() => {});
await page.waitForTimeout(500);
const sec = page.locator('#assess');
await sec.scrollIntoViewIfNeeded(); await page.waitForTimeout(800);
await page.screenshot({ path: `${outDir}/${mode}_assess_1_section.png` });
await sec.getByRole('button', { name: /^022/ }).first().click(); await page.waitForTimeout(800);
const rows = sec.locator('li li button');
await rows.nth(0).click(); await rows.nth(1).click(); await page.waitForTimeout(500);
await page.screenshot({ path: `${outDir}/${mode}_assess_2_selected.png` });
await page.getByRole('button', { name: /Record decision for/ }).click(); await page.waitForTimeout(1000);
await page.screenshot({ path: `${outDir}/${mode}_assess_3_sheet.png` });
await page.locator('[role=dialog] .overflow-y-auto').first().evaluate(el => el.scrollTo(0, el.scrollHeight)).catch(() => {});
await page.waitForTimeout(400);
await page.screenshot({ path: `${outDir}/${mode}_assess_4_sheet_bottom.png` });
console.log(mode, 'errors:', errs.length, errs.slice(0,2).join(' | '));
await browser.close();
