
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Book, CircuitBoard, Code, FileText, Lightbulb } from "lucide-react";
import { Link } from "react-router-dom";
import BackButton from "@/components/common/BackButton";

const ApprenticeAITools = () => {
  const aiTools = [
    {
      id: 1,
      title: "Circuit Assistant",
      description: "AI-powered circuit design validator and troubleshooter",
      status: "Available",
      icon: CircuitBoard
    },
    {
      id: 2,
      title: "Code Companion",
      description: "Get explanations of UK electrical regulations and IET Wiring Regulations",
      status: "Available",
      icon: Code
    },
    {
      id: 3,
      title: "Installation Guide",
      description: "Step-by-step AI guidance for complex electrical installations compliant with BS 7671",
      status: "Beta Access",
      icon: FileText
    },
    {
      id: 5,
      title: "Learning Assistant",
      description: "Personalized learning support for EAL and City & Guilds curriculum",
      status: "Available", 
      icon: Book
    },
    {
      id: 6,
      title: "Trade Tips",
      description: "Practical advice from experienced UK electricians generated by AI",
      status: "New",
      icon: Lightbulb
    }
  ];

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
        <h1 className="text-3xl font-bold tracking-tight text-center">AI Tools for Apprentices</h1>
        <div className="flex-grow"></div>
        <BackButton customUrl="/apprentice/hub" label="Back to Apprentice Hub" />
      </div>

      <Card className="border-elec-yellow/20 bg-elec-gray">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-elec-yellow" />
            AI-Powered Learning
          </CardTitle>
          <CardDescription>
            These AI tools are designed specifically for UK electrical apprentices
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="mb-4">
            Our AI tools provide instant feedback, personalized learning, and practical guidance
            to supplement your formal training and on-site experience. All tools are built with
            UK electrical standards and practices in mind.
          </p>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {aiTools.map((tool) => (
          <Card key={tool.id} className="border-elec-yellow/20 bg-elec-gray hover:shadow-md transition-shadow">
            <CardHeader className="pb-2">
              <div className="flex justify-between items-start">
                <CardTitle className="text-xl flex items-center gap-2">
                  <tool.icon className="h-5 w-5 text-elec-yellow" />
                  {tool.title}
                </CardTitle>
                <span className={`text-xs px-2 py-1 rounded-md ${
                  tool.status === "Available" 
                    ? "bg-green-500/20 text-green-400" 
                    : tool.status === "Beta Access"
                    ? "bg-blue-500/20 text-blue-400"
                    : tool.status === "New"
                    ? "bg-purple-500/20 text-purple-400"
                    : "bg-amber-500/20 text-amber-400"
                }`}>
                  {tool.status}
                </span>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground mb-4">{tool.description}</p>
              <Button className="w-full">Launch Tool</Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default ApprenticeAITools;
