/**
 * Employer Mate page knowledge: one entry per Employer Hub section and Worker
 * Tools page, written from each component's code on 7 Oct 2026 (button labels,
 * tabs and role rules). Read by page-knowledge.ts. When a page changes, change
 * its entry here, then regenerate src/components/employer/mateSuggestions.ts.
 */
const PAGES_A = [
  {
    key: 'overview',
    title: 'Employer',
    area: 'Hub',
    what: 'The morning briefing: a To do list of everything that needs you today (safety, unbooked jobs, approvals, expiring tickets), who is where today, the week ahead, Money tiles and the hub cards for every area.',
    tabs: [],
    tasks: [
      'Work the day: go down "To do", most urgent first, and tap the button on each row ("Approve", "Decide", "Review") to jump straight to it.',
      'See who is out: check "Today" for who is booked, clocked in or on leave, tap a person to open their job, or tap "Diary" for the full board.',
      'Start a job: tap "New job" in the top bar, or "Diary" to book people on existing jobs.',
      'Share your quote page: in "Grow" under "Your quote page" tap "Copy", "Share" or "QR".',
      'New firm set-up: follow "Your first five minutes" (company profile and logo, add your team, create your first job, book someone on it, card payments, share your quote page).',
    ],
    who: 'Owner/admin: everything including the Money tiles (Owed to you, Paid this month, Quotes waiting, Gross profit). Office: everything else on the page, without the figures.',
    records: '',
    mate: 'Can pull what is waiting across the firm (get_pending_approvals), safety items (get_safety_overview, list_overdue_safety_actions), expiring tickets (list_expiring_tickets) and draft a job (create_job); cannot approve anything, gives the taps.',
    suggestions: ['What needs me today?', 'Who is on site right now?', 'How do I book someone on a job?'],
  },
  {
    key: 'peoplehub',
    title: 'People',
    area: 'People',
    what: 'The front door to everything about your workforce: alerts (timesheets to approve, leave to decide, invites not joined, credentials expiring, new applications, unread messages), quick actions, live on-site counts and cards for each People screen.',
    tabs: [],
    tasks: [
      'Add someone: tap "Invite member" under Quick actions, then "Add team member" on the Team page.',
      'Approve hours: tap "Approve timesheets" to open Timesheets.',
      'Hire: tap "Post vacancy" to open Job Vacancies, or open "Talent Pool" under Grow the team.',
      'Message everyone: tap "Message team" to open Communications.',
      'Check compliance: tap the "Compliance" ring to open Credentials.',
    ],
    who: '',
    records: '',
    mate: 'Can list the team (list_team), pending approvals (get_pending_approvals) and expiring tickets (list_expiring_tickets), add a team member (add_team_member) or draft a vacancy (create_vacancy), and with a confirmation card approve clean timesheets (approve_timesheets), decide leave (decide_leave), chase an invite (chase_team_invite) or message the team (send_team_message).',
    suggestions: ['Who has not joined yet?', 'Whose tickets are expiring?', 'What is waiting for approval?'],
  },
  {
    key: 'team',
    title: 'Your Team',
    area: 'People',
    what: 'Every operative, supervisor and PM on your books. Open a person to see their details, jobs, hours, spend, leave and credentials, or chase invites for people who have not signed in.',
    tabs: [
      'Active: people who have joined',
      'Invited: added but never signed in, with "Send reminder" and "Team code"',
      'Archived: people taken off the team',
    ],
    tasks: [
      'Add a person: tap "Add team member", fill name, job role and team role, tap "Next" through the steps, then "Add team member".',
      'Chase an invite: open "Invited", tap "Send reminder" on their row (up to three, a day apart).',
      'Put people on a job: tap the multi-select icon, pick people, tap "Assign".',
      'Archive a leaver: open their sheet, tap "Archive" (or "Archive anyway" if they still have open items). "Restore to team" brings them back.',
      'Edit someone: open their sheet and tap "Edit Profile".',
    ],
    who: 'Owner/admin: see hourly rates and can sort by rate. Office: same page without pay rates.',
    records: 'URL ?member=<id> opens that worker\'s sheet; ?tab=invited opens the Invited tab.',
    mate: 'Can list the team (list_team), read one worker (get_team_member, or get_page_record when ?member is open) and add a team member (add_team_member). With a confirmation card it can email an invite reminder to someone who has not joined (chase_team_invite: offer it on the Invited tab), book someone on a job (book_person_on_job) or message them (send_team_message). Cannot edit or archive people, gives the steps.',
    suggestions: ['Who has not joined yet?', 'How do I archive someone?', 'Add a new electrician'],
  },
  {
    key: 'elecid',
    title: 'Credentials',
    area: 'People',
    what: 'Elec-ID digital credentials for the team: ECS cards, qualifications, training and expiry dates, with a competence matrix you can export for a principal contractor.',
    tabs: [
      'Workers: one credential profile per person',
      'Competence matrix: the grid principal contractors ask for, with "Export PDF", "Share" and "CSV"',
      'All, ECS checked, ECS not checked, Expiring, Expired: filters on the Workers list',
    ],
    tasks: [
      'Give someone an Elec-ID: tap "Add credential", pick the person, or tap "Create all" for everyone missing one.',
      'Record an ECS check: open the worker, tap the "ECS card" row under Verification, choose how you checked it, tap "Save".',
      'Chase renewals: open the worker and tap "Nudge to renew" under Urgent attention.',
      'Add training: open the worker and tap "Add training".',
      'Send a contractor the matrix: open "Competence matrix" and tap "Export PDF" or "Share".',
    ],
    who: 'Skills and work history can only be edited on an Elec-ID the firm created itself; a worker\'s own Elec-ID is theirs to share.',
    records: 'URL ?member=<id> selects that worker.',
    mate: 'Can list expiring tickets (list_expiring_tickets) and read a worker (get_team_member); cannot record checks or send nudges, gives the steps.',
    suggestions: ['Whose ECS cards expire soon?', 'How do I record an ECS check?', 'Export the competence matrix'],
  },
  {
    key: 'timesheets',
    title: 'Timesheets',
    area: 'People',
    what: 'Every hour the team logs lands here. You approve it or send it back, then download the approved hours as a payroll or hours file.',
    tabs: [
      'Week: the week on screen, per worker',
      'Pending: everything waiting, every week',
      'Approved: approved entries for the week',
      'Leave: opens the Leave page',
    ],
    tasks: [
      'Approve the clean ones: open "Pending", in the "Payroll check" card tap "Approve all N clean". Flagged entries (long day, no break, weekend, no job, far from site, no rate) stay for you.',
      'Approve one or send back: tap the entry, then "Approve", or "Reject", type the reason and tap "Send back".',
      'Approve several: tap "Select", then "Select all waiting" or tick entries, then "Approve".',
      'Add a missed day: tap "Add entry".',
      'Pay the team: tap "Payroll file" (office sees "Hours file") and download.',
    ],
    who: 'Owner/admin: see pay rates, spend and the payroll file, and set the timesheet rules (cog). Office: can approve and send back but sees hours only and gets the "Hours file".',
    records: 'URL ?tab=pending or ?tab=approved opens that tab; ?tab=leave forwards to Leave.',
    mate: 'Can list pending entries by person (get_pending_approvals) and a worker\'s recent hours (get_team_member). With a confirmation card it can approve a person\'s clean entries (approve_timesheets; flagged ones only when the user names them, never one still clocked in) and send an entry back with the user\'s reason (send_back_timesheet). Offer it: "Dan has 4 clean entries, want me to approve them?". Cannot add entries or download the payroll file, gives the steps.',
    suggestions: ['How do I approve the week?', 'Who has entries waiting?', 'Why is this entry flagged?'],
  },
  {
    key: 'leave',
    title: 'Leave',
    area: 'People',
    what: 'Holiday and time-off requests from the team, who is off in the next 7 days, a month calendar, and each person\'s allowance for the year.',
    tabs: [],
    tasks: [
      'Decide a request: under "Waiting for you" tap the request, check the clash warning, then "Approve" (or "Approve anyway"), or "Decline", type why and tap "Send decline".',
      'Book agreed leave: tap "Book leave", pick who, type and length, then "Yes, book it" or "No, add as a request".',
      'Set an allowance: under "Allowances" tap the person (amber "Set it" means none set), enter days they work and the allowance, tap "Save".',
    ],
    who: '',
    records: '',
    mate: 'Can list leave waiting for a decision (get_pending_approvals) and a worker\'s recent leave (get_team_member). With a confirmation card it can approve or decline a request (decide_leave): the card shows clashes (others off, jobs left with nobody) first, and a decline needs the user\'s reason. Cannot book leave or set allowances, gives the steps.',
    suggestions: ['Who is off this week?', 'How do I set holiday allowance?', 'Who has leave waiting?'],
  },
  {
    key: 'comms',
    title: 'Communications',
    area: 'People',
    what: 'Announcements, job messages and safety alerts to the team, each a thread they can reply in, with a record of who has read or acknowledged it.',
    tabs: [
      'All: every message',
      'New replies: threads with unread replies',
      'Awaiting sign-off: must-acknowledge messages not everyone has confirmed',
      'Safety: safety alerts',
    ],
    tasks: [
      'Send a message: tap "New message", pick "Everyone", "A job\'s crew" or "Choose people", pick the kind, tick "Must acknowledge" if needed, write it, tap "Send to N people".',
      'Chase who has not read it: open the message and tap "Chase N" (once an hour at most). Tap "Who" to see each person.',
      'Pin or delete: open the message and tap the pin icon or the bin, then "Delete".',
      'Everyday chat: tap "Team chat" for channels and direct messages.',
    ],
    who: '',
    records: 'URL ?thread=<id> opens that message thread.',
    mate: 'Can read the open thread (get_page_record). With a confirmation card it can send a message to everyone, a job\'s crew or named people, with or without must-acknowledge (send_team_message); offer to draft it. Cannot chase, pin or delete messages, gives the steps.',
    suggestions: ['Who has not read my message?', 'How do I send a safety alert?', 'How do I chase acknowledgements?'],
  },
  {
    key: 'talentpool',
    title: 'Talent Pool',
    area: 'People',
    what: 'Electricians who have switched on "Let firms find me" in their Elec-ID. You see first name, area and credentials; phone and email stay private, so contact is through messages.',
    tabs: [
      'All, Verified+, Premium, EV Charging, Solar PV, Senior 8+ yrs: quick filters on the list',
    ],
    tasks: [
      'Narrow the list: tap "Filters" and set Elec-ID verification, specialisms, experience, ECS card type or day rate, then "Done".',
      'Contact someone: tap "Message" on their card, write it, tap "Send Message".',
      'Ask them to apply: tap "Invite", pick a live vacancy, tap "Send Invitation".',
      'Shortlist: tap the bookmark on their card to save them.',
    ],
    who: '',
    records: '',
    mate: 'Can draft a vacancy to invite people to (create_vacancy); cannot message or invite candidates, gives the steps.',
    suggestions: ['Why is the pool empty?', 'How do I invite someone to apply?', 'Can I see their phone number?'],
  },
  {
    key: 'apprentices',
    title: 'Apprentices',
    area: 'People',
    what: 'Live college progress for apprentices on your books: off-the-job hours, attendance, course progress, end-point assessment and progress reviews, plus training entries waiting for your attestation.',
    tabs: [],
    tasks: [
      'Confirm logged hours: under "Awaiting your attestation" tap the entry, check what they logged and the evidence, tap "Attest N h".',
      'Query an entry: open it, tap "Send back", type what is wrong, tap "Confirm send back".',
      'Check one apprentice: tap them under "Your apprentices" to see OTJ hours, attendance, EPA dates and reviews.',
      'Get a review booked: open the apprentice and tap "Ask to arrange review" when one is due.',
    ],
    who: 'Office managers cannot confirm apprentice OTJ hours; the owner or an admin attests.',
    records: 'URL ?entry=<id> opens that training entry\'s review sheet.',
    mate: 'Can read the team (list_team, get_team_member); cannot attest or send back hours, gives the steps.',
    suggestions: ['What hours need attesting?', 'Is this apprentice on track?', 'When is their next review due?'],
  },
  {
    key: 'vacancies',
    title: 'Job Vacancies',
    area: 'People',
    what: 'Post roles, review applicants through a hiring pipeline (New, Reviewing, Shortlisted, Interview, Offer, Hired) and message candidates.',
    tabs: [
      'Vacancies: your roles, split into Live, Draft and Closed',
      'Candidates: every application, filterable by tier, vacancy and stage',
      'Messages: conversations with applicants',
    ],
    tasks: [
      'Post a role: tap "Post vacancy", fill each step with "Continue" (or "Save Draft"), then "Publish Job Listing".',
      'Move a candidate on: open the application and tap "Shortlist", then "Schedule interview", "Make offer" and "Hire & onboard".',
      'Turn someone down: open the application and tap "Reject"; "Reinstate to New" undoes it.',
      'Publish a draft: open "Draft", open the vacancy, tap "Publish".',
    ],
    who: '',
    records: '',
    mate: 'Can draft a vacancy (create_vacancy) after confirming; cannot publish it, move candidates or message them, gives the steps.',
    suggestions: ['Write a vacancy for an Approved Electrician', 'How do I shortlist a candidate?', 'Where are my drafts?'],
  },
];

const PAGES_B = [
  {
    key: 'financehub',
    title: 'Finance',
    area: 'Finance',
    what: 'The money landing page: Outstanding, Overdue, Cash in over 30 days and Open quotes at the top, then cards for every finance page. Outstanding is the unpaid balance of sent and overdue invoices, never drafts.',
    tabs: [],
    tasks: [
      'See who owes you: tap "Outstanding £" or "Overdue £", which open Quotes & Invoices.',
      'Find a finance page: tap a card, for example "Quotes & Invoices", "Accounts", "Reports", "Job Financials", "Expenses", "Purchase orders", "Signatures", "Price Book" or "Accounting".',
      'Check the accounting link: the "Accounting" card says "Not connected", "needs reconnecting", how many invoices failed, or "Connected to" the package.',
    ],
    who: 'Owner/admin: everything. Office: the Accounts and Job Financials cards show "Owner and admins only" instead of profit.',
    records: '',
    mate: 'Can answer questions about the pages and draft a quote or invoice (create_quote, create_invoice); cannot send anything or sync to Xero or QuickBooks.',
    suggestions: ['How much are we owed?', 'Which page shows job profit?', 'Is Xero connected?'],
  },
  {
    key: 'quotes',
    title: 'Quotes & Invoices',
    area: 'Finance',
    what: 'Every quote and invoice in one list, newest first, with Outstanding, Cash in over 30 days, Open quotes and Won this month at the top. Overdue invoices show days overdue and a Chase button.',
    tabs: ['All: quotes and invoices together', 'Quotes: quotes only', 'Invoices: invoices only', 'Overdue: unpaid invoices past their due date, with an Aging breakdown'],
    tasks: [
      'Write a quote: tap "New quote", fill it in, save, then open it and tap "Send email" to send it with an accept/decline link.',
      'Turn a won quote into an invoice: open the quote (Approved or Customer accepted) and tap "Convert to invoice".',
      'Chase a late payment: open the Overdue tab and tap "Chase" on the row. If no email is on file, enter one and tap "Send reminder".',
      'Record a payment: open the invoice and tap "Mark paid".',
    ],
    who: 'Owner, admin and office can all create, send and chase. Rows tagged "Electrical Hub" are read-only here and edited in that hub.',
    records: '?quote=<id> or ?invoice=<id> opens that record; ?tab=overdue picks a tab; ?job=<id> shows only that job\'s quotes and invoices; ?new=quote&client=... opens a prefilled new quote.',
    mate: 'Can read the open quote or invoice (get_page_record) and create a draft quote or invoice (create_quote, create_invoice); cannot send, chase or mark paid, gives the steps.',
    suggestions: ['How do I chase an overdue invoice?', 'How do I turn a quote into an invoice?', 'Can you draft a quote?'],
  },
  {
    key: 'accounts',
    title: 'Accounts',
    area: 'Finance',
    what: 'Profit and loss and a ledger of money in and out for a chosen period, matching Reports and Job financials. Gross profit is invoiced less costs (materials, supplier invoices, expenses, labour, other job costs).',
    tabs: ['Profit & loss: invoiced, costs, gross profit, margin and cash', 'Ledger: every payment in and cost out for the period'],
    tasks: [
      'Pick a period: tap "This month", "Last month", "This quarter", "This year", "Last 12 months" or "All time".',
      'Export for your accountant: tap "P&L CSV", "Ledger CSV" or "PDF".',
      'See what came in and went out: open "Ledger" for money in, money out and net cash.',
    ],
    who: 'Owner/admin only. Office sees "Accounts are for the owner and admins" and should use Quotes & Invoices for what is outstanding.',
    records: '',
    mate: 'Can explain the figures and how they are worked out; cannot read the P&L or ledger, so points the user to the page and exports.',
    suggestions: ['Why is gross profit different to cash in?', 'How do I export for my accountant?', 'What counts as labour cost?'],
  },
  {
    key: 'tenders',
    title: 'Tenders',
    area: 'Finance',
    what: 'Public sector bid opportunities and your own bid pipeline, with Open, Bidding and Won this year figures. Discover searches 20+ UK sources by postcode.',
    tabs: ['Open: tenders you are working on', 'Bidding: submitted bids awaiting a result', 'Closed: won, lost and withdrawn'],
    tasks: [
      'Find opportunities: tap "Discover", enter a postcode, search, open one and tap "Start tender".',
      'Track a bid by hand: tap "Track tender" and fill in the details.',
      'Get an AI estimate: open an Open tender, tap "AI estimate", add drawings, specs or BOQs, then tap "Generate estimate".',
      'Move a bid along: open it and tap "Mark submitted", then "Won" or "Lost". On a won tender tap "Convert to job".',
      'Bring one back: open a lost or withdrawn tender and tap "Reopen tender".',
    ],
    who: '',
    records: '',
    mate: 'Can explain the pipeline and steps; has no tender tools, so cannot create or update tenders.',
    suggestions: ['How do I find local tenders?', 'How do I turn a won tender into a job?', 'What does AI estimate do?'],
  },
  {
    key: 'expenses',
    title: 'Expenses',
    area: 'Finance',
    what: 'Receipts and mileage the team claims back. You approve or reject them, then pay approved claims in a pay run.',
    tabs: ['All: every claim', 'To approve: waiting for a decision', 'To pay: approved, not yet paid', 'Paid: reimbursed', 'Rejected: turned down', 'Mileage: mileage claims'],
    tasks: [
      'Approve a claim: open "To approve", tap the claim, check the receipt, tap "Approve" or "Reject" and give a reason.',
      'Pay approved claims: tap "Pay", set "Paid on", tick the claims, tap "Export" if needed, then "Mark N paid".',
      'Change the mileage rate: tap the mileage rate line above the list ("Change") and save. Default is the HMRC rate, 45p a mile then 25p after 10,000 miles.',
      'Export the list: tap the export icon for a CSV.',
    ],
    who: 'Owner/admin: everything, including setting the mileage rate. Others see the rate but cannot change it.',
    records: '?expense=<id> opens that claim.',
    mate: 'Can list claims awaiting approval (get_pending_approvals) and read the open claim (get_page_record). With a confirmation card it can approve or reject a claim (decide_expense, rejecting needs a reason) and, for the owner or an admin only, mark approved claims paid (mark_expenses_paid). Cannot export or change the mileage rate, gives the steps.',
    suggestions: ['Who has expenses waiting?', 'How do I pay approved claims?', 'What mileage rate do we pay?'],
  },
  {
    key: 'procurement',
    title: 'Purchase orders',
    area: 'Finance',
    what: 'Order materials for a job, book deliveries in and check the supplier\'s invoice against the order. Shows Awaiting delivery, Due today and Late counts.',
    tabs: ['Orders: purchase orders', 'Suppliers: the merchants you buy from'],
    tasks: [
      'Raise an order: tap "Raise an order" (or "Order materials" from a job), add lines, save as a draft, then open it and tap "Send to <supplier>".',
      'Book a delivery in: open the order, tap "Book a delivery in", set what arrived, add the delivery note, then tap "Book in".',
      'Check the supplier invoice: open the order and tap "Match the invoice (PDF or photo)". Overcharges and short deliveries are flagged.',
      'Add suppliers: open Suppliers and tap "Add supplier" or "Add the big UK merchants". An order email is needed before an order can be sent.',
      'Cancel an order: open it, tap "Cancel this order", then "Cancel order".',
    ],
    who: 'Owner/admin: everything. Office: can track orders, book deliveries in and add suppliers, but cannot raise or send orders and never sees prices or supplier invoices.',
    records: '?job=<id> shows only that job\'s orders; ?order=1 opens a new order straight away.',
    mate: 'Can draft a purchase order (create_purchase_order, never sends), add a supplier (add_supplier) and look up prices (get_material_prices); cannot send orders or book deliveries.',
    suggestions: ['How do I send an order to a supplier?', 'How do I book a delivery in?', 'Can you draft an order for this job?'],
  },
  {
    key: 'financials',
    title: 'Job Financials',
    area: 'Finance',
    what: 'Profit per job: invoiced against labour, materials, expenses and other costs, with budget alongside. Labour is approved hours times each person\'s cost rate.',
    tabs: ['All: every job', 'Invoiced: jobs with an invoice', 'Losing money: forecast profit below zero', 'Over budget: costs above budget', 'Over quoted hours: hours above the quote'],
    tasks: [
      'See a job\'s profit: tap the job to open "Job profit" with value, costs, invoices and the cost log.',
      'Add a cost: open the job and tap "Record cost".',
      'Correct labour: open the job and tap "Labour", give a reason. The change is logged.',
      'Add a variation: open the job, tap "Add variation", enter the description and value, then "Add variation". Tap "Approve" on a pending one to add it to contract value.',
      'Set cost rates: tap "Cost rates" at the top.',
    ],
    who: 'Owner/admin only. Office sees "Job profit is for the owner and admins".',
    records: '?job=<id> opens that job\'s profit sheet.',
    mate: 'Can explain how profit is worked out and read the job (get_page_record); cannot record costs or approve variations, gives the steps.',
    suggestions: ['Which jobs are losing money?', 'How is labour cost worked out?', 'How do I add a variation?'],
  },
  {
    key: 'reports',
    title: 'Reports',
    area: 'Finance',
    what: 'Invoiced, costs and gross profit for a period with charts, debtor aging, job profitability, expenses by category, compliance status, jobs by status and busiest team members. Same figures as Accounts.',
    tabs: ['This month', 'Last month', 'This quarter', 'This year', 'Last 12 months', 'All time'],
    tasks: [
      'Change the period: tap a period chip at the top.',
      'Export the P&L: tap "Export CSV".',
      'See who owes money: scroll to "Debtor aging", bucketed by how late invoices are.',
      'Drill into a job: tap a job under "Job profitability" to open it in Job Financials.',
    ],
    who: 'Owner/admin: everything. Office sees invoiced, cash in, outstanding and overdue only; costs, profit, job profitability and expenses are hidden and Export CSV is off.',
    records: '',
    mate: 'Can explain each figure and where it comes from; cannot run reports itself.',
    suggestions: ['What is debtor aging?', 'Why does margin show a dash?', 'How do I export this month?'],
  },
  {
    key: 'signatures',
    title: 'Signatures',
    area: 'Finance',
    what: 'Every document clients have been asked to sign: quotes, variations, handovers and certificates. The client signs the actual document on their phone, and you keep a signed copy with an audit record.',
    tabs: ['Waiting: sent or opened, not signed', 'Signed: signed', 'Declined: turned down', 'Expired or cancelled: dead links', 'All: everything'],
    tasks: [
      'Ask for a signature: tap "Request signature", pick Quote, Variation, Handover or Certificate, choose the document, add the signer, then tap "Send for signature" (or "Create signing link" with no email).',
      'Chase it: open the request and tap "Chase by email", or "Copy link" or "Share" to text it.',
      'Get the proof: open a signed request and tap "Download signed copy".',
      'Apply a signed variation: open it and tap "Add <amount> to job value".',
      'Stop a link: open it, tap "Cancel this link", then "Cancel link".',
    ],
    who: '',
    records: '?request=<id> opens that request; ?job=<id> shows only that job\'s requests.',
    mate: 'Can read the open signature request (get_page_record) and, with a confirmation card, email the signer a reminder (chase_signature; once a day, six emails at most). Cannot create, cancel or apply requests, gives the steps.',
    suggestions: ['Has the client signed yet?', 'How do I chase a signature?', 'How do I add a variation to the job?'],
  },
  {
    key: 'pricebook',
    title: 'Price book',
    area: 'Finance',
    what: 'One price list for quotes and orders, shared with the owner\'s Electrical Hub price book, so a change here changes there too. Items needing a check have no sell price, an old price (over 60 days) or were paid above book.',
    tabs: ['Items: the price list', 'Labour & markup: day and hourly rates and default markup (office sees "Labour rates")'],
    tasks: [
      'Add an item: tap "Add item", fill in name, unit, prices, then "Add to price book".',
      'Import a merchant list: tap "Import", choose a CSV or Excel file, then tap "Import N items".',
      'Fix stale prices: tap "Needs a check" and update each item, then "Save changes".',
      'Set labour rates: open "Labour & markup", enter the day and hourly rates, tap "Save rates".',
    ],
    who: 'Owner: everything, and only the owner can change rates. Admin: sees buy prices and markup. Office: sell prices only, never buy price, markup or last paid.',
    records: '',
    mate: 'Can add a price book item (add_price_book_item) and look up material prices (get_material_prices); cannot edit or remove items it did not add.',
    suggestions: ['Can you add an item to the price book?', 'Why does this item need a check?', 'How do I import a price list?'],
  },
  {
    key: 'accounting',
    title: 'Accounting',
    area: 'Finance',
    what: 'The firm\'s Xero, QuickBooks or Sage connection (the same one as the owner\'s Electrical Hub). Invoices sync live into your books; payroll is a file built from approved hours, expenses and mileage.',
    tabs: ['Need attention: invoices that failed or are not sent yet', 'All sent: every sent invoice and its sync state'],
    tasks: [
      'Connect: tap "Xero", "QuickBooks" or "Sage" and sign in on their page. If it says "Signed out", "Needs reconnecting" or "Not working", tap "Reconnect <package>".',
      'Fix an unsynced invoice: open "Need attention". "Failed" shows the reason (expired connection, sales account code, contact, VAT, package busy); fix it, tap "Try again". "Not sent yet" means sent since connecting but not across: tap "Sync now", or "Sync N now". "From before connecting" is not flagged.',
      'Auto sync: turn on "Send invoices to <package> when they are emailed". Off means only "Sync now" sends them.',
      'Run payroll: pick "Last period" or "This period", choose the file type, tap "Send to payroll", check it, then "Send and save the file". Entries still waiting approval go next time.',
      'Undo a run: tap "Undo" within 48 hours, or "Save again" for the file.',
    ],
    who: 'Owner/admin: connect, sync, set the pay period, full pay files. Only the owner has "Account codes and disconnect". Office: sees connection state and counts, sends hours-only payroll files.',
    records: '?accounting=<provider>&success=true or ?accounting_error=... after returning from the sign-in page.',
    mate: 'Can explain sync states and errors and list hours awaiting approval (get_pending_approvals); cannot sync to Xero or QuickBooks or run payroll, gives the exact taps.',
    suggestions: ['Why has this invoice not synced?', 'How do I reconnect Xero?', 'How do I send hours to payroll?'],
  },
];

const PAGES_C = [
  {
    key: 'jobshub',
    title: 'Jobs',
    area: 'Jobs',
    what: 'The Jobs hub: live counts (Active jobs, Today, Issues, Completed 7d) and a card for every operations page, from Job Packs and Diary to Fleet, Kit register, Purchase orders and Job Financials.',
    tabs: [],
    tasks: [
      'Start a new job: tap the "Jobs" card, then "New job".',
      'See who is where this week: tap the "Diary" card.',
      'Check open problems: tap the "Issues" count at the top, or the "Issues" card.',
      'Countersign certificates: tap the "QS Reviews" card.',
    ],
    who: 'Owner/admin: everything, including the Job Financials card with profit figures. Office: the Job Financials card shows "Owner and admins only" and no money.',
    records: '',
    mate: 'Can create a job (create_job) or a job pack (create_job_pack) after confirming, and read safety and sign-off status; otherwise points to the right card.',
    suggestions: ['Where do I start a new job?', 'Which jobs are on today?', 'Where do I countersign certs?'],
  },
  {
    key: 'jobpacks',
    title: 'Job Packs',
    area: 'Jobs',
    what: 'Scope, hazards, crew and documents bundled per job: AI RAMS, method statement and briefing pack, sent to the assigned workers for sign-off.',
    tabs: ['All: every pack', 'Draft: not sent yet', 'Sent: with workers for sign-off', 'Signed: all signed off'],
    tasks: [
      'Make a pack: tap "New pack", pick the job, fill the scope and crew, tap "Create pack". Or tap a job under "Jobs awaiting pack".',
      'Generate the documents: tap "Generate" on the pack (or open it and go to the "Docs" tab) and generate RAMS, Method statement and Briefing pack.',
      'Send to the crew: once Docs shows 3/3 and workers are assigned, tap "Send" on the row, or open the pack, "Send" tab, "Send to workers".',
      'Check sign-offs: open the pack and go to the "Send" tab to see who has acknowledged.',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s packs and offers to create one if it has none.',
    mate: 'Can create a job pack (create_job_pack) after confirming and show who has not signed (who_has_not_signed); cannot generate documents or send the pack, gives the steps.',
    suggestions: ['Who has not signed this pack?', 'Why can I not send this pack?', 'Make a job pack for this job'],
  },
  {
    key: 'jobs',
    title: 'Jobs',
    area: 'Jobs',
    what: 'Every job with its client, location, dates, workers and signals like incidents, overdue invoices or expiring certs. Tap a job to open its sheet, the centre for everything on that job.',
    tabs: ['All: every job', 'Active: running now', 'Pending: not started', 'On hold: paused', 'Completed: finished'],
    tasks: [
      'Add a job: tap "New job", fill it in, tap "Create job".',
      'Book people on: open the job, on Assigned workers tap "Assign" and pick the team.',
      'Change status or dates: open the job, tap "Edit job", change Status, save.',
      'Reuse a job: open it, tap the "More" menu, then "Copy job" or "Save as template".',
      'Jump to the job\'s records: use the shortcuts on the job sheet (Quotes, Invoices, RAMS & packs, Hours, Photos, Snags, Issues, Testing, Client sign-off).',
    ],
    who: 'Owner/admin: see job value, the Value (£) field and the Financials shortcut. Office: no job values, profit or Financials shortcut.',
    records: 'URL ?job=<id> opens that job\'s sheet.',
    mate: 'Can create a job (create_job) or add a task (add_task) after confirming, and read the open job (get_page_record); cannot edit or delete existing jobs, gives the steps.',
    suggestions: ['How do I assign someone to this job?', 'Why is this job flagged?', 'How do I copy a job?'],
  },
  {
    key: 'jobboard',
    title: 'Job Board',
    area: 'Jobs',
    what: 'A kanban of every job by stage: Enquiry, Quoted, Confirmed, Scheduled, In progress, Testing, Complete and On hold. Moving a card updates the job\'s status.',
    tabs: [],
    tasks: [
      'Move a job on: drag its card to the next column, or use the move menu on the card.',
      'Quick add: tap "Add job" at the bottom of a column, enter the job title and client, tap "Add job".',
      'Tidy the view: tap "Filters" and tick "Hide completed jobs", or switch to List view.',
      'Find old work: tap "Templates" or "Archived".',
    ],
    who: 'Owner/admin: see job values and the pipeline value per column. Office: no money shown.',
    records: '',
    mate: 'Can create a job (create_job) after confirming; cannot move a job between stages, gives the steps.',
    suggestions: ['How do I move a job to Scheduled?', 'How do I hide completed jobs?', 'Where are archived jobs?'],
  },
  {
    key: 'diary',
    title: 'Diary',
    area: 'Jobs',
    what: 'Who is where this week. Book people onto jobs by day, see clashes and jobs with nobody on them, and push the changes to workers\' My week.',
    tabs: [],
    tasks: [
      'Book someone: on desktop drag a job onto a person and day; on a phone tap a day, tap the job or person, then "Book".',
      'Move or remove a booking: tap it, change the dates and tap "Save", or tap "Take off" then "Yes, take off".',
      'Repeat a week: tap "Copy last week".',
      'Send changes now: tap "Send now" on the banner, otherwise they go about a minute after your last change.',
      'Book won work with no date: use the "To schedule" tray at the bottom.',
    ],
    who: '',
    records: '',
    mate: 'Can list the team (list_team) and a worker\'s on-site status (get_team_member), and with a confirmation card book someone on a job for given dates (book_person_on_job): the card shows clashes (leave, double-booking, over a working day) first, and a new booking can be undone for 15 minutes. Cannot move or copy weeks, gives the steps.',
    suggestions: ['How do I book someone on a job?', 'What does a red booking mean?', 'How do I copy last week?'],
  },
  {
    key: 'timeline',
    title: 'Timeline',
    area: 'Jobs',
    what: 'Every booked job as a bar across a week, month or quarter, plus team availability. Moving a job moves everyone on it, and the Diary shows the same dates.',
    tabs: ['Week: this week', 'Month: this month', 'Quarter: three months'],
    tasks: [
      'Move a job: on desktop drag the bar, or drag its right edge to change length. On phone or tablet tap the job, change Starts and Ends, tap "Save dates".',
      'Step through time: use "Prev", "Today" and "Next".',
      'Spot slippage: check the "Running late" count.',
    ],
    who: 'Owner/admin: job values on the Jobs list. Office: no values.',
    records: '',
    mate: 'Can read the open job (get_page_record); cannot change dates, gives the steps.',
    suggestions: ['How do I move a job\'s dates?', 'Which jobs are running late?', 'Who is free next week?'],
  },
  {
    key: 'tracking',
    title: 'Worker Tracking',
    area: 'Jobs',
    what: 'Live GPS, check-ins and location history: who is On site, Travelling, in the Office, Off duty or On leave, in a list or on a live map.',
    tabs: ['All', 'On site', 'Travelling', 'Office', 'Off duty', 'On leave'],
    tasks: [
      'Check someone in: tap the check-in button, choose the worker and job, tap "Check in to site".',
      'End a forgotten shift: tap "Check out" on the worker\'s row.',
      'Message a worker: tap the message icon on their row, type, tap "Send message". It lands in their Worker Tools with a push.',
      'See the map: switch to Map view.',
    ],
    who: '',
    records: '',
    mate: 'Can say whether a worker is on site (get_team_member) and list the team (list_team); cannot check people in or out or send messages, gives the steps.',
    suggestions: ['Who is on site right now?', 'How do I check someone out?', 'How do I message a worker?'],
  },
  {
    key: 'progresslogs',
    title: 'Progress Logs',
    area: 'Jobs',
    what: 'Time-stamped daily progress per job with work completed, materials, notes and photo evidence, plus notes "From the team".',
    tabs: ['Today', 'This week', 'This month', 'All'],
    tasks: [
      'Log a day: tap "New log", pick the job and date, describe the work, add photos, tap "Create progress log".',
      'Sign a log off: open it and tap "Sign off log".',
      'Go to the job: open the log and tap "View job".',
      'Remove a mistake: open the log, tap "Delete log".',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s logs.',
    mate: 'Can read the open job (get_page_record); cannot create or sign off logs, gives the steps.',
    suggestions: ['How do I add a progress log?', 'How do I sign off a log?', 'What did the team log today?'],
  },
  {
    key: 'issues',
    title: 'Issues',
    area: 'Jobs',
    what: 'Problems, blockers and escalations across all jobs: snags, variations, RFIs, defects and delays, with severity, owner and due date.',
    tabs: ['All', 'Open', 'Critical / High', 'In progress', 'Resolved'],
    tasks: [
      'Report one: tap "Report issue", pick the job, add a title, type, severity, who it is assigned to and photos, tap "Report issue".',
      'Close one: open it, tap "Resolve issue", add resolution notes, tap "Mark as resolved". Or swipe the row to "Resolve".',
      'Change status: open it and use "Update status".',
      'Charge for a variation: open a Variation issue and tap "Price it and get the client to sign".',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s issues.',
    mate: 'Can add a task (add_task) after confirming and read the open job (get_page_record); cannot create or resolve issues, gives the steps.',
    suggestions: ['How do I report an issue?', 'What is still critical?', 'How do I bill a variation?'],
  },
  {
    key: 'testing',
    title: 'Testing Workflow',
    area: 'Jobs',
    what: 'Electrical test records grouped by job: circuit, test type, inspector, instrument, reading and result, with a signed sign-off for each result.',
    tabs: ['All', 'Pending', 'Passed', 'Failed'],
    tasks: [
      'Add a test: tap "New test", pick the job and test type, add circuit, inspector and instrument, tap "Create test record".',
      'Record a result: tap "Record" on a pending test, choose the result, add the reading, confirm.',
      'Sign a result off: open the test, tap "Sign off result", sign, tap "Confirm sign-off".',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s tests.',
    mate: 'Can look up regulations and test limits (search_bs7671) and read the open job (get_page_record); cannot record or sign off results, gives the steps.',
    suggestions: ['How do I record a test result?', 'What is the IR limit for this circuit?', 'How do I sign off a test?'],
  },
  {
    key: 'quality',
    title: 'Quality & Snags',
    area: 'Jobs',
    what: 'Snags and defects per job with photo evidence and resolution records, so every site is ready for sign-off.',
    tabs: ['All', 'Open', 'In progress', 'Resolved'],
    tasks: [
      'Log a snag: tap "Log snag", pick the job, add a title, location, severity and photos, tap "Create snag".',
      'Close a snag: open it, tap "Mark resolved", say what was done, tap "Confirm resolved".',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s snags.',
    mate: 'Can read the open job (get_page_record); cannot log or resolve snags, gives the steps.',
    suggestions: ['How do I log a snag?', 'How do I close a snag?', 'What snags are still open?'],
  },
  {
    key: 'qsreviews',
    title: 'QS Reviews',
    area: 'Jobs',
    what: 'Qualifying Supervisor sign-off for EICR, EIC and Minor Works certificates the team submits. Approving adds the countersignature to the PDF.',
    tabs: ['Awaiting review: certs waiting for sign-off', 'All reviews: every review and its outcome', 'Team Certificates: all certificates from the team'],
    tasks: [
      'Countersign: open the cert, check it (tap "View PDF"), tap "Approve & countersign", enter your name and signature, tap "Confirm approval".',
      'Send it back: open the cert, tap "Return with comments", say what needs changing, tap "Return certificate".',
      'Export the record: on "All reviews" tap "Export register. Assessment-ready".',
      'No QS yet: tap "Set up your team" and give someone the QS role.',
    ],
    who: 'Only a QS or the owner/admin can sign certificates. Team Certificates is hidden from team members who are not the principal QS.',
    records: 'URL ?review=<id> opens that review.',
    mate: 'Can read the open review (get_page_record) and check regulations (search_bs7671); cannot approve or return certificates, gives the steps.',
    suggestions: ['How do I countersign this cert?', 'How do I send a cert back?', 'Who can sign certificates?'],
  },
  {
    key: 'fleet',
    title: 'Fleet',
    area: 'Jobs',
    what: 'The firm\'s vans: who drives them, MOT, tax, insurance and service dates, daily checks, documents and fuel logs.',
    tabs: ['All', 'Active', 'Maintenance', 'Off road'],
    tasks: [
      'Add a van: tap "Add vehicle", enter the registration, make and model, assign a driver, tap "Add vehicle".',
      'Log fuel: tap "Log fuel", pick the vehicle, enter litres, cost and mileage, tap "Log fuel".',
      'Run a daily check: open the vehicle and tap "Daily check".',
      'Update a van: open it and tap "Edit vehicle", or "Remove vehicle".',
    ],
    who: '',
    records: '',
    mate: 'No fleet tools; gives the steps.',
    suggestions: ['Which vans have an MOT due?', 'How do I log fuel?', 'How do I add a van?'],
  },
  {
    key: 'kit',
    title: 'Kit register',
    area: 'Jobs',
    what: 'Company tools and testers, who has them, and when PAT and calibration are due. A failed test marks the item Under repair until it is re-tested.',
    tabs: ['All', 'Due soon', 'Overdue', 'Under repair'],
    tasks: [
      'Add kit: tap "Add kit" and enter the item, with the serial number for testers.',
      'Log a test: open the item, under "Log a test" choose "PAT test" or "Calibration", the result and date, tap "Log PAT test" or "Log calibration".',
      'Find what is due: tap the "Overdue" or "Due in 30 days" count.',
    ],
    who: 'Owner/admin: see the purchase price. Office: no prices.',
    records: '',
    mate: 'No kit tools; gives the steps.',
    suggestions: ['What kit is overdue?', 'How do I log a calibration?', 'Why is this tester under repair?'],
  },
  {
    key: 'photogallery',
    title: 'Photo Gallery',
    area: 'Jobs',
    what: 'Every photo from every job in a grid, timeline, map or before and after view. Photos can be approved and shared with the client.',
    tabs: ['Grid', 'Timeline', 'Map', 'Compare: before and after slider'],
    tasks: [
      'Add photos: tap "Upload" and pick the job.',
      'Approve or share: open a photo and tap "Approve" or "Share with Client".',
      'Show before and after: open "Compare". It needs Before and After photos on the same job.',
      'Narrow down: tap the filter button to filter by job, approved or shared.',
    ],
    who: '',
    records: 'URL ?job=<id> shows only that job\'s photos.',
    mate: 'Can read the open job (get_page_record); cannot upload, approve or share photos, gives the steps.',
    suggestions: ['How do I share photos with the client?', 'How do I upload photos?', 'How does Compare work?'],
  },
];

const PAGES_D = [
  {
    key: 'safetyhub',
    title: 'Safety',
    area: 'Safety',
    what: 'The Safety hub: headline counts (Open incidents, Pending RAMS, Policies, Training due) and cards into every safety page, plus the Job Safety Pack for proving a site is ready to a principal contractor.',
    tabs: [],
    tasks: [
      'Prove a site is ready: tap the "Job Safety Pack" card ("Build pack"), choose the job, then check Crew competence, RAMS, Briefings & toolbox talks and Compliance documents for that job.',
      'Clear what needs attention: tap the "Open incidents" or "Pending RAMS" figure, or the "Safety alerts" card, to jump to the items waiting.',
      'Check renewals: tap "Training due" or the "Training Records" card to see expired or due tickets.',
    ],
    who: '',
    records: '',
    mate: 'Can give the firm safety picture (get_safety_overview), open incidents (list_safety_incidents), unsigned RAMS and job packs (who_has_not_signed), overdue actions (list_overdue_safety_actions) and expiring tickets (list_expiring_tickets).',
    suggestions: ['What needs attention on safety?', 'Who has not signed the RAMS?', 'Whose tickets are expiring?'],
  },
  {
    key: 'safety',
    title: 'Health & Safety',
    area: 'Safety',
    what: 'Safety alerts: the latest incidents and RAMS waiting for sign-off in one list, with a Snapshot of Total incidents, Critical, Total RAMS and Approved RAMS.',
    tabs: [],
    tasks: [
      'Deal with an alert: tap the row under "Recent alerts". Incident rows open Incidents, RAMS rows open RAMS.',
      'Refresh the list: tap the refresh button at the top.',
    ],
    who: '',
    records: '',
    mate: 'Can list open incidents (list_safety_incidents), RAMS awaiting sign-off (who_has_not_signed) and the overall picture (get_safety_overview).',
    suggestions: ['What alerts are open right now?', 'Which RAMS need signing off?', 'Any critical incidents?'],
  },
  {
    key: 'rams',
    title: 'RAMS',
    area: 'Safety',
    what: 'Risk assessments and method statements for every job: write one yourself or generate it with AI, link it to a job, and move it through Draft, Submitted, Approved or Rejected.',
    tabs: ['All: every RAMS', 'Active: in use', 'Draft: work in progress', 'Approved: signed off'],
    tasks: [
      'Write a RAMS: tap "New RAMS", fill Project name, Location and Assessor, optionally "Link job" and add Work activities, then tap "Create RAMS".',
      'Generate with AI: tap "Generate AI" to open the AI RAMS builder.',
      'Approve or reject: open the RAMS, then under "Update status" tap "Mark Approved" or "Mark Rejected".',
      'Share the document: open it and tap "Download PDF" or "Copy PDF link" (only shown once a PDF exists).',
      'Link to a job later: open the RAMS and pick the job under "Link to a job".',
    ],
    who: '',
    records: '',
    mate: 'Can say who has not signed RAMS (who_has_not_signed) and give the safety overview (get_safety_overview); cannot create or approve RAMS, gives the steps.',
    suggestions: ['How do I approve a RAMS?', 'Who has not signed this RAMS?', 'How do I make one with AI?'],
  },
  {
    key: 'incidents',
    title: 'Incidents',
    area: 'Safety',
    what: 'Near misses and incidents from site: log them, record the RIDDOR decision, investigate the root cause, set actions with owners and dates, then close the report.',
    tabs: ['New: nobody has looked at it yet', 'Open: not closed', 'Closed: finished reports', 'All: everything'],
    tasks: [
      'Log an incident: tap "Report incident", choose the kind and job, fill in what happened, then tap "Log report".',
      'Record RIDDOR: open the report, make the RIDDOR decision, and if reportable use "HSE form", then enter Date reported and HSE reference and tap "I have reported it".',
      'Investigate: open the report, fill Root cause and Investigation notes, tap "Save investigation".',
      'Set fixes: under "What will change" type a New action, pick Owner and Due, tap "Add action". Owners on the app are told straight away.',
      'Close it: fill "What was done" and tap "Close report". Use "Report PDF" or "RIDDOR PDF" for a copy.',
    ],
    who: '',
    records: '?incident=<id> opens that report. ?new=incident opens the report form.',
    mate: 'Can read the open report (get_page_record), list incidents (list_safety_incidents) and overdue actions (list_overdue_safety_actions); cannot edit or close reports, gives the steps.',
    suggestions: ['Is this incident RIDDOR reportable?', 'Which actions are overdue?', 'How do I close this report?'],
  },
  {
    key: 'policies',
    title: 'Policies',
    area: 'Safety',
    what: 'Your company policy library: adopt ready-made templates, put your company name in, edit them and track review dates.',
    tabs: ['Active: adopted policies', 'Templates: ones you have not adopted yet', 'Review due: policies past their review date'],
    tasks: [
      'Adopt a policy: tap "Browse templates", open a template, tap "Adopt This Policy", optionally enter Company Name, then "Confirm Adoption".',
      'Edit a policy: open it from Active and tap "Edit Policy".',
      'Get a copy: open the policy and tap "Export PDF".',
    ],
    who: '',
    records: '',
    mate: 'Can search the firm knowledge (search_employer_knowledge) to answer what a policy says; cannot adopt or edit policies, gives the steps.',
    suggestions: ['Which policies do I need?', 'How do I adopt a template?', 'Which policies are due a review?'],
  },
  {
    key: 'contracts',
    title: 'Contracts',
    area: 'Safety',
    what: 'Employment, subcontractor and HR letter templates, plus the contracts you have made from them, with e-signature for employer and employee.',
    tabs: ['All: your contracts', 'Active: in force', 'Draft: not live yet', 'Expired: expired or terminated', 'Templates: Employment, Subcontractor and HR letters'],
    tasks: [
      'Make a contract: tap "New from template", open a template, tap "Use This Template", fill the details, then "Create Contract".',
      'Sign as the firm: open the contract, tap "Sign as employer", enter your name and signature, tap "Sign contract".',
      'Get the other party to sign: open it, tap "Send for signature", enter Signer name and Email (or leave email blank for a link), then "Send request" or "Create signing link".',
      'Change status: open the contract, tap "Edit" and set Contract status.',
    ],
    who: '',
    records: '',
    mate: 'Cannot create, send or sign contracts; gives the steps.',
    suggestions: ['How do I send a contract to sign?', 'Which contracts end soon?', 'Which template for a subcontractor?'],
  },
  {
    key: 'training',
    title: 'Training Records',
    area: 'Safety',
    what: 'The firm training matrix: courses, certifications and CPD for each team member with expiry tracking.',
    tabs: ['All: every record', 'Valid: in date', 'Expiring: due within 30 days', 'Expired: out of date'],
    tasks: [
      'Log training: tap "Log training", enter Training name, type, Provider, Employee and dates, then "Log training".',
      'Mark it done: open the record and tap "Mark complete".',
      'Print the matrix: tap "Export matrix".',
    ],
    who: 'Records a worker added on their own Elec-ID are read-only here: they keep them up to date.',
    records: '',
    mate: 'Can list expiring or expired tickets across the team (list_expiring_tickets) and one worker\'s details (get_team_member).',
    suggestions: ['Whose tickets expire this month?', 'How do I log a course?', 'Can I print the training matrix?'],
  },
  {
    key: 'briefings',
    title: 'Briefings',
    area: 'Safety',
    what: 'Toolbox talks, site inductions and safety briefings: schedule them, run sign-off on the day (in person or by QR) and export a signed PDF.',
    tabs: ['All: every briefing', 'Live: scheduled, not finished', 'Completed: delivered'],
    tasks: [
      'Schedule a briefing: tap "New briefing", fill Title, type, Date, Repeat, Presenter and "Link job (optional)", then tap "Schedule".',
      'Use a ready-made talk: tap "Templates" and pick one from the toolbox talk library.',
      'Get sign-offs: open the briefing and tap "Sign-Off" to add team or guests, or tap "QR" or "Copy Link" for people to sign on their phones.',
      'Keep a record: open the briefing and tap "Export PDF".',
    ],
    who: '',
    records: '',
    mate: 'Can give the safety overview (get_safety_overview); cannot schedule or sign briefings, gives the steps.',
    suggestions: ['How do I get the crew to sign?', 'Is there a toolbox talk template?', 'How do I make it repeat weekly?'],
  },
  {
    key: 'compliance',
    title: 'Compliance',
    area: 'Safety',
    what: 'Insurance renewals, PAT, calibration and audit documents with expiry dates, a renewal calendar and an audit trail.',
    tabs: ['All', 'Insurance', 'PAT', 'Calibration', 'Audits'],
    tasks: [
      'Add a document: tap "Add document", enter a Title, category and renewal date, optionally link an employee or job and attach the file, then tap "Add document".',
      'Record a renewal: open the document, tap "Edit / record renewal", update the date, attach the new file.',
      'See what is due: check "Compliance Calendar" and "Renewal Reminders" (Overdue, Due in, Renews).',
    ],
    who: '',
    records: '',
    mate: 'Can give the safety overview (get_safety_overview); cannot add or edit documents, gives the steps.',
    suggestions: ['What is overdue for renewal?', 'How do I record our new insurance?', 'Where do PAT records go?'],
  },
  {
    key: 'clientshub',
    title: 'Clients',
    area: 'Clients',
    what: 'The Clients hub: from enquiry to repeat business. Counts for Clients, Outstanding, Open quotes and Paid to date, and cards into Quote Page, Leads, Clients, Quotes & Invoices, Tenders and Client Portal.',
    tabs: [],
    tasks: [
      'Get more enquiries: tap "Quote Page" to set up your branded page and QR.',
      'Chase new work: tap "Leads" to work enquiries through to won.',
      'Find a customer: tap "Clients" to see their jobs, quotes, invoices and balance.',
      'Give a client their own page: tap "Client Portal".',
    ],
    who: '',
    records: '',
    mate: 'Can draft a quote (create_quote) or invoice (create_invoice) after confirming; cannot send them.',
    suggestions: ['How do I get more enquiries?', 'Who owes us money?', 'How does the client portal work?'],
  },
  {
    key: 'clients',
    title: 'Clients',
    area: 'Clients',
    what: 'Every customer in one place with their quotes, invoices, jobs, certificates, follow-ups, reviews, portal link and messages.',
    tabs: [],
    tasks: [
      'Add a client: tap "Add client", enter Client name and contact details, then save.',
      'Start work for a client: open them and tap "New quote" or "New job".',
      'Give them their portal: open the client and use the Client portal card ("Create portal link").',
      'Ask for a review: open the client and tap "Request a review by email" (needs an email address).',
    ],
    who: 'Office managers do not see job values on the client record.',
    records: '?client=<id> opens that client. Add &tab=messages to open their message thread.',
    mate: 'Can read the open client (get_page_record), draft a quote (create_quote) or invoice (create_invoice), or create a job (create_job), always confirming first; cannot send anything.',
    suggestions: ['What does this client owe?', 'Draft a quote for this client', 'How do I send them their portal?'],
  },
  {
    key: 'leads',
    title: 'Leads',
    area: 'Clients',
    what: 'Every enquiry from first contact to won, before it becomes a client. Quote page requests land here automatically.',
    tabs: ['All', 'New', 'Contacted', 'Quoted', 'Won', 'Lost'],
    tasks: [
      'Add a lead: tap "Add lead", fill Name / company, contact details, Source and Estimated value, then "Add lead".',
      'Follow up: open the lead, under "Follow up with Mate" tap "Text" or "Email", check the draft, then "Send text" or "Send email" (opens your phone\'s messages or email app).',
      'Move it on: open the lead and change Stage.',
      'Win it: open the lead, tap "Convert to client", then "Write a quote".',
    ],
    who: '',
    records: '?lead=<id> opens that lead.',
    mate: 'Can read the open lead (get_page_record) and draft a follow-up from the lead sheet; can draft a quote (create_quote) after confirming. Never sends.',
    suggestions: ['Write a follow-up for this lead', 'How do I turn a lead into a client?', 'What is my win rate?'],
  },
  {
    key: 'quotepage',
    title: 'Quote Page',
    area: 'Clients',
    what: 'Your own public page where customers ask for a quote with photos. Requests drop straight into Leads. Includes views and requests stats, QR code and artwork.',
    tabs: [],
    tasks: [
      'Set it up: fill Link name, Headline, About you, What you do and Areas you cover, then tap "Save changes".',
      'Go live: switch on the toggle by "Your page is hidden". Use "Preview" to check it.',
      'Get it seen: under "Get it seen" use "Van sign PDF", "A4 poster", "QR (PNG)" or "QR (SVG)", "Copy link for Google" or "Copy signature line".',
      'Put it on documents: switch on "Every invoice and quote" to add a "Get a quote" link to invoice and quote emails.',
    ],
    who: 'Only the owner or an admin can change the quote page.',
    records: '',
    mate: 'Cannot change the page; gives the steps.',
    suggestions: ['How do I put my QR on the van?', 'Why can\'t customers see my page?', 'How many requests this month?'],
  },
  {
    key: 'clientportal',
    title: 'Client Portal',
    area: 'Clients',
    what: 'One private page per client showing their jobs, who is coming, certificates, invoices with Pay now, and messages to you. This page lists every portal link and client message.',
    tabs: [],
    tasks: [
      'Share with a client: tap "Share with a client", open the client, tap "Create portal link", then "Copy", "Share", "WhatsApp", "Email" or "QR code".',
      'Answer a message: tap it under "Messages" to open the client record and reply there.',
      'Stop a link: open the client and on the portal card tap "Pause", "New link" or "Switch off".',
    ],
    who: '',
    records: '',
    mate: 'Can read a message thread or client (get_page_record); cannot create links or send messages, gives the steps.',
    suggestions: ['How do I give a client their link?', 'What does the client see?', 'Why does it say Being finalised?'],
  },
];

const PAGES_E = [
  {
    key: 'smartdocs',
    title: 'Smart Docs',
    area: 'Smart Docs',
    what: 'The landing page for AI documents: counts of RAMS, method statements, designs and briefing packs the firm has generated, your last five documents, and cards into each generator plus AI quote.',
    tabs: [],
    tasks: [
      'Make a RAMS: tap the "AI RAMS" card ("Generate"), add the brief, tap "Generate RAMS".',
      'Draft a quote: under Quotes tap the "AI quote" card ("Draft"), then "Start a draft".',
      'Open a recent document: under "Recent documents" tap the row; it opens that generator.',
      'Build a briefing pack: tap "AI Briefing Pack". The job pack needs a RAMS and a method statement first.',
    ],
    who: '',
    records: '',
    mate: 'Can create a job pack (create_job_pack) and a draft quote (create_quote), and check who has not signed packs (who_has_not_signed); cannot generate RAMS, method statements, designs or briefing packs, gives the steps.',
    suggestions: ['Which document should I start with?', 'How do I make a briefing pack?', 'Where are my recent RAMS?'],
  },
  {
    key: 'aidesignspec',
    title: 'Design Spec',
    area: 'Smart Docs',
    what: 'AI Design: designs a full installation to BS 7671, sizing and protecting every circuit and compliance checking it, then gives a branded design schedule PDF. Same designer as the electrician side, without save to customer.',
    tabs: ['Project: basic details', 'Supply: electrical characteristics', 'Circuits: add your circuits', 'Install: per circuit setup', 'Validate: pre-flight check', 'Review: final check'],
    tasks: [
      'Design an installation: fill each step and tap "Next", then on Review tap "Generate Design".',
      'Get the PDF: on the results tap "Download PDF".',
      'Start again: on the results tap "New design".',
    ],
    who: '',
    records: '',
    mate: 'Can answer regulation questions (search_bs7671) and explain the steps; cannot run the designer itself.',
    suggestions: ['What do I need for the Supply step?', 'How do I get the design PDF?', 'Why did a circuit fail?'],
  },
  {
    key: 'airams',
    title: 'RAMS',
    area: 'Smart Docs',
    what: 'AI RAMS: drafts a full risk assessment and method statement from a brief in about three minutes. Can link to a job pack so the PDF is saved there for worker sign-off. Shows a Library of recent RAMS.',
    tabs: [],
    tasks: [
      'Generate a RAMS: under Briefing pick a "Linked job pack" (optional), fill "Scope of works" and "Hazards / additional notes", tap "Generate RAMS".',
      'Save it to the job pack: once ready tap "Download". With a job pack linked, the PDF is attached for workers to sign.',
      'Reopen an old one: in "Library" tap the row, then "Download".',
      'Start fresh: tap "New", or the reset button at the top.',
    ],
    who: '',
    records: '',
    mate: 'Can create a job pack (create_job_pack), check RAMS and pack sign-off (who_has_not_signed) and give the safety overview (get_safety_overview); cannot generate the RAMS, gives the steps.',
    suggestions: ['How do I attach RAMS to a job pack?', 'Who has not signed the RAMS?', 'What should I put in the scope?'],
  },
  {
    key: 'aimethodstatement',
    title: 'Method Statement',
    area: 'Smart Docs',
    what: 'AI Method Statement: drafts a step by step method statement (8 to 14 steps, tools and materials, testing with pass and fail criteria, linked hazards) from a short brief, optionally linked to a job pack.',
    tabs: [],
    tasks: [
      'Draft one: under Brief pick "Link to job pack", fill "Scope of work", tap "Generate".',
      'Attach the PDF to the job pack: when Result shows Ready, tap "Download".',
      'Start again: tap "New".',
    ],
    who: '',
    records: '',
    mate: 'Can create a job pack (create_job_pack) and look up regulations (search_bs7671); cannot generate the method statement, gives the steps.',
    suggestions: ['How do I link this to a job pack?', 'What does the method statement include?', 'Where is my last statement?'],
  },
  {
    key: 'aibriefingpack',
    title: 'Briefing Pack',
    area: 'Smart Docs',
    what: 'AI Briefing Pack: builds a pre-job site briefing for a job pack, with your notes and site photos, exported as a PDF. The job pack must already have a RAMS and a method statement.',
    tabs: [],
    tasks: [
      'Make a briefing: under "New briefing" pick the "Job pack", add "Additional notes", tap "Add photos" if needed, then "Generate briefing pack".',
      'Missing RAMS or method statement: tap "Generate RAMS" or "Generate Method Statement" shown under the job pack.',
      'Get the PDF: after it is ready tap "Export PDF".',
    ],
    who: '',
    records: '',
    mate: 'Can create a job pack (create_job_pack) and check sign-off (who_has_not_signed); cannot generate the briefing, gives the steps.',
    suggestions: ['Why can\'t I generate the briefing?', 'Can I add site photos?', 'How do workers see the briefing?'],
  },
  {
    key: 'aiquote',
    title: 'AI quote',
    area: 'Smart Docs',
    what: 'Drafts a quote for a job, pricing materials from your price book first and labour against your own past jobs, with VAT and CIS from your settings. Lists your AI drafted quotes with Drafts, Sent, Won and Won value.',
    tabs: [],
    tasks: [
      'Draft a quote: tap "Start a draft", choose "From a job" or "Describe the work", then "Draft my quote".',
      'Save it: on the review tap "Save draft and review"; it opens in the quote builder to adjust and send.',
      'Check a draft: tap a row marked "Draft, tap to check".',
      'Wrong job: on the review tap "Change the job".',
    ],
    who: 'Owner, admin and office can draft. Office sees sell prices only, never buy prices or markup. Others see "Quotes are drafted by the office".',
    records: '?job=<id> opens the draft sheet with that job picked.',
    mate: 'Can create a draft quote (create_quote) and get material prices (get_material_prices); cannot send a quote, gives the steps.',
    suggestions: ['Where do the prices come from?', 'How do I send the draft?', 'Draft a quote for this job'],
  },
  {
    key: 'settings',
    title: 'Settings',
    area: 'Account',
    what: 'Company details, branding, notification email, QS sign-off rules and bank details shown on invoices.',
    tabs: [],
    tasks: [
      'Change company details or bank details: edit the fields under General or "Billing & payments", tap "Save" (or "Save all" in the unsaved changes bar).',
      'Add your logo and colours: under Branding tap "Upload", set Primary and Secondary colour, tap "Save branding".',
      'Get office alert emails: enter the "Office email" under Notifications, tap "Save".',
      'Require QS sign-off: under "QS sign-off" switch on "Require QS approval before issue", or "I am my own Qualifying Supervisor".',
    ],
    who: 'Owner: can change everything. Co-admins (admin and office): can view only; only the account owner can change company details, branding, payments, the office email and QS switches.',
    records: '',
    mate: 'No tool changes settings; Mate gives the steps.',
    suggestions: ['How do I add my logo?', 'Where do bank details go?', 'How do I require QS sign-off?'],
  },
  {
    key: 'wt-hub',
    title: 'Worker Tools',
    area: 'Worker Tools',
    what: 'The worker\'s home: clock in, "To do now" alerts (sent back timesheets, new jobs, packs to sign, tasks due, crew approvals, apprentice hours, certificates to sign) and links to every tool.',
    tabs: [],
    tasks: [
      'Start the day: tap "Clock in".',
      'Book time off: tap "Request leave".',
      'Message the office: tap "Messages" under Team.',
    ],
    who: 'Any team member linked to the firm. "Your crew" shows only for supervisors with crew, "Apprentice hours" only when entries need them, "QS reviews" for the QS. No team link shows "Join your team".',
    records: '?task=<id> and ?signoff=<id> redirect to Tasks and Sign-offs.',
    mate: 'Can look up a worker (get_team_member); gives the steps.',
    suggestions: ['Why can\'t my worker see Worker Tools?', 'Who sees Your crew?', 'How does a worker clock in?'],
  },
  {
    key: 'wt-status',
    title: 'My Status',
    area: 'Worker Tools',
    what: 'Sets the worker\'s status (On Site, En Route, Office, Off Duty) so the office knows where they are. On Site and En Route need a job and share location once.',
    tabs: [],
    tasks: [
      'Set status: tap a status, pick the job under "Which job?" if asked, tap "Set to On Site".',
    ],
    who: 'Any team member.',
    records: '',
    mate: 'Can show a worker\'s on-site status (get_team_member).',
    suggestions: ['Where is this worker now?', 'Why does it ask for location?', 'Who set my status?'],
  },
  {
    key: 'wt-timesheets',
    title: 'Timesheets',
    area: 'Worker Tools',
    what: 'Workers clock in and out against a job or add a missed day; days go to the office to approve. Shows this week and logged days with Waiting, Approved or Sent to payroll.',
    tabs: ['This week', 'All'],
    tasks: [
      'Clock in: tap "Clock in", pick the job, tap "Start the clock". Finish with "Clock out".',
      'Log a missed day: tap "Add a past day", fill it, send it for approval.',
      'Fix a sent back day: under "Sent back by the office" tap "Fix", correct and save.',
    ],
    who: 'Any team member. Waiting days can be changed with "Change".',
    records: '?job=<id> opens clock in with that job.',
    mate: 'Can show a worker\'s recent hours (get_team_member) and pending timesheets (get_pending_approvals); cannot approve.',
    suggestions: ['How does a worker fix a day?', 'Who has timesheets waiting?', 'Can they add a missed day?'],
  },
  {
    key: 'wt-pay',
    title: 'My pay',
    area: 'Worker Tools',
    what: 'An estimate of pay before deductions from approved hours at the rate on the worker\'s record, plus hours awaiting approval, what went to payroll and expenses to be repaid. Not a payslip.',
    tabs: ['This pay period', 'Last pay period'],
    tasks: [
      'Check this period: open the page; switch to "Last pay period" for the one before.',
    ],
    who: 'The worker sees only their own figures. No rate set shows "Rate not set" with hours only.',
    records: '',
    mate: 'Can show a worker\'s recent hours and expenses (get_team_member); gives the steps.',
    suggestions: ['Why does it say Rate not set?', 'Why are hours not counted?', 'Is this my payslip?'],
  },
  {
    key: 'wt-leave',
    title: 'Leave',
    area: 'Worker Tools',
    what: 'Leave allowance (Left, Taken or booked, Waiting) and leave requests. Workers request annual, sick, unpaid, compassionate or training leave and can withdraw or cancel.',
    tabs: ['All', 'Pending', 'Approved', 'Declined'],
    tasks: [
      'Request leave: tap "Request Leave", pick the type, pick dates (or "Half Day"), tap "Submit Request".',
      'Withdraw: on the request tap "Withdraw request" (or "Cancel leave" once approved).',
    ],
    who: 'Any team member.',
    records: '',
    mate: 'Can show leave waiting (get_pending_approvals); cannot approve.',
    suggestions: ['How does a worker book leave?', 'Who has leave waiting?', 'Can they cancel approved leave?'],
  },
  {
    key: 'wt-comms',
    title: 'Team comms',
    area: 'Worker Tools',
    what: 'Announcements, safety alerts and job messages from the office. Workers reply in a message and acknowledge those that need it.',
    tabs: ['All', 'Unread', 'To acknowledge'],
    tasks: [
      'Acknowledge: open a message marked "Please acknowledge", tap "Acknowledge".',
      'Chat with the team: tap "Team chat".',
    ],
    who: 'Any team member.',
    records: '?thread=<id> opens that message.',
    mate: 'Can read the open thread (get_page_record); cannot send, gives the steps.',
    suggestions: ['Who has not acknowledged?', 'How do workers reply?', 'Where is team chat?'],
  },
  {
    key: 'wt-jobs',
    title: 'My Jobs',
    area: 'Worker Tools',
    what: 'Jobs the worker is put on, grouped New from the office, Today and on now, Coming up, No date yet. A job shows directions, who to ask for, notes, packs to sign and who else is on it.',
    tabs: ['On my list', 'Finished', 'All'],
    tasks: [
      'Get there: open the job, tap "Directions".',
      'Finish your part: tap "I’ve finished my part", add a note and photos, tap "Tell the office".',
    ],
    who: 'Workers see only jobs they are on.',
    records: '?job=<id> opens that job.',
    mate: 'Can read the job (get_page_record) and create jobs (create_job); gives the steps.',
    suggestions: ['How does a worker mark a job done?', 'Why can\'t they see this job?', 'Where are the drawings?'],
  },
  {
    key: 'wt-my-week',
    title: 'My week',
    area: 'Worker Tools',
    what: 'Seven days of the worker\'s bookings from the office Diary: job, address, time, drive time, and who moved or booked what and when.',
    tabs: [],
    tasks: [
      'See another week: use the previous and next week arrows.',
      'Open a job: tap the booking.',
    ],
    who: 'Workers see only their own bookings.',
    records: '?week=<date> opens that week.',
    mate: 'No tool reads the diary; gives the steps.',
    suggestions: ['Who moved this booking?', 'How do I see next week?', 'Where does the drive time come from?'],
  },
  {
    key: 'wt-tasks',
    title: 'My Tasks',
    area: 'Worker Tools',
    what: 'Tasks given to the worker, with priority and due date, plus "Up for grabs on your jobs" they can take.',
    tabs: ['To do', 'Done', 'All'],
    tasks: [
      'Update a task: open it, tap "Start", "Blocked" or "Done". Add a photo with "Add photo".',
      'Take an unassigned task: tap "I’ll take it".',
    ],
    who: 'Any team member.',
    records: '?task=<id> opens that task; ?job=<id> filters to a job.',
    mate: 'Can add a task (add_task); cannot change a worker\'s task status.',
    suggestions: ['Give this worker a task', 'Who has blocked tasks?', 'How do they take a task?'],
  },
  {
    key: 'wt-signoffs',
    title: 'Sign-offs',
    area: 'Worker Tools',
    what: 'Job packs and RAMS the worker must read and sign: scope, required credentials, briefing and documents.',
    tabs: ['All', 'To sign', 'Signed'],
    tasks: [
      'Sign a pack: open it, read it, draw your signature, tap "Sign and confirm".',
    ],
    who: 'Any team member assigned the pack.',
    records: '?signoff=<id> opens that pack; ?job=<id> filters to a job.',
    mate: 'Can list who has not signed (who_has_not_signed).',
    suggestions: ['Who has not signed this pack?', 'How does a worker sign?', 'Why is the RAMS missing?'],
  },
  {
    key: 'wt-credentials',
    title: 'Credentials',
    area: 'Worker Tools',
    what: 'The worker\'s Elec-ID: ECS card, qualifications, cards and training with expiry and whether the employer has checked them.',
    tabs: ['All', 'Needs attention', 'Not checked'],
    tasks: [
      'Add a ticket: tap "Add a qualification", fill "Name" and dates, tap "Save".',
      'No Elec-ID yet: tap "Set up Elec-ID".',
    ],
    who: 'Any team member. Their entries are self-declared until the employer checks them.',
    records: '',
    mate: 'Can list expiring tickets (list_expiring_tickets).',
    suggestions: ['Whose tickets are expiring?', 'How does a worker add a card?', 'What does Not checked mean?'],
  },
  {
    key: 'wt-equipment',
    title: 'My Equipment',
    area: 'Worker Tools',
    what: 'Read only list of tools signed out to the worker with PAT test and calibration due dates.',
    tabs: ['All', 'Due soon'],
    tasks: [
      'Check what is due: tap "Due soon".',
    ],
    who: 'Any team member. The employer manages the kit; workers only view.',
    records: '',
    mate: 'No tool reads equipment; gives the steps.',
    suggestions: ['What kit is overdue?', 'How do I assign a tool?', 'Why is this PAT overdue?'],
  },
  {
    key: 'wt-progress-notes',
    title: 'Progress Notes',
    area: 'Worker Tools',
    what: 'Daily notes and photos against a job that go straight to the office with name and time. Apprentices can send a note to their OTJ log.',
    tabs: ['All', 'Today'],
    tasks: [
      'Log progress: pick the job, write what is done, tap "Send to the office". Editable for 24 hours.',
    ],
    who: 'Any team member; the OTJ option shows for apprentices only.',
    records: '?job=<id> picks that job.',
    mate: 'Can read the job (get_page_record); gives the steps.',
    suggestions: ['What did the team log today?', 'Can a note be edited?', 'How do apprentices log OTJ?'],
  },
  {
    key: 'wt-expenses',
    title: 'Expenses',
    area: 'Worker Tools',
    what: 'Mileage and receipt claims the office approves and pays back, with Waiting, Coming back to you and Paid back totals.',
    tabs: ['All', 'Waiting', 'Approved', 'Paid', 'Rejected'],
    tasks: [
      'Claim: tap "Log mileage" or "Claim a receipt", fill it, tap "Send claim".',
      'Change or withdraw a waiting claim: open it, tap "Change it" or "Withdraw".',
    ],
    who: 'Any team member.',
    records: '',
    mate: 'Can show expenses waiting (get_pending_approvals); cannot approve.',
    suggestions: ['Who has expenses waiting?', 'What mileage rate applies?', 'How do they withdraw a claim?'],
  },
  {
    key: 'wt-reports',
    title: 'Reports',
    area: 'Worker Tools',
    what: 'Workers raise a snag, near-miss or incident against a job and see its history, plus "Safety actions for you" to mark done.',
    tabs: ['All', 'Open', 'Resolved'],
    tasks: [
      'Report: pick Snag, Near-miss or Incident, choose the "Job" and "Severity", describe it, tap "Submit snag" (or "Submit near-miss", "Submit incident").',
      'Close a safety action: tap "Done" on it.',
    ],
    who: 'Any team member.',
    records: '?job=<id> picks that job; ?incident=<id> highlights an incident.',
    mate: 'Can list incidents (list_safety_incidents) and overdue actions (list_overdue_safety_actions).',
    suggestions: ['What incidents are open?', 'Which safety actions are overdue?', 'How does a worker report a snag?'],
  },
  {
    key: 'wt-qs-reviews',
    title: 'QS Reviews',
    area: 'Worker Tools',
    what: 'QS sign-off of EICR, EIC and Minor Works certificates. Electricians see their QS\'s feedback; the QS approves and countersigns or returns with comments.',
    tabs: ['My certificates', 'To review', 'Awaiting', 'Approved', 'Returned', 'All'],
    tasks: [
      'Countersign: open it under "To review", tap "Approve & countersign", add name and signature, tap "Confirm approval".',
      'Return it: tap "Return with comments", write what needs changing, tap "Return certificate".',
      'Act on feedback: tap "Edit certificate", then "Resubmit to QS".',
    ],
    who: 'Team members see "QS feedback". Only the QS gets "To review".',
    records: '?review=<id> opens it; ?side=review opens the reviewer side.',
    mate: 'Can read a signature request (get_page_record); cannot sign.',
    suggestions: ['How do I countersign?', 'Which certs await the QS?', 'How does an electrician resubmit?'],
  },
  {
    key: 'wt-apprentice-hours',
    title: 'Confirm apprentice hours',
    area: 'Worker Tools',
    what: 'Off-the-job training hours apprentices logged, for the people who saw the work to confirm or send back. College checks separately.',
    tabs: [],
    tasks: [
      'Confirm: tap "Confirm" on the entry.',
      'Send back: tap "Send back", say what to change, tap "Send back".',
    ],
    who: 'The apprentice\'s workplace supervisor, Supervisors, Project Managers and Apprentice Co-ordinators. Lists only entries they may confirm.',
    records: '?entry=<id> highlights that entry.',
    mate: 'No tool confirms OTJ hours; gives the steps.',
    suggestions: ['Who can confirm OTJ hours?', 'How do I send hours back?', 'Does college still check it?'],
  },
  {
    key: 'wt-crew',
    title: 'Your crew',
    area: 'Worker Tools',
    what: 'For supervisors: timesheets, expenses and leave waiting from the people who name them as workplace supervisor. The office sees every decision.',
    tabs: [],
    tasks: [
      'Approve: tap "Approve".',
      'Send back: tap "Send back", give a reason, tap "Send back".',
    ],
    who: 'Supervisors only. Crew is set on each person in Team; until then approvals stay with the office.',
    records: '',
    mate: 'Can list approvals waiting (get_pending_approvals); cannot approve.',
    suggestions: ['How do I set a supervisor?', 'What is my crew waiting on?', 'Does the office see this?'],
  },
];

export const PAGES = [...PAGES_A, ...PAGES_B, ...PAGES_C, ...PAGES_D, ...PAGES_E];
