import { ArrowLeft, Building2, CheckCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import useSEO from "@/hooks/useSEO";

const TITLE = "Plant Room Design - HNC Module 8 Section 6.2";
const DESCRIPTION = "Master plant room design principles for electrical installations: layout considerations, access requirements, ventilation for heat rejection, lighting requirements (200 lux minimum), switchboard positioning, cable routes, earthing systems, and CIBSE/BSRIA design guidance.";

const quickCheckQuestions = [
  {
    id: "layout-principle",
    question: "What is the primary consideration when positioning electrical switchgear in a plant room?",
    options: ["Minimising cable lengths only", "Ensuring adequate front and rear access for maintenance and operation", "Placing equipment as close together as possible", "Locating switchgear near water services"],
    correctIndex: 1,
    explanation: "Switchgear positioning must prioritise adequate access space for safe operation, maintenance, and fault clearance. BS 7671 and CIBSE guidance require minimum clearances of 1000mm in front of switchgear and 600mm at the rear where access is required."
  },
  {
    id: "ventilation-purpose",
    question: "What is the primary purpose of mechanical ventilation in an electrical plant room?",
    options: ["To reduce noise levels", "To remove heat generated by electrical equipment and maintain ambient temperature", "To increase air pressure", "To provide fresh air for occupants"],
    correctIndex: 1,
    explanation: "Electrical equipment generates significant heat during operation. Mechanical ventilation removes this heat to maintain ambient temperatures within equipment ratings (typically 35-40 degrees Celsius maximum). Overheating reduces equipment lifespan and can cause protective device nuisance tripping."
  },
  {
    id: "lighting-level",
    question: "What is the minimum recommended illuminance level for general plant room areas according to CIBSE guidance?",
    options: ["50 lux", "100 lux", "200 lux", "500 lux"],
    correctIndex: 2,
    explanation: "CIBSE SLL Lighting Guide recommends a minimum of 200 lux for plant rooms to enable safe equipment operation, maintenance tasks, and meter reading. Higher levels (300-500 lux) may be required at control panels and where detailed work is performed."
  },
  {
    id: "earthing-main",
    question: "What is the purpose of the main earthing terminal (MET) in a plant room?",
    options: ["To provide a connection point for lightning protection only", "To serve as the central bonding point connecting all protective conductors and extraneous-conductive-parts", "To terminate the neutral conductor", "To provide a test point for insulation resistance only"],
    correctIndex: 1,
    explanation: "The main earthing terminal (MET) is the central equipotential bonding point where all circuit protective conductors, main protective bonding conductors, and earthing conductor connect. This ensures all exposed and extraneous-conductive-parts are at the same potential during fault conditions."
  }
];

const quizQuestions = [
  {
    id: 1,
    question: "According to BS 7671 and industry guidance, what is the minimum clearance required in front of switchgear for safe operation and maintenance?",
    options: [
      "600mm",
      "800mm",
      "1000mm",
      "1200mm"
    ],
    correctAnswer: 2,
    explanation: "A minimum clearance of 1000mm is required in front of switchgear to allow safe operation, visual inspection of indicators, and adequate working space for maintenance personnel. This dimension accommodates door swing, panel removal, and emergency egress."
  },
  {
    id: 2,
    question: "What temperature should plant room ambient conditions typically be maintained below for standard electrical equipment?",
    options: ["25 degrees Celsius", "30 degrees Celsius", "35 degrees Celsius", "45 degrees Celsius"],
    correctAnswer: 2,
    explanation: "Most standard electrical equipment is rated for ambient temperatures up to 35-40 degrees Celsius. Exceeding this reduces equipment life, affects protective device calibration, and may require cable derating. CIBSE TM52 provides guidance on overheating assessment."
  },
  {
    id: 3,
    question: "What is the recommended minimum illuminance at switchboard control panels according to CIBSE guidance?",
    options: ["100 lux", "200 lux", "300 lux", "500 lux"],
    correctAnswer: 2,
    explanation: "CIBSE recommends 300 lux minimum at control panels where operators need to read instruments, meters, and labels accurately. General plant room areas require 200 lux minimum, whilst task lighting may provide up to 500 lux for detailed maintenance work."
  },
  {
    id: 4,
    question: "Which BSRIA guide provides specific guidance on the design and installation of plant rooms?",
    options: [
      "BG 6 - Energy Efficient Lighting",
      "BG 29 - Pre-Commission Cleaning",
      "BG 32 - Designing Plant Rooms",
      "BG 44 - Commissioning Management"
    ],
    correctAnswer: 2,
    explanation: "BSRIA BG 32 'Designing Plant Rooms' provides comprehensive guidance on plant room layout, access requirements, services coordination, and maintenance considerations. It covers spatial planning, equipment zoning, and coordination with other building services."
  },
  {
    id: 5,
    question: "What is the primary purpose of installing a supplementary equipotential bonding conductor in a plant room?",
    options: [
      "To provide additional current-carrying capacity",
      "To connect all simultaneously accessible exposed-conductive-parts and extraneous-conductive-parts",
      "To reduce voltage drop in circuits",
      "To provide a neutral return path"
    ],
    correctAnswer: 1,
    explanation: "Supplementary equipotential bonding connects simultaneously accessible exposed-conductive-parts and extraneous-conductive-parts to limit touch voltage during fault conditions. This is particularly important in plant rooms where metallic services and equipment are in close proximity."
  },
  {
    id: 6,
    question: "When designing cable routes in a plant room, what minimum height should horizontal cable containment be installed above floor level?",
    options: ["1.8m", "2.1m", "2.4m", "3.0m"],
    correctAnswer: 2,
    explanation: "Horizontal cable containment should be installed at minimum 2.4m (or higher where ceiling height permits) to maintain clear headroom for personnel access and equipment movement. This also reduces risk of mechanical damage and provides adequate bend radii for cable entries."
  },
  {
    id: 7,
    question: "According to CIBSE guidance, what ventilation rate is typically required per kW of heat dissipation in an electrical plant room?",
    options: [
      "10-15 litres per second per kW",
      "25-35 litres per second per kW",
      "50-60 litres per second per kW",
      "80-100 litres per second per kW"
    ],
    correctAnswer: 1,
    explanation: "A ventilation rate of approximately 25-35 litres per second per kW of heat dissipation is typically required to maintain acceptable ambient temperatures. The exact rate depends on external temperatures, room configuration, and equipment temperature ratings."
  },
  {
    id: 8,
    question: "What type of emergency lighting is required in plant rooms according to BS 5266?",
    options: [
      "No emergency lighting required",
      "Maintained emergency lighting only",
      "Non-maintained escape route lighting providing minimum 1 lux",
      "High-risk task area lighting providing minimum 10% of normal illuminance"
    ],
    correctAnswer: 3,
    explanation: "Plant rooms are classified as high-risk task areas where sudden loss of lighting could create danger. BS 5266-1 requires emergency lighting providing minimum 10% of normal illuminance (or 15 lux minimum) to allow safe shutdown of equipment and egress."
  },
  {
    id: 9,
    question: "What is the recommended minimum cross-sectional area for the main protective bonding conductor to metallic water pipes entering a building?",
    options: [
      "6mm squared copper",
      "10mm squared copper",
      "Half the size of the earthing conductor (minimum 6mm squared)",
      "Equal to the earthing conductor size"
    ],
    correctAnswer: 2,
    explanation: "BS 7671 Table 54.8 specifies that main protective bonding conductors should have a cross-sectional area not less than half that of the earthing conductor, with a minimum of 6mm squared for copper. This ensures adequate fault current capacity for protective bonding."
  },
  {
    id: 10,
    question: "Which factor most influences the required depth of cable trenches in a plant room floor?",
    options: [
      "The number of cables only",
      "The cable bend radius requirements and quantity of cables",
      "The floor finish material only",
      "The ambient temperature only"
    ],
    correctAnswer: 1,
    explanation: "Cable trench depth must accommodate the required number of cables plus maintain minimum bend radii at entries and exits. Large power cables may require bend radii of 12-20 times cable diameter, significantly affecting trench depth and width requirements."
  },
  {
    id: 11,
    question: "What is the recommended minimum door width for plant room access to allow equipment entry and replacement?",
    options: ["800mm", "900mm", "1000mm", "1200mm"],
    correctAnswer: 3,
    explanation: "A minimum door width of 1200mm is recommended to allow entry of standard equipment, cable drums, and maintenance equipment. Larger openings (double doors or removable panels) may be required for major plant items that cannot be disassembled."
  },
  {
    id: 12,
    question: "According to BS 7671 Regulation 522.8, what protection is required for cables installed in plant rooms where mechanical damage may occur?",
    options: [
      "No specific protection required",
      "Metal conduit or trunking only",
      "Appropriate protection against mechanical damage such as conduit, trunking, or steel wire armoured cables",
      "PVC conduit only"
    ],
    correctAnswer: 2,
    explanation: "BS 7671 Regulation 522.8 requires cables to be protected against mechanical damage where such damage is likely. In plant rooms, this typically means using steel conduit, metal trunking, or SWA cables, particularly for cables at low level or crossing access routes."
  },
  {
    id: 13,
    question: "What is the purpose of maintaining a 'services coordination drawing' for a plant room?",
    options: [
      "To record energy consumption",
      "To show the spatial relationship of all services and identify potential clashes",
      "To calculate electrical loads only",
      "To schedule maintenance activities"
    ],
    correctAnswer: 1,
    explanation: "Services coordination drawings show the spatial arrangement of all building services (electrical, mechanical, plumbing, fire systems) to identify and resolve clashes before installation. This is essential in plant rooms where multiple services converge in limited space."
  },
  {
    id: 14,
    question: "What minimum IP rating is generally recommended for electrical enclosures in plant rooms with potential water exposure?",
    options: ["IP2X", "IP4X", "IP44", "IP65"],
    correctAnswer: 2,
    explanation: "IP44 provides protection against solid objects greater than 1mm and water splashing from any direction. This is suitable for most plant rooms where cleaning operations or minor water leaks may occur. Higher ratings (IP55/IP65) may be needed near water services or in humid conditions."
  }
];

const faqs = [
  {
    question: "How do I determine the ventilation requirements for an electrical plant room?",
    answer: "Calculate the total heat dissipation from all electrical equipment (typically 2-5% of rated power for transformers, losses from cables, and heat from switchgear). Apply a ventilation rate of 25-35 litres per second per kW of heat gain. Consider the maximum external temperature and the equipment ambient rating (typically 35 degrees Celsius). Mechanical extract ventilation is usually required, with low-level fresh air intake and high-level extract to promote natural convection. CIBSE Guide B provides detailed calculation methods."
  },
  {
    question: "What are the key access requirements for switchboard maintenance?",
    answer: "Minimum 1000mm clear space in front of switchgear for operation and maintenance. Rear access of 600mm minimum where required for cable termination or component replacement. Side clearances as specified by manufacturer, typically 200-300mm minimum. Emergency egress routes must be maintained clear at all times. Consider future equipment replacement routes and ensure adequate door widths (minimum 1200mm). All access routes should have slip-resistant flooring and adequate lighting."
  },
  {
    question: "How should cable containment be organised in a plant room?",
    answer: "Segregate power and data cables per BS 7671 requirements. Install horizontal containment at 2.4m minimum height for headroom. Provide adequate support intervals (ladder rack typically 1.5-2m centres). Allow 30-50% spare capacity for future cables. Maintain minimum bend radii at changes of direction. Use fire-resistant containment where cables pass through fire barriers. Label all containment to identify contents and destinations. Coordinate with other services to avoid clashes and maintain access."
  },
  {
    question: "What earthing arrangements are required in a plant room?",
    answer: "Install main earthing terminal (MET) in accessible location, clearly labelled. Connect main protective bonding conductors to incoming metallic services (water, gas, structural steel). Provide supplementary bonding between simultaneously accessible exposed-conductive-parts and extraneous-conductive-parts. Install earth bars for multiple circuit connections. Ensure all metallic containment is electrically continuous and bonded. Consider mesh bonding network (MBN) for EMC-sensitive equipment. All connections should be accessible for testing."
  },
  {
    question: "What fire protection measures are needed in electrical plant rooms?",
    answer: "Provide minimum 60-minute fire-rated construction (walls, floors, ceilings) per Building Regulations. Install fire-stopping at all service penetrations. Consider automatic fire suppression (gas suppression systems preferred over water sprinklers for electrical equipment). Ensure fire alarm detection suitable for electrical fires (optical or multi-sensor detectors). Provide clearly marked emergency stop buttons near exits. Maintain fire extinguishers suitable for electrical fires (CO2 or dry powder). Display evacuation procedures and emergency contact information."
  },
  {
    question: "How do I ensure adequate lighting in a plant room?",
    answer: "Provide minimum 200 lux general illuminance throughout the plant room. Increase to 300-500 lux at control panels, meters, and where detailed work is performed. Use luminaires with good colour rendering (Ra greater than 80) for accurate identification of cable colours. Install emergency lighting providing minimum 10% of normal illuminance or 15 lux minimum. Position luminaires to avoid shadows on switchgear operating faces. Consider maintenance access when selecting mounting heights. Protect luminaires against mechanical damage where necessary."
  }
];

const HNCModule8Section6_2 = () => {
  useSEO(TITLE, DESCRIPTION);

  return (
    <div className="overflow-x-hidden bg-[#1a1a1a]">
      {/* Minimal Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section6">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <article className="px-4 sm:px-6 py-8 sm:py-12">

        {/* Centred Title */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Building2 className="h-4 w-4" />
            <span>Module 8.6.2</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            Plant Room Design
          </h1>
          <p className="text-white/80">
            Layout considerations, access requirements, ventilation, lighting and electrical infrastructure
          </p>
        </header>

        {/* Quick Summary Boxes */}
        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2">In 30 Seconds</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
              <li className="pl-1"><strong>Layout:</strong> Adequate access, logical equipment zoning, future expansion</li>
              <li className="pl-1"><strong>Access:</strong> 1000mm front clearance, 600mm rear access minimum</li>
              <li className="pl-1"><strong>Ventilation:</strong> 25-35 l/s per kW heat dissipation</li>
              <li className="pl-1"><strong>Lighting:</strong> 200 lux minimum, 300 lux at control panels</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2">Key Standards</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
              <li className="pl-1"><strong>BS 7671:</strong> Installation requirements, earthing, bonding</li>
              <li className="pl-1"><strong>CIBSE Guide B:</strong> Ventilation and heat dissipation</li>
              <li className="pl-1"><strong>BSRIA BG 32:</strong> Designing Plant Rooms</li>
              <li className="pl-1"><strong>BS 5266:</strong> Emergency lighting requirements</li>
            </ul>
          </div>
        </div>

        {/* Learning Outcomes */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You'll Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              "Design plant room layouts with appropriate equipment zoning",
              "Specify adequate access clearances for operation and maintenance",
              "Calculate ventilation requirements for heat rejection",
              "Apply lighting standards including emergency lighting",
              "Position switchboards and plan cable routes effectively",
              "Design earthing and bonding arrangements per BS 7671"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 mb-12" />

        {/* Section 1: Layout Considerations */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            Layout Considerations
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Plant room layout design requires careful coordination of electrical, mechanical, and plumbing
              services within a confined space. BSRIA BG 32 provides comprehensive guidance on spatial planning,
              equipment zoning, and the creation of efficient, maintainable installations. The layout must balance
              operational requirements, maintenance access, safety considerations, and future flexibility.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Fundamental Layout Principles:</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Equipment zoning:</strong> Group related equipment together (electrical, mechanical, controls)</li>
                <li className="pl-1"><strong>Segregation:</strong> Separate electrical equipment from water services where possible</li>
                <li className="pl-1"><strong>Access routes:</strong> Maintain clear circulation paths to all equipment</li>
                <li className="pl-1"><strong>Emergency egress:</strong> Ensure alternative escape routes from all areas</li>
                <li className="pl-1"><strong>Future expansion:</strong> Allow space for additional equipment and circuits</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Equipment Positioning Hierarchy</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Equipment Type</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Position Priority</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Key Considerations</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Main switchboard</td>
                      <td className="border border-white/10 px-3 py-2">Near plant room entrance</td>
                      <td className="border border-white/10 px-3 py-2">Emergency access, cable entry routes</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Transformers</td>
                      <td className="border border-white/10 px-3 py-2">External wall or fire-rated enclosure</td>
                      <td className="border border-white/10 px-3 py-2">Ventilation, noise, fire separation</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Distribution boards</td>
                      <td className="border border-white/10 px-3 py-2">Central to served areas</td>
                      <td className="border border-white/10 px-3 py-2">Cable route efficiency, accessibility</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Control panels (BMS/HVAC)</td>
                      <td className="border border-white/10 px-3 py-2">Near associated plant</td>
                      <td className="border border-white/10 px-3 py-2">Signal cable lengths, operator access</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Metering equipment</td>
                      <td className="border border-white/10 px-3 py-2">Accessible without entering plant area</td>
                      <td className="border border-white/10 px-3 py-2">Meter reading access, CT locations</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Services Coordination</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>3D modelling:</strong> Use BIM coordination to identify clashes before installation</li>
                <li className="pl-1"><strong>Vertical zoning:</strong> Establish service layers (drainage lowest, electrical highest)</li>
                <li className="pl-1"><strong>Horizontal corridors:</strong> Maintain clear routes for cable containment runs</li>
                <li className="pl-1"><strong>Equipment replacement:</strong> Consider removal routes for major plant items</li>
                <li className="pl-1"><strong>Structural coordination:</strong> Verify floor loadings and fixing positions</li>
              </ul>
            </div>

            <div className="my-6 p-4 rounded-lg bg-blue-500/10 border border-blue-500/30">
              <p className="text-sm font-medium text-blue-400 mb-2">Plant Room Sizing Guide</p>
              <div className="font-mono text-sm space-y-1">
                <p><span className="text-white/60">Rule of thumb:</span> <span className="text-white">Plant room area = 3-5% of gross building floor area</span></p>
                <p><span className="text-white/60">Height:</span> <span className="text-white">Minimum 3.0m clear, 3.5-4.0m preferred</span></p>
                <p><span className="text-white/60">Door size:</span> <span className="text-white">1200mm wide minimum, double doors for large equipment</span></p>
                <p><span className="text-white/60">Floor loading:</span> <span className="text-white">Typically 7.5-10 kN/m squared for equipment areas</span></p>
              </div>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Design coordination:</strong> Early engagement between electrical, mechanical, and architectural designers is essential. Establish equipment layouts before structural design is finalised to ensure adequate space and structural provisions.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 2: Access Requirements */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            Access Requirements
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Adequate access is fundamental to safe plant room operation and maintenance. BS 7671, CIBSE guides,
              and manufacturer requirements all specify minimum clearances that must be maintained throughout the
              installation's life. Access requirements influence not only layout but also the sizing of the plant
              room itself.
            </p>

            <div className="grid sm:grid-cols-3 gap-4 my-6">
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Front Access</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">1000mm minimum clear depth</li>
                  <li className="pl-1">Full width of switchgear</li>
                  <li className="pl-1">Door swing clearance</li>
                  <li className="pl-1">Arc flash safe distance</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Rear Access</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">600mm minimum where required</li>
                  <li className="pl-1">Cable termination space</li>
                  <li className="pl-1">Component replacement</li>
                  <li className="pl-1">May require lighting</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Side Access</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">200-300mm typical minimum</li>
                  <li className="pl-1">Manufacturer specified</li>
                  <li className="pl-1">Ventilation requirements</li>
                  <li className="pl-1">Section removal routes</li>
                </ul>
              </div>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Access Clearance Requirements</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Equipment</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Front</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Rear</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">LV switchboard</td>
                      <td className="border border-white/10 px-3 py-2">1000mm</td>
                      <td className="border border-white/10 px-3 py-2">600mm (if rear access)</td>
                      <td className="border border-white/10 px-3 py-2">Check arc flash requirements</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Distribution boards</td>
                      <td className="border border-white/10 px-3 py-2">800mm</td>
                      <td className="border border-white/10 px-3 py-2">N/A (wall-mounted)</td>
                      <td className="border border-white/10 px-3 py-2">Door opening clearance</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Transformers</td>
                      <td className="border border-white/10 px-3 py-2">1000mm</td>
                      <td className="border border-white/10 px-3 py-2">600mm all sides</td>
                      <td className="border border-white/10 px-3 py-2">Ventilation requirements</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Control panels</td>
                      <td className="border border-white/10 px-3 py-2">800mm</td>
                      <td className="border border-white/10 px-3 py-2">450mm</td>
                      <td className="border border-white/10 px-3 py-2">Cabling access</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Maintenance Access Considerations</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Equipment removal:</strong> Clear route from equipment to plant room door</li>
                <li className="pl-1"><strong>Lifting provisions:</strong> Overhead lifting beams or adequate headroom for mobile lifting</li>
                <li className="pl-1"><strong>Floor loadings:</strong> Adequate for equipment transport (pallet trucks, forklifts)</li>
                <li className="pl-1"><strong>Service isolation:</strong> Accessible isolators for maintenance work</li>
                <li className="pl-1"><strong>Test equipment:</strong> Space for test instruments during commissioning and maintenance</li>
              </ul>
            </div>

            <div className="my-6 p-4 rounded-lg bg-orange-500/10 border border-orange-500/30">
              <p className="text-sm font-medium text-orange-400 mb-2">Safety Requirements</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Emergency egress:</strong> Two exits required where travel distance exceeds 12m</li>
                <li className="pl-1"><strong>Floor surfaces:</strong> Non-slip finish, free from trip hazards</li>
                <li className="pl-1"><strong>Headroom:</strong> 2.1m minimum throughout, 2.4m preferred</li>
                <li className="pl-1"><strong>Emergency stops:</strong> Located near exits, clearly identified</li>
              </ul>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Future-proofing:</strong> Design access routes to accommodate potential equipment upgrades or replacements. Consider modular construction allowing section removal without major alterations.
            </p>
          </div>
        </section>

        {/* Section 3: Ventilation and Environmental Control */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Ventilation and Environmental Control
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Effective ventilation is critical for maintaining electrical equipment within its rated operating
              temperature. Heat generated by transformers, switchgear, cables, and electronic equipment must be
              removed to prevent premature failure and maintain protective device accuracy. CIBSE Guide B provides
              detailed guidance on plant room ventilation design.
            </p>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Heat Sources in Electrical Plant Rooms</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Equipment</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Typical Heat Loss</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Transformers (dry type)</td>
                      <td className="border border-white/10 px-3 py-2">2-3% of rated kVA</td>
                      <td className="border border-white/10 px-3 py-2">Higher at full load</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">LV switchgear</td>
                      <td className="border border-white/10 px-3 py-2">0.5-1% of throughput</td>
                      <td className="border border-white/10 px-3 py-2">Contact and conductor losses</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Power cables</td>
                      <td className="border border-white/10 px-3 py-2">I squared R losses</td>
                      <td className="border border-white/10 px-3 py-2">Varies with loading</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">UPS systems</td>
                      <td className="border border-white/10 px-3 py-2">5-15% of rated load</td>
                      <td className="border border-white/10 px-3 py-2">Includes battery charging</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Variable speed drives</td>
                      <td className="border border-white/10 px-3 py-2">2-5% of rated power</td>
                      <td className="border border-white/10 px-3 py-2">Requires local extraction</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid sm:grid-cols-2 gap-4 my-6">
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Natural Ventilation</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">Low-level intake, high-level exhaust</li>
                  <li className="pl-1">Inlet area 50% of exhaust area</li>
                  <li className="pl-1">Stack effect calculation required</li>
                  <li className="pl-1">Weather louvres for rain protection</li>
                  <li className="pl-1">Limited cooling capacity</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Mechanical Ventilation</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">Extract fans with motorised dampers</li>
                  <li className="pl-1">Temperature-controlled operation</li>
                  <li className="pl-1">25-35 l/s per kW heat gain</li>
                  <li className="pl-1">Standby fan for critical areas</li>
                  <li className="pl-1">BMS integration for monitoring</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-blue-500/10 border border-blue-500/30">
              <p className="text-sm font-medium text-blue-400 mb-2">Ventilation Calculation Example</p>
              <div className="font-mono text-sm space-y-1">
                <p><span className="text-white/60">Total heat dissipation:</span> <span className="text-white">15 kW (transformer 8kW, switchgear 4kW, cables 3kW)</span></p>
                <p><span className="text-white/60">Ventilation rate:</span> <span className="text-white">30 l/s per kW (standard)</span></p>
                <p><span className="text-white/60">Required airflow:</span> <span className="text-white">15 x 30 = 450 l/s</span></p>
                <p><span className="text-white/60">Temperature rise:</span> <span className="text-white">Q = m x Cp x delta T</span></p>
                <p><span className="text-white/60">With 10K rise:</span> <span className="text-white">External 28 degrees C + 10K = 38 degrees C max ambient</span></p>
                <p className="text-green-400 mt-2">Within 40 degrees C equipment rating - acceptable</p>
              </div>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Environmental Control Requirements</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Temperature:</strong> Maintain below 35-40 degrees Celsius (equipment rating dependent)</li>
                <li className="pl-1"><strong>Humidity:</strong> 40-60% RH to prevent condensation and static discharge</li>
                <li className="pl-1"><strong>Dust control:</strong> Filtered air intake, IP rating appropriate to environment</li>
                <li className="pl-1"><strong>Pressure:</strong> Slight positive pressure prevents dust ingress</li>
                <li className="pl-1"><strong>Monitoring:</strong> Temperature and humidity sensors with BMS alerts</li>
              </ul>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Critical consideration:</strong> Inadequate ventilation causes accelerated insulation degradation, increased contact resistance, and protective device nuisance tripping. Equipment life may be reduced by 50% for every 10 degrees Celsius above rated ambient.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 4: Lighting and Electrical Infrastructure */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Lighting and Electrical Infrastructure
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Plant room lighting must provide adequate illumination for safe equipment operation, maintenance tasks,
              and emergency egress. CIBSE SLL Lighting Guide and BS 5266 for emergency lighting establish the
              requirements. The electrical infrastructure must support the plant room's own requirements as well as
              providing distribution to the wider building.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Lighting Requirements (CIBSE SLL)</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Area/Task</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Maintained Illuminance</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Colour Rendering (Ra)</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">General plant room areas</td>
                      <td className="border border-white/10 px-3 py-2">200 lux minimum</td>
                      <td className="border border-white/10 px-3 py-2">&gt;60</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Control panels and switchgear faces</td>
                      <td className="border border-white/10 px-3 py-2">300 lux minimum</td>
                      <td className="border border-white/10 px-3 py-2">&gt;80</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Detailed maintenance work</td>
                      <td className="border border-white/10 px-3 py-2">500 lux (task lighting)</td>
                      <td className="border border-white/10 px-3 py-2">&gt;80</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Cable termination areas</td>
                      <td className="border border-white/10 px-3 py-2">300 lux minimum</td>
                      <td className="border border-white/10 px-3 py-2">&gt;80 (cable identification)</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Emergency lighting (high-risk)</td>
                      <td className="border border-white/10 px-3 py-2">10% of normal or 15 lux min</td>
                      <td className="border border-white/10 px-3 py-2">&gt;40</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid sm:grid-cols-2 gap-4 my-6">
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Lighting Design Considerations</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">Avoid shadows on switchgear operating faces</li>
                  <li className="pl-1">Luminaires positioned for maintenance access</li>
                  <li className="pl-1">Protection against mechanical damage (IP rating)</li>
                  <li className="pl-1">Local switching at plant room entrance</li>
                  <li className="pl-1">Separate circuits for general and task lighting</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Emergency Lighting (BS 5266)</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">High-risk task area classification</li>
                  <li className="pl-1">Minimum 10% of normal illuminance</li>
                  <li className="pl-1">3-hour rated duration</li>
                  <li className="pl-1">Self-contained or central battery</li>
                  <li className="pl-1">Monthly function tests required</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Switchboard Positioning</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Cable entry:</strong> Position to minimise cable route lengths and crossings</li>
                <li className="pl-1"><strong>Incoming supply:</strong> Locate main switchboard near service entry point</li>
                <li className="pl-1"><strong>Orientation:</strong> Operating face towards main access route</li>
                <li className="pl-1"><strong>Environmental:</strong> Away from heat sources, water services, vibration</li>
                <li className="pl-1"><strong>Expansion:</strong> Allow space for future panel extensions</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Cable Containment Systems</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">System</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Application</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Considerations</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Cable ladder</td>
                      <td className="border border-white/10 px-3 py-2">Heavy power cables</td>
                      <td className="border border-white/10 px-3 py-2">Good ventilation, easy installation</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Cable tray (perforated)</td>
                      <td className="border border-white/10 px-3 py-2">Medium cables, mixed services</td>
                      <td className="border border-white/10 px-3 py-2">Segregation dividers available</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Cable trunking</td>
                      <td className="border border-white/10 px-3 py-2">Distribution to boards</td>
                      <td className="border border-white/10 px-3 py-2">Mechanical protection, neat appearance</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Floor trenches</td>
                      <td className="border border-white/10 px-3 py-2">Switchboard entries</td>
                      <td className="border border-white/10 px-3 py-2">Fire-stopped covers required</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Earthing and Bonding Infrastructure</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Main earthing terminal (MET):</strong> Central connection point, clearly labelled, accessible for testing</li>
                <li className="pl-1"><strong>Earth bars:</strong> Copper earth bars for multiple circuit connections (minimum 25mm x 6mm)</li>
                <li className="pl-1"><strong>Main protective bonding:</strong> Connect incoming metallic services (water, gas, structural steel)</li>
                <li className="pl-1"><strong>Supplementary bonding:</strong> Connect simultaneously accessible extraneous-conductive-parts</li>
                <li className="pl-1"><strong>Containment bonding:</strong> Ensure electrical continuity of all metallic containment</li>
                <li className="pl-1"><strong>Lightning protection:</strong> Connection to LPS earth where applicable</li>
              </ul>
            </div>

            <div className="my-6 p-4 rounded-lg bg-blue-500/10 border border-blue-500/30">
              <p className="text-sm font-medium text-blue-400 mb-2">BS 7671 Earthing Requirements</p>
              <div className="font-mono text-sm space-y-1">
                <p><span className="text-white/60">Main bonding conductor:</span> <span className="text-white">Minimum 50% of earthing conductor (min 6mm squared Cu)</span></p>
                <p><span className="text-white/60">Earthing conductor:</span> <span className="text-white">Per Table 54.7 based on line conductor size</span></p>
                <p><span className="text-white/60">Supplementary bonding:</span> <span className="text-white">Minimum 4mm squared Cu (2.5mm squared if mechanically protected)</span></p>
                <p><span className="text-white/60">Earth bar:</span> <span className="text-white">Sized for connected conductors + 30% spare capacity</span></p>
              </div>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Cable route planning:</strong> Establish primary containment routes early in design. Maintain 30-50% spare capacity for future cables. Segregate power and data cables per BS 7671 requirements.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Worked Examples */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Worked Examples</h2>

          <div className="space-y-6">
            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 1: Ventilation Requirement Calculation</h3>
              <p className="text-sm text-white mb-2">
                <strong>Scenario:</strong> Calculate ventilation requirements for a plant room containing 500kVA transformer, main LV switchboard (400A), and distribution equipment.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p className="text-white/60">Heat sources:</p>
                <p className="ml-4">Transformer (500kVA x 2.5% loss) = 12.5 kW</p>
                <p className="ml-4">Switchgear (estimated) = 3 kW</p>
                <p className="ml-4">Cables and miscellaneous = 2.5 kW</p>
                <p className="ml-4">Total heat gain = 18 kW</p>
                <p className="mt-2">Ventilation calculation:</p>
                <p className="ml-4">Rate = 30 l/s per kW (standard for electrical plant)</p>
                <p className="ml-4">Required airflow = 18 x 30 = 540 l/s</p>
                <p className="mt-2">Extract fan specification:</p>
                <p className="ml-4">Minimum duty = 540 l/s at system pressure</p>
                <p className="ml-4">With 20% margin = 648 l/s design flow</p>
                <p className="mt-2 text-green-400">Select 2 x 400 l/s fans (duty/standby) for resilience</p>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 2: Lighting Design</h3>
              <p className="text-sm text-white mb-2">
                <strong>Scenario:</strong> Design lighting for a 10m x 6m plant room with 3.5m ceiling height.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p className="text-white/60">Requirements:</p>
                <p className="ml-4">General illuminance = 200 lux minimum</p>
                <p className="ml-4">Switchgear face = 300 lux</p>
                <p className="ml-4">Emergency = 10% or 15 lux minimum</p>
                <p className="mt-2">Lumen method calculation:</p>
                <p className="ml-4">Room area = 60 m squared</p>
                <p className="ml-4">Required lumens = E x A / (UF x MF)</p>
                <p className="ml-4">= 200 x 60 / (0.5 x 0.8) = 30,000 lumens</p>
                <p className="mt-2">Luminaire selection:</p>
                <p className="ml-4">LED battens 5000 lumens each</p>
                <p className="ml-4">Quantity = 30,000 / 5,000 = 6 luminaires</p>
                <p className="mt-2 text-green-400">Install 6 x LED battens in 2 rows of 3</p>
                <p className="text-white/60">+ 3 x emergency luminaires (self-contained)</p>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 3: Main Bonding Conductor Sizing</h3>
              <p className="text-sm text-white mb-2">
                <strong>Scenario:</strong> Determine main protective bonding conductor sizes for a plant room with 120mm squared earthing conductor.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p className="text-white/60">Given data:</p>
                <p className="ml-4">Earthing conductor = 120mm squared copper</p>
                <p className="ml-4">Water pipe = 54mm diameter</p>
                <p className="ml-4">Gas pipe = 42mm diameter</p>
                <p className="ml-4">Structural steel present</p>
                <p className="mt-2">BS 7671 Table 54.8 calculation:</p>
                <p className="ml-4">Main bonding = 50% of earthing conductor</p>
                <p className="ml-4">= 0.5 x 120 = 60mm squared</p>
                <p className="ml-4">Minimum = 6mm squared (not applicable here)</p>
                <p className="mt-2">Bonding conductor requirements:</p>
                <p className="ml-4">Water main = 70mm squared copper</p>
                <p className="ml-4">Gas main = 70mm squared copper</p>
                <p className="ml-4">Structural steel = 70mm squared copper</p>
                <p className="mt-2 text-green-400">All main bonding = 70mm squared Cu to MET</p>
              </div>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[3]} />

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Practical Guidance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Practical Guidance</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Plant Room Design Checklist</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1">Obtain equipment data sheets for all major items (dimensions, weights, heat output)</li>
                <li className="pl-1">Verify floor loading capacity for equipment and maintenance access</li>
                <li className="pl-1">Coordinate layout with mechanical and plumbing services</li>
                <li className="pl-1">Confirm access clearances meet manufacturer and regulatory requirements</li>
                <li className="pl-1">Calculate ventilation requirements and verify plant room can achieve required airflow</li>
                <li className="pl-1">Design lighting to achieve recommended illuminance levels</li>
                <li className="pl-1">Plan cable routes with adequate capacity and segregation</li>
                <li className="pl-1">Specify earthing and bonding arrangements per BS 7671</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Key Standards Reference</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>BS 7671:</strong> Wiring Regulations - installation requirements, earthing, bonding</li>
                <li className="pl-1"><strong>CIBSE Guide B:</strong> Heating, ventilating, air conditioning - ventilation design</li>
                <li className="pl-1"><strong>CIBSE SLL:</strong> Lighting Guide - illuminance requirements</li>
                <li className="pl-1"><strong>BSRIA BG 32:</strong> Designing Plant Rooms - layout guidance</li>
                <li className="pl-1"><strong>BS 5266:</strong> Emergency lighting requirements</li>
                <li className="pl-1"><strong>BS EN 61439:</strong> Switchgear assembly requirements</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-red-400/80 mb-2">Common Design Errors</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Inadequate ventilation:</strong> Undersized ventilation leading to overheating</li>
                <li className="pl-1"><strong>Poor access planning:</strong> Equipment installed without adequate maintenance access</li>
                <li className="pl-1"><strong>Insufficient lighting:</strong> Shadow areas preventing safe operation</li>
                <li className="pl-1"><strong>Cable route clashes:</strong> Containment conflicts with other services</li>
                <li className="pl-1"><strong>Omitting expansion space:</strong> No provision for future equipment or circuits</li>
                <li className="pl-1"><strong>Ignoring floor drainage:</strong> No provision for water ingress or cleaning</li>
              </ul>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <h3 className="text-sm font-medium text-white mb-1">{faq.question}</h3>
                <p className="text-sm text-white/90 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Quick Reference */}
        <section className="mb-10">
          <div className="p-5 rounded-lg bg-transparent">
            <h3 className="text-sm font-medium text-white mb-4">Quick Reference</h3>
            <div className="grid sm:grid-cols-2 gap-4 text-xs text-white">
              <div>
                <p className="font-medium text-white mb-1">Access Clearances</p>
                <ul className="space-y-0.5">
                  <li>Front of switchgear: 1000mm minimum</li>
                  <li>Rear access (where required): 600mm</li>
                  <li>Headroom: 2.1m minimum, 2.4m preferred</li>
                  <li>Door width: 1200mm minimum</li>
                </ul>
              </div>
              <div>
                <p className="font-medium text-white mb-1">Environmental Requirements</p>
                <ul className="space-y-0.5">
                  <li>Ambient temperature: &lt;35-40 degrees Celsius</li>
                  <li>Ventilation rate: 25-35 l/s per kW</li>
                  <li>Lighting: 200 lux general, 300 lux panels</li>
                  <li>Emergency lighting: 10% or 15 lux minimum</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Quiz */}
        <section className="mb-10">
          <Quiz
            title="Test Your Knowledge"
            questions={quizQuestions}
          />
        </section>

        {/* Navigation */}
        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section6">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section6-3">
              Next: Interface Coordination
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>

      </article>
    </div>
  );
};

export default HNCModule8Section6_2;
