import { ArrowLeft, Settings, CheckCircle, AlertTriangle, Wrench, Cable, Shield, Activity } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import useSEO from "@/hooks/useSEO";

const TITLE = "Installation and Commissioning - HNC Module 8 Section 4.6";
const DESCRIPTION = "Master VSD installation requirements including motor cable selection, screened cables, EMC considerations, drive parameter setup, acceleration/deceleration ramps, commissioning procedures, fault codes and troubleshooting common issues in HVAC applications.";

const quickCheckQuestions = [
  {
    id: "cable-screening",
    question: "Why must screened (shielded) cables be used between VSDs and motors?",
    options: ["To reduce cable cost", "To contain EMC emissions and protect nearby equipment", "To increase cable current rating", "To allow longer cable runs"],
    correctIndex: 1,
    explanation: "Screened cables contain the high-frequency emissions generated by PWM switching within the cable screen, preventing electromagnetic interference with nearby sensitive equipment such as BMS sensors, communication networks and instrumentation."
  },
  {
    id: "emc-filter",
    question: "Where should an EMC filter be installed in a VSD system?",
    options: ["Between the motor and drive", "At the motor terminals", "At the supply input to the drive", "In the control circuit only"],
    correctIndex: 2,
    explanation: "EMC filters are installed at the supply input to the drive to prevent high-frequency switching noise from being conducted back onto the mains supply where it could affect other equipment and cause radio frequency interference."
  },
  {
    id: "accel-ramp",
    question: "What is the typical default acceleration time for HVAC fan and pump applications?",
    options: ["1-2 seconds", "5-15 seconds", "30-60 seconds", "120 seconds"],
    correctIndex: 1,
    explanation: "HVAC applications typically use acceleration times of 5-15 seconds for fans and pumps. This provides smooth starting, reduces mechanical stress on couplings and belts, and prevents water hammer in pumping systems. Longer ramps may be needed for high-inertia loads."
  },
  {
    id: "fault-overcurrent",
    question: "What is the most likely cause of an overcurrent fault immediately upon starting a VSD?",
    options: ["Motor insulation failure", "Earth fault in motor cable", "Incorrect motor parameters entered", "Supply undervoltage"],
    correctIndex: 2,
    explanation: "Incorrect motor parameters (particularly motor current rating) entered during commissioning often cause immediate overcurrent faults. The drive calculates expected current based on entered parameters, and mismatches trigger protective trips. Always verify motor nameplate data matches drive settings."
  }
];

const quizQuestions = [
  {
    id: 1,
    question: "What type of cable is recommended for VSD-to-motor connections in HVAC installations?",
    options: [
      "Standard PVC singles in conduit",
      "Screened/shielded cable with symmetrical construction",
      "Armoured cable without screen",
      "Flat twin and earth cable"
    ],
    correctAnswer: 1,
    explanation: "Screened/shielded cables with symmetrical construction (e.g., SY, CY or dedicated VSD cable) are required to contain EMC emissions. The screen must be earthed at both ends with 360-degree termination for effective EMI containment."
  },
  {
    id: 2,
    question: "What is the maximum recommended cable length between VSD and motor without additional measures?",
    options: [
      "10 metres",
      "50-100 metres depending on drive and cable type",
      "500 metres",
      "There is no limit"
    ],
    correctAnswer: 1,
    explanation: "Typical maximum cable lengths are 50-100 metres depending on drive switching frequency, cable type and motor characteristics. Longer runs may require output reactors/filters to reduce voltage reflections and motor insulation stress. Always consult manufacturer guidelines."
  },
  {
    id: 3,
    question: "Why should VSD motor cables be routed separately from control and signal cables?",
    options: [
      "To save installation costs",
      "To prevent electromagnetic interference coupling",
      "To comply with cable colour regulations",
      "To allow easier maintenance access"
    ],
    correctAnswer: 1,
    explanation: "VSD output cables carry high-frequency PWM switching waveforms that can couple electromagnetically into nearby signal cables, causing interference with sensors, BMS communications and control signals. A minimum separation of 300mm is typically required, with crossings at 90 degrees."
  },
  {
    id: 4,
    question: "What is the purpose of a dV/dt filter (motor choke) on VSD outputs?",
    options: [
      "To increase motor efficiency",
      "To reduce voltage spikes and protect motor insulation",
      "To improve power factor",
      "To increase motor speed range"
    ],
    correctAnswer: 1,
    explanation: "dV/dt filters reduce the rate of voltage rise from PWM switching, protecting motor insulation from voltage spikes caused by cable reflections. They are essential for long cable runs and older motors not designed for inverter duty."
  },
  {
    id: 5,
    question: "When commissioning a VSD for a centrifugal pump, which parameter critically affects pump performance?",
    options: [
      "Display contrast setting",
      "Minimum frequency setting",
      "Keypad lock code",
      "Parameter copy function"
    ],
    correctAnswer: 1,
    explanation: "Minimum frequency setting is critical for pumps - setting it too low can cause the pump to operate below its minimum flow requirement, causing overheating, cavitation or reverse flow. Typically 20-30Hz minimum is appropriate for centrifugal pumps."
  },
  {
    id: 6,
    question: "What does an 'Earth Fault' or 'Ground Fault' trip on a VSD typically indicate?",
    options: [
      "The supply earth is disconnected",
      "Insulation breakdown in motor or cable to earth",
      "The motor is overloaded",
      "Supply voltage is too high"
    ],
    correctAnswer: 1,
    explanation: "Earth fault trips indicate current leaking from a phase conductor to earth, typically caused by damaged motor windings, cable insulation failure, moisture ingress, or contamination. Insulation resistance testing of motor and cables is required to locate the fault."
  },
  {
    id: 7,
    question: "What is the correct procedure for earthing screened VSD motor cables?",
    options: [
      "Earth the screen at the motor end only",
      "Earth the screen at the drive end only",
      "Earth the screen at both ends with 360-degree termination",
      "Leave the screen floating (not earthed)"
    ],
    correctAnswer: 2,
    explanation: "Screens must be earthed at both ends using 360-degree (gland) termination for effective EMC containment. Single-point earthing or pigtail connections reduce screening effectiveness and can create antenna effects, increasing EMC emissions."
  },
  {
    id: 8,
    question: "What parameter should be set to match the motor's rated current on the nameplate?",
    options: [
      "Maximum frequency",
      "Motor nominal current (In)",
      "Acceleration time",
      "Braking resistor value"
    ],
    correctAnswer: 1,
    explanation: "Motor nominal current must be set accurately from the motor nameplate (FLC - Full Load Current). This value is used for motor thermal protection, current limiting and flux vector control. Incorrect settings can cause nuisance trips or inadequate protection."
  },
  {
    id: 9,
    question: "Why might a VSD show an 'Undervoltage' fault during motor deceleration?",
    options: [
      "The motor is too small",
      "Regenerated energy is raising DC bus voltage",
      "The supply fuse has blown",
      "Motor cable is too long"
    ],
    correctAnswer: 1,
    explanation: "During rapid deceleration, the motor acts as a generator, pumping energy back to the drive DC bus. If the bus voltage exceeds limits, a DC overvoltage or undervoltage fault occurs. Solutions include longer deceleration ramps or braking resistors for high-inertia loads."
  },
  {
    id: 10,
    question: "What EMC standard classification typically applies to VSDs in industrial HVAC applications?",
    options: [
      "Category C1 - unrestricted distribution",
      "Category C2 - restricted distribution (second environment)",
      "Category C3 - industrial only",
      "No EMC requirements apply"
    ],
    correctAnswer: 1,
    explanation: "Most industrial HVAC applications fall under Category C2 (second environment/industrial), requiring appropriate EMC filters and installation practices. Category C1 is for residential/first environment and has stricter emission limits requiring additional filtering."
  },
  {
    id: 11,
    question: "What should be checked before energising a newly installed VSD for the first time?",
    options: [
      "Motor direction only",
      "Motor and cable insulation resistance, connections, and parameter settings",
      "Only the supply voltage",
      "Motor nameplate data only"
    ],
    correctAnswer: 1,
    explanation: "Pre-energisation checks must include: insulation resistance of motor and cables (&gt;1M ohm), all connections tight and correct, earth continuity, motor nameplate data recorded, basic parameters set, and mechanical safety (coupling guards, isolation)."
  },
  {
    id: 12,
    question: "What is the typical switching frequency range for modern HVAC VSDs?",
    options: [
      "50-100 Hz",
      "2-16 kHz",
      "50-100 kHz",
      "1-5 MHz"
    ],
    correctAnswer: 1,
    explanation: "Modern VSDs typically operate at 2-16 kHz switching frequency. Higher frequencies reduce motor noise but increase cable EMC emissions and switching losses. HVAC applications often use 4-8 kHz as a compromise between acoustic noise and EMC performance."
  }
];

const faqs = [
  {
    question: "Can I use standard SWA cable for VSD-to-motor connections?",
    answer: "Standard steel wire armoured (SWA) cable is not ideal for VSD applications as the armour does not provide effective high-frequency screening. Dedicated VSD cables with braided copper screens, or SY/CY flexible screened cables, provide much better EMC containment. If SWA must be used, additional EMC filters and output reactors may be required, and cable lengths should be minimised."
  },
  {
    question: "Why does my VSD cause interference with BMS sensors?",
    answer: "VSD interference with BMS sensors typically results from: inadequate cable separation (motor cables too close to signal cables), poor screen earthing (pigtails instead of 360-degree termination), missing EMC filters, or high switching frequency settings. Solutions include routing cables separately with minimum 300mm spacing, proper gland terminations for screens, installing appropriate EMC filters, and potentially reducing switching frequency."
  },
  {
    question: "How do I determine the correct acceleration/deceleration times?",
    answer: "Acceleration times depend on load inertia, motor rating and application requirements. For HVAC fans and pumps, 5-15 seconds is typical. High-inertia loads (large fans, flywheels) need longer ramps to prevent overcurrent trips. Pumps need controlled acceleration to prevent water hammer. Start with manufacturer defaults and adjust based on observed behaviour - increase times if overcurrent trips occur during acceleration."
  },
  {
    question: "What causes nuisance earth fault trips on VSDs?",
    answer: "Nuisance earth fault trips can result from: long motor cables with high capacitance, multiple motors on one drive, moisture in motor terminal boxes, EMC filter earth leakage currents, or sensitive earth fault trip settings. Solutions include using output reactors to reduce cable charging current, checking and improving motor insulation, verifying filter specifications, and adjusting earth fault trip level if motor and cable insulation tests pass."
  },
  {
    question: "Do I need to use inverter-duty motors with VSDs?",
    answer: "For new installations, inverter-duty (VSD-rated) motors are strongly recommended. They have enhanced insulation systems (Class H or higher), reinforced bearings, improved cooling at low speeds, and are designed for PWM voltage waveforms. Standard motors can be used with VSDs but may require output filters for long cable runs, may have reduced service life, and should not operate below 20-30% speed without supplementary cooling."
  },
  {
    question: "What commissioning documentation should I prepare?",
    answer: "VSD commissioning documentation should include: motor nameplate data and as-found insulation resistance, drive parameter settings (screenshot or printout), cable types and lengths, EMC filter details, functional tests performed (start/stop, speed range, trips), analogue input/output calibrations, fault history cleared, handover training records, and manufacturer contact details for technical support."
  }
];

const HNCModule8Section4_6 = () => {
  useSEO(TITLE, DESCRIPTION);

  return (
    <div className="overflow-x-hidden bg-[#1a1a1a]">
      {/* Minimal Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <article className="px-4 sm:px-6 py-8 sm:py-12">

        {/* Centred Title */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Settings className="h-4 w-4" />
            <span>Module 8.4.6</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            Installation and Commissioning
          </h1>
          <p className="text-white/80">
            Cable requirements, EMC considerations, drive setup and fault finding for VSD installations
          </p>
        </header>

        {/* Quick Summary Boxes */}
        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2">In 30 Seconds</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
              <li className="pl-1"><strong>Screened cables:</strong> Essential for EMC compliance</li>
              <li className="pl-1"><strong>EMC filters:</strong> Required at drive supply input</li>
              <li className="pl-1"><strong>360-degree earthing:</strong> Screens at both cable ends</li>
              <li className="pl-1"><strong>Motor parameters:</strong> Must match nameplate exactly</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2">Building Services Context</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
              <li className="pl-1"><strong>Accel/decel ramps:</strong> 5-15s typical for HVAC</li>
              <li className="pl-1"><strong>Minimum frequency:</strong> 20-30Hz for centrifugal pumps</li>
              <li className="pl-1"><strong>Cable separation:</strong> 300mm from signal cables</li>
              <li className="pl-1"><strong>Commissioning:</strong> Document all parameters</li>
            </ul>
          </div>
        </div>

        {/* Learning Outcomes */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You Will Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              "Select appropriate motor cables for VSD applications",
              "Understand EMC requirements and filter selection",
              "Apply correct cable screening and earthing techniques",
              "Configure essential drive parameters for HVAC loads",
              "Set appropriate acceleration and deceleration ramps",
              "Perform systematic commissioning procedures",
              "Interpret common VSD fault codes and alarms",
              "Troubleshoot typical installation problems"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 mb-12" />

        {/* Section 1: Motor Cable Requirements */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            Motor Cable Requirements for VSD Applications
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Variable speed drives generate high-frequency pulse width modulation (PWM) waveforms that place
              unique demands on motor cables. Unlike conventional DOL motor circuits, VSD cables must contain
              electromagnetic emissions, withstand voltage reflections, and maintain motor insulation integrity.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">VSD Cable Selection Criteria</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Screened/shielded construction:</strong> Braided copper screen or foil with drain wire</li>
                <li className="pl-1"><strong>Symmetrical geometry:</strong> Three phases plus earth in balanced configuration</li>
                <li className="pl-1"><strong>Low capacitance:</strong> Reduces charging current and earth leakage</li>
                <li className="pl-1"><strong>Appropriate voltage rating:</strong> Consider voltage spikes from reflections</li>
                <li className="pl-1"><strong>Flexible construction:</strong> For motor terminal box connections</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Recommended Cable Types</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Cable Type</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Construction</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Application</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Dedicated VSD cable</td>
                      <td className="border border-white/10 px-3 py-2">Symmetrical cores, copper braid screen, PE outer</td>
                      <td className="border border-white/10 px-3 py-2">Preferred for all VSD installations</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">SY/CY cable</td>
                      <td className="border border-white/10 px-3 py-2">Steel or copper braided screen, flexible</td>
                      <td className="border border-white/10 px-3 py-2">Suitable for shorter runs, panel connections</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Screened SWA</td>
                      <td className="border border-white/10 px-3 py-2">Armour over copper tape screen</td>
                      <td className="border border-white/10 px-3 py-2">Where mechanical protection required</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">EMC-compliant trunking</td>
                      <td className="border border-white/10 px-3 py-2">Metal trunking with bonded joints</td>
                      <td className="border border-white/10 px-3 py-2">Alternative to screened cable if properly installed</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Cable Length Considerations</p>
              <p className="text-sm text-white/90 mb-3">
                Long motor cables cause voltage reflections that stress motor insulation. The reflected wave
                can double the peak voltage at motor terminals, particularly with fast-switching IGBTs.
              </p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Cable Length</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Recommended Measures</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">&lt; 25m</td>
                      <td className="border border-white/10 px-3 py-2">Screened cable usually sufficient</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">25-100m</td>
                      <td className="border border-white/10 px-3 py-2">Consider output reactor (choke) at drive</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">&gt; 100m</td>
                      <td className="border border-white/10 px-3 py-2">dV/dt filter or sine-wave filter essential</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-orange-500/10 border border-orange-500/30">
              <p className="text-sm font-medium text-orange-400 mb-2">Important: Motor Insulation</p>
              <p className="text-sm text-white/90">
                Standard motors may not withstand the voltage stresses from VSD operation, particularly on long
                cable runs. Inverter-duty motors with reinforced insulation (typically rated for 1600V peak or
                Class F/H insulation systems) are recommended for all new installations. For existing motors,
                output filters should be considered.
              </p>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Key rule:</strong> Cable selection affects EMC compliance, motor life and system reliability.
              Never substitute standard cable types to reduce costs.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 2: EMC Considerations */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            EMC Considerations and Filtering
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Electromagnetic compatibility (EMC) is a critical consideration for VSD installations. The
              high-frequency switching generates both conducted and radiated emissions that can interfere
              with nearby equipment including BMS systems, radio communications and sensitive instrumentation.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Sources of EMC Emissions</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Conducted emissions:</strong> High-frequency noise conducted back onto mains supply</li>
                <li className="pl-1"><strong>Radiated emissions:</strong> Electromagnetic fields from motor cables acting as antennas</li>
                <li className="pl-1"><strong>Common-mode currents:</strong> High-frequency currents flowing through earth paths</li>
                <li className="pl-1"><strong>Bearing currents:</strong> Capacitively coupled currents through motor bearings</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">EMC Installation Categories</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Category</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Environment</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Typical Requirements</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">C1 (First environment)</td>
                      <td className="border border-white/10 px-3 py-2">Domestic, commercial, light industrial</td>
                      <td className="border border-white/10 px-3 py-2">Strictest limits, internal EMC filter + external filter often required</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">C2 (Second environment)</td>
                      <td className="border border-white/10 px-3 py-2">Industrial, restricted distribution</td>
                      <td className="border border-white/10 px-3 py-2">Less strict, internal EMC filter typically sufficient</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">C3 (Industrial only)</td>
                      <td className="border border-white/10 px-3 py-2">Dedicated industrial installation</td>
                      <td className="border border-white/10 px-3 py-2">No conducted emission limits (radiated only)</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">EMC Filter Functions</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Common-mode choke:</strong> Blocks high-frequency noise on all conductors</li>
                  <li className="pl-1"><strong>Differential-mode inductors:</strong> Filter line-to-line noise</li>
                  <li className="pl-1"><strong>X capacitors:</strong> Line-to-line decoupling</li>
                  <li className="pl-1"><strong>Y capacitors:</strong> Line-to-earth decoupling</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Filter Installation Points</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Supply input:</strong> Main EMC filter location</li>
                  <li className="pl-1"><strong>Motor output:</strong> dV/dt or sine-wave filter if required</li>
                  <li className="pl-1"><strong>Control inputs:</strong> Ferrite cores on signal cables</li>
                  <li className="pl-1"><strong>Encoder cables:</strong> Screened with separate earthing</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Cable Screening and Earthing</p>
              <p className="text-sm text-white/90 mb-3">
                Proper screen termination is critical for EMC performance. The screen provides a low-impedance
                path for high-frequency currents, preventing them from radiating as interference.
              </p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>360-degree termination:</strong> Use EMC glands providing full circumferential contact</li>
                <li className="pl-1"><strong>Both ends:</strong> Earth screen at both drive and motor ends</li>
                <li className="pl-1"><strong>Avoid pigtails:</strong> Pigtail earth connections act as antennas at high frequency</li>
                <li className="pl-1"><strong>Continuous bonding:</strong> Ensure electrical continuity of metallic enclosures</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Cable Routing Best Practice</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Separation:</strong> Minimum 300mm between motor cables and signal/control cables</li>
                <li className="pl-1"><strong>Crossings:</strong> Where cables must cross, do so at 90 degrees</li>
                <li className="pl-1"><strong>Parallel runs:</strong> Avoid parallel routing with sensitive cables</li>
                <li className="pl-1"><strong>Metal containment:</strong> Use metal trunking/tray with bonded joints</li>
                <li className="pl-1"><strong>BMS cables:</strong> Route well away from VSD motor cables</li>
              </ul>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>HVAC context:</strong> Building management systems are particularly susceptible to VSD
              interference. Proper EMC installation prevents false readings, communication errors and control
              instability.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 3: Drive Parameter Setup */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Drive Parameter Setup
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Correct parameter configuration is essential for safe and efficient VSD operation. Modern drives
              contain hundreds of parameters, but a core set must be configured correctly during commissioning
              for the drive to match the motor and application requirements.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Essential Motor Parameters</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Parameter</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Source</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Purpose</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor nominal current (In)</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate FLC</td>
                      <td className="border border-white/10 px-3 py-2">Thermal protection, current limit</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor nominal voltage (Un)</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate</td>
                      <td className="border border-white/10 px-3 py-2">V/f ratio calculation</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor nominal frequency</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate (50Hz UK)</td>
                      <td className="border border-white/10 px-3 py-2">Base frequency for V/f control</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor nominal speed</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate RPM</td>
                      <td className="border border-white/10 px-3 py-2">Slip calculation, speed feedback</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor power (Pn)</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate kW</td>
                      <td className="border border-white/10 px-3 py-2">Auto-tuning, parameter estimation</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor cos phi</td>
                      <td className="border border-white/10 px-3 py-2">Nameplate power factor</td>
                      <td className="border border-white/10 px-3 py-2">Magnetising current calculation</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Motor Auto-Tune (ID Run)</p>
              <p className="text-sm text-white/90 mb-3">
                Most modern drives include an auto-tune or motor identification function that measures motor
                electrical parameters for optimal control. This should be performed during commissioning.
              </p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Stationary tune:</strong> Measures resistance and inductance with motor stopped</li>
                <li className="pl-1"><strong>Rotating tune:</strong> Measures at various speeds (motor must be uncoupled)</li>
                <li className="pl-1"><strong>Benefits:</strong> Improved efficiency, better dynamic response, accurate current control</li>
                <li className="pl-1"><strong>When to perform:</strong> After entering motor nameplate data, before commissioning</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Acceleration and Deceleration Ramps</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Application</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Typical Accel Time</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Typical Decel Time</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Considerations</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Centrifugal pumps</td>
                      <td className="border border-white/10 px-3 py-2">5-15 seconds</td>
                      <td className="border border-white/10 px-3 py-2">10-30 seconds</td>
                      <td className="border border-white/10 px-3 py-2">Prevent water hammer, check valves</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Centrifugal fans</td>
                      <td className="border border-white/10 px-3 py-2">10-30 seconds</td>
                      <td className="border border-white/10 px-3 py-2">20-60 seconds</td>
                      <td className="border border-white/10 px-3 py-2">High inertia, belt slip prevention</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">AHU supply fans</td>
                      <td className="border border-white/10 px-3 py-2">15-45 seconds</td>
                      <td className="border border-white/10 px-3 py-2">30-90 seconds</td>
                      <td className="border border-white/10 px-3 py-2">Large inertia, avoid regeneration</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Cooling towers</td>
                      <td className="border border-white/10 px-3 py-2">20-60 seconds</td>
                      <td className="border border-white/10 px-3 py-2">Coast to stop</td>
                      <td className="border border-white/10 px-3 py-2">Very high inertia fans</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Frequency Limits</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Maximum frequency:</strong> Typically 50-60Hz for fans/pumps</li>
                  <li className="pl-1"><strong>Minimum frequency:</strong> 20-30Hz for centrifugal pumps</li>
                  <li className="pl-1"><strong>Skip frequencies:</strong> Avoid mechanical resonance bands</li>
                  <li className="pl-1"><strong>Base frequency:</strong> Motor rated frequency (50Hz)</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Control Mode Selection</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>V/f control:</strong> Standard for fans and pumps</li>
                  <li className="pl-1"><strong>V/f with flux optimisation:</strong> Energy saving mode</li>
                  <li className="pl-1"><strong>Sensorless vector:</strong> Better dynamic response</li>
                  <li className="pl-1"><strong>Closed-loop vector:</strong> Precise speed control (encoder)</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Analogue Input/Output Configuration</p>
              <p className="text-sm text-white/90 mb-3">
                HVAC applications typically use 0-10V or 4-20mA signals from BMS for speed reference and feedback.
              </p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Speed reference:</strong> 0-10V = 0-100% speed (or 4-20mA)</li>
                <li className="pl-1"><strong>Speed feedback:</strong> 0-10V output proportional to actual speed</li>
                <li className="pl-1"><strong>Run status:</strong> Relay output indicating drive running</li>
                <li className="pl-1"><strong>Fault status:</strong> Relay output indicating fault condition</li>
              </ul>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Documentation:</strong> Always record all parameter settings during commissioning. Many
              drives allow parameter backup to memory card or PC for restoration and documentation.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Section 4: Commissioning and Fault Finding */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Commissioning Procedures and Fault Finding
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Systematic commissioning ensures safe, reliable VSD operation. A structured approach prevents
              damage to equipment and identifies installation issues before they cause operational problems.
              Understanding fault codes enables rapid diagnosis of problems.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Pre-Commissioning Checks</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Visual inspection:</strong> Check all connections, cable routing, gland terminations</li>
                <li className="pl-1"><strong>Motor insulation:</strong> Measure IR with motor disconnected (&gt;1M ohm at 500V DC)</li>
                <li className="pl-1"><strong>Cable insulation:</strong> Test motor cables separately from motor</li>
                <li className="pl-1"><strong>Earth continuity:</strong> Verify protective conductor continuity</li>
                <li className="pl-1"><strong>Supply voltage:</strong> Confirm within drive specification (+/-10% typical)</li>
                <li className="pl-1"><strong>Mechanical checks:</strong> Coupling alignment, guards fitted, rotation free</li>
              </ul>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Commissioning Sequence</p>
              <div className="bg-black/30 p-3 rounded text-sm text-white/90">
                <p className="mb-1"><strong>Step 1:</strong> Enter motor nameplate parameters</p>
                <p className="mb-1"><strong>Step 2:</strong> Set acceleration/deceleration times for application</p>
                <p className="mb-1"><strong>Step 3:</strong> Configure frequency limits (min/max)</p>
                <p className="mb-1"><strong>Step 4:</strong> Run motor auto-tune (if available)</p>
                <p className="mb-1"><strong>Step 5:</strong> Check rotation direction at low speed (10Hz)</p>
                <p className="mb-1"><strong>Step 6:</strong> Gradually increase speed, observe motor and load</p>
                <p className="mb-1"><strong>Step 7:</strong> Check vibration at various speeds (avoid resonances)</p>
                <p className="mb-1"><strong>Step 8:</strong> Verify current draw against motor rating</p>
                <p className="mb-1"><strong>Step 9:</strong> Test control signals (analogue, digital I/O)</p>
                <p><strong>Step 10:</strong> Document all parameter settings and test results</p>
              </div>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Common VSD Fault Codes</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Fault Type</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Typical Causes</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Investigation Steps</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Overcurrent (OC)</td>
                      <td className="border border-white/10 px-3 py-2">Short circuit, earth fault, incorrect parameters, seized motor</td>
                      <td className="border border-white/10 px-3 py-2">Check motor IR, verify parameters, inspect for mechanical jam</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Earth Fault (EF)</td>
                      <td className="border border-white/10 px-3 py-2">Motor winding fault, cable damage, moisture ingress</td>
                      <td className="border border-white/10 px-3 py-2">Insulation resistance test motor and cable separately</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">DC Overvoltage (OV)</td>
                      <td className="border border-white/10 px-3 py-2">Rapid deceleration, high inertia load, regenerating</td>
                      <td className="border border-white/10 px-3 py-2">Increase decel time, consider braking resistor</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">DC Undervoltage (UV)</td>
                      <td className="border border-white/10 px-3 py-2">Supply dips, supply loss, loose connections</td>
                      <td className="border border-white/10 px-3 py-2">Check supply voltage and connections</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Motor Overload (OL)</td>
                      <td className="border border-white/10 px-3 py-2">Overload condition, incorrect motor current setting</td>
                      <td className="border border-white/10 px-3 py-2">Verify motor In parameter, check load condition</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Overtemperature (OT)</td>
                      <td className="border border-white/10 px-3 py-2">Blocked cooling, high ambient, overload</td>
                      <td className="border border-white/10 px-3 py-2">Clean filters, check ventilation, reduce load</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2 font-medium">Output Phase Loss</td>
                      <td className="border border-white/10 px-3 py-2">Open circuit in motor or cable, loose connection</td>
                      <td className="border border-white/10 px-3 py-2">Check motor and cable continuity</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-orange-500/10 border border-orange-500/30">
              <p className="text-sm font-medium text-orange-400 mb-2">Troubleshooting Intermittent Faults</p>
              <p className="text-sm text-white/90">
                Intermittent faults are often the most difficult to diagnose. Check drive fault history for
                patterns (time of day, operating conditions). Common causes include: loose connections that
                make/break under vibration, EMC interference from nearby equipment, supply voltage variations
                during building peak loads, and thermal issues that appear only when drive/motor reaches
                operating temperature.
              </p>
            </div>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Diagnostic Tools</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Drive keypad:</strong> Fault history, real-time monitoring</li>
                  <li className="pl-1"><strong>Multimeter:</strong> Voltage, current, continuity checks</li>
                  <li className="pl-1"><strong>Insulation tester:</strong> Motor and cable IR testing</li>
                  <li className="pl-1"><strong>Clamp meter:</strong> Phase balance, earth leakage</li>
                  <li className="pl-1"><strong>Oscilloscope:</strong> Advanced waveform analysis</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">When to Replace vs Repair</p>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Replace drive:</strong> IGBT failure, control board fault</li>
                  <li className="pl-1"><strong>Repair on-site:</strong> Blown fuses, loose connections</li>
                  <li className="pl-1"><strong>Replace motor:</strong> Winding failure, bearing seizure</li>
                  <li className="pl-1"><strong>Replace cable:</strong> Insulation breakdown, screen damage</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Handover Documentation</p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Parameter list:</strong> All configured parameters with values</li>
                <li className="pl-1"><strong>Test results:</strong> Insulation resistance, functional tests</li>
                <li className="pl-1"><strong>Commissioning sheet:</strong> Date, engineer, tests performed</li>
                <li className="pl-1"><strong>O&M manuals:</strong> Drive and motor documentation</li>
                <li className="pl-1"><strong>Training records:</strong> Client staff trained on basic operation</li>
                <li className="pl-1"><strong>Warranty information:</strong> Supplier and manufacturer contacts</li>
              </ul>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Best practice:</strong> Clear the fault history after successful commissioning so any
              future faults are easily identifiable. Record a baseline of normal operating parameters for
              future reference.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[3]} />

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Worked Examples */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Worked Examples</h2>

          <div className="space-y-6">
            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 1: Cable Selection for AHU Fan</h3>
              <p className="text-sm text-white mb-2">
                <strong>Question:</strong> An 11kW AHU supply fan motor is located 45 metres from the VSD
                panel. The motor FLC is 22A. Select an appropriate cable and specify any additional measures.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p>Motor current: 22A</p>
                <p>Cable selection: 4mm squared 3-core + earth screened VSD cable</p>
                <p>(Rated approximately 30A depending on installation method)</p>
                <p className="mt-2">Cable length: 45m - within typical limits (50-100m)</p>
                <p>Additional measures at this length:</p>
                <p>- Consider output reactor (choke) at drive if motor not inverter-duty</p>
                <p>- Use 360-degree EMC glands at both ends</p>
                <p>- Route separately from BMS signal cables (300mm min)</p>
                <p className="mt-2 text-green-400">Recommendation: 4mm sq. screened VSD cable with output reactor</p>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 2: Acceleration Time Calculation</h3>
              <p className="text-sm text-white mb-2">
                <strong>Question:</strong> A 15kW centrifugal fan has a moment of inertia of 12 kg.m squared and
                runs at 1450 rpm. The drive current limit is set at 150% of motor FLC. Calculate the minimum
                acceleration time to avoid overcurrent trips.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p>Motor power: 15kW at 1450 rpm</p>
                <p>Motor torque Tn = (P x 9550) / n = (15 x 9550) / 1450 = 98.8 Nm</p>
                <p className="mt-2">Available accelerating torque at 150% current:</p>
                <p>Ta = 1.5 x Tn = 1.5 x 98.8 = 148.2 Nm (assuming linear T-I relationship)</p>
                <p className="mt-2">Angular acceleration: alpha = T / J = 148.2 / 12 = 12.35 rad/s squared</p>
                <p className="mt-2">Final speed: omega = (1450 x 2 x pi) / 60 = 151.8 rad/s</p>
                <p className="mt-2">Minimum acceleration time:</p>
                <p>t = omega / alpha = 151.8 / 12.35 = <strong>12.3 seconds minimum</strong></p>
                <p className="mt-2 text-white/60">Set acceleration time to 15-20 seconds to allow margin</p>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 3: Troubleshooting Earth Fault</h3>
              <p className="text-sm text-white mb-2">
                <strong>Scenario:</strong> A VSD supplying a chilled water pump trips on earth fault after
                running for 2-3 hours. The fault does not occur on initial start-up.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p>Diagnostic steps:</p>
                <p className="mt-2">1. Check insulation resistance when motor is cold: 15M ohm - PASS</p>
                <p>2. Run motor from drive until fault occurs</p>
                <p>3. Immediately test IR when warm: 0.8M ohm - MARGINAL</p>
                <p className="mt-2">Analysis:</p>
                <p>- IR drops significantly when motor heated</p>
                <p>- Indicates moisture ingress or insulation degradation</p>
                <p>- Common with pumps due to humid environment</p>
                <p className="mt-2">Investigation:</p>
                <p>- Motor terminal box inspected - condensation present</p>
                <p>- Cable gland not properly sealed</p>
                <p className="mt-2 text-green-400">Solution: Dry out motor, reseal terminal box, install breather</p>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Example 4: EMC Filter Selection</h3>
              <p className="text-sm text-white mb-2">
                <strong>Question:</strong> A 7.5kW VSD is being installed in a hospital plantroom (C1
                environment). The drive has a basic internal EMC filter. Specify additional EMC requirements.
              </p>
              <div className="bg-black/30 p-3 rounded text-sm font-mono text-white/90">
                <p>Environment: Hospital = sensitive electromagnetic environment (C1)</p>
                <p>C1 requires strictest EMC emission limits</p>
                <p className="mt-2">Requirements:</p>
                <p>1. External EMC filter at drive input (matched to drive rating)</p>
                <p>   - Filter rating: 7.5kW / 3-phase / 400V</p>
                <p>   - Select filter with C1 compliance certification</p>
                <p className="mt-2">2. Screened motor cable with 360-degree termination</p>
                <p>3. Output reactor if motor cable &gt; 25m</p>
                <p>4. Ferrite cores on control cables</p>
                <p>5. Metal back-plate with dedicated EMC earth bar</p>
                <p className="mt-2 text-green-400">Note: Install EMC filter as close to drive as possible</p>
                <p className="text-green-400">Maximum 300mm between filter and drive</p>
              </div>
            </div>
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Practical Guidance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Practical Guidance</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Pre-Commissioning Checklist</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Motor IR test:</strong> &gt;1M ohm at 500V DC minimum (&gt;100M ohm preferred)</li>
                <li className="pl-1"><strong>Cable IR test:</strong> &gt;1M ohm with motor disconnected</li>
                <li className="pl-1"><strong>Earth continuity:</strong> &lt;0.5 ohm from MET to motor frame</li>
                <li className="pl-1"><strong>Supply voltage:</strong> Verify within +/-10% of drive rating</li>
                <li className="pl-1"><strong>Phase sequence:</strong> Check if drive requires correct sequence</li>
                <li className="pl-1"><strong>Mechanical freedom:</strong> Ensure motor and load rotate freely</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Key Parameters to Record</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Motor nominal current:</strong> From nameplate (most critical parameter)</li>
                <li className="pl-1"><strong>Acceleration time:</strong> 5-15s for fans/pumps, longer for high inertia</li>
                <li className="pl-1"><strong>Deceleration time:</strong> 10-60s depending on inertia and regen capability</li>
                <li className="pl-1"><strong>Minimum frequency:</strong> 20-30Hz for centrifugal pumps</li>
                <li className="pl-1"><strong>Maximum frequency:</strong> 50Hz unless extended speed required</li>
                <li className="pl-1"><strong>Control mode:</strong> V/f for most HVAC, vector for dynamic loads</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-red-400/80 mb-2">Common Installation Mistakes</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Pigtail screen termination:</strong> Creates antenna, use 360-degree glands</li>
                <li className="pl-1"><strong>Screen earthed one end only:</strong> Must be earthed at both ends</li>
                <li className="pl-1"><strong>Motor cables with signal cables:</strong> Maintain 300mm separation</li>
                <li className="pl-1"><strong>EMC filter remote from drive:</strong> Must be within 300mm of drive</li>
                <li className="pl-1"><strong>Incorrect motor parameters:</strong> Verify against nameplate, not assumptions</li>
                <li className="pl-1"><strong>Missing output protection:</strong> Long cables need dV/dt filters</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Fault Diagnosis Quick Guide</h3>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Immediate OC on start:</strong> Check motor parameters, look for short/earth fault</li>
                <li className="pl-1"><strong>OC during acceleration:</strong> Increase accel time, check for mechanical binding</li>
                <li className="pl-1"><strong>OV during deceleration:</strong> Increase decel time, add braking resistor</li>
                <li className="pl-1"><strong>Earth fault:</strong> Test motor and cable IR separately</li>
                <li className="pl-1"><strong>Intermittent trips:</strong> Check connections, look for thermal or EMC issues</li>
                <li className="pl-1"><strong>Motor overheating:</strong> Check load, verify cooling, check minimum speed</li>
              </ul>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <h3 className="text-sm font-medium text-white mb-1">{faq.question}</h3>
                <p className="text-sm text-white/90 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Quick Reference */}
        <section className="mb-10">
          <div className="p-5 rounded-lg bg-transparent">
            <h3 className="text-sm font-medium text-white mb-4">Quick Reference</h3>
            <div className="grid sm:grid-cols-2 gap-4 text-xs text-white">
              <div>
                <p className="font-medium text-white mb-1">Cable Requirements</p>
                <ul className="space-y-0.5">
                  <li>Screened cable: VSD, SY, CY types</li>
                  <li>360-degree screen earthing both ends</li>
                  <li>&lt;25m: Screened cable sufficient</li>
                  <li>25-100m: Add output reactor</li>
                  <li>&gt;100m: dV/dt or sine-wave filter</li>
                </ul>
              </div>
              <div>
                <p className="font-medium text-white mb-1">Typical Parameters</p>
                <ul className="space-y-0.5">
                  <li>Accel/decel: 5-15s fans, 10-30s pumps</li>
                  <li>Min frequency: 20-30Hz pumps</li>
                  <li>Motor In: From nameplate exactly</li>
                  <li>Control: V/f for most HVAC</li>
                  <li>Switching freq: 4-8kHz typical</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Quiz */}
        <section className="mb-10">
          <Quiz
            title="Test Your Knowledge"
            questions={quizQuestions}
          />
        </section>

        {/* Navigation */}
        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section4-5">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Previous: Energy Efficiency
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../h-n-c-module8-section5">
              Next: Section 5
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>

      </article>
    </div>
  );
};

export default HNCModule8Section4_6;
