import { ArrowLeft, ArrowRight, HardHat, Target, CheckCircle, AlertTriangle, ClipboardList, Wrench, Shield, Users, Book } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Link } from "react-router-dom";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import useSEO from "@/hooks/useSEO";

const TITLE = "PPE for Cutting, Bending, and Fixing Work - Module 4.7.3 | Level 2 Electrical Course";
const DESCRIPTION = "Learn proper PPE selection and use for electrical installation tasks. Master legal requirements, hazard protection, and maintenance of personal protective equipment.";

// Inline check questions
const quickCheckQuestions = [
  {
    id: 1,
    question: "Which regulation requires employers to provide PPE?",
    options: ["PPE at Work Regulations 1992", "Health and Safety at Work Act", "COSHH", "Manual Handling Operations Regulations"],
    correctIndex: 0,
    explanation: "The PPE at Work Regulations 1992 specifically require employers to provide suitable PPE free of charge to their employees."
  },
  {
    id: 2,
    question: "Name two types of PPE essential when using a grinder.",
    options: ["Safety glasses and hearing protection", "Gloves and boots", "Hi-vis vest and hard hat", "Dust mask and knee pads"],
    correctIndex: 0,
    explanation: "Safety glasses protect eyes from sparks and debris, while hearing protection prevents damage from the high noise levels generated by grinders."
  },
  {
    id: 3,
    question: "True or False: PPE can replace safe working methods.",
    options: ["False", "True", "Sometimes", "Only for simple tasks"],
    correctIndex: 0,
    explanation: "False - PPE is the last line of defence and complements, not replaces, safe working methods. Proper procedures, guards, and safe techniques must still be used."
  }
];

const Module4Section7_3 = () => {
  useSEO(TITLE, DESCRIPTION);

  const quizQuestions = [
    {
      id: 1,
      question: "Which regulation covers PPE requirements in the workplace?",
      options: [
        "EAWR 1989",
        "PPE at Work Regulations 1992",
        "PUWER 1998",
        "CDM 2015"
      ],
      correctAnswer: 1,
      explanation: "The PPE at Work Regulations 1992 specifically covers the provision, use, and maintenance of personal protective equipment in the workplace."
    },
    {
      id: 2,
      question: "True or False: Employers can charge workers for PPE.",
      options: [
        "True",
        "False",
        "Only for expensive items",
        "Only for personal items"
      ],
      correctAnswer: 1,
      explanation: "False - under the PPE at Work Regulations, employers must provide PPE free of charge to employees who need it for their work."
    },
    {
      id: 3,
      question: "Name two hazards PPE protects against when cutting conduit.",
      options: [
        "Good lighting and clean workspace",
        "Sharp edges and metal fragments",
        "Proper tool maintenance",
        "Adequate supervision"
      ],
      correctAnswer: 1,
      explanation: "Sharp edges from cut conduit and flying metal fragments are major hazards that PPE protects against during cutting operations."
    },
    {
      id: 4,
      question: "What type of gloves should be used when handling sharp-edged conduit?",
      options: [
        "Rubber gloves",
        "Cut-resistant gloves",
        "Cloth gloves",
        "None"
      ],
      correctAnswer: 1,
      explanation: "Cut-resistant gloves (EN388 standard Level 3-5) provide the best protection against sharp edges and reduce the risk of cuts and lacerations."
    },
    {
      id: 5,
      question: "Why should PPE be inspected daily?",
      options: [
        "To keep supervisors happy",
        "To meet legal obligations and prevent failure",
        "To make PPE last longer",
        "To reduce tool wear"
      ],
      correctAnswer: 1,
      explanation: "Daily inspection ensures PPE is fit for purpose and will provide protection when needed. It's also a legal requirement under PPE regulations."
    },
    {
      id: 6,
      question: "Name one PPE item required when working in noisy environments.",
      options: [
        "Safety glasses",
        "Hard hat",
        "Ear defenders or ear plugs",
        "Hi-vis vest"
      ],
      correctAnswer: 2,
      explanation: "Ear defenders or ear plugs protect hearing from damage caused by prolonged exposure to high noise levels from power tools and machinery."
    },
    {
      id: 7,
      question: "What should you do if your PPE is damaged?",
      options: [
        "Continue using it",
        "Repair it yourself",
        "Report and replace it immediately",
        "Lend it to someone else"
      ],
      correctAnswer: 2,
      explanation: "Damaged PPE must be reported and replaced immediately as it may not provide adequate protection when needed."
    },
    {
      id: 8,
      question: "True or False: PPE is a substitute for following safe work practices.",
      options: [
        "True",
        "False",
        "Sometimes",
        "Only for simple tasks"
      ],
      correctAnswer: 1,
      explanation: "False - PPE is the last line of defence and should be used alongside, not instead of, safe working practices and proper procedures."
    },
    {
      id: 9,
      question: "Give two examples of PPE required when using a grinder.",
      options: [
        "Gloves and boots only",
        "Face shield and hearing protection",
        "Hi-vis vest and hard hat",
        "Dust mask and knee pads"
      ],
      correctAnswer: 1,
      explanation: "Face shield (or safety glasses) protects against sparks and debris, while hearing protection prevents damage from the high noise levels of grinding operations."
    },
    {
      id: 10,
      question: "Where should PPE be stored when not in use?",
      options: [
        "In a clean, dry location",
        "In the tool bag",
        "On the floor of the site",
        "Shared with other workers"
      ],
      correctAnswer: 0,
      explanation: "PPE should be stored in clean, dry conditions to maintain its effectiveness and prevent contamination or damage."
    }
  ];

  const faqs = [
    {
      question: "Who is responsible for providing PPE?",
      answer: "The employer must provide PPE free of charge. This includes initial provision, replacement when worn or damaged, and ensuring it meets appropriate safety standards for the specific tasks being performed."
    },
    {
      question: "Can I use my own PPE instead of company-issued equipment?",
      answer: "Yes, but only if it meets the correct safety standards and is approved by your employer. Your PPE must comply with relevant CE marking and British/European standards for the specific hazards you face."
    },
    {
      question: "How often should PPE be replaced?",
      answer: "PPE should be replaced as soon as it becomes damaged, worn, or fails inspection. Some items have specific replacement schedules (e.g., filters in respirators), while others depend on usage and condition."
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Top header bar */}
      <div className="border-b border-border/20 bg-card sticky top-0 z-10 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 sm:py-4">
          <Button variant="ghost" className="text-muted-foreground hover:text-foreground active:text-foreground p-0 -ml-1" asChild>
            <Link to="..">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Section 7
            </Link>
          </Button>
        </div>
      </div>

      {/* Main */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Header */}
        <header className="mb-6 sm:mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 rounded-lg bg-card">
              <HardHat className="w-6 h-6 text-foreground" />
            </div>
            <Badge variant="outline" className="border-emerald-500/30 text-emerald-400">
              Section 4.7.3
            </Badge>
          </div>
          <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground mb-2">
            PPE for Cutting, Bending, and Fixing Work
          </h1>
          <p className="text-muted-foreground">
            Master proper PPE selection, use, and maintenance to protect against workplace hazards in electrical installation.
          </p>
        </header>

        {/* Introduction */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4">Introduction</h2>
          <div className="grid md:grid-cols-2 gap-4 sm:gap-6 text-base text-foreground">
            <div className="rounded-lg p-3 sm:p-4 bg-emerald-500/10 border-l-4 border-l-emerald-500 border border-emerald-500/30">
              <p className="font-semibold text-emerald-400 mb-2">In 30 Seconds</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>PPE is the last line of defence against workplace hazards during cutting, bending, and fixing operations.</li>
                <li>Legal requirements under PPE at Work Regulations 1992 mandate free provision and proper use of protective equipment.</li>
                <li>Correct PPE selection, daily inspection, and proper maintenance are essential for effective protection.</li>
              </ul>
            </div>
            <div className="rounded-lg p-3 sm:p-4 bg-emerald-500/10 border-l-4 border-l-emerald-500 border border-emerald-500/30">
              <p className="font-semibold text-emerald-400 mb-2">Spot it / Use it</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Spot:</strong> Missing eye protection, damaged gloves, no hearing protection with power tools, worn-out safety boots.</li>
                <li><strong>Use:</strong> Safety glasses, cut-resistant gloves, ear defenders, steel-toe boots, dust masks when needed.</li>
                <li><strong>Check:</strong> PPE condition before use, proper fit, appropriate standard for the hazard.</li>
              </ul>
            </div>
          </div>
        </Card>

        {/* Learning outcomes */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4">Learning outcomes</h2>
          <ul className="list-disc pl-6 space-y-2 text-base text-foreground">
            <li>Identify the correct PPE for different installation tasks.</li>
            <li>Understand how PPE reduces risk during cutting, bending, and fixing.</li>
            <li>Apply safe working practices alongside PPE use.</li>
            <li>Inspect, maintain, and correctly store PPE.</li>
            <li>Recognise your legal responsibilities under PPE regulations.</li>
          </ul>
        </Card>

        {/* Content */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4">Content</h2>

          {/* Legal Requirements */}
          <section className="mb-6">
            <h3 className="font-medium text-foreground mb-4">1. Legal Requirements</h3>
            <p className="text-base text-foreground mb-4">
              PPE regulations establish clear legal obligations for both employers and employees to ensure adequate protection against workplace hazards:
            </p>
            
            <div className="space-y-4">
              <div className="rounded-lg p-5 border-l-4 border-l-emerald-500 bg-card">
                <div className="flex items-start gap-3 mb-2">
                  <span className="flex-shrink-0 w-8 h-8 bg-emerald-500 text-white rounded-full flex items-center justify-center text-sm font-bold">1</span>
                  <div className="flex-1">
                    <p className="font-semibold text-emerald-400 dark:text-emerald-400 mb-1">PPE at Work Regulations 1992</p>
                    <ul className="text-xs sm:text-sm text-foreground ml-4 mb-2 list-disc space-y-1">
                      <li><strong>Employer obligations</strong> - provide PPE free of charge when risks cannot be controlled by other means</li>
                      <li><strong>Suitability requirements</strong> - PPE must be appropriate for the risks and fit properly</li>
                      <li><strong>Maintenance duties</strong> - ensure PPE is maintained in good working order and hygienically clean</li>
                      <li><strong>Information and training</strong> - provide adequate instruction on proper use and care</li>
                      <li><strong>Employee responsibilities</strong> - use PPE correctly, report defects, and take reasonable care</li>
                      <li><strong>Compatibility</strong> - ensure different items of PPE work together without reducing protection</li>
                    </ul>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>CE marking requirements:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        All PPE must carry CE marking and comply with relevant European standards (EN standards). This ensures the equipment has been tested and meets minimum safety requirements for protection against specific hazards.
                      </p>
                    </div>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Risk assessment integration:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        PPE selection must be based on proper risk assessment. The hierarchy of control means PPE is used when risks cannot be eliminated, reduced, or controlled by other means such as engineering controls or safe systems of work.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-1"
            question={quickCheckQuestions[0].question}
            options={quickCheckQuestions[0].options}
            correctIndex={quickCheckQuestions[0].correctIndex}
            explanation={quickCheckQuestions[0].explanation}
          />
          <Separator className="my-6" />

          {/* Typical PPE for Cutting and Bending Work */}
          <section className="mb-6">
            <h3 className="font-medium text-foreground mb-4">2. Typical PPE for Cutting and Bending Work</h3>
            <p className="text-base text-foreground mb-4">
              Different installation tasks require specific PPE combinations to protect against the unique hazards of each operation:
            </p>
            
            <div className="space-y-4">
              <div className="rounded-lg p-5 border-l-4 border-l-green-500 bg-card">
                <div className="flex items-start gap-3 mb-2">
                  <span className="flex-shrink-0 w-8 h-8 bg-green-500 text-white rounded-full flex items-center justify-center text-sm font-bold">2</span>
                  <div className="flex-1">
                    <p className="font-semibold text-green-600 dark:text-green-400 mb-1">Essential PPE for Installation Tasks</p>
                    <ul className="text-xs sm:text-sm text-foreground ml-4 mb-2 list-disc space-y-1">
                      <li><strong>Safety glasses/goggles</strong> - protect eyes from sparks, dust, and flying fragments (EN 166 standard)</li>
                      <li><strong>Cut-resistant gloves</strong> - protect against sharp edges, hot surfaces, and handling hazards (EN 388 Level 3-5)</li>
                      <li><strong>Hearing protection</strong> - ear defenders or plugs when using noisy cutting tools (EN 352 standard)</li>
                      <li><strong>Respiratory protection</strong> - dust masks or respirators for cutting materials that generate particles</li>
                      <li><strong>Safety footwear</strong> - steel toe-cap boots for protection from dropped tools and materials (EN ISO 20345)</li>
                      <li><strong>High-visibility clothing</strong> - essential when working in shared construction areas or near traffic</li>
                    </ul>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Task-specific PPE combinations:</strong></p>
                      <ul className="text-xs text-muted-foreground list-disc ml-4 space-y-1">
                        <li><strong>Cutting conduit/trunking:</strong> Safety glasses, cut-resistant gloves, hearing protection</li>
                        <li><strong>Bending cable tray:</strong> Cut-resistant gloves, safety footwear, back support if heavy</li>
                        <li><strong>Drilling fixings:</strong> Safety glasses, dust mask, hearing protection, steel-toe boots</li>
                        <li><strong>Grinding/deburring:</strong> Face shield, hearing protection, respiratory protection, spark-resistant clothing</li>
                        <li><strong>Cable pulling:</strong> Cut-resistant gloves, safety footwear, knee protection if required</li>
                      </ul>
                    </div>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>PPE standards and ratings:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        Understanding PPE ratings helps select appropriate protection. EN 388 mechanical hazards (cut, puncture, tear, abrasion), EN 166 eye protection (impact, chemical, optical), EN 352 hearing protection (noise reduction ratings). Always match PPE rating to hazard severity.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-2"
            question={quickCheckQuestions[1].question}
            options={quickCheckQuestions[1].options}
            correctIndex={quickCheckQuestions[1].correctIndex}
            explanation={quickCheckQuestions[1].explanation}
          />
          <Separator className="my-6" />

          {/* Hazards Without PPE */}
          <section className="mb-6">
            <h3 className="font-medium text-foreground mb-4">3. Hazards Without PPE</h3>
            <p className="text-base text-foreground mb-4">
              Understanding the serious consequences of inadequate PPE helps emphasise the importance of proper protection in electrical installation work:
            </p>
            
            <div className="space-y-4">
              <div className="rounded-lg p-5 border-l-4 border-l-red-500 bg-card">
                <div className="flex items-start gap-3 mb-2">
                  <span className="flex-shrink-0 w-8 h-8 bg-red-500 text-white rounded-full flex items-center justify-center text-sm font-bold">3</span>
                  <div className="flex-1">
                    <p className="font-semibold text-red-600 dark:text-emerald-400 mb-1">Serious Injury Risks Without Proper PPE</p>
                    <ul className="text-xs sm:text-sm text-foreground ml-4 mb-2 list-disc space-y-1">
                      <li><strong>Eye injuries from metal swarf</strong> - permanent vision damage or blindness from cutting and grinding operations</li>
                      <li><strong>Severe cuts and lacerations</strong> - from sharp conduit edges, cable tray, and cutting tools</li>
                      <li><strong>Noise-induced hearing loss</strong> - irreversible damage from repeated exposure to power tools without protection</li>
                      <li><strong>Respiratory problems</strong> - from inhaling harmful dusts, particularly from cutting treated materials</li>
                      <li><strong>Foot and toe injuries</strong> - crushing and puncture wounds from dropped tools and materials</li>
                      <li><strong>Hand and finger injuries</strong> - burns from hot surfaces, cuts from sharp edges, impact injuries</li>
                    </ul>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Long-term health consequences:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        Many PPE-preventable injuries have long-term implications. Eye injuries can affect career prospects and quality of life. Hearing loss is progressive and irreversible. Respiratory conditions from dust exposure can develop years after initial exposure, emphasising the importance of consistent PPE use.
                      </p>
                    </div>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Project and business impact:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        Injuries affect not just the individual but the entire project. Lost time incidents, HSE investigations, insurance claims, and potential prosecution create significant costs. Good PPE practice protects both personnel and business interests.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-3"
            question={quickCheckQuestions[2].question}
            options={quickCheckQuestions[2].options}
            correctIndex={quickCheckQuestions[2].correctIndex}
            explanation={quickCheckQuestions[2].explanation}
          />
          <Separator className="my-6" />

          {/* Maintenance of PPE */}
          <section className="mb-6">
            <h3 className="font-medium text-foreground mb-4">4. Maintenance of PPE</h3>
            <p className="text-base text-foreground mb-4">
              Proper maintenance ensures PPE remains effective throughout its service life and provides reliable protection when needed:
            </p>
            
            <div className="space-y-4">
              <div className="rounded-lg p-5 border-l-4 border-l-amber-500 bg-card">
                <div className="flex items-start gap-3 mb-2">
                  <span className="flex-shrink-0 w-8 h-8 bg-amber-500 text-white rounded-full flex items-center justify-center text-sm font-bold">4</span>
                  <div className="flex-1">
                    <p className="font-semibold text-amber-600 dark:text-amber-400 mb-1">PPE Maintenance and Care Systems</p>
                    <ul className="text-xs sm:text-sm text-foreground ml-4 mb-2 list-disc space-y-1">
                      <li><strong>Daily pre-use inspection</strong> - check PPE condition before each use for damage or wear</li>
                      <li><strong>Immediate replacement</strong> - remove and replace worn or damaged items without delay</li>
                      <li><strong>Proper cleaning procedures</strong> - follow manufacturer instructions for cleaning and disinfection</li>
                      <li><strong>Appropriate storage conditions</strong> - clean, dry locations away from direct sunlight and chemicals</li>
                      <li><strong>Personal assignment</strong> - avoid sharing PPE where hygiene or fit is critical</li>
                      <li><strong>Regular replacement schedules</strong> - replace items according to manufacturer or company schedules</li>
                    </ul>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Inspection checklist for common PPE:</strong></p>
                      <ul className="text-xs text-muted-foreground list-disc ml-4 space-y-1">
                        <li><strong>Safety glasses:</strong> Scratches, cracks, loose components, clean lenses</li>
                        <li><strong>Gloves:</strong> Holes, tears, contamination, proper grip, sizing still correct</li>
                        <li><strong>Hearing protection:</strong> Foam condition, headband tension, seal integrity</li>
                        <li><strong>Safety boots:</strong> Sole wear, upper damage, lace condition, internal support</li>
                        <li><strong>Hard hats:</strong> Shell cracks, suspension system, expiry date, impact damage</li>
                      </ul>
                    </div>
                    
                    <div className="mt-3 p-3 bg-amber-50/50 dark:bg-amber-900/10 rounded border border-amber-200/30">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Storage best practices:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        Store PPE in dedicated clean areas, not in tool bags where contamination and damage can occur. Use protective cases for safety glasses, keep gloves in clean containers, and ensure hearing protection is stored away from sharp objects. Label storage areas clearly and maintain inventory of spare items.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Integrating PPE with Safe Practice */}
          <section className="mb-6">
            <h3 className="font-medium text-foreground mb-4">5. Integrating PPE with Safe Practice</h3>
            <p className="text-base text-foreground mb-4">
              PPE works most effectively when integrated with comprehensive safe working practices and proper risk management:
            </p>
            
            <div className="space-y-4">
              <div className="rounded-lg p-5 border-l-4 border-l-purple-500 bg-card">
                <div className="flex items-start gap-3 mb-2">
                  <span className="flex-shrink-0 w-8 h-8 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold">5</span>
                  <div className="flex-1">
                    <p className="font-semibold text-purple-600 dark:text-emerald-400 mb-1">Comprehensive Safety Integration</p>
                    <ul className="text-xs sm:text-sm text-foreground ml-4 mb-2 list-disc space-y-1">
                      <li><strong>Hierarchy of control</strong> - PPE is the last line of defence, not a substitute for safe methods</li>
                      <li><strong>Job planning</strong> - always plan the task first, then select appropriate PPE for identified hazards</li>
                      <li><strong>Engineering controls</strong> - use guards, clamps, and correct tools alongside PPE for maximum protection</li>
                      <li><strong>Training integration</strong> - teach apprentices to recognise task-specific PPE requirements</li>
                      <li><strong>Environmental assessment</strong> - consider workplace conditions when selecting PPE combinations</li>
                      <li><strong>Team coordination</strong> - ensure all team members understand PPE requirements for shared tasks</li>
                    </ul>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>PPE selection process:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        Effective PPE selection follows a systematic approach: identify hazards through risk assessment, determine required protection levels, select appropriate standards and ratings, ensure proper fit and compatibility, provide adequate training, and establish maintenance procedures.
                      </p>
                    </div>
                    
                    <div className="mt-3 p-3 bg-background/50 rounded border">
                      <p className="text-xs sm:text-sm text-foreground mb-2"><strong>Behavioural factors:</strong></p>
                      <p className="text-xs text-muted-foreground">
                        PPE effectiveness depends on consistent use. Address comfort issues through proper fitting, involve users in selection where possible, provide adequate training on benefits, and create a positive safety culture where PPE use is normal and expected behaviour.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </Card>

        {/* Practical Guidance */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <Wrench className="w-5 h-5" />
            Practical Guidance (On-Site Tips)
          </h2>
          <div className="grid gap-4">
            <div className="p-4 bg-card rounded-lg border border-border/10">
              <h3 className="font-medium text-foreground mb-2">Pre-Task PPE Preparation</h3>
              <ul className="text-xs sm:text-sm text-foreground space-y-1 list-disc ml-5">
                <li>Always de-burr conduit ends before handling to reduce cut risk even with gloves</li>
                <li>Keep a spare pair of safety glasses in your kit for when one gets damaged</li>
                <li>Check PPE fit and condition at the start of each day, not just before first use</li>
                <li>Ensure adequate lighting to properly inspect PPE condition</li>
              </ul>
            </div>
            
            <div className="p-4 bg-card rounded-lg border border-border/10">
              <h3 className="font-medium text-foreground mb-2">Task-Specific PPE Selection</h3>
              <ul className="text-xs sm:text-sm text-foreground space-y-1 list-disc ml-5">
                <li>Wear ear protection when drilling into blockwork or using angle grinders</li>
                <li>Use cut-resistant gloves (Level 3–5 EN388 standard) when cutting cable tray</li>
                <li>Consider respiratory protection when cutting galvanised or treated materials</li>
                <li>Wear steel toe-cap boots in all areas where tools and materials are being moved</li>
              </ul>
            </div>
            
            <div className="p-4 bg-card rounded-lg border border-border/10">
              <h3 className="font-medium text-foreground mb-2">PPE Management Best Practices</h3>
              <ul className="text-xs sm:text-sm text-foreground space-y-1 list-disc ml-5">
                <li>Label and keep PPE personal — never swap gloves or ear protection with others</li>
                <li>Report defective PPE immediately and remove from circulation</li>
                <li>Clean PPE according to manufacturer instructions to maintain effectiveness</li>
                <li>Store PPE in designated clean areas, away from tools and materials</li>
              </ul>
            </div>
          </div>
        </Card>

        {/* Real-World Examples */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <Users className="w-5 h-5" />
            Real-World Examples
          </h2>
          
          <div className="space-y-6">
            <div className="p-5 border border-red-200/50 bg-red-50/50 dark:bg-red-900/10 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600 mt-1" />
                <div>
                  <h3 className="font-medium text-red-800 dark:text-emerald-400 mb-2">Case Study 1: Eye Injury from Metal Fragment</h3>
                  <p className="text-xs sm:text-sm text-foreground mb-2">
                    On a commercial site, an electrician was cutting trunking with a hacksaw without safety glasses. A small metal fragment flew into his eye, requiring hospital treatment and three days off work.
                  </p>
                  <p className="text-xs text-muted-foreground bg-background/50 p-2 rounded">
                    <strong>Prevention:</strong> Safety glasses costing less than £5 would have prevented this injury entirely. The incident resulted in project delays, HSE reporting, and potential permanent vision damage.
                  </p>
                </div>
              </div>
            </div>
            
            <div className="p-5 border border-red-200/50 bg-red-50/50 dark:bg-red-900/10 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600 mt-1" />
                <div>
                  <h3 className="font-medium text-red-800 dark:text-emerald-400 mb-2">Case Study 2: Hearing Damage from Prolonged Tool Use</h3>
                  <p className="text-xs sm:text-sm text-foreground mb-2">
                    An experienced electrician developed significant hearing loss after years of using power tools without hearing protection. The condition was identified during a routine health check but the damage was irreversible.
                  </p>
                  <p className="text-xs text-muted-foreground bg-background/50 p-2 rounded">
                    <strong>Prevention:</strong> Consistent use of hearing protection throughout his career would have prevented this occupational disease. Early intervention and regular health surveillance are crucial for long-term hearing protection.
                  </p>
                </div>
              </div>
            </div>
            
            <div className="p-5 border border-green-200/50 bg-green-50/50 dark:bg-green-900/10 rounded-lg">
              <div className="flex items-start gap-3">
                <CheckCircle className="w-5 h-5 text-green-600 mt-1" />
                <div>
                  <h3 className="font-medium text-green-800 dark:text-green-300 mb-2">Case Study 3: Good PPE Practice Prevents Serious Injury</h3>
                  <p className="text-xs sm:text-sm text-foreground mb-2">
                    During cable tray installation, a worker's cut-resistant gloves prevented serious injury when a sharp edge sliced through the outer layer. The gloves were immediately replaced, and the incident was reported as a near-miss.
                  </p>
                  <p className="text-xs text-muted-foreground bg-background/50 p-2 rounded">
                    <strong>Good Practice:</strong> Proper PPE selection, immediate replacement when damaged, and treating near-misses as learning opportunities. The incident led to improved edge finishing procedures for the entire team.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Card>

        {/* FAQ */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5" />
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="border-b border-border/20 pb-4 last:border-b-0">
                <h3 className="font-medium text-foreground mb-2">{faq.question}</h3>
                <p className="text-sm text-muted-foreground">{faq.answer}</p>
              </div>
            ))}
          </div>
        </Card>

        {/* Pocket Guide */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <ClipboardList className="w-5 h-5" />
            Pocket Guide (Key Takeaways)
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">PPE is legally required under PPE at Work Regulations</span>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">Safety glasses, gloves, boots, and hearing protection are essential</span>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">Always inspect and replace PPE as needed</span>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">PPE complements, not replaces, safe working methods</span>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">Never start cutting, bending, or fixing work without full PPE</span>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                <span className="font-medium text-foreground">Store PPE in clean, dry conditions when not in use</span>
              </div>
            </div>
          </div>
        </Card>

        {/* Recap */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <Book className="w-5 h-5" />
            Recap
          </h2>
          <p className="text-base text-foreground mb-4">In this subsection, you learned:</p>
          <ul className="list-disc pl-6 space-y-2 text-base text-foreground">
            <li>The legal requirements for PPE in electrical installation.</li>
            <li>Typical PPE used in cutting, bending, and fixing tasks.</li>
            <li>Common hazards that PPE helps prevent.</li>
            <li>How to maintain and store PPE effectively.</li>
            <li>Practical habits for keeping yourself and others safe on site.</li>
          </ul>
        </Card>

        {/* Quiz */}
        <Card className="mb-6 sm:mb-8 p-4 sm:p-6 bg-card border-border/20">
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
            <Target className="w-5 h-5" />
            Knowledge Check Quiz
          </h2>
          <Quiz questions={quizQuestions} />
        </Card>

        {/* Navigation */}
        <div className="flex justify-between items-center pt-6 border-t border-border/20">
          <Button variant="outline" asChild>
            <Link to="module4-section7/subsection2" className="flex items-center gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back: Hand and Power Tools
            </Link>
          </Button>
          
          <Button asChild>
            <Link to="module4-section7/subsection4" className="flex items-center gap-2">
              Next: Working at Height
              <ArrowRight className="w-4 h-4" />
            </Link>
          </Button>
        </div>
      </main>
    </div>
  );
};

export default Module4Section7_3;