import { ArrowLeft, ArrowRight, HardHat, Target, CheckCircle, AlertTriangle, Wrench, Shield, Users, Book } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import useSEO from "@/hooks/useSEO";

const TITLE = "PPE for Cutting, Bending, and Fixing Work - Module 4.7.3 | Level 2 Electrical Course";
const DESCRIPTION = "Learn proper PPE selection and use for electrical installation tasks. Master legal requirements, hazard protection, and maintenance of personal protective equipment.";

// Inline check questions
const quickCheckQuestions = [
  {
    id: 1,
    question: "Which regulation requires employers to provide PPE?",
    options: ["PPE at Work Regulations 1992", "Health and Safety at Work Act", "COSHH", "Manual Handling Operations Regulations"],
    correctIndex: 0,
    explanation: "The PPE at Work Regulations 1992 specifically require employers to provide suitable PPE free of charge to their employees."
  },
  {
    id: 2,
    question: "Name two types of PPE essential when using a grinder.",
    options: ["Safety glasses and hearing protection", "Gloves and boots", "Hi-vis vest and hard hat", "Dust mask and knee pads"],
    correctIndex: 0,
    explanation: "Safety glasses protect eyes from sparks and debris, while hearing protection prevents damage from the high noise levels generated by grinders."
  },
  {
    id: 3,
    question: "True or False: PPE can replace safe working methods.",
    options: ["False", "True", "Sometimes", "Only for simple tasks"],
    correctIndex: 0,
    explanation: "False - PPE is the last line of defence and complements, not replaces, safe working methods. Proper procedures, guards, and safe techniques must still be used."
  }
];

const Module4Section7_3 = () => {
  useSEO(TITLE, DESCRIPTION);

  const quizQuestions = [
    {
      id: 1,
      question: "Which regulation covers PPE requirements in the workplace?",
      options: [
        "EAWR 1989",
        "PPE at Work Regulations 1992",
        "PUWER 1998",
        "CDM 2015"
      ],
      correctAnswer: 1,
      explanation: "The PPE at Work Regulations 1992 specifically covers the provision, use, and maintenance of personal protective equipment in the workplace."
    },
    {
      id: 2,
      question: "True or False: Employers can charge workers for PPE.",
      options: [
        "True",
        "False",
        "Only for expensive items",
        "Only for personal items"
      ],
      correctAnswer: 1,
      explanation: "False - under the PPE at Work Regulations, employers must provide PPE free of charge to employees who need it for their work."
    },
    {
      id: 3,
      question: "Name two hazards PPE protects against when cutting conduit.",
      options: [
        "Good lighting and clean workspace",
        "Sharp edges and metal fragments",
        "Proper tool maintenance",
        "Adequate supervision"
      ],
      correctAnswer: 1,
      explanation: "Sharp edges from cut conduit and flying metal fragments are major hazards that PPE protects against during cutting operations."
    },
    {
      id: 4,
      question: "What type of gloves should be used when handling sharp-edged conduit?",
      options: [
        "Rubber gloves",
        "Cut-resistant gloves",
        "Cloth gloves",
        "None"
      ],
      correctAnswer: 1,
      explanation: "Cut-resistant gloves (EN388 standard Level 3-5) provide the best protection against sharp edges and reduce the risk of cuts and lacerations."
    },
    {
      id: 5,
      question: "Why should PPE be inspected daily?",
      options: [
        "To keep supervisors happy",
        "To meet legal obligations and prevent failure",
        "To make PPE last longer",
        "To reduce tool wear"
      ],
      correctAnswer: 1,
      explanation: "Daily inspection ensures PPE is fit for purpose and will provide protection when needed. It's also a legal requirement under PPE regulations."
    },
    {
      id: 6,
      question: "Name one PPE item required when working in noisy environments.",
      options: [
        "Safety glasses",
        "Hard hat",
        "Ear defenders or ear plugs",
        "Hi-vis vest"
      ],
      correctAnswer: 2,
      explanation: "Ear defenders or ear plugs protect hearing from damage caused by prolonged exposure to high noise levels from power tools and machinery."
    },
    {
      id: 7,
      question: "What should you do if your PPE is damaged?",
      options: [
        "Continue using it",
        "Repair it yourself",
        "Report and replace it immediately",
        "Lend it to someone else"
      ],
      correctAnswer: 2,
      explanation: "Damaged PPE must be reported and replaced immediately as it may not provide adequate protection when needed."
    },
    {
      id: 8,
      question: "True or False: PPE is a substitute for following safe work practices.",
      options: [
        "True",
        "False",
        "Sometimes",
        "Only for simple tasks"
      ],
      correctAnswer: 1,
      explanation: "False - PPE is the last line of defence and should be used alongside, not instead of, safe working practices and proper procedures."
    },
    {
      id: 9,
      question: "Give two examples of PPE required when using a grinder.",
      options: [
        "Gloves and boots only",
        "Face shield and hearing protection",
        "Hi-vis vest and hard hat",
        "Dust mask and knee pads"
      ],
      correctAnswer: 1,
      explanation: "Face shield (or safety glasses) protects against sparks and debris, while hearing protection prevents damage from the high noise levels of grinding operations."
    },
    {
      id: 10,
      question: "Where should PPE be stored when not in use?",
      options: [
        "In a clean, dry location",
        "In the tool bag",
        "On the floor of the site",
        "Shared with other workers"
      ],
      correctAnswer: 0,
      explanation: "PPE should be stored in clean, dry conditions to maintain its effectiveness and prevent contamination or damage."
    }
  ];

  const faqs = [
    {
      question: "Who is responsible for providing PPE?",
      answer: "The employer must provide PPE free of charge. This includes initial provision, replacement when worn or damaged, and ensuring it meets appropriate safety standards for the specific tasks being performed."
    },
    {
      question: "Can I use my own PPE instead of company-issued equipment?",
      answer: "Yes, but only if it meets the correct safety standards and is approved by your employer. Your PPE must comply with relevant CE marking and British/European standards for the specific hazards you face."
    },
    {
      question: "How often should PPE be replaced?",
      answer: "PPE should be replaced as soon as it becomes damaged, worn, or fails inspection. Some items have specific replacement schedules (e.g., filters in respirators), while others depend on usage and condition."
    }
  ];

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#1a1a1a]">
      {/* Sticky Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-3">
          <Button
            variant="ghost"
            className="text-white/70 hover:text-white hover:bg-white/5 -ml-2 min-h-[44px] touch-manipulation active:scale-[0.98]"
            asChild
          >
            <Link to="..">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Section 7
            </Link>
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <article className="px-4 sm:px-6 py-8 sm:py-12">
        <div className="max-w-3xl mx-auto">
          {/* Centered Header */}
          <header className="text-center mb-12">
            <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
              <span className="px-2 py-0.5 bg-elec-yellow/10 rounded">Module 4</span>
              <span className="text-white/40">•</span>
              <span className="text-white/60">Section 7.3</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white mb-3 leading-tight">
              PPE for Cutting, Bending, and Fixing Work
            </h1>
            <p className="text-white/70 text-base sm:text-lg leading-relaxed max-w-2xl mx-auto">
              Master proper PPE selection, use, and maintenance to protect against workplace hazards in electrical installation.
            </p>
          </header>

          {/* Introduction */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">01</span>
              Introduction
            </h2>
            <div className="grid md:grid-cols-2 gap-4 text-white/80">
              <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
                <p className="font-semibold text-elec-yellow mb-2">In 30 Seconds</p>
                <ul className="list-disc pl-6 space-y-1 text-sm">
                  <li>PPE is the last line of defence against workplace hazards during cutting, bending, and fixing operations.</li>
                  <li>Legal requirements under PPE at Work Regulations 1992 mandate free provision and proper use of protective equipment.</li>
                  <li>Correct PPE selection, daily inspection, and proper maintenance are essential for effective protection.</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
                <p className="font-semibold text-elec-yellow mb-2">Spot it / Use it</p>
                <ul className="list-disc pl-6 space-y-1 text-sm">
                  <li><strong>Spot:</strong> Missing eye protection, damaged gloves, no hearing protection with power tools, worn-out safety boots.</li>
                  <li><strong>Use:</strong> Safety glasses, cut-resistant gloves, ear defenders, steel-toe boots, dust masks when needed.</li>
                  <li><strong>Check:</strong> PPE condition before use, proper fit, appropriate standard for the hazard.</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Learning Outcomes */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">02</span>
              Learning Outcomes
            </h2>
            <div className="p-4 rounded-lg bg-white/5 border border-white/10">
              <ul className="list-disc pl-6 space-y-2 text-white/80">
                <li>Identify the correct PPE for different installation tasks.</li>
                <li>Understand how PPE reduces risk during cutting, bending, and fixing.</li>
                <li>Apply safe working practices alongside PPE use.</li>
                <li>Inspect, maintain, and correctly store PPE.</li>
                <li>Recognise your legal responsibilities under PPE regulations.</li>
              </ul>
            </div>
          </section>

          {/* Legal Requirements */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">03</span>
              Legal Requirements
            </h2>
            <div className="text-white/80 space-y-4 leading-relaxed">
              <p>
                PPE regulations establish clear legal obligations for both employers and employees to ensure adequate protection against workplace hazards:
              </p>

              <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
                <p className="font-semibold text-elec-yellow mb-2">PPE at Work Regulations 1992</p>
                <ul className="text-sm list-disc pl-6 space-y-1">
                  <li><strong>Employer obligations</strong> - provide PPE free of charge when risks cannot be controlled by other means</li>
                  <li><strong>Suitability requirements</strong> - PPE must be appropriate for the risks and fit properly</li>
                  <li><strong>Maintenance duties</strong> - ensure PPE is maintained in good working order and hygienically clean</li>
                  <li><strong>Information and training</strong> - provide adequate instruction on proper use and care</li>
                  <li><strong>Employee responsibilities</strong> - use PPE correctly, report defects, and take reasonable care</li>
                  <li><strong>Compatibility</strong> - ensure different items of PPE work together without reducing protection</li>
                </ul>

                <div className="mt-3 p-3 bg-black/20 rounded text-sm">
                  <p className="mb-2"><strong>CE marking requirements:</strong></p>
                  <p className="text-white/70">
                    All PPE must carry CE marking and comply with relevant European standards (EN standards). This ensures the equipment has been tested and meets minimum safety requirements for protection against specific hazards.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-1"
            question={quickCheckQuestions[0].question}
            options={quickCheckQuestions[0].options}
            correctIndex={quickCheckQuestions[0].correctIndex}
            explanation={quickCheckQuestions[0].explanation}
          />

          {/* Typical PPE for Cutting and Bending Work */}
          <section className="mb-10 mt-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">04</span>
              Typical PPE for Cutting and Bending Work
            </h2>
            <div className="text-white/80 space-y-4 leading-relaxed">
              <p>
                Different installation tasks require specific PPE combinations to protect against the unique hazards of each operation:
              </p>

              <div className="p-4 rounded-lg bg-green-500/10 border-l-2 border-green-500/50">
                <p className="font-semibold text-green-400 mb-2">Essential PPE for Installation Tasks</p>
                <ul className="text-sm list-disc pl-6 space-y-1">
                  <li><strong>Safety glasses/goggles</strong> - protect eyes from sparks, dust, and flying fragments (EN 166 standard)</li>
                  <li><strong>Cut-resistant gloves</strong> - protect against sharp edges, hot surfaces, and handling hazards (EN 388 Level 3-5)</li>
                  <li><strong>Hearing protection</strong> - ear defenders or plugs when using noisy cutting tools (EN 352 standard)</li>
                  <li><strong>Respiratory protection</strong> - dust masks or respirators for cutting materials that generate particles</li>
                  <li><strong>Safety footwear</strong> - steel toe-cap boots for protection from dropped tools and materials (EN ISO 20345)</li>
                  <li><strong>High-visibility clothing</strong> - essential when working in shared construction areas or near traffic</li>
                </ul>

                <div className="mt-3 p-3 bg-black/20 rounded text-sm">
                  <p className="mb-2"><strong>Task-specific PPE combinations:</strong></p>
                  <ul className="text-white/70 list-disc pl-4 space-y-1">
                    <li><strong>Cutting conduit/trunking:</strong> Safety glasses, cut-resistant gloves, hearing protection</li>
                    <li><strong>Bending cable tray:</strong> Cut-resistant gloves, safety footwear, back support if heavy</li>
                    <li><strong>Drilling fixings:</strong> Safety glasses, dust mask, hearing protection, steel-toe boots</li>
                    <li><strong>Grinding/deburring:</strong> Face shield, hearing protection, respiratory protection, spark-resistant clothing</li>
                    <li><strong>Cable pulling:</strong> Cut-resistant gloves, safety footwear, knee protection if required</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-2"
            question={quickCheckQuestions[1].question}
            options={quickCheckQuestions[1].options}
            correctIndex={quickCheckQuestions[1].correctIndex}
            explanation={quickCheckQuestions[1].explanation}
          />

          {/* Hazards Without PPE */}
          <section className="mb-10 mt-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">05</span>
              Hazards Without PPE
            </h2>
            <div className="text-white/80 space-y-4 leading-relaxed">
              <p>
                Understanding the serious consequences of inadequate PPE helps emphasise the importance of proper protection in electrical installation work:
              </p>

              <div className="p-4 rounded-lg bg-red-500/10 border-l-2 border-red-500/50">
                <p className="font-semibold text-red-400 mb-2">Serious Injury Risks Without Proper PPE</p>
                <ul className="text-sm list-disc pl-6 space-y-1">
                  <li><strong>Eye injuries from metal swarf</strong> - permanent vision damage or blindness from cutting and grinding operations</li>
                  <li><strong>Severe cuts and lacerations</strong> - from sharp conduit edges, cable tray, and cutting tools</li>
                  <li><strong>Noise-induced hearing loss</strong> - irreversible damage from repeated exposure to power tools without protection</li>
                  <li><strong>Respiratory problems</strong> - from inhaling harmful dusts, particularly from cutting treated materials</li>
                  <li><strong>Foot and toe injuries</strong> - crushing and puncture wounds from dropped tools and materials</li>
                  <li><strong>Hand and finger injuries</strong> - burns from hot surfaces, cuts from sharp edges, impact injuries</li>
                </ul>
              </div>
            </div>
          </section>

          <InlineCheck
            id="7-3-check-3"
            question={quickCheckQuestions[2].question}
            options={quickCheckQuestions[2].options}
            correctIndex={quickCheckQuestions[2].correctIndex}
            explanation={quickCheckQuestions[2].explanation}
          />

          {/* Maintenance of PPE */}
          <section className="mb-10 mt-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">06</span>
              Maintenance of PPE
            </h2>
            <div className="text-white/80 space-y-4 leading-relaxed">
              <p>
                Proper maintenance ensures PPE remains effective throughout its service life and provides reliable protection when needed:
              </p>

              <div className="p-4 rounded-lg bg-amber-500/10 border-l-2 border-amber-500/50">
                <p className="font-semibold text-amber-400 mb-2">PPE Maintenance and Care Systems</p>
                <ul className="text-sm list-disc pl-6 space-y-1">
                  <li><strong>Daily pre-use inspection</strong> - check PPE condition before each use for damage or wear</li>
                  <li><strong>Immediate replacement</strong> - remove and replace worn or damaged items without delay</li>
                  <li><strong>Proper cleaning procedures</strong> - follow manufacturer instructions for cleaning and disinfection</li>
                  <li><strong>Appropriate storage conditions</strong> - clean, dry locations away from direct sunlight and chemicals</li>
                  <li><strong>Personal assignment</strong> - avoid sharing PPE where hygiene or fit is critical</li>
                  <li><strong>Regular replacement schedules</strong> - replace items according to manufacturer or company schedules</li>
                </ul>

                <div className="mt-3 p-3 bg-black/20 rounded text-sm">
                  <p className="mb-2"><strong>Inspection checklist for common PPE:</strong></p>
                  <ul className="text-white/70 list-disc pl-4 space-y-1">
                    <li><strong>Safety glasses:</strong> Scratches, cracks, loose components, clean lenses</li>
                    <li><strong>Gloves:</strong> Holes, tears, contamination, proper grip, sizing still correct</li>
                    <li><strong>Hearing protection:</strong> Foam condition, headband tension, seal integrity</li>
                    <li><strong>Safety boots:</strong> Sole wear, upper damage, lace condition, internal support</li>
                    <li><strong>Hard hats:</strong> Shell cracks, suspension system, expiry date, impact damage</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>

          {/* Integrating PPE with Safe Practice */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <span className="text-elec-yellow/80 text-sm font-normal">07</span>
              Integrating PPE with Safe Practice
            </h2>
            <div className="text-white/80 space-y-4 leading-relaxed">
              <p>
                PPE works most effectively when integrated with comprehensive safe working practices and proper risk management:
              </p>

              <div className="p-4 rounded-lg bg-purple-500/10 border-l-2 border-purple-500/50">
                <p className="font-semibold text-purple-400 mb-2">Comprehensive Safety Integration</p>
                <ul className="text-sm list-disc pl-6 space-y-1">
                  <li><strong>Hierarchy of control</strong> - PPE is the last line of defence, not a substitute for safe methods</li>
                  <li><strong>Job planning</strong> - always plan the task first, then select appropriate PPE for identified hazards</li>
                  <li><strong>Engineering controls</strong> - use guards, clamps, and correct tools alongside PPE for maximum protection</li>
                  <li><strong>Training integration</strong> - teach apprentices to recognise task-specific PPE requirements</li>
                  <li><strong>Environmental assessment</strong> - consider workplace conditions when selecting PPE combinations</li>
                  <li><strong>Team coordination</strong> - ensure all team members understand PPE requirements for shared tasks</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Practical Guidance */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <Wrench className="w-5 h-5" />
              Practical Guidance (On-Site Tips)
            </h2>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                <h3 className="font-medium text-white mb-2">Pre-Task PPE Preparation</h3>
                <ul className="text-sm text-white/70 space-y-1 list-disc ml-5">
                  <li>Always de-burr conduit ends before handling to reduce cut risk even with gloves</li>
                  <li>Keep a spare pair of safety glasses in your kit for when one gets damaged</li>
                  <li>Check PPE fit and condition at the start of each day, not just before first use</li>
                  <li>Ensure adequate lighting to properly inspect PPE condition</li>
                </ul>
              </div>

              <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                <h3 className="font-medium text-white mb-2">Task-Specific PPE Selection</h3>
                <ul className="text-sm text-white/70 space-y-1 list-disc ml-5">
                  <li>Wear ear protection when drilling into blockwork or using angle grinders</li>
                  <li>Use cut-resistant gloves (Level 3–5 EN388 standard) when cutting cable tray</li>
                  <li>Consider respiratory protection when cutting galvanised or treated materials</li>
                  <li>Wear steel toe-cap boots in all areas where tools and materials are being moved</li>
                </ul>
              </div>

              <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                <h3 className="font-medium text-white mb-2">PPE Management Best Practices</h3>
                <ul className="text-sm text-white/70 space-y-1 list-disc ml-5">
                  <li>Label and keep PPE personal — never swap gloves or ear protection with others</li>
                  <li>Report defective PPE immediately and remove from circulation</li>
                  <li>Clean PPE according to manufacturer instructions to maintain effectiveness</li>
                  <li>Store PPE in designated clean areas, away from tools and materials</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Real-World Examples */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <Users className="w-5 h-5" />
              Real-World Examples
            </h2>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-red-500/10 border-l-2 border-red-500/50">
                <div className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <h3 className="font-medium text-white mb-2">Case Study 1: Eye Injury from Metal Fragment</h3>
                    <p className="text-sm text-white/70 mb-2">
                      On a commercial site, an electrician was cutting trunking with a hacksaw without safety glasses. A small metal fragment flew into his eye, requiring hospital treatment and three days off work.
                    </p>
                    <p className="text-sm text-white/70 bg-black/20 p-2 rounded">
                      <strong>Prevention:</strong> Safety glasses costing less than £5 would have prevented this injury entirely.
                    </p>
                  </div>
                </div>
              </div>

              <div className="p-4 rounded-lg bg-green-500/10 border-l-2 border-green-500/50">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <h3 className="font-medium text-white mb-2">Case Study 3: Good PPE Practice Prevents Serious Injury</h3>
                    <p className="text-sm text-white/70 mb-2">
                      During cable tray installation, a worker's cut-resistant gloves prevented serious injury when a sharp edge sliced through the outer layer. The gloves were immediately replaced, and the incident was reported as a near-miss.
                    </p>
                    <p className="text-sm text-white/70 bg-black/20 p-2 rounded">
                      <strong>Good Practice:</strong> Proper PPE selection, immediate replacement when damaged, and treating near-misses as learning opportunities.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* FAQs */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <Shield className="w-5 h-5" />
              Frequently Asked Questions
            </h2>
            <div className="space-y-4">
              {faqs.map((faq, index) => (
                <div key={index} className="p-4 rounded-lg bg-white/5 border border-white/10">
                  <h3 className="font-medium text-white mb-2">{faq.question}</h3>
                  <p className="text-sm text-white/70">{faq.answer}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Pocket Guide */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <Book className="w-5 h-5" />
              Pocket Guide (Key Takeaways)
            </h2>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">PPE is legally required under PPE at Work Regulations</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">Safety glasses, gloves, boots, and hearing protection are essential</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">Always inspect and replace PPE as needed</span>
                  </div>
                </div>
              </div>
              <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">PPE complements, not replaces, safe working methods</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">Never start cutting, bending, or fixing work without full PPE</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <div className="w-2 h-2 bg-elec-yellow rounded-full"></div>
                    <span className="font-medium text-white">Store PPE in clean, dry conditions when not in use</span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Recap */}
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
              <Target className="w-5 h-5" />
              Recap
            </h2>
            <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
              <p className="text-white/80 mb-4">In this subsection, you learned:</p>
              <ul className="list-disc pl-6 space-y-2 text-white/80">
                <li>The legal requirements for PPE in electrical installation.</li>
                <li>Typical PPE used in cutting, bending, and fixing tasks.</li>
                <li>Common hazards that PPE helps prevent.</li>
                <li>How to maintain and store PPE effectively.</li>
                <li>Practical habits for keeping yourself and others safe on site.</li>
              </ul>
            </div>
          </section>

          {/* Quiz */}
          <Quiz questions={quizQuestions} title="PPE for Cutting, Bending, and Fixing Quiz" />

          {/* Navigation */}
          <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10 mt-10">
            <Button
              variant="outline"
              className="border-white/10 hover:bg-white/5 min-h-[48px] touch-manipulation active:scale-[0.98]"
              asChild
            >
              <Link to="../7-2">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back: Hand and Power Tools
              </Link>
            </Button>
            <Button
              className="bg-elec-yellow text-black hover:bg-elec-yellow/90 min-h-[48px] touch-manipulation active:scale-[0.98]"
              asChild
            >
              <Link to="../7-4">
                Next: Working in Voids, Risers, and Ceilings
                <ArrowRight className="w-4 h-4 ml-2" />
              </Link>
            </Button>
          </nav>
        </div>
      </article>
    </div>
  );
};

export default Module4Section7_3;
