import { ArrowLeft, Shield, CheckCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import useSEO from "@/hooks/useSEO";

const TITLE = "Lubrication, Cleaning and Adjustments - MOET Module 4.1.3";
const DESCRIPTION = "Bearing lubrication, motor greasing schedules, contact cleaning, thermal paste application, belt tension, alignment, torque checking, panel and filter cleaning for electrical maintenance technicians.";

const quickCheckQuestions = [
  {
    id: "over-greasing",
    question: "What is the primary risk of over-greasing an electric motor bearing?",
    options: [
      "The motor will run faster than designed",
      "Excess grease causes increased friction and heat, potentially leading to bearing failure",
      "The grease will contaminate the motor windings",
      "Over-greasing has no negative effects"
    ],
    correctIndex: 1,
    explanation: "Over-greasing is one of the most common causes of premature bearing failure in electric motors. Excess grease creates churning resistance, generating additional heat that breaks down the lubricant and accelerates bearing wear. The correct quantity — typically calculated from the bearing size — must be applied using a calibrated grease gun."
  },
  {
    id: "torque-checking",
    question: "Why must electrical connections be re-torqued periodically?",
    options: [
      "To make them easier to remove in future",
      "Because thermal cycling causes connections to loosen over time, increasing resistance and creating hot spots",
      "To change the colour of the terminals",
      "Re-torquing is only needed during initial installation"
    ],
    correctIndex: 1,
    explanation: "Electrical connections expand and contract with heating and cooling cycles (thermal cycling). This gradually loosens the connection, increasing contact resistance. Higher resistance generates more heat, which accelerates loosening further — a dangerous positive feedback loop that can lead to overheating, arcing and fire."
  },
  {
    id: "belt-tension",
    question: "What happens if a V-belt driving a motor-pump combination is too tight?",
    options: [
      "The pump will operate more efficiently",
      "Excessive bearing load on both motor and driven equipment, leading to premature bearing failure",
      "The belt will last longer",
      "Nothing — tighter is always better"
    ],
    correctIndex: 1,
    explanation: "An over-tensioned belt places excessive radial load on the bearings of both the motor and driven equipment, significantly reducing bearing life. It also accelerates belt wear and increases energy consumption. Correct tension — typically checked with a tension gauge or deflection measurement — is essential for reliable operation."
  }
];

const quizQuestions = [
  {
    id: 1,
    question: "The primary purpose of lubricating electric motor bearings is to:",
    options: [
      "Make the motor run faster",
      "Reduce friction, dissipate heat, prevent corrosion and exclude contaminants",
      "Increase the weight of the motor for stability",
      "Make the bearings easier to remove"
    ],
    correctAnswer: 1,
    explanation: "Bearing lubrication serves four key functions: reducing friction between rolling elements and races, dissipating heat generated by friction, providing a protective barrier against corrosion from moisture, and helping to exclude dust and other contaminants from the bearing. Without adequate lubrication, bearings overheat and fail rapidly."
  },
  {
    id: 2,
    question: "A motor manufacturer recommends re-greasing a bearing every 4,000 operating hours. The motor runs 16 hours per day, 5 days per week. How often should the bearing be re-greased?",
    options: [
      "Every 12 months approximately",
      "Every 12 months exactly",
      "Approximately every 10 months",
      "Every 6 months"
    ],
    correctAnswer: 2,
    explanation: "Operating hours per week = 16 x 5 = 80 hours. Operating hours per month (approx.) = 80 x 4.33 = 346 hours. Months to reach 4,000 hours = 4,000 / 346 = 11.6 months, so approximately every 10-12 months. In practice, rounding down to 10 months provides a safety margin, especially if the environment is dusty or hot."
  },
  {
    id: 3,
    question: "When cleaning electrical panel interiors, which of the following should NOT be used?",
    options: [
      "An approved electrical contact cleaner spray",
      "A vacuum cleaner with anti-static nozzle",
      "Water or water-based cleaning solutions on energised equipment",
      "Clean, lint-free cloths"
    ],
    correctAnswer: 2,
    explanation: "Water and water-based solutions must never be used on energised electrical equipment due to the risk of electric shock and short circuit. Even on de-energised equipment, water can leave conductive residues and cause corrosion. Always use approved electrical contact cleaners, vacuum cleaners with anti-static nozzles, or clean dry cloths."
  },
  {
    id: 4,
    question: "Shaft alignment between a motor and driven equipment should be checked:",
    options: [
      "Only during initial installation",
      "Regularly during PPM, as foundations can settle, vibration can shift alignment, and thermal growth changes the geometry",
      "Only when the motor is replaced",
      "Only if the operator complains about noise"
    ],
    correctAnswer: 1,
    explanation: "Shaft alignment should be checked periodically because foundations can settle or shift, vibration can move equipment, thermal expansion under operating conditions changes geometry, and coupling wear can mask misalignment. Misaligned shafts cause excessive bearing wear, seal failure, coupling damage and increased energy consumption."
  },
  {
    id: 5,
    question: "The correct procedure for re-torquing busbar connections is:",
    options: [
      "Tighten as much as possible using the longest available spanner",
      "Use a calibrated torque wrench, apply the manufacturer's specified torque value, and mark the connection to confirm completion",
      "Hand-tighten only to avoid damage",
      "Use an impact driver for speed"
    ],
    correctAnswer: 1,
    explanation: "Busbar connections must be torqued to the manufacturer's specification using a calibrated torque wrench. Under-torquing leaves loose connections; over-torquing can deform the conductor, damage plating, or crack the insulator. Marking the connection after torquing (e.g., with a witness mark) provides visual confirmation that the task has been completed."
  },
  {
    id: 6,
    question: "Air filters in electrical panel ventilation systems should be cleaned or replaced:",
    options: [
      "Only when the panel overheats",
      "At regular intervals as part of PPM, with frequency adjusted based on environmental conditions",
      "Once during the panel's lifetime",
      "Only during the five-yearly EICR"
    ],
    correctAnswer: 1,
    explanation: "Panel ventilation filters accumulate dust and debris, restricting airflow and causing internal temperatures to rise. In dusty environments (workshops, manufacturing), filters may need monthly cleaning. In cleaner environments (offices, data centres), quarterly may suffice. A blocked filter can raise internal panel temperatures by 10-20°C, significantly reducing the life of components."
  },
  {
    id: 7,
    question: "Thermal paste (compound) is used between a power semiconductor and its heat sink to:",
    options: [
      "Glue the component in place permanently",
      "Fill microscopic air gaps, improving thermal conductivity between the component and the heat sink",
      "Provide electrical insulation between the component and the heat sink",
      "Prevent the component from vibrating"
    ],
    correctAnswer: 1,
    explanation: "Thermal paste fills the microscopic air gaps between the flat surfaces of the semiconductor device and the heat sink. Air is a poor thermal conductor; the paste (typically silicone-based with metal oxide fillers) is much better. Without thermal paste, the component runs hotter, reducing its life and potentially causing premature failure."
  },
  {
    id: 8,
    question: "When greasing a motor bearing, the motor should ideally be:",
    options: [
      "Running at full speed, so the grease is distributed immediately",
      "Stationary and isolated, with grease applied slowly using a calibrated grease gun",
      "Running at half speed",
      "Under full load"
    ],
    correctAnswer: 0,
    explanation: "Best practice for motor re-greasing is to apply grease while the motor is running at normal speed. This allows the grease to be immediately distributed throughout the bearing by the rolling elements. If the motor cannot be greased while running (due to safety constraints), grease should be applied with the motor stationary, then the motor run briefly to distribute the grease before being returned to normal service."
  },
  {
    id: 9,
    question: "Contactor contacts that show heavy pitting and blackening should be:",
    options: [
      "Filed smooth and returned to service",
      "Assessed for replacement — silver or silver-alloy contacts should not be filed as this removes the contact material",
      "Cleaned with sandpaper and oiled",
      "Ignored unless the contactor fails to operate"
    ],
    correctAnswer: 1,
    explanation: "Modern contactor contacts are made of silver or silver alloy, with only a thin layer of contact material. Filing removes this material, reducing the contact's life and potentially changing the contact geometry. Heavily pitted contacts should be replaced as a set. Minor discolouration is normal and does not require action — silver oxide is actually a conductor."
  },
  {
    id: 10,
    question: "Environmental considerations when disposing of used lubricants include:",
    options: [
      "Used oil can be poured down the drain",
      "Used lubricants are classified as hazardous waste and must be collected, stored and disposed of through a licensed waste carrier",
      "Used grease can be placed in general waste bins",
      "There are no regulations covering lubricant disposal"
    ],
    correctAnswer: 1,
    explanation: "Used lubricating oils and greases are classified as hazardous waste under the Hazardous Waste Regulations. They must be collected in suitable containers, stored in designated areas with secondary containment, and disposed of through a licensed waste carrier. Duty of care requirements under the Environmental Protection Act 1990 apply to everyone in the waste chain."
  }
];

const faqs = [
  {
    question: "How do I know how much grease to put in a motor bearing?",
    answer: "The quantity of grease depends on the bearing size. The standard formula is: Grease quantity (grams) = 0.005 x D x B, where D is the bearing outside diameter in mm and B is the bearing width in mm. For example, a bearing with OD 120 mm and width 30 mm needs approximately 0.005 x 120 x 30 = 18 grams. Many motor manufacturers also specify the quantity on the motor nameplate or in the installation manual. Always use a calibrated grease gun to ensure the correct amount is applied."
  },
  {
    question: "Should I use oil or grease for motor bearings?",
    answer: "Most standard electric motors use grease-lubricated bearings because grease is simpler to apply, seals better against contamination, and does not leak. Oil lubrication is used for high-speed motors, very high-temperature applications, or large bearings where grease cannot dissipate enough heat. If in doubt, always follow the motor manufacturer's recommendation — the bearing type and lubrication method are specified at the design stage."
  },
  {
    question: "What torque values should I use for busbar connections?",
    answer: "Torque values depend on the bolt size, conductor material and contact plating. Typical values for copper busbars with M10 bolts are 40-50 Nm, but this varies significantly with the installation. Always refer to the switchgear manufacturer's documentation for specific torque values. Using generic values risks either under-torquing (loose connection) or over-torquing (damaged conductor or insulator). A calibrated torque wrench is essential — do not estimate."
  },
  {
    question: "How do I check belt tension correctly?",
    answer: "The most common method is the deflection check: measure the span length between pulleys, then apply a perpendicular force at the midpoint. The belt should deflect approximately 1.5% of the span length per 10 N of force applied. For example, for a 1,000 mm span, the deflection should be about 15 mm under 10 N. A belt tension gauge provides more accurate and repeatable measurements. Always refer to the belt manufacturer's tensioning data for the specific belt profile."
  },
  {
    question: "Is it safe to clean electrical panels with compressed air?",
    answer: "Compressed air is generally not recommended for cleaning electrical panels because it can blow dust and debris into contacts, push contamination further into equipment, and generate static charges. If compressed air must be used, it should be at low pressure (below 2 bar), directed away from sensitive components, and used only on de-energised equipment. A vacuum cleaner with an anti-static nozzle is the preferred method for removing loose dust and debris from panels."
  }
];

const MOETModule4Section1_3 = () => {
  useSEO(TITLE, DESCRIPTION);

  return (
    <div className="overflow-x-hidden bg-[#1a1a1a]">
      {/* Sticky Header */}
      <div className="border-b border-white/10 sticky top-0 z-30 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/study-centre/apprentice/m-o-e-t-module4-section1">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      <article className="px-4 sm:px-6 py-8 sm:py-12">

        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Shield className="h-4 w-4" />
            <span>Module 4.1.3</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            Lubrication, Cleaning and Adjustments
          </h1>
          <p className="text-white/80">
            Hands-on PPM techniques for bearings, contacts, belts, panels and mechanical components
          </p>
        </header>

        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2 text-center sm:text-left">In 30 Seconds</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5 text-left">
              <li className="pl-1"><strong>Lubrication:</strong> Correct grease type, quantity and frequency prevent bearing failure</li>
              <li className="pl-1"><strong>Cleaning:</strong> Dust, dirt and contamination degrade insulation and cause overheating</li>
              <li className="pl-1"><strong>Adjustments:</strong> Belt tension, alignment and torque require regular checking</li>
              <li className="pl-1"><strong>Environmental:</strong> Hazardous waste disposal rules apply to used lubricants</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2 text-center sm:text-left">Electrical Maintenance Context</p>
            <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5 text-left">
              <li className="pl-1"><strong>Motor greasing:</strong> Calculated quantities, calibrated gun, correct intervals</li>
              <li className="pl-1"><strong>Panel cleaning:</strong> Vacuum with anti-static nozzle, contact cleaner spray</li>
              <li className="pl-1"><strong>Torque checking:</strong> Busbars, terminals — calibrated wrench to spec</li>
              <li className="pl-1"><strong>ST1426:</strong> Practical maintenance skills are a core requirement</li>
            </ul>
          </div>
        </div>

        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You'll Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              "Apply correct bearing lubrication techniques for electric motors",
              "Calculate grease quantities and determine re-greasing intervals",
              "Clean electrical panels and components safely using appropriate methods",
              "Check and adjust belt tension and shaft alignment",
              "Re-torque electrical connections using calibrated tools",
              "Dispose of used lubricants and cleaning materials in compliance with environmental regulations"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        <hr className="border-white/5 mb-12" />

        {/* Section 01: Bearing Lubrication */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            Bearing Lubrication
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Bearing failure is the single most common cause of electric motor breakdown. In the majority of
              cases, the root cause is lubrication-related — either insufficient lubrication, excessive
              lubrication, contaminated lubricant, or the wrong type of lubricant. Getting lubrication right
              is one of the highest-value PPM activities a maintenance technician can perform.
            </p>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Grease vs Oil Lubrication</p>
              <div className="overflow-x-auto">
                <table className="text-sm text-white w-full border-collapse">
                  <thead>
                    <tr className="bg-white/5">
                      <th className="border border-white/10 px-3 py-2 text-left">Factor</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Grease</th>
                      <th className="border border-white/10 px-3 py-2 text-left">Oil</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Application</td>
                      <td className="border border-white/10 px-3 py-2">Most standard motors up to ~3,600 rpm</td>
                      <td className="border border-white/10 px-3 py-2">High-speed motors, very large bearings, high-temp applications</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Sealing</td>
                      <td className="border border-white/10 px-3 py-2">Good — stays in the bearing housing</td>
                      <td className="border border-white/10 px-3 py-2">Requires oil seals; risk of leakage</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Contamination protection</td>
                      <td className="border border-white/10 px-3 py-2">Good — grease acts as a barrier</td>
                      <td className="border border-white/10 px-3 py-2">Moderate — requires effective sealing</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Heat dissipation</td>
                      <td className="border border-white/10 px-3 py-2">Limited</td>
                      <td className="border border-white/10 px-3 py-2">Good — circulating oil removes heat</td>
                    </tr>
                    <tr>
                      <td className="border border-white/10 px-3 py-2">Maintenance</td>
                      <td className="border border-white/10 px-3 py-2">Periodic re-greasing via grease nipple</td>
                      <td className="border border-white/10 px-3 py-2">Oil level checks, periodic oil changes</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Grease Quantity Calculation</p>
              <p className="text-sm text-white mb-2">
                The standard formula for calculating the correct grease quantity for a single re-greasing event is:
              </p>
              <div className="bg-white/5 p-3 rounded text-sm font-mono text-elec-yellow/90 mb-2">
                G = 0.005 x D x B
              </div>
              <p className="text-sm text-white mb-2">
                Where G = grease quantity in grams, D = bearing outside diameter in mm, B = bearing width in mm.
              </p>
              <p className="text-sm text-white">
                For example, a 6310 bearing (OD 110 mm, width 27 mm): G = 0.005 x 110 x 27 = 14.9 g.
                A calibrated grease gun typically delivers a known quantity per stroke (e.g., 1.5 g per stroke
                for a standard lever gun), allowing precise application.
              </p>
            </div>

            <div className="my-6 p-4 rounded-lg bg-red-500/10 border border-red-500/30">
              <p className="text-sm font-medium text-red-400 mb-2">Over-Greasing — The Hidden Killer</p>
              <p className="text-sm text-white">
                Over-greasing causes more bearing failures than under-greasing. Excess grease cannot escape
                the bearing housing, creating churning resistance that generates heat. This heat breaks down
                the grease, reducing its lubricating properties, which generates more heat — a destructive
                cycle. Symptoms include elevated bearing temperature, grease leaking from seals, and in severe
                cases, grease being forced past the inner seal and contaminating motor windings.
              </p>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>Key point:</strong> Never mix different grease types. Incompatible greases can react
              chemically, causing the mixture to soften excessively or harden, destroying its lubricating
              properties. If changing grease type, the old grease must be completely purged first.
            </p>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 02: Contact Cleaning and Thermal Paste */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            Contact Cleaning and Thermal Compound
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Electrical contacts degrade through use. Arcing erodes contact surfaces, oxidation increases
              resistance, and contamination from dust and atmospheric pollutants creates insulating films.
              Regular cleaning and inspection of contacts is essential for reliable operation and safety.
            </p>

            <div className="my-6 space-y-4">
              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Contactor and Relay Contacts</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">Silver and silver-alloy contacts: Do not file — silver oxide is conductive; filing removes the thin contact material layer</li>
                  <li className="pl-1">Copper contacts: May be lightly dressed with a fine file if heavily pitted, then cleaned with contact cleaner</li>
                  <li className="pl-1">Replacement: Contacts worn to 50% of original thickness or with deep pitting should be replaced as a matched set</li>
                  <li className="pl-1">Contact gap: Check against manufacturer specification — incorrect gap can cause chattering or failure to break</li>
                  <li className="pl-1">Spring pressure: Weakened contact springs reduce pressure, increasing resistance and arcing</li>
                </ul>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Circuit Breaker Contacts</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1">ACB and MCCB contacts: Inspect for erosion, pitting and discolouration during scheduled maintenance</li>
                  <li className="pl-1">Contact resistance measurement: Use a DLRO (digital low resistance ohmmeter) to measure micro-ohm resistance across closed contacts</li>
                  <li className="pl-1">Arcing chambers: Inspect and clean arc chutes; replace if cracked or heavily carbonised</li>
                  <li className="pl-1">Operating mechanism: Clean, lubricate and check for correct operation per manufacturer's instructions</li>
                </ul>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Thermal Paste Application</h3>
                <p className="text-sm text-white mb-2">
                  Power semiconductors (thyristors, IGBTs, diodes) in variable speed drives and power
                  supplies rely on thermal paste to transfer heat to their heat sinks. During PPM, the
                  condition of thermal paste should be checked and renewed if dried out or degraded.
                </p>
                <ul className="text-sm text-white space-y-1 list-disc list-outside ml-5">
                  <li className="pl-1">Remove old paste completely using isopropyl alcohol and lint-free cloth</li>
                  <li className="pl-1">Apply a thin, even layer — too much is as bad as too little</li>
                  <li className="pl-1">Ensure mounting screws are torqued evenly to specification</li>
                  <li className="pl-1">Use only the paste type specified by the manufacturer (silicone-based, metal oxide filled)</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 03: Belt Tension and Alignment */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Belt Tension, Alignment and Torque Checking
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Many electrical maintenance technicians work on motor-driven systems where mechanical
              adjustments are integral to reliable operation. Belt tension, shaft alignment and connection
              torque are three critical adjustments that directly affect equipment reliability, energy
              consumption and safety.
            </p>

            <div className="grid sm:grid-cols-2 gap-4 my-6">
              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Belt Tension</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Too loose:</strong> Belt slips, generates heat, wears rapidly, power transmission lost</li>
                  <li className="pl-1"><strong>Too tight:</strong> Excessive bearing load, premature bearing failure, increased energy use</li>
                  <li className="pl-1"><strong>Check method:</strong> Deflection test — measure span, apply force at midpoint, check deflection against specification</li>
                  <li className="pl-1"><strong>Frequency:</strong> Check tension after first 24-48 hours of running a new belt, then at each PPM visit</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Shaft Alignment</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Angular misalignment:</strong> Shaft centrelines intersect at an angle — causes axial vibration</li>
                  <li className="pl-1"><strong>Parallel (offset) misalignment:</strong> Shafts are parallel but offset — causes radial vibration</li>
                  <li className="pl-1"><strong>Dial indicator method:</strong> Traditional approach using clock gauges on coupling faces and rims</li>
                  <li className="pl-1"><strong>Laser alignment:</strong> Modern method providing faster, more accurate results with digital readout</li>
                </ul>
              </div>
            </div>

            <div className="my-6 p-4 rounded-lg bg-white/5">
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Connection Torque Checking</h3>
              <p className="text-sm text-white mb-2">
                Re-torquing electrical connections is one of the most effective PPM tasks for preventing
                electrical fires. All bolted electrical connections should be checked at intervals
                determined by the installation type and operating conditions.
              </p>
              <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                <li className="pl-1"><strong>Equipment:</strong> Calibrated torque wrench (insulated for electrical work); correct socket/spanner</li>
                <li className="pl-1"><strong>Values:</strong> Refer to manufacturer's specification — typical values: M6 = 7-9 Nm, M8 = 18-22 Nm, M10 = 35-45 Nm, M12 = 55-70 Nm (varies with material)</li>
                <li className="pl-1"><strong>Technique:</strong> Apply torque smoothly; do not jerk. Re-torque in a star pattern on multi-bolt connections</li>
                <li className="pl-1"><strong>Recording:</strong> Mark completed connections with torque seal or witness mark; record in maintenance log</li>
                <li className="pl-1"><strong>Safety:</strong> Always work on de-energised, isolated equipment; use insulated tools as a secondary precaution</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Section 04: Panel Cleaning and Environmental Considerations */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Panel Cleaning and Environmental Considerations
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Dust, dirt and contamination are the enemies of electrical equipment. They reduce insulation
              resistance, block ventilation, trap moisture and can provide conductive paths leading to
              tracking and flashover. Regular cleaning is a fundamental PPM activity.
            </p>

            <div className="my-6 space-y-4">
              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Panel Interior Cleaning</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Isolate first:</strong> All cleaning of panel interiors must be carried out on de-energised, isolated equipment</li>
                  <li className="pl-1"><strong>Vacuum:</strong> Use a vacuum cleaner with anti-static nozzle to remove loose dust and debris</li>
                  <li className="pl-1"><strong>Wipe:</strong> Clean surfaces with lint-free cloths dampened with approved electrical cleaner</li>
                  <li className="pl-1"><strong>Contacts:</strong> Spray contact cleaner on relay and contactor contacts; allow to evaporate fully</li>
                  <li className="pl-1"><strong>Ventilation:</strong> Clean or replace air filters; check fan operation and airflow</li>
                  <li className="pl-1"><strong>Sealing:</strong> Check door seals and cable entry glands for integrity — gaps allow dust and vermin ingress</li>
                </ul>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Environmental Compliance</h3>
                <ul className="text-sm text-white space-y-1.5 list-disc list-outside ml-5">
                  <li className="pl-1"><strong>Used lubricants:</strong> Classified as hazardous waste — collect in sealed containers, dispose via licensed carrier</li>
                  <li className="pl-1"><strong>Contact cleaner:</strong> Many solvents are volatile organic compounds (VOCs) — use in ventilated areas, dispose of empty cans correctly</li>
                  <li className="pl-1"><strong>Contaminated cloths:</strong> Oil-soaked rags are a fire hazard and hazardous waste — store in metal lidded containers</li>
                  <li className="pl-1"><strong>COSHH:</strong> All cleaning chemicals require COSHH assessments; safety data sheets must be available</li>
                  <li className="pl-1"><strong>Waste documentation:</strong> Hazardous waste consignment notes must be completed for each collection</li>
                </ul>
              </div>
            </div>

            <p className="text-sm text-elec-yellow/70">
              <strong>ST1426 link:</strong> The maintenance technician standard requires you to carry out
              maintenance tasks safely, using appropriate tools and materials, and to comply with environmental
              regulations including waste disposal requirements. Practical competence in lubrication, cleaning
              and adjustment is assessed during the end-point assessment.
            </p>
          </div>
        </section>

        <hr className="border-white/5 my-12" />

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <h3 className="text-sm font-medium text-white mb-1">{faq.question}</h3>
                <p className="text-sm text-white/90 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        <hr className="border-white/5 my-12" />

        <section className="mb-10">
          <div className="p-5 rounded-lg bg-transparent">
            <h3 className="text-sm font-medium text-white mb-4">Quick Reference</h3>
            <div className="grid sm:grid-cols-2 gap-4 text-xs text-white">
              <div>
                <p className="font-medium text-white mb-1">Grease Quantity Formula</p>
                <ul className="space-y-0.5">
                  <li>G = 0.005 x D x B (grams)</li>
                  <li>D = bearing outside diameter (mm)</li>
                  <li>B = bearing width (mm)</li>
                  <li>Use calibrated grease gun</li>
                  <li>Never mix grease types</li>
                </ul>
              </div>
              <div>
                <p className="font-medium text-white mb-1">Torque Check Process</p>
                <ul className="space-y-0.5">
                  <li>1. Isolate and lock off</li>
                  <li>2. Use calibrated torque wrench</li>
                  <li>3. Apply manufacturer's specified torque</li>
                  <li>4. Star pattern on multi-bolt joints</li>
                  <li>5. Apply witness mark and record</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-10">
          <Quiz title="Test Your Knowledge" questions={quizQuestions} />
        </section>

        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/study-centre/apprentice/m-o-e-t-module4-section1-2">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Previous: Scheduling and Records
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/study-centre/apprentice/m-o-e-t-module4-section1-4">
              Next: Electrical Inspection Routines
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>

      </article>
    </div>
  );
};

export default MOETModule4Section1_3;
