
export interface EnhancedEducationOption {
  id: number;
  title: string;
  institution: string;
  description: string;
  level: string;
  category: string;
  duration: string;
  studyMode: string;
  cost: string;
  fundingOptions: string[];
  locations: string[];
  nextIntakes: string[];
  entryRequirements: string[];
  keyTopics: string[];
  careerOutcomes: string[];
  employmentRate: number;
  averageStartingSalary: string;
  industryDemand: "High" | "Medium" | "Low";
  rating: number;
  accreditation: string[];
  partnerEmployers: string[];
  onlineComponents: boolean;
  practicalHours: number;
  assessmentMethods: string[];
}

export const educationCategories = [
  "All Categories",
  "Higher National Certificates (HNC)",
  "Higher National Diplomas (HND)", 
  "Foundation Degrees",
  "Bachelor's Degrees",
  "Master's Degrees",
  "Professional Certifications",
  "Apprenticeship Pathway"
];

export const studyModes = [
  "All Study Modes",
  "Full-time",
  "Part-time", 
  "Distance Learning",
  "Flexible",
  "Evening Classes",
  "Weekend Study"
];

export const enhancedEducationOptions: EnhancedEducationOption[] = [
  {
    id: 1,
    title: "HNC Electrical Engineering",
    institution: "City & Guilds College London",
    description: "Comprehensive Higher National Certificate covering electrical engineering fundamentals with hands-on practical experience and industry-relevant theory.",
    level: "Level 4",
    category: "Higher National Certificates (HNC)",
    duration: "1-2 years",
    studyMode: "Part-time",
    cost: "£3,500 - £5,200",
    fundingOptions: ["Advanced Learner Loan", "Employer Sponsorship", "Self-funded", "Skills Bank"],
    locations: ["London", "Birmingham", "Manchester", "Leeds", "Glasgow"],
    nextIntakes: ["September 2025", "January 2026"],
    entryRequirements: ["Level 3 Electrical Installation", "C&G 2365", "NVQ Level 3", "Relevant work experience", "18th Edition Wiring Regulations"],
    keyTopics: ["Electrical Principles", "Circuit Analysis", "Power Systems", "Control Systems", "Health & Safety", "Project Management", "BS 7671", "Motor Control"],
    careerOutcomes: ["Electrical Technician", "Maintenance Engineer", "Design Technician", "Project Coordinator", "Site Supervisor"],
    employmentRate: 96,
    averageStartingSalary: "£28,000 - £32,000",
    industryDemand: "High",
    rating: 4.8,
    accreditation: ["Pearson BTEC", "City & Guilds", "EAL", "IET Recognition"],
    partnerEmployers: ["Balfour Beatty", "Kier Group", "Skanska", "NICEIC Approved Contractors"],
    onlineComponents: true,
    practicalHours: 240,
    assessmentMethods: ["Coursework", "Practical Assessment", "Written Examinations", "Portfolio Development"]
  },
  {
    id: 2,
    title: "HND Electrical & Electronic Engineering",
    institution: "Coventry University",
    description: "Advanced Higher National Diploma combining electrical and electronic engineering with modern technology applications and strong industry partnerships.",
    level: "Level 5",
    category: "Higher National Diplomas (HND)",
    duration: "2 years full-time, 3 years part-time",
    studyMode: "Full-time",
    cost: "£6,800 - £8,500",
    fundingOptions: ["Advanced Learner Loan", "Student Finance", "Employer Sponsorship", "IET Scholarships"],
    locations: ["Coventry", "London", "Scarborough", "Online delivery"],
    nextIntakes: ["September 2025", "February 2026"],
    entryRequirements: ["HNC or equivalent", "Level 3 qualifications", "Industry experience", "GCSE Maths & English Grade C/4"],
    keyTopics: ["Advanced Circuit Design", "Digital Systems", "Power Electronics", "Renewable Energy", "Automation", "Research Methods", "Smart Grids", "Energy Storage"],
    careerOutcomes: ["Senior Technician", "Design Engineer", "Project Engineer", "Technical Manager", "Energy Consultant"],
    employmentRate: 94,
    averageStartingSalary: "£32,000 - £38,000",
    industryDemand: "High",
    rating: 4.7,
    accreditation: ["Pearson BTEC", "IET Accredited", "Engineering Council Recognised"],
    partnerEmployers: ["Rolls-Royce", "BAE Systems", "Schneider Electric", "National Grid"],
    onlineComponents: true,
    practicalHours: 480,
    assessmentMethods: ["Portfolio", "Group Projects", "Presentations", "Technical Reports", "Industry Placement"]
  },
  {
    id: 3,
    title: "BEng (Hons) Electrical Engineering",
    institution: "University of Strathclyde",
    description: "Honours degree in electrical engineering with strong industry connections, covering power systems, electronics, and emerging technologies.",
    level: "Level 6",
    category: "Bachelor's Degrees",
    duration: "3-4 years full-time, 5-6 years part-time",
    studyMode: "Full-time",
    cost: "£9,250 per year (UK students)",
    fundingOptions: ["Student Finance", "Scholarships", "Employer Sponsorship", "Bursaries", "IET Power Academy"],
    locations: ["Glasgow", "London", "Distance learning available"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["A-Levels: ABB including Maths", "BTEC Triple Distinction", "HND with Merit", "Scottish Highers: AABBB"],
    keyTopics: ["Power Systems Engineering", "Control Engineering", "Signal Processing", "Renewable Energy Systems", "Professional Engineering", "Smart Grid Technology", "Electric Vehicles"],
    careerOutcomes: ["Graduate Engineer", "Design Engineer", "Project Engineer", "Research & Development", "Chartered Engineer pathway"],
    employmentRate: 97,
    averageStartingSalary: "£26,000 - £32,000",
    industryDemand: "High",
    rating: 4.9,
    accreditation: ["IET Accredited", "Engineering Council", "EUR-ACE Quality Label"],
    partnerEmployers: ["Scottish Power", "SSE", "National Grid", "Ørsted", "EDF Energy"],
    onlineComponents: false,
    practicalHours: 600,
    assessmentMethods: ["Examinations", "Coursework", "Laboratory Reports", "Final Year Project", "Professional Development"]
  },
  {
    id: 4,
    title: "Foundation Degree in Building Services Engineering",
    institution: "South Thames College",
    description: "Work-focused foundation degree combining electrical, mechanical, and building services with strong employer partnerships and practical application.",
    level: "Level 5",
    category: "Foundation Degrees",
    duration: "2 years full-time, 3 years part-time",
    studyMode: "Part-time",
    cost: "£4,500 - £6,000",
    fundingOptions: ["Student Finance", "Advanced Learner Loan", "Employer Sponsorship", "Access to HE Diploma funding"],
    locations: ["London", "Surrey", "Kent", "Evening classes available"],
    nextIntakes: ["September 2025", "January 2026"],
    entryRequirements: ["Level 3 qualification", "Relevant work experience", "GCSE Maths & English", "Industry portfolio"],
    keyTopics: ["HVAC Systems", "Electrical Installation", "Energy Management", "Sustainability", "Building Regulations", "MEP Design", "BIM Technology"],
    careerOutcomes: ["Building Services Technician", "Energy Assessor", "Facilities Manager", "MEP Coordinator", "Sustainability Consultant"],
    employmentRate: 92,
    averageStartingSalary: "£24,000 - £28,000",
    industryDemand: "Medium",
    rating: 4.5,
    accreditation: ["University of Greenwich validated", "CIBSE Recognition"],
    partnerEmployers: ["Crown House Technologies", "Skanska", "Mace Group", "Arup"],
    onlineComponents: true,
    practicalHours: 300,
    assessmentMethods: ["Work-based Assessment", "Portfolio", "Technical Reports", "Site Visits"]
  },
  {
    id: 5,
    title: "MSc Renewable Energy Engineering",
    institution: "University of Edinburgh",
    description: "Advanced master's degree focusing on renewable energy technologies, smart grids, and sustainable electrical systems with cutting-edge research opportunities.",
    level: "Level 7",
    category: "Master's Degrees",
    duration: "1 year full-time, 2 years part-time",
    studyMode: "Full-time",
    cost: "£12,500 - £15,000",
    fundingOptions: ["Postgraduate Loan", "Research Councils", "Industry Sponsorship", "Scholarships", "Green Skills Funding"],
    locations: ["Edinburgh", "Online delivery available"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["Bachelor's degree 2:1 or above", "Engineering background preferred", "Professional experience considered", "IELTS 6.5 (international)"],
    keyTopics: ["Wind Energy Systems", "Solar PV Technology", "Energy Storage", "Smart Grid Technology", "Policy & Economics", "Carbon Management", "Grid Integration"],
    careerOutcomes: ["Renewable Energy Engineer", "Project Developer", "Energy Consultant", "Research Engineer", "Sustainability Manager"],
    employmentRate: 95,
    averageStartingSalary: "£35,000 - £45,000",
    industryDemand: "High",
    rating: 4.8,
    accreditation: ["IET Accredited", "Engineering Council", "Institute of Energy"],
    partnerEmployers: ["Ørsted", "EDF Renewables", "ScottishPower Renewables", "Vattenfall"],
    onlineComponents: true,
    practicalHours: 200,
    assessmentMethods: ["Dissertation", "Group Project", "Technical Assignments", "Industry Placement", "Research Proposal"]
  },
  {
    id: 6,
    title: "City & Guilds 2391-52 Inspection & Testing",
    institution: "Various NICEIC Training Centres",
    description: "Professional certification for electrical inspection and testing, essential for qualified electricians seeking advancement and NICEIC/NAPIT registration.",
    level: "Level 3",
    category: "Professional Certifications",
    duration: "5-10 days intensive",
    studyMode: "Flexible",
    cost: "£800 - £1,200",
    fundingOptions: ["Employer Funding", "Self-funded", "Skills Bank", "CITB Grants"],
    locations: ["Nationwide locations", "London", "Birmingham", "Manchester", "Glasgow", "Online theory"],
    nextIntakes: ["Monthly intakes available"],
    entryRequirements: ["18th Edition", "Level 3 Electrical qualification", "Industry experience", "AM2 Assessment"],
    keyTopics: ["BS 7671 Requirements", "Test Equipment", "Inspection Procedures", "Certification", "Health & Safety", "Fault Finding", "Documentation"],
    careerOutcomes: ["Qualified Supervisor", "Inspection Engineer", "Compliance Officer", "Self-employment opportunities", "NICEIC Approved Contractor"],
    employmentRate: 98,
    averageStartingSalary: "£32,000 - £40,000",
    industryDemand: "High",
    rating: 4.9,
    accreditation: ["City & Guilds", "EAL", "NICEIC Approved", "NAPIT Recognised"],
    partnerEmployers: ["NICEIC", "NAPIT", "Electrical Safety First", "SELECT Scotland"],
    onlineComponents: false,
    practicalHours: 35,
    assessmentMethods: ["Practical Assessment", "Multiple Choice Exam", "Open Book Exam", "Portfolio Evidence"]
  },
  {
    id: 7,
    title: "Degree Apprenticeship - Electrical Engineering",
    institution: "Rolls-Royce & University Partners",
    description: "Earn whilst you learn degree apprenticeship combining university study with hands-on experience at leading engineering companies. Fully funded pathway to BEng/MEng.",
    level: "Level 6",
    category: "Apprenticeship Pathway",
    duration: "4-5 years",
    studyMode: "Part-time",
    cost: "Fully funded by employer",
    fundingOptions: ["Fully funded", "Apprenticeship Levy", "Government co-investment"],
    locations: ["Derby", "Bristol", "Various employer sites", "University campuses"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["A-Levels AAB", "Strong GCSE profile", "Successful assessment centre", "Aptitude tests"],
    keyTopics: ["Engineering Fundamentals", "Power Systems", "Control Systems", "Professional Skills", "Research Project", "Manufacturing", "Quality Management"],
    careerOutcomes: ["Graduate Engineer", "Design Engineer", "Project Engineer", "Technical Specialist", "Management pathway"],
    employmentRate: 100,
    averageStartingSalary: "£28,000 - £35,000",
    industryDemand: "High",
    rating: 4.9,
    accreditation: ["IET Accredited", "University validated", "Engineering Council"],
    partnerEmployers: ["Rolls-Royce", "BAE Systems", "Siemens", "Jaguar Land Rover"],
    onlineComponents: true,
    practicalHours: 1200,
    assessmentMethods: ["University Assessments", "Workplace Projects", "Portfolio", "Final Degree Project", "Professional Review"]
  },
  {
    id: 8,
    title: "BSc (Hons) Smart Grid Technology",
    institution: "Nottingham Trent University",
    description: "Cutting-edge degree programme focusing on future electrical networks, IoT integration, and digital energy systems. Addressing the UK's Net Zero ambitions.",
    level: "Level 6",
    category: "Bachelor's Degrees",
    duration: "3 years full-time, 4 years with placement",
    studyMode: "Full-time",
    cost: "£9,250 per year (UK students)",
    fundingOptions: ["Student Finance", "Industry Scholarships", "Placement Year Salary", "Green Skills Scholarships"],
    locations: ["Nottingham", "Online components available"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["A-Levels: BBC including Maths", "BTEC Extended Diploma", "Access to HE", "Scottish Highers"],
    keyTopics: ["Smart Grid Architecture", "Data Analytics", "IoT Systems", "Cybersecurity", "Energy Storage", "Electric Vehicles", "Machine Learning", "Grid Flexibility"],
    careerOutcomes: ["Smart Grid Engineer", "Data Analyst", "Network Engineer", "Innovation Specialist", "Digital Energy Consultant"],
    employmentRate: 93,
    averageStartingSalary: "£25,000 - £30,000",
    industryDemand: "High",
    rating: 4.6,
    accreditation: ["IET Recognition pending", "University validated"],
    partnerEmployers: ["National Grid ESO", "UK Power Networks", "Octopus Energy", "Centrica"],
    onlineComponents: true,
    practicalHours: 450,
    assessmentMethods: ["Practical Projects", "Data Analysis Tasks", "Group Work", "Industry Challenge", "Innovation Portfolio"]
  },
  {
    id: 9,
    title: "MEng Electrical & Electronic Engineering",
    institution: "Imperial College London",
    description: "Prestigious four-year integrated master's degree combining undergraduate and postgraduate study. Leading to Chartered Engineer status with exceptional industry connections.",
    level: "Level 7",
    category: "Master's Degrees",
    duration: "4 years full-time",
    studyMode: "Full-time",
    cost: "£9,250 per year (UK students)",
    fundingOptions: ["Student Finance", "Imperial Scholarships", "Industry Sponsorship", "EEE Department Bursaries"],
    locations: ["London (South Kensington)"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["A-Levels: A*A*A including Maths & Physics", "STEP/AEA desirable", "Strong personal statement"],
    keyTopics: ["Advanced Power Electronics", "Machine Learning", "Quantum Technologies", "Sustainable Energy", "Biomedical Engineering", "Wireless Communications"],
    careerOutcomes: ["Senior Design Engineer", "Research Engineer", "Technical Consultant", "Engineering Manager", "Technology Entrepreneur"],
    employmentRate: 98,
    averageStartingSalary: "£35,000 - £50,000",
    industryDemand: "High",
    rating: 4.9,
    accreditation: ["IET Accredited", "Engineering Council", "EUR-ACE"],
    partnerEmployers: ["ARM", "Google DeepMind", "Tesla", "National Grid", "Space industry"],
    onlineComponents: false,
    practicalHours: 800,
    assessmentMethods: ["Examinations", "Laboratory Work", "Group Design Project", "Individual Research Project", "Professional Development"]
  },
  {
    id: 10,
    title: "IET Power Academy Scholarship Programme",
    institution: "Multiple University Partners",
    description: "Prestigious scholarship programme for electrical power engineering study. Combines academic excellence with industry mentorship and guaranteed graduate employment.",
    level: "Level 6-7",
    category: "Bachelor's Degrees",
    duration: "3-4 years (depends on course)",
    studyMode: "Full-time",
    cost: "Tuition fees covered + £2,000/year bursary",
    fundingOptions: ["IET Power Academy Scholarship", "Industry partner funding", "Student Finance top-up"],
    locations: ["Manchester", "Strathclyde", "Cardiff", "Southampton", "Bath"],
    nextIntakes: ["September 2025"],
    entryRequirements: ["A-Levels: AAB including Maths", "Passion for power engineering", "Leadership potential", "Interview"],
    keyTopics: ["Power Generation", "Transmission & Distribution", "Smart Grids", "Renewable Integration", "Grid Stability", "Power Electronics"],
    careerOutcomes: ["Power Systems Engineer", "Grid Operations Engineer", "Protection Engineer", "Asset Manager", "Technical Specialist"],
    employmentRate: 100,
    averageStartingSalary: "£30,000 - £40,000",
    industryDemand: "High",
    rating: 4.9,
    accreditation: ["IET Accredited", "Power industry validated"],
    partnerEmployers: ["National Grid", "UK Power Networks", "SSE", "Scottish Power", "Western Power Distribution"],
    onlineComponents: false,
    practicalHours: 500,
    assessmentMethods: ["Academic Assessment", "Industry Projects", "Placement Reports", "Professional Development", "Leadership Activities"]
  }
];
