// Outreach unsubscribe — RFC 8058 one-click + branded confirmation page.
//
// - GET renders a confirmation page. No suppression happens on GET, so Gmail /
//   Outlook link pre-fetchers can't auto-unsubscribe recipients.
// - POST actually suppresses. Used by:
//     1. The native "Unsubscribe" button Gmail/Outlook render from the
//        List-Unsubscribe + List-Unsubscribe-Post: One-Click headers (they
//        POST directly to the URL).
//     2. The confirmation page's form submit.
// - Tokens are HMAC-signed so only a token generated by our send function is
//   accepted. Base64(email) was previously used and was trivially forgeable.
//
// Env:
//   OUTREACH_UNSUB_SECRET  -- HMAC secret (falls back to SUPABASE_SERVICE_ROLE_KEY).
//   SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY -- standard Supabase service access.

import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

// ─── HMAC helpers ──────────────────────────────────────────────────
const textEncoder = new TextEncoder();

function getSecret(): string {
  return (
    Deno.env.get('OUTREACH_UNSUB_SECRET') ||
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ||
    ''
  );
}

function base64UrlEncode(bytes: Uint8Array): string {
  let str = '';
  for (let i = 0; i < bytes.length; i++) str += String.fromCharCode(bytes[i]);
  return btoa(str).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function base64UrlDecodeToBytes(input: string): Uint8Array {
  const padded = input.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (input.length % 4)) % 4);
  const bin = atob(padded);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function base64UrlDecodeToString(input: string): string {
  const bytes = base64UrlDecodeToBytes(input);
  return new TextDecoder().decode(bytes);
}

async function hmacSha256(secret: string, message: string): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    'raw',
    textEncoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, textEncoder.encode(message));
  return new Uint8Array(sig);
}

// Token format: <base64url(email)>.<base64url(hmac)>
async function verifyToken(token: string): Promise<string | null> {
  const parts = token.split('.');
  if (parts.length !== 2) return null;
  const [payload, signature] = parts;
  let email: string;
  try {
    email = base64UrlDecodeToString(payload).trim().toLowerCase();
  } catch {
    return null;
  }
  if (!email.includes('@')) return null;

  const secret = getSecret();
  if (!secret) return null;
  const expected = await hmacSha256(secret, email);
  const expectedB64 = base64UrlEncode(expected);

  // constant-time-ish compare
  if (expectedB64.length !== signature.length) return null;
  let diff = 0;
  for (let i = 0; i < expectedB64.length; i++) {
    diff |= expectedB64.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return diff === 0 ? email : null;
}

// Legacy fallback — accept old base64(email) tokens that were already in-flight
// before this rewrite deployed. These are deleted from new sends, so this only
// exists to honour unsubs from already-sent mail.
function tryLegacyToken(token: string): string | null {
  try {
    const email = atob(token).trim().toLowerCase();
    if (email && email.includes('@')) return email;
    return null;
  } catch {
    return null;
  }
}

// ─── Suppression write ─────────────────────────────────────────────
async function suppressEmail(
  supabase: ReturnType<typeof createClient>,
  email: string,
  meta: { campaign_id?: string | null; method: string; user_agent?: string | null; ip?: string | null }
) {
  // 1. email_suppressions — the cross-system source of truth.
  await supabase.from('email_suppressions').upsert(
    {
      email,
      reason: 'user_unsubscribed_one_click',
      source: 'outreach_unsubscribe',
      metadata: {
        campaign_id: meta.campaign_id ?? null,
        method: meta.method,
        user_agent: meta.user_agent ?? null,
        ip: meta.ip ?? null,
      },
    },
    { onConflict: 'email', ignoreDuplicates: false }
  );

  // 2. outreach_contacts mirror — so the admin UI and prepare_send filter
  //    both see suppression immediately without an extra join.
  await supabase
    .from('outreach_contacts')
    .update({
      is_suppressed: true,
      suppression_reason: 'unsubscribed',
      suppressed_at: new Date().toISOString(),
    })
    .ilike('email', email);

  // 3. Analytics audit trail.
  try {
    await supabase.from('email_tracking_events').insert({
      user_email: email,
      event_type: 'unsubscribe',
      raw_payload: {
        campaign_id: meta.campaign_id ?? null,
        source: 'outreach_unsubscribe',
        method: meta.method,
      },
    });
  } catch (err) {
    console.error('tracking event insert failed:', err instanceof Error ? err.message : err);
  }
}

// ─── Handler ───────────────────────────────────────────────────────
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const token = url.searchParams.get('token') ?? '';
    const campaignId = url.searchParams.get('campaign');
    const userAgent = req.headers.get('user-agent');
    const forwardedFor = req.headers.get('x-forwarded-for');
    const ip = forwardedFor ? forwardedFor.split(',')[0].trim() : null;

    if (!token) {
      return htmlResponse(errorPage('Missing unsubscribe token.'), 400);
    }

    // Verify token (HMAC or legacy).
    const email = (await verifyToken(token)) || tryLegacyToken(token);
    if (!email) {
      return htmlResponse(errorPage('Invalid or expired unsubscribe link.'), 400);
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { autoRefreshToken: false, persistSession: false } }
    );

    // ─── POST = actually unsubscribe ─────────────────────────────
    if (req.method === 'POST') {
      // RFC 8058 one-click clients POST with no body or with
      // "List-Unsubscribe=One-Click" form data. Either way, suppress.
      let method = 'confirmation_form';
      try {
        const body = await req.text();
        if (body.includes('List-Unsubscribe=One-Click')) method = 'rfc8058_one_click';
      } catch {
        method = 'rfc8058_one_click';
      }

      await suppressEmail(supabase, email, {
        campaign_id: campaignId,
        method,
        user_agent: userAgent,
        ip,
      });

      console.log(`[unsub] suppressed ${email} via ${method}${campaignId ? ` (campaign ${campaignId})` : ''}`);

      return htmlResponse(successPage(email), 200);
    }

    // ─── GET = show confirmation page (no suppression yet) ───────
    // Safe against Gmail/Outlook link pre-fetchers.
    return htmlResponse(confirmPage(email, token, campaignId), 200);
  } catch (err) {
    console.error('[unsub] error:', err instanceof Error ? err.message : err);
    return htmlResponse(errorPage('Something went wrong. Please try again.'), 500);
  }
});

// ─── Pages ─────────────────────────────────────────────────────────
function htmlResponse(html: string, status: number) {
  return new Response(html, {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'text/html; charset=utf-8' },
  });
}

function shell(body: string) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Elec-Mate &mdash; Email preferences</title>
  <style>
    html,body{margin:0;padding:0;min-height:100vh;background:#000;color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}
    body{display:flex;align-items:center;justify-content:center;padding:24px}
    .card{max-width:520px;width:100%;background:#0a0a0a;border:1px solid rgba(255,255,255,0.08);border-radius:20px;padding:44px 36px;text-align:center}
    .logo{width:72px;height:72px;border-radius:16px;margin:0 auto 22px;display:block}
    h1{margin:0 0 14px;font-size:22px;font-weight:700;letter-spacing:-0.3px;color:#ffffff}
    p{margin:0 0 18px;font-size:15px;line-height:1.6;color:#d4d4d8}
    strong{color:#ffffff}
    .btn{display:inline-block;padding:16px 36px;border:none;border-radius:12px;font-size:15px;font-weight:700;cursor:pointer;font-family:inherit}
    .btn-primary{background:linear-gradient(135deg,#fbbf24,#f59e0b);color:#000}
    .btn-ghost{background:transparent;color:#a1a1aa;padding:12px 20px;font-size:13px;text-decoration:none}
    .meta{margin-top:20px;font-size:12px;color:#71717a}
    .status-ok{background:#15803d}
    .status-err{background:#991b1b}
    .status-dot{width:56px;height:56px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 18px;font-size:26px;color:#fff;font-weight:700}
  </style>
</head>
<body>
  <div class="card">
    <img src="https://www.elec-mate.com/images/elec-mate-logo-512.png" alt="Elec-Mate" class="logo" />
    ${body}
    <p class="meta">&copy; ${new Date().getFullYear()} Elec-Mate Ltd &middot; United Kingdom</p>
  </div>
</body>
</html>`;
}

function confirmPage(email: string, token: string, campaignId: string | null) {
  // Escape for attribute
  const safeToken = token.replace(/"/g, '&quot;');
  const safeCampaign = (campaignId || '').replace(/"/g, '&quot;');
  const action = `?token=${encodeURIComponent(token)}${campaignId ? `&campaign=${encodeURIComponent(campaignId)}` : ''}`;
  return shell(`
    <h1>Unsubscribe from Elec-Mate?</h1>
    <p>We&apos;ll stop sending outreach emails to <strong>${escapeHtml(email)}</strong>. You can re-subscribe any time by replying to one of our emails.</p>
    <form method="POST" action="${action}" style="margin:0">
      <input type="hidden" name="token" value="${safeToken}" />
      <input type="hidden" name="campaign" value="${safeCampaign}" />
      <button type="submit" class="btn btn-primary">Yes, unsubscribe me</button>
    </form>
    <p style="margin-top:22px"><a href="https://elec-mate.com" class="btn-ghost">No &mdash; take me to elec-mate.com</a></p>
  `);
}

function successPage(email: string) {
  return shell(`
    <div class="status-dot status-ok">&#10003;</div>
    <h1>You&apos;re unsubscribed.</h1>
    <p><strong>${escapeHtml(email)}</strong> will no longer receive outreach emails from Elec-Mate.</p>
    <p style="font-size:13px;color:#71717a">Changed your mind? Reply to any previous email and we&apos;ll re-add you.</p>
    <p><a href="https://elec-mate.com" class="btn-ghost">Visit elec-mate.com</a></p>
  `);
}

function errorPage(message: string) {
  return shell(`
    <div class="status-dot status-err">!</div>
    <h1>${escapeHtml(message)}</h1>
    <p>If this keeps happening, email <a href="mailto:founder@elec-mate.com" style="color:#fbbf24">founder@elec-mate.com</a> and we&apos;ll sort it manually.</p>
  `);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
