import type { Section } from '@/pages/employer/EmployerDashboard';
import { useEmployerHubCounts } from '@/hooks/useFinanceModel';
import {
  HubLanding,
  SectionHeader,
  HubGrid,
  HubCard,
  Pill,
  ListCard,
  ListBody,
  ListRow,
  EmptyState,
} from '@/components/employer/editorial';
import { PageHelpButton, HowItWorks } from '@/components/hub/PageHelp';
import { SMART_DOCS_HELP } from '@/components/employer/help/clients';

interface SmartDocsHubProps {
  onNavigate: (section: Section) => void;
}

const KIND: Record<string, { label: string; section: Section }> = {
  rams: { label: 'RAMS', section: 'airams' },
  method_statement: { label: 'Method statement', section: 'aimethodstatement' },
  design: { label: 'Installation design', section: 'aidesignspec' },
  briefing_pack: { label: 'Briefing pack', section: 'aibriefingpack' },
};

const generated = (n: number | undefined) =>
  n === undefined ? undefined : n === 0 ? 'None generated yet' : `${n} generated`;

export function SmartDocsHub({ onNavigate }: SmartDocsHubProps) {
  // Counts and the recent list cover documents generated by the firm's owner
  // and managers (one firm-scoped call).
  const { data: hub, isLoading } = useEmployerHubCounts();
  const docs = hub?.docs;

  return (
    <HubLanding
      eyebrow="Documents"
      title="Smart Docs"
      description="Generate RAMS, method statements, design specs and briefing packs in minutes, and build quotes."
      tone="purple"
      actions={<PageHelpButton help={SMART_DOCS_HELP} askContext={{ page: 'smartdocs' }} />}
      stats={
        docs
          ? [
              { label: 'RAMS', value: docs.rams, tone: 'orange', onClick: () => onNavigate('airams') },
              {
                label: 'Method statements',
                value: docs.method_statements,
                tone: 'emerald',
                onClick: () => onNavigate('aimethodstatement'),
              },
              { label: 'Designs', value: docs.designs, tone: 'indigo', onClick: () => onNavigate('aidesignspec') },
              {
                label: 'Briefing packs',
                value: docs.briefing_packs,
                tone: 'amber',
                accent: true,
                onClick: () => onNavigate('aibriefingpack'),
              },
            ]
          : undefined
      }
    >
      <HowItWorks help={SMART_DOCS_HELP} askContext={{ page: 'smartdocs' }} />

      <section className="space-y-4">
        <SectionHeader eyebrow="Latest" title="Recent documents" />
        {isLoading ? null : (docs?.recent ?? []).length === 0 ? (
          <EmptyState
            title="Nothing generated yet"
            description="Your last five generated documents will appear here."
          />
        ) : (
          <ListCard>
            <ListBody>
              {(docs?.recent ?? []).map((d, i) => {
                const k = KIND[d.kind] ?? KIND.rams;
                return (
                  <ListRow
                    key={`${d.kind}-${d.at}-${i}`}
                    title={d.title}
                    subtitle={`${k.label} · ${new Date(d.at).toLocaleDateString('en-GB', {
                      day: 'numeric',
                      month: 'short',
                      year: 'numeric',
                    })}`}
                    onClick={() => onNavigate(k.section)}
                  />
                );
              })}
            </ListBody>
          </ListCard>
        )}
      </section>

      <section className="space-y-5">
        <SectionHeader eyebrow="AI drafts, you approve" title="Documents in minutes" />
        <HubGrid columns={2}>
          <div data-help="smartdocs.design" className="contents">
          <HubCard
            number="01"
            eyebrow="Design"
            title="AI Design Spec"
            description="Circuit design documents drafted from your job brief."
            tone="indigo"
            badge={<Pill tone="purple">AI</Pill>}
            meta={generated(docs?.designs)}
            onClick={() => onNavigate('aidesignspec')}
            cta="Generate"
          />
          </div>
          <HubCard
            number="02"
            eyebrow="Procedure"
            title="AI Method Statement"
            description="Step-by-step work procedures aligned to BS 7671 practice."
            tone="emerald"
            badge={<Pill tone="purple">AI</Pill>}
            meta={generated(docs?.method_statements)}
            onClick={() => onNavigate('aimethodstatement')}
            cta="Generate"
          />
          <HubCard
            number="03"
            eyebrow="Safety"
            title="AI RAMS"
            description="Risk assessments and method statements ready for site."
            tone="orange"
            badge={<Pill tone="purple">AI</Pill>}
            meta={generated(docs?.rams)}
            onClick={() => onNavigate('airams')}
            cta="Generate"
          />
          <HubCard
            number="04"
            eyebrow="Briefing"
            title="AI Briefing Pack"
            description="Pre-job briefing packs to share with the crew before mobilisation."
            tone="amber"
            badge={<Pill tone="purple">AI</Pill>}
            meta={generated(docs?.briefing_packs)}
            onClick={() => onNavigate('aibriefingpack')}
            cta="Generate"
          />
        </HubGrid>
      </section>

      <section className="space-y-5">
        <SectionHeader eyebrow="Drafted for you" title="Quotes" />
        <HubGrid columns={2}>
          <div data-help="smartdocs.quote" className="contents">
          <HubCard
            number="05"
            eyebrow="Commercial"
            title="AI quote"
            description="Pick a job and get a draft quote priced from your own price book and your own past jobs. You check it, then send it."
            tone="yellow"
            onClick={() => onNavigate('aiquote')}
            cta="Draft"
          />
          </div>
        </HubGrid>
      </section>
    </HubLanding>
  );
}
