import { ArrowLeft, Zap, CheckCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import SingleQuestionQuiz from "@/components/upskilling/quiz/SingleQuestionQuiz";
import useSEO from "@/hooks/useSEO";

const quickCheckQuestions = [
  {
    id: "grouping-effect",
    question: "What is the impact of grouping cables on current-carrying capacity?",
    options: ["No impact", "Increases capacity", "Reduces capacity due to heat buildup", "Only affects voltage drop"],
    correctIndex: 2,
    explanation: "Grouping cables reduces current-carrying capacity because heat generated by one cable affects others nearby, requiring derating factors to maintain safe operating temperatures."
  },
  {
    id: "cable-sizing-factors",
    question: "Name two key factors that influence cable sizing.",
    options: ["Cable colour and manufacturer", "Load current and voltage drop", "Installation height and length", "Ambient lighting and ventilation"],
    correctIndex: 1,
    explanation: "Load current and voltage drop are fundamental factors in cable sizing - the cable must carry the load safely while maintaining voltage within acceptable limits."
  },
  {
    id: "fire-resistant-cable",
    question: "Which cable is best for fire-resistance and critical systems?",
    options: ["PVC insulated cable", "XLPE cable", "Mineral insulated (MI) cable", "Rubber insulated cable"],
    correctIndex: 2,
    explanation: "Mineral insulated (MI) cable offers the highest fire resistance, maintaining circuit integrity even in fire conditions, making it ideal for critical safety systems."
  }
];

const faqs = [
  {
    question: "What are the voltage drop limits in BS 7671?",
    answer: "From the local distribution board: 3% for lighting circuits, 5% for other circuits. Total from origin: 6% for lighting, 10% for other circuits."
  },
  {
    question: "When should LSZH cables be used?",
    answer: "LSZH (Low Smoke Zero Halogen) cables should be used in escape routes, enclosed spaces, and areas where smoke and toxic gas emission could endanger occupants during a fire."
  },
  {
    question: "How do derating factors combine?",
    answer: "Derating factors are cumulative - multiply them together. Example: thermal insulation (0.5) × grouping (0.6) = 0.3 combined factor."
  },
  {
    question: "What's the purpose of SWA cable armour?",
    answer: "Steel Wire Armour provides mechanical protection against impact, crushing, and penetration. It also provides an earth path when correctly terminated, suitable for underground and industrial installations."
  }
];

const quizQuestion = {
  question: "What happens if voltage drop exceeds recommended limits?",
  options: [
    "Equipment operates more efficiently",
    "Poor equipment performance, reduced lifespan, and potential safety issues",
    "Improved power factor",
    "Reduced energy consumption"
  ],
  correctAnswer: 1,
  explanation: "Excessive voltage drop causes poor equipment performance, reduced efficiency, shortened equipment lifespan, and can create safety issues with inadequate operation of protective devices."
};

const BS7671Module5Section2 = () => {
  useSEO({
    title: "Cable Types, Sizing, Grouping and Routing | BS7671 Module 5.2",
    description: "Learn about cable selection, sizing calculations, grouping derating factors, and routing considerations for BS 7671 compliant installations."
  });

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#1a1a1a]">
      {/* Minimal Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/electrician/upskilling/bs7671-module-5">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      <article className="px-4 sm:px-6 py-8 sm:py-12">
        {/* Page Title */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Zap className="h-4 w-4" />
            <span>Module 5.2</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            Cable Types, Sizing, Grouping and Routing
          </h1>
          <p className="text-white/80">
            The Lifelines of Electrical Installations
          </p>
        </header>

        {/* Quick Summary */}
        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2">In 30 Seconds</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>Size for:</strong> Current capacity + voltage drop + fault rating</li>
              <li><strong>Grouping:</strong> Reduces capacity (heat buildup)</li>
              <li><strong>V-drop:</strong> 3% lighting, 5% other circuits</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2">Spot it / Use it</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>Spot:</strong> Cable markings show type, size, rating</li>
              <li><strong>Use:</strong> Match cable type to application</li>
            </ul>
          </div>
        </div>

        {/* Learning Outcomes */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You'll Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              "Understand different cable types and insulation materials",
              "Calculate cable sizes using current capacity and voltage drop",
              "Apply derating factors for grouping and environment",
              "Learn routing considerations and installation methods"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        <hr className="border-white/5 mb-12" />

        {/* Section 1: Cable Types */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            Cable Types and Insulation
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Different cable types are designed for specific applications, environments, and performance requirements. Selection depends on installation method, environmental conditions, and safety requirements.
            </p>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Common Types</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>PVC (6242Y):</strong> General domestic use, 70°C rated</li>
                  <li><strong>LSZH:</strong> Low smoke, escape routes</li>
                  <li><strong>SWA:</strong> Armoured, underground/industrial</li>
                  <li><strong>MI (MICC):</strong> Fire-resistant, safety systems</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Selection Guide</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>Domestic:</strong> PVC flat, SWA for outdoor</li>
                  <li><strong>Commercial:</strong> LSZH for escape routes</li>
                  <li><strong>Industrial:</strong> SWA, higher temp ratings</li>
                  <li><strong>Safety Systems:</strong> MI for fire resistance</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 2: Cable Sizing */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            Cable Sizing Principles
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Cable sizing must satisfy multiple criteria simultaneously: current-carrying capacity, voltage drop limitations, and fault current capacity to ensure safe and efficient operation.
            </p>

            <div className="grid sm:grid-cols-3 gap-4 my-6">
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Current Capacity</p>
                <ul className="text-xs space-y-1">
                  <li>Design current (Ib)</li>
                  <li>Apply correction factors</li>
                  <li>Cable rating (Iz) ≥ In</li>
                  <li>Temperature derating</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Voltage Drop</p>
                <ul className="text-xs space-y-1">
                  <li>Lighting: 3% max</li>
                  <li>Other uses: 5% max</li>
                  <li>Formula: mV/A/m × Ib × L</li>
                  <li>Check at design load</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-white/5">
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Fault Rating</p>
                <ul className="text-xs space-y-1">
                  <li>Withstand fault current</li>
                  <li>k²S² ≥ I²t</li>
                  <li>CPC adequacy</li>
                  <li>Adiabatic equation</li>
                </ul>
              </div>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Sizing Process:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Step 1:</strong> Calculate design current, apply diversity</li>
                <li><strong>Step 2:</strong> Determine installation method and correction factors</li>
                <li><strong>Step 3:</strong> Select cable, verify capacity ≥ design current</li>
                <li><strong>Step 4:</strong> Check voltage drop against limits</li>
                <li><strong>Step 5:</strong> Verify fault current capability</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 3: Grouping and Derating */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Grouping and Derating Factors
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              When cables are grouped together or installed in thermally challenging environments, their current-carrying capacity must be reduced to prevent overheating.
            </p>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Grouping Factors (BS 7671)</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>2 cables:</strong> factor 0.80</li>
                  <li><strong>3 cables:</strong> factor 0.70</li>
                  <li><strong>4-5 cables:</strong> factor 0.65</li>
                  <li><strong>6-8 cables:</strong> factor 0.60</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Other Derating</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>Thermal insulation:</strong> factor 0.5</li>
                  <li><strong>High ambient:</strong> temperature factors apply</li>
                  <li><strong>Combined:</strong> multiply factors together</li>
                </ul>
              </div>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-red-400/80 mb-2">Practical Strategies:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Use separate routes where possible</li>
                <li>Use ventilated cable trays for heat dissipation</li>
                <li>Consider load diversity in grouped circuits</li>
                <li>Use larger cables to reduce heat generation</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Section 4: Installation and Routing */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Installation Methods and Routing
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Proper cable routing ensures mechanical protection, accessibility for maintenance, electromagnetic compatibility, and compliance with safety requirements.
            </p>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Installation Methods</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>Surface:</strong> Clipped direct, good heat dissipation</li>
                  <li><strong>Concealed:</strong> In walls/floors, requires safe zones or RCD</li>
                  <li><strong>Containment:</strong> Trays, conduit, trunking systems</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Routing Considerations</p>
                <ul className="text-sm text-white space-y-1">
                  <li><strong>Protection:</strong> Impact, abrasion, crush</li>
                  <li><strong>EMC:</strong> Separate power/data cables</li>
                  <li><strong>Access:</strong> Maintenance and future additions</li>
                  <li><strong>Fire:</strong> Segregation and fire stopping</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Section 5: Real World Scenario */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">05</span>
            Real World Scenario
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <div className="p-4 rounded-lg bg-white/5 border border-white/10">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Commercial Office Rewiring</p>
              <p className="text-sm mb-3">
                Routing 8 circuits through 200mm thermal insulation over 50m in a ceiling void.
              </p>
              <p className="text-sm mb-2">
                <strong>Challenge:</strong> Combined derating for thermal insulation (0.5) and grouping 8 cables (0.6).
              </p>
              <p className="text-sm mb-2">
                <strong>Calculation:</strong> Combined factor = 0.5 × 0.6 = 0.3. Cables need significant upsizing.
              </p>
              <p className="text-sm">
                <strong>Solution:</strong> Increase lighting circuits from 2.5mm² to 4mm², socket circuits from 4mm² to 6mm². Use LSZH cables for escape route compliance.
              </p>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <h3 className="text-sm font-medium text-white mb-1">{faq.question}</h3>
                <p className="text-sm text-white/90 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Quick Reference */}
        <div className="mt-6 p-5 rounded-lg bg-transparent">
          <h3 className="text-sm font-medium text-white mb-4">Quick Reference</h3>
          <div className="grid sm:grid-cols-2 gap-4 text-xs text-white">
            <div>
              <p className="font-medium text-white mb-1">Voltage Drop Limits</p>
              <ul className="space-y-0.5">
                <li>Lighting: 3% from DB</li>
                <li>Other: 5% from DB</li>
                <li>Total from origin: 6%/10%</li>
              </ul>
            </div>
            <div>
              <p className="font-medium text-white mb-1">Cable Types</p>
              <ul className="space-y-0.5">
                <li>PVC: General domestic</li>
                <li>LSZH: Escape routes</li>
                <li>SWA: Underground/industrial</li>
                <li>MI: Fire-resistant</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Quiz */}
        <section className="mb-10">
          <SingleQuestionQuiz
            question={quizQuestion.question}
            options={quizQuestion.options}
            correctAnswer={quizQuestion.correctAnswer}
            explanation={quizQuestion.explanation}
          />
        </section>

        {/* Navigation */}
        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/study-centre/upskilling/bs7671-module-5-section-1">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Previous Section
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/study-centre/upskilling/bs7671-module-5-section-3">
              Next Section
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>
      </article>
    </div>
  );
};

export default BS7671Module5Section2;
