import { ArrowLeft, ArrowRight, Cable, CheckCircle, AlertTriangle, Target, Lightbulb, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Link } from 'react-router-dom';
import BS7671EmbeddedQuiz from '@/components/upskilling/BS7671EmbeddedQuiz';

const BS7671Module5Section2 = () => {

  const quizQuestions = [
    {
      id: 1,
      question: "What is the impact of grouping cables on current-carrying capacity?",
      options: [
        "No impact on current capacity",
        "Increases current-carrying capacity",
        "Reduces current-carrying capacity due to increased heat buildup",
        "Only affects voltage drop calculations"
      ],
      correct: 2,
      explanation: "Grouping cables reduces current-carrying capacity because heat generated by one cable affects others nearby, requiring derating factors to maintain safe operating temperatures."
    },
    {
      id: 2,
      question: "Name two factors that influence cable sizing.",
      options: [
        "Cable colour and manufacturer",
        "Load current and voltage drop",
        "Installation height and cable length",
        "Ambient lighting and ventilation"
      ],
      correct: 1,
      explanation: "Load current and voltage drop are fundamental factors in cable sizing - the cable must carry the load safely while maintaining voltage within acceptable limits."
    },
    {
      id: 3,
      question: "Which cable is best for fire-resistance and critical systems?",
      options: [
        "PVC insulated cable",
        "XLPE cable",
        "Mineral insulated (MI) cable",
        "Rubber insulated cable"
      ],
      correct: 2,
      explanation: "Mineral insulated (MI) cable offers the highest fire resistance, maintaining circuit integrity even in fire conditions, making it ideal for critical safety systems."
    },
    {
      id: 4,
      question: "What does LSZH stand for and where is it used?",
      options: [
        "Low Smoke Zero Halogen - used in escape routes and enclosed spaces",
        "Low Strength Zero Heat - used in high temperature areas",
        "Light Single Zone Housing - used in residential applications",
        "Limited Size Zero Humidity - used in wet locations"
      ],
      correct: 0,
      explanation: "LSZH (Low Smoke Zero Halogen) cables produce minimal smoke and no toxic halogen gases when burning, essential for escape routes and enclosed spaces where people might be trapped."
    },
    {
      id: 5,
      question: "What happens if voltage drop exceeds recommended limits?",
      options: [
        "Equipment operates more efficiently",
        "Poor equipment performance, reduced lifespan, and potential safety issues",
        "Improved power factor",
        "Reduced energy consumption"
      ],
      correct: 1,
      explanation: "Excessive voltage drop causes poor equipment performance, reduced efficiency, shortened equipment lifespan, and can create safety issues with inadequate operation of protective devices."
    }
  ];

  return (
    <div className="space-y-4 sm:space-y-6 animate-fade-in">
      <div>
        <Link to="../bs7671-module-5">
          <Button
            variant="ghost"
            className="text-foreground hover:bg-card hover:text-yellow-400 transition-all duration-200 mb-8 px-4 py-2 rounded-md"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Module 5
          </Button>
        </Link>
        
        <div className="space-y-4 sm:space-y-6">
          {/* Header */}
          <div>
            <div className="flex items-center gap-4 mb-4">
              <Cable className="h-8 w-8 text-yellow-400" />
              <div>
                <h1 className="text-xl sm:text-2xl font-bold text-white">
                  Cable Types, Sizing, Grouping, and Routing
                </h1>
                <p className="text-white">
                  The lifelines of electrical installations
                </p>
              </div>
            </div>
            <div className="flex gap-4">
              <Badge variant="secondary" className="bg-yellow-400 text-black">
                Module 5.2
              </Badge>
              <Badge variant="outline" className="border-gray-600 text-white">
                30 minutes
              </Badge>
            </div>
          </div>

          {/* Introduction */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Target className="h-6 w-6 text-yellow-400" />
                Introduction
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-4">
              <p className="text-base leading-relaxed">
                Cables are the lifelines of an electrical installation. Choosing the right type, size, and installation method is key to safety, performance, and compliance with BS 7671 requirements.
              </p>
              <p className="text-base leading-relaxed">
                This section covers the essential principles of cable selection, from understanding different cable types to calculating appropriate sizes and implementing proper routing strategies.
              </p>
            </CardContent>
          </Card>

          {/* Learning Goals */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Target className="h-6 w-6 text-yellow-400" />
                Learning Goals
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">Understand different cable types and insulation materials</span>
                </div>
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">Calculate appropriate cable sizes using current-carrying capacity and voltage drop</span>
                </div>
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">Learn grouping and routing considerations</span>
                </div>
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">Apply derating factors based on environment and layout</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Cable Types */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Cable className="h-6 w-6 text-yellow-400" />
                Cable Types and Insulation Materials
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-6">
              <div className="bg-yellow-400/10 p-4 rounded-lg border border-blue-600/30">
                <h4 className="text-white font-semibold mb-3">Understanding Cable Construction</h4>
                <p className="text-sm">
                  Different cable types are designed for specific applications, environments, and performance requirements. Selection depends on installation method, environmental conditions, and safety requirements.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Common Cable Types</h4>
                  <div className="space-y-3">
                    <div className="bg-red-600/20 p-3 rounded border border-red-600/40">
                      <p className="text-red-400 font-semibold text-sm mb-2">PVC Insulated:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Most common for general applications</li>
                        <li>• Good electrical properties and flexibility</li>
                        <li>• Temperature rating typically 70°C</li>
                        <li>• Cost-effective for standard installations</li>
                        <li>• Examples: 6242Y flat cable, 6491X single core</li>
                      </ul>
                    </div>
                    <div className="bg-orange-600/20 p-3 rounded border border-orange-600/40">
                      <p className="text-orange-400 font-semibold text-sm mb-2">LSZH (Low Smoke Zero Halogen):</p>
                      <ul className="text-xs space-y-1">
                        <li>• Reduced smoke and toxic gas emission</li>
                        <li>• Essential for escape routes and enclosed spaces</li>
                        <li>• Higher cost but improved safety</li>
                        <li>• Required in certain building types</li>
                        <li>• Examples: LSZH multicore cables</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Specialised Cable Types</h4>
                  <div className="space-y-3">
                    <div className="bg-green-600/20 p-3 rounded border border-green-600/40">
                      <p className="text-green-400 font-semibold text-sm mb-2">SWA (Steel Wire Armoured):</p>
                      <ul className="text-xs space-y-1">
                        <li>• Mechanical protection from steel wire armouring</li>
                        <li>• Suitable for underground and industrial use</li>
                        <li>• Armour provides earth path when correctly terminated</li>
                        <li>• Higher current capacity due to size</li>
                        <li>• Examples: 6944X SWA cables</li>
                      </ul>
                    </div>
                    <div className="bg-yellow-400/20 p-3 rounded border border-blue-600/40">
                      <p className="text-yellow-400 font-semibold text-sm mb-2">Mineral Insulated (MI):</p>
                      <ul className="text-xs space-y-1">
                        <li>• Copper conductors in magnesium oxide insulation</li>
                        <li>• Fire resistant - maintains circuit integrity</li>
                        <li>• Suitable for critical safety systems</li>
                        <li>• High temperature rating (up to 250°C)</li>
                        <li>• Examples: MICC pyro cables</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-card p-4 rounded-lg">
                <h4 className="text-yellow-400 font-semibold mb-3">Cable Selection Matrix</h4>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Domestic Applications:</p>
                    <ul className="text-xs space-y-1">
                      <li>• PVC flat cables for fixed wiring</li>
                      <li>• Single core PVC for conduit/trunking</li>
                      <li>• LSZH where fire risk is concern</li>
                      <li>• SWA for outdoor/underground runs</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Commercial Buildings:</p>
                    <ul className="text-xs space-y-1">
                      <li>• LSZH for escape routes</li>
                      <li>• PVC for general applications</li>
                      <li>• Fire-resistant for safety systems</li>
                      <li>• Data cables with appropriate screening</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Industrial Environments:</p>
                    <ul className="text-xs space-y-1">
                      <li>• SWA for mechanical protection</li>
                      <li>• Higher temperature rated cables</li>
                      <li>• Chemical resistant outer sheaths</li>
                      <li>• Flexible cables for moving applications</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Safety Critical Systems:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Mineral insulated for fire resistance</li>
                      <li>• Enhanced fire performance cables</li>
                      <li>• Circuit integrity systems</li>
                      <li>• Segregated routing requirements</li>
                    </ul>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Cable Sizing Principles */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Zap className="h-6 w-6 text-yellow-400" />
                Cable Sizing Principles
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-6">
              <div className="bg-yellow-600/10 p-4 rounded-lg border border-yellow-600/30">
                <h4 className="text-white font-semibold mb-3">Fundamental Sizing Criteria</h4>
                <p className="text-sm">
                  Cable sizing must satisfy multiple criteria simultaneously: current-carrying capacity, voltage drop limitations, and fault current capacity to ensure safe and efficient operation.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-yellow-400 font-semibold text-lg mb-3">Current-Carrying Capacity</h4>
                  <div className="space-y-3">
                    <div className="bg-red-600/20 p-3 rounded border border-red-600/40">
                      <p className="text-red-400 font-semibold text-sm mb-2">Design Current (Ib):</p>
                      <ul className="text-xs space-y-1">
                        <li>• Maximum expected load current</li>
                        <li>• Include diversity factors</li>
                        <li>• Consider future load growth</li>
                        <li>• Account for harmonic effects</li>
                      </ul>
                    </div>
                    <div className="bg-orange-600/20 p-3 rounded border border-orange-600/40">
                      <p className="text-orange-400 font-semibold text-sm mb-2">Cable Rating (Iz):</p>
                      <ul className="text-xs space-y-1">
                        <li>• Tabulated current-carrying capacity</li>
                        <li>• Apply correction factors</li>
                        <li>• Must be ≥ protective device rating</li>
                        <li>• Consider temperature rise effects</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-green-400 font-semibold text-lg mb-3">Voltage Drop</h4>
                  <div className="space-y-3">
                    <div className="bg-green-600/20 p-3 rounded border border-green-600/40">
                      <p className="text-green-400 font-semibold text-sm mb-2">BS 7671 Limits:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Lighting: 3% of nominal voltage</li>
                        <li>• Other uses: 5% of nominal voltage</li>
                        <li>• Total from origin: lighting 6%, other 10%</li>
                        <li>• Consider starting currents for motors</li>
                      </ul>
                    </div>
                    <div className="bg-yellow-400/20 p-3 rounded border border-blue-600/40">
                      <p className="text-yellow-400 font-semibold text-sm mb-2">Calculation Method:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Voltage drop = (mV/A/m) × Ib × L</li>
                        <li>• Use tabulated values for cable type</li>
                        <li>• Consider power factor for AC</li>
                        <li>• Check at design and maximum load</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-purple-400 font-semibold text-lg mb-3">Fault Current Capacity</h4>
                  <div className="space-y-3">
                    <div className="bg-purple-600/20 p-3 rounded border border-purple-600/40">
                      <p className="text-purple-400 font-semibold text-sm mb-2">Short Circuit Rating:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Withstand prospective fault current</li>
                        <li>• Time limited by protective device</li>
                        <li>• k²S² ≥ I²t for fault duration</li>
                        <li>• Adiabatic heating assumptions</li>
                      </ul>
                    </div>
                    <div className="bg-indigo-600/20 p-3 rounded border border-indigo-600/40">
                      <p className="text-indigo-400 font-semibold text-sm mb-2">Earth Fault Rating:</p>
                      <ul className="text-xs space-y-1">
                        <li>• CPC must withstand earth fault current</li>
                        <li>• Often determines minimum CPC size</li>
                        <li>• Consider touch voltage limitations</li>
                        <li>• Verify with Zs calculations</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-yellow-400/10 p-4 rounded-lg border border-blue-600/30">
                <h4 className="text-yellow-400 font-semibold mb-3">Cable Sizing Process</h4>
                <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Step 1 - Load Analysis:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Calculate design current</li>
                      <li>• Apply diversity factors</li>
                      <li>• Consider load characteristics</li>
                      <li>• Plan for future expansion</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Step 2 - Installation Method:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Select installation method</li>
                      <li>• Determine correction factors</li>
                      <li>• Assess thermal environment</li>
                      <li>• Consider cable grouping</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Step 3 - Current Capacity:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Select initial cable size</li>
                      <li>• Apply derating factors</li>
                      <li>• Verify capacity ≥ design current</li>
                      <li>• Check protective device coordination</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Step 4 - Voltage Drop:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Calculate voltage drop</li>
                      <li>• Check against BS 7671 limits</li>
                      <li>• Increase size if necessary</li>
                      <li>• Consider cable route length</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Step 5 - Fault Rating:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Calculate prospective fault current</li>
                      <li>• Verify cable fault rating</li>
                      <li>• Check CPC adequacy</li>
                      <li>• Confirm final selection</li>
                    </ul>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Cable Grouping and Derating */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Cable className="h-6 w-6 text-red-500" />
                Cable Grouping and Derating Factors
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-6">
              <div className="bg-red-600/10 p-4 rounded-lg border border-red-600/30">
                <h4 className="text-white font-semibold mb-3">Understanding Thermal Effects</h4>
                <p className="text-sm">
                  When cables are grouped together or installed in thermally challenging environments, their current-carrying capacity must be reduced to prevent overheating and maintain safe operation.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Grouping Effects</h4>
                  <div className="space-y-3">
                    <div className="bg-red-600/20 p-3 rounded border border-red-600/40">
                      <p className="text-red-400 font-semibold text-sm mb-2">Heat Accumulation:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Multiple cables generate heat in confined space</li>
                        <li>• Reduced heat dissipation capability</li>
                        <li>• Temperature rise affects insulation life</li>
                        <li>• Risk of thermal runaway in extreme cases</li>
                      </ul>
                    </div>
                    <div className="bg-orange-600/20 p-3 rounded border border-orange-600/40">
                      <p className="text-orange-400 font-semibold text-sm mb-2">Grouping Factors (BS 7671):</p>
                      <ul className="text-xs space-y-1">
                        <li>• 2 cables: factor 0.80</li>
                        <li>• 3 cables: factor 0.70</li>
                        <li>• 4-5 cables: factor 0.65</li>
                        <li>• 6-8 cables: factor 0.60</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Environmental Derating</h4>
                  <div className="space-y-3">
                    <div className="bg-yellow-400/20 p-3 rounded border border-blue-600/40">
                      <p className="text-yellow-400 font-semibold text-sm mb-2">Ambient Temperature:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Standard rating at 30°C ambient</li>
                        <li>• Higher temperatures require derating</li>
                        <li>• Lower temperatures allow uprating</li>
                        <li>• Consider seasonal temperature variations</li>
                      </ul>
                    </div>
                    <div className="bg-green-600/20 p-3 rounded border border-green-600/40">
                      <p className="text-green-400 font-semibold text-sm mb-2">Thermal Insulation:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Cables in thermal insulation: factor 0.5</li>
                        <li>• Partial contact requires assessment</li>
                        <li>• Insulation thickness affects derating</li>
                        <li>• Alternative routing may be beneficial</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-yellow-600/10 p-4 rounded-lg border border-yellow-600/30">
                <h4 className="text-yellow-400 font-semibold mb-3">Practical Grouping Strategies</h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Minimise Grouping:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Use separate routes where possible</li>
                      <li>• Spread cables across multiple containment</li>
                      <li>• Consider trefoil formation for three-phase</li>
                      <li>• Use larger containment systems</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Improve Heat Dissipation:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Ventilated cable trays</li>
                      <li>• Perforated containment systems</li>
                      <li>• Adequate spacing between groups</li>
                      <li>• Forced air cooling where justified</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Load Management:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Consider load diversity</li>
                      <li>• Separate high and low load circuits</li>
                      <li>• Use larger cables to reduce heat generation</li>
                      <li>• Monitor cable temperatures</li>
                    </ul>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Installation Methods and Routing */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Target className="h-6 w-6 text-green-500" />
                Installation Methods and Routing
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-6">
              <div className="bg-green-600/10 p-4 rounded-lg border border-green-600/30">
                <h4 className="text-white font-semibold mb-3">Strategic Cable Routing</h4>
                <p className="text-sm">
                  Proper cable routing ensures mechanical protection, accessibility for maintenance, electromagnetic compatibility, and compliance with safety requirements.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Installation Methods</h4>
                  <div className="space-y-3">
                    <div className="bg-yellow-400/20 p-3 rounded border border-blue-600/40">
                      <p className="text-yellow-400 font-semibold text-sm mb-2">Surface Installation:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Clipped direct to structure</li>
                        <li>• Easy installation and maintenance</li>
                        <li>• Good heat dissipation</li>
                        <li>• Requires mechanical protection in some areas</li>
                      </ul>
                    </div>
                    <div className="bg-green-600/20 p-3 rounded border border-green-600/40">
                      <p className="text-green-400 font-semibold text-sm mb-2">Concealed Installation:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Buried in walls or floors</li>
                        <li>• Protection from mechanical damage</li>
                        <li>• Requires safe zones or RCD protection</li>
                        <li>• Difficult access for maintenance</li>
                      </ul>
                    </div>
                    <div className="bg-orange-600/20 p-3 rounded border border-orange-600/40">
                      <p className="text-orange-400 font-semibold text-sm mb-2">Containment Systems:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Cable trays and ladder systems</li>
                        <li>• Conduit and trunking systems</li>
                        <li>• Underground duct systems</li>
                        <li>• Overhead catenary systems</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-4 rounded-lg">
                  <h4 className="text-white font-semibold text-lg mb-3">Routing Considerations</h4>
                  <div className="space-y-3">
                    <div className="bg-red-600/20 p-3 rounded border border-red-600/40">
                      <p className="text-red-400 font-semibold text-sm mb-2">Mechanical Protection:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Protection from impact and abrasion</li>
                        <li>• Adequate support to prevent sagging</li>
                        <li>• Protection at entry/exit points</li>
                        <li>• Consider expansion and contraction</li>
                      </ul>
                    </div>
                    <div className="bg-purple-600/20 p-3 rounded border border-purple-600/40">
                      <p className="text-purple-400 font-semibold text-sm mb-2">EMC Considerations:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Separate power and data cables</li>
                        <li>• Minimise loop areas</li>
                        <li>• Use screened cables where required</li>
                        <li>• Proper earthing of containment</li>
                      </ul>
                    </div>
                    <div className="bg-yellow-600/20 p-3 rounded border border-yellow-600/40">
                      <p className="text-yellow-400 font-semibold text-sm mb-2">Accessibility:</p>
                      <ul className="text-xs space-y-1">
                        <li>• Access for inspection and testing</li>
                        <li>• Space for cable replacement</li>
                        <li>• Clear identification and labelling</li>
                        <li>• Safe access for maintenance personnel</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-card p-4 rounded-lg">
                <h4 className="text-yellow-400 font-semibold mb-3">Special Routing Requirements</h4>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Fire Safety:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Fire-resistant cable requirements</li>
                      <li>• Segregation of safety circuits</li>
                      <li>• Fire stopping at compartment boundaries</li>
                      <li>• Alternative routing for critical circuits</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Hazardous Areas:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Explosion-protected cable systems</li>
                      <li>• Intrinsically safe circuit separation</li>
                      <li>• Special sealing requirements</li>
                      <li>• Certified installation methods</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Outdoor Installation:</p>
                    <ul className="text-xs space-y-1">
                      <li>• UV-resistant cable sheathing</li>
                      <li>• Protection from wildlife</li>
                      <li>• Drainage considerations</li>
                      <li>• Thermal expansion accommodation</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm mb-2">Underground Systems:</p>
                    <ul className="text-xs space-y-1">
                      <li>• Suitable cable construction (SWA/XLPE)</li>
                      <li>• Warning tape and marker posts</li>
                      <li>• Sand bedding and protection</li>
                      <li>• Accurate route records</li>
                    </ul>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Real World Scenario */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <AlertTriangle className="h-6 w-6 text-orange-500" />
                Real World Scenario
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-4">
              <div className="bg-orange-600/10 p-4 rounded-lg border border-orange-600/30">
                <h4 className="text-white font-semibold mb-3">Commercial Office Rewiring Project</h4>
                <p className="text-sm mb-3">
                  You're rewiring a commercial office and need to route cables through thermal insulation in the ceiling void. Multiple circuits will share the same route, requiring careful consideration of derating factors and cable selection.
                </p>
                <div className="bg-card p-3 rounded">
                   <p className="text-xs text-white mb-2">
                     <strong>Challenge:</strong> 8 circuits (5×2.5mm² lighting, 3×4mm² socket circuits) routed through 200mm thermal insulation over 50m length.
                   </p>
                   <p className="text-xs text-white mb-2">
                     <strong>Solution:</strong> Apply 0.5 derating for thermal insulation and 0.6 for 8 cables grouped. Use LSZH cables for escape route compliance.
                   </p>
                   <p className="text-xs text-white mb-2">
                     <strong>Calculation:</strong> Combined derating factor 0.5 × 0.6 = 0.3. Increase cable sizes: lighting to 4mm², sockets to 6mm² to maintain capacity.
                   </p>
                   <p className="text-xs text-white">
                     <strong>Outcome:</strong> Compliant installation with adequate current capacity, acceptable voltage drop, and improved fire safety characteristics.
                   </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Summary */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <CheckCircle className="h-6 w-6 text-green-500" />
                Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="text-white space-y-4">
              <p className="text-base leading-relaxed">
                Cable selection and routing must consider current load, environment, physical routing, and safety requirements. BS 7671 provides specific guidance under multiple sections to ensure compliant installations.
              </p>
              <div className="bg-card p-4 rounded-lg">
                <h4 className="text-yellow-400 font-semibold mb-3">Key Points</h4>
                <ul className="space-y-2 text-sm">
                  <li>• Cable types must match application requirements: PVC for general use, LSZH for fire safety, SWA for protection, MI for critical systems</li>
                  <li>• Cable sizing requires consideration of current capacity, voltage drop, and fault current capability</li>
                  <li>• Grouping cables reduces current-carrying capacity due to thermal effects - apply derating factors</li>
                  <li>• Environmental conditions affect cable performance - temperature, insulation, and installation method matter</li>
                  <li>• Proper routing ensures mechanical protection, accessibility, EMC compliance, and safety</li>
                  <li>• Derating factors are cumulative - thermal insulation, grouping, and temperature effects combine</li>
                  <li>• Voltage drop limits: 3% for lighting, 5% for other circuits from local distribution board</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          {/* Quiz Section */}
          <Card className="bg-card border-transparent">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Lightbulb className="h-6 w-6 text-yellow-400" />
                Knowledge Check Quiz
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <p className="text-white">
                Test your understanding of cable types, sizing, and routing.
              </p>
              
              <BS7671EmbeddedQuiz 
                questions={quizQuestions}
                title="Cable Selection Quiz"
                description="Test your knowledge of cable types, sizing, grouping, and routing"
              />
            </CardContent>
          </Card>

          {/* Navigation */}
          <div className="flex justify-between">
            <Link to="../bs7671-module-5-section-1">
              <Button variant="outline" className="border-white text-white hover:bg-card">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Previous Section
              </Button>
            </Link>
            <Link to="../bs7671-module-5">
              <Button className="bg-yellow-400 text-black hover:bg-yellow-600">
                Back to Module 5
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BS7671Module5Section2;