import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Zap, CheckCircle, ChevronDown, ChevronUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Quiz } from '@/components/apprentice-courses/Quiz';
import { InlineCheck } from '@/components/apprentice-courses/InlineCheck';
import useSEO from '@/hooks/useSEO';

const TITLE = 'Incentives and Funding Opportunities - Energy Efficiency Module 6 Section 3';
const DESCRIPTION = 'Learn about UK government grants, ECO4 scheme, Enhanced Capital Allowances, green finance, and local authority funding for energy efficiency improvements.';

const quickCheckQuestions = [
  {
    id: 'ee-m6s3-qc1',
    question: 'Which households are eligible for ECO4 funding?',
    options: [
      'All UK households regardless of income',
      'Only households in fuel poverty or on qualifying benefits',
      'Only owner-occupied properties',
      'Only properties built after 2000'
    ],
    correctIndex: 1,
    explanation: 'ECO4 targets households in fuel poverty or receiving qualifying benefits such as Universal Credit, Pension Credit, or Child Tax Credits. The scheme aims to improve energy efficiency in the homes that need it most.'
  },
  {
    id: 'ee-m6s3-qc2',
    question: 'What is the key benefit of Enhanced Capital Allowances (ECAs)?',
    options: [
      'Free equipment from the government',
      'Reduced VAT on energy-efficient products',
      '100% first-year tax deduction on qualifying equipment',
      'Lower interest rates on business loans'
    ],
    correctIndex: 2,
    explanation: 'ECAs allow businesses to deduct 100% of the cost of qualifying energy-efficient equipment from taxable profits in the year of purchase, rather than spreading the deduction over several years through normal depreciation.'
  },
  {
    id: 'ee-m6s3-qc3',
    question: 'What type of organisation can access Salix Finance interest-free loans?',
    options: [
      'Any UK business',
      'Only large corporations',
      'Public sector organisations (NHS, schools, councils)',
      'Only renewable energy companies'
    ],
    correctIndex: 2,
    explanation: 'Salix Finance provides interest-free loans specifically to public sector organisations including NHS trusts, schools, universities, and local authorities for energy efficiency improvements.'
  }
];

const quizQuestions = [
  {
    id: 1,
    question: 'What percentage of equipment cost can be claimed under Enhanced Capital Allowances?',
    options: ['25%', '50%', '75%', '100%'],
    correctAnswer: 3,
    explanation: 'ECAs provide 100% first-year allowance, meaning the full cost can be deducted from taxable profits in the year of purchase.'
  },
  {
    id: 2,
    question: 'Which database lists products qualifying for Enhanced Capital Allowances?',
    options: ['OFGEM Register', 'Energy Technology List (ETL)', 'Carbon Trust Database', 'BEIS Product Register'],
    correctAnswer: 1,
    explanation: 'The Energy Technology List (ETL) is maintained by the government and lists all products and technologies qualifying for ECAs.'
  },
  {
    id: 3,
    question: 'What is the primary goal of the ECO4 scheme?',
    options: [
      'Reducing commercial energy bills',
      'Upgrading the national grid',
      'Improving energy efficiency in fuel-poor homes',
      'Installing smart meters nationwide'
    ],
    correctAnswer: 2,
    explanation: 'ECO4 (Energy Company Obligation) requires large energy suppliers to fund energy efficiency improvements in fuel-poor and vulnerable households.'
  },
  {
    id: 4,
    question: 'How long does Salix Finance typically allow for loan repayment?',
    options: ['1-2 years', '5-8 years', 'Up to 12 years', 'No repayment required'],
    correctAnswer: 1,
    explanation: 'Salix loans are typically repaid over 5-8 years using the energy cost savings generated by the improvements, making them cash-flow neutral.'
  },
  {
    id: 5,
    question: 'Which measure is typically NOT covered by ECO4 funding?',
    options: ['Loft insulation', 'Cavity wall insulation', 'Solar PV panels', 'First-time central heating'],
    correctAnswer: 2,
    explanation: 'ECO4 focuses on fabric improvements and heating system upgrades rather than electricity generation. Solar PV is not typically funded under ECO4.'
  },
  {
    id: 6,
    question: 'What must equipment have to qualify for Enhanced Capital Allowances?',
    options: [
      'UK manufacturing origin',
      'Listing on the Energy Technology List',
      'Minimum 10-year warranty',
      'EU energy label A++'
    ],
    correctAnswer: 1,
    explanation: 'Products must be listed on the Energy Technology List (ETL), which is regularly updated by DESNZ (Department for Energy Security and Net Zero).'
  },
  {
    id: 7,
    question: 'What is PACE financing?',
    options: [
      'A government grant scheme',
      'Property-assessed clean energy loans repaid through property tax',
      'An energy company rebate programme',
      'Power purchase agreement for solar'
    ],
    correctAnswer: 1,
    explanation: 'PACE (Property Assessed Clean Energy) allows property owners to finance energy improvements and repay through an assessment on the property, transferring obligation to future owners if sold.'
  },
  {
    id: 8,
    question: 'Which organisation administers the Green Homes Grant Local Authority Delivery scheme?',
    options: ['OFGEM', 'Local councils', 'Energy suppliers', 'Carbon Trust'],
    correctAnswer: 1,
    explanation: 'The Local Authority Delivery (LAD) scheme is administered by local councils who identify eligible properties and coordinate improvements in their areas.'
  },
  {
    id: 9,
    question: 'What does the Super-deduction (now Full Expensing) allow for qualifying plant and machinery?',
    options: [
      '25% immediate deduction',
      '50% immediate deduction',
      '100% immediate deduction',
      '130% immediate deduction'
    ],
    correctAnswer: 2,
    explanation: 'Full Expensing (replacing the 130% super-deduction from April 2023) allows 100% first-year deduction for qualifying plant and machinery investments.'
  },
  {
    id: 10,
    question: 'What should electricians advise clients about funding applications?',
    options: [
      'Apply for funding after completing works',
      'Combine multiple funding sources without declaration',
      'Pre-approve funding before commencing work',
      'Only apply for grants over £10,000'
    ],
    correctAnswer: 2,
    explanation: 'Most funding schemes require pre-approval before work begins. Starting work early can disqualify the project from funding. Always confirm funding approval first.'
  }
];

const faqs = [
  {
    question: 'Can my client combine multiple funding sources?',
    answer: 'Often yes, but it depends on the specific schemes. For example, a public sector client might combine Salix funding with ECAs on qualifying equipment. However, you cannot "double-dip" on the same costs - each scheme must fund different elements. Always check scheme rules carefully and declare other funding sources in applications.'
  },
  {
    question: 'How do I find ECO4 installers or become one?',
    answer: 'To become an ECO installer, you need TrustMark registration and appropriate PAS (Publicly Available Specification) certifications for the measures you want to install. Contact energy suppliers\' ECO teams directly or join installer networks like TrustMark and Retrofit Works. For clients, start with their energy supplier or use the Simple Energy Advice service.'
  },
  {
    question: 'What records should be kept for tax relief claims?',
    answer: 'Maintain invoices showing the product description and Energy Technology List (ETL) reference, proof that products were new (not second-hand), installation certificates, commissioning records, and evidence of the purchase date. Keep records for at least 6 years as HMRC may enquire.'
  },
  {
    question: 'Are there funding schemes for SMEs?',
    answer: 'Yes, several options exist including ECAs (tax relief), low-interest green loans from banks, Carbon Trust Green Business Fund (when open), local authority business grants, and some energy supplier programmes. The British Business Bank also promotes green finance initiatives. Check your local Growth Hub for area-specific schemes.'
  },
  {
    question: 'What happens if funding is reduced mid-project?',
    answer: 'This risk exists with some schemes that have limited budgets. Protect yourself by getting funding confirmation in writing before starting, having a contract clause explaining the contingency if funding falls through, ensuring the client understands their liability, and considering staged applications for large projects.'
  },
  {
    question: 'How can electricians help clients access funding?',
    answer: 'Electricians can add value by staying informed about current schemes, providing energy assessments to support applications, supplying product specifications meeting ETL requirements, writing supporting letters describing energy savings, connecting clients with specialist funding advisers, and ensuring installations meet scheme requirements for sign-off.'
  }
];

const EnergyEfficiencyModule6Section3: React.FC = () => {
  const [expandedFAQ, setExpandedFAQ] = useState<number | null>(null);

  useSEO({
    title: TITLE,
    description: DESCRIPTION,
    keywords: ['ECO4', 'Enhanced Capital Allowances', 'Salix Finance', 'energy efficiency funding', 'green finance UK'],
    canonicalUrl: '/study-centre/upskilling/energy-efficiency/module-6/section-3'
  });

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#1a1a1a]">
      {/* Sticky Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="..">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <article className="px-4 sm:px-6 py-8 sm:py-12">
        {/* Centered Title Header */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Zap className="h-4 w-4" />
            <span>Module 6 Section 3</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            Incentives and Funding Opportunities
          </h1>
          <p className="text-white/80">
            UK schemes to fund energy efficiency improvements
          </p>
        </header>

        {/* Quick Summary Boxes */}
        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2">Key Schemes</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>ECO4:</strong> Free insulation for fuel-poor homes</li>
              <li><strong>ECAs:</strong> 100% tax deduction on equipment</li>
              <li><strong>Salix:</strong> Interest-free public sector loans</li>
              <li><strong>LAD:</strong> Local authority delivery grants</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2">Eligibility Tips</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>ECO4:</strong> Benefits, low EPC, fuel poverty</li>
              <li><strong>ECAs:</strong> Products on Energy Technology List</li>
              <li><strong>Salix:</strong> NHS, councils, schools only</li>
              <li><strong>Pre-approval:</strong> Always secure before work</li>
            </ul>
          </div>
        </div>

        {/* Learning Outcomes */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You'll Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              'ECO4 eligibility criteria and measures',
              'Enhanced Capital Allowances for businesses',
              'Salix Finance for public sector clients',
              'Local authority funding schemes',
              'Green finance options for commercial clients',
              'How to help clients access funding'
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        <hr className="border-white/5 mb-12" />

        {/* Section 01: ECO4 */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            ECO4 (Energy Company Obligation)
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              ECO4 is the fourth phase of the Energy Company Obligation, running from 2022 to 2026. It requires large energy suppliers to fund energy efficiency improvements in fuel-poor homes. As an electrician, understanding ECO4 helps you connect vulnerable clients with free or subsidised improvements.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Eligible households:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Households on qualifying benefits (Universal Credit, Pension Credit, Child Tax Credits, etc.)</li>
                <li>Low-income households in fuel poverty</li>
                <li>Properties with EPC rating D, E, F, or G</li>
                <li>Referrals through local authority flex eligibility</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Funded measures:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Loft insulation (up to 300mm)</li>
                <li>Cavity wall insulation</li>
                <li>Solid wall insulation (internal or external)</li>
                <li>First-time central heating</li>
                <li>Heating controls and thermostats</li>
                <li>Boiler upgrades for broken or inefficient systems</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">How electricians can help:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Install heating controls and programmable thermostats</li>
                <li>Upgrade electric heating systems</li>
                <li>Install first-time central heating electrical supplies</li>
                <li>Refer clients to ECO installers for insulation</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 02: Enhanced Capital Allowances */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            Enhanced Capital Allowances (ECAs)
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Enhanced Capital Allowances allow businesses to deduct 100% of the cost of qualifying energy-efficient equipment from taxable profits in the year of purchase. This accelerates tax relief compared to standard writing-down allowances spread over several years.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">How ECAs work:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>100% first-year allowance on qualifying equipment</li>
                <li>Immediate cash-flow benefit through reduced tax bill</li>
                <li>Products must be listed on the Energy Technology List (ETL)</li>
                <li>Equipment must be new (not second-hand)</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Qualifying equipment categories:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Motors and drives:</strong> Variable speed drives, high-efficiency motors</li>
                <li><strong>Lighting:</strong> LED luminaires, lighting controls</li>
                <li><strong>HVAC:</strong> Air conditioning, chillers, heat pumps</li>
                <li><strong>Building controls:</strong> BEMS, automatic controls</li>
                <li><strong>Refrigeration:</strong> Efficient commercial refrigeration</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Example calculation:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>LED lighting system cost: £20,000</li>
                <li>Corporation tax rate: 25%</li>
                <li>Tax saving: £20,000 x 25% = £5,000</li>
                <li>Effective net cost: £15,000 (25% discount)</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 03: Salix Finance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Salix Finance (Public Sector)
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Salix Finance provides interest-free loans to public sector organisations for energy efficiency improvements. The loans are designed to be cash-flow neutral - repayments are funded by the energy savings generated by the improvements.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Eligible organisations:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>NHS trusts and health boards</li>
                <li>Schools, academies, and universities</li>
                <li>Local authorities and councils</li>
                <li>Police, fire, and emergency services</li>
                <li>Central government departments</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Key features:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>0% interest rate - no cost of borrowing</li>
                <li>5-8 year typical repayment period</li>
                <li>Repayments match projected energy savings</li>
                <li>No minimum or maximum project size</li>
                <li>Multiple technologies can be bundled</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Eligible measures:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>LED lighting upgrades</li>
                <li>Building Energy Management Systems (BEMS)</li>
                <li>Variable speed drives and motor upgrades</li>
                <li>Heating and cooling system improvements</li>
                <li>Building fabric improvements</li>
                <li>Renewable energy installations</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Section 04: Local Authority Schemes */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Local Authority Schemes
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Local authorities deliver various energy efficiency programmes funded by central government, energy companies, and their own budgets. These schemes often target specific areas or demographics and can complement national programmes.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Home Upgrade Grant (HUG):</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Targets off-gas-grid homes with low EPCs</li>
                <li>Funded improvements include insulation and clean heating</li>
                <li>Means-tested eligibility criteria</li>
                <li>Delivered through local authority partnerships</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Local Authority Delivery (LAD):</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Councils identify eligible properties in their areas</li>
                <li>Often area-based targeting of low EPC homes</li>
                <li>Can include private rented and owner-occupied</li>
                <li>Budget varies by local authority</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Finding local schemes:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Contact your local council's housing or sustainability team</li>
                <li>Check Simple Energy Advice website for area-specific grants</li>
                <li>Sign up to local authority contractor frameworks</li>
                <li>Network with other local installers to share intelligence</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Section 05: Commercial Green Finance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">05</span>
            Commercial Green Finance
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Beyond government schemes, commercial green finance options are expanding rapidly. Banks and specialist lenders offer products tailored to energy efficiency investments, often with preferential rates reflecting the reduced risk of lower energy bills.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Green loans:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Lower interest rates than standard business loans</li>
                <li>Ring-fenced for sustainability improvements</li>
                <li>Available from most major banks</li>
                <li>Typically require evidence of environmental benefit</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Energy performance contracts:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>ESCo (Energy Service Company) funds improvements</li>
                <li>Client pays from guaranteed energy savings</li>
                <li>Risk transferred to ESCo if savings not achieved</li>
                <li>Suitable for large commercial and public sector</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">PACE financing:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Property Assessed Clean Energy model</li>
                <li>Repayment attached to property, not owner</li>
                <li>Transfers with property on sale</li>
                <li>Growing availability in UK commercial sector</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Section 06: Applying for Funding */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">06</span>
            Applying for Funding Successfully
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Before starting work:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Always secure funding approval in writing</li>
                <li>Understand what documentation is required</li>
                <li>Check product specifications meet scheme requirements</li>
                <li>Clarify payment timelines and processes</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Supporting documentation:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Energy assessment or survey report</li>
                <li>Product specifications and ETL references</li>
                <li>Detailed quotation breaking down costs</li>
                <li>Projected energy and carbon savings calculations</li>
                <li>Installation timeline and methodology</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-red-400/80 mb-2">Common pitfalls:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Starting before approval</strong> - Most schemes require pre-approval</li>
                <li><strong>Wrong products</strong> - Check ETL listing for ECAs</li>
                <li><strong>Missing deadlines</strong> - Funding windows close; apply early</li>
                <li><strong>Incomplete records</strong> - Retain all documentation</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Practical Guidance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Practical Guidance</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Advising domestic clients</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Ask about benefits to check ECO4 eligibility</li>
                <li>Refer to energy supplier or Simple Energy Advice</li>
                <li>Suggest home insulation before heating upgrades</li>
                <li>Explain the "fabric first" approach to energy efficiency</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Advising business clients</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Mention Enhanced Capital Allowances in quotations</li>
                <li>Specify ETL-listed products where possible</li>
                <li>Calculate tax savings to improve business case</li>
                <li>Suggest checking with their accountant about tax relief</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">Advising public sector clients</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Highlight Salix 0% finance option</li>
                <li>Emphasise cash-flow neutral repayments</li>
                <li>Help with savings calculations for applications</li>
                <li>Offer to bundle multiple measures in one project</li>
              </ul>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <button
                  onClick={() => setExpandedFAQ(expandedFAQ === index ? null : index)}
                  className="w-full flex items-center justify-between text-left min-h-[44px] touch-manipulation"
                >
                  <h3 className="text-sm font-medium text-white pr-4">{faq.question}</h3>
                  {expandedFAQ === index ? (
                    <ChevronUp className="w-5 h-5 text-elec-yellow flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-elec-yellow flex-shrink-0" />
                  )}
                </button>
                {expandedFAQ === index && (
                  <p className="text-sm text-white/90 leading-relaxed mt-2">{faq.answer}</p>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Reference Card */}
        <section className="mb-10">
          <div className="mt-6 p-5 rounded-lg bg-transparent">
            <h3 className="text-sm font-medium text-white mb-4">Quick Reference</h3>
            <div className="grid sm:grid-cols-2 gap-4 text-xs text-white">
              <div>
                <p className="font-medium text-white mb-1">Domestic Schemes</p>
                <ul className="space-y-0.5">
                  <li>ECO4: Free insulation for fuel poor</li>
                  <li>HUG: Off-gas-grid upgrades</li>
                  <li>LAD: Council-targeted areas</li>
                  <li>BUS: Boiler Upgrade Scheme</li>
                </ul>
              </div>
              <div>
                <p className="font-medium text-white mb-1">Commercial/Public</p>
                <ul className="space-y-0.5">
                  <li>ECAs: 100% tax deduction</li>
                  <li>Salix: 0% public sector loans</li>
                  <li>Green loans: Bank products</li>
                  <li>PACE: Property-attached finance</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Quiz */}
        <section className="mb-10">
          <Quiz
            title="Test Your Knowledge"
            questions={quizQuestions}
          />
        </section>

        {/* Navigation */}
        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../section-2">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Previous Section
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../section-4">
              Next Section
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>
      </article>
    </div>
  );
};

export default EnergyEfficiencyModule6Section3;
