import { ArrowLeft, Zap, CheckCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import useSEO from "@/hooks/useSEO";

const TITLE = "DC Rapid Charging Infrastructure - Renewable Energy Module 6";
const DESCRIPTION =
  "Advanced knowledge of DC rapid charging technology including power architecture, cooling systems, installation requirements, and grid connection considerations for high-power charging infrastructure.";

const quickCheckQuestions = [
  {
    id: "dc-rapid-qc1",
    question: "What is the typical efficiency of a modern 150 kW DC rapid charger?",
    options: ["80-85%", "88-92%", "93-96%", "97-99%"],
    correctIndex: 2,
    explanation:
      "Modern high-power DC chargers achieve 93-96% efficiency, with losses occurring in AC-DC conversion, DC-DC conversion, and cooling systems.",
  },
  {
    id: "dc-rapid-qc2",
    question: "What cooling method is typically used for cables on ultra-rapid chargers above 150 kW?",
    options: ["Natural air cooling", "Forced air cooling", "Liquid cooling", "No cooling required"],
    correctIndex: 2,
    explanation:
      "Ultra-rapid chargers above 150 kW use liquid-cooled cables to manage the heat generated by high currents, enabling smaller, more flexible cables.",
  },
  {
    id: "dc-rapid-qc3",
    question: "What DNO connection type is typically required for a 350 kW rapid charger?",
    options: ["Low voltage single-phase", "Low voltage three-phase", "High voltage (11kV/33kV)", "Any connection type"],
    correctIndex: 2,
    explanation:
      "350 kW chargers typically require HV connections with on-site transformers, as LV supplies cannot economically provide the required capacity.",
  },
  {
    id: "dc-rapid-qc4",
    question: "What is the primary purpose of power factor correction in DC chargers?",
    options: [
      "Increase charging speed",
      "Reduce harmonic distortion and improve efficiency",
      "Provide backup power",
      "Enable V2G operation",
    ],
    correctIndex: 1,
    explanation:
      "Power factor correction improves the power factor to near unity, reducing reactive power demand, harmonic distortion, and associated network charges.",
  },
];

const quizQuestions = [
  {
    id: 1,
    question: "What is the maximum continuous current rating for a typical CCS Combo 2 connector?",
    options: ["200A", "350A", "500A", "1000A"],
    correctAnswer: 2,
    explanation:
      "CCS Combo 2 connectors are rated for up to 500A continuous current with liquid cooling, enabling power levels up to 350 kW at 800V.",
  },
  {
    id: 2,
    question: "What DC voltage range do most modern rapid chargers support?",
    options: ["200-400V only", "200-500V", "200-920V", "400-800V only"],
    correctAnswer: 2,
    explanation:
      "Modern rapid chargers support 200-920V to accommodate both 400V vehicle architectures and newer 800V systems that enable faster charging.",
  },
  {
    id: 3,
    question: "What is the purpose of the contactor in a DC rapid charger?",
    options: [
      "To measure current",
      "To safely connect/disconnect DC power to the vehicle",
      "To convert AC to DC",
      "To cool the cable",
    ],
    correctAnswer: 1,
    explanation:
      "DC contactors safely connect and disconnect high-current DC power to the vehicle, providing galvanic isolation when not charging and during fault conditions.",
  },
  {
    id: 4,
    question: "What pre-charge function is performed before main DC power is connected?",
    options: [
      "Battery temperature check",
      "Soft-start to prevent inrush current damage",
      "User authentication",
      "Cable continuity test",
    ],
    correctAnswer: 1,
    explanation:
      "Pre-charge gradually increases voltage to match the vehicle battery before connecting main contactors, preventing damaging inrush currents to capacitors.",
  },
  {
    id: 5,
    question: "What is the typical site footprint for a dual-output 350 kW charging station?",
    options: ["2m x 2m", "3m x 4m", "5m x 8m", "10m x 15m"],
    correctAnswer: 2,
    explanation:
      "A dual-output 350 kW station typically requires 5m x 8m or larger, including the power cabinet, dispensers, transformer (if HV), and maintenance access.",
  },
  {
    id: 6,
    question: "What protection is essential for DC rapid charger installations?",
    options: [
      "Type A RCD only",
      "Surge protection and DC isolation monitoring",
      "MCB only",
      "No special protection required",
    ],
    correctAnswer: 1,
    explanation:
      "DC rapid chargers require surge protection (SPDs) for both AC and DC sides, plus DC isolation monitoring to detect ground faults on the DC system.",
  },
  {
    id: 7,
    question: "What communication protocol controls power delivery during DC fast charging?",
    options: [
      "Control Pilot only",
      "CAN bus or Power Line Communication",
      "WiFi",
      "Bluetooth",
    ],
    correctAnswer: 1,
    explanation:
      "DC fast charging uses CAN bus (CHAdeMO) or PLC/High Level Communication (CCS) to precisely control voltage and current based on battery requirements.",
  },
  {
    id: 8,
    question: "What is power stacking in rapid charger installations?",
    options: [
      "Installing chargers on top of each other",
      "Sharing power modules between multiple dispensers",
      "Battery storage integration",
      "Grid reinforcement",
    ],
    correctAnswer: 1,
    explanation:
      "Power stacking shares power modules between dispensers, allowing full power to one vehicle or split power to multiple vehicles simultaneously.",
  },
  {
    id: 9,
    question: "What noise level consideration applies to rapid charger installations?",
    options: [
      "No noise is produced",
      "Cooling systems can produce significant noise requiring mitigation",
      "Noise only occurs during faults",
      "Noise is below audible levels",
    ],
    correctAnswer: 1,
    explanation:
      "High-power charger cooling fans and transformers can produce 60-75 dB noise, requiring consideration of proximity to noise-sensitive locations and potential mitigation.",
  },
  {
    id: 10,
    question: "What is the primary benefit of battery-buffered rapid charging?",
    options: [
      "Faster vehicle charging",
      "Reduced peak grid demand and connection costs",
      "Improved charger efficiency",
      "Extended cable life",
    ],
    correctAnswer: 1,
    explanation:
      "Battery buffers store energy during low-demand periods and supplement grid power during charging, reducing peak demand and potentially enabling rapid charging on smaller grid connections.",
  },
];

const faqs = [
  {
    question: "How long does it take to install a DC rapid charging station?",
    answer:
      "Installation timelines vary significantly based on grid connection requirements. With existing adequate supply, installation might take 2-4 weeks. If HV connection or DNO reinforcement is needed, the total project can take 12-24 months, with most time spent on grid connection works.",
  },
  {
    question: "What maintenance do DC rapid chargers require?",
    answer:
      "DC rapid chargers require regular maintenance including filter cleaning/replacement, cooling system checks, connector inspection and cleaning, firmware updates, and electrical testing. Manufacturer service contracts typically specify quarterly or six-monthly preventive maintenance visits.",
  },
  {
    question: "Can I install a 350 kW charger on a standard LV supply?",
    answer:
      "A 350 kW charger requires approximately 400+ kVA supply capacity, exceeding typical LV connection limits. Most 350 kW installations require HV connections with dedicated transformers. Battery buffering can enable lower grid connection requirements but adds significant cost.",
  },
  {
    question: "What is the difference between dispensers and power cabinets?",
    answer:
      "The power cabinet contains AC-DC conversion equipment, cooling, and control systems. Dispensers are the user-facing units with connectors, screens, and payment terminals. Separating these allows multiple dispensers to share power infrastructure and simplifies maintenance access.",
  },
  {
    question: "How do 800V vehicle architectures affect charging infrastructure?",
    answer:
      "800V vehicles can accept higher power at lower currents than 400V vehicles, reducing cable heating. Chargers must support the wider voltage range (200-920V). Many 800V vehicles can charge at 270+ kW, making ultra-rapid infrastructure essential for these vehicles.",
  },
  {
    question: "What ground conditions affect rapid charger installation?",
    answer:
      "Heavy equipment requires adequate foundations - typically reinforced concrete slabs designed for the equipment weight and maintenance access. Underground services, drainage, and soil conditions must be assessed. Cable ducting routes need planning around existing infrastructure.",
  },
];

const RenewableEnergyModule6Section4 = () => {
  useSEO({ title: TITLE, description: DESCRIPTION });

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#1a1a1a]">
      {/* Header */}
      <header className="sticky top-0 z-30 border-b border-white/10 bg-[#1a1a1a]/95 backdrop-blur supports-[backdrop-filter]:bg-[#1a1a1a]/80">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link
            to=".."
            className="inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-white/10"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Module Overview
          </Link>
          <span className="text-sm text-white">Module 6 • Section 4</span>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden py-12 sm:py-16">
        <div className="absolute inset-0 bg-gradient-to-br from-elec-yellow/10 via-transparent to-transparent" />
        <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-elec-yellow/10 px-4 py-1.5 text-sm font-medium text-elec-yellow">
              <Zap className="h-4 w-4" />
              EV Charging Infrastructure
            </div>
            <h1 className="mb-4 text-3xl font-bold tracking-tight text-white sm:text-4xl lg:text-5xl">
              DC Rapid Charging Infrastructure
            </h1>
            <p className="text-lg text-white sm:text-xl">
              Advanced technology and installation requirements for high-power DC rapid charging systems.
            </p>
          </div>
        </div>
      </section>

      {/* Quick Summary */}
      <section className="py-8">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-lg border-l-2 border-elec-yellow/50 bg-elec-yellow/5 p-4">
              <h3 className="mb-2 font-semibold text-white">Power Architecture</h3>
              <p className="text-sm text-white">
                DC rapid chargers use sophisticated power electronics to convert AC grid power to precisely controlled DC for direct battery charging at 50-350 kW.
              </p>
            </div>
            <div className="rounded-lg border-l-2 border-elec-yellow/50 bg-elec-yellow/5 p-4">
              <h3 className="mb-2 font-semibold text-white">Grid Connection</h3>
              <p className="text-sm text-white">
                High-power installations often require HV connections with dedicated transformers, making early DNO engagement and site selection critical.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Learning Outcomes */}
      <section className="py-8">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="rounded-xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-4 text-xl font-bold text-white">Learning Outcomes</h2>
            <div className="grid gap-3 sm:grid-cols-2">
              {[
                "Understand DC rapid charger power conversion architecture",
                "Explain cooling requirements for high-power charging",
                "Identify grid connection options and requirements",
                "Describe communication protocols for DC charging",
                "Apply site planning considerations for rapid chargers",
                "Understand battery buffering and power management",
              ].map((outcome, index) => (
                <div key={index} className="flex items-start gap-3">
                  <CheckCircle className="mt-0.5 h-5 w-5 flex-shrink-0 text-elec-yellow" />
                  <span className="text-sm text-white">{outcome}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          {/* Section 01 */}
          <section className="mb-12">
            <div className="mb-4 flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-full bg-elec-yellow text-lg font-bold text-black">
                01
              </span>
              <h2 className="text-2xl font-bold text-white">DC Charger Power Architecture</h2>
            </div>
            <div className="space-y-4 text-white">
              <p>
                DC rapid chargers contain sophisticated power electronics that convert three-phase AC grid power into precisely controlled DC power matched to the vehicle battery requirements.
              </p>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Power Conversion Stages</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li><strong>Input rectification:</strong> Three-phase AC to uncontrolled DC</li>
                  <li><strong>Power factor correction:</strong> Active PFC for near-unity power factor</li>
                  <li><strong>DC-DC conversion:</strong> Isolated converter for voltage/current control</li>
                  <li><strong>Output filtering:</strong> Smoothing for clean DC output</li>
                  <li><strong>Pre-charge circuit:</strong> Controlled voltage ramp-up</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Modular Power Architecture</h4>
                <p className="mb-2">
                  Modern high-power chargers use modular designs with multiple power modules:
                </p>
                <ul className="list-inside list-disc space-y-1">
                  <li>Typical modules: 25-50 kW each</li>
                  <li>Modules operate in parallel for higher power</li>
                  <li>Redundancy: Charging continues if one module fails</li>
                  <li>Scalability: Add modules to increase capacity</li>
                  <li>Serviceability: Replace individual modules</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Power Stacking Technology</h4>
                <p>
                  Power stacking allows multiple dispensers to share a common power cabinet. When one vehicle charges alone, it receives full power. When multiple vehicles charge simultaneously, power is distributed based on demand and configuration. This maximises infrastructure utilisation and reduces cost per charging point.
                </p>
              </div>
            </div>
          </section>

          <InlineCheck
            question={quickCheckQuestions[0].question}
            options={quickCheckQuestions[0].options}
            correctIndex={quickCheckQuestions[0].correctIndex}
            explanation={quickCheckQuestions[0].explanation}
          />

          {/* Section 02 */}
          <section className="mb-12 mt-12">
            <div className="mb-4 flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-full bg-elec-yellow text-lg font-bold text-black">
                02
              </span>
              <h2 className="text-2xl font-bold text-white">Thermal Management Systems</h2>
            </div>
            <div className="space-y-4 text-white">
              <p>
                High-power charging generates significant heat that must be managed to maintain efficiency, protect components, and ensure reliable operation across all ambient conditions.
              </p>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Power Cabinet Cooling</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li><strong>Forced air cooling:</strong> Fans and heat sinks for lower power units</li>
                  <li><strong>Liquid cooling:</strong> Glycol loops for high-power cabinets</li>
                  <li><strong>Heat exchangers:</strong> Transfer heat to ambient air</li>
                  <li><strong>Climate control:</strong> Heating for cold conditions, cooling for hot</li>
                  <li><strong>Filtration:</strong> Air filters prevent contamination buildup</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Liquid-Cooled Cables</h4>
                <p className="mb-2">
                  Above 150 kW, cable current would require impractically thick conductors. Liquid-cooled cables solve this:
                </p>
                <ul className="list-inside list-disc space-y-1">
                  <li>Coolant circulates through cable jacket</li>
                  <li>Enables 500A+ in flexible, manageable cables</li>
                  <li>Requires cooling unit in cabinet or dispenser</li>
                  <li>Adds maintenance complexity</li>
                  <li>Connector includes coolant connections</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Operating Temperature Range</h4>
                <p>
                  Rapid chargers must operate reliably across wide temperature ranges, typically -35°C to +50°C ambient. Power derating may apply at temperature extremes. Cold-start heating and high-temperature cooling consume auxiliary power, affecting overall efficiency.
                </p>
              </div>
            </div>
          </section>

          <InlineCheck
            question={quickCheckQuestions[1].question}
            options={quickCheckQuestions[1].options}
            correctIndex={quickCheckQuestions[1].correctIndex}
            explanation={quickCheckQuestions[1].explanation}
          />

          {/* Section 03 */}
          <section className="mb-12 mt-12">
            <div className="mb-4 flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-full bg-elec-yellow text-lg font-bold text-black">
                03
              </span>
              <h2 className="text-2xl font-bold text-white">Grid Connection Requirements</h2>
            </div>
            <div className="space-y-4 text-white">
              <p>
                Grid connection is often the most challenging and time-consuming aspect of rapid charger deployment. Early engagement with the DNO and careful site selection are essential.
              </p>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Connection Options by Power Level</h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-white/20">
                        <th className="py-2 text-left text-white">Power Level</th>
                        <th className="py-2 text-left text-white">Typical Connection</th>
                        <th className="py-2 text-left text-white">Considerations</th>
                      </tr>
                    </thead>
                    <tbody className="text-white">
                      <tr className="border-b border-white/10">
                        <td className="py-2">50 kW</td>
                        <td className="py-2">LV three-phase</td>
                        <td className="py-2">Often feasible on existing supply</td>
                      </tr>
                      <tr className="border-b border-white/10">
                        <td className="py-2">100-150 kW</td>
                        <td className="py-2">LV or HV</td>
                        <td className="py-2">Site-dependent, may need upgrade</td>
                      </tr>
                      <tr className="border-b border-white/10">
                        <td className="py-2">150-350 kW</td>
                        <td className="py-2">HV (11kV/33kV)</td>
                        <td className="py-2">Dedicated transformer required</td>
                      </tr>
                      <tr className="border-b border-white/10">
                        <td className="py-2">350 kW+</td>
                        <td className="py-2">HV with substation</td>
                        <td className="py-2">Significant infrastructure</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">HV Connection Components</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li><strong>Ring main unit:</strong> HV switchgear for network connection</li>
                  <li><strong>Transformer:</strong> 11kV to 400V step-down, typically 500-1000 kVA</li>
                  <li><strong>LV switchgear:</strong> Distribution and protection</li>
                  <li><strong>Metering:</strong> HV or LV metering as required</li>
                  <li><strong>Earthing:</strong> Substation earth electrode system</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">DNO Application Process</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li>Budget estimate request (indicative costs and timescales)</li>
                  <li>Formal connection application with detailed design</li>
                  <li>Connection offer with firm costs and programme</li>
                  <li>Reinforcement works if required (can add 6-18 months)</li>
                  <li>Connection energisation and testing</li>
                </ul>
              </div>
            </div>
          </section>

          <InlineCheck
            question={quickCheckQuestions[2].question}
            options={quickCheckQuestions[2].options}
            correctIndex={quickCheckQuestions[2].correctIndex}
            explanation={quickCheckQuestions[2].explanation}
          />

          {/* Section 04 */}
          <section className="mb-12 mt-12">
            <div className="mb-4 flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-full bg-elec-yellow text-lg font-bold text-black">
                04
              </span>
              <h2 className="text-2xl font-bold text-white">Vehicle Communication Protocols</h2>
            </div>
            <div className="space-y-4 text-white">
              <p>
                DC rapid charging requires sophisticated communication between the charger and vehicle to safely manage high-power energy transfer to the battery.
              </p>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">CCS Communication (ISO 15118)</h4>
                <p className="mb-2">
                  CCS uses Power Line Communication (PLC) for high-level communication:
                </p>
                <ul className="list-inside list-disc space-y-1">
                  <li>Vehicle transmits battery parameters and charging requirements</li>
                  <li>Charger negotiates power delivery schedule</li>
                  <li>Continuous monitoring and adjustment during charging</li>
                  <li>Plug & Charge authentication support</li>
                  <li>V2G communication capability (ISO 15118-20)</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">CHAdeMO Communication (CAN Bus)</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li>Uses automotive CAN bus protocol</li>
                  <li>Battery parameters transmitted every 100ms</li>
                  <li>Charger adjusts output in real-time</li>
                  <li>Supports bidirectional V2X from early versions</li>
                  <li>Protocol 2.0 supports up to 400 kW</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Charging Session Sequence</h4>
                <ol className="list-inside list-decimal space-y-2">
                  <li><strong>Connection:</strong> Physical connection, pilot signal detected</li>
                  <li><strong>Identification:</strong> Protocol negotiation and authentication</li>
                  <li><strong>Pre-charge:</strong> Voltage matching before main contactors close</li>
                  <li><strong>Charging:</strong> Power delivery with continuous monitoring</li>
                  <li><strong>Termination:</strong> Current reduction, contactor opening</li>
                  <li><strong>Disconnection:</strong> Connector release, session logging</li>
                </ol>
              </div>
            </div>
          </section>

          <InlineCheck
            question={quickCheckQuestions[3].question}
            options={quickCheckQuestions[3].options}
            correctIndex={quickCheckQuestions[3].correctIndex}
            explanation={quickCheckQuestions[3].explanation}
          />

          {/* Section 05 */}
          <section className="mb-12 mt-12">
            <div className="mb-4 flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-full bg-elec-yellow text-lg font-bold text-black">
                05
              </span>
              <h2 className="text-2xl font-bold text-white">Site Planning and Installation</h2>
            </div>
            <div className="space-y-4 text-white">
              <p>
                Rapid charger installations require careful site planning considering equipment footprint, civil works, electrical infrastructure, and operational requirements.
              </p>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Site Layout Considerations</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li>Power cabinet positioning for maintenance access</li>
                  <li>Dispenser locations for vehicle reach and traffic flow</li>
                  <li>Cable routing between cabinet and dispensers</li>
                  <li>Transformer and switchgear location if HV</li>
                  <li>Customer waiting/shelter areas</li>
                  <li>Signage and lighting requirements</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Civil Engineering Requirements</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li><strong>Foundations:</strong> Reinforced concrete pads for heavy equipment</li>
                  <li><strong>Ducting:</strong> Multiple duct routes for power and data</li>
                  <li><strong>Drainage:</strong> Surface water management around equipment</li>
                  <li><strong>Surfacing:</strong> Appropriate surface for vehicle loading</li>
                  <li><strong>Barriers:</strong> Protection from vehicle impact</li>
                </ul>
              </div>
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="mb-3 font-semibold text-elec-yellow">Environmental Considerations</h4>
                <ul className="list-inside list-disc space-y-2">
                  <li><strong>Noise:</strong> Cooling fans can reach 70+ dB - consider neighbours</li>
                  <li><strong>Visual impact:</strong> Equipment screening may be required</li>
                  <li><strong>Lighting:</strong> Adequate for safe use without light pollution</li>
                  <li><strong>Flood risk:</strong> Equipment elevation and drainage</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Practical Guidance */}
          <section className="mb-12 mt-12">
            <div className="rounded-xl border border-elec-yellow/30 bg-elec-yellow/5 p-6">
              <h2 className="mb-4 text-xl font-bold text-white">Practical Guidance</h2>
              <div className="space-y-4 text-white">
                <div>
                  <h4 className="font-semibold text-elec-yellow">Battery Buffering Option</h4>
                  <p className="mt-1 text-sm">
                    Battery energy storage can reduce peak grid demand and connection costs. The buffer charges slowly from a smaller grid connection and supplements grid power during charging sessions. This adds capital cost but may be economic where grid reinforcement is expensive.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-elec-yellow">Commissioning Requirements</h4>
                  <p className="mt-1 text-sm">
                    Rapid charger commissioning involves electrical testing, communication verification, vehicle compatibility testing, and backend integration. Manufacturer technical support is typically required. Plan adequate time for commissioning - issues are common with complex systems.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-elec-yellow">Ongoing Support Planning</h4>
                  <p className="mt-1 text-sm">
                    Rapid chargers require robust support arrangements. Remote monitoring enables proactive maintenance. Spare parts holding reduces downtime for common failures. Service level agreements should specify response times appropriate to the site's commercial importance.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* FAQs */}
          <section className="mb-12">
            <h2 className="mb-6 text-2xl font-bold text-white">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {faqs.map((faq, index) => (
                <div key={index} className="rounded-lg border border-white/10 bg-white/5 p-4">
                  <h3 className="mb-2 font-semibold text-elec-yellow">{faq.question}</h3>
                  <p className="text-sm text-white">{faq.answer}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Quiz Section */}
          <section className="mb-12">
            <Quiz
              title="DC Rapid Charging Quiz"
              questions={quizQuestions}
              onComplete={(score) => console.log("Quiz completed with score:", score)}
            />
          </section>

          {/* Navigation */}
          <nav className="mt-12 flex flex-col gap-4 border-t border-white/10 pt-8 sm:flex-row sm:justify-between">
            <Link to="/upskilling/renewable-energy/module-6/section-3">
              <Button variant="outline" className="w-full gap-2 border-white/20 text-white hover:bg-white/10 sm:w-auto">
                <ArrowLeft className="h-4 w-4" />
                Previous Section
              </Button>
            </Link>
            <Link to="/upskilling/renewable-energy/module-6/section-5">
              <Button className="w-full gap-2 bg-elec-yellow text-black hover:bg-elec-yellow/90 sm:w-auto">
                Next Section
                <ArrowLeft className="h-4 w-4 rotate-180" />
              </Button>
            </Link>
          </nav>
        </div>
      </div>
    </div>
  );
};

export default RenewableEnergyModule6Section4;
