import { ArrowLeft, Zap, CheckCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Quiz } from "@/components/apprentice-courses/Quiz";
import { InlineCheck } from "@/components/apprentice-courses/InlineCheck";
import useSEO from "@/hooks/useSEO";

const TITLE = "DC Rapid Charging Infrastructure - Renewable Energy Module 6 Section 4";
const DESCRIPTION = "Advanced knowledge of DC rapid charging technology including power architecture, cooling systems, installation requirements, and grid connection considerations for high-power charging infrastructure.";

const quickCheckQuestions = [
  {
    id: "dc-rapid-qc1",
    question: "What is the typical efficiency of a modern 150 kW DC rapid charger?",
    options: ["80-85%", "88-92%", "93-96%", "97-99%"],
    correctIndex: 2,
    explanation: "Modern high-power DC chargers achieve 93-96% efficiency, with losses occurring in AC-DC conversion, DC-DC conversion, and cooling systems."
  },
  {
    id: "dc-rapid-qc2",
    question: "What cooling method is typically used for cables on ultra-rapid chargers above 150 kW?",
    options: ["Natural air cooling", "Forced air cooling", "Liquid cooling", "No cooling required"],
    correctIndex: 2,
    explanation: "Ultra-rapid chargers above 150 kW use liquid-cooled cables to manage the heat generated by high currents, enabling smaller, more flexible cables."
  },
  {
    id: "dc-rapid-qc3",
    question: "What DNO connection type is typically required for a 350 kW rapid charger?",
    options: ["Low voltage single-phase", "Low voltage three-phase", "High voltage (11kV/33kV)", "Any connection type"],
    correctIndex: 2,
    explanation: "350 kW chargers typically require HV connections with on-site transformers, as LV supplies cannot economically provide the required capacity."
  }
];

const quizQuestions = [
  {
    id: 1,
    question: "What is the maximum continuous current rating for a typical CCS Combo 2 connector?",
    options: ["200A", "350A", "500A", "1000A"],
    correctAnswer: 2,
    explanation: "CCS Combo 2 connectors are rated for up to 500A continuous current with liquid cooling, enabling power levels up to 350 kW at 800V."
  },
  {
    id: 2,
    question: "What DC voltage range do most modern rapid chargers support?",
    options: ["200-400V only", "200-500V", "200-920V", "400-800V only"],
    correctAnswer: 2,
    explanation: "Modern rapid chargers support 200-920V to accommodate both 400V vehicle architectures and newer 800V systems that enable faster charging."
  },
  {
    id: 3,
    question: "What is the purpose of the contactor in a DC rapid charger?",
    options: ["To measure current", "To safely connect/disconnect DC power to the vehicle", "To convert AC to DC", "To cool the cable"],
    correctAnswer: 1,
    explanation: "DC contactors safely connect and disconnect high-current DC power to the vehicle, providing galvanic isolation when not charging and during fault conditions."
  },
  {
    id: 4,
    question: "What pre-charge function is performed before main DC power is connected?",
    options: ["Battery temperature check", "Soft-start to prevent inrush current damage", "User authentication", "Cable continuity test"],
    correctAnswer: 1,
    explanation: "Pre-charge gradually increases voltage to match the vehicle battery before connecting main contactors, preventing damaging inrush currents to capacitors."
  },
  {
    id: 5,
    question: "What is the typical site footprint for a dual-output 350 kW charging station?",
    options: ["2m x 2m", "3m x 4m", "5m x 8m", "10m x 15m"],
    correctAnswer: 2,
    explanation: "A dual-output 350 kW station typically requires 5m x 8m or larger, including the power cabinet, dispensers, transformer (if HV), and maintenance access."
  },
  {
    id: 6,
    question: "What protection is essential for DC rapid charger installations?",
    options: ["Type A RCD only", "Surge protection and DC isolation monitoring", "MCB only", "No special protection required"],
    correctAnswer: 1,
    explanation: "DC rapid chargers require surge protection (SPDs) for both AC and DC sides, plus DC isolation monitoring to detect ground faults on the DC system."
  },
  {
    id: 7,
    question: "What communication protocol controls power delivery during DC fast charging?",
    options: ["Control Pilot only", "CAN bus or Power Line Communication", "WiFi", "Bluetooth"],
    correctAnswer: 1,
    explanation: "DC fast charging uses CAN bus (CHAdeMO) or PLC/High Level Communication (CCS) to precisely control voltage and current based on battery requirements."
  },
  {
    id: 8,
    question: "What is power stacking in rapid charger installations?",
    options: ["Installing chargers on top of each other", "Sharing power modules between multiple dispensers", "Battery storage integration", "Grid reinforcement"],
    correctAnswer: 1,
    explanation: "Power stacking shares power modules between dispensers, allowing full power to one vehicle or split power to multiple vehicles simultaneously."
  },
  {
    id: 9,
    question: "What noise level consideration applies to rapid charger installations?",
    options: ["No noise is produced", "Cooling systems can produce significant noise requiring mitigation", "Noise only occurs during faults", "Noise is below audible levels"],
    correctAnswer: 1,
    explanation: "High-power charger cooling fans and transformers can produce 60-75 dB noise, requiring consideration of proximity to noise-sensitive locations and potential mitigation."
  },
  {
    id: 10,
    question: "What is the primary benefit of battery-buffered rapid charging?",
    options: ["Faster vehicle charging", "Reduced peak grid demand and connection costs", "Improved charger efficiency", "Extended cable life"],
    correctAnswer: 1,
    explanation: "Battery buffers store energy during low-demand periods and supplement grid power during charging, reducing peak demand and potentially enabling rapid charging on smaller grid connections."
  }
];

const faqs = [
  {
    question: "How long does it take to install a DC rapid charging station?",
    answer: "Installation timelines vary significantly based on grid connection requirements. With existing adequate supply, installation might take 2-4 weeks. If HV connection or DNO reinforcement is needed, the total project can take 12-24 months, with most time spent on grid connection works."
  },
  {
    question: "What maintenance do DC rapid chargers require?",
    answer: "DC rapid chargers require regular maintenance including filter cleaning/replacement, cooling system checks, connector inspection and cleaning, firmware updates, and electrical testing. Manufacturer service contracts typically specify quarterly or six-monthly preventive maintenance visits."
  },
  {
    question: "Can I install a 350 kW charger on a standard LV supply?",
    answer: "A 350 kW charger requires approximately 400+ kVA supply capacity, exceeding typical LV connection limits. Most 350 kW installations require HV connections with dedicated transformers. Battery buffering can enable lower grid connection requirements but adds significant cost."
  },
  {
    question: "What is the difference between dispensers and power cabinets?",
    answer: "The power cabinet contains AC-DC conversion equipment, cooling, and control systems. Dispensers are the user-facing units with connectors, screens, and payment terminals. Separating these allows multiple dispensers to share power infrastructure and simplifies maintenance access."
  },
  {
    question: "How do 800V vehicle architectures affect charging infrastructure?",
    answer: "800V vehicles can accept higher power at lower currents than 400V vehicles, reducing cable heating. Chargers must support the wider voltage range (200-920V). Many 800V vehicles can charge at 270+ kW, making ultra-rapid infrastructure essential for these vehicles."
  },
  {
    question: "What ground conditions affect rapid charger installation?",
    answer: "Heavy equipment requires adequate foundations - typically reinforced concrete slabs designed for the equipment weight and maintenance access. Underground services, drainage, and soil conditions must be assessed. Cable ducting routes need planning around existing infrastructure."
  }
];

const RenewableEnergyModule6Section4 = () => {
  useSEO(TITLE, DESCRIPTION);

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#1a1a1a]">
      {/* Minimal Header */}
      <div className="border-b border-white/10 sticky top-0 z-50 bg-[#1a1a1a]/95 backdrop-blur-sm">
        <div className="px-4 sm:px-6 py-2">
          <Button variant="ghost" size="lg" className="min-h-[44px] px-3 -ml-3 text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="/electrician/upskilling/renewable-energy-module-6">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Link>
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <article className="px-4 sm:px-6 py-8 sm:py-12">

        {/* Centered Title */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-elec-yellow text-sm mb-3">
            <Zap className="h-4 w-4" />
            <span>Module 6 Section 4</span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3">
            DC Rapid Charging Infrastructure
          </h1>
          <p className="text-white/80">
            High-Power Technology &amp; Grid Connections
          </p>
        </header>

        {/* Quick Summary Boxes */}
        <div className="grid sm:grid-cols-2 gap-4 mb-12">
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow text-sm font-medium mb-2">In 30 Seconds</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>Power:</strong> 50-350 kW, modular architecture</li>
              <li><strong>Cooling:</strong> Liquid-cooled cables above 150 kW</li>
              <li><strong>Grid:</strong> HV connection typically needed for 150 kW+</li>
              <li><strong>Efficiency:</strong> 93-96% for modern chargers</li>
            </ul>
          </div>
          <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50">
            <p className="text-elec-yellow/90 text-sm font-medium mb-2">Spot it / Use it</p>
            <ul className="text-sm text-white space-y-1">
              <li><strong>Spot:</strong> Power cabinet, dispenser units, cooling systems</li>
              <li><strong>Use:</strong> Site assessment, grid connection planning</li>
              <li><strong>Apply:</strong> Specify appropriate rapid charging solutions</li>
            </ul>
          </div>
        </div>

        {/* Learning Outcomes */}
        <section className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-4">What You'll Learn</h2>
          <div className="grid sm:grid-cols-2 gap-2">
            {[
              "Understand DC rapid charger power conversion architecture",
              "Explain cooling requirements for high-power charging",
              "Identify grid connection options and requirements",
              "Describe communication protocols for DC charging",
              "Apply site planning considerations for rapid chargers",
              "Understand battery buffering and power management"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-white">
                <CheckCircle className="h-4 w-4 text-elec-yellow/70 mt-0.5 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 mb-12" />

        {/* Section 1: DC Charger Power Architecture */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">01</span>
            DC Charger Power Architecture
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              DC rapid chargers contain sophisticated power electronics that convert three-phase AC grid power into precisely controlled DC power matched to the vehicle battery requirements.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Power Conversion Stages</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Input rectification:</strong> Three-phase AC to uncontrolled DC</li>
                <li><strong>Power factor correction:</strong> Active PFC for near-unity power factor</li>
                <li><strong>DC-DC conversion:</strong> Isolated converter for voltage/current control</li>
                <li><strong>Output filtering:</strong> Smoothing for clean DC output</li>
                <li><strong>Pre-charge circuit:</strong> Controlled voltage ramp-up</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Modular Power Architecture</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Typical modules: 25-50 kW each</li>
                <li>Modules operate in parallel for higher power</li>
                <li>Redundancy: Charging continues if one module fails</li>
                <li>Scalability: Add modules to increase capacity</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[0]} />

        {/* Section 2: Thermal Management Systems */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">02</span>
            Thermal Management Systems
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              High-power charging generates significant heat that must be managed to maintain efficiency, protect components, and ensure reliable operation across all ambient conditions.
            </p>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Power Cabinet Cooling</p>
                <ul className="text-sm text-white space-y-1">
                  <li>Forced air cooling for lower power</li>
                  <li>Liquid cooling for high-power cabinets</li>
                  <li>Heat exchangers to ambient air</li>
                  <li>Climate control for temperature extremes</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Liquid-Cooled Cables</p>
                <ul className="text-sm text-white space-y-1">
                  <li>Coolant circulates through cable jacket</li>
                  <li>Enables 500A+ in flexible cables</li>
                  <li>Requires cooling unit in cabinet</li>
                  <li>Adds maintenance complexity</li>
                </ul>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-elec-yellow/5 border-l-2 border-elec-yellow/50 my-6">
              <p className="text-elec-yellow text-sm font-medium">
                Operating Range: Rapid chargers must operate reliably from -35°C to +50°C ambient. Power derating may apply at temperature extremes.
              </p>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[1]} />

        {/* Section 3: Grid Connection Requirements */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">03</span>
            Grid Connection Requirements
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Grid connection is often the most challenging and time-consuming aspect of rapid charger deployment. Early engagement with the DNO and careful site selection are essential.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-white mb-2">Connection Options by Power Level:</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>50 kW:</strong> LV three-phase, often feasible on existing supply</li>
                <li><strong>100-150 kW:</strong> LV or HV, site-dependent</li>
                <li><strong>150-350 kW:</strong> HV (11kV/33kV), dedicated transformer required</li>
                <li><strong>350 kW+:</strong> HV with substation, significant infrastructure</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">HV Connection Components</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Ring main unit:</strong> HV switchgear for network connection</li>
                <li><strong>Transformer:</strong> 11kV to 400V step-down, typically 500-1000 kVA</li>
                <li><strong>LV switchgear:</strong> Distribution and protection</li>
                <li><strong>Metering:</strong> HV or LV metering as required</li>
              </ul>
            </div>
          </div>
        </section>

        <InlineCheck {...quickCheckQuestions[2]} />

        {/* Section 4: Vehicle Communication Protocols */}
        <section className="mb-10 mt-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">04</span>
            Vehicle Communication Protocols
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              DC rapid charging requires sophisticated communication between the charger and vehicle to safely manage high-power energy transfer to the battery.
            </p>

            <div className="grid sm:grid-cols-2 gap-6 my-6">
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">CCS Communication (ISO 15118)</p>
                <ul className="text-sm text-white space-y-1">
                  <li>Power Line Communication (PLC)</li>
                  <li>Vehicle transmits battery parameters</li>
                  <li>Charger negotiates power delivery</li>
                  <li>Plug &amp; Charge authentication</li>
                </ul>
              </div>
              <div>
                <p className="text-sm font-medium text-elec-yellow/80 mb-2">Charging Session Sequence</p>
                <ul className="text-sm text-white space-y-1">
                  <li>1. Connection and identification</li>
                  <li>2. Pre-charge voltage matching</li>
                  <li>3. Main charging with monitoring</li>
                  <li>4. Termination and disconnection</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Section 5: Site Planning and Installation */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="text-elec-yellow/80 text-sm font-normal">05</span>
            Site Planning and Installation
          </h2>
          <div className="text-white space-y-4 leading-relaxed">
            <p>
              Rapid charger installations require careful site planning considering equipment footprint, civil works, electrical infrastructure, and operational requirements.
            </p>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Site Layout Considerations</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Power cabinet positioning for maintenance access</li>
                <li>Dispenser locations for vehicle reach and traffic flow</li>
                <li>Cable routing between cabinet and dispensers</li>
                <li>Customer waiting/shelter areas</li>
                <li>Signage and lighting requirements</li>
              </ul>
            </div>

            <div className="my-6">
              <p className="text-sm font-medium text-elec-yellow/80 mb-2">Environmental Considerations</p>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Noise:</strong> Cooling fans can reach 70+ dB - consider neighbours</li>
                <li><strong>Visual impact:</strong> Equipment screening may be required</li>
                <li><strong>Lighting:</strong> Adequate for safe use without light pollution</li>
                <li><strong>Flood risk:</strong> Equipment elevation and drainage</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Practical Guidance */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Practical Guidance</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">When Planning Projects</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Request DNO budget estimate early</li>
                <li>Allow 12-24 months for HV connections</li>
                <li>Consider battery buffering for constrained sites</li>
                <li>Plan for maintenance access and spare parts</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-elec-yellow/80 mb-2">When Commissioning</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li>Manufacturer technical support typically required</li>
                <li>Vehicle compatibility testing essential</li>
                <li>Backend integration verification</li>
                <li>Plan adequate time - issues are common</li>
              </ul>
            </div>

            <div>
              <h3 className="text-sm font-medium text-red-400/80 mb-2">Common Mistakes to Avoid</h3>
              <ul className="text-sm text-white space-y-1 ml-4">
                <li><strong>Underestimating timescales</strong> - grid connections take time</li>
                <li><strong>Ignoring noise</strong> - can cause neighbour complaints</li>
                <li><strong>Inadequate foundations</strong> - equipment is heavy</li>
                <li><strong>No service agreement</strong> - rapid chargers need support</li>
              </ul>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-6">Common Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="pb-4 border-b border-white/5 last:border-0">
                <h3 className="text-sm font-medium text-white mb-1">{faq.question}</h3>
                <p className="text-sm text-white/90 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <hr className="border-white/5 my-12" />

        {/* Quiz */}
        <section className="mb-10">
          <Quiz
            title="Test Your Knowledge"
            questions={quizQuestions}
          />
        </section>

        {/* Navigation */}
        <nav className="flex flex-col-reverse sm:flex-row sm:justify-between gap-3 pt-8 border-t border-white/10">
          <Button variant="ghost" size="lg" className="w-full sm:w-auto min-h-[48px] text-white/70 hover:text-white hover:bg-white/5 touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../section-3">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Previous
            </Link>
          </Button>
          <Button size="lg" className="w-full sm:w-auto min-h-[48px] bg-elec-yellow text-[#1a1a1a] hover:bg-elec-yellow/90 font-semibold touch-manipulation active:scale-[0.98]" asChild>
            <Link to="../section-5">
              Next Section
              <ArrowLeft className="w-4 h-4 ml-2 rotate-180" />
            </Link>
          </Button>
        </nav>

      </article>
    </div>
  );
};

export default RenewableEnergyModule6Section4;
