import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface LaTeXRequest {
  markdown: string;
  title?: string;
  author?: string;
  reportType?: string;
  includeSignatures?: boolean;
  watermark?: string;
}

function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\$/g, '\\$')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/#/g, '\\#')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/_/g, '\\_')
    .replace(/~/g, '\\textasciitilde{}');
}

function markdownToLatex(markdown: string, title: string, author: string, reportType: string): string {
  // Parse markdown content
  let latex = markdown;
  
  // Convert headers
  latex = latex.replace(/^### (.*$)/gm, '\\subsubsection{$1}');
  latex = latex.replace(/^## (.*$)/gm, '\\subsection{$1}');
  latex = latex.replace(/^# (.*$)/gm, '\\section{$1}');
  
  // Convert bold and italic
  latex = latex.replace(/\*\*(.*?)\*\*/g, '\\textbf{$1}');
  latex = latex.replace(/\*(.*?)\*/g, '\\textit{$1}');
  
  // Convert lists
  latex = latex.replace(/^\* (.*$)/gm, '\\item $1');
  latex = latex.replace(/^(\d+)\. (.*$)/gm, '\\item $1');
  
  // Handle tables - basic conversion
  const tableRegex = /\|(.+)\|/g;
  latex = latex.replace(tableRegex, (match, content) => {
    const cells = content.split('|').map((cell: string) => cell.trim()).filter((cell: string) => cell);
    return cells.join(' & ') + ' \\\\';
  });
  
  // Wrap list items in proper environments
  latex = latex.replace(/(\\item.*(?:\n\\item.*)*)/g, '\\begin{itemize}\n$1\n\\end{itemize}');
  
  // Create complete LaTeX document
  const fullLatex = `
\\documentclass[11pt,a4paper]{article}

% Essential packages
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage[margin=1in]{geometry}
\\usepackage{parskip}
\\usepackage{titlesec}
\\usepackage{hyperref}
\\usepackage{fancyhdr}
\\usepackage{xcolor}
\\usepackage{booktabs}
\\usepackage{longtable}
\\usepackage{array}
\\usepackage{graphicx}
\\usepackage{lastpage}

% Professional colours
\\definecolor{primaryblue}{RGB}{41, 98, 255}
\\definecolor{darkgrey}{RGB}{64, 64, 64}
\\definecolor{lightgrey}{RGB}{245, 245, 245}

% Font setup - fallback to Computer Modern if Noto not available
\\usepackage{fontspec}
\\setmainfont{Latin Modern Roman}

% Header and footer setup
\\pagestyle{fancy}
\\fancyhf{}
\\fancyhead[L]{\\textcolor{primaryblue}{${escapeLatex(title)}}}
\\fancyhead[R]{\\textcolor{darkgrey}{${escapeLatex(reportType)}}}
\\fancyfoot[C]{\\textcolor{darkgrey}{Page \\thepage\\ of \\pageref{LastPage}}}
\\renewcommand{\\headrulewidth}{0.5pt}
\\renewcommand{\\footrulewidth}{0.5pt}

% Section formatting
\\titleformat{\\section}
  {\\Large\\bfseries\\color{primaryblue}}
  {\\thesection}{1em}{}
\\titleformat{\\subsection}
  {\\large\\bfseries\\color{darkgrey}}
  {\\thesubsection}{1em}{}
\\titleformat{\\subsubsection}
  {\\normalsize\\bfseries\\color{darkgrey}}
  {\\thesubsubsection}{1em}{}

% Hyperref setup
\\hypersetup{
    colorlinks=true,
    linkcolor=primaryblue,
    urlcolor=primaryblue,
    citecolor=primaryblue
}

\\begin{document}

% Title page
\\begin{titlepage}
\\centering
\\vspace*{2cm}

{\\Huge\\bfseries\\color{primaryblue} ${escapeLatex(title)} \\par}
\\vspace{1cm}
{\\Large\\color{darkgrey} ${escapeLatex(reportType)} \\par}
\\vspace{2cm}

\\begin{tabular}{@{}ll@{}}
\\textbf{Document Type:} & ${escapeLatex(reportType)} \\\\
\\textbf{Generated By:} & ${escapeLatex(author)} \\\\
\\textbf{Date:} & \\today \\\\
\\textbf{Compliance:} & BS 7671:2018+A3:2024 \\\\
\\end{tabular}

\\vfill
{\\large\\textcolor{darkgrey}{Generated using AI Technology - Professional Electrical Reporting}}
\\end{titlepage}

% Table of contents
\\tableofcontents
\\newpage

% Main content
${latex}

% Signature section
\\vfill
\\begin{center}
\\begin{tabular}{@{}p{6cm}@{\\hspace{2cm}}p{6cm}@{}}
\\toprule
\\textbf{Inspector Signature} & \\textbf{Client Signature} \\\\
\\midrule
& \\\\[2cm]
\\bottomrule
\\end{tabular}
\\end{center}

\\end{document}
`;

  return fullLatex;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { markdown, title = "Professional Report", author = "Electrical Inspector", reportType = "Electrical Certificate", includeSignatures = true, watermark = "BS 7671:2018+A3:2024 Compliant" }: LaTeXRequest = await req.json();

    console.log('Generating LaTeX PDF for:', title);

    // Convert markdown to LaTeX
    const latexContent = markdownToLatex(markdown, title, author, reportType);

    // For now, we'll return the LaTeX source as a downloadable file
    // In a production environment, you would compile this with a LaTeX service
    console.log('LaTeX content generated successfully');

    // Since we can't run LaTeX compilation directly in Deno,
    // we'll create a response that includes both the LaTeX source
    // and instructions for compilation
    const response = {
      success: true,
      latexSource: latexContent,
      compilationInstructions: {
        engine: "pdflatex",
        packages: ["texlive-full", "texlive-fonts-extra"],
        command: "pdflatex -interaction=nonstopmode document.tex"
      },
      message: "LaTeX source generated successfully. Use a LaTeX compiler to generate PDF."
    };

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('LaTeX generation error:', error);
    return new Response(JSON.stringify({ 
      error: 'Failed to generate LaTeX document',
      details: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});