export type SymbolCategory = 'lighting' | 'sockets' | 'switches' | 'distribution' | 'safety' | 'architectural' | 'mechanical' | 'renewables' | 'containment' | 'equipment' | 'controls';

export interface SymbolDefinition {
  id: string;
  name: string;
  category: SymbolCategory;
  mountType: 'ceiling' | 'wall' | 'floor' | 'panel' | 'schematic';
  svgPath: string;
}

export const symbolRegistry: SymbolDefinition[] = [
  // Lighting
  { id: 'light-ceiling', name: 'Ceiling Light', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/ceiling-light.svg' },
  { id: 'light-wall', name: 'Wall Light', category: 'lighting', mountType: 'wall', svgPath: '/symbols/lighting/wall-light.svg' },
  { id: 'light-downlight', name: 'Downlight', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/downlight.svg' },
  { id: 'light-emergency', name: 'Emergency Light', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/emergency-light.svg' },
  { id: 'light-fluorescent', name: 'Fluorescent', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/fluorescent.svg' },
  { id: 'light-pendant', name: 'Pendant', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/pendant.svg' },
  { id: 'light-bulkhead', name: 'Bulkhead', category: 'lighting', mountType: 'wall', svgPath: '/symbols/lighting/bulkhead.svg' },
  { id: 'light-pir', name: 'PIR Sensor', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/pir-sensor.svg' },
  { id: 'light-outside', name: 'Outside Light', category: 'lighting', mountType: 'wall', svgPath: '/symbols/lighting/outside-light.svg' },
  { id: 'light-led-strip', name: 'LED Strip', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/led-strip.svg' },
  { id: 'light-exit-sign', name: 'Exit Sign', category: 'lighting', mountType: 'wall', svgPath: '/symbols/lighting/exit-sign.svg' },
  { id: 'light-twin-emergency', name: 'Twin Emergency', category: 'lighting', mountType: 'wall', svgPath: '/symbols/lighting/twin-emergency.svg' },
  { id: 'light-high-bay', name: 'High Bay', category: 'lighting', mountType: 'ceiling', svgPath: '/symbols/lighting/high-bay.svg' },
  // Sockets
  { id: 'socket-single-13a', name: 'Single 13A', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/single-13a.svg' },
  { id: 'socket-double-13a', name: 'Double 13A', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/double-13a.svg' },
  { id: 'socket-fused-spur', name: 'Fused Spur', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/fused-spur.svg' },
  { id: 'socket-cooker-45a', name: 'Cooker 45A', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/cooker-45a.svg' },
  { id: 'socket-floor', name: 'Floor Socket', category: 'sockets', mountType: 'floor', svgPath: '/symbols/sockets/floor-socket.svg' },
  { id: 'socket-outdoor', name: 'Outdoor IP66', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/outdoor-ip66.svg' },
  { id: 'socket-usb', name: 'USB Socket', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/usb-socket.svg' },
  { id: 'socket-ev-charger', name: 'EV Charger', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/ev-charger.svg' },
  { id: 'socket-tv-aerial', name: 'TV Aerial', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/tv-aerial.svg' },
  { id: 'socket-data', name: 'Data Socket', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/data-socket.svg' },
  { id: 'socket-telephone', name: 'Telephone', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/telephone.svg' },
  { id: 'socket-shaver', name: 'Shaver Socket', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/shaver.svg' },
  { id: 'socket-switched-fused-spur', name: 'Switched Fused Spur', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/switched-fused-spur.svg' },
  { id: 'socket-unswitched-spur', name: 'Unswitched Spur', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/unswitched-spur.svg' },
  { id: 'socket-comms-cabinet', name: 'Comms Cabinet', category: 'sockets', mountType: 'wall', svgPath: '/symbols/sockets/comms-cabinet.svg' },
  // Switches
  { id: 'switch-1way', name: '1-Way Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/1way.svg' },
  { id: 'switch-2way', name: '2-Way Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/2way.svg' },
  { id: 'switch-intermediate', name: 'Intermediate', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/intermediate.svg' },
  { id: 'switch-dimmer', name: 'Dimmer', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/dimmer.svg' },
  { id: 'switch-pull-cord', name: 'Pull Cord', category: 'switches', mountType: 'ceiling', svgPath: '/symbols/switches/pull-cord.svg' },
  { id: 'switch-double', name: 'Double Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/double-switch.svg' },
  { id: 'switch-pir', name: 'PIR Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/pir-switch.svg' },
  { id: 'switch-timer', name: 'Timer Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/timer-switch.svg' },
  { id: 'switch-isolator', name: 'Isolator', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/isolator.svg' },
  { id: 'switch-emergency-stop', name: 'Emergency Stop', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/emergency-stop.svg' },
  { id: 'switch-fan-isolator', name: 'Fan Isolator', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/fan-isolator.svg' },
  { id: 'switch-key', name: 'Key Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/key-switch.svg' },
  { id: 'switch-heater', name: 'Heater Switch', category: 'switches', mountType: 'wall', svgPath: '/symbols/switches/heater-switch.svg' },
  // Distribution
  { id: 'consumer-unit', name: 'Consumer Unit', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/consumer-unit.svg' },
  { id: 'mcb', name: 'MCB', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/mcb.svg' },
  { id: 'rcd', name: 'RCD', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/rcd.svg' },
  { id: 'rcbo', name: 'RCBO', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/rcbo.svg' },
  { id: 'main-isolator', name: 'Main Isolator', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/main-isolator.svg' },
  { id: 'distribution-board', name: 'Distribution Board', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/distribution-board.svg' },
  { id: 'spd', name: 'SPD', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/spd.svg' },
  { id: 'meter', name: 'Meter', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/meter.svg' },
  { id: 'mccb', name: 'MCCB', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/mccb.svg' },
  { id: 'contactor', name: 'Contactor', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/contactor.svg' },
  { id: 'changeover-switch', name: 'Changeover Switch', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/changeover-switch.svg' },
  { id: 'generator-changeover', name: 'Generator Changeover', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/generator-changeover.svg' },
  { id: 'busbar-chamber', name: 'Busbar Chamber', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/busbar-chamber.svg' },
  { id: 'sub-main-board', name: 'Sub-Main Board', category: 'distribution', mountType: 'panel', svgPath: '/symbols/distribution/sub-main-board.svg' },
  // Safety
  { id: 'smoke-detector', name: 'Smoke Detector', category: 'safety', mountType: 'ceiling', svgPath: '/symbols/safety/smoke-detector.svg' },
  { id: 'co-detector', name: 'CO Detector', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/co-detector.svg' },
  { id: 'heat-detector', name: 'Heat Detector', category: 'safety', mountType: 'ceiling', svgPath: '/symbols/safety/heat-detector.svg' },
  { id: 'fire-alarm', name: 'Fire Alarm', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/fire-alarm.svg' },
  { id: 'bell', name: 'Bell', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/bell.svg' },
  { id: 'junction-box', name: 'Junction Box', category: 'safety', mountType: 'ceiling', svgPath: '/symbols/safety/junction-box.svg' },
  { id: 'thermostat', name: 'Thermostat', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/thermostat.svg' },
  { id: 'extractor-fan', name: 'Extractor Fan', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/extractor-fan.svg' },
  { id: 'cctv', name: 'CCTV Camera', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/cctv.svg' },
  { id: 'door-entry', name: 'Door Entry', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/door-entry.svg' },
  { id: 'emergency-call-point', name: 'Emergency Call Point', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/emergency-call-point.svg' },
  { id: 'disabled-alarm', name: 'Disabled Alarm', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/disabled-alarm.svg' },
  { id: 'sounder-beacon', name: 'Sounder Beacon', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/sounder-beacon.svg' },
  { id: 'access-control', name: 'Access Control', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/access-control.svg' },
  { id: 'door-release', name: 'Door Release', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/door-release.svg' },
  { id: 'motion-detector', name: 'Motion Detector', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/motion-detector.svg' },
  { id: 'break-glass', name: 'Break Glass', category: 'safety', mountType: 'wall', svgPath: '/symbols/safety/break-glass.svg' },
  // Architectural
  { id: 'door-left', name: 'Door (Left)', category: 'architectural', mountType: 'wall', svgPath: '/symbols/architectural/door-left.svg' },
  { id: 'door-right', name: 'Door (Right)', category: 'architectural', mountType: 'wall', svgPath: '/symbols/architectural/door-right.svg' },
  { id: 'door-double', name: 'Double Door', category: 'architectural', mountType: 'wall', svgPath: '/symbols/architectural/door-double.svg' },
  { id: 'window', name: 'Window', category: 'architectural', mountType: 'wall', svgPath: '/symbols/architectural/window.svg' },
  { id: 'north-arrow', name: 'North Arrow', category: 'architectural', mountType: 'schematic', svgPath: '/symbols/architectural/north-arrow.svg' },
  { id: 'stairs', name: 'Stairs', category: 'architectural', mountType: 'schematic', svgPath: '/symbols/architectural/stairs.svg' },
  // Mechanical
  { id: 'fan-coil-unit', name: 'Fan Coil Unit', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/fan-coil-unit.svg' },
  { id: 'heater', name: 'Heater', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/heater.svg' },
  { id: 'water-heater', name: 'Water Heater', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/water-heater.svg' },
  { id: 'boiler', name: 'Boiler', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/boiler.svg' },
  { id: 'air-conditioning', name: 'Air Conditioning', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/air-conditioning.svg' },
  { id: 'hand-dryer', name: 'Hand Dryer', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/hand-dryer.svg' },
  { id: 'panel-heater', name: 'Panel Heater', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/panel-heater.svg' },
  { id: 'towel-rail', name: 'Towel Rail', category: 'mechanical', mountType: 'wall', svgPath: '/symbols/mechanical/towel-rail.svg' },
  // Renewables
  { id: 'solar-panel', name: 'Solar Panel', category: 'renewables', mountType: 'schematic', svgPath: '/symbols/renewables/solar-panel.svg' },
  { id: 'inverter', name: 'Inverter', category: 'renewables', mountType: 'wall', svgPath: '/symbols/renewables/inverter.svg' },
  { id: 'battery', name: 'Battery', category: 'renewables', mountType: 'schematic', svgPath: '/symbols/renewables/battery.svg' },
  { id: 'ev-distribution', name: 'EV Distribution', category: 'renewables', mountType: 'panel', svgPath: '/symbols/renewables/ev-distribution.svg' },
  { id: 'generator', name: 'Generator', category: 'renewables', mountType: 'schematic', svgPath: '/symbols/renewables/generator.svg' },
  // Containment
  { id: 'cable-tray', name: 'Cable Tray', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/cable-tray.svg' },
  { id: 'conduit', name: 'Conduit', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/conduit.svg' },
  { id: 'trunking', name: 'Trunking', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/trunking.svg' },
  { id: 'floor-trunking', name: 'Floor Trunking', category: 'containment', mountType: 'floor', svgPath: '/symbols/containment/floor-trunking.svg' },
  { id: 'busbar-trunking', name: 'Busbar Trunking', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/busbar-trunking.svg' },
  { id: 'cable-tray-drop', name: 'Cable Tray Drop', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/cable-tray-drop.svg' },
  { id: 'riser', name: 'Riser', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/riser.svg' },
  { id: 'floor-box-multi', name: 'Multi-Compartment Floor Box', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/floor-box-multi.svg' },
  { id: 'underfloor-trunking', name: 'Underfloor Trunking', category: 'containment', mountType: 'schematic', svgPath: '/symbols/containment/underfloor-trunking.svg' },
  // Equipment
  { id: 'motor', name: 'Motor', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/motor.svg' },
  { id: 'pump', name: 'Pump', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/pump.svg' },
  { id: 'fan', name: 'Fan', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/fan.svg' },
  { id: 'ahu', name: 'Air Handling Unit', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/ahu.svg' },
  { id: 'lift', name: 'Lift', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/lift.svg' },
  { id: 'ups', name: 'UPS', category: 'equipment', mountType: 'panel', svgPath: '/symbols/equipment/ups.svg' },
  { id: 'transformer', name: 'Transformer', category: 'equipment', mountType: 'panel', svgPath: '/symbols/equipment/transformer.svg' },
  { id: 'panel-board', name: 'Panel Board', category: 'equipment', mountType: 'panel', svgPath: '/symbols/equipment/panel-board.svg' },
  { id: 'sub-main', name: 'Sub-Main', category: 'equipment', mountType: 'floor', svgPath: '/symbols/equipment/sub-main.svg' },
  // Controls
  { id: 'bms-controller', name: 'BMS Controller', category: 'controls', mountType: 'wall', svgPath: '/symbols/controls/bms-controller.svg' },
  { id: 'control-panel', name: 'Control Panel', category: 'controls', mountType: 'wall', svgPath: '/symbols/controls/control-panel.svg' },
  { id: 'sensor', name: 'Sensor', category: 'controls', mountType: 'wall', svgPath: '/symbols/controls/sensor.svg' },
  { id: 'humidity-sensor', name: 'Humidity Sensor', category: 'controls', mountType: 'wall', svgPath: '/symbols/controls/humidity-sensor.svg' },
  { id: 'lighting-control', name: 'Lighting Control', category: 'controls', mountType: 'wall', svgPath: '/symbols/controls/lighting-control.svg' },
];

export const categories: { id: SymbolCategory; name: string }[] = [
  { id: 'lighting', name: 'Lighting' },
  { id: 'sockets', name: 'Sockets' },
  { id: 'switches', name: 'Switches' },
  { id: 'distribution', name: 'Distribution' },
  { id: 'safety', name: 'Safety' },
  { id: 'architectural', name: 'Architectural' },
  { id: 'mechanical', name: 'Mechanical' },
  { id: 'renewables', name: 'Renewables' },
  { id: 'containment', name: 'Containment' },
  { id: 'equipment', name: 'Equipment' },
  { id: 'controls', name: 'Controls' },
];
