import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Copy, Download, Mail, MessageSquare, FileText, CheckCircle,
  Sparkles, Send, FileDown
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { generateProfessionalElectricalPDF } from '@/utils/professional-electrical-pdf';
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";

interface OutputPanelProps {
  content: string;
  settings: {
    tone: string;
    readingLevel: string;
    clientType: string;
    includeAnalogy: boolean;
    emphasizeSafety: boolean;
    includeCostInfo: boolean;
  };
}

const OutputPanel = ({ content, settings }: OutputPanelProps) => {
  const { toast } = useToast();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [copied, setCopied] = useState(false);

  const processContentForDisplay = (text: string) => {
    if (!text) return text;

    let cleanText = text.replace(/[ \t]+/g, ' ').trim();

    if (!cleanText.includes('\n\n')) {
      cleanText = cleanText
        .replace(/(\*\*[^*]+\*\*:?)(\s+)(?=[A-Z])/g, '$1\n\n')
        .replace(/([.!?])\s+(?=[A-Z][a-z]+ [A-Z])/g, '$1\n\n')
        .replace(/([.!?])\s+(What |Why |How |Next |This )/g, '$1\n\n$2');
    }

    const sections = cleanText.split(/\n\n+/);

    return sections.map(section => {
      let formatted = section.trim();

      if (!formatted) return '';

      if (/^\*\*.*\*\*:?$/.test(formatted)) {
        const headingText = formatted.replace(/\*\*/g, '').replace(/:$/, '');
        return `<h3 class="text-lg font-bold text-elec-yellow mb-4 mt-6 first:mt-0">${headingText}</h3>`;
      }

      formatted = formatted
        .replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-foreground">$1</strong>')
        .replace(/\*(.*?)\*/g, '<em class="italic text-foreground">$1</em>')
        .replace(/BS 7671/gi, '<span class="text-elec-yellow font-medium">BS 7671</span>')
        .replace(/(\d{3}\.\d+\.\d+)/g, '<span class="text-blue-400 font-mono text-sm">$1</span>')
        .replace(/(C[123]|FI)\b/g, '<span class="px-1.5 py-0.5 rounded bg-red-500/20 text-red-400 text-xs font-semibold">$1</span>');

      if (/^[\d\-\*•]\s/.test(formatted)) {
        const items = formatted.split(/\n/).filter(item => item.trim());
        return '<ul class="space-y-3 mb-6 ml-0 list-none">' +
          items.map(item => {
            const cleanItem = item.replace(/^[\d\-\*•]\s*/, '').trim();
            return `<li class="text-foreground leading-relaxed pl-6 relative before:content-['•'] before:absolute before:left-0 before:text-elec-yellow before:font-bold text-base">${cleanItem}</li>`;
          }).join('') +
          '</ul>';
      }

      return `<p class="text-foreground leading-relaxed mb-6 text-base">${formatted}</p>`;
    }).filter(s => s).join('');
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast({
        title: "Copied",
        description: "Explanation copied to clipboard",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleDownloadTxt = () => {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'client-explanation.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const formattedContent = `
# Client Explanation Document

**Generated Settings:**
- **Tone:** ${settings.tone}
- **Reading Level:** ${settings.readingLevel}
- **Client Type:** ${settings.clientType}

---

## Explanation Content

${content}

---

*Generated by ElecConnect AI Client Explainer Tool*
*Date: ${new Date().toLocaleDateString('en-GB')}*
      `;

      await generateProfessionalElectricalPDF(formattedContent, "Client Explanation", 'client-explanation.pdf', {
        reportType: "Client Explanation",
        companyName: "ElecConnect Professional",
        includeSignatures: false,
        watermark: "CLIENT COMMUNICATION"
      });

      toast({
        title: "Success",
        description: "Professional PDF downloaded successfully",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate professional PDF",
        variant: "destructive"
      });
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleEmailTemplate = () => {
    const subject = encodeURIComponent("Electrical Work Explanation");
    const body = encodeURIComponent(`Dear Client,\n\nPlease find below the explanation of the electrical work findings:\n\n${content}\n\nBest regards,\nYour Electrician`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleSMSTemplate = () => {
    const smsContent = content.length > 160 ? content.substring(0, 157) + "..." : content;
    const smsBody = encodeURIComponent(`Hi, regarding your electrical work: ${smsContent}`);
    window.open(`sms:?body=${smsBody}`);
  };

  const formatForEmail = (content: string) => {
    const cleanContent = content
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/#{1,6}\s/g, '')
      .replace(/[-*+]\s/g, '')
      .replace(/\n\s*\n/g, '\n\n')
      .trim();

    return `Dear Valued Client,

I hope this email finds you well. I wanted to provide you with a clear explanation of the electrical work findings from my recent inspection of your property.

${cleanContent}

If you have any questions about these findings or would like to discuss the work in more detail, please don't hesitate to contact me. I'm here to ensure your electrical system is safe and compliant with current regulations.

Thank you for trusting me with your electrical needs. I look forward to hearing from you soon.

Best regards,

[Your Name]
Qualified Electrician
[Your Contact Details]
[Your Company Name]`;
  };

  const formatForSMS = (content: string) => {
    const shortContent = content.split('.')[0] + '.';
    return `Hi! Quick update on your electrical work: ${shortContent} Call me for more details.`;
  };

  const formatForQuote = (content: string) => {
    return `ELECTRICAL WORK EXPLANATION

${content}

This explanation accompanies our quotation and outlines the work required to address the findings detailed above.

Next Steps:
1. Review this explanation
2. Contact us with any questions
3. Approve the quotation to proceed

Thank you for choosing our electrical services.`;
  };

  // Empty state
  if (!content) {
    return (
      <div className="rounded-2xl border border-border/30 bg-gradient-to-br from-card via-card/95 to-card/90 backdrop-blur-xl p-8 overflow-hidden relative">
        <div className="absolute inset-0 bg-gradient-to-br from-elec-yellow/[0.02] via-transparent to-transparent pointer-events-none" />

        <div className="relative flex flex-col items-center justify-center text-center space-y-4">
          <div className="p-4 rounded-2xl bg-elec-yellow/10 border border-elec-yellow/20">
            <MessageSquare className="h-10 w-10 text-elec-yellow/60" />
          </div>
          <div className="space-y-2">
            <h3 className="text-lg font-semibold text-foreground">Ready to Generate</h3>
            <p className="text-sm text-muted-foreground max-w-sm">
              Your client-friendly explanation will appear here. Available in multiple formats: standard, email, SMS, and quotation.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-border/30 bg-gradient-to-br from-card via-card/95 to-card/90 backdrop-blur-xl overflow-hidden"
    >
      {/* Header */}
      <div className="px-5 py-4 border-b border-border/30 bg-gradient-to-r from-elec-yellow/5 to-transparent">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-elec-yellow/20">
              <Sparkles className="h-5 w-5 text-elec-yellow" />
            </div>
            <div>
              <h2 className="font-bold text-foreground">Generated Explanation</h2>
              <p className="text-xs text-muted-foreground capitalize">{settings.tone} tone • {settings.clientType}</p>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className={cn(
                "h-10 px-4 min-w-[80px] border-border/30 transition-all",
                copied && "bg-green-500/10 border-green-500/30 text-green-400"
              )}
            >
              {copied ? (
                <>
                  <CheckCircle className="h-4 w-4 mr-2" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 mr-2" />
                  Copy
                </>
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadPDF}
              disabled={isGeneratingPDF}
              className="h-10 px-4 border-border/30"
            >
              <FileDown className="h-4 w-4 mr-2" />
              {isGeneratingPDF ? "..." : "PDF"}
            </Button>
          </div>
        </div>
      </div>

      {/* Tabbed Content */}
      <Tabs defaultValue="standard" className="w-full">
        <div className="px-4 pt-4">
          <TabsList className="w-full grid grid-cols-4 h-12 p-1 bg-muted/30 rounded-xl">
            <TabsTrigger
              value="standard"
              className="rounded-lg data-[state=active]:bg-card data-[state=active]:shadow-sm text-sm font-medium min-h-[44px]"
            >
              Standard
            </TabsTrigger>
            <TabsTrigger
              value="email"
              className="rounded-lg data-[state=active]:bg-card data-[state=active]:shadow-sm text-sm font-medium min-h-[44px]"
            >
              Email
            </TabsTrigger>
            <TabsTrigger
              value="sms"
              className="rounded-lg data-[state=active]:bg-card data-[state=active]:shadow-sm text-sm font-medium min-h-[44px]"
            >
              SMS
            </TabsTrigger>
            <TabsTrigger
              value="quote"
              className="rounded-lg data-[state=active]:bg-card data-[state=active]:shadow-sm text-sm font-medium min-h-[44px]"
            >
              Quote
            </TabsTrigger>
          </TabsList>
        </div>

        {/* Standard Tab */}
        <TabsContent value="standard" className="m-0 p-4">
          <div className="rounded-xl bg-background/50 border border-border/30 p-5">
            <div
              className="text-left max-w-none"
              style={{
                fontSize: '16px',
                lineHeight: '1.8',
              }}
              dangerouslySetInnerHTML={{
                __html: processContentForDisplay(content)
              }}
            />
          </div>
        </TabsContent>

        {/* Email Tab */}
        <TabsContent value="email" className="m-0 p-4 space-y-4">
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="text-xs">
              <Mail className="h-3 w-3 mr-1" />
              Email Template
            </Badge>
            <Button
              variant="outline"
              size="sm"
              onClick={handleEmailTemplate}
              className="h-10 border-border/30"
            >
              <Send className="h-4 w-4 mr-2" />
              Open in Email
            </Button>
          </div>

          <div className="rounded-xl bg-background/50 border border-border/30 p-5">
            <div className="space-y-4">
              {formatForEmail(content).split('\n').map((line, index) => (
                <p key={index} className="text-foreground leading-relaxed text-base">
                  {line || <br />}
                </p>
              ))}
            </div>
          </div>
        </TabsContent>

        {/* SMS Tab */}
        <TabsContent value="sms" className="m-0 p-4 space-y-4">
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="text-xs">
              <MessageSquare className="h-3 w-3 mr-1" />
              Text Message
            </Badge>
            <Button
              variant="outline"
              size="sm"
              onClick={handleSMSTemplate}
              className="h-10 border-border/30"
            >
              <Send className="h-4 w-4 mr-2" />
              Send SMS
            </Button>
          </div>

          <div className="rounded-xl bg-background/50 border border-border/30 p-5">
            <p className="text-foreground leading-relaxed text-base" style={{ lineHeight: '1.8' }}>
              {formatForSMS(content)}
            </p>

            <div className="mt-4 pt-3 border-t border-border/30">
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">Character count</span>
                <Badge
                  variant="outline"
                  className={cn(
                    "text-xs",
                    formatForSMS(content).length > 160 ? "text-red-400 border-red-500/30" : "text-green-400 border-green-500/30"
                  )}
                >
                  {formatForSMS(content).length}/160
                </Badge>
              </div>
            </div>
          </div>
        </TabsContent>

        {/* Quote Tab */}
        <TabsContent value="quote" className="m-0 p-4 space-y-4">
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="text-xs">
              <FileText className="h-3 w-3 mr-1" />
              Quotation Format
            </Badge>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadTxt}
              className="h-10 border-border/30"
            >
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>

          <div className="rounded-xl bg-background/50 border border-border/30 p-5">
            <div
              className="text-left max-w-none"
              style={{
                fontSize: '16px',
                lineHeight: '1.8',
              }}
              dangerouslySetInnerHTML={{
                __html: processContentForDisplay(formatForQuote(content))
              }}
            />
          </div>
        </TabsContent>
      </Tabs>
    </motion.div>
  );
};

export default OutputPanel;
