import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Copy, Download, Mail, MessageSquare, FileText, Printer, Share } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface OutputPanelProps {
  content: string;
  settings: {
    tone: string;
    readingLevel: string;
    clientType: string;
    includeAnalogy: boolean;
    emphasizeSafety: boolean;
    includeCostInfo: boolean;
  };
}

const OutputPanel = ({ content, settings }: OutputPanelProps) => {
  const { toast } = useToast();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      toast({
        title: "Copied",
        description: "Explanation copied to clipboard",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleDownloadTxt = () => {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'client-explanation.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const pdf = new jsPDF();
      
      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(255, 193, 7); // elec-yellow
      pdf.text('Client Explanation', 20, 30);
      
      // Settings info
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Tone: ${settings.tone} | Reading Level: ${settings.readingLevel} | Client: ${settings.clientType}`, 20, 45);
      
      // Content
      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);
      const lines = pdf.splitTextToSize(content, 170);
      pdf.text(lines, 20, 60);
      
      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text('Generated by AI Client Explainer Tool', 20, 280);
      pdf.text(new Date().toLocaleDateString(), 170, 280);
      
      pdf.save('client-explanation.pdf');
      
      toast({
        title: "Success",
        description: "PDF downloaded successfully",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate PDF",
        variant: "destructive"
      });
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleEmailTemplate = () => {
    const subject = encodeURIComponent("Electrical Work Explanation");
    const body = encodeURIComponent(`Dear Client,\n\nPlease find below the explanation of the electrical work findings:\n\n${content}\n\nBest regards,\nYour Electrician`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleSMSTemplate = () => {
    const smsContent = content.length > 160 ? content.substring(0, 157) + "..." : content;
    const smsBody = encodeURIComponent(`Hi, regarding your electrical work: ${smsContent}`);
    window.open(`sms:?body=${smsBody}`);
  };

  const formatForEmail = (content: string) => {
    return `Dear Client,

Please find below the explanation of our electrical findings:

${content}

If you have any questions about this explanation, please don't hesitate to contact me.

Best regards,
Your Electrician`;
  };

  const formatForSMS = (content: string) => {
    // SMS version - much shorter
    const shortContent = content.split('.')[0] + '.';
    return `Hi! Quick update on your electrical work: ${shortContent} Call me for more details.`;
  };

  const formatForQuote = (content: string) => {
    return `ELECTRICAL WORK EXPLANATION

${content}

This explanation accompanies our quotation and outlines the work required to address the findings detailed above.

Next Steps:
1. Review this explanation
2. Contact us with any questions
3. Approve the quotation to proceed

Thank you for choosing our electrical services.`;
  };

  return (
    <Card className="border-border/50 bg-card/50">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <MessageSquare className="h-4 w-4 text-elec-yellow" />
            <CardTitle className="text-lg">Client-Friendly Output</CardTitle>
          </div>
          {content && (
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopy}
                className="border-border/50 hover:bg-card"
              >
                <Copy className="h-4 w-4 mr-1" />
                Copy
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadPDF}
                disabled={isGeneratingPDF}
                className="border-border/50 hover:bg-card"
              >
                <Download className="h-4 w-4 mr-1" />
                {isGeneratingPDF ? "Generating..." : "PDF"}
              </Button>
            </div>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {content ? (
          <>
            {/* Settings display */}
            <div className="flex flex-wrap gap-2 mb-4">
              <Badge variant="outline" className="border-elec-yellow/30 text-elec-yellow bg-elec-yellow/5">
                {settings.tone}
              </Badge>
              <Badge variant="outline" className="border-blue-400/30 text-blue-400 bg-blue-400/5">
                {settings.readingLevel}
              </Badge>
              <Badge variant="outline" className="border-purple-400/30 text-purple-400 bg-purple-400/5">
                {settings.clientType}
              </Badge>
              {settings.includeAnalogy && (
                <Badge variant="outline" className="border-green-400/30 text-green-400 bg-green-400/5">
                  analogies
                </Badge>
              )}
              {settings.emphasizeSafety && (
                <Badge variant="outline" className="border-red-400/30 text-red-400 bg-red-400/5">
                  safety focus
                </Badge>
              )}
              {settings.includeCostInfo && (
                <Badge variant="outline" className="border-orange-400/30 text-orange-400 bg-orange-400/5">
                  cost info
                </Badge>
              )}
            </div>

            {/* Output formats */}
            <Tabs defaultValue="standard" className="w-full">
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="standard">Standard</TabsTrigger>
                <TabsTrigger value="email">Email</TabsTrigger>
                <TabsTrigger value="sms">SMS</TabsTrigger>
                <TabsTrigger value="quote">Quote</TabsTrigger>
              </TabsList>
              
              <TabsContent value="standard" className="mt-4">
                <div className="bg-muted/30 border border-border/50 rounded-lg p-4">
                  <div className="whitespace-pre-wrap text-sm leading-relaxed">
                    {content}
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="email" className="mt-4">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <h4 className="text-sm font-medium">Email Template</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleEmailTemplate}
                      className="text-xs"
                    >
                      <Mail className="h-3 w-3 mr-1" />
                      Open in Email
                    </Button>
                  </div>
                  <div className="bg-muted/30 border border-border/50 rounded-lg p-4">
                    <div className="whitespace-pre-wrap text-sm leading-relaxed">
                      {formatForEmail(content)}
                    </div>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="sms" className="mt-4">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <h4 className="text-sm font-medium">SMS Version</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleSMSTemplate}
                      className="text-xs"
                    >
                      <MessageSquare className="h-3 w-3 mr-1" />
                      Send SMS
                    </Button>
                  </div>
                  <div className="bg-muted/30 border border-border/50 rounded-lg p-4">
                    <div className="whitespace-pre-wrap text-sm leading-relaxed">
                      {formatForSMS(content)}
                    </div>
                    <div className="mt-2 text-xs text-muted-foreground">
                      Character count: {formatForSMS(content).length}/160
                    </div>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="quote" className="mt-4">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <h4 className="text-sm font-medium">Quotation Format</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleDownloadTxt}
                      className="text-xs"
                    >
                      <FileText className="h-3 w-3 mr-1" />
                      Download
                    </Button>
                  </div>
                  <div className="bg-muted/30 border border-border/50 rounded-lg p-4">
                    <div className="whitespace-pre-wrap text-sm leading-relaxed">
                      {formatForQuote(content)}
                    </div>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </>
        ) : (
          <div className="bg-muted/30 border border-border/50 rounded-lg p-8 text-center">
            <MessageSquare className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">
              Generated explanation will appear here with multiple format options
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default OutputPanel;