import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Copy, Download, Mail, MessageSquare, FileText, Printer, Share } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { generateProfessionalElectricalPDF } from '@/utils/professional-electrical-pdf';

interface OutputPanelProps {
  content: string;
  settings: {
    tone: string;
    readingLevel: string;
    clientType: string;
    includeAnalogy: boolean;
    emphasizeSafety: boolean;
    includeCostInfo: boolean;
  };
}

const OutputPanel = ({ content, settings }: OutputPanelProps) => {
  const { toast } = useToast();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  // Process content for better mobile rendering
const processContentForDisplay = (text: string) => {
  if (!text) return text;
  
  // Normalize whitespace but preserve intentional breaks
  let cleanText = text.replace(/[ \t]+/g, ' ').trim();
  
  // If AI didn't add double line breaks, try to detect paragraph boundaries
  // Look for section headers or sentence endings followed by capitals
  if (!cleanText.includes('\n\n')) {
    cleanText = cleanText
      .replace(/(\*\*[^*]+\*\*:?)(\s+)(?=[A-Z])/g, '$1\n\n')  // Break after headers
      .replace(/([.!?])\s+(?=[A-Z][a-z]+ [A-Z])/g, '$1\n\n')  // Break between major sentences
      .replace(/([.!?])\s+(What |Why |How |Next |This )/g, '$1\n\n$2');  // Break before key phrases
  }
  
  // Split by double line breaks to preserve paragraph structure
  const sections = cleanText.split(/\n\n+/);
  
  return sections.map(section => {
    let formatted = section.trim();
    
    if (!formatted) return '';
    
    // Check if it's a heading (starts with ** and ends with : or **)
    if (/^\*\*.*\*\*:?$/.test(formatted)) {
      const headingText = formatted.replace(/\*\*/g, '').replace(/:$/, '');
      return `<h3 class="text-lg font-bold text-elec-yellow mb-4 mt-6 first:mt-0">${headingText}</h3>`;
    }
    
    // Format inline styling - ENSURE white text for body content
    formatted = formatted
      .replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-foreground">$1</strong>')
      .replace(/\*(.*?)\*/g, '<em class="italic text-foreground">$1</em>')
      .replace(/BS 7671/gi, '<span class="text-elec-yellow font-medium">BS 7671</span>')
      .replace(/(\d{3}\.\d+\.\d+)/g, '<span class="text-blue-400 font-mono text-sm">$1</span>')
      .replace(/(C[123]|FI)\b/g, '<span class="px-1.5 py-0.5 rounded bg-red-500/20 text-red-400 text-xs font-semibold">$1</span>');
    
    // Check if it's a numbered or bulleted list
    if (/^[\d\-\*•]\s/.test(formatted)) {
      const items = formatted.split(/\n/).filter(item => item.trim());
      return '<ul class="space-y-3 mb-6 ml-0 list-none">' + 
        items.map(item => {
          const cleanItem = item.replace(/^[\d\-\*•]\s*/, '').trim();
          return `<li class="text-foreground leading-relaxed pl-6 relative before:content-['•'] before:absolute before:left-0 before:text-elec-yellow before:font-bold text-base">${cleanItem}</li>`;
        }).join('') + 
      '</ul>';
    }
    
    // Otherwise render as paragraph with WHITE text
    return `<p class="text-foreground leading-relaxed mb-6 text-base">${formatted}</p>`;
  }).filter(s => s).join('');
};

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      toast({
        title: "Copied",
        description: "Explanation copied to clipboard",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleDownloadTxt = () => {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'client-explanation.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      // Format content for professional PDF generation
      const formattedContent = `
# Client Explanation Document

**Generated Settings:**
- **Tone:** ${settings.tone}
- **Reading Level:** ${settings.readingLevel}
- **Client Type:** ${settings.clientType}

---

## Explanation Content

${content}

---

*Generated by ElecConnect AI Client Explainer Tool*
*Date: ${new Date().toLocaleDateString('en-GB')}*
      `;
      
      await generateProfessionalElectricalPDF(formattedContent, "Client Explanation", 'client-explanation.pdf', {
        reportType: "Client Explanation",
        companyName: "ElecConnect Professional",
        includeSignatures: false,
        watermark: "CLIENT COMMUNICATION"
      });
      
      toast({
        title: "Success",
        description: "Professional PDF downloaded successfully",
        variant: "success"
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate professional PDF",
        variant: "destructive"
      });
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleEmailTemplate = () => {
    const subject = encodeURIComponent("Electrical Work Explanation");
    const body = encodeURIComponent(`Dear Client,\n\nPlease find below the explanation of the electrical work findings:\n\n${content}\n\nBest regards,\nYour Electrician`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleSMSTemplate = () => {
    const smsContent = content.length > 160 ? content.substring(0, 157) + "..." : content;
    const smsBody = encodeURIComponent(`Hi, regarding your electrical work: ${smsContent}`);
    window.open(`sms:?body=${smsBody}`);
  };

  const formatForEmail = (content: string) => {
    // Clean content by removing markdown formatting
    const cleanContent = content
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/#{1,6}\s/g, '')
      .replace(/[-*+]\s/g, '')
      .replace(/\n\s*\n/g, '\n\n')
      .trim();

    return `Dear Valued Client,

I hope this email finds you well. I wanted to provide you with a clear explanation of the electrical work findings from my recent inspection of your property.

${cleanContent}

If you have any questions about these findings or would like to discuss the work in more detail, please don't hesitate to contact me. I'm here to ensure your electrical system is safe and compliant with current regulations.

Thank you for trusting me with your electrical needs. I look forward to hearing from you soon.

Best regards,

[Your Name]
Qualified Electrician
[Your Contact Details]
[Your Company Name]`;
  };

  const formatForSMS = (content: string) => {
    // SMS version - much shorter
    const shortContent = content.split('.')[0] + '.';
    return `Hi! Quick update on your electrical work: ${shortContent} Call me for more details.`;
  };

  const formatForQuote = (content: string) => {
    return `ELECTRICAL WORK EXPLANATION

${content}

This explanation accompanies our quotation and outlines the work required to address the findings detailed above.

Next Steps:
1. Review this explanation
2. Contact us with any questions
3. Approve the quotation to proceed

Thank you for choosing our electrical services.`;
  };

  return (
    <Card className="mobile-card border-border/50 bg-card/50">
      <CardHeader className="p-0 pb-3">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div className="flex items-center space-x-2">
            <MessageSquare className="h-5 w-5 text-elec-yellow" />
            <CardTitle className="mobile-heading text-foreground">Client Explanation</CardTitle>
          </div>
          {content && (
            <div className="flex gap-2 w-full sm:w-auto">
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopy}
                className="mobile-button-secondary flex-1 sm:flex-none touch-target border-border/50 hover:bg-card text-foreground"
              >
                <Copy className="h-4 w-4 mr-1" />
                Copy
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadPDF}
                disabled={isGeneratingPDF}
                className="mobile-button-secondary flex-1 sm:flex-none touch-target border-border/50 hover:bg-card text-foreground"
              >
                <Download className="h-4 w-4 mr-1" />
                {isGeneratingPDF ? "Creating..." : "PDF"}
              </Button>
            </div>
          )}
        </div>
      </CardHeader>
      <CardContent className="p-0 space-y-4">
        {content ? (
          <>
            {/* Output formats */}
            <Tabs defaultValue="standard" className="w-full">
              <TabsList className="mobile-grid-responsive grid w-full grid-cols-2 sm:grid-cols-4 h-auto">
                <TabsTrigger value="standard" className="mobile-tap-highlight touch-target text-xs sm:text-sm px-2">
                  Explanation
                </TabsTrigger>
                <TabsTrigger value="email" className="mobile-tap-highlight touch-target text-xs sm:text-sm">
                  Email
                </TabsTrigger>
                <TabsTrigger value="sms" className="mobile-tap-highlight touch-target text-xs sm:text-sm">
                  Text/SMS
                </TabsTrigger>
                <TabsTrigger value="quote" className="mobile-tap-highlight touch-target text-xs sm:text-sm">
                  Quote
                </TabsTrigger>
              </TabsList>
              
              <TabsContent value="standard" className="mt-4">
                <div className="mobile-card bg-muted/30 border border-border/50 rounded-lg p-4 sm:p-6">
                  <div 
                    className="text-left max-w-none prose prose-invert"
                    style={{ 
                      fontSize: '16px',
                      lineHeight: '1.8',
                      fontFamily: 'system-ui, -apple-system, sans-serif',
                      color: 'white'
                    }}
                    dangerouslySetInnerHTML={{ 
                      __html: processContentForDisplay(content)
                    }}
                  />
                </div>
              </TabsContent>
              
              <TabsContent value="email" className="mt-4">
                <div className="space-y-3">
                  <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                    <h4 className="mobile-small-text font-medium text-foreground">Email Template</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleEmailTemplate}
                      className="mobile-button-secondary touch-target w-full sm:w-auto"
                    >
                      <Mail className="h-4 w-4 mr-1" />
                      Open in Email App
                    </Button>
                  </div>
                  <div className="mobile-card bg-muted/30 border border-border/50 rounded-lg p-4 sm:p-6">
                    <div 
                      className="text-left max-w-none"
                      style={{ 
                        fontSize: '16px',
                        lineHeight: '1.8',
                        fontFamily: 'system-ui, -apple-system, sans-serif',
                        color: 'white'
                      }}
                    >
                      {formatForEmail(content).split('\n').map((line, index) => (
                        <p key={index} className="mb-4 leading-relaxed text-foreground">{line}</p>
                      ))}
                    </div>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="sms" className="mt-4">
                <div className="space-y-3">
                  <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                    <h4 className="mobile-small-text font-medium text-foreground">Text Message Version</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleSMSTemplate}
                      className="mobile-button-secondary touch-target w-full sm:w-auto"
                    >
                      <MessageSquare className="h-4 w-4 mr-1" />
                      Send Text Message
                    </Button>
                  </div>
                  <div className="mobile-card bg-muted/30 border border-border/50 rounded-lg p-4 sm:p-6">
                    <p className="text-foreground leading-relaxed text-base" style={{ lineHeight: '1.8' }}>
                      {formatForSMS(content)}
                    </p>
                    <div className="mt-3 text-xs text-foreground/70 bg-muted/20 rounded px-2 py-1">
                      Characters: {formatForSMS(content).length}/160
                    </div>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="quote" className="mt-4">
                <div className="space-y-3">
                  <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                    <h4 className="mobile-small-text font-medium text-foreground">Quotation Format</h4>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleDownloadTxt}
                      className="mobile-button-secondary touch-target w-full sm:w-auto"
                    >
                      <FileText className="h-4 w-4 mr-1" />
                      Download Document
                    </Button>
                  </div>
                  <div className="mobile-card bg-muted/30 border border-border/50 rounded-lg p-4 sm:p-6">
                    <div 
                      className="text-left max-w-none prose prose-invert"
                      style={{ 
                        fontSize: '16px',
                        lineHeight: '1.8',
                        fontFamily: 'system-ui, -apple-system, sans-serif',
                        color: 'white'
                      }}
                      dangerouslySetInnerHTML={{ 
                        __html: processContentForDisplay(formatForQuote(content))
                      }}
                    />
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </>
        ) : (
          <div className="mobile-card bg-muted/30 border border-border/50 rounded-lg p-8 text-center">
            <MessageSquare className="h-12 w-12 text-foreground/50 mx-auto mb-4" />
            <div className="space-y-2">
              <p className="mobile-text text-foreground">
                Your client-friendly explanation will appear here
              </p>
              <p className="mobile-small-text text-foreground/70">
                Available in multiple formats: standard explanation, email template, text message, and quotation format
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default OutputPanel;