
import React from "react";
import { Button } from "@/components/ui/button";
import { CheckCircle, Zap, Flame, Thermometer } from "lucide-react";

interface Subsection8_2Props {
  subsectionId: string;
  isCompleted: boolean;
  markAsComplete: () => void;
}

const Subsection8_2 = ({ subsectionId, isCompleted, markAsComplete }: Subsection8_2Props) => {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-elec-yellow">Protection Against Thermal Effects</h2>
      
      <div className="space-y-4">
        <p>
          Electrical installations must provide protection against fire, burns, and other thermal effects.
          BS 7671 Chapter 42 specifies requirements to prevent damage from heat generated by electrical equipment.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
          <div className="bg-elec-dark/50 border border-elec-yellow/30 rounded-lg p-6 space-y-4">
            <h3 className="text-xl font-bold text-elec-yellow flex items-center">
              <Flame className="h-5 w-5 mr-2" />
              Fire Protection
            </h3>
            <div className="space-y-3">
              <h4 className="font-semibold">Protection Against Fire Ignition</h4>
              <ul className="list-disc pl-5 space-y-2">
                <li>Equipment to be installed according to manufacturer instructions</li>
                <li>Fixed equipment with high surface temperatures restricted in hazardous areas</li>
                <li>Heat-producing equipment mounted on non-combustible surfaces</li>
                <li>Prevention of equipment and wiring installation that promotes flame spread</li>
                <li>Enhanced protection in locations with fire risk (AFDD recommended)</li>
              </ul>
              
              <h4 className="font-semibold mt-4">Installation in Fire-Risk Locations</h4>
              <ul className="list-disc pl-5 space-y-2">
                <li>Minimize equipment in escape routes</li>
                <li>Use of fire-resistant barriers and seals</li>
                <li>Specific cable types with fire-resistant properties</li>
                <li>Fire detection and emergency systems</li>
                <li>Special isolation arrangements for firefighting operations</li>
              </ul>
              
              <div className="mt-4 pt-4 border-t border-elec-yellow/20">
                <h4 className="font-semibold text-elec-yellow mb-2">Arc Fault Detection Devices (AFDDs):</h4>
                <ul className="list-disc pl-5 space-y-1">
                  <li>Detection of series and parallel arcing</li>
                  <li>Recommended for circuits supplying locations with high fire risk</li>
                  <li>Sleeping accommodations and locations with combustible materials</li>
                  <li>Historic buildings and premises with irreplaceable assets</li>
                  <li>Wood-frame buildings and other vulnerable structures</li>
                </ul>
              </div>
            </div>
          </div>
          
          <div className="bg-elec-dark/50 border border-elec-yellow/30 rounded-lg p-6 space-y-4">
            <h3 className="text-xl font-bold text-elec-yellow flex items-center">
              <Thermometer className="h-5 w-5 mr-2" />
              Thermal Considerations
            </h3>
            <div className="space-y-3">
              <h4 className="font-semibold">Temperature Limitations</h4>
              <ul className="list-disc pl-5 space-y-2">
                <li>Maximum operating temperatures for insulation materials</li>
                <li>Temperature ratings of cables and equipment</li>
                <li>Derating factors for ambient temperature</li>
                <li>Thermal constraints in grouped installations</li>
                <li>Heat dissipation in enclosed equipment</li>
              </ul>
              
              <h4 className="font-semibold mt-4">Protection Against Burns</h4>
              <ul className="list-disc pl-5 space-y-2">
                <li>Parts accessible to touch limited to specific temperatures</li>
                <li>Guards for equipment with hot surfaces</li>
                <li>Warning signs for hot surfaces</li>
                <li>Protection against hot water pipes adjacent to cables</li>
                <li>Adequate spacing from heat sources</li>
              </ul>
              
              <div className="mt-4 pt-4 border-t border-elec-yellow/20">
                <h4 className="font-semibold text-elec-yellow mb-2">External Influence Factors:</h4>
                <ul className="list-disc pl-5 space-y-1">
                  <li>Solar radiation effects on equipment and cables</li>
                  <li>Equipment in heated environments (boiler rooms, etc.)</li>
                  <li>Thermal insulation proximity considerations</li>
                  <li>Cable bundles and de-rating requirements</li>
                  <li>Ventilation requirements for heat-producing equipment</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        
        <div className="mt-8 bg-elec-dark/30 border border-elec-yellow/20 rounded-lg p-6">
          <h3 className="text-xl font-bold text-elec-yellow mb-4 flex items-center">
            <Zap className="h-5 w-5 mr-2" />
            Overcurrent Protection Design
          </h3>
          
          <div className="space-y-4">
            <p>Proper selection and coordination of overcurrent protection is critical for thermal protection:</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-3">
                <h4 className="font-semibold text-white">Protection Against Overload</h4>
                <ul className="list-disc pl-5 space-y-2">
                  <li>
                    <span className="font-medium">Protective device rating (In)</span>
                    <p className="text-sm mt-1">Selected based on design current (Ib) and cable rating (Iz)</p>
                  </li>
                  <li>
                    <span className="font-medium">Coordination condition</span>
                    <p className="text-sm mt-1">Ib ≤ In ≤ Iz (design current ≤ device rating ≤ cable rating)</p>
                  </li>
                  <li>
                    <span className="font-medium">Thermal protection of motors</span>
                    <p className="text-sm mt-1">Overload protection appropriate to starting characteristics</p>
                  </li>
                  <li>
                    <span className="font-medium">Diversity factors</span>
                    <p className="text-sm mt-1">Application to reduce overall cable/device size requirements</p>
                  </li>
                </ul>
              </div>
              
              <div className="space-y-3">
                <h4 className="font-semibold text-white">Protection Against Short-Circuit</h4>
                <ul className="list-disc pl-5 space-y-2">
                  <li>
                    <span className="font-medium">Breaking capacity</span>
                    <p className="text-sm mt-1">Must exceed maximum prospective short-circuit current</p>
                  </li>
                  <li>
                    <span className="font-medium">Fault energy limitation</span>
                    <p className="text-sm mt-1">I²t value less than cable thermal withstand capacity</p>
                  </li>
                  <li>
                    <span className="font-medium">Coordination types</span>
                    <p className="text-sm mt-1">Type 1 or Type 2 coordination for motor circuits</p>
                  </li>
                  <li>
                    <span className="font-medium">Selectivity considerations</span>
                    <p className="text-sm mt-1">Ensuring only affected circuit protection operates</p>
                  </li>
                </ul>
              </div>
            </div>
            
            <div className="mt-4 p-4 bg-elec-dark/70 rounded-lg text-sm">
              <p className="font-medium mb-1 text-elec-yellow">Regulatory Note:</p>
              <p>BS 7671 Section 421 requires that people, fixed equipment, and fixed materials near electrical equipment must be protected against harmful effects of heat or thermal radiation. This includes protection against burns, fire, and ignition. Sections 422 and 423 deal with locations with fire risk and combustible construction materials.</p>
            </div>
          </div>
        </div>
      </div>
      
      <div className="flex justify-end pt-6 border-t border-elec-yellow/20">
        <Button
          variant="study"
          className={`${isCompleted ? 'bg-green-600/20 border-green-500/50 text-green-400' : 'hover:bg-elec-yellow hover:text-elec-dark'}`}
          onClick={markAsComplete}
          disabled={isCompleted}
        >
          {isCompleted ? 'Completed' : 'Mark as Complete'}
          {isCompleted && <CheckCircle className="ml-2 h-4 w-4" />}
        </Button>
      </div>
    </div>
  );
};

export default Subsection8_2;
