import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FileText, Download, Sparkles, BookOpen, Settings2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { generateLaTeXStylePDF, sampleMarkdown } from '@/utils/professional-latex-style-pdf';

const LaTeXStylePDFGenerator = () => {
  const { toast } = useToast();
  const [markdownContent, setMarkdownContent] = useState(sampleMarkdown);
  const [title, setTitle] = useState('Professional Document');
  const [author, setAuthor] = useState('Generated by Lovable');
  const [subject, setSubject] = useState('Professional Document');
  const [keywords, setKeywords] = useState('professional, document, pdf');
  const [includeTableOfContents, setIncludeTableOfContents] = useState(true);
  const [fontFamily, setFontFamily] = useState<'serif' | 'sans-serif' | 'monospace'>('serif');
  const [fontSize, setFontSize] = useState(11);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGeneratePDF = async () => {
    if (!markdownContent.trim()) {
      toast({
        title: "Content Required",
        description: "Please provide markdown content to generate the PDF.",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);

    try {
      await generateLaTeXStylePDF(markdownContent, undefined, {
        title,
        author,
        subject,
        keywords,
        includeTableOfContents,
        fontFamily,
        fontSize,
        margins: { top: 25, right: 20, bottom: 25, left: 20 }
      });

      toast({
        title: "PDF Generated Successfully! ✨",
        description: "Your professional LaTeX-style PDF has been downloaded with beautiful formatting.",
      });
    } catch (error) {
      console.error('PDF generation error:', error);
      toast({
        title: "PDF Generation Failed",
        description: "There was an error generating your professional PDF. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const loadSampleContent = () => {
    setMarkdownContent(sampleMarkdown);
    setTitle('Professional Document Template');
    setAuthor('Lovable PDF Generator');
    setSubject('LaTeX-Style Professional Document');
    setKeywords('professional, latex, document, pdf, markdown');
    
    toast({
      title: "Sample Content Loaded ✨",
      description: "Beautiful sample markdown content has been loaded for you to try.",
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="flex items-center justify-center gap-3">
            <div className="bg-gradient-to-br from-blue-600 to-purple-600 p-3 rounded-xl">
              <FileText className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              LaTeX-Style PDF Generator
            </h1>
          </div>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Transform your Markdown into stunning, professional PDFs with LaTeX-quality typography and formatting. 
            Perfect for academic papers, business reports, and professional documentation.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {/* Content Input */}
          <Card className="shadow-xl border-0 bg-white/70 backdrop-blur-sm">
            <CardHeader className="bg-gradient-to-r from-blue-500 to-purple-500 text-white">
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="h-5 w-5" />
                Markdown Content
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 space-y-4">
              <div className="flex gap-2">
                <Button
                  onClick={loadSampleContent}
                  variant="outline"
                  size="sm"
                  className="border-blue-200 text-blue-600 hover:bg-blue-50"
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Load Sample
                </Button>
              </div>
              
              <Textarea
                value={markdownContent}
                onChange={(e) => setMarkdownContent(e.target.value)}
                placeholder="# Your Amazing Document

## Introduction
Write your content in Markdown format...

- Beautiful formatting
- Professional typography  
- LaTeX-quality output"
                className="min-h-[400px] font-mono text-sm border-slate-200 focus:border-blue-400 focus:ring-blue-400"
              />
            </CardContent>
          </Card>

          {/* Settings Panel */}
          <Card className="shadow-xl border-0 bg-white/70 backdrop-blur-sm">
            <CardHeader className="bg-gradient-to-r from-purple-500 to-pink-500 text-white">
              <CardTitle className="flex items-center gap-2">
                <Settings2 className="h-5 w-5" />
                Document Settings
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 space-y-6">
              {/* Document Metadata */}
              <div className="space-y-4">
                <h3 className="font-semibold text-slate-800 border-b border-slate-200 pb-2">
                  Document Information
                </h3>
                
                <div className="space-y-3">
                  <div>
                    <Label htmlFor="title" className="text-sm font-medium text-slate-700">
                      Document Title
                    </Label>
                    <Input
                      id="title"
                      value={title}
                      onChange={(e) => setTitle(e.target.value)}
                      placeholder="Professional Document"
                      className="border-slate-200 focus:border-purple-400 focus:ring-purple-400"
                    />
                  </div>
                  
                  <div>
                    <Label htmlFor="author" className="text-sm font-medium text-slate-700">
                      Author
                    </Label>
                    <Input
                      id="author"
                      value={author}
                      onChange={(e) => setAuthor(e.target.value)}
                      placeholder="Your Name"
                      className="border-slate-200 focus:border-purple-400 focus:ring-purple-400"
                    />
                  </div>
                  
                  <div>
                    <Label htmlFor="subject" className="text-sm font-medium text-slate-700">
                      Subject
                    </Label>
                    <Input
                      id="subject"
                      value={subject}
                      onChange={(e) => setSubject(e.target.value)}
                      placeholder="Document subject"
                      className="border-slate-200 focus:border-purple-400 focus:ring-purple-400"
                    />
                  </div>
                  
                  <div>
                    <Label htmlFor="keywords" className="text-sm font-medium text-slate-700">
                      Keywords
                    </Label>
                    <Input
                      id="keywords"
                      value={keywords}
                      onChange={(e) => setKeywords(e.target.value)}
                      placeholder="keyword1, keyword2, keyword3"
                      className="border-slate-200 focus:border-purple-400 focus:ring-purple-400"
                    />
                  </div>
                </div>
              </div>

              {/* Typography Settings */}
              <div className="space-y-4">
                <h3 className="font-semibold text-slate-800 border-b border-slate-200 pb-2">
                  Typography & Layout
                </h3>
                
                <div className="space-y-3">
                  <div>
                    <Label htmlFor="fontFamily" className="text-sm font-medium text-slate-700">
                      Font Family
                    </Label>
                    <Select value={fontFamily} onValueChange={(value: 'serif' | 'sans-serif' | 'monospace') => setFontFamily(value)}>
                      <SelectTrigger className="border-slate-200 focus:border-purple-400 focus:ring-purple-400">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="serif">Serif (Times) - Academic</SelectItem>
                        <SelectItem value="sans-serif">Sans Serif (Helvetica) - Modern</SelectItem>
                        <SelectItem value="monospace">Monospace (Courier) - Technical</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  
                  <div>
                    <Label htmlFor="fontSize" className="text-sm font-medium text-slate-700">
                      Font Size: {fontSize}pt
                    </Label>
                    <input
                      type="range"
                      min="9"
                      max="14"
                      step="1"
                      value={fontSize}
                      onChange={(e) => setFontSize(Number(e.target.value))}
                      className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer slider"
                    />
                    <div className="flex justify-between text-xs text-slate-500 mt-1">
                      <span>9pt</span>
                      <span>11pt</span>
                      <span>14pt</span>
                    </div>
                  </div>
                  
                  <div className="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
                    <div>
                      <Label htmlFor="toc" className="text-sm font-medium text-slate-700">
                        Table of Contents
                      </Label>
                      <p className="text-xs text-slate-500">
                        Automatically generate a TOC from headings
                      </p>
                    </div>
                    <Switch
                      id="toc"
                      checked={includeTableOfContents}
                      onCheckedChange={setIncludeTableOfContents}
                    />
                  </div>
                </div>
              </div>

              {/* Generate Button */}
              <Button
                onClick={handleGeneratePDF}
                disabled={isGenerating || !markdownContent.trim()}
                className="w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-semibold py-3 rounded-lg shadow-lg hover:shadow-xl transition-all duration-200"
                size="lg"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                    Crafting Beautiful PDF...
                  </>
                ) : (
                  <>
                    <Download className="h-5 w-5 mr-2" />
                    Generate LaTeX-Style PDF
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* Features */}
        <Card className="shadow-xl border-0 bg-white/70 backdrop-blur-sm">
          <CardContent className="p-6">
            <h3 className="text-xl font-bold text-slate-800 mb-4 text-center">
              ✨ Professional Features Included
            </h3>
            <div className="grid md:grid-cols-3 gap-6">
              <div className="text-center space-y-2">
                <div className="bg-blue-100 p-3 rounded-full w-fit mx-auto">
                  <FileText className="h-6 w-6 text-blue-600" />
                </div>
                <h4 className="font-semibold text-slate-800">LaTeX-Quality Typography</h4>
                <p className="text-sm text-slate-600">Professional fonts, spacing, and layout that rivals academic publications</p>
              </div>
              <div className="text-center space-y-2">
                <div className="bg-purple-100 p-3 rounded-full w-fit mx-auto">
                  <BookOpen className="h-6 w-6 text-purple-600" />
                </div>
                <h4 className="font-semibold text-slate-800">Automatic TOC Generation</h4>
                <p className="text-sm text-slate-600">Beautiful table of contents with page numbers and navigation</p>
              </div>
              <div className="text-center space-y-2">
                <div className="bg-pink-100 p-3 rounded-full w-fit mx-auto">
                  <Sparkles className="h-6 w-6 text-pink-600" />
                </div>
                <h4 className="font-semibold text-slate-800">Professional Polish</h4>
                <p className="text-sm text-slate-600">Headers, footers, page numbers, and elegant title pages</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      
      <style>{`
        .slider::-webkit-slider-thumb {
          appearance: none;
          height: 20px;
          width: 20px;
          border-radius: 50%;
          background: linear-gradient(135deg, #3b82f6, #8b5cf6);
          cursor: pointer;
          box-shadow: 0 2px 6px rgba(0,0,0,0.2);
        }
        
        .slider::-moz-range-thumb {
          height: 20px;
          width: 20px;
          border-radius: 50%;
          background: linear-gradient(135deg, #3b82f6, #8b5cf6);
          cursor: pointer;
          border: none;
          box-shadow: 0 2px 6px rgba(0,0,0,0.2);
        }
      `}</style>
    </div>
  );
};

export default LaTeXStylePDFGenerator;