services:
  elec-pipeline:
    build: .
    container_name: elec-pipeline
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3002:3002"
    env_file:
      - .env.pipeline
    environment:
      - TZ=Europe/London
    shm_size: '1g'
    deploy:
      resources:
        limits:
          memory: 4G
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
