import {
  LayoutDashboard,
  GraduationCap,
  Zap,
  BookOpen,
  Heart,
  Calculator,
  FileText,
  Users,
  Receipt,
  FolderKanban,
  ListTodo,
  ShieldCheck,
  PenTool,
  ClipboardCheck,
  Sparkles,
  Search,
  CreditCard,
  Bell,
  Gift,
  User,
  Settings,
  Briefcase,
  Wrench,
  TrendingUp,
  Calendar,
  Camera,
  HardHat,
  Bot,
  Flame,
  BatteryCharging,
  Sun,
  Plug,
  Shield,
  Video,
  Notebook,
  Award,
  Scale,
  Banknote,
  Package,
  Clock,
  MessageSquare,
  FileCheck,
  type LucideIcon,
} from 'lucide-react';

export interface SearchablePage {
  name: string;
  path: string;
  keywords: string[];
  icon: LucideIcon;
  category: string;
}

export const searchablePages: SearchablePage[] = [
  // ──── Hubs ────
  {
    name: 'Dashboard',
    path: '/dashboard',
    keywords: ['home', 'overview', 'main'],
    icon: LayoutDashboard,
    category: 'Hubs',
  },
  {
    name: 'Apprentice Hub',
    path: '/apprentice',
    keywords: ['apprentice', 'training', 'level 2', 'level 3'],
    icon: GraduationCap,
    category: 'Hubs',
  },
  {
    name: 'Electrical Hub',
    path: '/electrician',
    keywords: ['electrical', 'electrician', 'hub'],
    icon: Zap,
    category: 'Hubs',
  },
  {
    name: 'Study Centre',
    path: '/study-centre',
    keywords: ['study', 'learn', 'courses', 'education'],
    icon: BookOpen,
    category: 'Hubs',
  },
  {
    name: 'Mental Health',
    path: '/mental-health',
    keywords: ['wellbeing', 'mental', 'health', 'support'],
    icon: Heart,
    category: 'Hubs',
  },

  // ──── Business ────
  {
    name: 'Quotes',
    path: '/electrician/quotes',
    keywords: ['quote', 'estimate', 'pricing', 'price'],
    icon: Calculator,
    category: 'Business',
  },
  {
    name: 'Invoices',
    path: '/electrician/invoices',
    keywords: ['invoice', 'billing', 'payment'],
    icon: FileText,
    category: 'Business',
  },
  {
    name: 'Customers',
    path: '/customers',
    keywords: ['customer', 'client', 'contact'],
    icon: Users,
    category: 'Business',
  },
  {
    name: 'Expenses',
    path: '/electrician/expenses',
    keywords: ['expense', 'cost', 'receipt', 'spend'],
    icon: Receipt,
    category: 'Business',
  },
  {
    name: 'Projects',
    path: '/electrician/projects',
    keywords: ['project', 'job', 'site'],
    icon: FolderKanban,
    category: 'Business',
  },
  {
    name: 'Tasks',
    path: '/electrician/tasks',
    keywords: ['task', 'todo', 'to-do', 'spark'],
    icon: ListTodo,
    category: 'Business',
  },
  {
    name: 'Business Calendar',
    path: '/electrician/business/calendar',
    keywords: ['calendar', 'schedule', 'diary', 'dates'],
    icon: Calendar,
    category: 'Business',
  },
  {
    name: 'Business Hub',
    path: '/electrician/business',
    keywords: ['business', 'management', 'admin'],
    icon: Briefcase,
    category: 'Business',
  },
  {
    name: 'Site Visits',
    path: '/electrician/site-visits',
    keywords: ['site', 'visit', 'survey', 'assessment'],
    icon: ClipboardCheck,
    category: 'Business',
  },
  {
    name: 'Photo Documents',
    path: '/electrician/photo-docs',
    keywords: ['photo', 'document', 'image', 'evidence'],
    icon: Camera,
    category: 'Business',
  },

  // ──── Business Development ────
  {
    name: 'Business Development',
    path: '/electrician/business-development',
    keywords: ['business', 'development', 'grow', 'startup'],
    icon: TrendingUp,
    category: 'Business Development',
  },
  {
    name: 'Startup Guidance',
    path: '/electrician/business-development/startup',
    keywords: ['startup', 'new business', 'start', 'setup'],
    icon: TrendingUp,
    category: 'Business Development',
  },
  {
    name: 'Growth Strategies',
    path: '/electrician/business-development/growth',
    keywords: ['growth', 'strategy', 'expand', 'scale'],
    icon: TrendingUp,
    category: 'Business Development',
  },
  {
    name: 'Customer Development',
    path: '/electrician/business-development/customers',
    keywords: ['customer', 'development', 'acquisition'],
    icon: Users,
    category: 'Business Development',
  },
  {
    name: 'Tax & Finances',
    path: '/electrician/business-development/tax-finances',
    keywords: ['tax', 'finance', 'hmrc', 'vat', 'accounts'],
    icon: Banknote,
    category: 'Business Development',
  },
  {
    name: 'Debt Recovery',
    path: '/electrician/business-development/debt-recovery',
    keywords: ['debt', 'recovery', 'chase', 'unpaid', 'late payment'],
    icon: Scale,
    category: 'Business Development',
  },

  // ──── Business Calculators ────
  {
    name: 'Job Profitability Calculator',
    path: '/electrician/business-development/tools/job-profitability',
    keywords: ['profitability', 'profit', 'margin', 'job cost'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Cash Flow Planner',
    path: '/electrician/business-development/tools/cash-flow',
    keywords: ['cash', 'flow', 'planner', 'forecast'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Hourly Rate Calculator',
    path: '/electrician/business-development/tools/hourly-rate',
    keywords: ['hourly', 'rate', 'charge', 'day rate'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Tax & NI Estimator',
    path: '/electrician/business-development/tools/tax-estimator',
    keywords: ['tax', 'national insurance', 'ni', 'self assessment'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'ROI Calculator',
    path: '/electrician/business-development/tools/roi-calculator',
    keywords: ['roi', 'return', 'investment'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Break-Even Calculator',
    path: '/electrician/business-development/tools/break-even',
    keywords: ['break', 'even', 'breakeven'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Staff Cost Calculator',
    path: '/electrician/business-development/tools/staff-cost',
    keywords: ['staff', 'cost', 'employee', 'wage'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'VAT Scheme Comparison',
    path: '/electrician/business-development/tools/vat-scheme',
    keywords: ['vat', 'scheme', 'flat rate', 'standard'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'CIS / DRC Helper',
    path: '/electrician/business-development/tools/cis-drc',
    keywords: ['cis', 'drc', 'construction', 'deduction'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Pricing Strategy',
    path: '/electrician/business-development/tools/pricing-strategy',
    keywords: ['pricing', 'strategy', 'competitive'],
    icon: Calculator,
    category: 'Business Calculators',
  },
  {
    name: 'Minimum Charge Calculator',
    path: '/electrician/business-development/tools/minimum-charge',
    keywords: ['minimum', 'charge', 'call out'],
    icon: Calculator,
    category: 'Business Calculators',
  },

  // ──── AI Agents ────
  {
    name: 'AI Tools',
    path: '/electrician-tools/ai-tooling',
    keywords: ['ai', 'artificial', 'intelligence', 'assistant'],
    icon: Sparkles,
    category: 'AI Agents',
  },
  {
    name: 'AI Assistant',
    path: '/electrician-tools/ai-tooling/assistant',
    keywords: ['ai', 'assistant', 'chat', 'help'],
    icon: Bot,
    category: 'AI Agents',
  },
  {
    name: 'Circuit Designer',
    path: '/electrician/circuit-designer',
    keywords: ['circuit', 'design', 'diagram', 'schematic', 'ai'],
    icon: PenTool,
    category: 'AI Agents',
  },
  {
    name: 'Cost Engineer',
    path: '/electrician/cost-engineer',
    keywords: ['cost', 'engineer', 'estimate', 'ai', 'pricing'],
    icon: Calculator,
    category: 'AI Agents',
  },
  {
    name: 'Installation Specialist',
    path: '/electrician/installation-specialist',
    keywords: ['installation', 'specialist', 'install', 'ai', 'guidance'],
    icon: Wrench,
    category: 'AI Agents',
  },
  {
    name: 'Health & Safety Agent',
    path: '/electrician/health-safety',
    keywords: ['health', 'safety', 'rams', 'risk', 'assessment', 'ai'],
    icon: HardHat,
    category: 'AI Agents',
  },
  {
    name: 'Maintenance Specialist',
    path: '/electrician/maintenance',
    keywords: ['maintenance', 'specialist', 'repair', 'ai'],
    icon: Wrench,
    category: 'AI Agents',
  },
  {
    name: 'Component Identification',
    path: '/electrician-tools/ai-tooling/component-identify',
    keywords: ['component', 'identify', 'camera', 'scan', 'photo'],
    icon: Camera,
    category: 'AI Agents',
  },
  {
    name: 'Fault Diagnosis',
    path: '/electrician-tools/ai-tooling/fault-diagnosis',
    keywords: ['fault', 'diagnosis', 'troubleshoot', 'problem'],
    icon: Search,
    category: 'AI Agents',
  },
  {
    name: 'Installation Verification',
    path: '/electrician-tools/ai-tooling/installation-verify',
    keywords: ['installation', 'verify', 'check', 'photo'],
    icon: FileCheck,
    category: 'AI Agents',
  },
  {
    name: 'Client Explainer',
    path: '/electrician-tools/ai-tooling/explainer',
    keywords: ['client', 'explainer', 'explain', 'customer'],
    icon: MessageSquare,
    category: 'AI Agents',
  },
  {
    name: 'Install Planner',
    path: '/electrician/install-planner',
    keywords: ['install', 'planner', 'plan', 'ai'],
    icon: PenTool,
    category: 'AI Agents',
  },

  // ──── Inspection & Testing ────
  {
    name: 'Inspection & Testing',
    path: '/electrician/inspection-testing',
    keywords: ['inspection', 'testing', 'eicr', 'eic', 'report', 'certificate'],
    icon: ClipboardCheck,
    category: 'Inspection & Testing',
  },
  {
    name: 'New Certificate',
    path: '/electrician/inspection-testing/new',
    keywords: ['new', 'certificate', 'create', 'eicr', 'eic'],
    icon: ClipboardCheck,
    category: 'Inspection & Testing',
  },
  {
    name: 'Fire Alarm Certificate',
    path: '/electrician/inspection-testing/fire-alarm/new',
    keywords: ['fire', 'alarm', 'bs 5839', 'certificate'],
    icon: Flame,
    category: 'Inspection & Testing',
  },
  {
    name: 'EV Charging Certificate',
    path: '/electrician/inspection-testing/ev-charging/new',
    keywords: ['ev', 'charging', 'electric vehicle', 'iet', 'certificate'],
    icon: BatteryCharging,
    category: 'Inspection & Testing',
  },
  {
    name: 'Emergency Lighting Certificate',
    path: '/electrician/inspection-testing/emergency-lighting/new',
    keywords: ['emergency', 'lighting', 'bs 5266', 'certificate'],
    icon: Zap,
    category: 'Inspection & Testing',
  },
  {
    name: 'Solar PV Certificate',
    path: '/electrician/inspection-testing/solar-pv/new',
    keywords: ['solar', 'pv', 'mcs', 'photovoltaic', 'certificate'],
    icon: Sun,
    category: 'Inspection & Testing',
  },
  {
    name: 'PAT Testing Certificate',
    path: '/electrician/inspection-testing/pat-testing/new',
    keywords: ['pat', 'testing', 'portable', 'appliance', 'certificate'],
    icon: Plug,
    category: 'Inspection & Testing',
  },

  // ──── Site Safety & Tools ────
  {
    name: 'Site Safety',
    path: '/electrician/site-safety',
    keywords: ['site', 'safety', 'risk', 'hazard', 'toolbox', 'permits', 'coshh'],
    icon: HardHat,
    category: 'Site Safety & Tools',
  },
  {
    name: 'AI RAMS Generator',
    path: '/electrician-tools/site-safety/ai-rams',
    keywords: ['rams', 'risk', 'assessment', 'method', 'statement', 'ai'],
    icon: HardHat,
    category: 'Site Safety & Tools',
  },
  {
    name: 'Elec-ID',
    path: '/elec-id',
    keywords: ['id', 'identification', 'badge', 'verify', 'card'],
    icon: Shield,
    category: 'Site Safety & Tools',
  },
  {
    name: 'Calculations',
    path: '/electrician/calculations',
    keywords: ['calculation', 'calculator', 'voltage', 'current', 'resistance'],
    icon: Calculator,
    category: 'Site Safety & Tools',
  },

  // ──── Materials ────
  {
    name: 'Materials',
    path: '/electrician/materials',
    keywords: ['materials', 'supplies', 'parts', 'buy', 'order'],
    icon: Package,
    category: 'Materials',
  },
  {
    name: 'Materials Lists',
    path: '/electrician/materials/lists',
    keywords: ['materials', 'list', 'shopping', 'order'],
    icon: Package,
    category: 'Materials',
  },
  {
    name: 'Tools Marketplace',
    path: '/electrician/tools-marketplace',
    keywords: ['tools', 'marketplace', 'buy', 'sell', 'equipment'],
    icon: Wrench,
    category: 'Materials',
  },
  {
    name: 'Live Pricing',
    path: '/electrician/live-pricing',
    keywords: ['live', 'pricing', 'trade', 'wholesale'],
    icon: TrendingUp,
    category: 'Materials',
  },

  // ──── Apprentice ────
  {
    name: 'Learning Videos',
    path: '/apprentice/learning-videos',
    keywords: ['video', 'learn', 'watch', 'tutorial'],
    icon: Video,
    category: 'Apprentice',
  },
  {
    name: 'Site Diary',
    path: '/apprentice/site-diary',
    keywords: ['site', 'diary', 'log', 'record', 'daily'],
    icon: Notebook,
    category: 'Apprentice',
  },
  {
    name: 'EPA Simulator',
    path: '/apprentice/epa-simulator',
    keywords: ['epa', 'end point', 'assessment', 'simulator', 'exam'],
    icon: Award,
    category: 'Apprentice',
  },
  {
    name: 'AM2 Simulator',
    path: '/apprentice/am2-simulator',
    keywords: ['am2', 'simulator', 'exam', 'practical'],
    icon: Award,
    category: 'Apprentice',
  },
  {
    name: 'Portfolio Hub',
    path: '/apprentice/portfolio-hub',
    keywords: ['portfolio', 'evidence', 'work', 'record'],
    icon: FolderKanban,
    category: 'Apprentice',
  },
  {
    name: 'OJT Hub',
    path: '/apprentice/ojt-hub',
    keywords: ['ojt', 'on the job', 'training', 'hours'],
    icon: Clock,
    category: 'Apprentice',
  },
  {
    name: 'Apprentice Toolbox',
    path: '/apprentice/toolbox',
    keywords: ['toolbox', 'resources', 'guides', 'help'],
    icon: Wrench,
    category: 'Apprentice',
  },
  {
    name: 'Safety Fundamentals',
    path: '/apprentice/safety-fundamentals',
    keywords: ['safety', 'fundamentals', 'ppe', 'isolation'],
    icon: Shield,
    category: 'Apprentice',
  },
  {
    name: 'Professional Development',
    path: '/apprentice/professional-development',
    keywords: ['professional', 'development', 'career', 'growth'],
    icon: TrendingUp,
    category: 'Apprentice',
  },
  {
    name: 'Rights & Pay',
    path: '/apprentice/rights-and-pay',
    keywords: ['rights', 'pay', 'wages', 'minimum', 'entitlement'],
    icon: Scale,
    category: 'Apprentice',
  },
  {
    name: 'Apprentice Calculators',
    path: '/apprentice/calculators',
    keywords: ['calculator', 'maths', 'formulas', 'apprentice'],
    icon: Calculator,
    category: 'Apprentice',
  },

  // ──── Apprentice Courses ────
  {
    name: 'AM2 Preparation',
    path: '/study-centre/apprentice/am2',
    keywords: ['am2', 'preparation', 'exam', 'practical', 'apprentice'],
    icon: Award,
    category: 'Apprentice Courses',
  },
  {
    name: 'Functional Skills',
    path: '/study-centre/apprentice/functional-skills',
    keywords: ['functional', 'skills', 'maths', 'english', 'apprentice'],
    icon: BookOpen,
    category: 'Apprentice Courses',
  },
  {
    name: 'HNC Electrical',
    path: '/study-centre/apprentice/hnc',
    keywords: ['hnc', 'higher', 'national', 'certificate', 'electrical'],
    icon: GraduationCap,
    category: 'Apprentice Courses',
  },
  {
    name: 'Level 2 Electrical',
    path: '/study-centre/apprentice/level2',
    keywords: ['level 2', 'electrical', 'installation', 'apprentice'],
    icon: BookOpen,
    category: 'Apprentice Courses',
  },
  {
    name: 'Level 3 Electrical',
    path: '/study-centre/apprentice/level3',
    keywords: ['level 3', 'electrical', 'installation', 'apprentice'],
    icon: BookOpen,
    category: 'Apprentice Courses',
  },
  {
    name: 'MOET Course',
    path: '/study-centre/apprentice/moet',
    keywords: ['moet', 'maintenance', 'operations', 'electrical', 'technician'],
    icon: BookOpen,
    category: 'Apprentice Courses',
  },

  // ──── Upskilling Courses ────
  {
    name: 'Upskilling Courses',
    path: '/study-centre/upskilling',
    keywords: ['upskill', 'cpd', 'training', 'course', 'qualified'],
    icon: GraduationCap,
    category: 'Upskilling Courses',
  },
  {
    name: 'BMS Course',
    path: '/study-centre/upskilling/bms-course',
    keywords: ['bms', 'building', 'management', 'systems', 'hvac', 'controls'],
    icon: BookOpen,
    category: 'Upskilling Courses',
  },
  {
    name: 'BS 7671 Course',
    path: '/study-centre/upskilling/bs7671-course',
    keywords: ['bs 7671', 'wiring', 'regulations', '18th edition', 'regs'],
    icon: BookOpen,
    category: 'Upskilling Courses',
  },
  {
    name: 'Fire Alarm Systems Course',
    path: '/study-centre/upskilling/fire-alarm-course',
    keywords: ['fire', 'alarm', 'bs 5839', 'detection', 'systems'],
    icon: Flame,
    category: 'Upskilling Courses',
  },
  {
    name: 'Industrial Electrical Course',
    path: '/study-centre/upskilling/industrial-electrical-course',
    keywords: ['industrial', 'electrical', 'three phase', 'motors', 'plc'],
    icon: Zap,
    category: 'Upskilling Courses',
  },
  {
    name: 'Inspection & Testing Course',
    path: '/study-centre/upskilling/inspection-testing',
    keywords: ['inspection', 'testing', 'i&t', '2391', 'initial', 'periodic'],
    icon: ClipboardCheck,
    category: 'Upskilling Courses',
  },
  {
    name: 'PAT Testing Course',
    path: '/study-centre/upskilling/pat-testing-course',
    keywords: ['pat', 'testing', 'portable', 'appliance', 'course'],
    icon: Plug,
    category: 'Upskilling Courses',
  },
  {
    name: 'Instrumentation Course',
    path: '/study-centre/upskilling/instrumentation-course',
    keywords: ['instrumentation', 'process', 'control', 'specialised'],
    icon: PenTool,
    category: 'Upskilling Courses',
  },

  // ──── General Upskilling ────
  {
    name: 'IPAF Course',
    path: '/study-centre/general-upskilling/ipaf-course',
    keywords: ['ipaf', 'powered', 'access', 'platform', 'cherry picker'],
    icon: GraduationCap,
    category: 'General Upskilling',
  },
  {
    name: 'PASMA Course',
    path: '/study-centre/general-upskilling/pasma-course',
    keywords: ['pasma', 'scaffold', 'tower', 'mobile', 'access'],
    icon: GraduationCap,
    category: 'General Upskilling',
  },
  {
    name: 'MEWP Course',
    path: '/study-centre/general-upskilling/mewp-course',
    keywords: ['mewp', 'mobile', 'elevated', 'work', 'platform'],
    icon: GraduationCap,
    category: 'General Upskilling',
  },
  {
    name: 'First Aid Course',
    path: '/study-centre/general-upskilling/first-aid-course',
    keywords: ['first', 'aid', 'emergency', 'medical', 'cpr'],
    icon: Heart,
    category: 'General Upskilling',
  },
  {
    name: 'Mental Health Course',
    path: '/study-centre/general-upskilling/mental-health-course',
    keywords: ['mental', 'health', 'awareness', 'wellbeing', 'first aid'],
    icon: Heart,
    category: 'General Upskilling',
  },
  {
    name: 'Asbestos Awareness',
    path: '/study-centre/general-upskilling/asbestos-awareness-course',
    keywords: ['asbestos', 'awareness', 'hazard', 'removal'],
    icon: ShieldCheck,
    category: 'General Upskilling',
  },
  {
    name: 'Working at Height',
    path: '/study-centre/general-upskilling/working-at-height-course',
    keywords: ['working', 'height', 'ladder', 'fall', 'safety'],
    icon: HardHat,
    category: 'General Upskilling',
  },
  {
    name: 'Manual Handling',
    path: '/study-centre/general-upskilling/manual-handling-course',
    keywords: ['manual', 'handling', 'lifting', 'carrying', 'ergonomic'],
    icon: HardHat,
    category: 'General Upskilling',
  },
  {
    name: 'COSHH Awareness',
    path: '/study-centre/general-upskilling/coshh-awareness-course',
    keywords: ['coshh', 'hazardous', 'substances', 'chemical', 'safety'],
    icon: ShieldCheck,
    category: 'General Upskilling',
  },
  {
    name: 'Confined Spaces',
    path: '/study-centre/general-upskilling/confined-spaces-course',
    keywords: ['confined', 'spaces', 'entry', 'safety', 'rescue'],
    icon: HardHat,
    category: 'General Upskilling',
  },
  {
    name: 'Fire Safety',
    path: '/study-centre/general-upskilling/fire-safety-course',
    keywords: ['fire', 'safety', 'extinguisher', 'evacuation', 'prevention'],
    icon: Flame,
    category: 'General Upskilling',
  },
  {
    name: 'CSCS Card Course',
    path: '/study-centre/general-upskilling/cscs-card-course',
    keywords: ['cscs', 'card', 'construction', 'skills', 'certification'],
    icon: Award,
    category: 'General Upskilling',
  },
  {
    name: 'Scaffolding Awareness',
    path: '/study-centre/general-upskilling/scaffolding-awareness-course',
    keywords: ['scaffolding', 'awareness', 'safety', 'erection', 'inspection'],
    icon: HardHat,
    category: 'General Upskilling',
  },
  {
    name: 'Environmental Sustainability',
    path: '/study-centre/general-upskilling/environmental-sustainability-course',
    keywords: ['environmental', 'sustainability', 'green', 'waste', 'recycling'],
    icon: BookOpen,
    category: 'General Upskilling',
  },
  {
    name: 'CDM Regulations',
    path: '/study-centre/general-upskilling/cdm-regulations-course',
    keywords: ['cdm', 'regulations', 'construction', 'design', 'management'],
    icon: BookOpen,
    category: 'General Upskilling',
  },

  // ──── Personal Development ────
  {
    name: 'Leadership on Site',
    path: '/study-centre/personal-development/leadership-on-site',
    keywords: ['leadership', 'site', 'manage', 'team', 'supervisor'],
    icon: Users,
    category: 'Personal Development',
  },
  {
    name: 'Mental Health Awareness',
    path: '/study-centre/personal-development/mental-health-awareness',
    keywords: ['mental', 'health', 'awareness', 'wellbeing', 'support'],
    icon: Heart,
    category: 'Personal Development',
  },
  {
    name: 'Emotional Intelligence',
    path: '/study-centre/personal-development/emotional-intelligence',
    keywords: ['emotional', 'intelligence', 'eq', 'empathy', 'self awareness'],
    icon: Heart,
    category: 'Personal Development',
  },
  {
    name: 'Communication & Confidence',
    path: '/study-centre/personal-development/communication-confidence',
    keywords: ['communication', 'confidence', 'speaking', 'presentation'],
    icon: MessageSquare,
    category: 'Personal Development',
  },
  {
    name: 'Mentoring & Developing Others',
    path: '/study-centre/personal-development/mentoring-developing-others',
    keywords: ['mentoring', 'developing', 'coaching', 'training', 'others'],
    icon: Users,
    category: 'Personal Development',
  },
  {
    name: 'Resilience & Stress Management',
    path: '/study-centre/personal-development/resilience-stress-management',
    keywords: ['resilience', 'stress', 'management', 'coping', 'burnout'],
    icon: Shield,
    category: 'Personal Development',
  },
  {
    name: 'Time Management',
    path: '/study-centre/personal-development/time-management-organisation',
    keywords: ['time', 'management', 'organisation', 'productivity', 'planning'],
    icon: Clock,
    category: 'Personal Development',
  },
  {
    name: 'Conflict Resolution',
    path: '/study-centre/personal-development/conflict-resolution',
    keywords: ['conflict', 'resolution', 'dispute', 'mediation', 'negotiation'],
    icon: Scale,
    category: 'Personal Development',
  },
  {
    name: 'Personal Finance',
    path: '/study-centre/personal-development/personal-finance',
    keywords: ['personal', 'finance', 'money', 'budgeting', 'savings'],
    icon: Banknote,
    category: 'Personal Development',
  },
  {
    name: 'Goal Setting & Growth',
    path: '/study-centre/personal-development/goal-setting-growth',
    keywords: ['goal', 'setting', 'growth', 'mindset', 'ambition'],
    icon: TrendingUp,
    category: 'Personal Development',
  },

  // ──── Jobs ────
  {
    name: 'Job Vacancies',
    path: '/electrician/job-vacancies',
    keywords: ['job', 'vacancy', 'work', 'employment', 'hire'],
    icon: Briefcase,
    category: 'Jobs',
  },
  {
    name: 'CV Builder',
    path: '/electrician/cv-builder',
    keywords: ['cv', 'resume', 'builder', 'career'],
    icon: FileText,
    category: 'Jobs',
  },
  {
    name: 'Career Progression',
    path: '/electrician/career-progression',
    keywords: ['career', 'progression', 'pathway', 'advance'],
    icon: TrendingUp,
    category: 'Jobs',
  },

  // ──── Settings ────
  {
    name: 'Profile',
    path: '/profile',
    keywords: ['profile', 'account', 'personal', 'details'],
    icon: User,
    category: 'Settings',
  },
  {
    name: 'Settings',
    path: '/settings',
    keywords: ['settings', 'preferences', 'config'],
    icon: Settings,
    category: 'Settings',
  },
  {
    name: 'Subscriptions',
    path: '/subscriptions',
    keywords: ['subscription', 'plan', 'billing', 'upgrade', 'premium'],
    icon: CreditCard,
    category: 'Settings',
  },
  {
    name: 'Notifications',
    path: '/notifications',
    keywords: ['notification', 'alert', 'email', 'push'],
    icon: Bell,
    category: 'Settings',
  },
  {
    name: 'Refer a Mate',
    path: '/settings?tab=referrals',
    keywords: ['referral', 'refer', 'invite', 'share', 'friend', 'free month'],
    icon: Gift,
    category: 'Settings',
  },
];
