
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar, User, MapPin, AlertTriangle, Shield, CheckCircle, ClipboardList } from "lucide-react";
import { format } from "date-fns";

interface RiskAssessment {
  id: string;
  hazard: string;
  likelihood: number;
  severity: number;
  riskScore: number;
  riskLevel: string;
  controlMeasures: string[];
  timestamp: string;
  assessor: string;
  location: string;
}

interface RiskDocumentationProps {
  assessment: RiskAssessment | null;
}

const RiskDocumentation = ({ assessment }: RiskDocumentationProps) => {
  const generateReport = () => {
    if (!assessment) return;

    // Generate a simple text report
    const reportContent = `
ELECTRICAL RISK ASSESSMENT REPORT
=====================================

Assessment Details:
- Date: ${format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}
- Assessor: ${assessment.assessor}
- Location: ${assessment.location}
- Assessment ID: ${assessment.id}

Hazard Identification:
- Hazard: ${assessment.hazard}

Risk Analysis:
- Likelihood: ${assessment.likelihood}/5
- Severity: ${assessment.severity}/5
- Risk Score: ${assessment.riskScore}
- Risk Level: ${assessment.riskLevel}

Control Measures:
${assessment.controlMeasures.map((measure, index) => `${index + 1}. ${measure}`).join('\n')}

Recommendations:
- Review this assessment regularly
- Ensure all control measures are implemented
- Monitor effectiveness of control measures
- Update assessment if conditions change

Report generated by Elec-Mate Risk Assessment Tool
    `.trim();

    // Create and download the report
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `risk-assessment-${assessment.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getRiskLevelConfig = (level: string) => {
    switch (level) {
      case "Very High":
        return { bg: 'bg-red-500/20', text: 'text-red-400', border: 'border-red-500/30', badge: 'bg-red-500 text-white' };
      case "High":
        return { bg: 'bg-red-500/15', text: 'text-red-400', border: 'border-red-500/30', badge: 'bg-red-500/80 text-white' };
      case "Medium":
        return { bg: 'bg-elec-yellow/20', text: 'text-elec-yellow', border: 'border-elec-yellow/30', badge: 'bg-elec-yellow text-black' };
      case "Low":
        return { bg: 'bg-green-500/20', text: 'text-green-400', border: 'border-green-500/30', badge: 'bg-green-500 text-white' };
      case "Very Low":
        return { bg: 'bg-green-500/15', text: 'text-green-400', border: 'border-green-500/30', badge: 'bg-green-400 text-black' };
      default:
        return { bg: 'bg-white/10', text: 'text-white/70', border: 'border-white/20', badge: 'bg-white/20 text-white' };
    }
  };

  if (!assessment) {
    return (
      <Card className="bg-gradient-to-br from-white/5 to-elec-card border-white/10 overflow-hidden relative animate-fade-in">
        <div className="absolute top-0 right-0 w-64 h-64 bg-elec-yellow/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
        <CardHeader className="relative">
          <CardTitle className="text-white flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-gradient-to-br from-elec-yellow/20 to-elec-yellow/5 border border-elec-yellow/30">
              <FileText className="h-5 w-5 text-elec-yellow" />
            </div>
            Risk Documentation
          </CardTitle>
        </CardHeader>
        <CardContent className="relative">
          <div className="text-center py-12">
            <div className="p-4 rounded-2xl bg-white/10 border border-white/10 inline-block mb-4">
              <ClipboardList className="h-12 w-12 text-white/30" />
            </div>
            <h4 className="font-medium text-white mb-2">No Assessment Yet</h4>
            <p className="text-sm text-white/80 max-w-xs mx-auto">
              Complete a risk assessment to generate documentation and download your report
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  const riskConfig = getRiskLevelConfig(assessment.riskLevel);

  return (
    <Card className="bg-gradient-to-br from-white/5 to-elec-card border-white/10 overflow-hidden relative animate-fade-in">
      <div className="absolute top-0 right-0 w-64 h-64 bg-elec-yellow/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
      <CardHeader className="relative">
        <CardTitle className="text-white flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-gradient-to-br from-elec-yellow/20 to-elec-yellow/5 border border-elec-yellow/30">
            <FileText className="h-5 w-5 text-elec-yellow" />
          </div>
          Risk Documentation
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 relative">
        {/* Assessment Summary */}
        <div className={`p-4 rounded-xl ${riskConfig.bg} border ${riskConfig.border}`}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-white/10">
                <AlertTriangle className={`h-5 w-5 ${riskConfig.text}`} />
              </div>
              <h4 className="font-semibold text-white">Assessment Summary</h4>
            </div>
            <Badge className={riskConfig.badge}>
              {assessment.riskLevel} Risk
            </Badge>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/10">
              <div className="p-2 rounded-lg bg-blue-500/20">
                <Calendar className="h-4 w-4 text-blue-400" />
              </div>
              <div>
                <p className="text-xs text-white/80">Date & Time</p>
                <p className="text-sm font-medium text-white">{format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/10">
              <div className="p-2 rounded-lg bg-green-500/20">
                <User className="h-4 w-4 text-green-400" />
              </div>
              <div>
                <p className="text-xs text-white/80">Assessor</p>
                <p className="text-sm font-medium text-white">{assessment.assessor}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/10">
              <div className="p-2 rounded-lg bg-purple-500/20">
                <MapPin className="h-4 w-4 text-purple-400" />
              </div>
              <div>
                <p className="text-xs text-white/80">Location</p>
                <p className="text-sm font-medium text-white">{assessment.location}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Hazard Details */}
        <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/30">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-lg bg-red-500/20">
              <AlertTriangle className="h-4 w-4 text-red-400" />
            </div>
            <h4 className="font-semibold text-white">Identified Hazard</h4>
          </div>
          <p className="text-white/80 p-3 bg-white/10 rounded-lg border border-white/10">
            {assessment.hazard}
          </p>
        </div>

        {/* Risk Analysis */}
        <div className="space-y-3">
          <h4 className="font-semibold text-white flex items-center gap-2">
            <span className="w-6 h-6 bg-elec-yellow/20 rounded-lg flex items-center justify-center text-xs text-elec-yellow font-bold">R</span>
            Risk Analysis
          </h4>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="p-4 rounded-xl bg-white/10 border border-white/10 text-center">
              <div className="text-xs text-white/80 mb-2">Likelihood</div>
              <div className="text-2xl font-bold text-elec-yellow">{assessment.likelihood}</div>
              <div className="text-xs text-white/70">out of 5</div>
            </div>
            <div className="p-4 rounded-xl bg-white/10 border border-white/10 text-center">
              <div className="text-xs text-white/80 mb-2">Severity</div>
              <div className="text-2xl font-bold text-red-400">{assessment.severity}</div>
              <div className="text-xs text-white/70">out of 5</div>
            </div>
            <div className="p-4 rounded-xl bg-white/10 border border-white/10 text-center">
              <div className="text-xs text-white/80 mb-2">Risk Score</div>
              <div className={`text-2xl font-bold ${riskConfig.text}`}>{assessment.riskScore}</div>
              <div className="text-xs text-white/70">L × S</div>
            </div>
            <div className={`p-4 rounded-xl ${riskConfig.bg} border ${riskConfig.border} text-center`}>
              <div className="text-xs text-white/80 mb-2">Risk Level</div>
              <div className={`text-lg font-bold ${riskConfig.text}`}>{assessment.riskLevel}</div>
            </div>
          </div>
        </div>

        {/* Control Measures */}
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-green-500/20">
              <Shield className="h-4 w-4 text-green-400" />
            </div>
            <h4 className="font-semibold text-white">Control Measures ({assessment.controlMeasures.length})</h4>
          </div>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {assessment.controlMeasures.map((measure, index) => (
              <div key={index} className="flex items-start gap-3 p-3 rounded-xl bg-white/10 border border-white/10">
                <div className="w-6 h-6 rounded-lg bg-green-500/20 flex items-center justify-center flex-shrink-0">
                  <CheckCircle className="h-3.5 w-3.5 text-green-400" />
                </div>
                <span className="text-sm text-white/80">{measure}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="pt-4 border-t border-white/10">
          <Button
            onClick={generateReport}
            className="w-full h-12 bg-elec-yellow hover:bg-elec-yellow/90 text-black font-semibold touch-manipulation active:scale-95 transition-all"
          >
            <Download className="h-5 w-5 mr-2" />
            Download Assessment Report
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default RiskDocumentation;
