
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar, User, MapPin } from "lucide-react";
import { format } from "date-fns";

interface RiskAssessment {
  id: string;
  hazard: string;
  likelihood: number;
  severity: number;
  riskScore: number;
  riskLevel: string;
  controlMeasures: string[];
  timestamp: string;
  assessor: string;
  location: string;
}

interface RiskDocumentationProps {
  assessment: RiskAssessment | null;
}

const RiskDocumentation = ({ assessment }: RiskDocumentationProps) => {
  const generateReport = () => {
    if (!assessment) return;
    
    // Generate a simple text report
    const reportContent = `
ELECTRICAL RISK ASSESSMENT REPORT
=====================================

Assessment Details:
- Date: ${format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}
- Assessor: ${assessment.assessor}
- Location: ${assessment.location}
- Assessment ID: ${assessment.id}

Hazard Identification:
- Hazard: ${assessment.hazard}

Risk Analysis:
- Likelihood: ${assessment.likelihood}/5
- Severity: ${assessment.severity}/5
- Risk Score: ${assessment.riskScore}
- Risk Level: ${assessment.riskLevel}

Control Measures:
${assessment.controlMeasures.map((measure, index) => `${index + 1}. ${measure}`).join('\n')}

Recommendations:
- Review this assessment regularly
- Ensure all control measures are implemented
- Monitor effectiveness of control measures
- Update assessment if conditions change

Report generated by Elec-Mate Risk Assessment Tool
    `.trim();

    // Create and download the report
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `risk-assessment-${assessment.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getRiskLevelColor = (level: string) => {
    switch (level) {
      case "Very High":
        return "bg-red-600 text-white";
      case "High":
        return "bg-red-500 text-white";
      case "Medium":
        return "bg-yellow-500 text-black";
      case "Low":
        return "bg-green-500 text-white";
      case "Very Low":
        return "bg-green-400 text-black";
      default:
        return "bg-gray-500 text-white";
    }
  };

  if (!assessment) {
    return (
      <Card className="border-elec-yellow/20 bg-elec-gray">
        <CardHeader>
          <CardTitle className="text-elec-yellow flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Risk Documentation
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8">
            <FileText className="h-12 w-12 text-gray-400 mx-auto mb-3" />
            <p className="text-gray-400">Complete a risk assessment to generate documentation</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-elec-yellow/20 bg-elec-gray">
      <CardHeader>
        <CardTitle className="text-elec-yellow flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Risk Documentation
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Assessment Summary */}
        <div className="p-4 border border-gray-600 rounded-lg bg-elec-dark/50">
          <div className="flex items-center justify-between mb-4">
            <h4 className="font-semibold">Assessment Summary</h4>
            <Badge className={getRiskLevelColor(assessment.riskLevel)}>
              {assessment.riskLevel} Risk
            </Badge>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4 text-gray-400" />
              <span>{format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}</span>
            </div>
            <div className="flex items-center gap-2">
              <User className="h-4 w-4 text-gray-400" />
              <span>{assessment.assessor}</span>
            </div>
            <div className="flex items-center gap-2">
              <MapPin className="h-4 w-4 text-gray-400" />
              <span>{assessment.location}</span>
            </div>
          </div>
        </div>

        {/* Hazard Details */}
        <div className="space-y-3">
          <h4 className="font-semibold">Identified Hazard</h4>
          <p className="text-gray-300 p-3 bg-elec-dark/50 rounded border border-gray-600">
            {assessment.hazard}
          </p>
        </div>

        {/* Risk Analysis */}
        <div className="space-y-3">
          <h4 className="font-semibold">Risk Analysis</h4>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
            <div className="p-3 bg-elec-dark/50 rounded border border-gray-600 text-center">
              <div className="text-gray-400">Likelihood</div>
              <div className="text-xl font-bold text-elec-yellow">{assessment.likelihood}/5</div>
            </div>
            <div className="p-3 bg-elec-dark/50 rounded border border-gray-600 text-center">
              <div className="text-gray-400">Severity</div>
              <div className="text-xl font-bold text-elec-yellow">{assessment.severity}/5</div>
            </div>
            <div className="p-3 bg-elec-dark/50 rounded border border-gray-600 text-center">
              <div className="text-gray-400">Risk Score</div>
              <div className="text-xl font-bold text-elec-yellow">{assessment.riskScore}</div>
            </div>
            <div className="p-3 bg-elec-dark/50 rounded border border-gray-600 text-center">
              <div className="text-gray-400">Risk Level</div>
              <div className="text-sm font-bold text-elec-yellow">{assessment.riskLevel}</div>
            </div>
          </div>
        </div>

        {/* Control Measures */}
        <div className="space-y-3">
          <h4 className="font-semibold">Control Measures</h4>
          <div className="space-y-2">
            {assessment.controlMeasures.map((measure, index) => (
              <div key={index} className="flex items-start gap-2 p-3 bg-elec-dark/50 rounded border border-gray-600">
                <Badge variant="outline" className="border-elec-yellow/30 text-elec-yellow">
                  {index + 1}
                </Badge>
                <span className="text-sm text-gray-300">{measure}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-2 pt-4 border-t border-gray-600">
          <Button 
            onClick={generateReport}
            className="bg-elec-yellow text-black hover:bg-elec-yellow/90 flex-1"
          >
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default RiskDocumentation;
