import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { format } from 'date-fns';

interface RiskAssessment {
  id: string;
  hazard: string;
  likelihood: number;
  severity: number;
  riskScore: number;
  riskLevel: string;
  controlMeasures: string[];
  timestamp: string;
  assessor: string;
  location: string;
}

interface RiskDocumentationProps {
  assessment: RiskAssessment | null;
}

const RiskDocumentation = ({ assessment }: RiskDocumentationProps) => {
  const generateReport = () => {
    if (!assessment) return;

    const reportContent = `
ELECTRICAL RISK ASSESSMENT REPORT
=====================================

Assessment Details:
- Date: ${format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}
- Assessor: ${assessment.assessor}
- Location: ${assessment.location}
- Assessment ID: ${assessment.id}

Hazard Identification:
- Hazard: ${assessment.hazard}

Risk Analysis:
- Likelihood: ${assessment.likelihood}/5
- Severity: ${assessment.severity}/5
- Risk Score: ${assessment.riskScore}
- Risk Level: ${assessment.riskLevel}

Control Measures:
${assessment.controlMeasures.map((measure, index) => `${index + 1}. ${measure}`).join('\n')}

Recommendations:
- Review this assessment regularly
- Ensure all control measures are implemented
- Monitor effectiveness of control measures
- Update assessment if conditions change

Report generated by Elec-Mate Risk Assessment Tool
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `risk-assessment-${assessment.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!assessment) {
    return (
      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-8 text-center space-y-2 animate-fade-in">
        <p className="text-[16px] font-medium text-white">No assessment yet</p>
        <p className="text-[14px] text-white/70 leading-relaxed">
          Complete a risk assessment to generate documentation and download your report
        </p>
      </div>
    );
  }

  const isDanger = assessment.riskLevel === 'Very High' || assessment.riskLevel === 'High';

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="space-y-2">
        <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
          Risk documentation
        </span>
        <h3 className="text-[16px] sm:text-[18px] font-medium text-white">Assessment summary</h3>
      </div>

      <div
        className={`rounded-xl border p-4 sm:p-5 space-y-3 ${
          isDanger ? 'border-red-500/30 bg-red-500/[0.04]' : 'border-white/[0.06] bg-white/[0.02]'
        }`}
      >
        <div className="flex items-baseline justify-between">
          <span
            className={`text-[10px] font-medium uppercase tracking-[0.18em] ${isDanger ? 'text-red-300' : 'text-white/55'}`}
          >
            {assessment.riskLevel} risk
          </span>
          <span className="text-[12px] text-white/85 font-mono">Score: {assessment.riskScore}</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 space-y-1">
            <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
              Date & time
            </span>
            <p className="text-[13px] text-white/85 font-mono">
              {format(new Date(assessment.timestamp), 'dd/MM/yyyy HH:mm')}
            </p>
          </div>
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 space-y-1">
            <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
              Assessor
            </span>
            <p className="text-[13px] text-white/85">{assessment.assessor}</p>
          </div>
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 space-y-1">
            <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
              Location
            </span>
            <p className="text-[13px] text-white/85">{assessment.location}</p>
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 sm:p-5 space-y-2">
        <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
          Identified hazard
        </span>
        <p className="text-[14px] text-white/85 leading-relaxed">{assessment.hazard}</p>
      </div>

      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 sm:p-5 space-y-3">
        <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
          Risk analysis
        </span>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 text-center space-y-1">
            <div className="text-[10px] uppercase tracking-[0.18em] text-white/55">Likelihood</div>
            <div className="text-[20px] font-semibold text-white font-mono">
              {assessment.likelihood}
            </div>
            <div className="text-[10px] text-white/55">/ 5</div>
          </div>
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 text-center space-y-1">
            <div className="text-[10px] uppercase tracking-[0.18em] text-white/55">Severity</div>
            <div className="text-[20px] font-semibold text-white font-mono">
              {assessment.severity}
            </div>
            <div className="text-[10px] text-white/55">/ 5</div>
          </div>
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 text-center space-y-1">
            <div className="text-[10px] uppercase tracking-[0.18em] text-white/55">Score</div>
            <div className="text-[20px] font-semibold text-elec-yellow font-mono">
              {assessment.riskScore}
            </div>
            <div className="text-[10px] text-white/55">L × S</div>
          </div>
          <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 text-center space-y-1">
            <div className="text-[10px] uppercase tracking-[0.18em] text-white/55">Level</div>
            <div className="text-[14px] font-semibold text-white">{assessment.riskLevel}</div>
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 sm:p-5 space-y-3">
        <div className="flex items-baseline justify-between">
          <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-white/55">
            Control measures
          </span>
          <span className="text-[12px] text-white/85 font-mono">
            {assessment.controlMeasures.length}
          </span>
        </div>
        <ul className="space-y-1.5 max-h-48 overflow-y-auto">
          {assessment.controlMeasures.map((measure, index) => (
            <li
              key={index}
              className="flex items-start gap-2 text-[14px] text-white/85 leading-relaxed"
            >
              <span className="w-1 h-1 rounded-full bg-elec-yellow mt-2 flex-shrink-0" />
              <span>{measure}</span>
            </li>
          ))}
        </ul>
      </div>

      <Button
        onClick={generateReport}
        className="w-full h-11 bg-elec-yellow hover:bg-elec-yellow/90 text-black font-semibold touch-manipulation active:scale-[0.98]"
      >
        <Download className="h-4 w-4 mr-2" />
        Download assessment report
      </Button>
    </div>
  );
};

export default RiskDocumentation;
