import { useState, useEffect, useCallback, useMemo } from 'react';

export interface BS7671TestProgress {
  completedSteps: number[];
  completedAt?: string;
  lastStepViewed: number;
}

interface BS7671ProgressState {
  completedTests: Record<string, BS7671TestProgress>;
  lastUpdated: string;
}

const STORAGE_KEY = 'elec-mate-bs7671-progress';

const getInitialState = (): BS7671ProgressState => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      return JSON.parse(saved);
    }
  } catch (error) {
    console.error('Failed to load BS 7671 progress:', error);
  }
  return {
    completedTests: {},
    lastUpdated: new Date().toISOString(),
  };
};

export const useBS7671Progress = () => {
  const [state, setState] = useState<BS7671ProgressState>(getInitialState);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (error) {
      console.error('Failed to save BS 7671 progress:', error);
    }
  }, [state]);

  const markStepComplete = useCallback((testId: string, stepIndex: number) => {
    setState(prev => {
      const existing = prev.completedTests[testId] || { completedSteps: [], lastStepViewed: 0 };
      if (existing.completedSteps.includes(stepIndex)) return prev;
      return {
        ...prev,
        completedTests: {
          ...prev.completedTests,
          [testId]: {
            ...existing,
            completedSteps: [...existing.completedSteps, stepIndex],
            lastStepViewed: stepIndex,
          },
        },
        lastUpdated: new Date().toISOString(),
      };
    });
  }, []);

  const markTestComplete = useCallback((testId: string) => {
    setState(prev => {
      const existing = prev.completedTests[testId] || { completedSteps: [], lastStepViewed: 0 };
      return {
        ...prev,
        completedTests: {
          ...prev.completedTests,
          [testId]: {
            ...existing,
            completedAt: new Date().toISOString(),
          },
        },
        lastUpdated: new Date().toISOString(),
      };
    });
  }, []);

  const setLastStepViewed = useCallback((testId: string, step: number) => {
    setState(prev => {
      const existing = prev.completedTests[testId] || { completedSteps: [], lastStepViewed: 0 };
      return {
        ...prev,
        completedTests: {
          ...prev.completedTests,
          [testId]: { ...existing, lastStepViewed: step },
        },
        lastUpdated: new Date().toISOString(),
      };
    });
  }, []);

  const clearProgress = useCallback(() => {
    const fresh: BS7671ProgressState = {
      completedTests: {},
      lastUpdated: new Date().toISOString(),
    };
    setState(fresh);
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch (error) {
      console.error('Failed to clear BS 7671 progress:', error);
    }
  }, []);

  const isStepComplete = useCallback((testId: string, stepIndex: number) => {
    return state.completedTests[testId]?.completedSteps.includes(stepIndex) || false;
  }, [state.completedTests]);

  const isTestComplete = useCallback((testId: string) => {
    return !!state.completedTests[testId]?.completedAt;
  }, [state.completedTests]);

  const getCompletedStepCount = useCallback((testId: string) => {
    return state.completedTests[testId]?.completedSteps.length || 0;
  }, [state.completedTests]);

  const getTestProgress = useCallback((testId: string): BS7671TestProgress | undefined => {
    return state.completedTests[testId];
  }, [state.completedTests]);

  const completedTestCount = useMemo(() => {
    return Object.values(state.completedTests).filter(t => t.completedAt).length;
  }, [state.completedTests]);

  const totalStepsCompleted = useMemo(() => {
    return Object.values(state.completedTests).reduce((sum, t) => sum + t.completedSteps.length, 0);
  }, [state.completedTests]);

  const exportAsText = useCallback((tests: { id: string; title: string; stepCount: number }[]) => {
    const lines: string[] = [
      'BS 7671 INSPECTION & TESTING PROGRESS REPORT',
      '='.repeat(45),
      `Date: ${new Date().toLocaleDateString('en-GB')}`,
      `Tests Completed: ${completedTestCount}/${tests.length}`,
      `Total Steps Completed: ${totalStepsCompleted}`,
      '',
    ];

    for (const test of tests) {
      const progress = state.completedTests[test.id];
      const stepsComplete = progress?.completedSteps.length || 0;
      const status = progress?.completedAt ? '[DONE]' : `[${stepsComplete}/${test.stepCount}]`;
      lines.push(`${status} ${test.title}`);
      if (progress?.completedAt) {
        lines.push(`       Completed: ${new Date(progress.completedAt).toLocaleDateString('en-GB')}`);
      }
    }

    lines.push('');
    lines.push('Generated by Elec-Mate BS 7671 Tools');
    return lines.join('\n');
  }, [completedTestCount, totalStepsCompleted, state.completedTests]);

  return {
    markStepComplete,
    markTestComplete,
    setLastStepViewed,
    clearProgress,
    isStepComplete,
    isTestComplete,
    getCompletedStepCount,
    getTestProgress,
    completedTestCount,
    totalStepsCompleted,
    exportAsText,
    lastUpdated: state.lastUpdated,
  };
};
