import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Copy, Download } from "lucide-react";
import { toast } from "sonner";
import type { CommissioningProgressData } from "@/hooks/useCommissioningProgress";

interface CertificateDataSectionProps {
  progress: CommissioningProgressData | null;
  projectName: string;
  location: string;
  installationDate: string;
}

export const CertificateDataSection = ({
  progress,
  projectName,
  location,
  installationDate,
}: CertificateDataSectionProps) => {
  const [showCertificateData, setShowCertificateData] = useState(false);

  // Defensive checks: ensure data structure is valid
  if (!progress || !Array.isArray(progress.testResults) || progress.testResults.length === 0) {
    return null;
  }

  const calculateNextInspectionDate = () => {
    const installDate = new Date(installationDate);
    const type = progress.installationType.toLowerCase();
    
    // BS 7671 recommended inspection intervals
    if (type.includes('domestic')) {
      installDate.setFullYear(installDate.getFullYear() + 10);
    } else if (type.includes('commercial')) {
      installDate.setFullYear(installDate.getFullYear() + 5);
    } else if (type.includes('industrial')) {
      installDate.setFullYear(installDate.getFullYear() + 3);
    } else {
      installDate.setFullYear(installDate.getFullYear() + 5);
    }
    
    return installDate.toISOString().split('T')[0];
  };

  const generateScheduleOfTestResults = () => {
    return progress.testResults.map((result, index) => ({
      ref: `C${index + 1}`,
      description: result.testName,
      value: result.measuredValue || 'N/A',
      unit: result.unit || '',
      passed: result.passed ? 'PASS' : result.passed === false ? 'FAIL' : 'N/A',
      notes: result.notes || '',
    }));
  };

  const generateObservations = () => {
    const observations: string[] = [];
    
    progress.testResults.forEach((result) => {
      if (result.passed === false) {
        observations.push(`${result.testName}: FAILED - ${result.notes || 'See test results'}`);
      }
    });
    
    // Ensure visualChecks is an array before iterating
    if (Array.isArray(progress.visualChecks)) {
      progress.visualChecks.forEach((check, index) => {
        if (check.notes) {
          observations.push(`Visual Check ${index + 1}: ${check.notes}`);
        }
      });
    }
    
    if (observations.length === 0) {
      observations.push('No observations - installation complies with BS 7671:2018+A2:2024');
    }
    
    return observations;
  };

  const generateRecommendations = () => {
    const recommendations: string[] = [];
    
    const failedTests = progress.testResults.filter((r) => r.passed === false);
    
    if (failedTests.length > 0) {
      recommendations.push('Remedial work required - see observations for details');
      recommendations.push('Re-test after remedial work completion');
    }
    
    const nextInspection = calculateNextInspectionDate();
    recommendations.push(`Next inspection recommended by: ${nextInspection}`);
    
    if (progress.installationType.toLowerCase().includes('commercial') || 
        progress.installationType.toLowerCase().includes('industrial')) {
      recommendations.push('Maintain electrical maintenance log');
      recommendations.push('Test RCDs quarterly as per IET Code of Practice');
    }
    
    return recommendations;
  };

  const overallCondition = progress.testResults.every((r) => r.passed !== false)
    ? 'SATISFACTORY'
    : 'UNSATISFACTORY';

  const scheduleData = generateScheduleOfTestResults();
  const observations = generateObservations();
  const recommendations = generateRecommendations();
  const nextInspectionDate = calculateNextInspectionDate();

  const copyCertificateData = () => {
    const markdown = `# ELECTRICAL INSTALLATION CERTIFICATE - SCHEDULE OF TEST RESULTS

**Project:** ${projectName}
**Location:** ${location}
**Date of Installation:** ${installationDate}
**Next Inspection Due:** ${nextInspectionDate}
**Overall Condition:** ${overallCondition}

## Schedule of Test Results

| Ref | Test Description | Measured Value | Unit | Pass/Fail | Notes |
|-----|-----------------|----------------|------|-----------|-------|
${scheduleData.map((row) => 
  `| ${row.ref} | ${row.description} | ${row.value} | ${row.unit} | ${row.passed} | ${row.notes} |`
).join('\n')}

## Observations

${observations.map((obs, i) => `${i + 1}. ${obs}`).join('\n')}

## Recommendations

${recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

---
*Generated by Sparky AI Commissioning Agent*
*Data exported: ${new Date().toISOString()}*
`;

    navigator.clipboard.writeText(markdown);
    toast.success("Certificate data copied!", {
      description: "Paste into your certification software or document",
    });
  };

  const exportJSON = () => {
    const certificateData = {
      projectInfo: {
        projectName,
        location,
        installationDate,
        installationType: progress.installationType,
      },
      scheduleOfTestResults: scheduleData,
      observations,
      recommendations,
      overallCondition,
      nextInspectionDate,
      exportedAt: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(certificateData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `certificate-data-${projectName.replace(/\s+/g, '-')}-${installationDate}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Certificate data exported!", {
      description: "JSON file downloaded successfully",
    });
  };

  return (
    <Card className="bg-card border-elec-yellow/20 overflow-hidden">
      <button
        onClick={() => setShowCertificateData(!showCertificateData)}
        className="w-full p-5 text-left hover:bg-elec-yellow/5 transition-colors"
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="h-6 w-6 text-elec-yellow" />
            <div>
              <h3 className="text-lg font-bold text-white">Certificate Pre-Fill Data</h3>
              <p className="text-sm text-white/70 mt-1">
                Ready for EIC/EICR software - {scheduleData.length} test results recorded
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className={`px-3 py-1 rounded-full ${
              overallCondition === 'SATISFACTORY' 
                ? 'bg-green-500/10 border border-green-500/30 text-green-400' 
                : 'bg-red-500/10 border border-red-500/30 text-red-400'
            }`}>
              <span className="text-xs font-semibold">{overallCondition}</span>
            </div>
          </div>
        </div>
      </button>

      {showCertificateData && (
        <div className="px-5 pb-5 space-y-5 border-t border-elec-yellow/20">
          {/* Actions */}
          <div className="pt-5 flex flex-wrap gap-2">
            <Button
              onClick={copyCertificateData}
              variant="outline"
              size="sm"
              className="border-elec-yellow/30 hover:bg-elec-yellow/10"
            >
              <Copy className="h-4 w-4 mr-2" />
              Copy Markdown
            </Button>
            <Button
              onClick={exportJSON}
              variant="outline"
              size="sm"
              className="border-elec-yellow/30 hover:bg-elec-yellow/10"
            >
              <Download className="h-4 w-4 mr-2" />
              Export JSON
            </Button>
          </div>

          {/* Schedule of Test Results */}
          <div>
            <h4 className="text-base font-semibold text-white mb-3">Schedule of Test Results</h4>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-elec-yellow/20">
                    <th className="text-left py-2 text-white/70 font-medium">Ref</th>
                    <th className="text-left py-2 text-white/70 font-medium">Test</th>
                    <th className="text-left py-2 text-white/70 font-medium">Value</th>
                    <th className="text-left py-2 text-white/70 font-medium">Result</th>
                  </tr>
                </thead>
                <tbody>
                  {scheduleData.map((row, index) => (
                    <tr key={index} className="border-b border-elec-yellow/10">
                      <td className="py-2 text-white">{row.ref}</td>
                      <td className="py-2 text-white">{row.description}</td>
                      <td className="py-2 text-white">{row.value} {row.unit}</td>
                      <td className="py-2">
                        <span className={`px-2 py-1 rounded text-xs font-semibold ${
                          row.passed === 'PASS' 
                            ? 'bg-green-500/10 text-green-400' 
                            : row.passed === 'FAIL'
                            ? 'bg-red-500/10 text-red-400'
                            : 'bg-gray-500/10 text-gray-400'
                        }`}>
                          {row.passed}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Observations */}
          <div>
            <h4 className="text-base font-semibold text-white mb-3">Observations</h4>
            <ul className="space-y-2">
              {observations.map((obs, index) => (
                <li key={index} className="text-sm text-white/80 bg-background/40 p-3 rounded-lg">
                  {index + 1}. {obs}
                </li>
              ))}
            </ul>
          </div>

          {/* Recommendations */}
          <div>
            <h4 className="text-base font-semibold text-white mb-3">Recommendations</h4>
            <ul className="space-y-2">
              {recommendations.map((rec, index) => (
                <li key={index} className="text-sm text-white/80 bg-background/40 p-3 rounded-lg">
                  {index + 1}. {rec}
                </li>
              ))}
            </ul>
          </div>

          {/* Next Inspection */}
          <div className="bg-elec-yellow/10 border border-elec-yellow/30 rounded-lg p-4">
            <p className="text-sm text-white/70 mb-1">Next Inspection Recommended By:</p>
            <p className="text-lg font-bold text-elec-yellow">{nextInspectionDate}</p>
            <p className="text-xs text-white/60 mt-2">
              Based on BS 7671:2018+A2:2024 requirements for {progress.installationType} installations
            </p>
          </div>
        </div>
      )}
    </Card>
  );
};
