
export interface RegulationData {
  number: string;
  title: string;
  part: number;
  section: string;
  content: string;
  keywords: string[];
  relatedRegs: string[];
  apprenticeNote?: string;
  testMethod?: string;
  safetyTip?: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  frequency: 'common' | 'frequent' | 'occasional';
  category: 'testing' | 'protection' | 'installation' | 'special-locations' | 'earthing' | 'cables' | 'equipment';
}

// Comprehensive BS7671 regulation database
export const REGULATIONS_DATABASE: RegulationData[] = [
  // Part 1 - Scope, Object and Fundamental Principles
  {
    number: '110.1.1',
    title: 'Scope of BS 7671',
    part: 1,
    section: 'Scope and Object',
    content: 'These Regulations apply to the design, erection, verification and periodic inspection and testing of electrical installations.',
    keywords: ['scope', 'design', 'erection', 'verification', 'inspection', 'testing'],
    relatedRegs: ['610.1', '612.1'],
    apprenticeNote: 'This is what BS 7671 covers - everything from design to testing electrical installations.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '131.1',
    title: 'Protection against electric shock',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Persons and livestock shall be protected against dangers that may arise from contact with live parts of the installation.',
    keywords: ['protection', 'electric shock', 'live parts', 'contact'],
    relatedRegs: ['411.1', '412.1'],
    apprenticeNote: 'Fundamental safety principle - prevent people touching live parts!',
    safetyTip: 'This is why we have insulation, barriers, and RCD protection.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '131.2.1',
    title: 'Protection against thermal effects',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Persons, livestock and property shall be protected against harmful effects of heat or thermal radiation.',
    keywords: ['thermal effects', 'heat', 'fire protection', 'overheating'],
    relatedRegs: ['421.1', '422.1'],
    apprenticeNote: 'Prevent fires and burns from electrical equipment getting too hot.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '131.3',
    title: 'Protection against overcurrent',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Persons and property shall be protected against injury and damage due to excessive current.',
    keywords: ['overcurrent', 'protection', 'excessive current', 'fuses', 'MCB'],
    relatedRegs: ['433.1', '434.1'],
    apprenticeNote: 'Why we need fuses and MCBs - to stop excessive current causing damage.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },

  // Part 4 - Protection for Safety (Expanded)
  {
    number: '411.1',
    title: 'General requirements for protection against electric shock',
    part: 4,
    section: 'Protection for Safety',
    content: 'Protection against electric shock shall be provided by basic protection and fault protection.',
    keywords: ['electric shock', 'basic protection', 'fault protection'],
    relatedRegs: ['411.2', '411.3'],
    apprenticeNote: 'Two layers of protection: basic (prevent touching live parts) and fault (protection when things go wrong).',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '411.2.1',
    title: 'Basic protection by insulation',
    part: 4,
    section: 'Protection for Safety',
    content: 'Live parts shall be completely covered with insulation which can be removed only by destruction.',
    keywords: ['basic protection', 'insulation', 'live parts', 'covering'],
    relatedRegs: ['416.1', '416.2'],
    apprenticeNote: 'Cable insulation prevents you touching live conductors - first line of defence.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '411.3.1.1',
    title: 'Automatic disconnection - general',
    part: 4,
    section: 'Protection for Safety',
    content: 'A protective device shall automatically disconnect the supply in case of a fault.',
    keywords: ['automatic disconnection', 'protective device', 'fault', 'supply'],
    relatedRegs: ['411.3.2', '411.4'],
    apprenticeNote: 'MCBs, RCDs and fuses must trip automatically when there\'s a fault.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '411.3.3',
    title: 'Additional protection by RCD',
    part: 4,
    section: 'Protection for Safety',
    content: 'For socket-outlets with a rated current not exceeding 20 A and for mobile equipment outdoors, additional protection by RCD (30mA) shall be provided.',
    keywords: ['RCD', 'socket outlets', 'additional protection', 'outdoor', '30mA', '20A'],
    relatedRegs: ['415.1.1', '531.2.4', '701.411.3.3'],
    apprenticeNote: 'Most sockets need 30mA RCD protection. Essential safety requirement!',
    testMethod: 'Check all sockets ≤20A are RCD protected. Test RCD operation.',
    safetyTip: 'No RCD on sockets = electrocution risk from damaged appliances!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'protection'
  },
  {
    number: '411.4.5',
    title: 'Maximum earth fault loop impedance',
    part: 4,
    section: 'Protection for Safety',
    content: 'The earth fault loop impedance at every point of utilisation shall not exceed the values given in the relevant tables.',
    keywords: ['earth fault', 'loop impedance', 'Zs', 'maximum values', 'tables'],
    relatedRegs: ['Table 41.3', '612.8'],
    apprenticeNote: 'Zs must be low enough for protective device to operate in time. Critical safety requirement!',
    testMethod: 'Measure Zs at outlets and compare with Table 41.3 values.',
    safetyTip: 'High Zs = MCB won\'t trip fast enough during earth fault = danger!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '411.5.3',
    title: 'TT system earth electrode resistance',
    part: 4,
    section: 'Protection for Safety',
    content: 'In TT systems, the sum of resistances of earth electrode and protective conductor shall be such that automatic disconnection occurs.',
    keywords: ['TT system', 'earth electrode', 'resistance', 'automatic disconnection'],
    relatedRegs: ['542.1.2', '612.7'],
    apprenticeNote: 'TT systems (rod in ground) need low earth electrode resistance for RCD to work properly.',
    testMethod: 'Test earth electrode resistance separately from installation.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'earthing'
  },

  // Protection Devices
  {
    number: '415.1.1',
    title: 'RCD characteristics for additional protection',
    part: 4,
    section: 'Protection for Safety',
    content: 'RCDs for additional protection shall have rated residual operating current ≤30mA and operating time ≤40ms at 5×IΔn.',
    keywords: ['RCD', 'characteristics', '30mA', '40ms', 'operating time'],
    relatedRegs: ['411.3.3', '612.10'],
    apprenticeNote: '30mA max current, 40ms max trip time at 150mA test current. Learn these limits!',
    testMethod: 'Test with RCD tester: 30mA should trip within 300ms, 150mA within 40ms.',
    safetyTip: 'Slow RCD = may not prevent electrocution! Check trip times regularly.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },

  // Overcurrent Protection (Part 4)
  {
    number: '433.1.1',
    title: 'Overcurrent protection of conductors',
    part: 4,
    section: 'Protection for Safety',
    content: 'Every conductor shall be protected against overcurrent by one or more automatic disconnection devices.',
    keywords: ['overcurrent', 'protection', 'conductors', 'automatic disconnection', 'MCB', 'fuse'],
    relatedRegs: ['433.1.204', '434.1'],
    apprenticeNote: 'Every cable needs overcurrent protection (MCB/fuse) rated correctly for cable size.',
    testMethod: 'Check MCB/fuse rating matches cable current carrying capacity.',
    safetyTip: 'Wrong protection rating = fire risk! Undersized = nuisance tripping, oversized = cable fire!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '433.1.204',
    title: 'Overcurrent protection for ring circuits',
    part: 4,
    section: 'Protection for Safety',
    content: 'Ring final circuits shall be protected by a single overcurrent protective device, the rating of which shall not exceed 32A.',
    keywords: ['ring circuit', 'overcurrent protection', '32A', 'single device'],
    relatedRegs: ['433.1.1', 'Appendix 15'],
    apprenticeNote: 'Ring circuits maximum 32A protection. Both legs share the load.',
    testMethod: 'Check ring circuit protection is 32A max and ring integrity is maintained.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },

  // Part 5 - Selection and Erection (Expanded)
  {
    number: '314.1',
    title: 'Division of installation',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every installation shall be divided into circuits to avoid danger and minimise inconvenience in case of fault.',
    keywords: ['division', 'circuits', 'danger', 'inconvenience', 'fault'],
    relatedRegs: ['314.2', '537.2'],
    apprenticeNote: 'Separate circuits by function - lighting, sockets, cooker, etc. Makes fault finding easier.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '314.2',
    title: 'Separate circuits for safety services',
    part: 5,
    section: 'Selection and Erection',
    content: 'Circuits for safety services shall be independent of other circuits.',
    keywords: ['safety services', 'independent circuits', 'fire alarms', 'emergency lighting'],
    relatedRegs: ['314.1', '560.6'],
    apprenticeNote: 'Fire alarms, emergency lighting need their own circuits - can\'t share with normal power.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'installation'
  },

  // Cable Selection and Installation
  {
    number: '521.5.1',
    title: 'Minimum cross-sectional area of conductors',
    part: 5,
    section: 'Selection and Erection',
    content: 'The cross-sectional area of line and neutral conductors shall be not less than the values specified in Table 52.1.',
    keywords: ['cross-sectional area', 'conductors', 'minimum', 'Table 52.1'],
    relatedRegs: ['Table 52.1', '523.1'],
    apprenticeNote: 'Minimum cable sizes: 1.5mm² for lighting, 2.5mm² for sockets in most cases.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '522.6.201',
    title: 'Cables in walls - general',
    part: 5,
    section: 'Selection and Erection',
    content: 'A cable concealed in a wall shall be installed in such a way that it is not liable to be damaged by nails, screws, or similar.',
    keywords: ['cables', 'walls', 'concealed', 'damage', 'nails', 'screws'],
    relatedRegs: ['522.6.204', '522.6.202'],
    apprenticeNote: 'Cables in walls must be protected from mechanical damage - run in safe zones or use protection.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '522.6.202',
    title: 'Cables in walls - safe zones',
    part: 5,
    section: 'Selection and Erection',
    content: 'Cables shall be run in the permitted zones shown in Figure 52.1, or be provided with additional protection.',
    keywords: ['safe zones', 'cables', 'walls', 'Figure 52.1', 'additional protection'],
    relatedRegs: ['522.6.201', '522.6.204'],
    apprenticeNote: 'Run cables in safe zones (top/bottom 150mm, sides 150mm from corners) or use RCD protection.',
    testMethod: 'Check cable routes comply with safe zones or have RCD protection.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '522.6.204',
    title: 'Cables concealed in walls - RCD protection',
    part: 5,
    section: 'Selection and Erection',
    content: 'A cable concealed in a wall at depth <50mm shall be protected against mechanical damage or protected by 30mA RCD.',
    keywords: ['cables', 'concealed', 'walls', '50mm', 'mechanical protection', 'RCD'],
    relatedRegs: ['522.6.201', '411.3.3'],
    apprenticeNote: 'Cables in walls need protection: >50mm deep, or metal protection, or 30mA RCD.',
    testMethod: 'Check cable routes, depths, and RCD protection during inspection.',
    safetyTip: 'Unprotected cables in walls = nail/screw hazard! Could cause electrocution.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '523.1',
    title: 'Current-carrying capacity of conductors',
    part: 5,
    section: 'Selection and Erection',
    content: 'The current-carrying capacity of conductors shall be such that the design current does not exceed the rated current.',
    keywords: ['current-carrying capacity', 'conductors', 'design current', 'rated current'],
    relatedRegs: ['Appendix 4', '525.1'],
    apprenticeNote: 'Cable must be big enough to carry the load current safely without overheating.',
    testMethod: 'Check cable size against load using current capacity tables.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },

  // Connections and Joints
  {
    number: '526.1',
    title: 'Electrical connections - general',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every electrical connection shall provide durable electrical continuity and adequate mechanical strength.',
    keywords: ['electrical connections', 'durable', 'continuity', 'mechanical strength'],
    relatedRegs: ['526.3', '526.8'],
    apprenticeNote: 'All connections must be reliable and strong - poor connections cause fires!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '526.3',
    title: 'Accessibility of connections',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every connection and joint shall be accessible for inspection, testing and maintenance, except for specific permitted cases.',
    keywords: ['connections', 'joints', 'accessible', 'inspection', 'testing', 'maintenance'],
    relatedRegs: ['526.1', '526.8'],
    apprenticeNote: 'All connections must be accessible - no joints buried in walls! Use proper enclosures.',
    testMethod: 'Visual inspection - check all connections can be accessed for testing.',
    safetyTip: 'Hidden connections = fire/failure risk! Always use maintenance-free connections if inaccessible.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '526.8',
    title: 'Maintenance-free connections',
    part: 5,
    section: 'Selection and Erection',
    content: 'Connections may be buried or concealed only if they are maintenance-free and suitably enclosed.',
    keywords: ['maintenance-free', 'connections', 'buried', 'concealed', 'enclosed'],
    relatedRegs: ['526.3', '526.1'],
    apprenticeNote: 'Only certain connection types can be hidden - compression joints, welded joints, etc.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'installation'
  },

  // Isolation and Switching
  {
    number: '537.1.4',
    title: 'Isolation - general requirements',
    part: 5,
    section: 'Selection and Erection',
    content: 'Means of isolation shall be provided to enable every circuit to be isolated from all sources of electrical energy.',
    keywords: ['isolation', 'circuit', 'electrical energy', 'sources'],
    relatedRegs: ['537.2.1.1', '462.1'],
    apprenticeNote: 'Every circuit needs isolation for safe working - main switch, MCBs, local isolators.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '537.2.1.1',
    title: 'Isolation requirements',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every circuit shall be provided with means of isolation such that it may be cut off from every source of electrical energy.',
    keywords: ['isolation', 'circuit', 'isolator', 'electrical energy', 'safety'],
    relatedRegs: ['537.1.4', '462.1'],
    apprenticeNote: 'Every circuit needs an isolator for safe maintenance. Main switch isolates whole installation.',
    testMethod: 'Check isolators actually isolate all poles and operate correctly.',
    safetyTip: 'No isolation = maintenance danger! Lock off isolators during work.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },

  // Earthing and Protective Conductors
  {
    number: '542.1.1',
    title: 'Main earthing terminal',
    part: 5,
    section: 'Selection and Erection',
    content: 'A main earthing terminal shall be provided for the connection of protective conductors, functional earthing conductors and bonding conductors.',
    keywords: ['main earthing terminal', 'protective conductors', 'bonding', 'connection'],
    relatedRegs: ['542.1.2', '544.1'],
    apprenticeNote: 'Central point where all earth connections come together - usually at the consumer unit.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: '542.1.2',
    title: 'Earth electrode resistance',
    part: 5,
    section: 'Selection and Erection',
    content: 'The resistance to earth of an earth electrode shall be as low as practicable.',
    keywords: ['earth electrode', 'resistance', 'low', 'practicable'],
    relatedRegs: ['542.1.1', '411.5.3'],
    apprenticeNote: 'Lower earth electrode resistance = better protection. Target less than 200Ω where possible.',
    testMethod: 'Measure with earth electrode tester, not normal test equipment.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'earthing'
  },
  {
    number: '543.1.1',
    title: 'Cross-sectional area of protective conductors',
    part: 5,
    section: 'Selection and Erection',
    content: 'The cross-sectional area of protective conductors shall be determined by Regulation 543.1.3 or Table 54.7.',
    keywords: ['protective conductors', 'cross-sectional area', 'sizing', 'earth', 'cpc'],
    relatedRegs: ['543.1.3', 'Table 54.7', '612.2.1'],
    apprenticeNote: 'Earth wire size depends on line conductor size. Use Table 54.7 for quick reference.',
    testMethod: 'Check earth conductor sizes match Table 54.7 requirements during inspection.',
    safetyTip: 'Undersized earth = won\'t carry fault current safely = fire/shock risk!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: '544.1.1',
    title: 'Main equipotential bonding',
    part: 5,
    section: 'Selection and Erection',
    content: 'Main equipotential bonding conductors shall connect extraneous-conductive-parts to the main earthing terminal.',
    keywords: ['main bonding', 'equipotential', 'extraneous-conductive-parts', 'main earthing terminal'],
    relatedRegs: ['544.1.2', '542.1.1'],
    apprenticeNote: 'Bond metal pipes, structural steel to earth - prevents dangerous voltages between metal parts.',
    testMethod: 'Check continuity from main earth terminal to all bonded metalwork.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },

  // Part 6 - Inspection and Testing (Expanded with more detail)
  {
    number: '610.1',
    title: 'General requirements for inspection',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Every installation shall be inspected before being put into service to verify compliance with these Regulations.',
    keywords: ['inspection', 'installation', 'service', 'compliance', 'verification'],
    relatedRegs: ['610.2', '612.1'],
    apprenticeNote: 'Visual inspection comes first - check everything looks right before any testing.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'testing'
  },
  {
    number: '610.2',
    title: 'Inspection checklist',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The inspection shall include verification of connection of conductors, identification of conductors, routing of cables, selection of equipment.',
    keywords: ['inspection checklist', 'connections', 'identification', 'routing', 'equipment selection'],
    relatedRegs: ['610.1', 'Appendix 6'],
    apprenticeNote: 'Systematic visual check - connections, cable routes, equipment suitability, labelling.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'testing'
  },
  {
    number: '612.1',
    title: 'General requirements for testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Every installation shall be inspected and tested during erection and on completion before being put into service to verify that the requirements of the regulations have been met.',
    keywords: ['inspection', 'testing', 'installation', 'completion', 'verification'],
    relatedRegs: ['610.1', '612.2.1'],
    apprenticeNote: 'This is the foundation regulation - every installation MUST be tested before energising!',
    testMethod: 'Visual inspection followed by testing in sequence per Regulation 612.1',
    safetyTip: 'Never energise an installation without proper testing - lives depend on it!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'testing'
  },
  {
    number: '612.2.1',
    title: 'Continuity of protective conductors',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The continuity of every protective conductor, including main and supplementary equipotential bonding conductors, shall be verified.',
    keywords: ['continuity', 'protective conductors', 'testing', 'bonding', 'earth'],
    relatedRegs: ['612.1', '543.1.1', '612.2.2'],
    apprenticeNote: 'First test to perform! Use low resistance ohmmeter with test current 200mA minimum.',
    testMethod: 'Test between earth terminal at DB and all earth points. Reading should be very low (typically <0.5Ω)',
    safetyTip: 'Broken earth = death trap! Always test earth continuity first.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.2.2',
    title: 'Continuity of ring final circuit conductors',
    part: 6,
    section: 'Inspection and Testing',
    content: 'For ring final circuits, the continuity of both the line and neutral conductors and the protective conductor shall be verified.',
    keywords: ['ring circuit', 'continuity', 'line', 'neutral', 'protective conductor'],
    relatedRegs: ['612.2.1', 'Appendix 15'],
    apprenticeNote: 'Ring circuits need special testing! Test line, neutral AND earth rings separately.',
    testMethod: 'End-to-end test, then cross-connect test. All readings should be similar and low.',
    safetyTip: 'Broken ring = overload risk! Use the Figure-of-8 method for accurate testing.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.3.1',
    title: 'Insulation resistance testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The insulation resistance between live conductors and between live conductors and earth shall be measured.',
    keywords: ['insulation resistance', 'testing', 'live conductors', 'earth', 'megger'],
    relatedRegs: ['612.3.2', 'Table 61'],
    apprenticeNote: 'Use correct test voltage: 250V for SELV, 500V for up to 500V circuits, 1000V for higher voltages.',
    testMethod: 'Test L-N, L-E, N-E. Minimum 1MΩ for most circuits (0.5MΩ for SELV/electronic equipment)',
    safetyTip: 'Remove/isolate electronic equipment before testing - high voltage will damage sensitive components!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.3.2',
    title: 'Minimum insulation resistance values',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Minimum insulation resistance values: SELV circuits 0.25MΩ, up to 500V 1MΩ, above 500V 1MΩ.',
    keywords: ['minimum', 'insulation resistance', 'values', 'MΩ', 'SELV'],
    relatedRegs: ['612.3.1', 'Table 61'],
    apprenticeNote: 'Learn these values by heart! Most common circuits need minimum 1MΩ.',
    testMethod: 'If reading is below minimum, investigate: dampness, damaged cables, or poor terminations.',
    safetyTip: 'Low insulation = shock risk! Never ignore low readings.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.4.1',
    title: 'Protection by SELV - testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'For SELV circuits, insulation resistance between SELV circuit and other circuits shall be verified.',
    keywords: ['SELV', 'testing', 'insulation', 'separation', 'isolation'],
    relatedRegs: ['414.1', '612.3.1'],
    apprenticeNote: 'SELV circuits must be properly separated from mains voltage circuits.',
    testMethod: 'Test insulation between SELV and all other circuits - minimum 0.25MΩ at 250V.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'testing'
  },
  {
    number: '612.5',
    title: 'Protection by electrical separation - testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'For circuits with electrical separation, insulation resistance shall be measured between separated circuits.',
    keywords: ['electrical separation', 'testing', 'insulation', 'isolated circuits'],
    relatedRegs: ['413.1', '612.3.1'],
    apprenticeNote: 'Electrically separated circuits (isolation transformers) need testing between primary and secondary.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'testing'
  },
  {
    number: '612.6',
    title: 'Polarity testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'It shall be verified that single-pole control and protective devices are connected in the line conductor only.',
    keywords: ['polarity', 'testing', 'single-pole', 'control devices', 'line conductor'],
    relatedRegs: ['612.1', '132.14'],
    apprenticeNote: 'Check all switches, fuses, and MCBs are in the line (not neutral). Critical safety test!',
    testMethod: 'Use continuity tester or bell set. Test with supply isolated.',
    safetyTip: 'Wrong polarity = live neutral = death! Always verify polarity.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.7',
    title: 'Earth electrode resistance',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Where an earth electrode is used, its resistance to earth shall be measured.',
    keywords: ['earth electrode', 'resistance', 'earth', 'measurement', 'TT system'],
    relatedRegs: ['542.2.1', '411.5.3'],
    apprenticeNote: 'For TT systems (rod in ground). Use earth electrode tester, not megger!',
    testMethod: 'Disconnect electrode from installation. Use 3 or 4-terminal method.',
    safetyTip: 'High earth electrode resistance in TT system = RCD may not operate correctly!',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'earthing'
  },
  {
    number: '612.8',
    title: 'Earth fault loop impedance (Zs)',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The earth fault loop impedance shall be measured at the origin and at all outlets.',
    keywords: ['earth fault', 'loop impedance', 'Zs', 'outlets', 'measurement'],
    relatedRegs: ['411.4.5', 'Table 41.3', '612.9'],
    apprenticeNote: 'Critical test! Zs must be low enough for MCB/fuse to operate within required time.',
    testMethod: 'Test at consumer unit and furthest outlets. Compare with maximum values in Table 41.3.',
    safetyTip: 'High Zs = MCB won\'t trip in fault = fire/death risk!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.9',
    title: 'Prospective fault current',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The prospective short-circuit current and earth fault current shall be measured or determined by calculation.',
    keywords: ['prospective fault current', 'short-circuit', 'earth fault', 'calculation'],
    relatedRegs: ['612.8', '434.1', '435.1'],
    apprenticeNote: 'Ensures protective devices can handle fault currents. High current = need higher rated devices.',
    testMethod: 'Use prospective fault current tester at origin of installation.',
    safetyTip: 'Too high current = MCB may not break safely. Check device ratings!',
    difficulty: 'advanced',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.10',
    title: 'Functional testing of RCDs',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The effectiveness of any RCD shall be verified by a test simulating an appropriate fault condition.',
    keywords: ['functional testing', 'RCD', 'test', 'fault condition', 'trip'],
    relatedRegs: ['415.1.1', '531.2.4'],
    apprenticeNote: 'Test RCDs at rated current (30mA) and 5x rated current. Must trip within time limits.',
    testMethod: 'Use RCD tester. Test trip time at 1x, 5x rated current. Check trip/no-trip thresholds.',
    safetyTip: 'RCD not working = no shock protection! Test regularly - quarterly for sockets!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.11',
    title: 'Phase sequence testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Where the phase sequence is important for the operation of equipment, it shall be verified.',
    keywords: ['phase sequence', 'testing', 'three-phase', 'motor rotation'],
    relatedRegs: ['612.1', '551.1'],
    apprenticeNote: 'Three-phase motors need correct phase sequence to rotate the right direction.',
    testMethod: 'Use phase sequence indicator before connecting motors or other phase-sensitive equipment.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'testing'
  },

  // Part 7 - Special Locations (Expanded)
  {
    number: '700.1',
    title: 'General requirements for special locations',
    part: 7,
    section: 'Special Locations',
    content: 'Special locations require additional measures due to increased risk of electric shock, fire, or explosion.',
    keywords: ['special locations', 'additional measures', 'risk', 'shock', 'fire', 'explosion'],
    relatedRegs: ['701.1', '702.1', '703.1'],
    apprenticeNote: 'Bathrooms, swimming pools, saunas etc. need extra safety measures.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },

  // Bathrooms and Wet Locations
  {
    number: '701.32',
    title: 'Classification of external influences - Bathrooms',
    part: 7,
    section: 'Special Locations - Bathrooms',
    content: 'Zone 0: IPX7, Zone 1: IPX4, Zone 2: IPX4, Outside zones: suitable for conditions.',
    keywords: ['bathroom', 'zones', 'IP rating', 'water protection', 'IPX4', 'IPX7'],
    relatedRegs: ['701.411.3.3', 'Appendix 5'],
    apprenticeNote: 'Learn bathroom zones! Zone 0 (inside bath) = IPX7, Zones 1&2 = IPX4 minimum.',
    testMethod: 'Check IP ratings of equipment match zone requirements during inspection.',
    safetyTip: 'Wrong IP rating in bathroom = electrocution from water ingress!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },
  {
    number: '701.411.3.3',
    title: 'Additional protection in bathrooms',
    part: 7,
    section: 'Special Locations - Bathrooms',
    content: 'Additional protection by RCD with IΔn ≤30mA shall be provided for all circuits in the location.',
    keywords: ['bathroom', 'RCD', '30mA', 'additional protection', 'all circuits'],
    relatedRegs: ['701.32', '415.1.1'],
    apprenticeNote: 'ALL circuits in bathrooms need 30mA RCD protection - no exceptions!',
    testMethod: 'Check every circuit serving bathroom has 30mA RCD protection.',
    safetyTip: 'Water + electricity = death! RCDs are essential in wet locations.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },
  {
    number: '701.512.3',
    title: 'Socket outlets in bathrooms',
    part: 7,
    section: 'Special Locations - Bathrooms',
    content: 'Socket outlets are not permitted in zones 0, 1 and 2. Shaver sockets to BS EN 61558-2-5 are permitted in zone 2.',
    keywords: ['socket outlets', 'bathrooms', 'zones', 'prohibited', 'shaver sockets'],
    relatedRegs: ['701.32', '701.411.3.3'],
    apprenticeNote: 'No normal sockets near baths/showers! Only special shaver sockets allowed in zone 2.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },

  // Swimming Pools
  {
    number: '702.32',
    title: 'Swimming pool zones',
    part: 7,
    section: 'Special Locations - Swimming Pools',
    content: 'Zone 0: interior of basin, Zone 1: 2m from edge of basin, Zone 2: 1.5m from zone 1.',
    keywords: ['swimming pool', 'zones', 'basin', 'distances', 'water'],
    relatedRegs: ['702.410', '702.55'],
    apprenticeNote: 'Swimming pools have different zones to bathrooms - learn the distances!',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'special-locations'
  },

  // Agricultural Locations
  {
    number: '705.411.1',
    title: 'Agricultural locations - RCD protection',
    part: 7,
    section: 'Special Locations - Agricultural',
    content: 'All circuits in agricultural locations shall have additional protection by RCD with IΔn ≤30mA.',
    keywords: ['agricultural', 'RCD', '30mA', 'all circuits', 'livestock'],
    relatedRegs: ['705.32', '415.1.1'],
    apprenticeNote: 'Farms need RCD protection on everything - animals are more sensitive to electric shock.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'special-locations'
  },

  // Tables and Reference Data
  {
    number: 'Table 41.3',
    title: 'Maximum earth fault loop impedance (Zs)',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Maximum Zs values for MCBs: 6A Type B = 7.67Ω, 10A = 4.60Ω, 16A = 2.87Ω, 20A = 2.30Ω, 32A = 1.44Ω',
    keywords: ['Zs', 'maximum', 'earth fault', 'loop impedance', 'MCB', 'table'],
    relatedRegs: ['612.8', '411.4.5'],
    apprenticeNote: 'Learn common Zs values! Apply 0.8 correction factor for measured values.',
    testMethod: 'Measure Zs and compare with Table 41.3 values (remember 0.8 factor).',
    safetyTip: 'Zs too high = MCB won\'t disconnect fault current in time = danger!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 41.4',
    title: 'Maximum earth fault loop impedance for RCBOs',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Maximum Zs values for RCBOs are generally higher than MCBs due to RCD protection.',
    keywords: ['Zs', 'RCBO', 'maximum', 'earth fault', 'loop impedance'],
    relatedRegs: ['Table 41.3', '531.2'],
    apprenticeNote: 'RCBOs have higher Zs limits because RCD part provides additional protection.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'testing'
  },
  {
    number: 'Table 52.1',
    title: 'Minimum cross-sectional area of conductors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'Minimum conductor sizes: Power circuits 2.5mm², Lighting circuits 1.5mm², Control circuits 1.5mm²',
    keywords: ['minimum', 'cross-sectional area', 'conductors', 'power', 'lighting'],
    relatedRegs: ['521.5.1', '523.1'],
    apprenticeNote: 'Standard minimums: 2.5mm² for sockets, 1.5mm² for lights in domestic installations.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: 'Table 54.7',
    title: 'Minimum cross-sectional area of protective conductors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'CPC sizes: Line ≤16mm² CPC = Line, 16mm² < Line ≤35mm² CPC = 16mm², Line >35mm² CPC = Line/2',
    keywords: ['protective conductors', 'CPC', 'minimum', 'cross-sectional area', 'earth'],
    relatedRegs: ['543.1.1', '543.1.3'],
    apprenticeNote: 'Earth wire sizing: same as line up to 16mm², then use table or calculation.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: 'Table 61',
    title: 'Test voltages for insulation resistance',
    part: 6,
    section: 'Inspection and Testing - Tables',
    content: 'Test voltages: SELV/PELV circuits = 250V DC, Circuits up to 500V = 500V DC, Above 500V = 1000V DC',
    keywords: ['test voltage', 'insulation resistance', 'SELV', '500V', '1000V', 'DC'],
    relatedRegs: ['612.3.1', '612.3.2'],
    apprenticeNote: 'Use correct test voltage for insulation testing - wrong voltage gives false results!',
    testMethod: 'Select correct voltage on megger based on circuit voltage.',
    safetyTip: 'Too high test voltage = damage equipment! Too low = false pass!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },

  // Appendices
  {
    number: 'Appendix 15',
    title: 'Ring final circuit design and testing',
    part: 6,
    section: 'Appendices',
    content: 'Ring circuits require specific design and testing methods to ensure proper load sharing.',
    keywords: ['ring circuit', 'design', 'testing', 'load sharing', 'continuity'],
    relatedRegs: ['612.2.2', '433.1.204'],
    apprenticeNote: 'Ring circuits are unique to UK. Must test properly to ensure both legs share load.',
    testMethod: 'End-to-end test, then sockets test with figure-of-8 method.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'testing'
  },

  // Periodic Testing
  {
    number: '643.7',
    title: 'Periodic testing of RCDs',
    part: 6,
    section: 'Inspection and Testing',
    content: 'RCDs shall be tested at appropriate intervals to ensure they remain functional.',
    keywords: ['periodic testing', 'RCD', 'intervals', 'functional', 'maintenance'],
    relatedRegs: ['612.10', '415.1.1'],
    apprenticeNote: 'RCDs need regular testing: quarterly for socket RCDs using test button.',
    testMethod: 'Use test button monthly, proper RCD tester annually or after any electrical work.',
    safetyTip: 'RCDs can fail over time - regular testing saves lives!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'testing'
  },

  // Emergency Systems
  {
    number: '560.6.1',
    title: 'Emergency lighting systems',
    part: 5,
    section: 'Selection and Erection',
    content: 'Emergency lighting shall be supplied from a source independent of the normal lighting supply.',
    keywords: ['emergency lighting', 'independent supply', 'safety systems'],
    relatedRegs: ['314.2', '563.1'],
    apprenticeNote: 'Emergency lights need separate supply - usually battery or generator backup.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'installation'
  },

  // Medical Locations
  {
    number: '710.411.3.2.6',
    title: 'Medical locations - RCD protection',
    part: 7,
    section: 'Special Locations - Medical',
    content: 'RCD protection may not be suitable in medical locations where loss of supply could endanger life.',
    keywords: ['medical locations', 'RCD', 'life support', 'supply continuity'],
    relatedRegs: ['710.1', '411.3.3'],
    apprenticeNote: 'Hospitals/medical areas may avoid RCDs where equipment must not trip unexpectedly.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'special-locations'
  },

  // Additional practical regulations
  {
    number: '132.14',
    title: 'Single-pole switching',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Every fuse and single-pole control and protective device shall be inserted in the line conductor.',
    keywords: ['single-pole', 'switching', 'line conductor', 'fuse', 'control'],
    relatedRegs: ['612.6', '537.2'],
    apprenticeNote: 'Never switch or fuse the neutral - always the line conductor for safety.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '462.1',
    title: 'Isolation and switching',
    part: 4,
    section: 'Protection for Safety',
    content: 'Effective means shall be provided to prevent electrical energy from causing danger.',
    keywords: ['isolation', 'switching', 'electrical energy', 'danger', 'safety'],
    relatedRegs: ['537.1.4', '537.2.1.1'],
    apprenticeNote: 'Every installation needs proper isolation for safe working.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },

  // Equipment specific regulations
  {
    number: '531.2.4',
    title: 'RCD selection and application',
    part: 5,
    section: 'Selection and Erection',
    content: 'RCDs shall be selected according to their intended use and the characteristics of the circuits they protect.',
    keywords: ['RCD', 'selection', 'application', 'characteristics', 'circuits'],
    relatedRegs: ['415.1.1', '612.10'],
    apprenticeNote: 'Choose right RCD type: AC, A, or B type depending on loads connected.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'equipment'
  },

  // Low voltage systems
  {
    number: '414.1',
    title: 'SELV systems',
    part: 4,
    section: 'Protection for Safety',
    content: 'SELV systems shall not exceed 50V AC or 120V ripple-free DC and shall be separated from other circuits.',
    keywords: ['SELV', 'low voltage', '50V', 'separation', 'isolation'],
    relatedRegs: ['414.2', '612.4.1'],
    apprenticeNote: 'SELV = Safety Extra Low Voltage. Used for bathroom lights, garden lighting etc.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'protection'
  },

  // Additional critical regulations for comprehensive coverage
  {
    number: '132.2.1',
    title: 'Skills and knowledge',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Electrical work shall be carried out only by skilled persons or by ordinary persons under the supervision of skilled persons.',
    keywords: ['skilled person', 'competent', 'supervision', 'qualifications'],
    relatedRegs: ['16', 'Part P'],
    apprenticeNote: 'You must be competent or supervised! This is why apprenticeships exist.',
    safetyTip: 'Never work beyond your competence - electricity kills!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '132.16',
    title: 'Isolation and lock-off procedures',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Adequate precautions shall be taken to prevent electrical equipment from being inadvertently or unintentionally energised.',
    keywords: ['isolation', 'lock-off', 'safety procedures', 'energised'],
    relatedRegs: ['537.2.1.1', '462.1'],
    apprenticeNote: 'Isolation and lock-off prevents accidents during maintenance work.',
    safetyTip: 'Always prove dead before starting work - test your tester!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '411.6.4',
    title: 'IT system requirements',
    part: 4,
    section: 'Protection for Safety',
    content: 'IT systems shall have insulation monitoring and first fault indication.',
    keywords: ['IT system', 'insulation monitoring', 'first fault', 'industrial'],
    relatedRegs: ['312.2', '411.6.1'],
    apprenticeNote: 'IT systems (isolated neutral) used in hospitals and industry for supply continuity.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'protection'
  },
  {
    number: '413.1.1',
    title: 'Electrical separation requirements',
    part: 4,
    section: 'Protection for Safety',
    content: 'Protection by electrical separation requires a source with at least simple separation.',
    keywords: ['electrical separation', 'isolation transformer', 'simple separation'],
    relatedRegs: ['413.2', '612.5'],
    apprenticeNote: 'Isolation transformers provide electrical separation - used for safety in special situations.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'protection'
  },
  {
    number: '421.1.201',
    title: 'Fire protection - general',
    part: 4,
    section: 'Protection for Safety',
    content: 'Electrical installations shall be designed and installed to minimise risk of fire.',
    keywords: ['fire protection', 'thermal effects', 'installation design'],
    relatedRegs: ['422.1', '527.1'],
    apprenticeNote: 'Prevent electrical fires through proper design, installation and protection.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '422.2.1',
    title: 'Heat-producing equipment',
    part: 4,
    section: 'Protection for Safety',
    content: 'Equipment producing heat shall be installed to prevent fire risk to surrounding materials.',
    keywords: ['heat-producing equipment', 'fire risk', 'thermal protection'],
    relatedRegs: ['421.1.201', '559.4.1'],
    apprenticeNote: 'Keep heat sources away from combustible materials - use proper spacing and barriers.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'equipment'
  },
  {
    number: '512.1.2',
    title: 'Operational conditions',
    part: 5,
    section: 'Selection and Erection',
    content: 'Equipment shall be suitable for nominal voltage, current, frequency and power.',
    keywords: ['operational conditions', 'voltage', 'current', 'frequency', 'power'],
    relatedRegs: ['512.2', '533.1'],
    apprenticeNote: 'Always check equipment ratings match the supply - voltage, frequency, and power.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'equipment'
  },
  {
    number: '515.3',
    title: 'Prevention of mutual detrimental influence',
    part: 5,
    section: 'Selection and Erection',
    content: 'Electrical and non-electrical services shall not adversely affect each other.',
    keywords: ['mutual influence', 'services', 'interference', 'separation'],
    relatedRegs: ['528.1', '444.4'],
    apprenticeNote: 'Keep electrical cables separated from other services - gas, water, telecoms.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '528.1',
    title: 'Proximity to other services',
    part: 5,
    section: 'Selection and Erection',
    content: 'Electrical cables and other services shall be adequately separated or barriers provided.',
    keywords: ['proximity', 'services', 'separation', 'barriers', 'gas pipes'],
    relatedRegs: ['515.3', '528.3'],
    apprenticeNote: 'Maintain safe distances from gas pipes, water services - use barriers if needed.',
    testMethod: 'Check cable routes avoid other services or have adequate separation.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '533.1.1',
    title: 'Devices for fault protection',
    part: 5,
    section: 'Selection and Erection',
    content: 'Overcurrent protective devices shall be capable of breaking fault currents.',
    keywords: ['fault protection', 'overcurrent devices', 'breaking capacity', 'fault current'],
    relatedRegs: ['434.1', '612.9'],
    apprenticeNote: 'MCBs must have sufficient breaking capacity for the prospective fault current.',
    testMethod: 'Check MCB kA rating exceeds prospective fault current at that point.',
    safetyTip: 'Inadequate breaking capacity = MCB may explode during fault!',
    difficulty: 'advanced',
    frequency: 'frequent',
    category: 'protection'
  },
  {
    number: '551.4.3',
    title: 'Low voltage generating sets',
    part: 5,
    section: 'Selection and Erection',
    content: 'Generating sets shall not operate in parallel with the public supply unless specifically approved.',
    keywords: ['generating sets', 'parallel operation', 'public supply', 'generators'],
    relatedRegs: ['551.1', '551.7'],
    apprenticeNote: 'Generators must not feed back into the grid without proper protection and approval.',
    safetyTip: 'Backfeeding generators can kill utility workers! Use proper changeover switches.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'equipment'
  },
  {
    number: '559.10.3.1',
    title: 'Highway power supplies',
    part: 5,
    section: 'Selection and Erection',
    content: 'Highway power supplies shall have additional protection by 30mA RCD.',
    keywords: ['highway power', 'street lighting', 'RCD', '30mA', 'public areas'],
    relatedRegs: ['411.3.3', '559.10.1'],
    apprenticeNote: 'Street lighting and highway electrical supplies need RCD protection for public safety.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '704.410.3.10',
    title: 'Construction sites - reduced voltage',
    part: 7,
    section: 'Special Locations - Construction Sites',
    content: 'Hand-held equipment on construction sites shall be supplied at reduced voltage (110V CTE).',
    keywords: ['construction sites', 'reduced voltage', '110V', 'CTE', 'hand tools'],
    relatedRegs: ['704.411.3.1', '414.1'],
    apprenticeNote: '110V centre-tapped-earth (CTE) systems reduce shock risk on building sites.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '706.411.1.201',
    title: 'Conducting locations - RCD protection',
    part: 7,
    section: 'Special Locations - Conducting Locations',
    content: 'All circuits in conducting locations shall have 30mA RCD protection.',
    keywords: ['conducting locations', 'RCD', '30mA', 'metalwork', 'boiler rooms'],
    relatedRegs: ['706.32', '415.1.1'],
    apprenticeNote: 'Locations with extensive metalwork (boiler rooms, etc.) need RCD protection.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '708.553.1.14',
    title: 'Electrical installations in caravans',
    part: 7,
    section: 'Special Locations - Caravans',
    content: 'Caravan installations shall have 30mA RCD protection for all circuits.',
    keywords: ['caravans', 'mobile homes', 'RCD', '30mA', 'mobile installations'],
    relatedRegs: ['708.410', '415.1.1'],
    apprenticeNote: 'Caravans and mobile homes need comprehensive RCD protection due to mobility.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: 'Table 41.2',
    title: 'Maximum disconnection times',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'TN systems: 230V = 0.4s, 400V = 0.2s. TT systems: all voltages = 0.2s (RCD required).',
    keywords: ['disconnection times', 'TN system', 'TT system', 'fault clearance'],
    relatedRegs: ['411.3.2', '411.5.1'],
    apprenticeNote: 'Faults must be cleared quickly! TT systems need RCDs because earth loop impedance is high.',
    testMethod: 'Calculate disconnection time based on Zs and protective device characteristics.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 44.1',
    title: 'Minimum cross-sectional areas for PEN conductors',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'PEN conductors: minimum 10mm² copper or 16mm² aluminium in fixed installations.',
    keywords: ['PEN conductor', 'cross-sectional area', 'minimum', 'copper', 'aluminium'],
    relatedRegs: ['543.4.1', 'PME'],
    apprenticeNote: 'PEN = Protective Earth and Neutral combined. Used in PME (TN-C-S) systems.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'earthing'
  },
  {
    number: 'Table 53.4',
    title: 'Current-carrying capacity correction factors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'Apply correction factors for ambient temperature, grouping, thermal insulation, and soil thermal resistivity.',
    keywords: ['correction factors', 'current-carrying capacity', 'ambient temperature', 'grouping'],
    relatedRegs: ['523.1', 'Appendix 4'],
    apprenticeNote: 'Cable ratings must be corrected for installation conditions - very important for cable sizing!',
    testMethod: 'Calculate corrected cable rating = tabulated rating × all applicable correction factors.',
    safetyTip: 'Ignoring correction factors = cable overheating = fire risk!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '643.2.3',
    title: 'Periodic inspection frequency',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Domestic installations: 10 years. Commercial: 5 years. Industrial: 3 years or as required.',
    keywords: ['periodic inspection', 'frequency', 'domestic', 'commercial', 'industrial'],
    relatedRegs: ['643.1', '643.7'],
    apprenticeNote: 'Regular electrical safety checks prevent dangerous faults developing over time.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'testing'
  }
];
