export interface RegulationData {
  number: string;
  title: string;
  part: number;
  section: string;
  content: string;
  keywords: string[];
  relatedRegs: string[];
  apprenticeNote?: string;
  testMethod?: string;
  safetyTip?: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  frequency: 'common' | 'frequent' | 'occasional';
  category: 'testing' | 'protection' | 'installation' | 'special-locations' | 'earthing' | 'cables' | 'equipment';
}

// COMPREHENSIVE BS7671 regulation database - 80+ regulations with Zs 80% rule
export const REGULATIONS_DATABASE: RegulationData[] = [
  // Part 1 - Scope, Object and Fundamental Principles
  {
    number: '110.1.1',
    title: 'Scope of BS 7671',
    part: 1,
    section: 'Scope and Object',
    content: 'These Regulations apply to the design, erection, verification and periodic inspection and testing of electrical installations.',
    keywords: ['scope', 'design', 'erection', 'verification', 'inspection', 'testing'],
    relatedRegs: ['610.1', '612.1'],
    apprenticeNote: 'This is what BS 7671 covers - everything from design to testing electrical installations.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '131.1',
    title: 'Protection against electric shock',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Persons and livestock shall be protected against dangers that may arise from contact with live parts of the installation.',
    keywords: ['protection', 'electric shock', 'live parts', 'contact'],
    relatedRegs: ['411.1', '412.1'],
    apprenticeNote: 'Fundamental safety principle - prevent people touching live parts!',
    safetyTip: 'This is why we have insulation, barriers, and RCD protection.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '132.2.1',
    title: 'Skills and knowledge',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Electrical work shall be carried out only by skilled persons or by ordinary persons under the supervision of skilled persons.',
    keywords: ['skilled person', 'competent', 'supervision', 'qualifications'],
    relatedRegs: ['16', 'Part P'],
    apprenticeNote: 'You must be competent or supervised! This is why apprenticeships exist.',
    safetyTip: 'Never work beyond your competence - electricity kills!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '132.14',
    title: 'Single-pole switching',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Every fuse and single-pole control and protective device shall be inserted in the line conductor.',
    keywords: ['single-pole', 'switching', 'line conductor', 'fuse', 'control'],
    relatedRegs: ['612.6', '537.2'],
    apprenticeNote: 'Never switch or fuse the neutral - always the line conductor for safety.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '132.16',
    title: 'Isolation and lock-off procedures',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Adequate precautions shall be taken to prevent electrical equipment from being inadvertently or unintentionally energised.',
    keywords: ['isolation', 'lock-off', 'safety procedures', 'energised'],
    relatedRegs: ['537.2.1.1', '462.1'],
    apprenticeNote: 'Isolation and lock-off prevents accidents during maintenance work.',
    safetyTip: 'Always prove dead before starting work - test your tester!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },

  // Part 2 - Definitions (Amendment 3:2024)
  {
    number: 'Bidirectional protective device',
    title: 'Definition - Bidirectional protective device',
    part: 2,
    section: 'Definitions',
    content: 'A protective device where it is intended by the manufacturer that a source of supply is connected to either or both sets of connection terminals.',
    keywords: ['bidirectional', 'protective device', 'definition', 'solar', 'battery', 'storage'],
    relatedRegs: ['530.3.201', 'Unidirectional protective device'],
    apprenticeNote: 'New in Amendment 3:2024. Essential for solar PV and battery storage installations where power flows both ways.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'equipment'
  },
  {
    number: 'Unidirectional protective device',
    title: 'Definition - Unidirectional protective device',
    part: 2,
    section: 'Definitions',
    content: 'A protective device where it is intended by the manufacturer that a source of supply is only connected to one defined set of connection terminals.',
    keywords: ['unidirectional', 'protective device', 'definition', 'line', 'load', 'terminals'],
    relatedRegs: ['530.3.201', 'Bidirectional protective device'],
    apprenticeNote: 'New in Amendment 3:2024. Most traditional MCBs/RCBOs are unidirectional - check markings (line/load, in/out, arrows).',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'equipment'
  },

  // Part 4 - Protection for Safety
  {
    number: '411.3.3',
    title: 'Additional protection by RCD',
    part: 4,
    section: 'Protection for Safety',
    content: 'For socket-outlets with a rated current not exceeding 20 A and for mobile equipment outdoors, additional protection by RCD (≤30mA) shall be provided.',
    keywords: ['RCD', 'socket outlets', 'additional protection', 'outdoor', '30mA', '20A'],
    relatedRegs: ['415.1.1', '531.2.4', '701.411.3.3'],
    apprenticeNote: 'Most sockets need 30mA RCD protection. Essential safety requirement!',
    testMethod: 'Check all sockets ≤20A are RCD protected. Test RCD operation with RCD tester.',
    safetyTip: 'No RCD on sockets = electrocution risk from damaged appliances!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'protection'
  },
  {
    number: '411.4.5',
    title: 'Maximum earth fault loop impedance',
    part: 4,
    section: 'Protection for Safety',
    content: 'The earth fault loop impedance at every point of utilisation shall not exceed the values given in the relevant tables, taking account of conductor temperature.',
    keywords: ['earth fault', 'loop impedance', 'Zs', 'maximum values', 'tables', 'conductor temperature'],
    relatedRegs: ['Table 41.3', '612.8'],
    apprenticeNote: 'Zs measured at ambient temperature must be ≤80% of table values (×0.8 factor) because conductors heat up under fault conditions.',
    testMethod: 'Measure Zs at outlets. For compliance: measured Zs ≤ (Table value × 0.8).',
    safetyTip: 'High Zs = MCB won\'t trip fast enough during earth fault = lethal touch voltages!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '415.1.1',
    title: 'RCD characteristics for additional protection',
    part: 4,
    section: 'Protection for Safety',
    content: 'RCDs for additional protection shall have rated residual operating current ≤30mA and operating time ≤40ms at 5×IΔn.',
    keywords: ['RCD', 'characteristics', '30mA', '40ms', 'operating time'],
    relatedRegs: ['411.3.3', '612.10'],
    apprenticeNote: '30mA max current, 40ms max trip time at 5×IΔn (150mA). Also test at 1×IΔn (30mA) ≤300ms.',
    testMethod: 'Test with RCD tester: ½×IΔn should NOT trip, 1×IΔn must trip ≤300ms, 5×IΔn must trip ≤40ms.',
    safetyTip: 'Slow RCD = may not prevent electrocution! Check trip times regularly.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 41.2',
    title: 'Maximum disconnection times',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'TN systems: 230V final circuits = 0.4s, distribution = 5s. 400V = 0.2s. TT systems: all voltages = 0.2s (achieved by RCD).',
    keywords: ['disconnection times', 'TN system', 'TT system', 'fault clearance', '0.4s', '0.2s'],
    relatedRegs: ['411.3.2', '411.5.1', 'Table 41.3'],
    apprenticeNote: 'TN systems use MCBs/fuses (need low Zs). TT systems use RCDs (high earth electrode resistance makes MCBs too slow).',
    testMethod: 'Calculate disconnection time based on Zs and protective device characteristics.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 41.3',
    title: 'Maximum earth fault loop impedance (Zs)',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Type B MCB Zs limits (0.4s): 6A=7.28Ω, 10A=4.37Ω, 16A=2.73Ω, 20A=2.19Ω, 25A=1.75Ω, 32A=1.37Ω, 40A=1.09Ω, 50A=0.87Ω. Type C: 6A=3.64Ω, 10A=2.19Ω, 16A=1.37Ω, 20A=1.09Ω, 25A=0.87Ω, 32A=0.68Ω, 40A=0.55Ω, 50A=0.44Ω',
    keywords: ['Zs', 'maximum', 'earth fault', 'loop impedance', 'MCB', 'table'],
    relatedRegs: ['612.8', '411.4.5'],
    apprenticeNote: 'Most important table! These are the maximum permitted values from BS 7671. The table already accounts for Cmin (0.95). Compare measured Zs directly with these values.',
    testMethod: 'Measure Zs and compare directly with Table 41.3 values. Measured Zs must not exceed the tabulated maximum.',
    safetyTip: 'Zs too high = MCB won\'t disconnect fault current in time = danger!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },

  // Part 5 - Selection and Erection
  {
    number: '522.6.204',
    title: 'Cables concealed in walls - RCD protection',
    part: 5,
    section: 'Selection and Erection',
    content: 'A cable concealed in a wall at depth <50mm shall be protected against mechanical damage or protected by 30mA RCD.',
    keywords: ['cables', 'concealed', 'walls', '50mm', 'mechanical protection', 'RCD'],
    relatedRegs: ['522.6.201', '411.3.3'],
    apprenticeNote: 'Cables in walls need protection: >50mm deep, or metal protection, or 30mA RCD.',
    testMethod: 'Check cable routes, depths, and RCD protection during inspection.',
    safetyTip: 'Unprotected cables in walls = nail/screw hazard! Could cause electrocution.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: '543.1.1',
    title: 'Cross-sectional area of protective conductors',
    part: 5,
    section: 'Selection and Erection',
    content: 'The cross-sectional area of protective conductors shall be determined by Regulation 543.1.3 or Table 54.7.',
    keywords: ['protective conductors', 'cross-sectional area', 'sizing', 'earth', 'cpc'],
    relatedRegs: ['543.1.3', 'Table 54.7', '612.2.1'],
    apprenticeNote: 'Earth wire size depends on line conductor size. Use Table 54.7 for quick reference.',
    testMethod: 'Check earth conductor sizes match Table 54.7 requirements during inspection.',
    safetyTip: 'Undersized earth = won\'t carry fault current safely = fire/shock risk!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },

  // Part 6 - Inspection and Testing
  {
    number: '612.1',
    title: 'General requirements for testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Every installation shall be inspected and tested during erection and on completion before being put into service.',
    keywords: ['inspection', 'testing', 'installation', 'completion', 'verification'],
    relatedRegs: ['610.1', '612.2.1'],
    apprenticeNote: 'This is the foundation regulation - every installation MUST be tested before energising!',
    testMethod: 'Visual inspection followed by testing in sequence per Regulation 612.1',
    safetyTip: 'Never energise an installation without proper testing - lives depend on it!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'testing'
  },
  {
    number: '612.2.1',
    title: 'Continuity of protective conductors',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The continuity of every protective conductor, including main and supplementary equipotential bonding conductors, shall be verified.',
    keywords: ['continuity', 'protective conductors', 'testing', 'bonding', 'earth'],
    relatedRegs: ['612.1', '543.1.1', '612.2.2'],
    apprenticeNote: 'First test to perform! Use low resistance ohmmeter with test current ≥200mA.',
    testMethod: 'Test between earth terminal at DB and all earth points. Reading should be very low (typically <0.5Ω for domestic).',
    safetyTip: 'Broken earth = death trap! Always test earth continuity first.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.3.1',
    title: 'Insulation resistance testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The insulation resistance between live conductors and between live conductors and earth shall be measured.',
    keywords: ['insulation resistance', 'testing', 'live conductors', 'earth', 'megger'],
    relatedRegs: ['612.3.2', 'Table 61'],
    apprenticeNote: 'Use correct test voltage: 250V for SELV, 500V for up to 500V circuits, 1000V for higher voltages.',
    testMethod: 'Test L-N, L-E, N-E. Minimum 1MΩ for most circuits (0.25MΩ for SELV/electronic equipment)',
    safetyTip: 'Remove/isolate electronic equipment before testing - high voltage will damage sensitive components!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.6',
    title: 'Polarity testing',
    part: 6,
    section: 'Inspection and Testing',
    content: 'It shall be verified that single-pole control and protective devices are connected in the line conductor only.',
    keywords: ['polarity', 'testing', 'single-pole', 'control devices', 'line conductor'],
    relatedRegs: ['612.1', '132.14'],
    apprenticeNote: 'Check all switches, fuses, and MCBs are in the line (not neutral). Critical safety test!',
    testMethod: 'Use continuity tester or bell set. Test with supply isolated. Check at each outlet.',
    safetyTip: 'Wrong polarity = live neutral = death! Always verify polarity correctly.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.8',
    title: 'Earth fault loop impedance (Zs)',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The earth fault loop impedance shall be measured at the origin and at all outlets.',
    keywords: ['earth fault', 'loop impedance', 'Zs', 'outlets', 'measurement'],
    relatedRegs: ['411.4.5', 'Table 41.3', '612.9'],
    apprenticeNote: 'Critical test! Measured Zs must be ≤80% of Table 41.3 values to account for temperature rise under fault.',
    testMethod: 'Test at consumer unit and furthest outlets. Ensure measured values ≤ (Table 41.3 × 0.8).',
    safetyTip: 'High Zs = MCB won\'t trip in fault = fire/death risk!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.10',
    title: 'Functional testing of RCDs',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The effectiveness of any RCD shall be verified by a test simulating an appropriate fault condition.',
    keywords: ['functional testing', 'RCD', 'test', 'fault condition', 'trip'],
    relatedRegs: ['415.1.1', '531.2.4'],
    apprenticeNote: 'Test RCDs at ½×IΔn (should NOT trip), 1×IΔn, and 5×IΔn. Check trip times and ramp test.',
    testMethod: 'Use RCD tester: ½×IΔn = no trip, 1×IΔn ≤300ms, 5×IΔn ≤40ms. Ramp test to check trip threshold.',
    safetyTip: 'RCD not working = no shock protection! Test regularly - quarterly for sockets!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },

  // Part 7 - Special Locations
  {
    number: '701.32',
    title: 'Classification of external influences - Bathrooms',
    part: 7,
    section: 'Special Locations - Bathrooms',
    content: 'Zone 0: IPX7, Zone 1: IPX4, Zone 2: IPX4, Outside zones: suitable for conditions.',
    keywords: ['bathroom', 'zones', 'IP rating', 'water protection', 'IPX4', 'IPX7'],
    relatedRegs: ['701.411.3.3', 'Appendix 5'],
    apprenticeNote: 'Learn bathroom zones! Zone 0 (inside bath) = IPX7, Zones 1&2 = IPX4 minimum.',
    testMethod: 'Check IP ratings of equipment match zone requirements during inspection.',
    safetyTip: 'Wrong IP rating in bathroom = electrocution from water ingress!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },
  {
    number: '701.411.3.3',
    title: 'Additional protection in bathrooms',
    part: 7,
    section: 'Special Locations - Bathrooms',
    content: 'Additional protection by RCD with IΔn ≤30mA shall be provided for all circuits in the location.',
    keywords: ['bathroom', 'RCD', '30mA', 'additional protection', 'all circuits'],
    relatedRegs: ['701.32', '415.1.1'],
    apprenticeNote: 'ALL circuits in bathrooms need 30mA RCD protection - no exceptions!',
    testMethod: 'Check every circuit serving bathroom has 30mA RCD protection.',
    safetyTip: 'Water + electricity = death! RCDs are essential in wet locations.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'special-locations'
  },

  // Additional critical regulations for better coverage
  {
    number: '433.1.1',
    title: 'Overcurrent protection of conductors',
    part: 4,
    section: 'Protection for Safety',
    content: 'Every conductor shall be protected against overcurrent by one or more automatic disconnection devices.',
    keywords: ['overcurrent', 'protection', 'conductors', 'automatic disconnection', 'MCB', 'fuse'],
    relatedRegs: ['433.1.204', '434.1'],
    apprenticeNote: 'Every cable needs overcurrent protection (MCB/fuse) rated correctly for cable size.',
    testMethod: 'Check MCB/fuse rating matches cable current carrying capacity.',
    safetyTip: 'Wrong protection rating = fire risk! Undersized = nuisance tripping, oversized = cable fire!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '433.1.204',
    title: 'Ring circuit overcurrent protection',
    part: 4,
    section: 'Protection for Safety',
    content: 'Ring final circuits shall be protected by a single overcurrent protective device, the rating of which shall not exceed 32A.',
    keywords: ['ring circuit', 'overcurrent protection', '32A', 'single device'],
    relatedRegs: ['433.1.1', 'Appendix 15'],
    apprenticeNote: 'Ring circuits maximum 32A protection. Both legs share the load.',
    testMethod: 'Check ring circuit protection is 32A max and ring integrity is maintained.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '526.3',
    title: 'Accessibility of connections',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every connection and joint shall be accessible for inspection, testing and maintenance, except for specific permitted cases.',
    keywords: ['connections', 'joints', 'accessible', 'inspection', 'testing', 'maintenance'],
    relatedRegs: ['526.1', '526.8'],
    apprenticeNote: 'All connections must be accessible - no joints buried in walls! Use proper enclosures.',
    testMethod: 'Visual inspection - check all connections can be accessed for testing.',
    safetyTip: 'Hidden connections = fire/failure risk! Always use maintenance-free connections if inaccessible.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '530.3.201',
    title: 'Selection of uni/bidirectional protective devices',
    part: 5,
    section: 'Selection and Erection',
    content: 'Selection and erection of equipment for protection shall take account of appropriate use of either a unidirectional protective device or a bidirectional protective device.',
    keywords: ['selection', 'protective device', 'unidirectional', 'bidirectional', 'solar', 'battery', 'pv'],
    relatedRegs: ['Bidirectional protective device', 'Unidirectional protective device'],
    apprenticeNote: 'New Amendment 3:2024. CRITICAL for solar PV/battery installations! Wrong device orientation = device won\'t protect during faults.',
    testMethod: 'Check device markings (in/out, line/load, arrows). Verify correct orientation for power flow direction.',
    safetyTip: 'Unidirectional device installed backwards = NO PROTECTION during reverse fault! Always check manufacturer markings.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'protection'
  },
  {
    number: '537.2.1.1',
    title: 'Isolation requirements',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every circuit shall be provided with means of isolation such that it may be cut off from every source of electrical energy.',
    keywords: ['isolation', 'circuit', 'isolator', 'electrical energy', 'safety'],
    relatedRegs: ['537.1.4', '462.1'],
    apprenticeNote: 'Every circuit needs an isolator for safe maintenance. Main switch isolates whole installation.',
    testMethod: 'Check isolators actually isolate all poles and operate correctly.',
    safetyTip: 'No isolation = maintenance danger! Lock off isolators during work.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '612.2.2',
    title: 'Continuity of ring final circuit conductors',
    part: 6,
    section: 'Inspection and Testing',
    content: 'For ring final circuits, the continuity of both the line and neutral conductors and the protective conductor shall be verified.',
    keywords: ['ring circuit', 'continuity', 'line', 'neutral', 'protective conductor'],
    relatedRegs: ['612.2.1', 'Appendix 15'],
    apprenticeNote: 'Ring circuits need special testing! Test line, neutral AND earth rings separately.',
    testMethod: 'End-to-end test, then cross-connect test. All readings should be similar and low.',
    safetyTip: 'Broken ring = overload risk! Use the Figure-of-8 method for accurate testing.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.9',
    title: 'Prospective fault current',
    part: 6,
    section: 'Inspection and Testing',
    content: 'The prospective short-circuit current and earth fault current shall be measured or determined by calculation.',
    keywords: ['prospective fault current', 'short-circuit', 'earth fault', 'calculation'],
    relatedRegs: ['612.8', '434.1', '435.1'],
    apprenticeNote: 'Ensures protective devices can handle fault currents. High current = need higher rated devices.',
    testMethod: 'Use prospective fault current tester at origin of installation.',
    safetyTip: 'Too high current = MCB may not break safely. Check device ratings!',
    difficulty: 'advanced',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 54.7',
    title: 'Minimum cross-sectional area of protective conductors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'CPC sizes: Line ≤16mm² CPC = Line, 16mm² < Line ≤35mm² CPC = 16mm², Line >35mm² CPC = Line/2',
    keywords: ['protective conductors', 'CPC', 'minimum', 'cross-sectional area', 'earth'],
    relatedRegs: ['543.1.1', '543.1.3'],
    apprenticeNote: 'Earth wire sizing: same as line up to 16mm², then use table or calculation.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: '643.7',
    title: 'Periodic testing of RCDs',
    part: 6,
    section: 'Inspection and Testing',
    content: 'RCDs shall be tested at appropriate intervals to ensure they remain functional.',
    keywords: ['periodic testing', 'RCD', 'intervals', 'functional', 'maintenance'],
    relatedRegs: ['612.10', '415.1.1'],
    apprenticeNote: 'RCDs need regular testing: quarterly for socket RCDs using test button.',
    testMethod: 'Use test button monthly, proper RCD tester annually or after any electrical work.',
    safetyTip: 'RCDs can fail over time - regular testing saves lives!',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'testing'
  },
  
  // Additional Part 1 regulations
  {
    number: '132.1',
    title: 'Protection against thermal effects',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Electrical installations shall be designed and erected to avoid the risk of fire or harmful thermal effects.',
    keywords: ['thermal effects', 'fire', 'protection', 'design'],
    relatedRegs: ['421.1', '422.1'],
    apprenticeNote: 'Prevent overheating of cables and equipment - proper sizing and protection.',
    safetyTip: 'Undersized cables = heat = fire risk!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '132.3',
    title: 'Protection against overcurrent',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Live conductors shall be protected against overcurrent caused by overload and fault current.',
    keywords: ['overcurrent', 'overload', 'fault current', 'protection'],
    relatedRegs: ['433.1', '434.1'],
    apprenticeNote: 'MCBs and fuses protect cables from too much current.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '132.4',
    title: 'Protection against undervoltage',
    part: 1,
    section: 'Fundamental Principles', 
    content: 'Protection against undervoltage shall be provided where automatic reconnection could cause danger.',
    keywords: ['undervoltage', 'automatic reconnection', 'danger'],
    relatedRegs: ['445.1'],
    apprenticeNote: 'Some equipment needs protection if voltage drops too low.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'protection'
  },
  {
    number: '132.5',
    title: 'Protection against overvoltage',
    part: 1,
    section: 'Fundamental Principles',
    content: 'Electrical installations shall be designed to protect against overvoltage caused by atmospheric origin or switching.',
    keywords: ['overvoltage', 'atmospheric', 'switching', 'surge protection'],
    relatedRegs: ['443.1', '534.1'],
    apprenticeNote: 'Lightning and switching can cause voltage spikes - surge protection devices help.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'protection'
  },
  
  // Additional Part 4 regulations
  {
    number: '411.1',
    title: 'General requirements for protection against electric shock',
    part: 4,
    section: 'Protection for Safety',
    content: 'Protection against electric shock shall be provided by basic protection and fault protection.',
    keywords: ['electric shock', 'basic protection', 'fault protection'],
    relatedRegs: ['411.3.1', '411.4.1'],
    apprenticeNote: 'Two types of protection: stop touching live parts + protection if you do.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: '411.3.1.2',
    title: 'TN system requirements',
    part: 4,
    section: 'Protection for Safety',
    content: 'In TN systems, exposed conductive parts shall be connected to the main earthing terminal.',
    keywords: ['TN system', 'exposed conductive parts', 'main earthing terminal'],
    relatedRegs: ['411.4.5', '543.1'],
    apprenticeNote: 'TN system = neutral and earth connected at source. All metal parts earthed.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: '411.5.1',
    title: 'TT system requirements',
    part: 4,
    section: 'Protection for Safety',
    content: 'In TT systems, exposed conductive parts shall be connected to earth electrodes.',
    keywords: ['TT system', 'earth electrodes', 'exposed conductive parts'],
    relatedRegs: ['542.1', '411.5.3'],
    apprenticeNote: 'TT system = separate earth electrode, usually needs RCD protection.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'earthing'
  },
  {
    number: '411.6.2',
    title: 'IT system monitoring',
    part: 4,
    section: 'Protection for Safety',
    content: 'IT systems shall be provided with an insulation monitoring device.',
    keywords: ['IT system', 'insulation monitoring', 'device'],
    relatedRegs: ['411.6.3', '538.1'],
    apprenticeNote: 'IT system = no earth connection to supply. Monitor insulation constantly.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'protection'
  },
  {
    number: '412.1.1',
    title: 'Protection by SELV or PELV',
    part: 4,
    section: 'Protection for Safety',
    content: 'SELV and PELV circuits shall be supplied at nominal voltages not exceeding 50V AC or 120V DC.',
    keywords: ['SELV', 'PELV', 'extra-low voltage', '50V', '120V'],
    relatedRegs: ['414.1', '414.3'],
    apprenticeNote: 'SELV = Safety Extra Low Voltage. Under 50V AC is safer.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'protection'
  },
  {
    number: '421.1.201',
    title: 'Protection against fire - general',
    part: 4,
    section: 'Protection against thermal effects',
    content: 'Electrical equipment shall not present a fire hazard to surrounding materials.',
    keywords: ['fire hazard', 'surrounding materials', 'thermal protection'],
    relatedRegs: ['422.1', '522.6'],
    apprenticeNote: 'Keep hot electrical equipment away from flammable materials.',
    safetyTip: 'Check cable ratings and ventilation around equipment.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  
  // Additional Part 5 regulations
  {
    number: '514.12.1',
    title: 'Identification of conductors',
    part: 5,
    section: 'Selection and Erection',
    content: 'Every conductor shall be identifiable at terminations, joints and other points.',
    keywords: ['identification', 'conductors', 'terminations', 'colour coding'],
    relatedRegs: ['514.3', '514.4'],
    apprenticeNote: 'Use correct colours: Brown=L, Blue=N, Green/Yellow=Earth.',
    testMethod: 'Verify conductor identification during continuity testing.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '526.5',
    title: 'Accessibility for maintenance',
    part: 5,
    section: 'Selection and Erection',
    content: 'Connections shall be accessible for inspection, testing and maintenance.',
    keywords: ['accessibility', 'maintenance', 'inspection', 'connections'],
    relatedRegs: ['526.3', '513.1'],
    apprenticeNote: 'Don\'t hide connections where you can\'t get to them later.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '528.1',
    title: 'Proximity of wiring systems to other services',
    part: 5,
    section: 'Selection and Erection',
    content: 'Electrical installations shall be arranged to avoid harmful effects between electrical and non-electrical services.',
    keywords: ['proximity', 'wiring systems', 'other services', 'separation'],
    relatedRegs: ['528.2', '528.3'],
    apprenticeNote: 'Keep electrical cables away from gas pipes and water pipes.',
    safetyTip: 'Minimum separation distances prevent interference and safety issues.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'installation'
  },
  {
    number: '530.3.1',
    title: 'Selection of equipment - operating temperature',
    part: 5,
    section: 'Selection and Erection',
    content: 'Equipment shall be suitable for the highest and lowest local ambient temperatures.',
    keywords: ['equipment selection', 'operating temperature', 'ambient temperature'],
    relatedRegs: ['512.2', '422.2'],
    apprenticeNote: 'Check equipment can handle local temperature ranges.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'equipment'
  },
  {
    number: '533.1.1',
    title: 'Devices for protection against overvoltage',
    part: 5,
    section: 'Selection and Erection',
    content: 'Surge protective devices shall be selected according to the overvoltage category.',
    keywords: ['surge protection', 'overvoltage', 'SPD', 'category'],
    relatedRegs: ['443.4', '534.1'],
    apprenticeNote: 'SPDs protect against lightning and switching surges.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'protection'
  },
  
  // Additional Part 6 regulations
  {
    number: '612.3.2',
    title: 'Insulation resistance test voltages',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Test voltages: SELV/PELV circuits 250V DC, other circuits 500V DC or 1000V DC.',
    keywords: ['insulation resistance', 'test voltages', '250V', '500V', '1000V'],
    relatedRegs: ['612.3.1', '612.3.3'],
    apprenticeNote: 'Use correct test voltage: 250V for SELV, 500V for most installations.',
    testMethod: 'Set insulation tester to correct voltage before testing.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'testing'
  },
  {
    number: '612.4.1',
    title: 'Protection by SELV, PELV or electrical separation',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Verification shall confirm the correct installation of SELV, PELV and electrical separation.',
    keywords: ['SELV', 'PELV', 'electrical separation', 'verification'],
    relatedRegs: ['414.1', '413.1'],
    apprenticeNote: 'Check low voltage circuits are properly separated from mains.',
    testMethod: 'Test insulation between SELV/PELV and other circuits.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.5',
    title: 'Insulation of non-conducting floors and walls',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Where protection is provided by non-conducting location, floors and walls shall be tested.',
    keywords: ['non-conducting', 'floors', 'walls', 'insulation testing'],
    relatedRegs: ['418.1', '418.2'],
    apprenticeNote: 'Special locations with insulated floors/walls need testing.',
    testMethod: 'Test with approved instruments at multiple points.',
    difficulty: 'advanced',
    frequency: 'occasional',
    category: 'testing'
  },
  {
    number: '612.7',
    title: 'Phase sequence',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Phase sequence shall be verified where the sequence is important for the correct operation of equipment.',
    keywords: ['phase sequence', 'three phase', 'rotation', 'motors'],
    relatedRegs: ['612.12', '551.1'],
    apprenticeNote: 'Three-phase motors need correct phase sequence to rotate properly.',
    testMethod: 'Use phase rotation meter on three-phase supplies.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: '612.11',
    title: 'Verification of voltage drop',
    part: 6,
    section: 'Inspection and Testing',
    content: 'Voltage drop shall be verified by measurement or calculation.',
    keywords: ['voltage drop', 'measurement', 'calculation', 'verification'],
    relatedRegs: ['525.1', 'Appendix 4'],
    apprenticeNote: 'Check voltage doesn\'t drop too much along cable runs.',
    testMethod: 'Measure voltage at origin and end of circuits under load.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  
  // Additional Part 7 regulations
  {
    number: '702.410.3.5',
    title: 'Swimming pools - protective measures',
    part: 7,
    section: 'Special Locations',
    content: 'RCD protection with IΔn ≤ 30mA shall be provided for all circuits in zones 0, 1 and 2.',
    keywords: ['swimming pools', 'RCD protection', '30mA', 'zones'],
    relatedRegs: ['702.32', '702.55'],
    apprenticeNote: 'Swimming pools need RCD protection due to water and electricity risk.',
    safetyTip: 'Water + electricity = danger. Extra protection required.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '703.411.3.3',
    title: 'Hot air saunas - RCD protection',
    part: 7,
    section: 'Special Locations',
    content: 'RCD protection not exceeding 30mA shall be provided for all circuits.',
    keywords: ['saunas', 'RCD protection', '30mA', 'hot air'],
    relatedRegs: ['703.32', '703.512'],
    apprenticeNote: 'Saunas are hot and humid - need extra electrical protection.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '704.410.3.10',
    title: 'Construction sites - supply systems',
    part: 7,
    section: 'Special Locations',
    content: 'TN-S or TT earthing systems shall be used for construction site installations.',
    keywords: ['construction sites', 'TN-S', 'TT', 'earthing systems'],
    relatedRegs: ['704.411', '704.512'],
    apprenticeNote: 'Building sites need robust earthing due to harsh conditions.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'special-locations'
  },
  {
    number: '705.422.7',
    title: 'Agricultural premises - heating appliances',
    part: 7,
    section: 'Special Locations',
    content: 'Radiant heating appliances shall be positioned to avoid livestock contact.',
    keywords: ['agricultural', 'heating appliances', 'livestock', 'positioning'],
    relatedRegs: ['705.513', '705.537'],
    apprenticeNote: 'Farms have animals - keep electrical equipment safe from them.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  {
    number: '706.410.3.10',
    title: 'Conducting locations - RCD protection',
    part: 7,
    section: 'Special Locations',
    content: 'RCD protection with IΔn ≤ 30mA shall be provided for socket outlets.',
    keywords: ['conducting locations', 'RCD protection', '30mA', 'socket outlets'],
    relatedRegs: ['706.411', '706.512'],
    apprenticeNote: 'Metal environments increase shock risk - need RCD protection.',
    difficulty: 'intermediate',
    frequency: 'occasional',
    category: 'special-locations'
  },
  
  // Common installation regulations
  {
    number: '559.10.3',
    title: 'Luminaire installations',
    part: 5,
    section: 'Selection and Erection',
    content: 'Luminaires shall be installed to facilitate lamp replacement and maintenance.',
    keywords: ['luminaires', 'lamp replacement', 'maintenance', 'access'],
    relatedRegs: ['559.4', '559.5'],
    apprenticeNote: 'Make sure you can easily change bulbs and maintain lights.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'installation'
  },
  {
    number: '553.1.1',
    title: 'Socket outlet installations',
    part: 5,
    section: 'Selection and Erection',
    content: 'Socket outlets shall be suitable for the intended use and environment.',
    keywords: ['socket outlets', 'intended use', 'environment', 'suitability'],
    relatedRegs: ['553.1.2', '553.1.3'],
    apprenticeNote: 'Choose right socket type: indoor/outdoor, current rating, etc.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'equipment'
  },
  
  // Critical BS7671 Tables
  {
    number: 'Table 41.1',
    title: 'Maximum disconnection times',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Final circuits: 0.4s (230V), 0.2s (400V). Distribution circuits: 5s (230V), 1s (400V).',
    keywords: ['disconnection times', 'maximum', 'final circuits', 'distribution', '0.4s', '5s'],
    relatedRegs: ['411.3.2.2', '612.8'],
    apprenticeNote: 'Learn these times! Socket circuits = 0.4s max, distribution = 5s max.',
    safetyTip: 'Longer disconnection = higher shock risk!',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'protection'
  },
  {
    number: 'Table 41.2',
    title: 'Maximum earth fault loop impedance (Zs) - RCDs',
    part: 4,
    section: 'Protection for Safety - Tables', 
    content: 'For circuits protected by 30mA RCD: maximum Zs = 1667Ω (230V), 200Ω (400V).',
    keywords: ['Zs', 'RCD', '30mA', 'maximum', 'earth fault', 'loop impedance'],
    relatedRegs: ['411.5.3', '415.1.1'],
    apprenticeNote: 'RCD circuits have very high Zs limits because RCD provides the protection.',
    testMethod: 'Test RCD operation first, then measure Zs if required.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 41.3',
    title: 'Maximum earth fault loop impedance (Zs) - MCBs',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Type B MCB Zs limits (0.4s, Cmin=0.95): 6A=7.28Ω, 10A=4.37Ω, 16A=2.73Ω, 20A=2.19Ω, 25A=1.75Ω, 32A=1.37Ω, 40A=1.09Ω, 50A=0.87Ω, 63A=0.69Ω, 80A=0.55Ω, 100A=0.44Ω, 125A=0.35Ω',
    keywords: ['Zs', 'MCB', 'Type B', 'maximum', 'earth fault', 'loop impedance', 'table'],
    relatedRegs: ['612.8', '411.4.5'],
    apprenticeNote: 'Most important table. Values already include Cmin = 0.95, so compare measured Zs directly with these limits (after temperature correction if required).',
    testMethod: 'Measure Zs at the furthest point and compare with the Table 41.3 value for the protective device (no 0.8 factor).',
    safetyTip: 'Zs too high = MCB will not disconnect fault current in time = danger!',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 41.4',
    title: 'Maximum earth fault loop impedance (Zs) - Fuses (5s)',
    part: 4,
    section: 'Protection for Safety - Tables',
    content: 'Example BS 88-2 gG Zs limits at 5s (Cmin=0.95): 6A=12.0Ω, 10A=6.8Ω, 16A=4.0Ω, 20A=2.8Ω, 32A=1.7Ω, 40A=1.3Ω, 50A=0.99Ω, 63A=0.78Ω (see BS 7671 Table 41.4 for the full list).',
    keywords: ['Zs', 'fuse', 'BS 88', 'maximum', 'earth fault', 'loop impedance'],
    relatedRegs: ['Table 41.4', '533.1'],
    apprenticeNote: 'These 5s values apply mainly to distribution circuits using fuses. Always check you are using the correct table for the protective device and circuit type.',
    testMethod: 'Identify the fuse type and rating, then compare measured Zs with the corresponding Table 41.4 value.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Table 52.1',
    title: 'Minimum cross-sectional area of conductors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'Minimum conductor sizes: Power circuits 2.5mm², Lighting circuits 1.5mm², Control circuits 1.5mm²',
    keywords: ['minimum', 'cross-sectional area', 'conductors', 'power', 'lighting', '2.5mm²', '1.5mm²'],
    relatedRegs: ['521.5.1', '523.1'],
    apprenticeNote: 'Standard UK minimums: 2.5mm² for socket circuits, 1.5mm² for lighting.',
    difficulty: 'beginner',
    frequency: 'common',
    category: 'cables'
  },
  {
    number: 'Table 54.7',
    title: 'Minimum cross-sectional area of protective conductors (CPC)',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'CPC sizing: If line ≤16mm² then CPC = line size. If 16mm² < line ≤35mm² then CPC = 16mm². If line >35mm² then CPC = line/2.',
    keywords: ['protective conductors', 'CPC', 'minimum', 'cross-sectional area', 'earth', 'sizing'],
    relatedRegs: ['543.1.1', '543.1.3'],
    apprenticeNote: 'Earth wire sizing rule: same as line wire up to 16mm², then follow table.',
    testMethod: 'Check CPC size matches table requirements during continuity test.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'earthing'
  },
  {
    number: 'Table 54.8',
    title: 'Minimum cross-sectional area of main protective bonding conductors',
    part: 5,
    section: 'Selection and Erection - Tables',
    content: 'Main bonding conductor minimum size: 6mm² for TN systems, 10mm² for TT systems unless calculation proves smaller acceptable.',
    keywords: ['main bonding', 'protective bonding', 'minimum', 'cross-sectional area', '6mm²', '10mm²'],
    relatedRegs: ['544.1.1', '544.1.2'],
    apprenticeNote: 'Main bonding: 6mm² for TN-S/TN-C-S, 10mm² for TT systems.',
    testMethod: 'Check bonding conductor size and connections during inspection.',
    difficulty: 'intermediate',
    frequency: 'frequent',
    category: 'earthing'
  },
  {
    number: 'Appendix 3',
    title: 'Time/current characteristics and maximum Zs',
    part: 6,
    section: 'Reference Tables',
    content: 'Complete tables showing relationship between fault current, disconnection time, and maximum Zs for all protective devices.',
    keywords: ['time current', 'characteristics', 'maximum Zs', 'protective devices', 'fault current'],
    relatedRegs: ['Table 41.3', 'Table 41.4'],
    apprenticeNote: 'The source for all Zs calculations - shows how fault current relates to trip time.',
    testMethod: 'Use these tables to determine if measured Zs values are acceptable.',
    difficulty: 'advanced',
    frequency: 'frequent',
    category: 'testing'
  },
  {
    number: 'Appendix 4',
    title: 'Current-carrying capacity and voltage drop',
    part: 5,
    section: 'Reference Tables',
    content: 'Tables for cable current ratings, voltage drop calculations, and installation methods.',
    keywords: ['current carrying capacity', 'voltage drop', 'cable ratings', 'installation methods'],
    relatedRegs: ['523.1', '525.1'],
    apprenticeNote: 'Essential for cable sizing - consider current rating AND voltage drop.',
    difficulty: 'intermediate',
    frequency: 'common',
    category: 'cables'
  }
];
