/**
 * Module 3 · Section 5 · Subsection 1 — DC machines: principles, types, applications
 * Maps to C&G 2365-03 / Unit 302 / LO3 / AC 3.1
 *   AC 3.1 — "state the basic types, applications and describe the operating principles of DC machines"
 *
 * Layered depth: 2357 Unit 609 ELTK08 / AC 8.1 — DC machine operating principles
 *
 * Brushes, commutator, field. Series for traction torque; shunt for constant speed; compound
 * for both. Back-EMF self-regulation. Speed control by armature voltage and field weakening.
 * Plus the brushless permanent-magnet DC motor (BLDC/PMSM) — the modern survivor in EVs and tools.
 */
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ChevronLeft, ChevronRight } from 'lucide-react';

import { InlineCheck } from '@/components/apprentice-courses/InlineCheck';
import { PowerCalculator } from '@/components/apprentice-courses/PowerCalculator';
import { Quiz } from '@/components/apprentice-courses/Quiz';
import { PageFrame, PageHero } from '@/components/college/primitives';
import {
  TLDR,
  ConceptBlock,
  RegsCallout,
  CommonMistake,
  Scenario,
  KeyTakeaways,
  FAQ,
  LearningOutcomes,
  ContentEyebrow,
  SectionRule,
  VideoCard,
} from '@/components/study-centre/learning';
import { DCMotorSchematic } from '@/components/study-centre/diagrams';
import { videos } from '@/data/study-centre/video-library';
import useSEO from '@/hooks/useSEO';

const TITLE = 'DC machines — principles, types, applications | Level 3 Module 3.5.1 (AC 3.1) | Elec-Mate';
const DESCRIPTION =
  'How a DC motor works: brushes, commutator, field winding. Series, shunt and compound machines. Back-EMF self-regulation. BLDC/PMSM and the modern survivors.';

const checks = [
  {
    id: 'l3-m3-5-1-bemf',
    question: 'A DC motor running at no-load draws very little current because:',
    options: [
      'It has high resistance',
      'The back-EMF nearly equals the supply voltage so net driving voltage is small',
      'It has a fuse',
      'No load = no current',
    ],
    correctIndex: 1,
    explanation:
      'I_a = (V − E_b) / R_a. At no-load, E_b builds up close to V, leaving only enough voltage to overcome internal losses. Loaded, speed drops, E_b drops, net V−E_b rises, current rises to deliver torque.',
  },
  {
    id: 'l3-m3-5-1-series',
    question: 'A DC series motor under heavy load:',
    options: [
      'Speeds up',
      'Develops huge torque (current and field both high)',
      'Stalls quickly',
      'Trips',
    ],
    correctIndex: 1,
    explanation:
      'In a series motor, field current = armature current. Heavy load → high I → high field → very high torque (T ∝ I²). Used for traction, cranes, starter motors.',
  },
  {
    id: 'l3-m3-5-1-shunt',
    question: 'A DC shunt motor speed when load increases:',
    options: [
      'Drops massively',
      'Drops only slightly (almost constant speed)',
      'Stays exactly constant',
      'Increases',
    ],
    correctIndex: 1,
    explanation:
      'Shunt has constant field (across full V). Speed N = (V − I_a R_a) / (kΦ). Only the I_a R_a drop changes with load — small effect, ~5 % speed reduction at full load. Used where speed matters.',
  },
];

const quizQuestions = [
  {
    id: 1,
    question: 'A DC motor commutator and brushes serve to:',
    options: [
      'Reduce voltage',
      'Switch the armature current direction at every half-revolution to keep the torque unidirectional',
      'Cool the motor',
      'Step up power',
    ],
    correctAnswer: 1,
    explanation:
      'Without commutation the rotor would oscillate. Commutator + brushes reverse the current in each armature coil as it passes through the neutral plane.',
  },
  {
    id: 2,
    question: 'Back-EMF E_b in a DC motor is:',
    options: [
      'The supply voltage',
      'EMF generated by the rotor cutting field flux as it spins',
      'The fuse rating',
      'Power loss',
    ],
    correctAnswer: 1,
    explanation:
      'A motor IS a generator while it spins. The motion in the field induces a back-EMF that opposes the supply voltage. E_b ∝ N (speed).',
  },
  {
    id: 3,
    question: 'DC series motor torque equation:',
    options: ['T ∝ I', 'T ∝ I²', 'T ∝ V', 'T ∝ N'],
    correctAnswer: 1,
    explanation:
      'Field is created by the armature current, so Φ ∝ I (below saturation). T ∝ Φ × I → T ∝ I². Hence the massive starting torque.',
  },
  {
    id: 4,
    question: 'DC shunt motor — main application:',
    options: [
      'Cranes',
      'Lathes, machine tools, conveyors needing constant speed',
      'EV traction',
      'Door bells',
    ],
    correctAnswer: 1,
    explanation:
      'Shunt = constant speed under varying load. Standard for machine tools, fans, pumps where speed must be predictable.',
  },
  {
    id: 5,
    question: 'DC compound motor combines:',
    options: ['DC and AC', 'Both series and shunt fields', 'Two armatures', 'Two commutators'],
    correctAnswer: 1,
    explanation:
      'Compound = two field windings, one in series, one in shunt (parallel). Compromise between starting torque (series) and constant speed (shunt).',
  },
  {
    id: 6,
    question: 'DC motor speed control via:',
    options: [
      'Armature voltage and field current variation',
      'Frequency only',
      'Capacitor switching',
      'Brake',
    ],
    correctAnswer: 0,
    explanation:
      'Reduce armature voltage → speed drops. Reduce field current (field weakening) → speed rises above base. Both used together for wide speed range.',
  },
  {
    id: 7,
    question: 'Brushes wear because:',
    options: [
      'Heating',
      'Mechanical contact + sparking at the commutator surface',
      'Oil contamination',
      'Magnetic forces',
    ],
    correctAnswer: 1,
    explanation:
      'Carbon brushes are sacrificial — sliding contact + tiny sparks at every commutation. Periodic replacement is part of DC motor maintenance.',
  },
  {
    id: 8,
    question: 'A DC motor reverses by:',
    options: [
      'Reversing both armature AND field',
      'Reversing armature OR field (not both — both = no change)',
      'Reversing the supply only',
      'Adding a capacitor',
    ],
    correctAnswer: 1,
    explanation:
      'T = k × Φ × I. Reverse current direction OR field direction — torque reverses. Reverse both → torque stays the same direction.',
  },
];

const faqs = [
  {
    question: 'Where do you actually see DC motors today?',
    answer:
      'Cranes, traction (older trains, EV traction motors that are technically permanent-magnet brushless DC), large rolling mills, mine winders, golf carts, cordless tools (small brushed DC), some industrial drives where simple speed control is needed.',
  },
  {
    question: 'Why is a DC series motor used for cranes and trains?',
    answer:
      'Massive starting torque (T ∝ I²). When standing still it draws huge current and develops huge torque to break the load free. Once moving, current drops, torque drops, speed climbs. Self-regulating to load.',
  },
  {
    question: 'Can I run a DC motor on AC?',
    answer:
      "Universal motors (cooker hood, drill, vacuum cleaner) ARE essentially DC series motors that work on AC because both field AND armature reverse together each half cycle. But standard DC motors don't — the commutator depends on DC.",
  },
  {
    question: 'Why do DC motors need brush maintenance?',
    answer:
      'Carbon brushes are the only sliding contact in the motor. They wear; they can develop ridges; they can spark badly if the commutator surface is rough. Inspect every 6–12 months on continuously running DC motors.',
  },
  {
    question: 'What is "field weakening"?',
    answer:
      'Reducing the shunt field current. Speed rises (because N ∝ V/Φ). Used to push a DC motor above its base speed at the cost of less torque. Common in rolling mills and lift drives.',
  },
  {
    question: 'Are DC motors more efficient than AC?',
    answer:
      'Comparable at full load (~85–90 % for medium machines). DC motors offer simpler speed control without electronics, but need brush maintenance. Modern AC + VFD has largely replaced DC for new installs except in specific traction applications.',
  },
];

export default function Sub1() {
  useSEO(TITLE, DESCRIPTION);
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[hsl(0_0%_8%)] text-white">
      <div className="px-4 sm:px-6 lg:px-8 pt-2 pb-24">
        <PageFrame>
          <button
            onClick={() => navigate('/study-centre/apprentice/level3-module3-section5')}
            className="inline-flex items-center gap-2 h-11 px-3 rounded-full bg-white/[0.06] border border-white/[0.1] text-white text-[13px] font-medium touch-manipulation hover:bg-white/[0.1] mb-1 self-start"
          >
            <ArrowLeft className="h-4 w-4" /> Section 5
          </button>

          <PageHero
            eyebrow="Module 3 · Section 5 · Subsection 1"
            title="DC machines — principles, types, applications"
            description="Brushes, commutator and field. Series for traction torque; shunt for constant speed; compound for both. Back-EMF as the self-regulating physics behind every DC motor."
            tone="yellow"
          />

          <TLDR
            points={[
              'DC motor: armature in a magnetic field, current creates force, commutator switches direction every half rev to keep torque unidirectional.',
              'Back-EMF E_b = supply minus internal drop. As speed rises, E_b rises and current falls (self-regulation).',
              'Series motor: T ∝ I² — huge starting torque, used for cranes, traction, starter motors.',
              'Shunt motor: constant field, near-constant speed under varying load — used for machine tools.',
              'Compound: combines series and shunt characteristics. BLDC/PMSM is the modern survivor in EV traction, drones, cordless tools.',
            ]}
          />

          <LearningOutcomes
            outcomes={[
              'Explain DC motor operation with reference to armature, field, commutator and brushes.',
              'Define back-EMF and explain its self-regulating role.',
              'Distinguish DC series, shunt and compound machines by torque-speed characteristic.',
              'Identify typical applications for each DC machine type, on site and in industry.',
              'Describe basic DC motor speed control by armature voltage and field weakening.',
              'Recognise the BLDC/PMSM as a permanent-magnet brushless DC machine.',
            ]}
            initialVisibleCount={3}
          />

          <ContentEyebrow>How a DC motor works</ContentEyebrow>

          <ConceptBlock
            title="Motor effect: current in a field produces force"
            plainEnglish="Pass current through a coil sitting in a magnetic field — Fleming's left-hand rule says force acts perpendicular to both. The coil tries to rotate. The commutator + brushes switch the current direction every half rev so the torque stays one direction."
            onSite="The same physics underpins every DC motor on site, from a 250 W golf-cart traction motor to a 500 kW mill drive. Knowing the equations means you can reason about behaviour rather than just remember nameplates."
          >
            <p>The three equations every DC machine question rests on:</p>
            <ul className="space-y-1.5 list-disc pl-5 marker:text-elec-yellow/70">
              <li>
                <strong>E_b = k × Φ × N</strong> — back-EMF (proportional to flux and speed).
              </li>
              <li>
                <strong>I_a = (V − E_b) / R_a</strong> — armature current.
              </li>
              <li>
                <strong>T = k × Φ × I_a</strong> — torque (proportional to flux and armature current).
              </li>
            </ul>
            <p>
              k is a machine constant that wraps up the number of conductors, pole count and
              winding geometry. Φ is the field flux per pole. R_a is the armature resistance,
              typically 0.1–1 Ω for medium machines. Once you have these three, every behaviour
              follows.
            </p>
          </ConceptBlock>

          <div className="my-4">
            <ContentEyebrow>Try the calculator</ContentEyebrow>
            <PowerCalculator />
          </div>

          <DCMotorSchematic />

          <VideoCard
            url={videos.dcMotor.url}
            title={videos.dcMotor.title}
            channel={videos.dcMotor.channel}
            duration={videos.dcMotor.duration}
            topic="How a DC motor works · Unit 302 LO3 AC 3.1"
            caption={
              <>
                The Engineering Mindset opens a brushed DC motor and walks the armature, brushes
                and commutator step by step — exactly the mechanical inverter described above.
                Watch how the brushes flip armature current direction every half-revolution to keep
                the torque pulling one way.
              </>
            }
          />

          <ConceptBlock
            title="Commutator and brushes — the mechanical inverter that defines a DC machine"
            plainEnglish="The commutator is a split copper ring on the rotor shaft. Stationary carbon brushes ride on it. As the rotor turns, the brushes connect to whichever segment is presently under the right pole, so the current direction in any one armature coil flips every half-revolution. The torque always pulls the same way around."
            onSite="Brush wear is the most common DC motor service item. Inspect carbon brush length at planned maintenance intervals — when the brush is shorter than the manufacturer's wear-limit mark, replace it before the spring-loaded carrier scores the commutator."
          >
            <p>
              Without the commutator the rotor would receive DC current that never reverses — it
              would pull through the neutral plane, overshoot, and then be pushed back. You'd have
              an oscillator, not a motor. The commutator is the original mechanical inverter, doing
              the same job a power-electronic IGBT bridge does inside a brushless DC motor today.
            </p>
            <p>
              <strong>Brush grade matters.</strong> Soft electrographite brushes (low friction, low
              arcing) for clean industrial duty; harder copper-graphite for high-current low-voltage
              starter motors and traction. A brush running too hard scores the commutator; too soft
              and it wears in weeks. Manufacturers specify the grade on the data sheet — match it
              when ordering replacements.
            </p>
            <p>
              <strong>The neutral plane</strong> is the position where the coil sits parallel to
              the field — instantaneously zero EMF. Brushes are set on this line so commutation
              happens at the lowest possible current and arcing is minimised. Heavy loads pull the
              neutral plane round (armature reaction) — premium machines fit interpoles to push it
              back.
            </p>
          </ConceptBlock>

          <ConceptBlock
            title="Back-EMF — the equation that explains every DC motor behaviour"
            plainEnglish="As the armature spins, the conductors cut the field flux and generate their own EMF that opposes the supply. The faster it spins, the bigger the back-EMF, the smaller the net driving voltage, the smaller the current. A DC motor self-regulates by being a generator at the same time."
          >
            <p>
              From the basic loop equation: <strong>V = E_b + I_a × R_a</strong>, so{' '}
              <strong>I_a = (V − E_b) / R_a</strong>.
            </p>
            <p>
              At the instant of starting, the rotor is stationary so E_b = 0. The full supply
              voltage drops across the very small armature resistance R_a. Starting current would
              be enormous — a 240 V motor with R_a = 0.5 Ω would draw 480 A on first energisation.
              That's why DC motors above ~5 kW always use a starting resistor or a controlled-voltage
              starter to limit inrush until E_b builds up.
            </p>
            <p>
              Once running near full speed, E_b might be 220 V on a 240 V supply. Net 20 V drives
              ~40 A through the same 0.5 Ω — a hundred-fold reduction. Add load → speed drops
              slightly → E_b drops → current rises automatically to deliver the new torque demand.
              No control electronics needed; the physics does it.
            </p>
          </ConceptBlock>

          <InlineCheck {...checks[0]} />

          <SectionRule />

          <ContentEyebrow>The three field connections</ContentEyebrow>

          <ConceptBlock
            title="Series, shunt, compound"
            plainEnglish="The field winding can be connected in series with the armature, in parallel (shunt), or both. Each gives a different torque-speed characteristic."
          >
            <ul className="space-y-1.5 list-disc pl-5 marker:text-elec-yellow/70">
              <li>
                <strong>Series:</strong> field winding in series with armature. Field current =
                armature current. T ∝ I². Massive starting torque, speed drops dramatically with
                load. Cranes, traction, starter motors.
              </li>
              <li>
                <strong>Shunt:</strong> field winding in parallel with armature, across full V.
                Constant field. Speed almost independent of load. Lathes, machine tools, fans.
              </li>
              <li>
                <strong>Compound:</strong> both series and shunt fields. Compromise — good
                starting torque and reasonable speed regulation. Mixers, hoists, conveyors with
                variable load.
              </li>
            </ul>
          </ConceptBlock>

          <ConceptBlock
            title="Torque-speed curves — the personality of each machine"
            plainEnglish="Plot torque (vertical) against speed (horizontal). Each DC machine type traces a different shape. Series gives a steep hyperbola (huge torque, low speed). Shunt gives an almost-horizontal line (constant speed). Compound sits between. The curve tells you what load the machine suits."
          >
            <p>
              <strong>Series motor curve:</strong> at zero speed, torque is at maximum because
              both armature current AND field flux are at their starting values (T = k Φ I, and
              Φ ∝ I, so T ∝ I²). As speed builds, current falls, torque falls fast, and speed rises
              rapidly. The curve has no defined no-load point — speed approaches infinity as
              torque approaches zero. That's the runaway risk.
            </p>
            <p>
              <strong>Shunt motor curve:</strong> field is fixed by V/R_f, so T ∝ I_a alone. The
              curve is nearly a vertical drop — speed barely changes from no-load to full load. A
              shunt motor is a "constant-speed" machine in the same sense an induction motor is —
              speed regulation typically 3–8 % from no-load to full load.
            </p>
            <p>
              <strong>Compound motor curve:</strong> the series winding adds extra torque at low
              speed (helping start heavy loads) while the shunt winding stops the runaway problem
              at no-load. Cumulative compound is the standard. Differential compound (series field
              opposing shunt) is rarely used because it can become unstable.
            </p>
          </ConceptBlock>

          <InlineCheck {...checks[1]} />

          <ConceptBlock
            title="Speed control — armature voltage below base, field weakening above"
            plainEnglish="To run a DC motor below its nameplate speed, reduce armature voltage. To run above, weaken the field. The two methods together give a 4:1 or wider speed range — historically the reason DC dominated industrial drives before VFDs arrived."
            onSite="Modern AC vector drives now do the same job electronically — V/f below base, then field-weakening flux control above. Knowing the DC version makes the AC drive's behaviour obvious."
          >
            <p>
              <strong>Armature voltage control (constant torque region):</strong> reducing V from
              full down to ~5 % slows the motor proportionally. Flux stays constant, so maximum
              torque available stays constant. Power output (P = T × ω) falls with speed. A
              Ward-Leonard set (motor-generator) was the classical method; modern installations
              use thyristor or IGBT converters.
            </p>
            <p>
              <strong>Field weakening (constant power region):</strong> with armature at full V,
              reducing the shunt field current cuts Φ. Since back-EMF E_b = k Φ N must equal V
              minus the small I_a R_a drop, reducing Φ forces N to rise. Torque capability falls
              (T ∝ Φ × I_a, and you can't increase I_a beyond the thermal limit), but power stays
              roughly constant.
            </p>
            <p>
              Combining the two gives constant torque from zero up to base speed, then constant
              power from base up to maximum (typically 2–4× base). Steel rolling mills, paper
              machines and lift drives all exploit this.
            </p>
          </ConceptBlock>

          <InlineCheck {...checks[2]} />

          <ConceptBlock
            title="Armature reaction — the field gets pushed sideways under load"
            plainEnglish="The current flowing in the rotating armature creates its own magnetic field. Under load, this cross-field distorts the main pole flux — pushing it sideways and weakening it slightly. The neutral plane shifts, brushes start to spark, and torque output drops below what the simple equation predicts."
          >
            <p>
              At no load, only the field winding produces flux and the field is symmetrical
              between the poles. Add load: armature current produces a magneto-motive force (MMF)
              at right angles to the main field. The two MMFs add vectorially, so the net flux
              pattern shifts by an angle that grows with armature current.
            </p>
            <p>
              Two consequences: (1) the neutral plane moves, so brushes set for no-load now
              commutate at a non-zero EMF — sparking, brush wear and pitted commutator segments;
              (2) saturation in the leading pole tip means total flux is reduced ("flux weakening
              by armature reaction") — torque per amp falls, especially noticeable on large
              machines under heavy load.
            </p>
            <p>
              <strong>Compensation:</strong> on machines above ~5 kW you'll see <em>interpoles</em>
              {' '}(small auxiliary poles between the main poles, wound in series with the armature)
              to inject opposing MMF on the neutral line. Very large traction machines add{' '}
              <em>compensating windings</em> embedded in the main pole faces. Both fixes do the
              same job — restore the neutral plane to its no-load position regardless of load.
            </p>
          </ConceptBlock>

          <ConceptBlock
            title="BLDC and PMSM — the modern permanent-magnet brushless DC motor"
            plainEnglish="Replace the wound field with permanent magnets and you delete the field winding losses. Replace the brushes-and-commutator with an electronic inverter and Hall sensors and you delete the only wearing parts. What's left is the brushless DC motor (BLDC) — high efficiency, long life, accurate control. Almost every battery tool, drone, EV traction motor and HVAC blower built since 2015 is one."
            onSite="When you specify a 'modern' fan, pump or hand tool today, the motor inside is almost certainly a BLDC/PMSM with a built-in driver. Treat it as a sealed unit — diagnose by the controller's fault codes, not by opening the motor."
          >
            <p>
              <strong>Construction:</strong> rotor carries permanent magnets (neodymium for high
              power density, ferrite for cost); stator carries the armature winding (the names
              "rotor" and "stator" swap roles vs a brushed DC motor). A 3-phase electronic
              controller switches the stator currents in sequence based on rotor position fed back
              from Hall-effect sensors or back-EMF detection (sensorless drives).
            </p>
            <p>
              <strong>Advantages over brushed DC:</strong> no brush dust, no commutator arcing, no
              brush replacement, higher efficiency (no I²R loss in field winding, no friction loss
              at brushes), higher power density, and electronic control gives precise speed and
              torque regulation.
            </p>
            <p>
              <strong>Disadvantages:</strong> needs a controller (cost, single point of failure),
              magnets demagnetise above their Curie temperature (~150–250 °C for typical NdFeB),
              and rare-earth magnet supply chain has price volatility.
            </p>
            <p>
              Strictly speaking a BLDC is a permanent-magnet synchronous AC motor with electronic
              commutation — the "DC" name comes from the DC supply at the controller input and
              from the trapezoidal current waveform that gives a brushed-DC-like torque-speed
              curve. The same motor with sinusoidal current is a PMSM (Sub 5.4). Same hardware,
              two control philosophies.
            </p>
          </ConceptBlock>

          <RegsCallout
            source="BS EN 60034-1:2010+A1:2020 — Rotating electrical machines: Rating and performance"
            clause="DC machines shall be rated by output power, voltage, current, speed, duty type (S1–S10) and class of insulation. The manufacturer's name plate shall include all rating quantities, and the machine shall comply with the temperature-rise limits for the declared insulation class."
            meaning={
              <>
                Every plate carries kW (output mechanical), V (armature), I (rated A), rpm, duty
                type (S1 = continuous, S2 = short-time, etc.) and insulation class. Designers and
                installers must select for the correct duty and rated quantities — not just the
                kW figure. Pull the manufacturer's data sheet before specifying any cable, MCB or
                contactor.
              </>
            }
            cite="Source: BS EN 60034-1:2010+A1:2020."
          />

          <RegsCallout
            source="BS 7671:2018+A4:2026 — Regulation 552.1.1 (Rotating machines)"
            clause="All equipment, including cable, of every circuit carrying the starting, accelerating and load currents of a motor shall be suitable for a current at least equal to the full-load current rating of the motor when rated in accordance with the appropriate British or Harmonized Standard. Where the motor is intended for intermittent duty and for frequent starting and stopping, account shall be taken of any cumulative effects of the starting or braking currents upon the temperature rise of the equipment of the circuit."
            meaning={
              <>
                The cable and switchgear feeding any DC or AC motor must handle full-load current
                continuously, plus the cumulative thermal effect of starting inrush. Intermittent
                or frequently-started duty (S3, S4 duty types) needs derating beyond the simple
                FLA-equals-cable approach. Always check duty type on the BS EN 60034 plate before
                sizing the supply.
              </>
            }
            cite="Source: BS 7671:2018+A4:2026 — Regulation 552.1.1."
          />

          <RegsCallout
            source="BS 7671:2018+A4:2026 — Regulation 552.1.2 (Motor overload protection)"
            clause="Every electric motor having a rating exceeding 0.37 kW shall be provided with control equipment incorporating means of protection against overload of the motor. This requirement does not apply to a motor incorporated in an item of current-using equipment complying as a whole with an appropriate British or Harmonized Standard."
            meaning={
              <>
                DC series motors are particularly vulnerable to overload because back-EMF
                self-regulation breaks down at light field. Reg 552.1.2 mandates a dedicated
                overload device above 0.37 kW — typically a thermal-magnetic relay matched to
                the armature FLC, with the magnetic element set to ride DOL inrush. On a
                BLDC/PMSM the controller's electronic overload performs the same regulatory job
                provided it is documented in the manufacturer's instructions.
              </>
            }
            cite="Source: BS 7671:2018+A4:2026, Regulation 552.1.2."
          />

          <SectionRule />

          <CommonMistake
            title="Running a DC series motor without load"
            whatHappens={
              <>
                Series motor disconnected from load and energised. With no load, current is tiny
                → field is tiny → speed shoots upward (N ∝ 1/Φ). Motor runs away, commutator and
                rotor explode from centrifugal force.
              </>
            }
            doInstead={
              <>
                Series motors must always have a load. Never bench-test or commission them
                no-load. Use a brake or load to absorb torque before applying voltage. Lock-out /
                tag-out the supply if you have to leave a series motor unattended during
                commissioning.
              </>
            }
          />

          <CommonMistake
            title="Reversing a DC motor by swapping the supply"
            whatHappens={
              <>
                Apprentice swaps line and neutral on a DC supply expecting the motor to reverse.
                The reversal flips current in the armature AND the field simultaneously, so torque
                direction stays the same. Motor runs the same way as before.
              </>
            }
            doInstead={
              <>
                Reverse EITHER the armature connections OR the field connections — not both. On a
                shunt motor the field terminals are usually labelled F1, F2 and the armature
                terminals A1, A2. Swap A1 and A2 (or F1 and F2). The torque equation T = k × Φ × I
                explains why.
              </>
            }
          />

          <Scenario
            title="Choosing a DC motor for an industrial hoist"
            situation={
              <>
                500 kg hoist, 0.5 m/s lift speed. Variable load (50–500 kg in service). Standby
                periods. Customer wants simple speed control without VFD complexity.
              </>
            }
            whatToDo={
              <>
                Force = mg = 500 × 9.81 = 4905 N at full load. Mech P = F × v = 4905 × 0.5 =
                2.45 kW.
                <br />
                Pick a 4 kW DC compound motor (compromise between series starting torque and shunt
                regulation).
                <br />
                Speed control: simple armature voltage variation via thyristor controller — coarse
                but adequate for hoist duty.
                <br />
                Field weakening for above-base lifting at light load.
                <br />
                Maintenance schedule: brushes inspected every 1000 hours, commutator dressed
                annually.
                <br />
                Motor circuit per BS 7671 §552 — cable rated for FLA, contactor rated for AC-3
                (or DC equivalent), Type C MCB to ride through inrush.
              </>
            }
            whyItMatters={
              <>
                For variable-load lifting where simplicity matters, DC compound is hard to beat.
                Modern AC + VFD does the same job with no brushes, but the DC option is still
                legitimate for retrofit and existing kit. The competence to choose correctly
                between technologies is part of LO3.
              </>
            }
          />

          <SectionRule />

          <FAQ items={faqs} />

          <SectionRule />

          <KeyTakeaways
            points={[
              'DC motor uses commutator + brushes to switch current direction every half rev → constant-direction torque.',
              'Back-EMF E_b ∝ speed; supply current = (V − E_b) / R_a; torque T ∝ I_a × Φ.',
              'Series: T ∝ I² (cranes, traction). Shunt: ~constant speed (machine tools). Compound: in between.',
              'Speed control: armature voltage (below base) + field weakening (above base).',
              'Series motors must NEVER run unloaded — they will overspeed and self-destruct.',
              'BLDC/PMSM is the modern brushless permanent-magnet survivor — EVs, drones, cordless tools.',
              'BS EN 60034-1 mandates plate ratings and duty-cycle classes. BS 7671 §552 governs the supply circuit.',
            ]}
          />

          <Quiz title="DC machines knowledge check" questions={quizQuestions} />

          <div className="grid grid-cols-2 gap-3 pt-2">
            <button
              onClick={() => navigate('/study-centre/apprentice/level3-module3-section4')}
              className="rounded-2xl bg-[hsl(0_0%_12%)] hover:bg-[hsl(0_0%_15%)] transition-colors border border-white/[0.06] p-4 text-left touch-manipulation active:scale-[0.99]"
            >
              <div className="flex items-center gap-2 text-[10.5px] uppercase tracking-[0.18em] text-white">
                <ChevronLeft className="h-3 w-3" /> Previous section
              </div>
              <div className="mt-1 text-[14px] font-semibold text-white truncate">Section 4</div>
            </button>
            <button
              onClick={() => navigate('/study-centre/apprentice/level3-module3-section5-2')}
              className="rounded-2xl bg-elec-yellow hover:bg-elec-yellow/90 transition-colors border border-elec-yellow p-4 text-right touch-manipulation active:scale-[0.99]"
            >
              <div className="flex items-center gap-2 justify-end text-[10.5px] uppercase tracking-[0.18em] text-black/70">
                Next subsection <ChevronRight className="h-3 w-3" />
              </div>
              <div className="mt-1 text-[14px] font-semibold text-black truncate">
                5.2 Single-phase AC motors
              </div>
            </button>
          </div>
        </PageFrame>
      </div>
    </div>
  );
}
