import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  Search,
  Zap,
  ShieldCheck,
  AlertTriangle,
  Wrench,
  Calculator,
  FileCheck2,
  GraduationCap,
  Radio,
  Gauge,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Guides', href: '/guides/electrical-certificate-types-uk' },
  { label: 'Cable Detector Buying Guide', href: '/guides/cable-detector-buying-guide' },
];

const tocItems = [
  { id: 'overview', label: 'Why Cable Detection is Safety-Critical' },
  { id: 'signal-vs-live', label: 'Signal Generator vs Live Cable Detection' },
  { id: 'cat-genny', label: 'The CAT & Genny System Explained' },
  { id: 'depth-signal', label: 'Depth Indication and Signal Strength' },
  { id: 'avoiding-errors', label: 'Common Errors and How to Avoid Them' },
  { id: 'best-detectors', label: 'Best Cable Detectors 2026' },
  { id: 'for-electricians', label: 'Cable Detection in Practice' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'Cable detectors (also called Cable Avoidance Tools, or CATs) detect buried services before excavation or drilling to prevent cable strike injuries and service damage.',
  'There are two detection modes: passive mode detects live cables by the electromagnetic field produced by mains frequency current; active mode uses a signal generator (Genny) to inject a traceable signal onto a known cable or system.',
  'Depth indication is an approximation — depth figures from a CAT should be treated as indicative, not precise. Always verify with trial excavation before heavy digging near the indicated depth.',
  'Signal strength varies with cable depth, current level, cable shielding, soil conditions, and the orientation of the detector. Sweep in multiple directions and use the peak-null method for accurate location.',
  'The Radiodetection CAT4+ with Genny4, Leica DD130, and Ridgid Scout 100 are the leading professional systems for UK electricians and civil contractors in 2026.',
];

const faqs = [
  {
    question: 'What is the difference between CAT (passive) mode and Genny (active) mode?',
    answer:
      'Passive mode detects electromagnetic fields produced by cables already carrying a signal — either the 50Hz field from mains voltage cables, or radio frequency fields induced in buried metallic services from natural or man-made RF sources. Passive mode requires no preparation and can detect any energised mains cable or pipe carrying a signal. Active mode (Genny mode) uses a signal generator to inject a specific frequency signal onto a cable or service, which the CAT detector then locates. Active mode is more accurate and more reliable for locating specific services because the injected signal is stronger and at a distinct frequency not present in the environment. It can also locate cables that are de-energised (no current, no passive field). Active mode requires physical access to the cable or a connected conductor to apply the Genny signal.',
  },
  {
    question: 'How accurate is the depth indication on a cable detector?',
    answer:
      'Depth indication on a CAT is based on the ratio of signal strength between a pair of antenna elements at known separation. It is an approximation — not a precision measurement. Accuracy is typically ±10–15% under ideal conditions (homogeneous soil, single isolated cable, correct detector orientation). Accuracy degrades significantly when multiple cables are close together (mutual interference), when the cable is shielded, when soil conditions are heterogeneous, or when the detector is not held in the correct orientation. Always treat depth readings as indicative only. The Highway Authorities and Utilities Committee (HAUC) code of practice and PAS 128 (specification for underground utility detection) both state that depth readings should be used for initial assessment only, with trial excavation required to confirm depth before heavy digging.',
  },
  {
    question: 'Can a cable detector find de-energised buried cables?',
    answer:
      'In passive mode, no — a cable detector relies on an electromagnetic field generated by current flowing in the cable. A de-energised cable with no current carries no field and cannot be detected passively. In active mode (Genny mode), the signal generator injects a signal onto the cable. This requires physical access to the cable termination or a connected metallic conductor. If you can connect the Genny to a metal pipe or cable tray that is electrically connected to the buried cable, the injected signal will travel along the buried service and the CAT can detect it. For completely isolated buried cables with no accessible termination, ground-penetrating radar (GPR) is the appropriate technology — but this is specialist equipment beyond the scope of a standard cable detector.',
  },
  {
    question: 'What is the peak-null method for accurate cable location?',
    answer:
      'The peak-null method uses two different antenna configurations on the CAT to accurately pinpoint the cable position. In peak mode, the detector displays maximum signal strength when the antenna is directly above the cable — the signal peaks at the cable position. In null mode, the detector uses a different antenna orientation that produces a null (minimum) signal when directly above the cable, with maximum signal at either side. The null point is narrower and more precise than the peak point, making it easier to pinpoint the exact cable position. The standard procedure is to first use peak mode to find the approximate cable direction, then switch to null mode to pinpoint the exact position by finding the minimum signal. Mark the cable line from multiple null points. Modern CATs like the Radiodetection CAT4+ perform this automatically, but understanding the underlying method helps interpret readings correctly.',
  },
  {
    question: 'How do I use a Genny to trace a specific cable?',
    answer:
      'The Genny (signal generator) is applied to the cable or service you want to trace. Connection methods depend on the access available: direct connection using crocodile clips to the cable termination conductors, inductive (clamp) coupling around the cable where it is accessible, or signal coupling through a metallic pipe or cable tray electrically connected to the buried service. The Genny must be earthed — either to the installation earth, a temporary earth stake, or a metallic object with a good earth connection. The injected signal frequency should be set to a frequency that the CAT receiver is tuned to detect. On the Radiodetection CAT4+, the receiver automatically detects the Genny4 signal frequency. Tune the receiver sensitivity so the signal is detectable but not so strong that it couples onto adjacent services and creates a false trace.',
  },
  {
    question: 'Is a cable detector necessary for drilling into walls inside a building?',
    answer:
      'Yes. Buried wiring inside walls, floors, and ceilings can be located and damaged by drilling or chiselling during alterations, second fixing, or maintenance work. The risk of cable strike and electric shock or arc flash is real even in internal wall drilling. A compact cable detector (such as the Bosch GMS 120 for domestic use, or the Ridgid Scout 100 for professional use) provides a rapid scan before drilling to identify buried cables, water pipes, and other services. PAS 68 (buried services guidance for domestic work) recommends cable detection before any core drilling, chiselling, or chase cutting that penetrates a wall or floor. Cable strikes during internal building work are a common cause of electrical accidents reported to HSE under RIDDOR.',
  },
  {
    question: 'What is the difference between the Radiodetection CAT4 and CAT4+?',
    answer:
      'The CAT4 and CAT4+ are the current (4th generation) Radiodetection cable avoidance tools. The CAT4+ adds several features over the base CAT4: a strike alert that records every time the detector enters a high-signal-strength zone (providing a tamper-evident log of near-misses for safety records), Bluetooth data logging for live depth and position data, and a more sensitive receiver for lower-current cables. Both models detect the same frequency ranges in passive and active modes. The Genny4 signal generator is compatible with both. For contractors who need strike logging for safety compliance records, the CAT4+ is the appropriate choice. For general use where data logging is not required, the CAT4 offers the same core detection performance at a lower cost.',
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/guides/multimeter-guide-electricians',
    title: 'Multimeter Guide for Electricians',
    description: 'CAT ratings, True RMS, and the best digital multimeters for professional use.',
    icon: Gauge,
    category: 'Guide',
  },
  {
    href: '/guides/drill-guide-electricians-sds-cordless',
    title: 'Drill Guide for Electricians',
    description: 'SDS Plus vs SDS Max, cordless voltage ratings, and hole saws for back boxes.',
    icon: Wrench,
    category: 'Guide',
  },
  {
    href: '/guides/safe-isolation-procedure',
    title: 'Safe Isolation Procedure',
    description: 'Step-by-step safe isolation before starting any electrical work.',
    icon: ShieldCheck,
    category: 'Guide',
  },
  {
    href: '/tools/eic-certificate',
    title: 'EIC Certificate App',
    description: 'Complete Electrical Installation Certificates on site from your phone.',
    icon: FileCheck2,
    category: 'Certificate',
  },
  {
    href: '/tools/cable-sizing-calculator',
    title: 'Cable Sizing Calculator',
    description: 'Size cables for buried runs and surface wiring with full BS 7671 derating.',
    icon: Calculator,
    category: 'Tool',
  },
  {
    href: '/training/health-and-safety',
    title: 'Health and Safety Training',
    description: 'CDM, manual handling, confined spaces, and excavation safety courses.',
    icon: GraduationCap,
    category: 'Training',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'overview',
    heading: 'Why Cable Detection is Safety-Critical',
    content: (
      <>
        <p>
          Cable strikes are one of the most serious hazards in construction and electrical work.
          Striking a buried cable while drilling, chiselling, or excavating can cause electrocution,
          arc flash, explosion, fire, and gas release if associated services are also damaged. HSE
          statistics consistently identify cable strikes as a significant cause of serious injuries
          and fatalities in construction.
        </p>
        <p>
          The Health and Safety Executive (HSE) guidance document HSG47 "Avoiding Danger from
          Underground Services" sets out the requirement to identify and locate underground services
          before excavation. The principle applies equally to internal building work — buried cables
          in walls and floors must be located before drilling or chasing.
        </p>
        <p>
          A cable detector (Cable Avoidance Tool, or CAT) is the primary tool for locating buried
          services on site. Used correctly with a signal generator (Genny), it can locate mains
          cables, water pipes, gas pipes (where they carry a signal), and telecomms conduits before
          work begins. This guide covers the detection methods, the CAT & Genny system, depth
          indication, common errors, and the best detectors available in 2026.
        </p>
      </>
    ),
  },
  {
    id: 'signal-vs-live',
    heading: 'Signal Generator Method vs Live Cable Detection',
    content: (
      <>
        <p>
          Cable detection relies on two fundamentally different principles. Understanding both is
          essential for reliable service location:
        </p>
        <div className="grid gap-4 sm:grid-cols-2 my-4">
          <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-3">Passive Detection (Live Cable Mode)</h3>
            <p className="text-white text-sm leading-relaxed mb-3">
              Detects the electromagnetic field radiated by current flowing in a buried conductor.
              Mains cables carrying 50Hz alternating current produce a characteristic 50Hz
              electromagnetic field that the CAT receiver detects and displays. Radio frequency
              detection (often called "Radio" mode) detects lower-level RF fields induced in buried
              metallic conductors by man-made and natural radio frequency signals.
            </p>
            <ul className="space-y-1 text-white text-sm">
              <li className="flex items-start gap-2"><span className="text-green-400">+</span><span>No preparation required</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400">+</span><span>Detects any energised mains cable</span></li>
              <li className="flex items-start gap-2"><span className="text-red-400">–</span><span>Cannot detect de-energised cables</span></li>
              <li className="flex items-start gap-2"><span className="text-red-400">–</span><span>Multiple cables cause mutual interference</span></li>
              <li className="flex items-start gap-2"><span className="text-red-400">–</span><span>Cannot distinguish which service is which</span></li>
            </ul>
          </div>
          <div className="rounded-2xl bg-green-500/10 border border-green-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-3">Active Detection (Genny Mode)</h3>
            <p className="text-white text-sm leading-relaxed mb-3">
              A signal generator (Genny) is connected to the target service and injects a specific
              frequency signal. The CAT receiver detects only this injected frequency, giving a
              strong, clean signal on the specific cable being traced while ignoring other services.
            </p>
            <ul className="space-y-1 text-white text-sm">
              <li className="flex items-start gap-2"><span className="text-green-400">+</span><span>Traces a specific identified service</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400">+</span><span>Works on de-energised cables</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400">+</span><span>Stronger, more reliable signal</span></li>
              <li className="flex items-start gap-2"><span className="text-red-400">–</span><span>Requires access to connect the Genny</span></li>
              <li className="flex items-start gap-2"><span className="text-red-400">–</span><span>Signal can couple to adjacent services</span></li>
            </ul>
          </div>
        </div>
        <p>
          Best practice per HSG47 and PAS 128 is to use both methods: passive mode first to identify
          all services in the area, then active mode with the Genny to trace specific services and
          confirm their routes before excavation.
        </p>
      </>
    ),
  },
  {
    id: 'cat-genny',
    heading: 'The CAT & Genny System Explained',
    content: (
      <>
        <p>
          The CAT (Cable Avoidance Tool) and Genny (signal generator) system is the industry
          standard for professional cable location in the UK. The two instruments work as a matched
          pair: the Genny generates a signal at a specific frequency, and the CAT receiver is tuned
          to detect that frequency.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Radio className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Genny connection methods:</strong> Direct connection (crocodile clips to
                cable termination conductors), inductive coupling (clamp the Genny transmitter coil
                around the cable where accessible), or signal plate coupling (place the Genny signal
                plate on the ground over a buried service to couple inductively without direct
                contact). The earthing connection is always required — Genny to installation earth,
                earth stake, or metallic earth reference.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Radio className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Signal frequencies:</strong> Most Genny systems operate at 33kHz (general
                purpose) and 8Hz (selective, lower coupling to adjacent services). The Radiodetection
                CAT4+/Genny4 system uses 33kHz and 131kHz with automatic frequency detection in the
                receiver. Lower frequencies travel further along services with less coupling to
                adjacents; higher frequencies give a stronger signal over short distances.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Radio className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Signal coupling to adjacent services:</strong> The injected signal will
                couple electromagnetically to any nearby metallic service running parallel to the
                target cable. This can create a false trace on an adjacent water pipe or telecomms
                duct. Always compare signal strength between services — the strongest signal should
                be on the target service. Use lower frequency (8Hz) to reduce coupling to adjacents
                in congested service corridors.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'depth-signal',
    heading: 'Depth Indication and Signal Strength',
    content: (
      <>
        <p>
          Depth indication and signal strength display are two key outputs from a professional CAT.
          Understanding their limitations is as important as knowing how to use them:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4 space-y-4">
          <div>
            <h3 className="font-bold text-white mb-2 flex items-center gap-2">
              <Gauge className="w-4 h-4 text-yellow-400" />
              Depth Indication
            </h3>
            <p className="text-white text-sm leading-relaxed">
              Calculated from the ratio of signal strength at two antenna heights. Provides an
              approximate depth under ideal conditions — single isolated cable, homogeneous ground,
              correct detector orientation. Error of ±10–15% under ideal conditions; much larger
              in practice near multiple services, rebar, or heterogeneous ground. Always treat depth
              as indicative — confirm by trial excavation before heavy plant work. PAS 128 quality
              levels define acceptable depth accuracy for survey work.
            </p>
          </div>
          <div>
            <h3 className="font-bold text-white mb-2 flex items-center gap-2">
              <Gauge className="w-4 h-4 text-blue-400" />
              Signal Strength Bar/Indicator
            </h3>
            <p className="text-white text-sm leading-relaxed">
              Displays the relative strength of the detected signal. Signal strength increases as you
              move directly over the cable and decreases as you move away. Used to track the cable
              route by keeping to the line of maximum signal. Sensitivity should be set so the
              maximum on-cable reading is approximately 80% of full scale — not pegged to maximum,
              as this saturates the display and makes it impossible to distinguish the peak location.
            </p>
          </div>
        </div>
        <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5 my-4">
          <h3 className="font-bold text-white mb-2 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-yellow-400" />
            Signal Sweep Technique
          </h3>
          <p className="text-white text-sm leading-relaxed">
            Walk a grid pattern over the suspected cable area in two perpendicular directions. Mark
            cable positions from multiple sweeps. Cross-reference peak mode markings with null mode
            markings (which are more precise) for accurate position. In congested areas with multiple
            services, the signal patterns from individual cables overlap and must be carefully
            interpreted. Call in a specialist buried services surveyor where services are densely
            packed or high-risk.
          </p>
        </div>
      </>
    ),
  },
  {
    id: 'avoiding-errors',
    heading: 'Common Errors and How to Avoid Them',
    content: (
      <>
        <p>
          Cable detection errors lead to cable strikes. The most common errors are:
        </p>
        <div className="rounded-2xl bg-red-500/10 border border-red-500/20 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 shrink-0" />
              <span>
                <strong>Assuming no signal means no cable:</strong> Passive mode only detects
                energised cables. De-energised, low-load, or well-shielded cables may give no
                detectable signal. Always use active Genny mode to supplement passive detection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 shrink-0" />
              <span>
                <strong>Incorrect sensitivity setting:</strong> Too high a sensitivity causes the
                signal to saturate — the detector shows maximum signal everywhere, making it
                impossible to locate the cable precisely. Too low a sensitivity misses weak signals
                from deep or low-current cables. Adjust sensitivity for each location.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 shrink-0" />
              <span>
                <strong>Sweeping in one direction only:</strong> Cables run in unexpected directions.
                Always sweep in at least two perpendicular directions. A cable running parallel to
                your sweep direction may give only a weak, broad signal — sweeping perpendicular
                gives a clear cross-cable reading.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 shrink-0" />
              <span>
                <strong>Treating depth as accurate:</strong> Depth indication is approximate. Cables
                may be deeper or shallower than indicated due to ground conditions, cable bends, or
                interference from nearby services. Use depth indication for initial assessment and
                confirm by careful trial excavation.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 shrink-0" />
              <span>
                <strong>Failing to obtain service records:</strong> Always request service records
                from the relevant utility companies and building management before commencing work.
                Cable detection is a supplement to, not a substitute for, researching existing
                drawings and service records.
              </span>
            </li>
          </ul>
        </div>
        <SEOAppBridge
          title="Document site conditions and services before work starts"
          description="Use Elec-Mate's AI to generate method statements and risk assessments for excavation and cable work — including buried service identification procedures and toolbox talk records."
          icon={ShieldCheck}
        />
      </>
    ),
  },
  {
    id: 'best-detectors',
    heading: 'Best Cable Detectors for Electricians 2026',
    content: (
      <>
        <p>
          The professional cable detector market in 2026 is dominated by Radiodetection and Leica at
          the top end, with strong mid-range options from Ridgid and C.Scope. Here are the leading
          choices for UK electricians and contractors:
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-1">Radiodetection CAT4+ with Genny4</h3>
            <p className="text-white text-xs mb-3 uppercase tracking-wide">
              Industry Standard Professional System — ~£900 (kit)
            </p>
            <p className="text-white text-sm leading-relaxed">
              The Radiodetection CAT (Cable Avoidance Tool) and Genny (signal generator) system is
              the most widely used professional cable detection system in the UK. The CAT4+ adds
              strike alert data logging and Bluetooth connectivity over the base CAT4. Detects power
              (50Hz passive), radio (RF passive), and Genny4 signal (33kHz and 131kHz active). Depth
              indication on active signal. Excellent sensitivity for low-current cables. The go-to
              recommendation for any contractor involved in excavation or buried services work.
            </p>
          </div>
          <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-1">Leica DD130 (CAT & Genny)</h3>
            <p className="text-white text-xs mb-3 uppercase tracking-wide">
              Best Alternative Professional System — ~£750 (kit)
            </p>
            <p className="text-white text-sm leading-relaxed">
              Leica's DD130 is a capable professional alternative to the Radiodetection system.
              Passive power and radio detection plus active Genny signal. Clear display with depth
              indication. Robust construction suited to outdoor site conditions. Compatible with
              Leica's broader geospatial survey equipment ecosystem — useful for contractors who
              already use Leica survey instruments. Slightly lighter than the CAT4+ which some users
              prefer for all-day carrying on large sites.
            </p>
          </div>
          <div className="rounded-2xl bg-green-500/10 border border-green-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-1">Ridgid Scout 100</h3>
            <p className="text-white text-xs mb-3 uppercase tracking-wide">
              Best for Internal Building Work — ~£300
            </p>
            <p className="text-white text-sm leading-relaxed">
              Compact cable and pipe locator designed for use inside buildings — walls, floors, and
              ceilings. Detects energised cables and metallic water/gas pipes. Separate transmitter
              applies a signal to pipes and cables for active tracing. Smaller form factor than
              full-size CAT systems suits internal wall scanning before drilling. A good choice for
              electricians who primarily do internal alterations work and do not regularly work on
              buried external services.
            </p>
          </div>
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-5">
            <h3 className="font-bold text-white text-lg mb-1">C.Scope MXL4 with SGA4</h3>
            <p className="text-white text-xs mb-3 uppercase tracking-wide">
              UK-Made Alternative — ~£600 (kit)
            </p>
            <p className="text-white text-sm leading-relaxed">
              C.Scope is a UK-based cable detector manufacturer with a long track record in the
              utilities sector. The MXL4 provides all standard passive and active detection modes.
              The SGA4 signal generator pairs with the MXL4 for active service tracing. Preferred by
              some UK utilities contractors who appreciate the UK manufacturer support and service
              network. Competitive with Radiodetection on sensitivity and features at a slightly
              lower price point.
            </p>
          </div>
        </div>
      </>
    ),
  },
  {
    id: 'for-electricians',
    heading: 'Cable Detection in Practice: Before You Drill or Dig',
    content: (
      <>
        <p>
          Cable detection integrates into the pre-work safety routine for any job involving drilling,
          chasing, or excavation. Here is the systematic approach recommended by HSG47:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ol className="space-y-4 text-white list-decimal list-inside">
            <li>
              <strong>Obtain service records</strong> — contact the relevant utility companies and
              building owner to obtain existing service drawings. Check the planning drawings and
              building services as-built drawings for internal work.
            </li>
            <li>
              <strong>Visual survey</strong> — identify surface features that indicate underground
              services: valve boxes, junction boxes, marker posts, overhead lines, and the route of
              service entry points into the building.
            </li>
            <li>
              <strong>Passive CAT sweep</strong> — sweep the work area in power mode (50Hz) and
              radio mode to identify all detected services. Mark positions with marking spray or pins.
            </li>
            <li>
              <strong>Active Genny tracing</strong> — connect the Genny to known accessible services
              and trace their routes through the work area. Mark confirmed routes.
            </li>
            <li>
              <strong>Reconcile with records</strong> — compare detected service positions with
              service records. Investigate any discrepancies before proceeding.
            </li>
            <li>
              <strong>Trial excavation</strong> — hand dig trial holes to expose and visually confirm
              service positions and depths before using mechanical plant.
            </li>
          </ol>
        </div>
        <SEOAppBridge
          title="Generate pre-work risk assessments and method statements"
          description="Elec-Mate's AI generates site-specific method statements for drilling, chasing, and excavation work — including buried services identification, PPE requirements, and emergency procedures. Professional PDF output."
          icon={Search}
        />
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function CableDetectorBuyingGuidePage() {
  return (
    <GuideTemplate
      title="Cable Detector Buying Guide UK 2026 | CAT & Genny for Electricians"
      description="Complete cable detector buying guide for UK electricians and contractors. How CAT and Genny systems work, signal generator vs passive detection, depth indication, common errors, and the best cable detectors in 2026 — Radiodetection CAT4+, Leica DD130, Ridgid Scout 100."
      datePublished="2026-03-27"
      dateModified="2026-03-27"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Tools & Equipment Guide"
      badgeIcon={Search}
      heroTitle={
        <>
          Cable Detector Buying Guide:{' '}
          <span className="text-yellow-400">CAT & Genny Systems for UK Electricians 2026</span>
        </>
      }
      heroSubtitle="Everything you need to know about cable detectors — passive vs active detection, the CAT & Genny system, depth indication limitations, common survey errors, and the best cable avoidance tools for professional electrical and civil work in 2026."
      readingTime={12}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions About Cable Detectors"
      relatedPages={relatedPages}
      ctaHeading="Generate Method Statements and Risk Assessments for Cable Work"
      ctaSubheading="Join 430+ UK electricians using Elec-Mate for AI-generated method statements, risk assessments, and professional EIC certification. 7-day free trial, cancel anytime."
    />
  );
}
