import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  Zap,
  ShieldCheck,
  AlertTriangle,
  Server,
  Activity,
  Layers,
  FileCheck2,
  Settings,
  PoundSterling,
  ClipboardCheck,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Commercial Electrical', href: '/commercial-electrical-installation' },
  { label: 'Data Centre Electrical Installation', href: '/data-centre-electrical-installation' },
];

const tocItems = [
  { id: 'overview', label: 'Overview' },
  { id: 'tier-classifications', label: 'Tier Classifications' },
  { id: 'ups-systems', label: 'UPS Systems' },
  { id: 'dual-power-feeds', label: 'Dual Power Feeds & PDUs' },
  { id: 'earthing', label: 'Earthing & BS 7671 TN-S' },
  { id: 'busbar-generators', label: 'Busbars & Generator Backup' },
  { id: 'cooling-integration', label: 'Cooling Integration' },
  { id: 'critical-power-calculations', label: 'Critical Power Calculations' },
  { id: 'for-electricians', label: 'For Electricians' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'Data centres are classified into Tier I through Tier IV by the Uptime Institute. Tier IV requires fully fault-tolerant infrastructure with N+1 or 2N redundancy on all electrical systems including UPS, generators, and distribution paths.',
  'BS 7671:2018+A3:2024 requires data centre installations to follow a TN-S earthing system (separate neutral and protective earth conductors) to minimise earth loop impedance and prevent conducted noise on sensitive IT equipment.',
  'Uninterruptible Power Supply (UPS) systems must be sized to cover the full critical load plus an additional 25 per cent capacity margin, with battery autonomy matched to the on-site generator start and transfer time.',
  'The Electricity at Work Regulations 1989 place a duty on duty holders to ensure electrical systems are maintained so as to prevent danger — this includes formal periodic inspection and testing of all HV and LV systems in data centres.',
  'Power Usage Effectiveness (PUE) is the primary efficiency metric for data centres. UK modern facilities target a PUE of 1.2 to 1.4; legacy sites can exceed 2.0. Electrical design directly determines PUE performance.',
];

const faqs = [
  {
    question:
      'What earthing system is recommended for data centre electrical installations in the UK?',
    answer:
      'BS 7671:2018+A3:2024 recommends TN-S (Terra Neutral Separated) earthing for data centre environments. In a TN-S system the neutral and protective earth conductors are kept entirely separate throughout the installation, which minimises earth loop impedance and prevents conducted noise from returning via the neutral to IT equipment. A single earth reference point (star point) is established at the main LV switchboard, with separate PE conductors run to all distribution boards and IT equipment frames. Mixed TN-C-S systems should be avoided in critical environments.',
  },
  {
    question: 'What is N+1 redundancy in data centre power systems?',
    answer:
      'N+1 redundancy means that for every N critical components required to run the facility, one additional (spare) component is installed. For example, if four UPS modules are needed to carry the full load, five are installed. If any single module fails, the remaining four can still carry the full load. Tier II data centres require N+1 redundancy. Tier III and IV require concurrent maintainability and fault tolerance respectively, which typically means 2N (fully duplicated) power paths from separate utility supplies to individual rack PDUs.',
  },
  {
    question: 'How are UPS systems sized for data centre installations?',
    answer:
      'UPS sizing begins with an accurate power audit of the IT load at full capacity. The UPS is then sized to 75 to 80 per cent of its rated capacity at full IT load, leaving headroom for load growth and preventing operation near the efficiency dip at very low load factors. Battery autonomy (runtime) is sized to cover the generator start and transfer sequence plus a safety margin — typically 10 to 15 minutes for sites with on-site generators. The UPS must also be capable of handling the harmonic distortion generated by IT switch-mode power supplies, which can reach a Total Harmonic Distortion (THD) of 30 per cent or more.',
  },
  {
    question: 'What is a Power Distribution Unit (PDU) in a data centre context?',
    answer:
      'A data centre Power Distribution Unit (PDU) is a device that distributes electrical power from a UPS or main distribution board to multiple server racks and IT equipment within the data hall. Intelligent (or "smart") PDUs provide individual outlet-level metering, remote switching, and environmental monitoring. Data centre PDUs typically operate at 32A or 63A, often at 230V single-phase or 400V three-phase. Each rack is typically served by two PDUs fed from independent power paths (A-feed and B-feed) to provide redundancy at rack level.',
  },
  {
    question:
      'What are the Electricity at Work Regulations 1989 obligations for data centre operators?',
    answer:
      'The Electricity at Work Regulations 1989 impose duties on employers and others in control of electrical systems (duty holders) to ensure those systems are constructed and maintained so as to prevent danger. For data centres this means: maintaining all switchgear, UPS systems, generators, and cabling in safe condition; conducting periodic inspection and testing in accordance with BS 7671; keeping records of all maintenance; ensuring only competent persons work on or near live conductors; and implementing safe systems of work (permits to work) for maintenance activities. Regulation 4(2) places a positive duty to maintain the system — failing to inspect and test is a criminal offence.',
  },
  {
    question: 'What is Power Usage Effectiveness (PUE) and how does electrical design affect it?',
    answer:
      'PUE is the ratio of total facility power consumption to IT equipment power consumption. A PUE of 1.0 is theoretically perfect (all power goes to IT). A PUE of 2.0 means half of all power is consumed by overhead systems (cooling, lighting, power conversion losses). Electrical design affects PUE through UPS efficiency (modern modular UPS units achieve 97 per cent efficiency in eco-mode), transformer losses, cable sizing (undersized cables increase resistive losses), power factor correction, and voltage level selection. Running distribution at 11kV or 33kV HV directly to data hall transformers reduces the number of power conversion stages and improves PUE.',
  },
  {
    question: 'What generator specifications are required for data centre backup power?',
    answer:
      'Data centre diesel generators are typically rated to PRP (Prime Rated Power) or LTP (Limited-Time Running Power) duty. Generator sets must start and reach stable voltage and frequency within 10 to 15 seconds of a mains failure (the UPS battery covers this transfer window). For Tier III and IV facilities, generators are sized to N+1 and often include dual fuel capability for extended outages. BS 7671 and the IET Code of Practice for Generator Systems require the generating system to be treated as a separate source, with appropriate protection co-ordination to prevent the generator and utility supply ever being paralleled unintentionally.',
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/hospital-electrical-installation',
    title: 'Hospital Electrical Installation',
    description:
      'Healthcare electrical systems, IEC 60364-7-710, isolated power supplies, and HTM06-01.',
    icon: ShieldCheck,
    category: 'Guide',
  },
  {
    href: '/factory-electrical-installation',
    title: 'Factory Electrical Installation',
    description:
      'Three-phase supplies, motor control centres, HRC fuses, and ATEX zone classification.',
    icon: Settings,
    category: 'Guide',
  },
  {
    href: '/guides/eicr-commercial-property',
    title: 'Commercial EICR Guide',
    description:
      'Periodic inspection and testing requirements for commercial and industrial premises.',
    icon: ClipboardCheck,
    category: 'Guide',
  },
  {
    href: '/tools/electrical-quoting-app',
    title: 'Electrical Quoting App',
    description:
      'Quote data centre and commercial electrical projects on site with instant PDF export.',
    icon: PoundSterling,
    category: 'Tool',
  },
  {
    href: '/tools/eicr-certificate',
    title: 'EICR Certificate App',
    description: 'Complete EICRs on your phone with AI board scanning and instant PDF export.',
    icon: FileCheck2,
    category: 'Certificate',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'overview',
    heading: 'Data Centre Electrical Installation in the UK',
    content: (
      <>
        <p>
          Data centres represent some of the most demanding electrical environments in the UK. The
          combination of extremely high power densities, zero-tolerance for unplanned downtime, and
          complex redundancy requirements means that data centre electrical installation demands
          expertise well beyond standard commercial work. Electricians and electrical contractors
          working in this sector must have a thorough understanding of UPS systems, generator
          integration, HV distribution, harmonic mitigation, and the specific earthing requirements
          of IT-sensitive environments.
        </p>
        <p>
          The UK data centre market has expanded rapidly, driven by cloud computing, AI workloads,
          and digital infrastructure investment. London remains the primary UK data centre hub, with
          significant clusters in Slough, Docklands, and the M25 corridor. Regional data centres in
          Manchester, Birmingham, and Edinburgh are also growing. All must comply with BS 7671, the
          Electricity at Work Regulations 1989, and building regulations.
        </p>
        <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Server className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Primary standards:</strong> BS 7671:2018+A3:2024 (IET Wiring Regulations),
                Electricity at Work Regulations 1989, EN 50600 (European data centre standard), and
                Uptime Institute Tier Classification.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Server className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Power densities:</strong> Modern hyperscale data centres can reach 20 to 50
                kW per rack, compared to 3 to 5 kW per rack in legacy facilities. Electrical
                infrastructure must be designed for these densities from day one.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Server className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Competence requirements:</strong> The Electricity at Work Regulations 1989
                require that persons working on data centre electrical systems are competent for the
                work they undertake. HV work additionally requires authorisation under a formal
                Authorisation and Safety Rules document.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'tier-classifications',
    heading: 'Tier Classifications and Redundancy Requirements',
    content: (
      <>
        <p>
          The Uptime Institute Tier Classification system is the internationally recognised standard
          for data centre reliability. Each Tier level specifies minimum requirements for electrical
          and mechanical redundancy, which directly determines the complexity and cost of the
          electrical installation.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Layers className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Tier I — Basic:</strong> Single non-redundant distribution path. UPS and
                generator required but no redundancy. Susceptible to disruption from planned and
                unplanned maintenance. Annual downtime up to 28.8 hours. Suitable for small server
                rooms with low criticality workloads.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Layers className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Tier II — Redundant Components:</strong> N+1 redundancy on UPS modules,
                generators, and cooling. Single distribution path. Annual downtime up to 22 hours.
                Planned maintenance requires a shutdown window.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Layers className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Tier III — Concurrently Maintainable:</strong> Multiple active distribution
                paths with N+1 redundancy. All equipment can be maintained without shutting down the
                load. Annual downtime up to 1.6 hours. The most common tier for commercial UK
                colocation facilities.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Layers className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Tier IV — Fault Tolerant:</strong> 2N (fully duplicated) electrical and
                mechanical systems. Any single failure of a component, system, or distribution path
                does not interrupt the load. Annual downtime up to 26 minutes. Required for
                financial trading systems, emergency services, and critical national infrastructure.
              </span>
            </li>
          </ul>
        </div>
        <p>
          The Tier specification must be agreed with the client before design commences. Tier IV
          infrastructure can cost three to four times more than Tier I to build and requires
          significantly more electrical plant space, cable volume, and switchgear complexity.
        </p>
      </>
    ),
  },
  {
    id: 'ups-systems',
    heading: 'UPS Systems for Data Centre Installations',
    content: (
      <>
        <p>
          Uninterruptible Power Supply (UPS) systems are the central element of data centre power
          protection. They bridge the gap between a mains failure and the start of backup
          generators, filter power quality issues, and protect sensitive IT equipment from voltage
          transients, sags, and surges.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Double-conversion (online) UPS:</strong> The standard topology for data
                centres. AC mains is rectified to DC, then inverted back to clean AC. The load is
                always fed from the inverter, providing complete isolation from mains disturbances.
                Efficiency of modern units reaches 97 per cent in eco-mode.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Modular UPS architecture:</strong> Large data centres use modular UPS frames
                where individual power modules (typically 20 to 75 kW each) can be hot-swapped
                without interrupting the load. This enables N+1 redundancy within a single frame and
                allows capacity to grow with the IT load.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Battery management:</strong> VRLA (Valve Regulated Lead Acid) batteries are
                most common, but lithium-ion battery systems are increasingly adopted for their
                higher energy density, longer life, and faster recharge capability. Battery rooms
                require ventilation to BS EN 50272-2 to manage hydrogen gas evolution.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Static bypass:</strong> All data centre UPS systems include a static bypass
                switch that allows the load to be transferred directly to raw mains in under 20
                milliseconds for UPS maintenance. The bypass must be interlocked to prevent
                back-feeding the generator onto the utility supply.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'dual-power-feeds',
    heading: 'Dual Power Feeds and Power Distribution Units',
    content: (
      <>
        <p>
          To achieve Tier III and IV availability, every server rack must be fed from two
          independent power paths, each capable of carrying the full rack load independently. This
          A-feed and B-feed architecture must be maintained from the utility supply all the way to
          the rack PDU.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Diverse supply paths:</strong> A-feed and B-feed must be physically
                separated — different cable routes, different UPS systems, different Automatic
                Transfer Switches (ATS), and separate distribution boards. Any single cable failure,
                switchgear fault, or UPS failure must not affect both feeds simultaneously.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Rack PDU types:</strong> Basic PDUs simply distribute power to outlets.
                Metered PDUs add input current monitoring. Switched PDUs enable individual outlet
                switching. Intelligent PDUs add outlet-level monitoring, environmental sensors, and
                remote access via IP. For new data centre installations, intelligent PDUs are
                strongly recommended for load balancing visibility and fault diagnosis.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Three-phase balance:</strong> Data hall PDUs are typically three-phase 32A
                or 63A with single-phase outlet circuits. Care must be taken during commissioning to
                balance loads across all three phases. Imbalance exceeding 10 per cent at the main
                distribution board should be corrected to maintain neutral conductor integrity and
                minimise UPS capacity waste.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Busway systems:</strong> High-density data halls increasingly use overhead
                busway (busbar trunking) systems rather than fixed cable runs to the racks. Busway
                allows tap-off boxes to be repositioned as rack layouts change, significantly
                reducing reconfiguration costs. The busway must be protected to the same level as
                the circuit breaker feeding it.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'earthing',
    heading: 'Earthing Systems — BS 7671 TN-S for Data Centres',
    content: (
      <>
        <p>
          Correct earthing is critical in data centre environments. IT equipment is highly sensitive
          to earth potential differences and conducted electrical noise. BS 7671:2018+A3:2024 and
          the IET Code of Practice for Earthing recommend TN-S earthing for IT-sensitive
          installations.
        </p>
        <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>TN-S system:</strong> Neutral (N) and Protective Earth (PE) conductors are
                kept separate throughout the installation. The neutral is connected to earth at the
                supply transformer star point only. This prevents earth fault current returning via
                the neutral and minimises the potential for conducted noise on sensitive IT
                equipment.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Meshed equipotential bonding network (MEPBN):</strong> Data centres
                implement a MEPBN (sometimes called a Signal Reference Grid or SRG) across the
                raised floor or within the structural fabric. This mesh of conductors bonds all
                equipment frames and racks to a common earth reference, eliminating potential
                differences that could damage equipment or cause data errors.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Earth electrode systems:</strong> Where TN-S supply is not available from
                the utility (many UK utility supplies are TN-C-S), an independent earth electrode
                system must be installed and the supply converted to TN-S at the main LV intake.
                Earth electrode resistance should be measured to confirm compliance with Regulation
                542.2 of BS 7671.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Generator earthing:</strong> When a generator operates in island mode
                (disconnected from the utility), it must have its own earthing arrangement. This
                typically means the generator neutral is connected to an earth electrode at the
                generator terminals, with the utility neutral link in the ATS opened when the
                generator is running.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'busbar-generators',
    heading: 'Busbar Systems and Generator Backup',
    content: (
      <>
        <p>
          Busbar trunking systems and diesel generator sets form the backbone of high-availability
          data centre power infrastructure. These systems must be designed, installed, and
          maintained to the highest standards to ensure that the electrical infrastructure never
          becomes the weak link in the availability chain.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Settings className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Main LV switchboard (MLVS):</strong> The main LV switchboard receives the
                incoming supply from the HV/LV transformer(s) and distributes power to UPS systems,
                mechanical plant, and lighting. For redundant facilities, two or more MLVS busbars
                are fed from separate transformers and linked by a bus-section circuit breaker with
                automatic transfer logic.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Settings className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Horizontal busbar trunking:</strong> High-current busbar trunking (typically
                1,600A to 6,300A) is used to distribute power from the MLVS to zone distribution
                boards across the data hall. Busway joints must be torqued to manufacturer
                specification and thermally imaged during commissioning.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Settings className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Generator sets:</strong> Standby generators are sized to carry the full data
                centre load on generator power alone, including mechanical cooling plant. Step-load
                acceptance testing confirms the generator can pick up the full load in stages
                without voltage or frequency excursions outside acceptable limits (typically ±10%
                voltage, ±2% frequency per IEC 60034).
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Settings className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Fuel systems:</strong> Generator fuel storage must comply with the Dangerous
                Substances and Explosive Atmospheres Regulations 2002 (DSEAR) and Environment Agency
                requirements for oil storage above 200 litres. Bunded tanks with a minimum 24-hour
                fuel supply (72 hours for critical facilities) are standard.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'cooling-integration',
    heading: 'Electrical Integration with Cooling Systems',
    content: (
      <>
        <p>
          Cooling systems typically account for 30 to 50 per cent of total data centre power
          consumption. The electrical installation must seamlessly integrate with mechanical cooling
          plant to achieve the required PUE target and maintain availability.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>CRAC/CRAH units:</strong> Computer Room Air Conditioning (CRAC) and Computer
                Room Air Handler (CRAH) units are typically three-phase 32A or 63A circuits.
                Variable speed drives (VSDs) on fans and compressors significantly reduce power
                consumption at part-load. Each unit should be on an independent circuit with local
                isolation.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Chiller plant:</strong> Larger data centres use chilled water systems with
                electric chillers. Chillers are typically the largest single electrical loads, often
                400 kW to several MW per unit. Chiller electrical connections must account for high
                starting currents and the specific requirements of the chiller manufacturer.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Activity className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Power factor correction:</strong> Cooling plant motor loads reduce the
                installation power factor. Automatic power factor correction (APFC) panels are
                typically installed to maintain a power factor of 0.95 or above, avoiding utility
                reactive power charges and maximising the effective capacity of the electrical
                supply.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'critical-power-calculations',
    heading: 'Critical Power Calculations',
    content: (
      <>
        <p>
          Accurate power calculations are the foundation of a successful data centre electrical
          design. Undersizing results in overloaded circuits and safety hazards; oversizing wastes
          capital and reduces efficiency.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>IT load calculation:</strong> Total IT load is calculated from the sum of
                rack power densities. Nameplate power ratings typically overstate actual consumption
                by 40 to 60 per cent. Measured data from the client's equipment data sheets or power
                metering is preferred over nameplate values.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Mechanical and lighting load:</strong> Add cooling plant, UPS losses,
                lighting, and building management systems to the IT load to determine the total
                facility load. UPS losses at full load are typically 3 to 5 per cent of IT load for
                modern double-conversion units.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Diversity factor:</strong> Apply a diversity factor appropriate to the
                facility type. Colocation facilities with diverse tenants typically use a diversity
                factor of 0.7 to 0.8 on rack nameplate values. Single-tenant facilities with known
                workloads can use more precise measured values.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Cable sizing to BS 7671:</strong> All data centre cables must be sized in
                accordance with BS 7671 Appendix 4, accounting for grouping, ambient temperature,
                and thermal insulation derating factors. Voltage drop must be calculated and kept
                within the limits of{' '}
                <SEOInternalLink href="/guides/bs-7671-18th-edition-guide">
                  BS 7671 Appendix 12
                </SEOInternalLink>
                , typically 1.5 per cent for final circuits in sensitive equipment applications.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'for-electricians',
    heading: 'For Electricians: Working in Data Centres',
    content: (
      <>
        <p>
          Data centre electrical work is a high-value specialism for UK electricians and electrical
          contractors. The combination of 24/7 operational constraints, high redundancy
          requirements, and complex systems means that experienced data centre electricians command
          premium rates.
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <div className="flex items-start gap-4">
              <AlertTriangle className="w-6 h-6 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Permit to Work Requirements</h4>
                <p className="text-white text-sm leading-relaxed">
                  All live working and isolation activities in data centres are controlled under
                  formal Permit to Work (PTW) systems. Electricians must be familiar with PTW
                  procedures, isolation verification using approved test equipment, and the
                  requirements of the Electricity at Work Regulations 1989.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-green-500/10 border border-green-500/20 p-5">
            <div className="flex items-start gap-4">
              <FileCheck2 className="w-6 h-6 text-green-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Certification and Compliance Records</h4>
                <p className="text-white text-sm leading-relaxed">
                  Every circuit installed or modified in a data centre must be certified. Use the{' '}
                  <SEOInternalLink href="/tools/eicr-certificate">
                    Elec-Mate certification app
                  </SEOInternalLink>{' '}
                  to complete Electrical Installation Certificates and Minor Works Certificates on
                  site, with instant PDF export for the client's compliance records.
                </p>
              </div>
            </div>
          </div>
        </div>
        <SEOAppBridge
          title="Manage data centre electrical projects with Elec-Mate"
          description="Join 1,000+ UK electricians using Elec-Mate for on-site certification, quoting, and project management. Complete EICs and EICRs on your phone with instant PDF export. 7-day free trial."
          icon={FileCheck2}
        />
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function DataCentreElectricalPage() {
  return (
    <GuideTemplate
      title="Data Centre Electrical Installation UK | Critical Power Systems"
      description="Complete guide to data centre electrical installation in the UK. UPS systems, dual power feeds, PDUs, N+1 redundancy, Tier classifications, TN-S earthing to BS 7671, busbar systems, generator backup, and critical power calculations."
      datePublished="2026-03-27"
      dateModified="2026-03-27"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Industrial Guide"
      badgeIcon={Server}
      heroTitle={
        <>
          Data Centre Electrical Installation UK:{' '}
          <span className="text-yellow-400">Critical Power Systems Guide</span>
        </>
      }
      heroSubtitle="The complete technical guide to data centre electrical installation in the UK — covering UPS systems, N+1 and 2N redundancy, Tier classifications, TN-S earthing to BS 7671, dual power feeds, PDUs, busbar systems, generator backup, and critical power calculations."
      readingTime={16}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions — Data Centre Electrical Installation"
      relatedPages={relatedPages}
      ctaHeading="Manage Your Data Centre Electrical Projects with Elec-Mate"
      ctaSubheading="Join 1,000+ UK electricians using Elec-Mate for on-site certification, quoting, and project management. 7-day free trial, cancel anytime."
    />
  );
}
