import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  PoundSterling,
  Camera,
  Brain,
  Mic,
  Receipt,
  Send,
  FileCheck2,
  Home,
  Building2,
  Clock,
  TrendingUp,
  ShieldCheck,
  Calculator,
  ClipboardCheck,
  GraduationCap,
  Search,
  Zap,
  FileText,
  BarChart3,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Certificates', href: '/guides/electrical-certificate-types-uk' },
  { label: 'EICR Cost UK', href: '/guides/eicr-cost-uk' },
];

const tocItems = [
  { id: 'eicr-pricing-overview', label: 'EICR Pricing Overview' },
  { id: 'prices-by-property', label: 'Prices by Property Type' },
  { id: 'factors-affecting-cost', label: 'Factors Affecting Cost' },
  { id: 'how-to-price-competitively', label: 'How to Price Competitively' },
  { id: 'charging-for-remedials', label: 'Charging for Remedial Work' },
  { id: 'maximising-eicr-profit', label: 'Maximising EICR Profitability' },
  { id: 'quoting-tools', label: 'Quoting and Invoice Tools' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'A typical domestic EICR costs £120 to £280 depending on property size, with HMOs and commercial premises costing more.',
  'The main factors affecting EICR cost are property size, number of circuits, age of the wiring, number of distribution boards, and access difficulty.',
  'Most electricians undercharge for EICRs because they fail to account for the time spent on paperwork after leaving site.',
  'The real profit in EICR work comes from remedial work generated by Unsatisfactory reports — pricing the inspection and remedials together maximises revenue per job.',
  'Elec-Mate eliminates post-site admin by completing the EICR, generating remedial quotes, and sending everything to the client from site — turning one visit into a fully invoiced job.',
];

const faqs = [
  {
    question: 'How much should I charge for a domestic EICR in 2026?',
    answer:
      'In 2026, the average EICR price for a typical UK domestic property ranges from £120 to £280, depending on the property size and complexity. A 1-bedroom flat with a single consumer unit and 6 circuits might be £120 to £180. A standard 3-bedroom house with 8 to 12 circuits is typically £180 to £280. A larger property with multiple distribution boards, outbuildings, or specialist circuits (such as a hot tub, EV charger, or solar PV system) could be £300 or more. These prices are for the inspection and report only — remedial work is priced separately. Your rate should reflect the time on site (typically 2 to 4 hours for a standard domestic property), the time to produce the report, your qualifications and scheme membership, your overheads (insurance, van, tools, calibration, subscription costs), and a reasonable profit margin. Do not undercut yourself — an EICR is a skilled professional service that carries significant liability.',
  },
  {
    question: 'Should I charge for a failed EICR and then charge again for the retest?',
    answer:
      'Yes, and you should be upfront about this from the start. The EICR inspection is a service — you are being paid for your time, expertise, and the report itself. If the installation is Unsatisfactory, the remedial work is a separate job. After the remedials are completed, a verification of the remedial work is needed, which may involve re-testing the affected circuits and issuing an EIC or Minor Works Certificate for the remedial work. Some electricians include a "re-inspection" fee in their remedial quote (covering the time to verify the work and update the EICR outcome). Others charge for the re-inspection separately. Either approach is acceptable, but make it clear to the client before starting the work. Many letting agents and landlords now expect the EICR inspection and any necessary remedials to be quoted as a package, with a fixed price for the inspection and an estimate for likely remedials based on the property age and condition.',
  },
  {
    question: 'Why do EICR prices vary so much between electricians?',
    answer:
      'EICR prices vary because the scope of work varies. A thorough EICR by a competent person scheme registered electrician includes: a comprehensive visual inspection of the entire installation, dead testing of every circuit (continuity of protective conductors, insulation resistance, polarity), live testing of every circuit (earth fault loop impedance, prospective fault current), RCD testing (half-rated, 1x, and 5x on both half-cycles), documentation of all results, observation coding, and production of the final report. This takes 2 to 4 hours for a typical house. An electrician who quotes £60 to £80 is almost certainly cutting corners — not testing every circuit, not completing the full inspection checklist, or not spending enough time on site. The cheapest quote is rarely the best value. A properly conducted EICR protects the landlord, the tenant, and the electrician. A poorly conducted one puts everyone at risk and may not satisfy the local authority if challenged.',
  },
  {
    question: 'How much does a commercial EICR cost?',
    answer:
      'Commercial EICR costs vary enormously depending on the size and complexity of the installation. A small retail unit or office with a single distribution board might cost £250 to £450. A medium-sized commercial premises with 2 to 3 distribution boards and 20 to 40 circuits could cost £500 to £1,200. Larger commercial and industrial installations — factories, warehouses, multi-floor office buildings — are typically priced on a per-board or per-circuit basis, and can run to several thousand pounds. Three-phase installations, high-voltage equipment, and specialist circuits (server rooms, industrial machinery, emergency lighting systems) all increase the price. Commercial EICRs are often quoted as a day rate (£300 to £500 per day for a single inspector), with the total cost depending on the number of days required. For very large installations, the EICR may be spread over multiple visits across several weeks.',
  },
  {
    question: 'Can I use Elec-Mate to generate quotes for EICR remedial work?',
    answer:
      'Yes. Elec-Mate includes a remedial works estimator that is integrated directly into the EICR workflow. When you add a C1, C2, or FI observation to the EICR, the remedial estimator can price the fix — materials, labour, and margin. It draws on current UK trade pricing data and labour timing data to produce an itemised estimate. You can adjust any line item, add or remove materials, and set your own labour rate and margin. The finished quote exports as a professional PDF that you can send to the landlord or client alongside the EICR. This means the client receives the inspection report and a quote for the remedial work in the same visit — no second trip, no desk time estimating at home. The quoting tool also integrates with Elec-Mate invoicing, so you can convert accepted quotes to invoices with a single tap and track payment status.',
  },
  {
    question: 'Should I include the EICR cost in a remedial package price?',
    answer:
      'This depends on your business model and the client relationship. Some electricians quote the EICR separately and then quote remedials as a distinct job if the result is Unsatisfactory. This is transparent and ensures you are paid for the inspection regardless of the outcome. Other electricians offer a package deal — particularly for landlords and letting agents who send regular work — where the EICR and basic remedials (up to a defined scope, such as consumer unit labelling, fitting a warning notice, tightening connections) are included in one price, with anything beyond that scope quoted separately. The package approach can win more work from landlords and agents because it gives them budget certainty. However, be careful not to undervalue your time — if you include remedials in the EICR price and then find significant C2 defects, you could end up working at a loss. The safest approach is to price the EICR at a fair rate and then quote remedials separately, using the observations from the EICR to produce an accurate and detailed quote.',
  },
  {
    question: 'How do I price an EICR for an HMO?',
    answer:
      'HMOs (Houses in Multiple Occupation) require a more thorough EICR than a standard domestic property. The typical price range is £250 to £450, but can be higher for large HMOs with multiple distribution boards, shared circuits, and individual room supplies. The key factors are: the number of distribution boards (an HMO may have a main board plus sub-boards for individual rooms), the number of circuits (often 15 to 30 or more), the complexity of the installation (shared circuits, individually metered supplies, emergency lighting), access to individual rooms (tenants may need to be notified in advance), and the age and condition of the wiring. Many HMOs have installations that have been modified over the years by different contractors, resulting in a patchwork of wiring styles, cable types, and protection devices. This complexity increases the inspection time and the likelihood of finding defects. When quoting for an HMO, ask about the number of rooms, the number of distribution boards, whether there is a landlord supply, and whether individual rooms have their own circuits or share a common supply.',
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/tools/eicr-certificate',
    title: 'EICR Certificate App',
    description:
      'Complete digital EICR certificates on your phone with AI board scanner and voice test entry.',
    icon: FileCheck2,
    category: 'Certificate',
  },
  {
    href: '/guides/eicr-for-landlords',
    title: 'EICR for Landlords',
    description: 'Legal requirements, penalties, and deadlines for landlord EICR inspections.',
    icon: ShieldCheck,
    category: 'Guide',
  },
  {
    href: '/tools/electrical-quoting-app',
    title: 'Electrical Quoting App',
    description:
      'AI-powered quoting with material pricing, labour estimation, and professional PDF output.',
    icon: Receipt,
    category: 'Tool',
  },
  {
    href: '/tools/electrician-invoice-app',
    title: 'Electrician Invoice App',
    description:
      'Generate and send invoices from site. Convert accepted quotes to invoices with a single tap.',
    icon: FileText,
    category: 'Tool',
  },
  {
    href: '/guides/job-profitability-calculator',
    title: 'Job Profitability Calculator',
    description: 'Track costs, revenue, and profit on every job to understand your true margins.',
    icon: BarChart3,
    category: 'Tool',
  },
  {
    href: '/guides/eicr-observation-codes-explained',
    title: 'Observation Codes Explained',
    description: 'In-depth guide to C1, C2, C3, and FI classification codes with real examples.',
    icon: Search,
    category: 'Guide',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'eicr-pricing-overview',
    heading: 'EICR Cost in 2026: What the Market Looks Like',
    content: (
      <>
        <p>
          The UK EICR market has grown significantly since the Electrical Safety Standards in the
          Private Rented Sector (England) Regulations 2020 made periodic inspections a legal
          requirement for all privately rented properties. With approximately 4.4 million private
          rented households in England alone, the demand for{' '}
          <SEOInternalLink href="/tools/eicr-certificate">EICR certificates</SEOInternalLink> is
          substantial and recurring (every 5 years per property).
        </p>
        <p>
          This demand has created both opportunity and pressure. Electricians who price their EICRs
          correctly can build a profitable, predictable revenue stream. Those who undercharge —
          either to win work or because they do not account for the full cost of their time — risk
          burning out on high-volume, low-margin work.
        </p>
        <p>
          The prices below are based on 2026 market rates across the UK. London and South East
          prices are typically 10 to 25% higher. Rural areas and Scotland tend to be at the lower
          end. These figures are for the inspection and report only — remedial work is additional.
        </p>
      </>
    ),
  },
  {
    id: 'prices-by-property',
    heading: 'EICR Prices by Property Type',
    content: (
      <>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6">
            <div className="flex items-center gap-3 mb-4">
              <Home className="w-6 h-6 text-yellow-400" />
              <h3 className="font-bold text-white text-lg">1-Bedroom Flat</h3>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              <div>
                <div className="text-sm text-white mb-1">Price Range</div>
                <div className="text-xl font-bold text-yellow-400">£120 — £180</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Typical Circuits</div>
                <div className="text-xl font-bold text-white">4 — 8</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Time on Site</div>
                <div className="text-xl font-bold text-white">1.5 — 2.5 hrs</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Boards</div>
                <div className="text-xl font-bold text-white">1</div>
              </div>
            </div>
            <p className="text-white text-sm leading-relaxed">
              A standard 1-bedroom flat with a single consumer unit is the quickest domestic EICR.
              The small number of circuits means testing is fast, and access is usually
              straightforward. At £120 to £180, this should take no more than 2.5 hours including
              report completion. Be careful with older conversion flats — they may have unusual
              wiring arrangements, shared circuits with other flats, or inadequate earthing that
              adds complexity.
            </p>
          </div>

          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6">
            <div className="flex items-center gap-3 mb-4">
              <Home className="w-6 h-6 text-yellow-400" />
              <h3 className="font-bold text-white text-lg">2 to 3-Bedroom House</h3>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              <div>
                <div className="text-sm text-white mb-1">Price Range</div>
                <div className="text-xl font-bold text-yellow-400">£180 — £280</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Typical Circuits</div>
                <div className="text-xl font-bold text-white">8 — 14</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Time on Site</div>
                <div className="text-xl font-bold text-white">2.5 — 4 hrs</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Boards</div>
                <div className="text-xl font-bold text-white">1 — 2</div>
              </div>
            </div>
            <p className="text-white text-sm leading-relaxed">
              The bread-and-butter of landlord EICRs. A typical 3-bedroom semi or terrace with a
              single consumer unit and 8 to 12 circuits takes 2.5 to 4 hours for a thorough
              inspection. Properties with extensions, loft conversions, or outbuilding supplies may
              have a second distribution board, adding time and justifying a price at the higher
              end. Properties built before 1970 with original wiring will almost always generate C2
              observations, creating remedial work opportunities.
            </p>
          </div>

          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6">
            <div className="flex items-center gap-3 mb-4">
              <Home className="w-6 h-6 text-yellow-400" />
              <h3 className="font-bold text-white text-lg">4 to 5-Bedroom House</h3>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              <div>
                <div className="text-sm text-white mb-1">Price Range</div>
                <div className="text-xl font-bold text-yellow-400">£280 — £400</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Typical Circuits</div>
                <div className="text-xl font-bold text-white">14 — 24</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Time on Site</div>
                <div className="text-xl font-bold text-white">4 — 6 hrs</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Boards</div>
                <div className="text-xl font-bold text-white">1 — 3</div>
              </div>
            </div>
            <p className="text-white text-sm leading-relaxed">
              Larger properties take proportionally longer due to more circuits, more rooms to
              access, and often multiple distribution boards. Properties of this size frequently
              have dedicated circuits for electric showers, cookers, EV chargers, hot tubs, or
              external buildings — each adding testing time. Older properties in this category may
              have had multiple extensions over the decades, each with different wiring standards
              and cable types.
            </p>
          </div>

          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-6">
            <div className="flex items-center gap-3 mb-4">
              <Building2 className="w-6 h-6 text-yellow-400" />
              <h3 className="font-bold text-white text-lg">HMO (House in Multiple Occupation)</h3>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              <div>
                <div className="text-sm text-white mb-1">Price Range</div>
                <div className="text-xl font-bold text-yellow-400">£250 — £450+</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Typical Circuits</div>
                <div className="text-xl font-bold text-white">15 — 40+</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Time on Site</div>
                <div className="text-xl font-bold text-white">4 — 8 hrs</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Boards</div>
                <div className="text-xl font-bold text-white">2 — 6+</div>
              </div>
            </div>
            <p className="text-white text-sm leading-relaxed">
              HMOs are the most complex and highest-value domestic EICRs. Multiple distribution
              boards, shared circuits, individual room supplies, emergency lighting, fire alarm
              systems, and years of modifications by different contractors all add time and
              complexity. Access to individual rooms requires coordination with tenants. The
              likelihood of finding C2 defects is high, meaning significant remedial work is
              commonly generated. Price accordingly — do not treat an HMO as "just a bigger house."
            </p>
          </div>

          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6">
            <div className="flex items-center gap-3 mb-4">
              <Building2 className="w-6 h-6 text-yellow-400" />
              <h3 className="font-bold text-white text-lg">Commercial Premises</h3>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              <div>
                <div className="text-sm text-white mb-1">Price Range</div>
                <div className="text-xl font-bold text-yellow-400">£250 — £2,000+</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Typical Circuits</div>
                <div className="text-xl font-bold text-white">10 — 100+</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Time on Site</div>
                <div className="text-xl font-bold text-white">Half day — multiple days</div>
              </div>
              <div>
                <div className="text-sm text-white mb-1">Boards</div>
                <div className="text-xl font-bold text-white">1 — 20+</div>
              </div>
            </div>
            <p className="text-white text-sm leading-relaxed">
              Commercial EICR pricing varies enormously. A small shop or office with a single board
              might be £250 to £450. A medium-sized commercial premises could be £500 to £1,200.
              Large multi-floor buildings, factories, and warehouses are typically priced on a day
              rate (£300 to £500 per day) with the total depending on the number of days needed.
              Three-phase installations, high-voltage equipment, and specialist systems all increase
              the price. Always conduct a pre-inspection site visit for larger commercial jobs to
              produce an accurate quote.
            </p>
          </div>
        </div>
      </>
    ),
  },
  {
    id: 'factors-affecting-cost',
    heading: 'Factors That Affect EICR Cost',
    content: (
      <>
        <p>
          The price you charge for an EICR should reflect the actual time and expertise required.
          Here are the factors that increase or decrease the cost:
        </p>
        <div className="space-y-4 my-4">
          {[
            {
              title: 'Number of circuits',
              description:
                'Each circuit requires individual testing — continuity, insulation resistance, polarity, Zs, and RCD times. More circuits means more time. A 6-circuit flat takes less than half the time of a 20-circuit house.',
            },
            {
              title: 'Number of distribution boards',
              description:
                'Each board needs individual Ze measurement, supply characteristics recording, and its own schedule of test results. Properties with extensions, outbuildings, or sub-mains feeding secondary boards take significantly longer.',
            },
            {
              title: 'Age and condition of the wiring',
              description:
                'Older installations (pre-1970 rubber or lead-sheathed cable, old colour codes, rewirable fuses) take longer to inspect and are far more likely to generate observations. Newer installations with modern cables and RCBOs are faster and cleaner.',
            },
            {
              title: 'Access difficulty',
              description:
                'A consumer unit in a locked cupboard behind furniture, circuits running through loft spaces with no boarding, or rooms that cannot be accessed due to tenant belongings all add time. Poor access may also result in FI codes, which require follow-up visits.',
            },
            {
              title: 'Specialist circuits',
              description:
                'EV chargers, solar PV, battery storage, hot tubs, swimming pools, emergency lighting, fire alarm systems — each requires specific testing procedures and knowledge. These circuits justify a higher price.',
            },
            {
              title: 'Location',
              description:
                'London and South East prices are typically 10 to 25% higher than the national average. This reflects higher running costs (parking, congestion charge, insurance, rent) and higher local demand.',
            },
          ].map((factor) => (
            <div
              key={factor.title}
              className="rounded-2xl bg-white/[0.04] border border-white/10 p-5"
            >
              <div className="flex items-start gap-3">
                <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
                <div>
                  <h4 className="font-bold text-white mb-1">{factor.title}</h4>
                  <p className="text-white text-sm leading-relaxed">{factor.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
        <SEOAppBridge
          title="AI Board Scanner saves 30 minutes per EICR"
          description="Point your phone camera at the distribution board. Elec-Mate reads MCB/RCBO ratings, circuit details, and board layout from the photo — so you start the EICR with half the data already filled in. More time saved means more profit per job."
          icon={Camera}
        />
      </>
    ),
  },
  {
    id: 'how-to-price-competitively',
    heading: 'How to Price Your EICRs Competitively',
    content: (
      <>
        <p>
          Pricing EICRs is a balance between winning the work and making a profit. Here is a
          framework for setting your rates:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <h4 className="font-bold text-white text-lg mb-4">Step 1: Calculate Your Hourly Cost</h4>
          <p className="text-white text-sm leading-relaxed mb-3">
            Before you can price an EICR, you need to know what it costs you per hour to operate.
            Add up your annual costs:
          </p>
          <ul className="space-y-2 text-white text-sm">
            {[
              'Van costs (lease, fuel, insurance, maintenance, MOT)',
              'Tool and test instrument costs (calibration, replacement, insurance)',
              'Insurance (public liability, professional indemnity, employers liability)',
              'Scheme membership (NICEIC, NAPIT, ELECSA)',
              'Software subscriptions (Elec-Mate, accounting software)',
              'Training and CPD (18th Edition updates, amendment courses)',
              'Tax, National Insurance, pension contributions',
              'Admin time (quoting, invoicing, chasing payments, bookkeeping)',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <Zap className="w-4 h-4 text-yellow-400 mt-0.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-white text-sm leading-relaxed mt-3">
            Divide the total by the number of billable hours you work per year (typically 1,400 to
            1,600 for a sole trader). This gives your break-even hourly rate. Add your desired
            profit margin (typically 20 to 40%) to get your target hourly rate. Most experienced
            electricians in 2026 should be working to a target hourly rate of £45 to £65 outside
            London, or £55 to £80 in London and the South East.
          </p>
        </div>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <h4 className="font-bold text-white text-lg mb-4">Step 2: Estimate the Time Per Job</h4>
          <p className="text-white text-sm leading-relaxed">
            A domestic EICR involves three blocks of time: travel (typically 30 to 60 minutes each
            way), on-site inspection and testing (1.5 to 6 hours depending on property size), and
            report completion (30 to 90 minutes if done manually at home, or zero additional time if
            you complete the report on site using Elec-Mate). Multiply the total time by your hourly
            rate to get the minimum price. For example: 3 hours on site + 1 hour travel + 0.5 hours
            report = 4.5 hours at £55/hour = £247.50. Round up to £250.
          </p>
        </div>
        <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-6 my-4">
          <h4 className="font-bold text-white text-lg mb-4">Step 3: Eliminate Post-Site Admin</h4>
          <p className="text-white text-sm leading-relaxed">
            The single biggest way to increase your EICR profitability is to eliminate the time
            spent at home typing up reports. If you save 45 minutes per EICR by completing the
            report on site with Elec-Mate, and you do 3 EICRs per week, that is 2.25 hours per week
            — over 100 hours per year. At £55/hour, that is £5,500 of time recovered annually. You
            can either do more jobs (increasing revenue) or finish earlier (improving your quality
            of life).
          </p>
        </div>
        <p>
          Do not compete on price alone. Compete on professionalism, speed of delivery, and the
          quality of your reports. A landlord who receives a thorough, well-written EICR with a
          clear remedial quote within hours of the inspection is far more likely to give you repeat
          work than one who has to chase for the report days later.
        </p>
      </>
    ),
  },
  {
    id: 'charging-for-remedials',
    heading: 'Charging for Remedial Work After an Unsatisfactory EICR',
    content: (
      <>
        <p>
          The real profit in EICR work comes not from the inspection itself, but from the remedial
          work generated by Unsatisfactory results. A significant proportion of EICRs on older
          properties return at least one C2 observation, and each C2 or C1 observation requires
          remedial work that the{' '}
          <SEOInternalLink href="/guides/eicr-for-landlords">
            landlord must complete within 28 days
          </SEOInternalLink>
          .
        </p>
        <p>Common remedial jobs and typical price ranges:</p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 overflow-hidden my-4">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-white/10">
                  <th className="p-4 text-sm font-semibold text-white">Remedial Work</th>
                  <th className="p-4 text-sm font-semibold text-yellow-400 text-right">
                    Typical Price
                  </th>
                </tr>
              </thead>
              <tbody>
                {[
                  { work: 'Fit warning notice for mixed wiring colours', price: '£25 — £40' },
                  { work: 'Replace missing consumer unit cover', price: '£30 — £60' },
                  {
                    work: 'Fit RCD protection to individual circuit (RCBO)',
                    price: '£80 — £150 per circuit',
                  },
                  { work: 'Install main protective bonding (gas, water)', price: '£100 — £200' },
                  {
                    work: 'Replace faulty socket outlet or switch',
                    price: '£40 — £80 per accessory',
                  },
                  { work: 'Consumer unit upgrade (full RCBO board)', price: '£600 — £1,200' },
                  { work: 'Fit earth connection to unearthed metalwork', price: '£50 — £120' },
                  {
                    work: 'Replace section of damaged cable',
                    price: '£80 — £300 depending on access',
                  },
                  { work: 'Partial rewire (single circuit)', price: '£200 — £600' },
                  { work: 'Full rewire (3-bed house)', price: '£3,500 — £6,000' },
                ].map((row, i) => (
                  <tr key={row.work} className={i < 9 ? 'border-b border-white/5' : ''}>
                    <td className="p-4 text-sm text-white">{row.work}</td>
                    <td className="p-4 text-sm text-yellow-400 font-semibold text-right">
                      {row.price}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        <p>
          The key is to present the remedial quote at the same time as the EICR report. If the
          landlord receives the Unsatisfactory EICR and a clear, itemised quote in the same email or
          WhatsApp message, they are far more likely to instruct you to do the work immediately. If
          you send the EICR and then follow up with a quote days later, the landlord may shop around
          or delay — costing you the remedial job.
        </p>
        <SEOAppBridge
          title="Observations to priced remedial quote in seconds"
          description="Every C1, C2, and FI observation you add to the EICR feeds directly into the remedial works estimator. It prices materials, labour, and margin for each fix. Hand the landlord the EICR and the quote in the same visit."
          icon={Receipt}
        />
      </>
    ),
  },
  {
    id: 'maximising-eicr-profit',
    heading: 'Maximising EICR Profitability',
    content: (
      <>
        <p>
          The most profitable electricians are not necessarily the ones doing the most EICRs — they
          are the ones extracting the most value from each inspection. Here is how:
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-5">
            <div className="flex items-start gap-3">
              <TrendingUp className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Complete everything on site</h4>
                <p className="text-white text-sm leading-relaxed">
                  The EICR report, remedial quote, certificate delivery, and invoice should all
                  happen before you leave the property. Every hour spent at home typing up reports
                  is an hour you could be on another job. Elec-Mate enables this with the AI board
                  scanner, voice test entry, defect code AI, remedial estimator, and instant PDF
                  delivery.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-5">
            <div className="flex items-start gap-3">
              <TrendingUp className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Win the remedial work</h4>
                <p className="text-white text-sm leading-relaxed">
                  An Unsatisfactory EICR is a sales opportunity. The landlord needs the remedial
                  work done within 28 days. If you provide the quote immediately — with clear
                  pricing, a professional presentation, and the convenience of having the same
                  electrician do the work — you will win the job the vast majority of the time.
                  Elec-Mate's remedial estimator prices the work on the spot.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-5">
            <div className="flex items-start gap-3">
              <TrendingUp className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">
                  Build landlord and agent relationships
                </h4>
                <p className="text-white text-sm leading-relaxed">
                  A landlord with multiple properties needs an EICR every 5 years on each one. A
                  letting agent may manage dozens or hundreds of properties. Deliver excellent
                  service on the first EICR — fast, thorough, professional, with instant report
                  delivery — and you build a pipeline of repeat work that fills your diary for
                  years.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-5">
            <div className="flex items-start gap-3">
              <TrendingUp className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Track profitability per job</h4>
                <p className="text-white text-sm leading-relaxed">
                  Know your true profit on every EICR. Track the time on site, the travel time, the
                  materials used for any minor remedials, and the revenue. Elec-Mate's job
                  profitability tracking shows you exactly what you made on each job, so you can
                  identify which property types and client types are most profitable.
                </p>
              </div>
            </div>
          </div>
        </div>
      </>
    ),
  },
  {
    id: 'quoting-tools',
    heading: 'Elec-Mate Quoting, Invoice, and EICR Tools',
    content: (
      <>
        <p>
          Elec-Mate is designed to turn the EICR workflow into a single-visit, fully-invoiced job.
          Here is how all the pieces fit together:
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <div className="flex items-start gap-4">
              <Camera className="w-6 h-6 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">AI Board Scanner</h4>
                <p className="text-white text-sm leading-relaxed">
                  Point your phone at the consumer unit. The AI reads MCB/RCBO ratings, circuit
                  details, and board layout from the photo. The EICR starts pre-filled with board
                  data.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-purple-500/10 border border-purple-500/20 p-5">
            <div className="flex items-start gap-4">
              <Mic className="w-6 h-6 text-purple-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Voice Test Entry</h4>
                <p className="text-white text-sm leading-relaxed">
                  Speak test results while your hands hold the probes. "Ring circuit 1, R1+R2 0.32,
                  Zs 0.89, insulation resistance 200 megohms, RCD 18 milliseconds." No putting the
                  probes down to type.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5">
            <div className="flex items-start gap-4">
              <Brain className="w-6 h-6 text-blue-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Defect Code AI</h4>
                <p className="text-white text-sm leading-relaxed">
                  Describe a defect in plain English. The AI returns the correct{' '}
                  <SEOInternalLink href="/guides/eicr-observation-codes-explained">
                    observation code
                  </SEOInternalLink>{' '}
                  with the matching BS 7671 regulation number. No more flicking through GN3.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-green-500/10 border border-green-500/20 p-5">
            <div className="flex items-start gap-4">
              <Receipt className="w-6 h-6 text-green-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Remedial Works Estimator</h4>
                <p className="text-white text-sm leading-relaxed">
                  Every C1, C2, and FI observation feeds into the estimator. It prices materials,
                  labour, and margin for each fix. The quote exports as a professional PDF — hand it
                  to the landlord alongside the EICR.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <div className="flex items-start gap-4">
              <Send className="w-6 h-6 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Send and Invoice from Site</h4>
                <p className="text-white text-sm leading-relaxed">
                  Send the EICR, remedial quote, and invoice by email or WhatsApp — all from the
                  app, all before you leave the property. No double-handling. No chasing. No desk
                  time.
                </p>
              </div>
            </div>
          </div>
        </div>
        <p>
          The result: every EICR becomes a fully-invoiced job completed in a single visit. No going
          home to type up the report. No separate email for the quote. No chasing for payment. That
          is how Elec-Mate turns EICR pricing from a question of "how much should I charge?" into
          "how much can I earn per day?"
        </p>
        <SEOAppBridge
          title="Start earning more from every EICR"
          description="Join 430+ UK electricians completing EICR certificates, generating remedial quotes, and sending invoices — all from their phones, all on site. 7-day free trial, cancel anytime."
          icon={PoundSterling}
        />
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function EICRCostUKPage() {
  return (
    <GuideTemplate
      title="EICR Cost UK 2026 | What Should You Charge?"
      description="EICR cost guide for UK electricians in 2026. Average prices by property type (1-bed flat to commercial), factors affecting cost, how to price competitively, and how Elec-Mate's quoting tools turn every EICR into a fully-invoiced job."
      datePublished="2025-02-01"
      dateModified="2026-02-13"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Pricing Guide"
      badgeIcon={PoundSterling}
      heroTitle={
        <>
          EICR Cost UK 2026: <span className="text-yellow-400">What Should You Charge?</span>
        </>
      }
      heroSubtitle="Most electricians undercharge for EICRs because they do not account for the time spent typing up reports at home. This guide covers average EICR prices by property type, factors that affect cost, how to price competitively, and how Elec-Mate eliminates post-site admin so every EICR is a fully-invoiced, single-visit job."
      readingTime={11}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions About EICR Pricing"
      relatedPages={relatedPages}
      ctaHeading="Turn every EICR into a fully-invoiced job"
      ctaSubheading="Join 430+ UK electricians using Elec-Mate to complete EICR certificates, generate remedial quotes, and send invoices — all from site. 7-day free trial, cancel anytime."
    />
  );
}
