import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SymbolGallery } from '@/components/seo/SymbolGallery';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import { ShieldCheck, BookOpen, FileCheck2, PenTool } from 'lucide-react';

const breadcrumbs = [
  { label: 'Guides', href: '/guides/electrical-symbols-chart' },
  { label: 'Switch Symbols', href: '/guides/electrical-switch-symbols' },
];

const tocItems = [
  { id: 'gallery', label: 'Symbol Gallery' },
  { id: 'about', label: 'About Switch Symbols' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'BS EN 60617 defines the graphical symbols for all UK electrical switching devices used on circuit diagrams, distribution board schedules and installation drawings.',
  'A one-way switch has a single break in the live conductor; a two-way switch has two fixed contacts (used in pairs); an intermediate switch has four terminals and is wired between two two-way switches.',
  'A pull-cord switch is required in bathroom zones 1 and 2 per BS 7671 Section 701 — wall switches inside the room are not permitted.',
  'Every bathroom extractor fan needs a 3-pole fan isolator outside the bathroom for safe maintenance.',
  'Elec-Mate auto-uses correct BS EN 60617 switch symbols on every circuit drawing and certificate generated by the platform.',
];

const faqs = [
  {
    question: 'What is the symbol for a two-way switch?',
    answer:
      'A two-way switch is drawn as a single line (the switch contact) with two alternative fixed contact points — one for the L1 strapper, one for the L2 strapper, plus a common terminal. The visual difference from a one-way switch is the addition of the second fixed contact, giving the symbol a fork shape. Two-way switches are always used in pairs to control a light from two locations.',
  },
  {
    question: 'How do I tell an intermediate switch from a two-way switch?',
    answer:
      'The intermediate switch symbol has four terminals (two pairs of strappers) and shows the contacts crossing over inside the switch. A two-way switch has three terminals (common + two strappers). The intermediate switch is wired between two two-way switches to give control from three or more locations — a staircase with three landings, a long corridor, or a hall with multiple entry points.',
  },
  {
    question: 'Is a fan isolator a switch or an isolator?',
    answer:
      'Both. A fan isolator is a 3-pole switch-disconnector — it switches all three conductors (live, neutral and switched-live to the fan) simultaneously, providing functional switching during normal use AND isolation for maintenance. BS 7671 537.3.2 requires every bathroom extractor fan to have a means of isolating all live conductors before any maintenance work.',
  },
  {
    question: 'When is a key switch used over a normal switch?',
    answer:
      'A key switch is used wherever unauthorised operation of a circuit must be prevented. Common applications include school assembly hall lighting (prevents pupils tampering), retail shutter motors, security override switches, alarm bypass keys, and emergency stop reset functions. The key acts as an administrative control rather than a technical safety measure.',
  },
  {
    question: 'Are emergency stop buttons the same as isolators?',
    answer:
      'No. An emergency stop (E-stop) is a momentary-action latching button designed for rapid disconnection in a hazardous situation. It must be operable without specialised knowledge, be coloured red on yellow, and require deliberate reset (twist-release or key). An isolator is for planned maintenance — lockable in OFF, but not designed for emergency-rapid use. A single circuit may need both: an isolator for routine work + an emergency stop for hazards.',
  },
];

const relatedPages = [
  {
    href: '/guides/electrical-symbols-chart',
    title: 'Electrical Symbols Chart (Full Library)',
    description: 'All 114 BS EN 60617 symbols grouped by category — the master reference.',
    icon: 'PenTool',
    category: 'Reference',
  },
  {
    href: '/guides/how-to-read-wiring-diagram',
    title: 'How to Read a Wiring Diagram',
    description: 'Apply BS EN 60617 symbols to interpret installation drawings.',
    icon: 'BookOpen',
    category: 'Guide',
  },
  {
    href: '/guides/how-to-read-electrical-drawings',
    title: 'How to Read Electrical Drawings',
    description:
      'Layout drawings, schematics, single-line diagrams — every drawing type explained.',
    icon: 'FileCheck2',
    category: 'Guide',
  },
  {
    href: '/ai-diagram-builder',
    title: 'AI Diagram Builder',
    description: 'Drag-and-drop BS EN 60617 symbols into a working circuit drawing.',
    icon: 'ShieldCheck',
    category: 'Tool',
  },
];

const sections = [
  {
    id: 'gallery',
    heading: 'Switch Symbols — Complete Symbol Set',
    content: (
      <>
        <p>
          Below are every switch symbols on the Elec-Mate symbol library, drawn to BS EN 60617.
          Right-click any symbol to save the SVG, or use the{' '}
          <SEOInternalLink href="/ai-diagram-builder">AI Diagram Builder</SEOInternalLink> to drag
          them directly into a circuit drawing.
        </p>
        <SymbolGallery category="switch" showCategoryHeadings={false} />
      </>
    ),
  },
  {
    id: 'about',
    heading: 'About Switch Symbols',
    content: (
      <>
        <p>
          Every switch symbol used on UK electrical drawings — one-way through emergency stop —
          drawn to BS EN 60617 with installation context, BS 7671 references and use cases.
        </p>
        <p>
          Each symbol is drawn to <strong>BS EN 60617</strong> — the UK adoption of the
          international IEC 60617 standard for graphical symbols on electrical diagrams. The same
          symbols appear on{' '}
          <SEOInternalLink href="/guides/how-to-fill-in-eicr">EICR forms</SEOInternalLink>,
          distribution board schedules, single-line schematics and installation layout drawings.
        </p>
        <p>
          Looking for symbols in a different category? See the full{' '}
          <SEOInternalLink href="/guides/electrical-symbols-chart">
            BS EN 60617 symbol library
          </SEOInternalLink>{' '}
          covering switches, sockets, lighting, distribution, safety, containment, equipment,
          mechanical, renewables, controls and architectural symbols.
        </p>
        <SEOAppBridge
          title="Use these symbols in real drawings"
          description="The Elec-Mate AI Diagram Builder gives you every BS EN 60617 symbol on a draggable canvas — perfect for circuit diagrams, certificate schedules…"
          ctaText="Open the Diagram Builder"
          ctaHref="/ai-diagram-builder"
        />
      </>
    ),
  },
];

export default function ElectricalSwitchSymbolsPage() {
  return (
    <GuideTemplate
      title="Electrical Switch Symbols | BS EN 60617 Reference UK"
      description="One-way, two-way, intermediate, dimmer, key, PIR, pull-cord, timer, isolator, fan-isolator + emergency stop switch symbols to BS EN 60617 for UK…"
      datePublished="2026-05-18"
      dateModified="2026-05-18"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Symbol Reference"
      badgeIcon={PenTool}
      heroTitle={
        <>
          Switch Symbols:{' '}
          <span className="text-yellow-400">BS EN 60617 reference for UK electricians</span>
        </>
      }
      heroSubtitle="Every switch symbol used on UK electrical drawings — one-way through emergency stop — drawn to BS EN 60617 with installation context, BS 7671 references and use cases."
      readingTime={6}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="FAQ — Switch Symbols"
      relatedPages={relatedPages}
      ctaHeading="Use BS EN 60617 symbols in working drawings"
      ctaSubheading="Drag-and-drop circuit diagrams. EICR + EIC schedules with correct symbols. Built for UK electricians. 7-day free trial."
    />
  );
}
