import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  PenTool,
  ShieldCheck,
  Home,
  FileCheck2,
  ClipboardCheck,
  Search,
  GraduationCap,
  Cable,
  Zap,
  Lightbulb,
  ToggleRight,
  BookOpen,
  CircuitBoard,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Guides', href: '/guides/electrical-certificate-types-uk' },
  { label: 'Electrical Symbols', href: '/guides/electrical-symbols-chart' },
];

const tocItems = [
  { id: 'what-are-symbols', label: 'What Are Electrical Symbols?' },
  { id: 'switch-symbols', label: 'Switch Symbols' },
  { id: 'socket-symbols', label: 'Socket Outlet Symbols' },
  { id: 'light-symbols', label: 'Lighting Symbols' },
  { id: 'protection-symbols', label: 'Protection Device Symbols' },
  { id: 'circuit-symbols', label: 'Circuit and Wiring Symbols' },
  { id: 'distribution-symbols', label: 'Distribution Board Symbols' },
  { id: 'reading-diagrams', label: 'How to Read Circuit Diagrams' },
  { id: 'for-electricians', label: 'For Electricians: Using Symbols on Site' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'Electrical symbols in the UK follow BS EN 60617 (graphical symbols for diagrams) and are used on circuit diagrams, installation drawings, and electrical certificates.',
  'Switch symbols use a single line at an angle to indicate the switching action. Variations show one-way, two-way, intermediate, dimmer, and pull-cord switches.',
  'Socket symbols use a semicircle shape. A single socket is one semicircle; a double socket is two semicircles. A line through the symbol indicates a switched socket.',
  'Protection device symbols differentiate between fuses, MCBs, RCDs, RCBOs, and AFDDs. Each has a distinct symbol that shows its operating principle.',
  'Elec-Mate includes a built-in BS EN 60617 symbol library and uses correct symbols on all circuit diagrams, distribution board schedules, and certificates generated by the app.',
];

const faqs = [
  {
    question: 'What standard covers electrical symbols in the UK?',
    answer:
      'Electrical symbols in the UK are defined by BS EN 60617 (Graphical symbols for diagrams). This is the European harmonised version of the international standard IEC 60617. It covers symbols for all types of electrical diagrams, including circuit diagrams, wiring diagrams, block diagrams, and installation drawings. BS 7671 (the IET Wiring Regulations) references BS EN 60617 for the symbols used on electrical installation certificates, distribution board schedules, and circuit charts. Some older UK installations may use symbols from the superseded BS 3939, but BS EN 60617 is the current standard and should be used for all new work.',
  },
  {
    question: 'What is the difference between a circuit diagram and a wiring diagram?',
    answer:
      'A circuit diagram (sometimes called a schematic diagram) shows the electrical connections between components using standard symbols. It focuses on the function of the circuit — how the components are connected electrically — without showing the physical layout or cable routing. A wiring diagram shows the physical layout of the installation, including the position of accessories, the routes of cables, and the connections at each point. In domestic electrical work, you are more likely to encounter wiring diagrams (such as a lighting layout for a house) than circuit diagrams. Both use BS EN 60617 symbols, but wiring diagrams also include dimensional information and cable identification.',
  },
  {
    question: 'How do I identify a two-way switch symbol on a diagram?',
    answer:
      'A one-way switch symbol is a single line (the switch contact) at an angle, with one fixed contact point and one moving contact point. A two-way switch symbol adds a second fixed contact point, showing that the switch can connect to either of two positions. This is represented by a single moving contact with two alternative fixed contacts — like a fork shape. The two-way switch is used for controlling a light from two locations (such as the top and bottom of a staircase). An intermediate switch symbol adds a third position and is used when three or more switches control the same light.',
  },
  {
    question: 'What does the RCD symbol look like?',
    answer:
      'The RCD (Residual Current Device) symbol in BS EN 60617 shows the basic switch/breaker symbol with an additional element representing the residual current detection coil. It is typically drawn as a rectangular box with a sinusoidal wave inside (representing the current-sensing element) and the breaker contacts. An RCBO (Residual Current Breaker with Overcurrent protection) combines the RCD symbol with the MCB symbol — showing both the overcurrent trip element and the residual current detection element in a single device. On distribution board schedules, RCDs, MCBs, and RCBOs should be identified by both their symbol and their type designation (e.g., Type A, Type AC, Type B).',
  },
  {
    question: 'Where are electrical symbols used on certificates?',
    answer:
      'Electrical symbols appear on several sections of electrical installation certificates. On the EIC (Electrical Installation Certificate), they are used on the circuit chart (if provided) showing the arrangement of circuits and protective devices. On the distribution board schedule, symbols identify the type of protective device on each way — MCB, RCBO, RCD, fuse, etc. On the EICR (Electrical Installation Condition Report), the schedule of inspections references the type of devices installed, and the schedule of test results identifies the circuit type. Elec-Mate uses correct BS EN 60617 symbols on all generated certificates and circuit diagrams, ensuring professional presentation and compliance with the standard.',
  },
  {
    question: 'Are electrical symbols the same across Europe?',
    answer:
      'Yes, broadly. BS EN 60617 is the UK adoption of the European standard EN 60617, which is itself based on the international standard IEC 60617. The symbols are harmonised across all EU and EEA countries. This means an electrician trained in the UK should be able to read a circuit diagram from Germany, France, or any other European country using the same standard. There are some minor national variations in how symbols are drawn on installation drawings (for example, the representation of socket outlets varies slightly between countries), but the core set of symbols for protective devices, switches, and circuit elements is consistent.',
  },
  {
    question: 'Do apprentices need to learn electrical symbols?',
    answer:
      "Yes. Electrical symbols are a core part of the Level 2 and Level 3 electrical installation qualifications. Apprentices are expected to be able to read and interpret circuit diagrams and wiring diagrams using BS EN 60617 symbols. The C&G 2365 (Level 2 Diploma in Electrical Installations) includes a unit on electrical science and principles that covers circuit diagrams and symbols. The C&G 2357 (Level 3 NVQ in Electrotechnical Services) requires the ability to interpret design documentation including circuit diagrams. The AM2 assessment also includes circuit diagram interpretation. Elec-Mate's study centre includes interactive symbol quizzes and diagram interpretation exercises.",
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/guides/wiring-colours-uk',
    title: 'UK Wiring Colours Guide',
    description:
      'Complete reference for old and new UK wiring colours with harmonisation explained.',
    icon: Cable,
    category: 'Guide',
  },
  {
    href: '/guides/bs-7671-18th-edition-guide',
    title: 'BS 7671 18th Edition Guide',
    description: 'Overview of the IET Wiring Regulations including Amendment 3 changes.',
    icon: BookOpen,
    category: 'Guide',
  },
  {
    href: '/guides/consumer-unit-regulations',
    title: 'Consumer Unit Regulations',
    description:
      'Current regulations for consumer units, MCB types, RCD arrangements, and Amendment 3.',
    icon: ShieldCheck,
    category: 'Guide',
  },
  {
    href: '/guides/earthing-arrangements',
    title: 'Earthing Arrangements',
    description: 'TN-S, TN-C-S, and TT earthing systems explained with symbols and diagrams.',
    icon: Zap,
    category: 'Guide',
  },
  {
    href: '/tools/eicr-certificate',
    title: 'EICR Certificate App',
    description:
      'Complete digital EICR certificates with correct BS EN 60617 symbols on all generated documents.',
    icon: FileCheck2,
    category: 'Certificate',
  },
  {
    href: '/training/level-2-electrical',
    title: 'Level 2 Electrical Course',
    description:
      'Start your electrical career with Level 2 training including circuit diagram interpretation.',
    icon: GraduationCap,
    category: 'Training',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'what-are-symbols',
    heading: 'What Are Electrical Symbols?',
    content: (
      <>
        <p>
          Electrical symbols are standardised graphical representations of electrical components,
          devices, and connections used on circuit diagrams, wiring diagrams, and installation
          drawings. They provide a universal language that allows electricians, designers, and
          inspectors to communicate the layout and function of an electrical installation without
          ambiguity.
        </p>
        <p>
          In the UK, electrical symbols follow <strong>BS EN 60617</strong> (Graphical symbols for
          diagrams), which is the European harmonised version of the international standard IEC
          60617. This standard defines symbols for everything from simple switches and socket
          outlets to complex protection devices and control circuits.
        </p>
        <p>Understanding electrical symbols is essential for:</p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <PenTool className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                Reading and interpreting installation drawings from architects and designers.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <PenTool className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                Completing distribution board schedules on{' '}
                <SEOInternalLink href="/tools/eicr-certificate">
                  electrical certificates
                </SEOInternalLink>
                .
              </span>
            </li>
            <li className="flex items-start gap-3">
              <PenTool className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>Drawing circuit charts for new installations.</span>
            </li>
            <li className="flex items-start gap-3">
              <PenTool className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                Passing Level 2, Level 3, and C&G 2391 examinations, all of which include diagram
                interpretation.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'switch-symbols',
    heading: 'Switch Symbols',
    content: (
      <>
        <p>
          Switch symbols all share a common base: a line at an angle representing the switch contact
          moving between open and closed positions. Variations indicate the type of switch.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>One-way switch:</strong> A single moving contact with one fixed contact.
                Used where a light is controlled from one position only.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Two-way switch:</strong> A single moving contact with two fixed contacts
                (fork shape). Used for controlling a light from two positions (staircase lighting,
                hallway lighting).
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Intermediate switch:</strong> A more complex symbol showing a double-pole,
                double-throw action. Used between two two-way switches when three or more switch
                positions control the same light.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Dimmer switch:</strong> The basic switch symbol with an additional arrow or
                diagonal line indicating variable control.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Pull-cord switch:</strong> The switch symbol with a small circle or dot
                indicating the pull-cord mechanism. Used in bathrooms and other locations where a
                plate switch is not appropriate.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ToggleRight className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Double-pole switch:</strong> Two switch symbols drawn in parallel,
                indicating that both live and neutral are switched simultaneously. Used for
                immersion heaters, cooker switches, and shower isolators.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'socket-symbols',
    heading: 'Socket Outlet Symbols',
    content: (
      <>
        <p>
          Socket outlet symbols use a semicircular shape to represent the outlet face. The number of
          semicircles indicates the number of sockets, and additional marks show switching and other
          features.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Single socket outlet:</strong> One semicircle. May include a horizontal line
                through it to indicate a switched socket.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Double socket outlet:</strong> Two semicircles side by side. Again, a line
                through indicates switched.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Fused connection unit (FCU):</strong> A rectangular symbol with a fuse
                element indicated inside. Used for fixed appliances such as boilers, towel
                radiators, and extractor fans.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Switched fused connection unit:</strong> The FCU symbol with a switch
                element added, indicating it can be locally isolated.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Shaver supply unit:</strong> A specific symbol indicating a BS EN 61558-2-5
                compliant transformer unit, used in{' '}
                <SEOInternalLink href="/guides/electrical-work-in-bathroom">
                  bathrooms
                </SEOInternalLink>
                .
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Home className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Cooker control unit:</strong> A symbol combining a switch with a socket
                outlet, representing the 45A switch and 13A socket typically found next to a cooker.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'light-symbols',
    heading: 'Lighting Symbols',
    content: (
      <>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Ceiling light:</strong> A circle with a cross inside (or lines radiating
                outward). The most common symbol on domestic installation drawings.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Wall light:</strong> A semicircle against a wall line, with radiating lines
                indicating the light output direction.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Downlight (recessed):</strong> A filled circle or a circle with a dot
                inside, indicating a recessed luminaire.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Fluorescent luminaire:</strong> A rectangular symbol representing the linear
                fitting, sometimes with a length dimension.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Emergency luminaire:</strong> The light symbol with an additional
                designation (often "EM" or an arrow) indicating it is an{' '}
                <SEOInternalLink href="/tools/emergency-lighting-certificate">
                  emergency lighting
                </SEOInternalLink>{' '}
                fitting with battery backup.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Exterior light:</strong> A light symbol with a weatherproof enclosure
                indication, used on site layout drawings.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'protection-symbols',
    heading: 'Protection Device Symbols',
    content: (
      <>
        <p>
          Protection device symbols are critical for understanding{' '}
          <SEOInternalLink href="/guides/consumer-unit-regulations">consumer unit</SEOInternalLink>{' '}
          schedules and circuit diagrams. Each type of protective device has a distinct symbol.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Fuse:</strong> A rectangular element in the circuit path, sometimes with a
                line through it. The oldest and simplest form of overcurrent protection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>MCB (Miniature Circuit Breaker):</strong> A switch symbol with an additional
                element showing the automatic trip mechanism (a small rectangle or arc indicating
                the thermal/magnetic trip). The most common protective device in modern consumer
                units.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>RCD (Residual Current Device):</strong> A switch symbol with a sensing coil
                element (often shown as a toroid or sinusoidal wave). The RCD detects imbalance
                between live and neutral current, indicating earth leakage.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>RCBO (RCD + MCB combined):</strong> Combines the MCB and RCD symbols in a
                single device, showing both overcurrent and residual current protection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>AFDD (Arc Fault Detection Device):</strong> A newer symbol introduced with
                BS 7671:2018. Shows the arc detection element alongside the overcurrent element.
                AFDDs detect series and parallel arc faults that could cause fire. Regulation
                421.1.7 recommends AFDDs for certain higher-risk locations.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Main switch / isolator:</strong> A simple switch symbol (open/closed
                contacts) without an automatic trip element. Used for the main switch in a consumer
                unit or local isolation of a circuit.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'circuit-symbols',
    heading: 'Circuit and Wiring Symbols',
    content: (
      <>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Conductor / wire:</strong> A single straight line. The most basic element on
                any circuit diagram.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Junction / connection:</strong> A filled dot where two or more conductors
                connect. Two crossing lines without a dot means the conductors cross but are not
                connected.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Earth connection:</strong> Three horizontal lines of decreasing length (like
                a triangle), or a single line ending in three short horizontal lines. Represents the
                connection to earth.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Cable / multicore:</strong> Multiple parallel lines or a single line with a
                number indicating the core count (e.g., "3C" for 3-core cable).
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Conduit:</strong> A line with small perpendicular marks indicating
                mechanical protection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Junction box:</strong> A filled or open square indicating a point where
                cables are terminated and connected.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Motor:</strong> A circle with an "M" inside, indicating an electric motor.
                Common on commercial and industrial diagrams.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CircuitBoard className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Transformer:</strong> Two coils (shown as parallel curved lines) with a core
                (shown as parallel straight lines between the coils).
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'distribution-symbols',
    heading: 'Distribution Board Symbols',
    content: (
      <>
        <p>
          Distribution board schedules use a combination of protection device symbols and circuit
          identification to show the arrangement of circuits in a consumer unit or distribution
          board.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Consumer unit:</strong> A rectangular outline representing the enclosure,
                with the main switch at one end and individual protective devices shown as branches.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Split-load board:</strong> The consumer unit symbol divided into sections,
                each protected by a separate RCD, with MCBs branching from each section.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>RCBO board:</strong> Each way shown with an individual RCBO symbol,
                indicating that every circuit has independent overcurrent and residual current
                protection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Busbar:</strong> A thick line representing the main busbar from which all
                circuits are fed.
              </span>
            </li>
          </ul>
        </div>
        <p>
          On an EICR or EIC, the distribution board schedule lists every circuit by number,
          describes its purpose (lighting, ring main, cooker, shower, etc.), and shows the type and
          rating of the protective device. Using the correct symbols ensures the schedule is
          unambiguous and can be understood by any qualified electrician.
        </p>
      </>
    ),
  },
  {
    id: 'reading-diagrams',
    heading: 'How to Read Circuit Diagrams',
    content: (
      <>
        <p>
          Reading a circuit diagram becomes straightforward once you know the symbols. Here are the
          key principles:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ol className="space-y-4 text-white list-decimal list-inside">
            <li>
              <strong>Start at the supply.</strong> Identify the incoming supply, the main switch or
              isolator, and the main distribution point (consumer unit or distribution board).
            </li>
            <li>
              <strong>Follow each circuit.</strong> Trace each circuit from its protective device
              through to the final accessory (socket, light, fixed appliance). Note the cable type
              and size if marked.
            </li>
            <li>
              <strong>Identify the protection.</strong> For each circuit, note the type of
              protective device (MCB, RCBO, fuse) and its rating. Check whether RCD protection is
              provided.
            </li>
            <li>
              <strong>Note the connections.</strong> Look for filled dots indicating connections
              between conductors. Crossing lines without dots are not connected.
            </li>
            <li>
              <strong>Check the earthing.</strong> Identify the{' '}
              <SEOInternalLink href="/guides/earthing-arrangements">
                earthing arrangement
              </SEOInternalLink>{' '}
              (TN-S, TN-C-S, or TT) and trace the main earth conductor to the earthing terminal.
            </li>
            <li>
              <strong>Read the legend.</strong> Most circuit diagrams include a legend or key
              explaining any non-standard symbols or abbreviations used.
            </li>
          </ol>
        </div>
      </>
    ),
  },
  {
    id: 'for-electricians',
    heading: 'For Electricians: Using Symbols on Site',
    content: (
      <>
        <p>
          On site, you encounter electrical symbols on installation drawings, distribution board
          schedules, and existing circuit charts. Elec-Mate integrates BS EN 60617 symbols
          throughout the app:
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <div className="flex items-start gap-4">
              <PenTool className="w-6 h-6 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Built-In Symbol Library</h4>
                <p className="text-white text-sm leading-relaxed">
                  Access the complete BS EN 60617 symbol set from within the app. Search by category
                  (switches, sockets, lights, protection devices) or by name. Each symbol includes a
                  description and the BS EN 60617 reference number.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5">
            <div className="flex items-start gap-4">
              <FileCheck2 className="w-6 h-6 text-blue-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Correct Symbols on Certificates</h4>
                <p className="text-white text-sm leading-relaxed">
                  All certificates generated by Elec-Mate use correct BS EN 60617 symbols on
                  distribution board schedules, circuit charts, and test result tables. This ensures
                  professional presentation and eliminates the guesswork of hand-drawing symbols.
                </p>
              </div>
            </div>
          </div>
        </div>
        <SEOAppBridge
          title="Professional symbols on every certificate"
          description="Join 430+ UK electricians producing certificates with correct BS EN 60617 symbols. Board scanner, voice test entry, AI defect coding, and instant PDF delivery. 7-day free trial."
          icon={PenTool}
        />
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function ElectricalSymbolsChartPage() {
  return (
    <GuideTemplate
      title="Electrical Symbols Chart | BS EN 60617 Reference"
      description="Complete reference chart for electrical symbols used in the UK following BS EN 60617. Switch symbols, socket symbols, light symbols, protection device symbols, circuit symbols, and how to read circuit diagrams."
      datePublished="2025-11-01"
      dateModified="2026-02-13"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Reference Guide"
      badgeIcon={PenTool}
      heroTitle={
        <>
          Electrical Symbols Chart:{' '}
          <span className="text-yellow-400">BS EN 60617 Reference for UK Electricians</span>
        </>
      }
      heroSubtitle="Every electrical symbol you need to know for circuit diagrams, installation drawings, and certificates. Switches, sockets, lights, protection devices, and circuit elements — all following BS EN 60617."
      readingTime={13}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions About Electrical Symbols"
      relatedPages={relatedPages}
      ctaHeading="Every Symbol at Your Fingertips"
      ctaSubheading="Built-in BS EN 60617 symbol library, correct symbols on every certificate, and AI-powered diagram interpretation. Elec-Mate is the complete reference tool for UK electricians. 7-day free trial."
    />
  );
}
