import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  ShieldCheck,
  AlertTriangle,
  Calculator,
  Zap,
  Cable,
  FileCheck2,
  GraduationCap,
  ClipboardCheck,
  CheckCircle2,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Installation', href: '/guides/electrical-certificate-types-uk' },
  { label: 'RCD Types', href: '/guides/rcd-types-a-b-f-explained' },
];

const tocItems = [
  { id: 'overview', label: 'RCD Types Overview' },
  { id: 'type-ac', label: 'Type AC' },
  { id: 'type-a', label: 'Type A' },
  { id: 'type-f', label: 'Type F' },
  { id: 'type-b', label: 'Type B' },
  { id: 'comparison', label: 'Side-by-Side Comparison' },
  { id: 'when-required', label: 'When Each Type Is Required' },
  { id: 'cost', label: 'Cost Comparison' },
  { id: 'regulations', label: 'BS 7671 Requirements' },
  { id: 'for-electricians', label: 'For Electricians' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'Type AC detects sinusoidal AC earth fault currents only. It is the cheapest type but is no longer recommended for new domestic installations because many modern loads produce non-sinusoidal fault currents.',
  'Type A detects sinusoidal AC and pulsating DC earth fault currents. It is now the minimum standard for most domestic circuits under BS 7671 Regulation 531.3.3, covering LED lighting, electronic equipment, and most household appliances.',
  'Type F detects everything Type A detects plus composite fault currents from frequency-controlled equipment (variable speed drives, some EV chargers, heat pumps). Required by some appliance manufacturers.',
  'Type B detects all types of earth fault current including smooth DC. Required for three-phase inverters, some EV chargers, and photovoltaic systems. Significantly more expensive than other types.',
  'BS 7671 Regulation 531.3.3 requires the RCD type to be selected according to the type of fault current that may be present. Always check the appliance manufacturer instructions for specific RCD type requirements.',
];

const faqs = [
  {
    question: 'What is the difference between Type AC and Type A RCDs?',
    answer:
      'Type AC detects only sinusoidal (pure sine wave) AC earth fault currents. Type A detects sinusoidal AC earth fault currents AND pulsating DC earth fault currents. Pulsating DC fault currents are produced by electronic rectifier circuits — found in LED drivers, computer power supplies, phone chargers, washing machine motor drives, and many modern appliances. A Type AC RCD may fail to detect these fault currents, leaving the circuit unprotected. This is why Type A is now the minimum standard for most domestic circuits. Type AC is no longer recommended for new installations in the UK.',
  },
  {
    question: 'When do I need a Type F RCD or RCBO?',
    answer:
      'Type F is required where fault currents may include composite waveforms generated by single-phase frequency converters (variable speed drives). Common examples include: certain EV chargers with built-in inverters, heat pumps with variable speed compressors, air conditioning units, and some washing machines and tumble dryers with inverter-driven motors. If the appliance manufacturer instructions specify Type F protection, you must use it. Some manufacturers specify that their equipment is compatible with Type A — always check.',
  },
  {
    question: 'When do I need a Type B RCD?',
    answer:
      'Type B is required where smooth DC fault currents may be present. This typically applies to: three-phase variable speed drives, three-phase inverters (such as commercial solar PV systems), some three-phase EV chargers, and DC charging systems. For domestic single-phase installations, Type B is rarely required — most single-phase loads are adequately protected by Type A or Type F. However, if a domestic installation includes a three-phase solar PV inverter or a DC fast charger, Type B may be needed. Always verify with the equipment manufacturer.',
  },
  {
    question: 'Can I use a Type A RCD where Type F is required?',
    answer:
      'No. If the appliance manufacturer or the equipment standard requires Type F, a Type A is not sufficient. Type F detects composite fault currents that Type A cannot reliably detect. Using a Type A where Type F is required means the RCD may not trip during a fault, leaving the circuit unprotected. However, a Type F can always be used where Type A is required — it provides all the detection capabilities of Type A plus additional composite current detection. Similarly, Type B can replace Type F or Type A.',
  },
  {
    question: 'How much more does a Type F or Type B RCBO cost?',
    answer:
      'Type A RCBOs typically cost £15 to £30 each. Type F RCBOs cost £25 to £50 each — roughly 50% to 100% more than Type A. Type B RCBOs cost £80 to £200 each — significantly more expensive due to the complex detection circuitry required for smooth DC fault currents. Type B devices are also physically larger, which can be an issue in consumer units with limited space. The high cost of Type B means it should only be specified where genuinely required by the load characteristics.',
  },
  {
    question: 'What does BS 7671 say about RCD type selection?',
    answer:
      'BS 7671 Regulation 531.3.3 states that where an RCD is used for fault protection or additional protection, the type of RCD shall be selected in accordance with the characteristics of the installation and the type of fault current that may be present. The regulation references the product standards (BS EN 61008, BS EN 61009, BS EN 62423) which define the detection capabilities of each type. In practical terms, this means the electrician must assess the loads on each circuit and select an RCD type that can detect the fault currents those loads may produce.',
  },
  {
    question: 'Do I need to replace existing Type AC RCDs during an EICR?',
    answer:
      'An existing Type AC RCD that was correctly specified at the time of installation is not automatically a defect. However, if the loads on the circuit have changed (for example, LED lighting or electronic equipment has been added), the Type AC may no longer be appropriate. On an EICR, this would typically be coded as C3 (improvement recommended) rather than C2, unless the assessor identifies a specific load that produces non-sinusoidal fault currents that the Type AC cannot detect. For new installations and consumer unit replacements, Type A should be specified as the minimum.',
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/guides/mcb-vs-rcbo',
    title: 'MCB vs RCBO Comparison',
    description: 'Choose between MCBs and RCBOs for your consumer unit design.',
    icon: ShieldCheck,
    category: 'Guide',
  },
  {
    href: '/guides/earthing-systems-tns-tncs-tt-explained',
    title: 'Earthing Systems Explained',
    description: 'TN-S, TN-C-S, and TT — RCD requirements vary by earthing system.',
    icon: Zap,
    category: 'Guide',
  },
  {
    href: '/eic-certificate',
    title: 'EIC Certificate App',
    description: 'Record RCD type and test results on your Electrical Installation Certificate.',
    icon: FileCheck2,
    category: 'Certificate',
  },
  {
    href: '/training/inspection-and-testing',
    title: 'Inspection and Testing Course',
    description: 'Master RCD testing and type selection for C&G 2391.',
    icon: GraduationCap,
    category: 'Training',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'overview',
    heading: 'RCD Types: What Every Electrician Needs to Know',
    content: (
      <>
        <p>
          RCDs (residual current devices) are classified by the type of earth fault current they can
          detect. The four main types — AC, A, F, and B — each detect progressively more waveforms.
          Using the wrong type means the RCD may not trip during a fault, leaving people
          unprotected.
        </p>
        <p>
          Modern homes are full of electronic loads that produce non-sinusoidal fault currents — LED
          drivers, EV chargers, heat pumps, washing machines with inverter motors, and IT equipment.
          Understanding which RCD type is needed for each circuit is now a core competency for UK
          electricians.
        </p>
        <p>
          This guide explains what each type detects, when it is required under{' '}
          <SEOInternalLink href="/guides/bs-7671-18th-edition-guide">
            BS 7671:2018+A3:2024
          </SEOInternalLink>
          , the cost differences, and practical guidance for specification.
        </p>
      </>
    ),
  },
  {
    id: 'type-ac',
    heading: 'Type AC: Sinusoidal AC Only',
    content: (
      <>
        <p>
          Type AC is the simplest and cheapest RCD type. It detects sinusoidal (pure sine wave) AC
          earth fault currents only. This was adequate when domestic loads were predominantly
          resistive (heaters, incandescent lighting, kettles) or simple inductive (motors with
          direct mains connection).
        </p>
        <div className="rounded-2xl bg-red-500/10 border border-red-500/20 p-5 my-4">
          <h3 className="font-bold text-white text-lg mb-3">Type AC Limitations</h3>
          <p className="text-white text-sm leading-relaxed">
            Type AC cannot reliably detect pulsating DC fault currents. These are produced by
            single-phase rectifier circuits, which are present in almost every modern electronic
            device — LED drivers, switched-mode power supplies, phone chargers, and inverter-driven
            motors. A DC component in the fault current can saturate the Type AC RCD current
            transformer, preventing it from detecting even the AC component of the fault. In extreme
            cases, a Type AC RCD can become completely blind to a fault.
          </p>
        </div>
        <p>
          Type AC is no longer recommended for new domestic installations in the UK. BS 7671
          Regulation 531.3.3 effectively requires Type A as the minimum for most circuits. Existing
          Type AC devices remain acceptable where the loads are purely sinusoidal, but this is
          increasingly rare.
        </p>
      </>
    ),
  },
  {
    id: 'type-a',
    heading: 'Type A: AC + Pulsating DC',
    content: (
      <>
        <p>
          Type A detects sinusoidal AC earth fault currents and pulsating DC earth fault currents.
          It is designed to handle the fault characteristics of single-phase rectifier loads — which
          covers the vast majority of modern domestic appliances.
        </p>
        <div className="rounded-2xl bg-green-500/10 border border-green-500/20 p-5 my-4">
          <h3 className="font-bold text-white text-lg mb-3">Type A Covers</h3>
          <ul className="space-y-2 text-white text-sm">
            <li>LED lighting and drivers</li>
            <li>Computer and IT equipment power supplies</li>
            <li>Phone and tablet chargers</li>
            <li>Washing machines and dishwashers (most models)</li>
            <li>Kitchen appliances with electronic controls</li>
            <li>Most single-phase domestic loads</li>
          </ul>
        </div>
        <p>
          Type A is now the standard choice for most domestic circuits. It provides reliable
          protection for modern electronic loads at a modest cost premium over Type AC. For a
          consumer unit upgrade or new installation, Type A RCBOs should be the baseline
          specification.
        </p>
      </>
    ),
  },
  {
    id: 'type-f',
    heading: 'Type F: AC + Pulsating DC + Composite',
    content: (
      <>
        <p>
          Type F detects everything Type A detects plus composite fault currents — complex waveforms
          produced by single-phase frequency converters (variable speed drives). These generate
          fault currents that combine multiple frequencies, which Type A may not reliably detect.
        </p>
        <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5 my-4">
          <h3 className="font-bold text-white text-lg mb-3">When Type F Is Needed</h3>
          <ul className="space-y-2 text-white text-sm">
            <li>EV chargers with built-in power electronics (check manufacturer instructions)</li>
            <li>Heat pumps with variable speed compressors</li>
            <li>Air conditioning units with inverter-driven compressors</li>
            <li>Washing machines and tumble dryers with inverter motors</li>
            <li>Any appliance with a single-phase variable speed drive</li>
          </ul>
        </div>
        <p>
          Not all appliances in these categories require Type F — many are compatible with Type A.
          The equipment manufacturer instructions are the definitive reference. If the instructions
          specify Type F, you must use it. If they specify "Type A minimum", Type A is sufficient
          but Type F would also work.
        </p>
      </>
    ),
  },
  {
    id: 'type-b',
    heading: 'Type B: All Fault Current Types Including Smooth DC',
    content: (
      <>
        <p>
          Type B is the most comprehensive RCD type. It detects sinusoidal AC, pulsating DC,
          composite, and smooth DC earth fault currents. Smooth DC fault currents are produced by
          three-phase rectifier circuits and DC power systems.
        </p>
        <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5 my-4">
          <h3 className="font-bold text-white text-lg mb-3">When Type B Is Needed</h3>
          <ul className="space-y-2 text-white text-sm">
            <li>Three-phase solar PV inverters</li>
            <li>Three-phase EV chargers (DC fast chargers)</li>
            <li>Three-phase variable speed drives</li>
            <li>DC charging systems</li>
            <li>Any equipment producing smooth DC fault currents</li>
          </ul>
        </div>
        <p>
          Type B devices are significantly more expensive (£80 to £200 for an RCBO) and physically
          larger than other types. They should only be specified where the load genuinely produces
          smooth DC fault currents. For most domestic single-phase installations, Type B is not
          required. Some EV charger manufacturers include built-in DC fault detection (6mA DC
          detection), which allows the use of a Type A RCD upstream — check the manufacturer
          documentation.
        </p>
      </>
    ),
  },
  {
    id: 'comparison',
    heading: 'Side-by-Side Comparison',
    content: (
      <>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4 overflow-x-auto">
          <table className="w-full text-white text-sm">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-3 pr-4 font-bold">Feature</th>
                <th className="text-left py-3 pr-4 font-bold">Type AC</th>
                <th className="text-left py-3 pr-4 font-bold">Type A</th>
                <th className="text-left py-3 pr-4 font-bold">Type F</th>
                <th className="text-left py-3 font-bold">Type B</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              <tr>
                <td className="py-3 pr-4">Sinusoidal AC</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3">Yes</td>
              </tr>
              <tr>
                <td className="py-3 pr-4">Pulsating DC</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3">Yes</td>
              </tr>
              <tr>
                <td className="py-3 pr-4">Composite</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3 pr-4">Yes</td>
                <td className="py-3">Yes</td>
              </tr>
              <tr>
                <td className="py-3 pr-4">Smooth DC</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3 pr-4">No</td>
                <td className="py-3">Yes</td>
              </tr>
              <tr>
                <td className="py-3 pr-4">RCBO cost (typical)</td>
                <td className="py-3 pr-4">£8 to £15</td>
                <td className="py-3 pr-4">£15 to £30</td>
                <td className="py-3 pr-4">£25 to £50</td>
                <td className="py-3">£80 to £200</td>
              </tr>
              <tr>
                <td className="py-3 pr-4">Domestic use</td>
                <td className="py-3 pr-4">Legacy only</td>
                <td className="py-3 pr-4">Standard</td>
                <td className="py-3 pr-4">Specific loads</td>
                <td className="py-3">Rare</td>
              </tr>
            </tbody>
          </table>
        </div>
      </>
    ),
  },
  {
    id: 'when-required',
    heading: 'When Each Type Is Required',
    content: (
      <>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <CheckCircle2 className="w-5 h-5 text-green-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type A — default for new domestic installations:</strong> All socket
                circuits, lighting circuits, kitchen appliances, and general domestic loads. Meets
                BS 7671 Regulation 531.3.3 for the vast majority of domestic circuits.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle2 className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type F — when specified by the appliance manufacturer:</strong> EV charger
                circuits, heat pump circuits, and air conditioning circuits where the manufacturer
                instructions require Type F. Do not assume Type F is needed — check the
                documentation.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle2 className="w-5 h-5 text-blue-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type B — three-phase inverter loads and DC systems:</strong> Only required
                for circuits feeding three-phase power electronics or DC equipment. Verify with the
                manufacturer before specifying.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'cost',
    heading: 'Cost Comparison',
    content: (
      <>
        <p>
          The cost difference between RCD types is significant, particularly for Type B devices:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-3 text-white">
            <li className="flex items-start gap-3">
              <Calculator className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type A RCBO:</strong> £15 to £30 — the standard for most domestic circuits.
                Modest premium over Type AC for significantly better protection.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Calculator className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type F RCBO:</strong> £25 to £50 — only needed for specific circuits with
                frequency converter loads. Do not fit Type F across the entire board unless
                required.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Calculator className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Type B RCBO:</strong> £80 to £200 — expensive and physically large. Only
                specify where smooth DC fault currents are present. Check if the equipment has
                built-in DC detection that allows Type A upstream.
              </span>
            </li>
          </ul>
        </div>
        <p>
          For a typical 12-way domestic RCBO board, using Type A across all circuits costs
          approximately £180 to £360 for the RCBOs. Replacing one or two circuits with Type F for an
          EV charger and heat pump adds £20 to £40 to the total. Type B should only be specified
          where genuinely required — the cost difference is not justified on a precautionary basis.
        </p>
      </>
    ),
  },
  {
    id: 'regulations',
    heading: 'BS 7671 Requirements for RCD Type Selection',
    content: (
      <>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Regulation 531.3.3:</strong> The characteristics of an RCD shall be selected
                in accordance with the duty the device is required to perform. Where the load may
                produce DC components in the earth fault current, the type of RCD must be
                appropriate for those characteristics. This is the key regulation driving Type A as
                the minimum domestic standard.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Regulation 411.3.3:</strong> Additional protection by an RCD with a rated
                residual operating current not exceeding 30mA. This regulation specifies where RCD
                protection is required (sockets, outdoor mobile equipment, etc.) but does not
                specify the type — that is covered by Regulation 531.3.3.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Regulation 722.531.3.101 (EV charging):</strong> The supply to EV charging
                equipment shall be protected by an RCD that can detect DC fault currents. This can
                be Type B, or Type A where the equipment incorporates DC fault detection.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'for-electricians',
    heading: 'For Electricians: Practical Specification',
    content: (
      <>
        <p>
          The simplest approach for domestic installations: specify Type A RCBOs as the default for
          all circuits, then upgrade individual circuits to Type F or Type B where the connected
          equipment requires it. Always check the appliance manufacturer instructions.
        </p>
        <SEOAppBridge
          title="Record RCD types and test results on site"
          description="Elec-Mate's EIC and EICR apps include RCD type recording, trip time testing, and automatic compliance checking. Complete your certificates on your phone. 7-day free trial."
          icon={ShieldCheck}
        />
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function RCDTypesComparisonPage() {
  return (
    <GuideTemplate
      title="RCD Types AC, A, F, B Explained | UK Electrician Guide"
      description="Complete guide to RCD types for UK electricians. Type AC, A, F, and B differences, when each is required, cost comparison, BS 7671 Regulation 531.3.3 requirements, and practical specification guidance."
      datePublished="2026-03-27"
      dateModified="2026-03-27"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Technical Guide"
      badgeIcon={ShieldCheck}
      heroTitle={
        <>
          RCD Types: <span className="text-yellow-400">AC, A, F, and B Explained</span>
        </>
      }
      heroSubtitle="Using the wrong RCD type means it may not trip during a fault. This guide explains what each type detects, when each is required under BS 7671, the cost differences, and practical specification guidance for UK electricians."
      readingTime={12}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions About RCD Types"
      relatedPages={relatedPages}
      ctaHeading="Record RCD Types and Test Results on Your Phone"
      ctaSubheading="Join 1,000+ UK electricians using Elec-Mate for on-site certification with RCD type recording and compliance checking. 7-day free trial, cancel anytime."
    />
  );
}
