import GuideTemplate from '@/pages/seo/templates/GuideTemplate';
import { SEOInternalLink } from '@/components/seo/SEOInternalLink';
import { SEOAppBridge } from '@/components/seo/SEOAppBridge';
import type { RelatedPage } from '@/components/seo/SEORelatedPages';
import {
  AlertTriangle,
  ShieldCheck,
  ClipboardCheck,
  FileCheck2,
  GraduationCap,
  Zap,
  Wrench,
  Gauge,
  Sun,
} from 'lucide-react';

// -------------------------------------------------------------------
// Data
// -------------------------------------------------------------------

const breadcrumbs = [
  { label: 'Guides', href: '/guides/electrical-certificate-types-uk' },
  {
    label: 'Thermal Imaging for Electrical Inspections',
    href: '/guides/thermal-imaging-electrical-inspections',
  },
];

const tocItems = [
  { id: 'overview', label: 'What is Thermal Imaging in Electrical Work?' },
  { id: 'eicr-use', label: 'Thermal Imaging in EICRs' },
  { id: 'hotspots', label: 'Identifying Hotspots' },
  { id: 'pv-iec62446', label: 'Solar PV: IEC 62446-3' },
  { id: 'camera-specs', label: 'Camera Specifications for Electrical Work' },
  { id: 'standards', label: 'NETA and Industry Standards' },
  { id: 'for-electricians', label: 'For Electricians' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related Pages' },
];

const keyTakeaways = [
  'Thermal imaging (thermography) detects heat generated by electrical problems — loose connections, overloaded conductors, failing components, and overloaded neutrals — that are invisible to the eye and undetectable by standard electrical tests.',
  'In EICRs, thermal imaging is an additional investigative tool that can be used to detect hotspots in distribution boards, busbar chambers, cable trays, and equipment enclosures without requiring shutdown.',
  'For solar PV installations, IEC 62446-3 (the standard for photovoltaic system test, documentation, and maintenance) explicitly includes thermal imaging as a commissioning and maintenance test method for identifying faulty cells, bypass diodes, and connector heating.',
  'Camera specifications that matter for electrical work include NETD (noise equivalent temperature difference) below 50mK for sensitivity, a minimum resolution of 320×240 pixels for usable detail on components, and a measurement range that covers typical electrical temperatures (up to at least 350°C).',
  'Thermal imaging does not replace electrical testing — it supplements it. High-resistance connections that generate heat are also detectable by resistance measurement, but thermal imaging is faster on large installations and can detect faults during normal operation without requiring circuit isolation.',
];

const faqs = [
  {
    question: 'When should I use thermal imaging in an electrical inspection?',
    answer:
      'Thermal imaging is most valuable when: inspecting large switchboards, busbar chambers, or cable trays where opening every enclosure would be impractical; the client has reported intermittent trips or unexplained heating; the installation is critical and any downtime for testing is costly (data centres, hospitals, industrial production lines); inspecting solar PV arrays as part of commissioning or periodic maintenance per IEC 62446-3; or investigating a suspected loose connection or overloaded neutral that has not been located by conventional testing. Thermal imaging is not a substitute for electrical testing — it does not measure insulation resistance, earth fault loop impedance, or continuity. It should be used in addition to standard inspection and test procedures.',
  },
  {
    question: 'What does a hotspot look like on a thermal image?',
    answer:
      'A hotspot appears as an area of elevated temperature relative to the surrounding components — typically shown in a warmer colour (red, yellow, or white) on the false-colour thermal image display. The significance of the temperature rise depends on context: a 10°C rise above ambient on a terminal in a distribution board warrants investigation; a 30°C or more rise above ambient indicates a potentially serious fault. For comparison, the IEC 61010 guidance and NETA standards classify temperature differentials: 1 to 10°C above reference is generally acceptable; 11 to 20°C indicates potential fault requiring monitoring; 21 to 40°C indicates a developing fault requiring corrective action; above 40°C indicates an immediate hazard requiring shutdown and repair. Always compare like-for-like: a phase terminal at 50°C running at full load is a different risk from a neutral terminal at 50°C carrying light load.',
  },
  {
    question: 'What camera specifications do I need for electrical thermal imaging?',
    answer:
      'For electrical inspection work, the minimum recommended thermal camera specifications are: resolution of 320×240 pixels (76,800 pixels) — lower resolution cameras miss detail on small components such as MCB terminals and cable connections; NETD (noise equivalent temperature difference) below 50mK — this is the sensitivity of the sensor, with lower values giving cleaner images and the ability to detect smaller temperature differences; temperature measurement range of -20°C to at least 350°C; accuracy of ±2°C or ±2% of reading; an optical resolution (D:S ratio) of at least 100:1 for working at practical distances from switchboards; and a frame rate of at least 9Hz (25Hz preferred) for real-time imaging. Cameras meeting the FLIR Ex, FLIR Exx, or Testo 8xx series specifications are typical for this level of work. For higher-grade PV and industrial inspections, 640×480 resolution is preferable.',
  },
  {
    question: 'Is IEC 62446-3 relevant to all solar PV inspections?',
    answer:
      'IEC 62446-3 (Photovoltaic (PV) systems — requirements for testing, documentation and maintenance — Part 3: Photovoltaic modules and plants — outdoor infrared thermography) is the international standard for thermal imaging of PV installations. It is relevant to any inspection or maintenance of a solar PV installation where thermal imaging is used. The standard specifies: minimum irradiance conditions for testing (at least 600 W/m² for module-level testing); the correct thermal pattern signatures for different fault types (cell defects, bypass diode failures, soiling, delamination, shading effects); classification of anomalies by temperature differential; and documentation requirements for thermal imaging reports. UK solar PV installers carrying out periodic maintenance to MCS standards should be familiar with IEC 62446-3 requirements.',
  },
  {
    question: 'Can I use thermal imaging to find a loose connection?',
    answer:
      'Yes. Loose electrical connections have higher contact resistance than solid connections. Under load current, this higher resistance generates heat proportional to I²R — so under high load, a loose connection can generate a significant temperature rise while an identical connection under light load may show little heating. For thermal imaging to reliably detect loose connections: the circuit must be under load (thermal imaging of a dead or lightly loaded circuit misses many faults); the load should be at least 30% to 40% of the circuit rating for meaningful results; and the thermal image should be taken after a period of operation sufficient for temperatures to stabilise (typically 15 to 20 minutes at load). Thermal imaging of distribution boards is best carried out during periods of high load such as morning startup in commercial premises.',
  },
  {
    question: 'Do I need a qualification to carry out thermal imaging surveys?',
    answer:
      'There is no specific legal requirement for a thermography qualification for electrical inspections in the UK. However, the Institute of Engineering and Technology (IET) guidance and BSRIA guidance recommend that persons carrying out thermal imaging surveys of electrical installations should have a relevant qualification such as Level 1 or Level 2 thermography certification from a recognised body (for example, the Infrared Training Centre or BINDT). Level 1 qualifies for data collection under supervision; Level 2 qualifies for interpretation and report writing. For solar PV thermal imaging under IEC 62446-3, a relevant understanding of PV system operation is also required to correctly interpret the thermal patterns. For electrical inspectors who use thermal imaging as a supplementary tool rather than as the primary inspection method, formal thermography certification is advisable but not universally mandated.',
  },
  {
    question: 'What are overloaded neutrals and how does thermal imaging find them?',
    answer:
      'In three-phase installations, the neutral conductor carries the vector sum of the three phase currents. In a balanced installation (equal loads on all three phases), the neutral current is theoretically zero. In an unbalanced installation, the neutral carries an imbalance current. However, in installations with significant non-linear loads (switch-mode power supplies, variable speed drives, computer equipment), the neutral can carry third harmonic currents that are additive rather than cancelling — meaning the neutral current can exceed any individual phase current. This overloading of the neutral conductor generates heat that is detectable with a thermal camera. On a thermal image, an overloaded neutral busbar or neutral cable appears significantly hotter than the phase conductors, even when the load appears balanced by conventional phase current measurement.',
  },
];

const relatedPages: RelatedPage[] = [
  {
    href: '/guides/electrical-fault-finding-guide',
    title: 'Electrical Fault Finding Methodology',
    description: 'Systematic approach to fault finding including visual inspection and testing.',
    icon: ClipboardCheck,
    category: 'Guide',
  },
  {
    href: '/guides/troubleshooting-high-earth-leakage',
    title: 'Troubleshooting High Earth Leakage',
    description: 'Clamp meter and systematic isolation methods for earth leakage faults.',
    icon: AlertTriangle,
    category: 'Guide',
  },
  {
    href: '/tools/solar-pv-certificate',
    title: 'Solar PV Certificate App',
    description:
      'Complete solar PV commissioning certificates including IEC 62446-3 documentation.',
    icon: Sun,
    category: 'Certificate',
  },
  {
    href: '/tools/eicr-certificate',
    title: 'EICR Certificate App',
    description: 'Record thermal imaging findings with photos and generate coded observations.',
    icon: FileCheck2,
    category: 'Certificate',
  },
  {
    href: '/guides/earthing-system-fault-finding',
    title: 'Earthing System Fault Finding',
    description: 'Diagnosing earth electrode faults, open circuit earth, and PME issues.',
    icon: Zap,
    category: 'Guide',
  },
  {
    href: '/training/inspection-and-testing',
    title: 'Inspection and Testing Course',
    description: 'C&G 2391 training covering inspection methods and supplementary techniques.',
    icon: GraduationCap,
    category: 'Training',
  },
];

// -------------------------------------------------------------------
// Sections
// -------------------------------------------------------------------

const sections = [
  {
    id: 'overview',
    heading: 'What is Thermal Imaging in Electrical Work?',
    content: (
      <>
        <p>
          Thermal imaging (infrared thermography) detects heat radiated from surfaces and presents
          it as a false-colour image in which different temperatures appear as different colours.
          All electrical components operating under load generate some heat — the greater the
          resistance and the current, the greater the heat generated. When a component develops a
          fault (loose connection, corrosion, failing insulation, overloaded conductor), its
          resistance increases and it generates more heat than the surrounding healthy components.
          This heat signature is often detectable with a thermal camera before any other symptom is
          visible and before the component fails.
        </p>
        <p>
          In electrical inspection work, thermal imaging is a non-contact, non-destructive technique
          that can survey large quantities of equipment quickly without requiring circuit isolation.
          A thermal survey of a large distribution board that would take hours to physically inspect
          can be completed in minutes, identifying the specific areas where further investigation is
          warranted.
        </p>
        <p>
          Thermal imaging is particularly valuable in commercial and industrial installations where
          the financial cost of a fault-related shutdown far exceeds the cost of the thermal survey.
          It is also increasingly used in domestic EICR work and is mandatory for solar PV
          commissioning and maintenance under IEC 62446-3.
        </p>
      </>
    ),
  },
  {
    id: 'eicr-use',
    heading: 'Thermal Imaging in EICRs',
    content: (
      <>
        <p>
          BS 7671:2018+A3:2024 does not mandate thermal imaging as part of a standard EICR
          inspection, but the IET Guidance Note 3 (Inspection and Testing) acknowledges it as a
          valid supplementary inspection technique. In practice, thermal imaging is increasingly
          offered as an added-value service during EICR inspection of commercial and industrial
          premises.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Gauge className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Distribution boards and switchboards</strong> — thermal imaging of MCBs,
                busbar connections, and cable terminations identifies overloaded circuits and loose
                connections that standard testing may not detect.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Gauge className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Cable trays and cable management</strong> — thermal imaging of cable runs
                identifies overloaded cables and cables that have been incorrectly grouped (bundled
                without derating), causing them to overheat under normal load.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Gauge className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Motor control centres</strong> — contactor coils, overload relays, and motor
                terminals can develop high-resistance connections that are detected by thermal
                imaging before motor failure occurs.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Gauge className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Transformer connections</strong> — HV and LV terminals of distribution
                transformers are a common location for high-resistance connections that develop
                significant heating under load.
              </span>
            </li>
          </ul>
        </div>
        <SEOAppBridge
          title="Attach thermal images to EICR observations on your phone"
          description="Elec-Mate's EICR app lets you attach thermal images directly to coded observations, providing clients with visual evidence of faults in your professional inspection reports."
          icon={ShieldCheck}
        />
      </>
    ),
  },
  {
    id: 'hotspots',
    heading: 'Identifying Hotspots — Loose Connections and Overloaded Neutrals',
    content: (
      <>
        <p>The two most common electrical fault patterns identified by thermal imaging are:</p>
        <div className="grid gap-4 sm:grid-cols-2 my-4">
          <div className="rounded-2xl bg-red-500/10 border border-red-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-3">Loose Connections</h3>
            <p className="text-white text-sm leading-relaxed">
              A loose terminal screw or poor crimp joint creates an air gap that increases contact
              resistance. Under load current, this resistance generates heat: P = I²R. The affected
              terminal appears significantly hotter than adjacent terminals carrying the same
              current. On a thermal image, a loose terminal in a 100A distribution board may show
              80°C while adjacent terminals are at 30°C. This differential is unmistakeable and
              would cause failure if not corrected. Common locations: MCB terminals, busbar
              connections, cable gland terminals, and socket outlet faceplates.
            </p>
          </div>
          <div className="rounded-2xl bg-orange-500/10 border border-orange-500/20 p-5">
            <h3 className="font-bold text-white text-lg mb-3">Overloaded Neutrals</h3>
            <p className="text-white text-sm leading-relaxed">
              In commercial premises with IT equipment, LED lighting with switch-mode drivers, and
              other non-linear loads, third-harmonic currents in the neutral conductor can exceed
              phase currents. The neutral busbar appears significantly hotter than the phase busbars
              even though load balancing appears correct by phase measurement. This is a common
              finding in open-plan offices converted to LED lighting with DALI controls, and in data
              centres. The solution is to upsize the neutral or install K-rated transformers.
            </p>
          </div>
        </div>
        <p>
          When a hotspot is identified by thermal imaging, follow up with electrical tests to
          confirm the cause. A loose connection can be confirmed by{' '}
          <SEOInternalLink href="/guides/continuity-testing-electricians-guide">
            resistance measurement
          </SEOInternalLink>{' '}
          of the terminal before and after tightening. An overloaded neutral can be confirmed by
          measuring neutral current with a clamp meter.
        </p>
      </>
    ),
  },
  {
    id: 'pv-iec62446',
    heading: 'Solar PV Thermal Imaging — IEC 62446-3',
    content: (
      <>
        <p>
          IEC 62446-3 is the international standard for outdoor infrared thermography of
          photovoltaic modules and plants. It is referenced in MCS and IET guidance on solar PV
          inspection and maintenance, and its requirements apply to any thermal imaging survey of a
          solar PV installation in the UK.
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Sun className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Irradiance requirement</strong> — IEC 62446-3 requires a minimum solar
                irradiance of 600 W/m² for module-level thermal imaging. Below this level, the
                modules are not generating enough current to make fault heating detectable. In the
                UK, this restricts PV thermal imaging to clear days between approximately 10:00 and
                14:00 BST in summer.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Sun className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Fault signatures</strong> — different PV faults create characteristic
                thermal patterns: a single hot cell indicates a cracked or damaged cell; multiple
                cells in a row indicate a failed bypass diode; the entire module being cooler than
                others indicates an open circuit or shading; connector heating indicates a loose or
                corroded MC4 connector.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Sun className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Classification</strong> — IEC 62446-3 classifies anomalies by temperature
                differential: Class 1 (minor, ΔT less than 10°C) to Class 3 (severe, ΔT over 40°C or
                absolute temperature risk). Class 3 anomalies require immediate investigation.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Sun className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Documentation</strong> — the standard requires that each anomaly is
                photographed with both the thermal and optical images, the GPS location recorded,
                and a written report produced with classification and recommended action.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'camera-specs',
    heading: 'Camera Specifications for Electrical Thermal Imaging',
    content: (
      <>
        <p>
          The quality of a thermal image depends critically on the camera specifications. For
          electrical inspection work, the following minimum specifications are recommended:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Thermal resolution</strong> — minimum 320×240 pixels (76,800 pixels) for
                distribution board inspection. Higher resolution (640×480, 307,200 pixels) is
                preferable for large panel surveys and for detecting small components.
                Consumer-grade cameras with resolutions below 80×60 pixels are not suitable for
                electrical work.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>NETD (Noise Equivalent Temperature Difference)</strong> — below 50mK
                (0.05°C). This is the smallest temperature difference the camera can detect
                reliably. Lower NETD values give cleaner images and allow detection of smaller
                temperature differentials indicating developing faults. Most professional inspection
                cameras specify NETD of 30mK to 50mK.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Temperature range and accuracy</strong> — a measurement range of -20°C to
                350°C minimum, with accuracy of ±2°C or ±2% of reading (whichever is greater). This
                covers all typical electrical fault temperatures.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>D:S (distance to spot size) ratio</strong> — at least 100:1. This means the
                camera can measure a 1cm spot from 100cm distance. For working at practical
                distances from distribution boards (0.5m to 2m), a 100:1 D:S ratio provides adequate
                spatial resolution.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>Optical camera integration</strong> — a built-in optical (visible) camera
                allows thermal and optical images to be captured simultaneously and overlaid. This
                is essential for producing interpretable reports — a thermal image alone is often
                insufficient to identify the exact component.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'standards',
    heading: 'NETA and Industry Standards for Electrical Thermal Imaging',
    content: (
      <>
        <p>
          Several industry standards and guidance documents are relevant to electrical thermal
          imaging in the UK:
        </p>
        <div className="rounded-2xl bg-white/[0.04] border border-white/10 p-6 my-4">
          <ul className="space-y-4 text-white">
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>NETA ATS-2019</strong> (ANSI/NETA Acceptance Testing Specifications) — the
                American standard widely used as a reference for electrical commissioning and
                maintenance testing, including thermal imaging criteria and temperature differential
                classification.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>IEC 62446-3</strong> — the specific standard for PV system thermal imaging,
                applicable to all PV installations in the UK when thermal imaging is used as part of
                commissioning or maintenance.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>IET Guidance Note 3</strong> (Inspection and Testing) — references thermal
                imaging as a supplementary inspection technique for electrical installations.
              </span>
            </li>
            <li className="flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
              <span>
                <strong>ISO 18434-1</strong> (Condition monitoring of machines — thermography) — the
                general international standard for thermographic inspection, applicable to
                electrical machinery.
              </span>
            </li>
          </ul>
        </div>
      </>
    ),
  },
  {
    id: 'for-electricians',
    heading: 'For Electricians: Adding Thermal Imaging to Your Services',
    content: (
      <>
        <p>
          Offering thermal imaging surveys as part of EICR or periodic maintenance services
          differentiates your business and provides tangible added value to commercial clients. Here
          is a practical guide to getting started:
        </p>
        <div className="space-y-4 my-4">
          <div className="rounded-2xl bg-yellow-500/10 border border-yellow-500/20 p-5">
            <div className="flex items-start gap-4">
              <Wrench className="w-6 h-6 text-yellow-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Start with a Mid-Range Camera</h4>
                <p className="text-white text-sm leading-relaxed">
                  A mid-range thermal camera in the £1,500 to £3,000 range (such as a FLIR E6 Pro or
                  Testo 871) meets the minimum specifications for distribution board inspection.
                  This is sufficient to start offering thermal surveys as an EICR add-on. Upgrade to
                  a higher-resolution camera as the service grows.
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-5">
            <div className="flex items-start gap-4">
              <ClipboardCheck className="w-6 h-6 text-blue-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="font-bold text-white mb-1">Document Every Thermal Image</h4>
                <p className="text-white text-sm leading-relaxed">
                  Use the{' '}
                  <SEOInternalLink href="/tools/eicr-certificate">
                    Elec-Mate EICR app
                  </SEOInternalLink>{' '}
                  to attach thermal images directly to coded observations. Clients value the visual
                  evidence — a thermal image of a glowing terminal in their distribution board is
                  far more compelling than a written description. It also protects you if the fault
                  develops further after your inspection.
                </p>
              </div>
            </div>
          </div>
        </div>
      </>
    ),
  },
];

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default function ThermalImagingElectricalPage() {
  return (
    <GuideTemplate
      title="Thermal Imaging for Electrical Inspections | IEC 62446-3 and Camera Specs"
      description="Complete guide to thermal imaging in electrical inspections for UK electricians. Covers use in EICRs, hotspot identification, IEC 62446-3 for solar PV, camera specifications (NETD below 50mK, 320×240 resolution minimum), and NETA standards."
      datePublished="2026-03-27"
      dateModified="2026-03-27"
      breadcrumbs={breadcrumbs}
      tocItems={tocItems}
      badge="Inspection Guide"
      badgeIcon={Gauge}
      heroTitle={
        <>
          Thermal Imaging for Electrical Inspections:{' '}
          <span className="text-yellow-400">Hotspots, IEC 62446-3, and Camera Specs</span>
        </>
      }
      heroSubtitle="A complete guide to using thermal imaging in electrical inspections. Covers EICR applications, hotspot detection (loose connections, overloaded neutrals), solar PV thermal imaging under IEC 62446-3, camera specifications for electrical work, and NETA standards."
      readingTime={13}
      keyTakeaways={keyTakeaways}
      sections={sections}
      faqs={faqs}
      faqHeading="Frequently Asked Questions About Thermal Imaging in Electrical Inspections"
      relatedPages={relatedPages}
      ctaHeading="Attach Thermal Images to EICR Reports on Your Phone"
      ctaSubheading="Elec-Mate's EICR app lets you attach thermal and optical images directly to coded observations for professional client reports. Join 1,000+ UK electricians. 7-day free trial."
    />
  );
}
