"""Comprehensive UK town / city list for Google Places sweeps.

~500 locations covering England, Scotland, Wales and Northern Ireland.
Includes every city plus every town with population > ~15,000.

Source: compiled from ONS built-up area data + Wikipedia lists of UK towns.
"""

from __future__ import annotations

UK_TOWNS: list[str] = [
    # ─── London boroughs ────────────────────────────────────────
    "City of London", "Barking", "Barnet", "Bexley", "Brent", "Bromley",
    "Camden", "Croydon", "Ealing", "Enfield", "Greenwich", "Hackney",
    "Hammersmith", "Haringey", "Harrow", "Havering", "Hillingdon",
    "Hounslow", "Islington", "Kensington", "Kingston upon Thames",
    "Lambeth", "Lewisham", "Merton", "Newham", "Redbridge", "Richmond",
    "Southwark", "Sutton", "Tower Hamlets", "Waltham Forest",
    "Wandsworth", "Westminster",

    # ─── South East ─────────────────────────────────────────────
    "Reading", "Milton Keynes", "Oxford", "Southampton", "Portsmouth",
    "Brighton", "Hove", "Hastings", "Eastbourne", "Worthing", "Crawley",
    "Horsham", "Chichester", "Basingstoke", "Farnborough", "Aldershot",
    "Guildford", "Woking", "Redhill", "Reigate", "Dorking", "Epsom",
    "Leatherhead", "Staines", "Slough", "High Wycombe", "Aylesbury",
    "Banbury", "Canterbury", "Maidstone", "Dover", "Folkestone",
    "Margate", "Ramsgate", "Chatham", "Gillingham", "Rochester",
    "Sittingbourne", "Ashford Kent", "Tunbridge Wells", "Tonbridge",
    "Sevenoaks", "Gravesend", "Dartford", "Bracknell", "Wokingham",
    "Newbury", "Andover", "Winchester", "Fareham", "Gosport", "Havant",
    "Waterlooville", "Petersfield", "Bognor Regis", "Littlehampton",
    "Burgess Hill", "Haywards Heath", "East Grinstead", "Henley on Thames",
    "Wallingford", "Bicester", "Witney", "Didcot", "Abingdon",
    "Hemel Hempstead", "Watford", "St Albans", "Harpenden",
    "Hitchin", "Stevenage", "Letchworth", "Welwyn Garden City",
    "Hatfield", "Hertford", "Cheshunt", "Bishops Stortford",
    "Luton", "Bedford", "Dunstable", "Leighton Buzzard",

    # ─── South West ─────────────────────────────────────────────
    "Bristol", "Bath", "Weston-super-Mare", "Taunton", "Yeovil",
    "Bridgwater", "Wells", "Glastonbury", "Frome", "Chard", "Minehead",
    "Exeter", "Plymouth", "Torquay", "Paignton", "Newton Abbot",
    "Exmouth", "Tiverton", "Barnstaple", "Bideford", "Ilfracombe",
    "Newquay", "Truro", "Penzance", "St Austell", "Falmouth",
    "Redruth", "Camborne", "Bodmin", "Launceston", "Bournemouth",
    "Poole", "Weymouth", "Dorchester", "Bridport", "Shaftesbury",
    "Blandford Forum", "Wimborne", "Christchurch", "Salisbury",
    "Swindon", "Chippenham", "Trowbridge", "Devizes", "Warminster",
    "Marlborough", "Cirencester", "Stroud", "Gloucester",
    "Cheltenham", "Tewkesbury", "Dursley", "Thornbury", "Keynsham",

    # ─── East of England ────────────────────────────────────────
    "Ipswich", "Colchester", "Chelmsford", "Basildon", "Southend-on-Sea",
    "Clacton-on-Sea", "Harlow", "Braintree", "Witham", "Maldon",
    "Brentwood", "Grays", "Tilbury", "Romford", "Cambridge",
    "Peterborough", "Huntingdon", "St Neots", "Ely", "Wisbech",
    "March", "Newmarket", "Bury St Edmunds", "Sudbury", "Haverhill",
    "Felixstowe", "Lowestoft", "Norwich", "Great Yarmouth",
    "Kings Lynn", "Dereham", "Fakenham", "Thetford", "Attleborough",
    "Cromer", "Sheringham",

    # ─── West Midlands ──────────────────────────────────────────
    "Birmingham", "Wolverhampton", "Walsall", "West Bromwich",
    "Dudley", "Stourbridge", "Halesowen", "Sandwell", "Solihull",
    "Tamworth", "Coventry", "Warwick", "Leamington Spa", "Rugby",
    "Nuneaton", "Bedworth", "Atherstone", "Stratford-upon-Avon",
    "Redditch", "Bromsgrove", "Kidderminster", "Worcester",
    "Evesham", "Malvern", "Droitwich", "Hereford", "Leominster",
    "Ross-on-Wye", "Ledbury", "Shrewsbury", "Telford", "Oswestry",
    "Ludlow", "Whitchurch", "Market Drayton", "Bridgnorth",
    "Stafford", "Stoke-on-Trent", "Newcastle-under-Lyme",
    "Burton upon Trent", "Cannock", "Rugeley", "Lichfield",

    # ─── East Midlands ──────────────────────────────────────────
    "Nottingham", "Derby", "Leicester", "Loughborough", "Melton Mowbray",
    "Hinckley", "Coalville", "Market Harborough", "Oakham",
    "Lincoln", "Boston", "Grimsby", "Scunthorpe", "Gainsborough",
    "Grantham", "Stamford", "Spalding", "Skegness", "Louth",
    "Sleaford", "Mansfield", "Worksop", "Newark-on-Trent",
    "Chesterfield", "Ilkeston", "Long Eaton", "Ripley",
    "Alfreton", "Matlock", "Buxton", "Glossop",
    "Kettering", "Corby", "Wellingborough", "Rushden",
    "Northampton", "Daventry", "Brackley", "Towcester",

    # ─── Yorkshire & The Humber ─────────────────────────────────
    "Leeds", "Sheffield", "Bradford", "Wakefield", "Huddersfield",
    "Halifax", "Dewsbury", "Batley", "Keighley", "Shipley",
    "Ilkley", "Otley", "Pontefract", "Castleford", "Featherstone",
    "Knottingley", "Hemsworth", "Brighouse", "Elland",
    "Rotherham", "Barnsley", "Doncaster", "Worksop",
    "York", "Harrogate", "Ripon", "Selby", "Thirsk",
    "Malton", "Bridlington", "Scarborough", "Whitby",
    "Hull", "Beverley", "Driffield", "Goole",

    # ─── North West ─────────────────────────────────────────────
    "Manchester", "Salford", "Stockport", "Oldham", "Rochdale",
    "Bury", "Bolton", "Wigan", "Leigh", "Ashton-under-Lyne",
    "Hyde", "Dukinfield", "Denton", "Altrincham", "Sale",
    "Stretford", "Eccles", "Swinton", "Trafford", "Liverpool",
    "Bootle", "Birkenhead", "Wallasey", "Ellesmere Port",
    "Chester", "Crewe", "Nantwich", "Sandbach", "Middlewich",
    "Macclesfield", "Wilmslow", "Knutsford", "Northwich",
    "Warrington", "Widnes", "Runcorn", "St Helens", "Southport",
    "Formby", "Ormskirk", "Skelmersdale", "Preston", "Blackpool",
    "Blackburn", "Burnley", "Accrington", "Darwen", "Chorley",
    "Leyland", "Lancaster", "Morecambe", "Kendal", "Barrow-in-Furness",
    "Ulverston", "Windermere", "Carlisle", "Penrith", "Whitehaven",
    "Workington", "Cockermouth", "Keswick",

    # ─── North East ─────────────────────────────────────────────
    "Newcastle upon Tyne", "Gateshead", "Sunderland", "South Shields",
    "North Shields", "Whitley Bay", "Tynemouth", "Jarrow",
    "Washington", "Houghton-le-Spring", "Hebburn", "Consett",
    "Durham", "Chester-le-Street", "Stanley", "Bishop Auckland",
    "Newton Aycliffe", "Darlington", "Stockton-on-Tees",
    "Middlesbrough", "Redcar", "Hartlepool", "Billingham",
    "Thornaby", "Yarm", "Ingleby Barwick", "Northallerton",
    "Richmond Yorkshire", "Catterick",
    "Alnwick", "Morpeth", "Hexham", "Berwick-upon-Tweed",
    "Blyth", "Cramlington", "Ashington",

    # ─── Wales ──────────────────────────────────────────────────
    "Cardiff", "Swansea", "Newport", "Wrexham", "Barry", "Caerphilly",
    "Merthyr Tydfil", "Pontypool", "Cwmbran", "Bridgend", "Port Talbot",
    "Neath", "Llanelli", "Aberystwyth", "Carmarthen", "Haverfordwest",
    "Milford Haven", "Pembroke", "Tenby", "Llandudno", "Bangor Wales",
    "Caernarfon", "Holyhead", "Rhyl", "Prestatyn", "Colwyn Bay",
    "Denbigh", "Ruthin", "Mold", "Flint", "Connah's Quay",
    "Aberdare", "Treorchy", "Pontypridd", "Llantrisant",
    "Tonypandy", "Abertillery", "Ebbw Vale",

    # ─── Scotland ───────────────────────────────────────────────
    "Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Stirling", "Perth",
    "Inverness", "Ayr", "Kilmarnock", "Irvine", "Paisley",
    "Greenock", "Port Glasgow", "Dumbarton", "Cumbernauld",
    "Falkirk", "Grangemouth", "Alloa", "Dunfermline", "Kirkcaldy",
    "Glenrothes", "St Andrews", "Arbroath", "Montrose", "Forfar",
    "Brechin", "Elgin", "Fraserburgh", "Peterhead", "Oban",
    "Fort William", "Thurso", "Wick", "Kirkwall", "Lerwick",
    "Dumfries", "Stranraer", "Lockerbie", "Annan", "Moffat",
    "Galashiels", "Hawick", "Kelso", "Jedburgh", "Selkirk",
    "Livingston", "Bathgate", "Broxburn", "East Kilbride",
    "Hamilton", "Motherwell", "Wishaw", "Bellshill", "Coatbridge",
    "Airdrie", "Cumbernauld", "Clydebank", "Bearsden", "Milngavie",

    # ─── Northern Ireland ───────────────────────────────────────
    "Belfast", "Derry", "Lisburn", "Newry", "Bangor NI", "Craigavon",
    "Ballymena", "Newtownabbey", "Carrickfergus", "Coleraine",
    "Antrim", "Larne", "Omagh", "Enniskillen", "Strabane",
    "Armagh", "Dungannon", "Cookstown", "Magherafelt",
    "Ballymoney", "Portadown", "Lurgan", "Downpatrick",
    "Newtownards", "Holywood", "Banbridge",

    # ─── Additional South East towns ────────────────────────────
    "Amersham", "Beaconsfield", "Berkhamsted", "Chesham", "Marlow",
    "Princes Risborough", "Thame", "Wendover", "Buckingham", "Olney",
    "Newport Pagnell", "Bletchley", "Stony Stratford", "Winslow",
    "Egham", "Virginia Water", "Cobham", "Weybridge", "Walton-on-Thames",
    "Esher", "Oxted", "Caterham", "Warlingham", "Godalming",
    "Cranleigh", "Haslemere", "Farnham", "Camberley", "Lightwater",
    "Bagshot", "Sandhurst", "Crowthorne", "Ascot", "Sunninghill",
    "Windsor", "Eton", "Maidenhead", "Wooburn Green", "Iver",
    "Uxbridge", "Ruislip", "Northwood", "Pinner", "Rickmansworth",
    "Chorleywood", "Croxley Green", "Kings Langley", "Abbots Langley",
    "Borehamwood", "Elstree", "Potters Bar", "Radlett", "Bushey",
    "Cheshunt", "Waltham Cross", "Hoddesdon", "Ware", "Buntingford",
    "Royston", "Baldock", "Biggleswade", "Sandy", "Flitwick",
    "Ampthill", "Cranfield", "Kempston", "Stotfold", "Shefford",
    "Thetford", "Mildenhall", "Brandon", "Bury", "Stowmarket",
    "Needham Market", "Hadleigh", "Saxmundham", "Aldeburgh",
    "Framlingham", "Southwold", "Leiston", "Woodbridge", "Halesworth",
    "Bungay", "Beccles", "Diss", "Harleston", "Wymondham",
    "Watton", "Swaffham", "East Dereham", "Holt",
    "Aylsham", "North Walsham", "Hunstanton", "Downham Market",
    "Sheringham", "Stalham", "Acle",

    # ─── Additional South West towns ────────────────────────────
    "Tavistock", "Okehampton", "Kingsbridge", "Totnes", "Dartmouth",
    "Ivybridge", "Crediton", "Honiton", "Sidmouth", "Seaton",
    "Ottery St Mary", "Axminster", "Lyme Regis", "Beaminster",
    "Sherborne", "Gillingham Dorset", "Wareham", "Swanage",
    "Ferndown", "Verwood", "Ringwood", "Lymington", "New Milton",
    "Romsey", "Stockbridge", "Alton", "Bordon", "Liphook",
    "Midhurst", "Petworth", "Pulborough", "Storrington",
    "Arundel", "Steyning", "Henfield", "Hassocks", "Lewes",
    "Uckfield", "Crowborough", "Heathfield", "Wadhurst",
    "Battle", "Rye", "Peacehaven", "Saltdean", "Seaford",
    "Newhaven", "Helston", "Hayle", "Saltash", "Liskeard",
    "Wadebridge", "Padstow", "St Ives", "Looe", "Fowey",
    "Torpoint", "Launceston", "Bude",
    "Minehead", "Wellington Somerset", "Crewkerne", "Ilminster",
    "Castle Cary", "Shepton Mallet", "Street", "Wincanton",
    "Midsomer Norton", "Radstock", "Portishead", "Clevedon",
    "Nailsea", "Chew Magna", "Pilning", "Thornbury", "Yate",
    "Chipping Sodbury", "Wotton-under-Edge", "Dursley", "Berkeley",
    "Lydney", "Cinderford", "Coleford", "Chepstow",

    # ─── Additional Midlands towns ──────────────────────────────
    "Kenilworth", "Southam", "Wellesbourne", "Shipston", "Alcester",
    "Studley", "Henley-in-Arden", "Atherstone",
    "Coleshill", "Kingsbury", "Polesworth", "Whitnash",
    "Market Bosworth", "Lutterworth", "Blaby", "Wigston",
    "Oadby", "Countesthorpe", "Broughton Astley", "Earl Shilton",
    "Barwell", "Burbage", "Enderby", "Narborough",
    "Kirby Muxloe", "Anstey", "Syston", "Mountsorrel",
    "Quorn", "Shepshed", "East Leake", "Hathern",
    "Sileby", "Birstall", "Thurmaston",
    "Beeston", "Stapleford", "Hucknall", "Eastwood",
    "Arnold", "Carlton", "Mapperley", "Southwell",
    "Bingham", "Radcliffe", "Cotgrave", "Keyworth",
    "West Bridgford", "Clifton", "Wollaton",
    "Heanor", "Swadlincote", "Ashby-de-la-Zouch",
    "Long Eaton", "Sandiacre", "Borrowash", "Belper",
    "Ripley Derbyshire", "Somercotes", "Alfreton", "Clay Cross",
    "Dronfield", "Bolsover", "Shirebrook", "Clowne", "Mosborough",
    "Eckington", "Killamarsh",

    # ─── Additional North West towns ────────────────────────────
    "Congleton", "Poynton", "Alderley Edge", "Prestbury",
    "Bollington", "Disley", "Goostrey", "Holmes Chapel",
    "Sandbach", "Winsford", "Lymm", "Newton-le-Willows",
    "Haydock", "Ashton-in-Makerfield", "Golborne",
    "Lowton", "Tyldesley", "Astley", "Walkden", "Farnworth",
    "Westhoughton", "Horwich", "Adlington", "Coppull",
    "Euxton", "Clayton-le-Woods", "Penwortham", "Lostock Hall",
    "Walton-le-Dale", "Bamber Bridge", "Longton Lancashire",
    "Kirkham", "Thornton Cleveleys", "Poulton-le-Fylde",
    "Fleetwood", "Garstang", "Kendal", "Windermere",
    "Ambleside", "Grange-over-Sands", "Milnthorpe",
    "Kirkby Lonsdale", "Sedbergh", "Dalton-in-Furness",
    "Millom", "Egremont", "Seascale", "Maryport",
    "Wigton", "Brampton", "Alston", "Appleby",

    # ─── Additional Yorkshire towns ─────────────────────────────
    "Pickering", "Helmsley", "Hornsea", "Withernsea",
    "Howden", "Market Weighton", "Pocklington", "Stamford Bridge",
    "Tadcaster", "Wetherby", "Boston Spa", "Harrogate",
    "Ripon", "Knaresborough", "Pateley Bridge", "Skipton",
    "Settle", "Hawes", "Leyburn", "Bedale", "Masham",
    "Stokesley", "Great Ayton", "Yarm", "Guisborough",
    "Skelton-in-Cleveland", "Loftus", "Staithes",
    "Whitby", "Scarborough", "Filey", "Bridlington",
    "Driffield", "Goole", "Rawcliffe", "Snaith",
    "Swinton Yorkshire", "Wath upon Dearne", "Mexborough",
    "Conisbrough", "Armthorpe", "Thorne", "Hatfield",
    "Stainforth", "Bentley", "Adwick", "Askern",

    # ─── Additional North East towns ────────────────────────────
    "Seaham", "Peterlee", "Easington", "Horden", "Blackhall",
    "Shotton", "Thornley", "Wheatley Hill", "Ferryhill",
    "Spennymoor", "Willington", "Crook", "Tow Law",
    "Stanhope", "Wolsingham", "Bishop Auckland", "Shildon",
    "Aycliffe", "Sedgefield", "Barnard Castle", "Teesdale",
    "Guisborough", "Skinningrove",
    "Prudhoe", "Haltwhistle", "Haydon Bridge", "Corbridge",
    "Rothbury", "Wooler", "Amble",
    "Seahouses", "Bamburgh", "Seaton Sluice",

    # ─── Additional Wales towns ─────────────────────────────────
    "Monmouth", "Abergavenny", "Brecon", "Crickhowell",
    "Usk", "Chepstow", "Caldicot", "Raglan",
    "Cowbridge", "Penarth", "Dinas Powys", "Barry",
    "Porthcawl", "Maesteg", "Pontycymer", "Ogmore Vale",
    "Tonyrefail", "Ystrad Mynach", "Bedwas", "Senghenydd",
    "Llantwit Major", "Cowbridge", "Rhoose",
    "Llandovery", "Llandeilo", "Ammanford", "Cross Hands",
    "Pontarddulais", "Gorseinon", "Mumbles",
    "Kidwelly", "Burry Port", "Llanelli", "Llanybydder",
    "Lampeter", "Tregaron", "New Quay", "Cardigan",
    "Newcastle Emlyn", "Fishguard", "St Davids", "Narberth",
    "Kilgetty", "Saundersfoot", "Penally",
    "Aberaeron", "Borth", "Machynlleth", "Aberdyfi",
    "Tywyn", "Dolgellau", "Barmouth", "Harlech", "Porthmadog",
    "Criccieth", "Pwllheli", "Abersoch", "Nefyn", "Beaumaris",
    "Menai Bridge", "Llangefni", "Amlwch", "Ruthin",
    "Corwen", "Bala", "Llanrwst", "Conwy", "Penmaenmawr",
    "Abergele", "Kinmel Bay", "Towyn", "Rhuddlan",

    # ─── Additional Scotland towns ──────────────────────────────
    "Bo'ness", "Linlithgow", "Whitburn", "Armadale",
    "Winchburgh", "South Queensferry", "Dalkeith", "Penicuik",
    "Bonnyrigg", "Loanhead", "Gorebridge", "Roslin",
    "Haddington", "Tranent", "Prestonpans", "Musselburgh",
    "North Berwick", "Dunbar", "East Linton",
    "Peebles", "Innerleithen", "Biggar", "Lanark",
    "Carluke", "Larkhall", "Strathaven", "Lesmahagow",
    "Douglas", "Newmilns", "Galston", "Cumnock",
    "Auchinleck", "Mauchline", "Catrine", "Dalmellington",
    "Maybole", "Girvan", "Ballantrae", "Turnberry",
    "Troon", "Prestwick", "Saltcoats", "Ardrossan",
    "Kilwinning", "Stevenston", "Beith", "Dalry",
    "Largs", "Millport", "Gourock", "Kilmacolm",
    "Bishopton", "Johnstone", "Erskine", "Renfrew",
    "Bearsden", "Milngavie", "Kirkintilloch", "Lenzie",
    "Bishopbriggs", "Cambuslang", "Rutherglen", "Uddingston",
    "Blantyre", "Strathblane", "Balfron",
    "Callander", "Doune", "Crieff", "Comrie", "Auchterarder",
    "Blairgowrie", "Pitlochry", "Aberfeldy", "Killin",
    "Dunblane", "Bridge of Allan", "Alva", "Tillicoultry",
    "Dollar", "Kincardine", "Clackmannan",
    "Kinross", "Milnathort", "Scotlandwell",
    "Aberdour", "Burntisland", "Kinghorn", "Buckhaven",
    "Leven", "Anstruther", "Pittenweem", "Crail",
    "Cupar", "Ladybank", "Auchtermuchty", "Newburgh Fife",
    "Tayport", "Newport on Tay", "Wormit", "Invergowrie",
    "Carnoustie", "Monifieth", "Broughty Ferry",
    "Kirriemuir", "Edzell", "Laurencekirk", "Stonehaven",
    "Inverurie", "Banchory", "Aboyne", "Ballater",
    "Huntly", "Keith", "Buckie", "Banff", "Macduff",
    "Turriff", "Alford", "Kintore",
    "Nairn", "Forres", "Grantown-on-Spey", "Aviemore",
    "Kingussie", "Newtonmore", "Dingwall", "Ullapool",
    "Kyle of Lochalsh", "Portree",
    "Gairloch", "Lochinver", "Durness",
    "Dornoch", "Golspie", "Brora", "Helmsdale",

    # ─── Additional NI towns ────────────────────────────────────
    "Carrickfergus", "Larne", "Ballyclare", "Glengormley",
    "Whitehead", "Islandmagee", "Kilroot", "Greenisland",
    "Jordanstown", "Whiteabbey", "Rathcoole",
    "Dromore", "Hillsborough", "Moira", "Glenavy",
    "Crumlin", "Antrim", "Templepatrick", "Ballyclare",
    "Broughshane", "Cullybackey", "Portglenone",
    "Rasharkin", "Kilrea", "Garvagh", "Coleraine",
    "Portstewart", "Portrush", "Ballycastle", "Bushmills",
    "Limavady", "Dungiven", "Claudy", "Strabane",
    "Castlederg", "Newtownstewart", "Sion Mills",
    "Donaghmore", "Coagh", "Ballyronan",
    "Maghera", "Bellaghy", "Draperstown", "Magherafelt",
    "Moneymore", "Cookstown", "Pomeroy", "Carrickmore",
    "Gortin", "Fintona", "Dromore Tyrone", "Fivemiletown",
    "Clogher", "Augher", "Aughnacloy", "Ballygawley",
    "Caledon", "Moy", "Benburb", "Tandragee", "Markethill",
    "Richhill", "Loughgall", "Keady", "Newtownhamilton",
    "Crossmaglen", "Forkhill", "Bessbrook", "Rostrevor",
    "Warrenpoint", "Kilkeel", "Annalong", "Newcastle County Down",
    "Castlewellan", "Dundrum", "Ballynahinch", "Saintfield",
    "Crossgar", "Killyleagh", "Portaferry", "Ardglass",
    "Comber", "Millisle", "Donaghadee", "Groomsport",
    "Helen's Bay", "Cultra", "Holywood",

    # ─── Additional Greater London suburbs ──────────────────────
    "Acton", "Alperton", "Balham", "Barnes", "Battersea",
    "Bayswater", "Belsize Park", "Bermondsey", "Bethnal Green",
    "Blackheath", "Bloomsbury", "Brixton", "Brockley",
    "Camberwell", "Canary Wharf", "Catford", "Chelsea",
    "Chingford", "Chiswick", "Clapham", "Clerkenwell",
    "Crouch End", "Crystal Palace", "Dalston", "Deptford",
    "Dulwich", "East Ham", "Edmonton", "Euston", "Finchley",
    "Finsbury Park", "Forest Gate", "Forest Hill", "Fulham",
    "Golders Green", "Hampstead", "Highgate", "Holloway",
    "Homerton", "Hornsey", "Ilford", "Kensal Green", "Kentish Town",
    "Kilburn", "Kings Cross", "Kingsbury", "Ladbroke Grove",
    "Leytonstone", "Manor Park", "Marylebone", "Mayfair",
    "Mile End", "Mill Hill", "Muswell Hill", "New Cross",
    "North Finchley", "Notting Hill", "Oval", "Paddington",
    "Peckham", "Pimlico", "Plaistow", "Poplar", "Putney",
    "Queens Park", "Rotherhithe", "Shepherds Bush", "Shoreditch",
    "Soho", "Stamford Hill", "Stockwell", "Stoke Newington",
    "Stratford", "Streatham", "Sydenham", "Teddington",
    "Tooting", "Tottenham", "Twickenham", "Upton Park",
    "Vauxhall", "Victoria", "Walthamstow", "Wanstead",
    "Wembley", "Whitechapel", "Willesden", "Wimbledon",
    "Woodford", "Woolwich",
]


def unique_towns() -> list[str]:
    """Return deduplicated town list preserving order."""
    seen: set[str] = set()
    out: list[str] = []
    for t in UK_TOWNS:
        k = t.lower()
        if k in seen:
            continue
        seen.add(k)
        out.append(t)
    return out
