
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { usePortfolioData } from "./usePortfolioData";
import { PortfolioEntry, PortfolioCategory } from "@/types/portfolio";
import { TimeEntry } from "@/types/time-tracking";

export interface UniversalActivityData {
  title: string;
  description: string;
  activityType: 'time-entry' | 'study-session' | 'quiz' | 'course' | 'assessment' | 'evidence' | 'manual';
  timeSpent: number; // in minutes
  date: string;
  skills?: string[];
  sourceData?: any; // Original data from the source activity
  autoGenerated?: boolean;
}

export const useUniversalPortfolio = () => {
  const { toast } = useToast();
  const { addEntry, categories } = usePortfolioData();
  const [isProcessing, setIsProcessing] = useState(false);

  // Smart category assignment based on activity type and content
  const assignSmartCategory = (activityData: UniversalActivityData): PortfolioCategory => {
    const { title, description, activityType, skills = [] } = activityData;
    const content = `${title} ${description}`.toLowerCase();

    // Health & Safety keywords
    if (content.includes('safety') || content.includes('ppe') || content.includes('hazard') || 
        content.includes('risk') || content.includes('isolation') || content.includes('emergency')) {
      return categories.find(cat => cat.id === 'health-safety') || categories[0];
    }

    // Testing & Inspection keywords
    if (content.includes('test') || content.includes('inspection') || content.includes('measurement') ||
        content.includes('certification') || content.includes('verify') || content.includes('bs7671')) {
      return categories.find(cat => cat.id === 'testing-inspection') || categories[0];
    }

    // Customer Service keywords
    if (content.includes('customer') || content.includes('client') || content.includes('communication') ||
        content.includes('presentation') || content.includes('meeting')) {
      return categories.find(cat => cat.id === 'customer-service') || categories[0];
    }

    // Professional Development keywords
    if (content.includes('study') || content.includes('course') || content.includes('learning') ||
        content.includes('development') || content.includes('training') || activityType === 'study-session') {
      return categories.find(cat => cat.id === 'professional-development') || categories[0];
    }

    // Default to Practical Skills
    return categories.find(cat => cat.id === 'practical-skills') || categories[0];
  };

  // Generate smart skills based on content analysis
  const generateSmartSkills = (activityData: UniversalActivityData): string[] => {
    const { title, description, skills = [], activityType } = activityData;
    const content = `${title} ${description}`.toLowerCase();
    const detectedSkills: string[] = [...skills];

    // Technical skills detection
    const skillMappings = {
      'wiring': ['Cable Installation', 'Circuit Design'],
      'installation': ['Installation Techniques', 'Project Planning'],
      'testing': ['Testing & Measurement', 'Compliance Verification'],
      'safety': ['Safety Procedures', 'Risk Assessment'],
      'troubleshooting': ['Problem Solving', 'Fault Finding'],
      'customer': ['Customer Service', 'Communication'],
      'documentation': ['Technical Documentation', 'Report Writing'],
      'inspection': ['Inspection Procedures', 'Quality Control'],
      'maintenance': ['Preventive Maintenance', 'Equipment Care'],
      'compliance': ['Regulatory Compliance', 'Standards Knowledge']
    };

    Object.entries(skillMappings).forEach(([keyword, relatedSkills]) => {
      if (content.includes(keyword)) {
        relatedSkills.forEach(skill => {
          if (!detectedSkills.includes(skill)) {
            detectedSkills.push(skill);
          }
        });
      }
    });

    // Activity type specific skills
    if (activityType === 'quiz') {
      detectedSkills.push('Knowledge Assessment', 'Self-Evaluation');
    } else if (activityType === 'study-session') {
      detectedSkills.push('Self-Directed Learning', 'Knowledge Acquisition');
    }

    return detectedSkills.slice(0, 8); // Limit to 8 skills
  };

  // Generate learning outcomes based on activity
  const generateLearningOutcomes = (activityData: UniversalActivityData): string[] => {
    const { activityType, title } = activityData;
    const outcomes: string[] = [];

    switch (activityType) {
      case 'study-session':
        outcomes.push(`Enhanced theoretical knowledge through ${title}`);
        outcomes.push('Improved understanding of electrical principles');
        break;
      case 'quiz':
        outcomes.push('Demonstrated knowledge retention and application');
        outcomes.push('Identified areas for further development');
        break;
      case 'time-entry':
        outcomes.push('Applied practical skills in real-world context');
        outcomes.push('Gained hands-on experience');
        break;
      case 'assessment':
        outcomes.push('Met competency requirements');
        outcomes.push('Demonstrated professional capability');
        break;
      default:
        outcomes.push('Continued professional development');
        outcomes.push('Enhanced technical competency');
    }

    return outcomes;
  };

  // Generate assessment criteria
  const generateAssessmentCriteria = (activityData: UniversalActivityData): string[] => {
    const category = assignSmartCategory(activityData);
    const criteria: string[] = [];

    switch (category.id) {
      case 'practical-skills':
        criteria.push('Demonstrated safe working practices');
        criteria.push('Applied appropriate techniques and methods');
        criteria.push('Completed work to industry standards');
        break;
      case 'health-safety':
        criteria.push('Identified and assessed risks appropriately');
        criteria.push('Applied safety procedures correctly');
        criteria.push('Used PPE effectively');
        break;
      case 'testing-inspection':
        criteria.push('Performed tests according to regulations');
        criteria.push('Interpreted results accurately');
        criteria.push('Documented findings professionally');
        break;
      default:
        criteria.push('Demonstrated competency in required areas');
        criteria.push('Applied knowledge effectively');
    }

    return criteria;
  };

  const createUniversalPortfolioEntry = async (activityData: UniversalActivityData) => {
    setIsProcessing(true);
    
    try {
      const smartCategory = assignSmartCategory(activityData);
      const smartSkills = generateSmartSkills(activityData);
      const learningOutcomes = generateLearningOutcomes(activityData);
      const assessmentCriteria = generateAssessmentCriteria(activityData);

      // Generate reflection based on activity type
      let reflection = '';
      if (activityData.activityType === 'quiz') {
        reflection = `Completed ${activityData.title} which helped reinforce my understanding of key concepts. This assessment activity contributed to my ongoing learning and development.`;
      } else if (activityData.activityType === 'study-session') {
        reflection = `Engaged in focused study session on ${activityData.title}. This theoretical learning will support my practical application in the workplace.`;
      } else {
        reflection = `Completed ${activityData.title} as part of my off-the-job training. This activity has contributed to my professional development and skill enhancement.`;
      }

      const portfolioEntry: Omit<PortfolioEntry, 'id' | 'dateCreated'> = {
        title: activityData.title,
        description: activityData.description,
        category: smartCategory,
        skills: smartSkills,
        reflection,
        dateCompleted: activityData.date,
        evidenceFiles: [],
        tags: [activityData.activityType, 'auto-generated'],
        assessmentCriteria,
        learningOutcomes,
        supervisorFeedback: '',
        selfAssessment: 3, // Default rating
        status: 'completed',
        timeSpent: activityData.timeSpent,
        awardingBodyStandards: []
      };

      const entryId = addEntry(portfolioEntry);
      
      if (!activityData.autoGenerated) {
        toast({
          title: "Added to Portfolio",
          description: `"${activityData.title}" has been automatically added to your portfolio.`
        });
      }

      return entryId;
    } catch (error) {
      console.error('Error creating universal portfolio entry:', error);
      toast({
        title: "Error",
        description: "Failed to add entry to portfolio. Please try again.",
        variant: "destructive"
      });
      throw error;
    } finally {
      setIsProcessing(false);
    }
  };

  // Convert time entry to universal format
  const convertTimeEntryToUniversal = (timeEntry: TimeEntry): UniversalActivityData => {
    return {
      title: timeEntry.activity,
      description: timeEntry.notes || 'Off-the-job training activity',
      activityType: timeEntry.isQuiz ? 'quiz' : 'time-entry',
      timeSpent: timeEntry.duration,
      date: timeEntry.date,
      sourceData: timeEntry
    };
  };

  // Batch process multiple activities
  const batchCreatePortfolioEntries = async (activities: UniversalActivityData[]) => {
    const results = [];
    for (const activity of activities) {
      try {
        const entryId = await createUniversalPortfolioEntry({ ...activity, autoGenerated: true });
        results.push({ success: true, entryId, activity });
      } catch (error) {
        results.push({ success: false, error, activity });
      }
    }
    return results;
  };

  return {
    createUniversalPortfolioEntry,
    convertTimeEntryToUniversal,
    batchCreatePortfolioEntries,
    isProcessing,
    categories,
    assignSmartCategory,
    generateSmartSkills
  };
};
