import { useEffect } from 'react';
import { 
  MobileAccordion,
  MobileAccordionItem,
  MobileAccordionTrigger,
  MobileAccordionContent
} from '@/components/ui/mobile-accordion';
import { Card, CardContent } from '@/components/ui/card';
import { Wrench, AlertTriangle, Cable, Zap } from 'lucide-react';

interface MobileInstallationGuidanceSectionProps {
  circuit: any;
}

export const MobileInstallationGuidanceSection = ({ circuit }: MobileInstallationGuidanceSectionProps) => {
  // ✅ DEBUG: Log what data is received from the backend
  useEffect(() => {
    console.log('🔍 Installation Guidance Debug:', {
      hasInstallationGuidance: !!circuit.installationGuidance,
      cableRoutingCount: circuit.installationGuidance?.cableRouting?.length || 0,
      terminationCount: circuit.installationGuidance?.terminationRequirements?.length || 0,
      safetyCount: circuit.installationGuidance?.safetyConsiderations?.length || 0,
      testingCount: circuit.testingRequirements?.tests?.length || 0,
      fullCircuitData: circuit
    });
  }, [circuit]);
  // ✅ Extract installation guidance from Installation Method Agent
  const installationGuidance = circuit.installationGuidance || {};
  
  // Check if we have any installation guidance data
  const hasData = 
    (installationGuidance.safetyConsiderations?.length > 0) ||
    (installationGuidance.cableRouting?.length > 0) ||
    (installationGuidance.terminationRequirements?.length > 0);
  
  // If no data available yet, show placeholder
  if (!hasData) {
    return (
      <Card className="bg-elec-dark/60 border-elec-yellow/20">
        <CardContent className="p-4 text-center text-sm text-white/70">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Wrench className="h-4 w-4 text-elec-yellow" />
            <span className="font-semibold text-white/90">Installation Guidance</span>
          </div>
          Installation guidance is being generated by the Installation Method Agent.
          <br />
          This data will be available once the parallel circuit design process completes.
        </CardContent>
      </Card>
    );
  }

  // Extract structured data from Installation Method Agent
  // Handle both new structured format and legacy string format
  const safetyConsiderations = Array.isArray(installationGuidance.safetyConsiderations) 
    ? installationGuidance.safetyConsiderations 
    : (installationGuidance.safetyNotes 
        ? (Array.isArray(installationGuidance.safetyNotes) 
            ? installationGuidance.safetyNotes 
            : [installationGuidance.safetyNotes])
        : []);
        
  const cableRouting = Array.isArray(installationGuidance.cableRouting) 
    ? installationGuidance.cableRouting 
    : [];
    
  const terminationRequirements = Array.isArray(installationGuidance.terminationRequirements) 
    ? installationGuidance.terminationRequirements 
    : (installationGuidance.terminationAdvice 
        ? (Array.isArray(installationGuidance.terminationAdvice) 
            ? installationGuidance.terminationAdvice 
            : [installationGuidance.terminationAdvice])
        : []);

  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold text-elec-light px-1 flex items-center gap-2">
        <Wrench className="h-4 w-4 text-elec-yellow" />
        Installation Guidance
      </h3>

      <MobileAccordion type="multiple" className="space-y-2">
        {/* Safety Considerations */}
        <MobileAccordionItem 
          value="safety"
          className="border-l-4 border-red-500/50 rounded-lg overflow-hidden"
        >
          <MobileAccordionTrigger
            icon={<AlertTriangle className="h-5 w-5 text-red-400" />}
            className="bg-elec-gray/50 hover:bg-elec-gray/70"
          >
            <span className="text-sm font-medium">Safety Considerations</span>
          </MobileAccordionTrigger>
          <MobileAccordionContent>
            <div className="p-4 bg-elec-dark/60 border-t border-elec-yellow/10">
              <ul className="space-y-2">
                {safetyConsiderations.map((item: any, idx: number) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-white/90">
                    <AlertTriangle className="h-4 w-4 text-red-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <p>{typeof item === 'string' ? item : item.consideration}</p>
                      {item.bsReference && (
                        <p className="text-xs text-blue-400 mt-1">BS 7671: {item.bsReference}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </MobileAccordionContent>
        </MobileAccordionItem>

        {/* Cable Routing */}
        <MobileAccordionItem 
          value="routing"
          className="border-l-4 border-blue-500/50 rounded-lg overflow-hidden"
        >
          <MobileAccordionTrigger
            icon={<Cable className="h-5 w-5 text-blue-400" />}
            className="bg-elec-gray/50 hover:bg-elec-gray/70"
          >
            <span className="text-sm font-medium">Cable Routing</span>
          </MobileAccordionTrigger>
          <MobileAccordionContent>
            <div className="p-4 bg-elec-dark/60 border-t border-elec-yellow/10">
              <ul className="space-y-2">
                {cableRouting.map((item: any, idx: number) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-white/90">
                    <Cable className="h-4 w-4 text-blue-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <p>{typeof item === 'string' ? item : item.step}</p>
                      {item.method && <p className="text-xs text-white/60 mt-1">Method: {item.method}</p>}
                      {item.bsReference && <p className="text-xs text-blue-400 mt-1">BS 7671: {item.bsReference}</p>}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </MobileAccordionContent>
        </MobileAccordionItem>

        {/* Termination Requirements */}
        <MobileAccordionItem 
          value="termination"
          className="border-l-4 border-green-500/50 rounded-lg overflow-hidden"
        >
          <MobileAccordionTrigger
            icon={<Zap className="h-5 w-5 text-green-400" />}
            className="bg-elec-gray/50 hover:bg-elec-gray/70"
          >
            <span className="text-sm font-medium">Termination Requirements</span>
          </MobileAccordionTrigger>
          <MobileAccordionContent>
            <div className="p-4 bg-elec-dark/60 border-t border-elec-yellow/10">
              <ul className="space-y-2">
                {terminationRequirements.map((item: any, idx: number) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-white/90">
                    <Zap className="h-4 w-4 text-green-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <p className="font-medium">{typeof item === 'string' ? item : item.location}</p>
                      {item.procedure && <p className="text-sm mt-1">{item.procedure}</p>}
                      {item.torqueSettings && <p className="text-xs text-white/60 mt-1">Torque: {item.torqueSettings}</p>}
                      {item.bsReference && <p className="text-xs text-blue-400 mt-1">BS 7671: {item.bsReference}</p>}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </MobileAccordionContent>
        </MobileAccordionItem>
      </MobileAccordion>
    </div>
  );
};
