
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, CheckCircle, AlertTriangle, Clock, FileText, Award, Zap, Bot } from "lucide-react";

const ComplianceTrackingTab = () => {
  const complianceAreas = [
    {
      area: "20% Off-the-Job Training",
      progress: 78,
      status: "on-track",
      hoursCompleted: 195,
      hoursRequired: 250,
      deadline: "2024-08-15",
      autoTracked: true
    },
    {
      area: "Portfolio Documentation",
      progress: 85,
      status: "ahead",
      completed: 17,
      required: 20,
      deadline: "2024-07-01",
      autoTracked: false
    },
    {
      area: "Skills Assessment",
      progress: 60,
      status: "needs-attention",
      completed: 6,
      required: 10,
      deadline: "2024-06-30",
      autoTracked: false
    },
    {
      area: "Professional Standards",
      progress: 92,
      status: "excellent",
      completed: 23,
      required: 25,
      deadline: "2024-09-01",
      autoTracked: true
    }
  ];

  const automatedAlerts = [
    {
      type: "warning",
      title: "Skills Assessment Behind Schedule",
      message: "Only 4 assessments completed this month. Recommend scheduling 2 more to stay on track.",
      action: "Schedule Now",
      automated: true
    },
    {
      type: "success",
      title: "Training Hours Auto-Logged",
      message: "18.5 hours automatically tracked this week from your learning activities.",
      action: "Review Details",
      automated: true
    },
    {
      type: "info",
      title: "Portfolio Review Due",
      message: "Your mentor portfolio review is scheduled for next week. Ensure all entries are complete.",
      action: "Prepare Portfolio",
      automated: false
    }
  ];

  const complianceReports = [
    {
      title: "Monthly Compliance Summary",
      date: "March 2024",
      score: 87,
      areas: ["Training Hours", "Portfolio", "Assessments"],
      autoGenerated: true
    },
    {
      title: "Quarterly Progress Review",
      date: "Q1 2024",
      score: 84,
      areas: ["Overall Progress", "Skills Development", "Standards"],
      autoGenerated: true
    },
    {
      title: "Annual Assessment Preparation",
      date: "2024 Prep",
      score: 79,
      areas: ["Readiness", "Knowledge Gaps", "Action Plan"],
      autoGenerated: true
    }
  ];

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "excellent":
        return <Badge className="bg-green-600 text-white">Excellent</Badge>;
      case "ahead":
        return <Badge className="bg-blue-600 text-white">Ahead</Badge>;
      case "on-track":
        return <Badge className="bg-green-600 text-white">On Track</Badge>;
      case "needs-attention":
        return <Badge className="bg-orange-600 text-white">Needs Attention</Badge>;
      default:
        return <Badge>Unknown</Badge>;
    }
  };

  const getAlertIcon = (type: string) => {
    switch (type) {
      case "warning":
        return <AlertTriangle className="h-4 w-4 text-orange-500" />;
      case "success":
        return <CheckCircle className="h-4 w-4 text-green-500" />;
      case "info":
        return <Clock className="h-4 w-4 text-blue-500" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Overall Compliance</CardTitle>
            <Shield className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-500">87%</div>
            <p className="text-xs text-muted-foreground">
              All areas tracked
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Auto-Tracking</CardTitle>
            <Bot className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-purple-500">78%</div>
            <p className="text-xs text-muted-foreground">
              Automated monitoring
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Reports Generated</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-500">12</div>
            <p className="text-xs text-muted-foreground">
              This month
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Risk Level</CardTitle>
            <Award className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-500">Low</div>
            <p className="text-xs text-muted-foreground">
              Compliance risk
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5" />
              Compliance Areas Tracking
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {complianceAreas.map((area, index) => (
                <div key={index} className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{area.area}</span>
                      {area.autoTracked && (
                        <Badge variant="outline" className="text-xs">
                          <Bot className="h-3 w-3 mr-1" />
                          Auto
                        </Badge>
                      )}
                    </div>
                    {getStatusBadge(area.status)}
                  </div>
                  
                  <Progress value={area.progress} className="h-2" />
                  
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">Progress: </span>
                      {area.hoursCompleted || area.completed}/{area.hoursRequired || area.required}
                      {area.hoursCompleted ? ' hours' : ' items'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Deadline: </span>
                      <span className="text-elec-yellow">{area.deadline}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="h-5 w-5" />
              Automated Alerts & Monitoring
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {automatedAlerts.map((alert, index) => (
                <div key={index} className="border rounded-lg p-4">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                      {getAlertIcon(alert.type)}
                      <h4 className="font-medium">{alert.title}</h4>
                    </div>
                    <div className="flex items-center gap-2">
                      {alert.automated && (
                        <Badge className="bg-purple-600 text-white text-xs">
                          <Bot className="h-3 w-3 mr-1" />
                          Auto
                        </Badge>
                      )}
                    </div>
                  </div>
                  
                  <p className="text-sm text-muted-foreground mb-3">{alert.message}</p>
                  
                  <Button size="sm" variant="outline" className="w-full">
                    {alert.action}
                  </Button>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Automated Compliance Reports
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {complianceReports.map((report, index) => (
              <div key={index} className="border rounded-lg p-4">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="font-medium">{report.title}</h4>
                  {report.autoGenerated && (
                    <Badge className="bg-green-600 text-white text-xs">
                      <Bot className="h-3 w-3 mr-1" />
                      Auto
                    </Badge>
                  )}
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Score:</span>
                    <span className="text-lg font-bold text-green-500">{report.score}%</span>
                  </div>
                  
                  <div className="text-sm text-muted-foreground">
                    Date: {report.date}
                  </div>
                  
                  <div className="flex flex-wrap gap-1 mt-2">
                    {report.areas.map((area, areaIndex) => (
                      <Badge key={areaIndex} variant="secondary" className="text-xs">
                        {area}
                      </Badge>
                    ))}
                  </div>
                </div>
                
                <Button size="sm" variant="outline" className="w-full mt-3">
                  <FileText className="h-4 w-4 mr-2" />
                  View Report
                </Button>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ComplianceTrackingTab;
