-- F1 / ELE-942 — slide-deck companion to college_lesson_plans.
-- Slide deck is a separate JSONB so we can regenerate without losing the
-- plan content, and so the lesson PDF / presenter / register flows stay
-- decoupled from the slide deck.
ALTER TABLE public.college_lesson_plans
  ADD COLUMN IF NOT EXISTS slide_deck_json jsonb,
  ADD COLUMN IF NOT EXISTS slide_deck_generated_at timestamptz;

COMMENT ON COLUMN public.college_lesson_plans.slide_deck_json IS
  'Tutor-ready slide deck generated from the lesson plan content. Schema is { generated_at, slides[] } where each slide carries a kind tag plus structured fields. Edited per-slide by the tutor in the slide viewer.';
COMMENT ON COLUMN public.college_lesson_plans.slide_deck_generated_at IS
  'When the slide deck was last (re)generated by ai-generate-slide-deck.';
