-- Schema labels for the Employer Hub and everything it touches (Andrew, 6 Oct 2026).
-- Every table carries a tag at the start of its comment so its role is obvious in any tool:
--   [EMPLOYER HUB]                          only a firm has this
--   [EMPLOYER HUB → WORKER TOOLS]           firm data its workers also read/write
--   [SHARED: ELECTRICAL HUB + EMPLOYER HUB] one table both hubs use (one record, owned by the account)
--   [ELEC-ID — OWNED BY THE ELECTRICIAN]    the person's own record; firms only read it
--   [BRIDGE: EMPLOYER ↔ COLLEGE]            links firms and colleges
--   [LEGACY — DO NOT USE]                   kept for rollback only; do not build on it
--   [INTERNAL — NOT THE EMPLOYER HUB]       Elec-Mate's own operations data
--   [AUDIT LOG]                             one-off change logs (rollback sources)
-- Query them: select * from public.schema_map order by tag, table_name;

comment on table public.app_settings is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] App-wide settings key/values. Scope: global. Used by: Both hubs.';
comment on table public.briefing_attendees is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Who attended/signed a briefing (roster member or named guest). Scope: briefing_id → briefings; employee_id → roster or guest_name. Used by: Briefing viewer, public sign page. Rule: Signing as a roster member with an account will require being signed in (ELE-1949, on release checklist).';
comment on table public.briefing_signing_tokens is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Public signing links for a briefing. Scope: briefing_id → briefings. Used by: Public /briefing-sign/:token. Rule: expires_at enforced once 20261006129000 ships.';
comment on table public.briefings is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Toolbox talks / site briefings (employer briefings store). Scope: user_id = the firm. Used by: Employer Hub Briefings, public /briefing-sign/:token.';
comment on table public.business_compliance is '[LEGACY — DO NOT USE] Old business-compliance score source (0 rows; unmounted dashboard). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: nothing live. Rule: Replaced by compliance_documents + the evidence-based score (ELE-1985).';
comment on table public.calendar_events is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Diary entries (Google/Outlook sync). Scope: user_id = account. Used by: Electrical Hub Calendar; Employer Hub diary will mirror into it (ELE-1820).';
comment on table public.client_activities is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Notes/activity log on a customer. Scope: client_id → customers; visible to the whole firm. Used by: Client detail sheet. Rule: FK moved from employer_clients to customers on 6 Oct.';
comment on table public.client_portal_links is '[EMPLOYER HUB] Customer portal links per job, with what the customer may see. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Client portal, public /portal/:token.';
comment on table public.client_reviews is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Reviews/feedback captured for a customer. Scope: client_id → customers; visible to the whole firm. Used by: Client detail sheet.';
comment on table public.client_tasks is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Follow-up tasks on a customer. Scope: client_id → customers; visible to the whole firm. Used by: Client detail sheet.';
comment on table public.college_otj_entries is '[BRIDGE: EMPLOYER ↔ COLLEGE] Apprentice off-the-job training hours. Workplace attestation (employer) and college verification are SEPARATE statuses on the same row. Scope: student_id = the apprentice''s user id = employer_employees.user_id (the only employer↔college join). Used by: Apprentice Hub OJT, Employer Hub Apprentices, College Hub. Rule: Owned by the College Hub; employer may only attest/send back pending rows (tg_guard_otj_self_edit).';
comment on table public.company_profiles is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Company/business profile per account: name, branding, bank details, Stripe Connect status, quote-page settings, labour rates. Scope: user_id = the account (the firm for an employer). Used by: Every PDF and email, Settings in both hubs, Worker Tools branding.';
comment on table public.competence_requirement_sets is '[EMPLOYER HUB] Requirement sets for the competence matrix (what a job type needs). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Elec-ID competence matrix. Rule: Feeds competence-matched dispatch (ELE-1834).';
comment on table public.compliance_documents is '[EMPLOYER HUB] Company compliance documents: insurance, PAT, calibration, audits (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Employer Hub Compliance. Rule: Renewal reminders to come (ELE-1985).';
comment on table public.contracts is '[EMPLOYER HUB] Contracts a firm adopted and sent for signature. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); employee_id → roster. Used by: Employer Hub Contracts, signature_requests. Rule: Moving under People (ELE-1982).';
comment on table public.customers is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] THE customer book for both hubs (one record per client). Tags ''auto-created-from-quotes'' mark 204 records created on 6 Oct from earlier quotes. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); co-admins read/edit via policy. Used by: Electrical Hub Customers, Employer Hub Clients/Leads, quotes, jobs, certificates. Rule: Never create a separate employer client table — employer_clients is legacy.';
comment on table public.customers_created_20261006 is '[AUDIT LOG] Customers auto-created on 6 Oct 2026 from unlinked quotes (204). Rollback source. Scope: customer_id → customers. Used by: none. Rule: See migration 20261006135000 for rollback SQL.';
comment on table public.elec_id_documents is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Uploaded Elec-ID documents with OCR extraction and confidence scoring. Scope: owner = the electrician. Used by: Elec-ID verification, Admin.';
comment on table public.elec_id_training_requests is '[EMPLOYER HUB] A firm asking a person to complete training. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Elec-ID / Employer Hub.';
comment on table public.employee_holiday_allowances is '[EMPLOYER HUB → WORKER TOOLS] Annual leave allowance per person per year (total/used/pending days). Scope: employee_id → employer_employees; user_id = the firm. Used by: Worker Tools Leave, Employer Hub Leave. Rule: Seeded at 28 days by trigger on first annual request; a set-by-office flag is still to come (ELE-1953).';
comment on table public.employee_qualifications is '[LEGACY — DO NOT USE] Old per-employee qualification store (0 rows; only the unmounted ComplianceDashboard reads it). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: nothing live. Rule: Use employer_elec_id_qualifications.';
comment on table public.employer_admins is '[EMPLOYER HUB] Co-admins of a firm (second managers). Read by my_employer_scope(). Scope: employer_id = the owning profiles.id (the company). Used by: Employer Hub access checks. Rule: No UI yet to add/remove (ELE-1986).';
comment on table public.employer_audit_log is '[EMPLOYER HUB] Audit trail of firm actions (also Employer Mate actions). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Mate activity feed.';
comment on table public.employer_certifications is '[EMPLOYER HUB → WORKER TOOLS] Certifications the firm recorded for a team member (0 rows). Scope: employee_id → employer_employees. Used by: Credentials page, competence matrix (old path). Rule: Being folded into the person''s Elec-ID qualifications (ELE-1950/1954).';
comment on table public.employer_client_messages is '[EMPLOYER HUB] Messages between the firm and a customer on the portal (0 rows). Scope: firm + portal link. Used by: Client portal panel, public portal.';
comment on table public.employer_clients is '[LEGACY — DO NOT USE] Old Employer Hub client list (3 rows, copied into customers on 6 Oct). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: nothing (read by no code since 6 Oct). Rule: Use customers. Kept only for rollback.';
comment on table public.employer_communication_recipients is '[EMPLOYER HUB → WORKER TOOLS] Per-person delivery/read/acknowledgement of a broadcast. Scope: communication → employer_communications; employee_id → roster. Used by: Comms both sides. Rule: Trigger notify_communication pushes to the worker.';
comment on table public.employer_communications is '[EMPLOYER HUB → WORKER TOOLS] Broadcasts from the firm to its team (announcements, safety alerts). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Hub Comms, Worker Tools Comms.';
comment on table public.employer_company_tools is '[EMPLOYER HUB → WORKER TOOLS] Company tools and test instruments with PAT/calibration (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(); assigned_to_employee_id → roster. Used by: Procurement tools tab, Worker Tools My equipment. Rule: Assignment by employee id not wired yet (ELE-2008).';
comment on table public.employer_conversations is '[EMPLOYER HUB] Firm ↔ candidate conversations (vacancies). Scope: firm + electrician. Used by: Vacancies messages.';
comment on table public.employer_elec_id_profiles is '[ELEC-ID — OWNED BY THE ELECTRICIAN] A person''s Elec-ID: number, verification tier/status, talent-pool visibility. The firm reads it; the person owns it. Scope: employee_id → employer_employees (often their own stub row). Used by: Elec-ID settings, Employer Hub Elec-ID/Talent pool, Admin Elec IDs. Rule: available_for_hire is OPT-IN (default false since 6 Oct; opt-ins stamped). is_verified = approved by an Elec-Mate admin (reviewed_by) — do not reset.';
comment on table public.employer_elec_id_qualifications is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Qualifications on a person''s Elec-ID (the real credentials store, 85 rows). Scope: profile_id → employer_elec_id_profiles. Used by: Elec-ID, Employer Hub competence. Rule: Target single store for all credentials/training (ELE-1950).';
comment on table public.employer_elec_id_share_links is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Share links/QR for an Elec-ID card (0 rows). Scope: profile_id → employer_elec_id_profiles. Used by: Elec-ID sharing. Rule: Consent-based sharing (ELE-1928).';
comment on table public.employer_elec_id_skills is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Skills on a person''s Elec-ID. Scope: profile_id → employer_elec_id_profiles. Used by: Elec-ID, talent pool.';
comment on table public.employer_elec_id_training is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Training entries on a person''s Elec-ID (0 rows). Scope: profile_id → employer_elec_id_profiles. Used by: Elec-ID.';
comment on table public.employer_elec_id_work_history is '[ELEC-ID — OWNED BY THE ELECTRICIAN] Work history on a person''s Elec-ID. Scope: profile_id → employer_elec_id_profiles. Used by: Elec-ID, talent pool.';
comment on table public.employer_employees is '[EMPLOYER HUB → WORKER TOOLS] The firm roster: one row per person on a team (employee, apprentice, subcontractor), with rates, role and status. Also holds electricians'' own Elec-ID stub rows (employer_id NULL). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(); user_id = the person''s own account once they join; my_employee_ids() = a worker''s own rows. Used by: Employer Hub People, Worker Tools (every page), Elec-ID. Rule: status=''Archived'' removes access. Rows with employer_id NULL are NOT team members.';
comment on table public.employer_expense_claims is '[EMPLOYER HUB → WORKER TOOLS] Worker expense claims with receipt, approved/rejected/paid by the firm. Scope: employee_id → employer_employees. Used by: Worker Tools Expenses, Employer Hub Expenses, accounts P&L. Rule: Receipts live in storage bucket expense-receipts (going private, ELE-1949).';
comment on table public.employer_goods_receipts is '[EMPLOYER HUB] Deliveries received against purchase orders (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Procurement.';
comment on table public.employer_incidents is '[EMPLOYER HUB → WORKER TOOLS] Safety reports: incidents and near misses (worker or office), with RIDDOR fields. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(); reported_by = roster id (text). Used by: Employer Hub Incidents, Worker Tools Reports. Rule: trg_notify_incident alerts the firm and closes the loop with the reporter.';
comment on table public.employer_invites is '[EMPLOYER HUB] Older shared "team code" invites (link-only; never creates a roster row). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: TeamInviteSheet (not mounted). Rule: Prefer employer_team_invites.';
comment on table public.employer_invoice_access is '[LEGACY — DO NOT USE] Access tokens for employer_invoices (0 rows). Scope: invoice → employer_invoices. Used by: old invoice link function. Rule: Use quotes.public_token / stripe_payment_link_url.';
comment on table public.employer_invoices is '[LEGACY — DO NOT USE] Old Employer Hub invoices table (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: old public /employer-invoice pages, employer_invoices_unified(). Rule: Use quotes (invoice_raised = true).';
comment on table public.employer_job_assignments is '[EMPLOYER HUB → WORKER TOOLS] Who is on which job, with role, dates and office notes. Scope: job_id → employer_jobs; employee_id → roster. Used by: Assign sheet, Worker Tools My Jobs, Overview "Who''s where". Rule: Trigger notify_assignment pushes to the worker.';
comment on table public.employer_job_checklist_items is '[EMPLOYER HUB] Per-job checklist items (0 rows; the editor is not mounted). Scope: job_id → employer_jobs. Used by: Job sheet progress only. Rule: Superseded by pre-start checklists (ELE-1826).';
comment on table public.employer_job_comments is '[EMPLOYER HUB → WORKER TOOLS] Job feed: comments and the crew''s progress notes (comment_type=''progress''). Scope: job_id → employer_jobs. Used by: Job sheet, Progress logs "From the team", Worker Tools Progress notes.';
comment on table public.employer_job_label_assignments is '[EMPLOYER HUB] Labels attached to jobs. Scope: job_id → employer_jobs. Used by: Job board.';
comment on table public.employer_job_labels is '[EMPLOYER HUB] Firm-defined job labels. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Job board.';
comment on table public.employer_job_pack_acknowledgements is '[EMPLOYER HUB → WORKER TOOLS] Who has signed which pack, with signature and time. Scope: job_pack_id → packs; employee_id → roster. Used by: Worker Tools Sign-offs, pack register. Rule: Trigger notify_pack_ack tells both sides.';
comment on table public.employer_job_pack_documents is '[EMPLOYER HUB → WORKER TOOLS] Documents inside a job pack (AI text in description, or a PDF file_url). Scope: job_pack_id → employer_job_packs. Used by: Job pack sheet, Worker Tools Sign-offs.';
comment on table public.employer_job_packs is '[EMPLOYER HUB → WORKER TOOLS] Safety packs for a job (RAMS, method statement, briefing) sent to the crew for sign-off. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Job packs, Worker Tools Sign-offs.';
comment on table public.employer_job_tasks is '[EMPLOYER HUB → WORKER TOOLS] Tasks within a job, assignable to team members. Scope: job_id → employer_jobs. Used by: Job sheet, Worker Tools My Tasks.';
comment on table public.employer_jobs is '[EMPLOYER HUB → WORKER TOOLS] A firm''s jobs: client, site, dates, stage, value. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); customer_id → customers (shared customer book). Used by: Employer Hub Jobs/Board/Timeline/Overview, Worker Tools My Jobs. Rule: client_id is legacy (employer_clients) — use customer_id.';
comment on table public.employer_knowledge is '[INTERNAL — NOT THE EMPLOYER HUB] RAG knowledge base behind Employer Mate (2,896 chunks). Scope: global. Used by: employer-ai-assistant search tool.';
comment on table public.employer_leads is '[EMPLOYER HUB] Sales enquiries (quote page or manual) and their pipeline stage. Scope: user_id = the firm; converted_customer_id → customers. Used by: Employer Hub Leads, public /get-quote/:slug. Rule: convert_lead() creates/matches a customers row.';
comment on table public.employer_leave_requests is '[EMPLOYER HUB → WORKER TOOLS] Holiday/sick/other leave requests and decisions. Scope: employee_id → employer_employees. Used by: Worker Tools Leave, Employer Hub Timesheets → Leave. Rule: Worker cancels via cancel_my_leave_request(). maintain_holiday_allowance keeps allowances in step.';
comment on table public.employer_material_orders is '[EMPLOYER HUB → WORKER TOOLS] Purchase orders to suppliers (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Hub Procurement, accounts P&L.';
comment on table public.employer_message_attachments is '[EMPLOYER HUB] Attachments on employer_messages. Scope: message_id. Used by: Vacancies messages.';
comment on table public.employer_message_reactions is '[EMPLOYER HUB] Reactions on employer_messages. Scope: message_id. Used by: Vacancies messages.';
comment on table public.employer_messages is '[EMPLOYER HUB] Messages inside employer_conversations. Scope: conversation_id. Used by: Vacancies messages.';
comment on table public.employer_notifications is '[EMPLOYER HUB → WORKER TOOLS] Bell rows written by worker_notify() for workers/apprentices, and for firm events with no registered type. Scope: user_id = the recipient. Used by: The one header bell (useUserNotifications). Rule: Firm events with a registered type go to user_notifications via notify_user() instead (no duplicates since 6 Oct).';
comment on table public.employer_outreach is '[INTERNAL — NOT THE EMPLOYER HUB] Elec-Mate''s OWN sales outreach to employers (tracker6.json via outreach-tracker/sync_outreach.py). Not customer data of any firm. Scope: —. Used by: Admin / outreach scripts.';
comment on table public.employer_policies is '[EMPLOYER HUB] Company policies the firm adopted (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Employer Hub Policies. Rule: Scoped by user_id today; co-admin access + acknowledgements to come (ELE-1946).';
comment on table public.employer_policy_templates is '[EMPLOYER HUB] Policy templates to adopt. Scope: global. Used by: Employer Hub Policies.';
comment on table public.employer_price_book is '[LEGACY — DO NOT USE] Second price book for firms (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Hub Price book. Rule: To be replaced by the shared Electrical Hub materials (ELE-1991). Don''t build on it.';
comment on table public.employer_quote_acceptances is '[LEGACY — DO NOT USE] Acceptances for employer_quotes (0 rows). Scope: quote → employer_quotes. Used by: old accept page. Rule: Acceptance lives on quotes (acceptance_status).';
comment on table public.employer_quotes is '[LEGACY — DO NOT USE] Old Employer Hub quotes table (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: old public /employer-quote pages. Rule: Use quotes. Hub writes there since 6 Oct.';
comment on table public.employer_seats is '[EMPLOYER HUB] Paid worker seats on a firm subscription. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Team section, billing, has_active_worker_seat(). Rule: Free roles must not consume a seat (ELE-1831).';
comment on table public.employer_stripe_connected_accounts is '[LEGACY — DO NOT USE] Unused Stripe Connect table (0 rows, read by nothing). Scope: —. Used by: nothing. Rule: Stripe Connect state lives on company_profiles.';
comment on table public.employer_supplier_invoices is '[EMPLOYER HUB] Supplier invoices matched against POs (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Procurement, match-supplier-invoice. Rule: PDF invoices still to be accepted (ELE-1978).';
comment on table public.employer_suppliers is '[EMPLOYER HUB → WORKER TOOLS] A firm''s suppliers/merchants (0 rows). Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Procurement.';
comment on table public.employer_talent_shortlist is '[EMPLOYER HUB] A firm''s shortlist of talent-pool candidates. Scope: employer_id = the firm; profile_id → employer_elec_id_profiles. Used by: Employer Hub Talent pool.';
comment on table public.employer_team_invites is '[EMPLOYER HUB] Email/link invites to join a firm roster. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: TeamInviteAccept, accept-team-invite / send-team-welcome functions.';
comment on table public.employer_timesheets is '[EMPLOYER HUB → WORKER TOOLS] Hours worked per person per job: clock-ins and manual entries, approved/rejected by the firm. Scope: employee_id → employer_employees; firm via the roster row. Used by: Worker Tools Timesheets, Employer Hub Timesheets, payroll export, job profit. Rule: rejection_reason shown to the worker. Triggers notify both sides.';
comment on table public.employer_vacancies is '[EMPLOYER HUB] Job adverts a firm posts. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Hub Vacancies; electricians browse them in the Electrical Hub.';
comment on table public.employer_vacancy_applications is '[EMPLOYER HUB] Applications to a firm''s vacancies. Scope: vacancy_id → employer_vacancies. Used by: Employer Hub Vacancies; Electrical Hub apply flow.';
comment on table public.employer_vacancy_invitations is '[EMPLOYER HUB] Invitations from a firm to an electrician to apply. Scope: firm + electrician profile. Used by: Employer Hub Talent pool; Electrical Hub.';
comment on table public.employer_vacancy_templates is '[EMPLOYER HUB] Reusable vacancy templates. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Employer Hub Vacancies.';
comment on table public.employer_worker_locations is '[EMPLOYER HUB → WORKER TOOLS] Presence/status history (On site, En route, Office, Off duty) with optional location. Scope: employee_id → employer_employees. Used by: Worker Tools Status, Employer Hub tracking/Overview "Who''s where". Rule: Location only while working; Office/Off duty may have null lat/lng.';
comment on table public.employment_contract_templates is '[EMPLOYER HUB] Employment/subcontractor contract templates firms adopt. Scope: global templates. Used by: Employer Hub Contracts.';
comment on table public.fuel_logs is '[EMPLOYER HUB] Fuel purchases per vehicle. Scope: vehicle_id → vehicles. Used by: Fleet.';
comment on table public.inspector_profiles is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Inspector details used on certificates. Scope: user_id = account. Used by: Certificates, Employer Hub QS.';
comment on table public.job_cost_entries is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Cost entries on Electrical Hub projects; also read for firm job costing. Scope: user_id = account. Used by: Electrical Hub Projects, Employer Hub.';
comment on table public.job_financials is '[EMPLOYER HUB] Per-job budget vs actual by category; auto-created per job. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Job financials, Reports. Rule: Revenue/labour still need wiring to invoices/timesheets (ELE-1981).';
comment on table public.job_issues is '[EMPLOYER HUB → WORKER TOOLS] Snags, defects, variations, RFIs, delays raised on a job. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Quality/Issues, Worker Tools Reports. Rule: Quality & Snags is a filtered view of this table (merge: ELE-1967).';
comment on table public.job_materials is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Materials used on Electrical Hub projects; also read for firm job costing. Scope: user_id = account. Used by: Electrical Hub Projects, Employer Hub job financials.';
comment on table public.job_photos is '[EMPLOYER HUB] Photos the office uploads against a job (bucket job-photos). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Photo gallery. Rule: Crew photos live elsewhere (ELE-1970).';
comment on table public.job_tests is '[LEGACY — DO NOT USE] Hand-typed test log per job (0 rows ever). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Testing workflow section. Rule: Retire in favour of the job''s real certificates (ELE-1973).';
comment on table public.maintenance_contracts is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Recurring maintenance contracts (cron 163 generates visits). Scope: user_id = account; customer_id → customers. Used by: Electrical Hub; Employer Hub recurring work (ELE-1821).';
comment on table public.otj_attest_codes is '[BRIDGE: EMPLOYER ↔ COLLEGE] Hashed 6-digit codes for the public employer attestation link (15-min expiry, 5 attempts). Scope: entry_id → college_otj_entries. Used by: ojt-employer-attest function only. Rule: Service role only.';
comment on table public.profiles is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Every account (electrician, apprentice, employer, college staff). The firm IS its owner''s profile row. Scope: id = auth user. Used by: Everything. Rule: role describes the person''s trade, NOT their place in a firm — never derive Employer Hub permissions from it.';
comment on table public.progress_logs is '[EMPLOYER HUB] Office daily site logs (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Employer Hub Progress logs. Rule: Crew notes are in employer_job_comments (merge: ELE-1964).';
comment on table public.quotes is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Quotes AND invoices for both hubs (invoice_raised = true makes it an invoice). PDFs, sending, Stripe pay links, Xero sync and certificate release all run on this table. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); customer_id → customers. Used by: Electrical Hub quote/invoice builder, Employer Hub Quotes & Invoices, portal, reports. Rule: Numbers come from assign_document_numbers (per owner) — insert quote_number/invoice_number NULL. employer_quotes/employer_invoices are legacy.';
comment on table public.quotes_customer_backfill_20261006 is '[AUDIT LOG] Quote→customer links made on 6 Oct 2026 (matched_on = email/name/created). Rollback source. Scope: quote_id → quotes. Used by: none. Rule: See migrations 20261006131000/135000.';
comment on table public.rams_documents is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] RAMS documents. Mixes sole-trader Site Safety RAMS and firm RAMS (filtered by user_id today). Scope: user_id = author. Used by: Electrical Hub Site Safety, Employer Hub RAMS. Rule: Needs employer_id + employer_job_id so the firm register is separate (ELE-1940).';
comment on table public.rams_generation_jobs is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] AI RAMS / method statement generation jobs, with cancellation. Scope: user_id = requester. Used by: AI RAMS in both hubs.';
comment on table public.report_qs_review_comments is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Comments on a QS review (0 rows). Scope: review → report_qs_reviews. Used by: QS review sheet.';
comment on table public.report_qs_reviews is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Qualifying Supervisor reviews of certificates (submit, approve, return). Scope: employer_id = the firm; report_id → reports. Used by: Employer Hub QS reviews, Worker Tools QS reviews.';
comment on table public.reports is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Certificates (EICR, EIC, Minor Works, specialist certs). report_id prefix gives the type. Scope: user_id = the electrician who wrote it; customer_id → customers. Used by: Electrical Hub I&T, Employer Hub QS reviews/cert lists. Rule: Will link to employer_jobs for the firm (ELE-1832).';
comment on table public.saved_opportunities is '[EMPLOYER HUB] Tender opportunities a firm saved. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Tenders.';
comment on table public.signature_requests is '[EMPLOYER HUB] Requests for a customer/employee to sign something by link. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id optional. Used by: Employer Hub Signatures, Contracts, public /sign/:token. Rule: Must carry a document (ELE-1993).';
comment on table public.team_channel_members is '[EMPLOYER HUB → WORKER TOOLS] Members of a team chat channel. Scope: channel + user_id. Used by: Global Messages sheet.';
comment on table public.team_channel_messages is '[EMPLOYER HUB → WORKER TOOLS] Messages in team chat channels. Scope: channel. Used by: Global Messages sheet.';
comment on table public.team_channels is '[EMPLOYER HUB → WORKER TOOLS] Team chat channels for a firm. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Global Messages sheet. Rule: Not yet reachable from Comms (ELE-1959).';
comment on table public.team_direct_messages is '[EMPLOYER HUB → WORKER TOOLS] Direct-message threads within a firm. Scope: employer_id = the firm (owner profiles.id); managers via my_employer_scope(). Used by: Global Messages sheet.';
comment on table public.team_dm_messages is '[EMPLOYER HUB → WORKER TOOLS] Messages in team direct-message threads. Scope: thread. Used by: Global Messages sheet.';
comment on table public.tender_applications is '[EMPLOYER HUB] Tender submissions. Scope: tender_id → tenders. Used by: Tenders.';
comment on table public.tender_estimates is '[EMPLOYER HUB] AI estimates for a tender. Scope: tender_id → tenders. Used by: Tenders.';
comment on table public.tender_opportunities is '[EMPLOYER HUB] Public tender feed synced from the configured public sources (tender_sources). Scope: global. Used by: Tenders → Discover. Rule: Not firm data; shared feed.';
comment on table public.tender_sources is '[EMPLOYER HUB] Sources for the tender feed. Scope: global. Used by: Tender sync.';
comment on table public.tenders is '[EMPLOYER HUB] A firm''s tender bids (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Employer Hub Tenders.';
comment on table public.time_sessions is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Time tracking sessions on Electrical Hub projects. Scope: user_id = account. Used by: Electrical Hub Projects, Employer Hub.';
comment on table public.toolbox_talk_templates is '[EMPLOYER HUB] Library of toolbox talk templates. Scope: global. Used by: Briefing editor.';
comment on table public.training_records is '[EMPLOYER HUB] Firm-logged training records (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); employee_id → roster. Used by: Employer Hub Training. Rule: Being folded into Elec-ID qualifications (ELE-1954).';
comment on table public.user_cvs is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] Electricians'' CVs, readable by firms they apply to. Scope: user_id = the electrician. Used by: Electrical Hub, Employer Hub Vacancies.';
comment on table public.user_notifications is '[SHARED: ELECTRICAL HUB + EMPLOYER HUB] The central bell + push log for every user (notify_user()). Scope: user_id = recipient. Used by: Header bell in every hub.';
comment on table public.user_tender_preferences is '[EMPLOYER HUB] A firm''s tender match criteria. Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Tenders.';
comment on table public.variation_orders is '[EMPLOYER HUB] Variation orders on a job (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(); job_id → employer_jobs. Used by: Job financials. Rule: To be raised from Variation issues (ELE-1967).';
comment on table public.vehicle_checks is '[EMPLOYER HUB] Daily walk-round vehicle checks. Scope: vehicle_id → vehicles. Used by: Fleet.';
comment on table public.vehicle_documents is '[EMPLOYER HUB] Vehicle documents (MOT, insurance). Scope: vehicle_id → vehicles. Used by: Fleet.';
comment on table public.vehicle_services is '[EMPLOYER HUB] Vehicle service history. Scope: vehicle_id → vehicles. Used by: Fleet.';
comment on table public.vehicle_tools is '[EMPLOYER HUB] Tools kept on a vehicle. Scope: vehicle_id → vehicles. Used by: Fleet.';
comment on table public.vehicles is '[EMPLOYER HUB] Company vans (0 rows). Scope: user_id = the owning account (for a firm: the owner''s profiles.id); firm managers reach it via my_employer_scope(). Used by: Employer Hub Fleet. Rule: Scoped by user_id; driver checks in Worker Tools to come (ELE-1984).';
comment on column public.quotes.user_id is 'The owning account. For a firm this is the firm (owner profiles.id); co-admins act on it via my_employer_scope().';
comment on column public.quotes.customer_id is '→ customers. Set by quotes_auto_link_customer on insert/client change; backfilled 6 Oct 2026.';
comment on column public.quotes.invoice_raised is 'true = this row is an INVOICE (invoice_number/invoice_status/invoice_paid_at apply). false = a quote.';
comment on column public.quotes.quote_number is 'Allocated per owner by assign_document_numbers when inserted NULL. Never generate client-side.';
comment on column public.customers.user_id is 'The owning account (the firm for an employer). Co-admins read/edit via my_employer_scope() policies.';
comment on column public.customers.tags is 'Free tags. ''auto-created-from-quotes'' = created automatically on 6 Oct 2026 from earlier quotes.';
comment on column public.employer_employees.employer_id is 'The firm (owner profiles.id). NULL = an electrician''s own Elec-ID stub, not a team member.';
comment on column public.employer_employees.user_id is 'The person''s own account once they have joined. NULL = invited but not joined.';
comment on column public.employer_employees.status is 'Employment status (Active / Archived …). NOT presence — presence is employer_worker_locations.';
comment on column public.employer_jobs.customer_id is '→ customers (shared customer book). Use this, not client_id.';
comment on column public.employer_jobs.client_id is 'LEGACY → employer_clients. Do not use; see customer_id.';
comment on column public.college_otj_entries.student_id is 'The apprentice''s auth user id. Equals employer_employees.user_id — the only employer↔college join.';
comment on column public.employer_elec_id_profiles.available_for_hire is 'Opt-in talent-pool listing. Default false since 6 Oct 2026; existing listings kept by decision.';
comment on column public.employer_elec_id_profiles.is_verified is 'Approved by an Elec-Mate admin (see reviewed_by/reviewed_at). Not a per-qualification check.';

-- A readable map of every labelled table. Service-role only (not exposed to app users).
create or replace view public.schema_map with (security_invoker = on) as
select c.relname as table_name,
       substring(obj_description(c.oid,'pg_class') from '^\[[^]]+\]') as tag,
       obj_description(c.oid,'pg_class') as description,
       s.n_live_tup as approx_rows
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_stat_user_tables s on s.relid = c.oid
 where n.nspname = 'public' and c.relkind = 'r'
   and obj_description(c.oid,'pg_class') like '[%';
revoke all on public.schema_map from anon, authenticated;
comment on view public.schema_map is '[INTERNAL — NOT THE EMPLOYER HUB] Lists every tagged table with its tag, description and approximate rows. Service-role only.';
