-- =====================================================================
-- EAL Level 3 Electrotechnical Qualification — 601/7345/2 (Issue 8, (c) EAL 2025)
-- Seeds the RAG "brain" (qualification_requirements) so College Hub +
-- Apprentice Hub support EAL learners identically to City & Guilds.
--
-- Source: authoritative (c) EAL 2025 unit PDFs (NETK3 Delivery Units + NETP3
-- Performance Units) + Qualification Specification Issue 8 (601/7345/2).
-- Every LO/AC transcribed verbatim from source then adversarially verified
-- against the source text (no invention; Delivery-Advice column excluded).
--
-- Combined qualification: mandatory knowledge (NETK3) + performance (NETP3)
-- units under ONE qualification_code.
--
-- AFTER applying: invoke edge function `embed-qualification-requirements`
-- (text-embedding-3-small, 1536-dim) to populate the `embedding` column;
-- rows are NULL-embedded on INSERT by trigger and are invisible to
-- match_qualification_acs until embedded.
-- =====================================================================

BEGIN;

-- 1) Qualification row (id is uuid DEFAULT gen_random_uuid(); no unique on code, so guard by NOT EXISTS)
INSERT INTO qualifications (awarding_body, level, title, code, description, requires_portfolio)
SELECT 'EAL','Level 3','Level 3 Electrotechnical Qualification','601/7345/2',
  'EAL Level 3 Electrotechnical Qualification. 745 GLH, TQT 866h. Combined knowledge (NETK3) and on-site performance (NETP3) units; occupational competence also requires the AM2S. Mandatory units plus one optional pathway performance unit.',
  true
WHERE NOT EXISTS (SELECT 1 FROM qualifications WHERE code='601/7345/2');

-- 2) Remove the old unsourced EAL-NETP3 backbone (verified zero student_ac_coverage).
--    NOTE: EAL-NETP3 was the shared requirement_code for 9 EAL quals via
--    qualification_requirement_mappings; section 5 repoints them all to 601/7345/2.
DELETE FROM qualification_requirements WHERE qualification_code = 'EAL-NETP3';
-- 3) Idempotent re-seed of this code
DELETE FROM qualification_requirements WHERE qualification_code = '601/7345/2';

-- 4) Insert unit LO/AC rows


-- NETK3-01  Understand Health, Safety and Environmental Considerations (65 GLH) · Ofqual H/507/7334 · knowledge · verify=pass · 4 LOs / 26 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',1,'Understand how relevant legislation applies in the workplace.','1.1','Identify roles and responsibilities with regard to current relevant Health and Safety legislation.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',1,'Understand how relevant legislation applies in the workplace.','1.2','Identify roles and responsibilities with regard to current relevant environmental legislation.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.1','State the procedures that should be followed in the case of accidents which involve injury, including requirements for the treatment of electric shock/electrical burns.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.2','Specify appropriate procedures which should be followed when emergency situations occur in the workplace.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.3','State the actions to be taken in situations which exceed their level of responsibility for Health and Safety in the workplace.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.4','Specify appropriate responsible persons to whom health and safety and welfare related matters should be reported.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.5','Describe the ways in which the environment may be affected by work activities.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.6','Specify the current requirements and good working practices for processing waste on site.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',2,'Understand the procedures for dealing with Environmental and Health and Safety situations in the work environment.','2.7','Explain why it is important to report any hazards to the environment that arise from work procedures.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.1','State the procedure for producing risk assessments and method statements in accordance with their level of responsibility.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.2','Describe the procedures that should be taken to remove or minimise risks before deciding PPE is needed.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.3','State the purpose of PPE.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.4','Specify the appropriate protective clothing and equipment that is required for identified work tasks.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.5','State the first aid facilities that must be available in the work area in accordance with health and safety regulations.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.6','Explain why it is important not to misuse first aid equipment/supplies and to replace first aid supplies once used.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.7','Describe and demonstrate safe practices and procedures for the use of equipment and materials in the working environment.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.8','Specify and demonstrate the procedures for ensuring electrical systems are safe to work on.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',3,'Be able to demonstrate and understand the procedures for establishing a safe working environment.','3.9','State the implications of: a) Carrying out safe isolation procedures; b) Not carrying out safe isolation procedures.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.1','Identify hazard symbols on packaging and labeling of substances and mixtures.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.2','Define what is meant by the term hazard in relation to health and safety legislation in the workplace.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.3','Identify specific hazards associated with the installation and maintenance of electrical systems and equipment.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.4','Describe situations which can constitute a hazard in the workplace.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.5','Explain practices and procedures for addressing hazards in the work place.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.6','Identify the correct type of fire extinguisher for a particular type of fire.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.7','Explain situations where asbestos may be encountered.'),
('601/7345/2','NETK3-01','Understand Health, Safety and Environmental Considerations',4,'Understand the requirements for identifying and dealing with hazards in the work environment.','4.8','Specify the procedures for dealing with the suspected presence of asbestos in the workplace.');

-- NETK3-03  Understand How to Plan and Oversee Electrical Work Activities (40 GLH) · Ofqual K/507/7335 · knowledge · verify=pass · 3 LOs / 17 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',1,'Understand the requirements for liaising with others when organising and overseeing work activities.','1.1','Describe techniques for the communication with others for the purpose of: motivation; instruction; monitoring; co-operation and teamwork.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',1,'Understand the requirements for liaising with others when organising and overseeing work activities.','1.2','Describe methods of determining the competence of operatives for whom they are responsible.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',1,'Understand the requirements for liaising with others when organising and overseeing work activities.','1.3','Specify procedures for re-scheduling work to co-ordinate with changing conditions in the workplace and to coincide with other trades.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',1,'Understand the requirements for liaising with others when organising and overseeing work activities.','1.4','Specify organisational procedures for completing the documentation that is required during work operations.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.1','Describe how to plan and implement: work allocations; duties of operatives for whom they are responsible; coordination with other services and personnel.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.2','State the procedures for carrying out work activities that will: maintain the safety of the work environment; maintain cost effectiveness; ensure compliance with the programme of work.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.3','Identify the industry standards that are relevant to activities carried out during the installation of electrical systems and equipment, including the current editions.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.4','Evaluate within the scope of the work programme and operations the responsibilities of themselves and others.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.5','Identify the procedures for dealing with changes to an original contract specification.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.6','Identify installations that require specialist advice or guidance: Hazardous installations; Installations outside the scope of BS 7671.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.7','Explain how the work completion time is estimated taking into account influential factors.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.8','State the possible consequences of not: completing work within the estimated time; meeting the requirements of the programme of work; using the specified materials; installing materials and equipment as specified.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',2,'Understand the requirements for organising and overseeing work programmes.','2.9','Specify and evaluate methods of producing and illustrating work programmes.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',3,'Understand the requirements for organising the provision and storage of resources that are required for work activities.','3.1','Interpret the installation specification and work programme to identify resource requirements.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',3,'Understand the requirements for organising the provision and storage of resources that are required for work activities.','3.2','Interpret the material schedule to confirm that materials available are: the right type; fit for purpose; in the correct quantity; suitable for work to be completed cost efficiently.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',3,'Understand the requirements for organising the provision and storage of resources that are required for work activities.','3.3','Specify the storage and transportation requirements for all materials required in the work location.'),
('601/7345/2','NETK3-03','Understand How to Plan and Oversee Electrical Work Activities',3,'Understand the requirements for organising the provision and storage of resources that are required for work activities.','3.4','Specify procedures to ensure the safe and effective storage of materials, tools and equipment in the work location.');

-- NETK3-04  Understand Design and Installation Practices and Procedures (170 GLH) · Ofqual M/507/7336 · knowledge · verify=corrected · 8 LOs / 45 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.1','Identify relevant sources of information which will inform electrical work.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.2','Describe the actions required to ensure that electrical work sites are correctly prepared in terms of health and safety considerations.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.3','State why it is important to check for any pre-existing damage to customer/client property prior to commencement of any work activity.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.4','Explain how to check for any pre-existing damage to customer/client property: a) Equipment and components; b) Building decor and floor finishes.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.5','State the actions that should be taken if pre-existing damage to customer/client property is identified.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',1,'Understand how to prepare for the installation of wiring systems.','1.6','Specify methods for protecting the fabric and structure of the property before and during electrical work.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',2,'Understand the applications of wiring systems.','2.1','Explain the constructional features, applications, advantages and limitations of electrical cables.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',2,'Understand the applications of wiring systems.','2.2','Explain the characteristics of containment, support and wiring systems used in electrical installations.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',2,'Understand the applications of wiring systems.','2.3','Determine the size of conduit and trunking as appropriate to the size and number of cables.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',2,'Understand the applications of wiring systems.','2.4','Describe the factors which affect the selection of wiring systems, associated equipment and enclosures.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',2,'Understand the applications of wiring systems.','2.5','Assess and select suitable wiring systems and equipment appropriate to the situation and use.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.1','State the procedures for selecting and safely using appropriate hand tools, power tools and adhesives for electrical work.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.2','State the procedures for selecting and safely using equipment for measuring and marking out for wiring systems, equipment and enclosures.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.3','State the criteria for selecting and safely using tools and equipment for fixing and installing wiring systems, associated equipment and enclosures.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.4','State the criteria for selecting and safely using fixing devices for wiring systems, associated equipment and enclosures.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.5','Assess and specify the installation methods and procedures to ensure that in accordance with the installation specification and statutory and non-statutory regulations: a) wiring systems, enclosures, cables and components are securely fixed and installed; b) a wiring system''s mechanical integrity is maintained; c) no damage to the wiring system or its components has occurred.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',3,'Understand the practices and procedures for carrying out electrical work.','3.6','Specify methods and techniques for restoring the building fabric.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',4,'Understand the characteristics and applications of supply systems and consumer''s equipment.','4.1','Explain the characteristics and applications of earthing arrangements.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',4,'Understand the characteristics and applications of supply systems and consumer''s equipment.','4.2','Explain the characteristics and applications of supply systems.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',4,'Understand the characteristics and applications of supply systems and consumer''s equipment.','4.3','Specify the arrangements for electrical installations and systems with regard to provision for: a) Isolation and switching (including DC isolators); b) Overcurrent protection.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.1','Explain the purpose of earthing and protective conductors.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.2','Identify extraneous and exposed conductive parts.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.3','Describe the requirements and measures for protection against electric shock.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.4','State the maximum disconnection time for different types of circuit.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.5','Explain the earth fault loop path and earth fault loop impedance.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.6','Specify requirements and applications of functional earthing.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',5,'Understand earthing and protection.','5.7','Select suitably sized protective conductors in accordance with BS 7671.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',6,'Understand protection against fault current.','6.1','Identify types of and reasons for overcurrent.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',6,'Understand protection against fault current.','6.2','Explain the operating principles, applications and limitations of protective devices.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',6,'Understand protection against fault current.','6.3','Identify fault current capacities of devices.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',6,'Understand protection against fault current.','6.4','Outline the need for selectivity between protective devices.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',7,'Understand electrical systems and circuits.','7.1','Describe the characteristics of standard electrical circuits.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',7,'Understand electrical systems and circuits.','7.2','Outline the key characteristics of particular electrical systems and circuits and the applications of these circuits and systems.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.1','State the purpose of diversity factors.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.2','Select suitable current using equipment giving consideration to energy efficiency and relevant codes of practice for sustainability.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.3','Determine the maximum demand (of an installation) after the application of diversity.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.4','Determine the design current.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.5','Select a suitably rated protective device.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.6','Establish the installation method reference.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.7','Determine appropriate rating factors.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.8','Determine the minimum cross-sectional area of live conductors taking into consideration current carrying capacity and voltage drop.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.9','Establish if the voltage drop is acceptable.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.10','Verify if the disconnection times have been achieved.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.11','Evaluate thermal constraints.'),
('601/7345/2','NETK3-04','Understand Design and Installation Practices and Procedures',8,'Understand the electrical design procedure.','8.12','Interpret the requirements of sources of information in the design of an installation.');

-- NETK3-05  Understand Terminations and Connections of Conductors (93 GLH) · Ofqual T/507/7337 · knowledge · verify=pass · 2 LOs / 7 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',1,'Understand the regulatory requirements and procedures for terminating and connecting conductors and cables in electrical wiring systems and equipment.','1.1','Identify and interpret appropriate sources of relevant information for the termination and connection of conductors and cables in electrical wiring systems and equipment.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',1,'Understand the regulatory requirements and procedures for terminating and connecting conductors and cables in electrical wiring systems and equipment.','1.2','Describe methods and procedures appropriate to the installation environment to ensure the safe and effective termination and connection of conductors and cables in electrical wiring systems and equipment.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',2,'Understand the procedures and applications of different methods of terminating, connecting and supporting conductors and cables in electrical wiring systems and equipment.','2.1','Explain the advantages, limitations and applications of the following connection methods: screw; crimped; soldered; non-screw compression; insulation displacement; compact lever; DC rated terminal.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',2,'Understand the procedures and applications of different methods of terminating, connecting and supporting conductors and cables in electrical wiring systems and equipment.','2.2','Describe the procedures for verifying that terminations and connections are electrically and mechanically sound.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',2,'Understand the procedures and applications of different methods of terminating, connecting and supporting conductors and cables in electrical wiring systems and equipment.','2.3','Explain the consequences of terminations not being electrically and mechanically sound in terms of: high resistance joints; corrosion and erosion.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',2,'Understand the procedures and applications of different methods of terminating, connecting and supporting conductors and cables in electrical wiring systems and equipment.','2.4','Interpret and apply the techniques and methods for the safe and effective termination and connection of: flexible cables; single and multicore thermoplastic (PVC) and thermosetting insulated cables; PVC/PVC flat profile cable; MICC; SWA cables; Galvanised steel wire braid; data cables; fire performance cable; DC cables.'),
('601/7345/2','NETK3-05','Understand Terminations and Connections of Conductors',2,'Understand the procedures and applications of different methods of terminating, connecting and supporting conductors and cables in electrical wiring systems and equipment.','2.5','Apply techniques and methods for effective support of cables.');

-- NETK3-06A  Inspection, Testing and Commissioning (80 GLH) · Ofqual A/650/7479 · knowledge · verify=pass · 11 LOs / 59 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.1','State the requirements of the Electricity at Work Regulations for the safe inspection of electrical systems and equipment.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.2','Specify the appropriate procedure for completing safe isolation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.3','State the implications of carrying out safe isolation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.4','State the implications of not carrying out safe isolation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.5','Identify the Health and Safety requirements which apply when inspecting, testing and commissioning electrical installations and circuits.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',1,'Understand the requirements for completing the safe isolation of electrical circuits and installations.','1.6','Identify the procedure for detecting potential diverted neutral currents.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',2,'Understand the requirement for inspection of electrical installations.','2.1','State the purpose of the inspection of electrical installations.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',2,'Understand the requirement for inspection of electrical installations.','2.2','State the requirements of the inspection.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',2,'Understand the requirement for inspection of electrical installations.','2.3','Identify the relevant documents associated with the inspection, testing, commissioning and reporting of an electrical installation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',2,'Understand the requirement for inspection of electrical installations.','2.4','Specify the information that is required by the inspector to conduct the inspection of an electrical installation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',3,'Understand the requirements for completing the inspection of electrical installations prior to their being placed into service.','3.1','Select appropriate items to be checked during the inspection process.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',3,'Understand the requirements for completing the inspection of electrical installations prior to their being placed into service.','3.2','Identify human senses appropriate for initial verification.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',3,'Understand the requirements for completing the inspection of electrical installations prior to their being placed into service.','3.3','State how the senses can be used during the inspection process.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',3,'Understand the requirements for completing the inspection of electrical installations prior to their being placed into service.','3.4','Specify the requirements for the inspection of electrical installations.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',3,'Understand the requirements for completing the inspection of electrical installations prior to their being placed into service.','3.5','Specify the requirements for the inspection to include: a) Special installations and locations, as identified in Part 7 of BS 7671; b) IP Classification of equipment.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.1','State the tests to be carried out on an electrical installation in accordance with BS 7671 and IET Guidance Note 3.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.2','Identify the appropriate instrument for each test to be carried out in terms of: a) The instrument is fit for purpose; b) Identifying the correct scale or setting.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.3','Specify the requirements for the safe use of instruments to be used for testing and commissioning, to include: a) Checks required to prove that test instruments are safe and functioning correctly; b) The requirements for test leads and probes must comply with HSE Guidance GS38; c) The need for instruments to be regularly checked and calibrated.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.4','Explain why it is necessary for test results to comply with standard values.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.5','State the actions to be taken in the event of unsatisfactory results being obtained.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',4,'Understand the requirements for the safe testing and commissioning of electrical installations.','4.6','Explain why testing is carried out in the sequence specified in BS 7671 and IET Guidance Note 3.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.1','State why it is necessary to verify continuity to include: a) Protective bonding conductors; b) Circuit protective conductors; c) Ring final circuit conductors.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.2','State the methods for verifying continuity to include: a) Protective conductors; b) Ring final circuit conductors.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.3','Explain factors that affect conductor resistance values.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.4','Specify the procedures for completing insulation resistance testing.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.5','State the effects on insulation resistance values that the following can have: a) Cables connected in parallel; b) Variations in cable length.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.6','Explain why it is necessary to verify polarity.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',5,'Understand the requirements for testing before circuits are energised.','5.7','State the procedures for verifying polarity.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.1','State the procedures for confirming the polarity of the incoming supply.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.2','Specify the methods for measuring earth electrode resistance to include: a) Installations forming part of a TT system; b) Generators and transformers.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.3','Describe common earth fault loop paths.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.4','State the methods for verifying protection by automatic disconnection of supply.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.5','Identify the requirements for the measurement of prospective fault current.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.6','Specify the methods for determining prospective fault current.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.7','Verify the suitability of protective devices for prospective fault currents.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.8','Specify the methods for testing the correct operation of residual current devices.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.9','State the reasons for verifying phase sequence.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.10','State the methods used to verify phase sequence.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.11','State the need for functional testing.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.12','Identify items which require functional testing.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',6,'Understand the requirements for testing energised installations.','6.13','State the appropriate procedures for dealing with clients during the commissioning and certification process.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',7,'Understand the requirements for the completion of documentation.','7.1','Explain the purpose of certification and associated documentation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',7,'Understand the requirements for the completion of documentation.','7.2','State the information that must be contained on documentation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',7,'Understand the requirements for the completion of documentation.','7.3','Describe the certification process for a completed installation.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',7,'Understand the requirements for the completion of documentation.','7.4','Identify the responsibilities of different relevant personnel in relation to the completion of the certification process.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',7,'Understand the requirements for the completion of documentation.','7.5','Explain the requirements for the recording and retention of completed documentation in accordance with BS 7671.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',8,'Be able to confirm safety of system and equipment prior to completion of inspection, testing and commissioning.','8.1','Carry out safe isolation procedures in accordance with regulatory requirements.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',8,'Be able to confirm safety of system and equipment prior to completion of inspection, testing and commissioning.','8.2','Comply with the health and safety requirements of themselves and others within the work location during the initial verification process.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',8,'Be able to confirm safety of system and equipment prior to completion of inspection, testing and commissioning.','8.3','Check the safety of electrical systems prior to the commencement of inspection, testing and commissioning.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',9,'Be able to carry out inspection of electrical installations prior to them being placed into service.','9.1','Identify a safe system of work appropriate to the work activity.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',9,'Be able to carry out inspection of electrical installations prior to them being placed into service.','9.2','Carry out an initial inspection of an electrical installation in accordance with the requirements of BS 7671 and IET Guidance Note 3.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',9,'Be able to carry out inspection of electrical installations prior to them being placed into service.','9.3','Complete a Schedule of Inspections in accordance with BS 7671 and IET Guidance Note 3 based on engineering evaluation of the installation to be verified.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',10,'Be able to test electrical installations prior to them being placed into service.','10.1','Select the test instruments and their accessories for tests to include: a) Continuity; b) Insulation resistance; c) Polarity; d) Earth electrode resistance; e) Earth fault loop impedance; f) Prospective fault current; g) RCD operation; h) Phase sequence; i) Functional testing.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',10,'Be able to test electrical installations prior to them being placed into service.','10.2','Evaluate the appropriate tests suitable for the installation to be verified.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',10,'Be able to test electrical installations prior to them being placed into service.','10.3','Carry out tests in accordance with BS 7671, OSG and GN3, to include: a) Continuity including: Main protective bonding conductors, Circuit protective conductors, Ring Final Circuits; b) Insulation resistance; c) Polarity; d) External earth fault loop impedance (Ze); e) System earth fault loop impedance (Zs); f) Prospective fault current; g) RCD operation, including additional protection; h) Phase sequence; i) Functional testing.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',10,'Be able to test electrical installations prior to them being placed into service.','10.4','Confirm compliance by evaluating and verifying test results.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',10,'Be able to test electrical installations prior to them being placed into service.','10.5','Complete appropriate documentation in accordance with BS 7671 and IET Guidance Note 3, including an Electrical Installation Certificate and related schedules.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',11,'Be able to commission electrical systems and equipment.','11.1','Clarify the commissioning procedures with relevant persons.'),
('601/7345/2','NETK3-06A','Inspection, Testing and Commissioning',11,'Be able to commission electrical systems and equipment.','11.2','Carry out the commissioning of circuits, accessories and equipment to confirm functionality.');

-- NETK3-07  Understand Fault Diagnosis and Rectification (32 GLH) · Ofqual F/507/7339 · knowledge · verify=pass · 6 LOs / 21 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',1,'Understand the health and safety requirements relevant to fault diagnosis.','1.1','State the dangers of electricity in relation to fault diagnosis work.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',1,'Understand the health and safety requirements relevant to fault diagnosis.','1.2','Identify the health and safety requirements relevant to diagnosing and correcting electrical faults in electrical systems and equipment.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',1,'Understand the health and safety requirements relevant to fault diagnosis.','1.3','Specify safe working procedures that should be adopted for completion of fault diagnosis and correction work.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',2,'Understand the importance of reporting and communication in fault diagnosis.','2.1','Describe the documentation relevant to fault diagnosis.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',2,'Understand the importance of reporting and communication in fault diagnosis.','2.2','State the implications of the fault diagnosis for customers and clients.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',2,'Understand the importance of reporting and communication in fault diagnosis.','2.3','Explain the communication requirements relevant to fault diagnosis.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',3,'Understand the nature and characteristics of electrical faults.','3.1','Identify types, causes and consequences of electrical faults.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',3,'Understand the nature and characteristics of electrical faults.','3.2','Describe typical types of faults and their likely locations in wiring systems and equipment.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.1','State precautions that must be taken when carrying out fault diagnosis with regard to particular locations, equipment and circumstances.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.2','Explain the logical stages of fault diagnosis.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.3','Select the appropriate test instrument/s for fault diagnosis work.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.4','Describe how test instruments are confirmed to be fit for purpose and functioning correctly.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.5','Specify appropriate and logical procedures for carrying out fault diagnosis tests.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',4,'Understand the fault diagnosis procedure.','4.6','Analyse and determine if test results are acceptable.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',5,'Understand the procedures and techniques for correcting electrical faults.','5.1','Identify factors which can affect repair or replacement of equipment.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',5,'Understand the procedures and techniques for correcting electrical faults.','5.2','Specify the procedures for verifying that the fault has been corrected suitable for the situation using technical analysis.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',5,'Understand the procedures and techniques for correcting electrical faults.','5.3','State the methods to ensure the safe disposal of any waste and that the work area is left in a safe and clean condition.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',6,'Perform fault diagnosis.','6.1','Follow safe working procedures.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',6,'Perform fault diagnosis.','6.2','Evaluate and apply appropriate fault diagnosis methods and techniques.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',6,'Perform fault diagnosis.','6.3','Diagnose electrical faults using engineering decision and evaluation of symptoms and findings.'),
('601/7345/2','NETK3-07','Understand Fault Diagnosis and Rectification',6,'Perform fault diagnosis.','6.4','Recommend the appropriate action/s to correct the fault.');

-- NETK3-08  Electrical Scientific Principles and Technologies (115 GLH) · Ofqual T/507/7340 · knowledge · verify=pass · 12 LOs / 47 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',1,'Understand mathematical principles which are appropriate to electrical installation, maintenance and design work.','1.1','Identify and apply appropriate mathematical principles which are relevant to electrical work tasks.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',2,'Understand standard units of measurement used in electrical installation, maintenance and design work.','2.1','Identify and use internationally recognised base and derived (SI) units of measurement.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',2,'Understand standard units of measurement used in electrical installation, maintenance and design work.','2.2','Identify and determine values of base and derived SI units which apply specifically to electrical quantities.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',2,'Understand standard units of measurement used in electrical installation, maintenance and design work.','2.3','Identify appropriate electrical instruments for the measurement of different electrical quantities.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',3,'Understand basic mechanics and the relationship between force, work, energy and power.','3.1','Specify what is meant by mass and weight.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',3,'Understand basic mechanics and the relationship between force, work, energy and power.','3.2','Explain the principles of basic mechanics as they apply to levers, gears and pulleys.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',3,'Understand basic mechanics and the relationship between force, work, energy and power.','3.3','Describe the main principles of the following and their inter-relationships: force; work; energy (kinetic and potential); power; efficiency.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',3,'Understand basic mechanics and the relationship between force, work, energy and power.','3.4','Calculate values of mechanical energy, power and efficiency.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.1','Describe the basic principles of electron theory.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.2','Identify and distinguish between materials which are good conductors and insulators.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.3','Describe what is meant by resistance and resistivity in relation to electrical circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.4','Explain the relationship between current, voltage and resistance in parallel and series d.c. circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.5','Calculate the values of current, voltage and resistance in parallel and series D.C. circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.6','Calculate values of power in parallel and series d.c. circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.7','State what is meant by the term voltage drop in relation to electrical circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',4,'Understand the relationship between resistance, resistivity, voltage, current and power.','4.8','Describe the chemical and thermal effects of electric currents.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',5,'Understand the fundamental principles which underpin the relationship between magnetism and electricity.','5.1','Describe the effects of magnetism in terms of attraction and repulsion.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',5,'Understand the fundamental principles which underpin the relationship between magnetism and electricity.','5.2','State the difference between magnetic flux and flux density.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',5,'Understand the fundamental principles which underpin the relationship between magnetism and electricity.','5.3','Describe the magnetic effects of electrical currents in terms of: production of a magnetic field; force on a current-carrying conductor in a magnetic field; electromagnetism; electromotive force.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',5,'Understand the fundamental principles which underpin the relationship between magnetism and electricity.','5.4','Describe the basic principles of generating an a.c. supply in terms of: a single-loop generator; sine-wave; frequency; EMF; magnetic flux.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',5,'Understand the fundamental principles which underpin the relationship between magnetism and electricity.','5.5','Identify the characteristics of sinewaves.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',6,'Understand the types, applications and limitations of electronic components in electrical systems and equipment.','6.1','Describe the function and application of electronic components that are used in electrical systems.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',6,'Understand the types, applications and limitations of electronic components in electrical systems and equipment.','6.2','State the basic operating principles of electronic components and devices.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.1','Describe how electricity is generated and transmitted for domestic and industrial/commercial consumption.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.2','Specify the features and characteristics of a generation and transmission system.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.3','State the basic operating principles of other sources of electricity.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.4','Describe the main characteristics of: single phase electrical supplies; three phase electrical supplies; three phase and neutral supplies; sub-station transformers.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.5','Identify types of transformers.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.6','Describe the operating principles, applications and limitations of transformers.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',7,'Understand electrical supply systems.','7.7','Determine by calculation and measurement: primary and secondary voltages; primary and secondary current; kVA rating of a transformer.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.1','Explain the relationship between resistance, inductance, capacitance and impedance.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.2','Determine electrical quantities in alternating current circuits.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.3','Explain the relationship between kW, kVAr, kVA and power factor.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.4','Calculate power factor.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.5','Explain what is meant by power factor correction.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.6','Specify methods of power factor correction.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.7','Determine the neutral current in a three-phase and neutral supply and why systems should be balanced.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',8,'Understand how different electrical properties can affect electrical circuits, systems and equipment.','8.8','Calculate values of voltage and current in star and delta connected systems.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',9,'Understand the operating principles and applications of d.c. machines and a.c. motors.','9.1','State the basic types, applications and describe the operating principles of d.c. machines.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',9,'Understand the operating principles and applications of d.c. machines and a.c. motors.','9.2','Describe the operating principles of a.c. motors.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',9,'Understand the operating principles and applications of d.c. machines and a.c. motors.','9.3','State the basic types, applications and limitations of a.c. motors.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',9,'Understand the operating principles and applications of d.c. machines and a.c. motors.','9.4','Describe the basic operating principles, limitations and applications of motor control.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',10,'Understand the operating principles of electrical components.','10.1','Specify the main types and operating principles of electrical components.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',11,'Understand the principles and applications of electrical lighting systems.','11.1','Explain the basic principles of illumination and state the applications of: inverse square law; cosine law; lumen method.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',11,'Understand the principles and applications of electrical lighting systems.','11.2','Explain the operating principles, types, limitations and applications of luminaires.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',12,'Understand the principles and applications of electrical heating.','12.1','Explain the basic principles of electrical space heating and electrical water heating.'),
('601/7345/2','NETK3-08','Electrical Scientific Principles and Technologies',12,'Understand the principles and applications of electrical heating.','12.2','Explain the operating principles, types, limitations and applications of electrical space and water heating appliances and components.');

-- NETP3-01  Apply Health, Safety and Environmental Considerations (10 GLH) · Ofqual F/507/7342 · performance · verify=pass · 4 LOs / 14 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',1,'Be able to apply relevant health and safety legislation in the workplace','1.1','Identify which workplace health and safety procedures are relevant to the working environment and comply with their duties and obligations as defined by current legislation and organisational procedures'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',1,'Be able to apply relevant health and safety legislation in the workplace','1.2','Produce a risk assessment and method statement in accordance with organisational procedures for a given work activity'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',1,'Be able to apply relevant health and safety legislation in the workplace','1.3','Work within the requirements of: a) Risk assessments; b) Method statements; c) Safe systems of work'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',2,'Be able to assess the work environment for hazards and identify remedial actions in accordance with health and safety legislation','2.1','Identify unsafe situations and conditions and take remedial actions'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',2,'Be able to assess the work environment for hazards and identify remedial actions in accordance with health and safety legislation','2.2','Assess the work environment and revise work practices accordingly to take into account hazards which could cause harm, including the handling of potentially hazardous: a) Materials; b) Tools; c) Equipment'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',2,'Be able to assess the work environment for hazards and identify remedial actions in accordance with health and safety legislation','2.3','Identify any hazards which may present a high risk and report their presence to the relevant persons who have overall responsibility for health and safety in the workplace'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',2,'Be able to assess the work environment for hazards and identify remedial actions in accordance with health and safety legislation','2.4','Apply measures to control health and safety hazards'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',2,'Be able to assess the work environment for hazards and identify remedial actions in accordance with health and safety legislation','2.5','Select and use correct personal protective equipment'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',3,'Be able to apply methods and procedures to ensure work on site is in accordance with health and safety legislation','3.1','Demonstrate a level of personal conduct and behaviour within the workplace, to ensure that the health and safety of themselves and others is not endangered'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',3,'Be able to apply methods and procedures to ensure work on site is in accordance with health and safety legislation','3.2','Apply procedures to ensure the safe use, maintenance and storage of tools, plant and equipment as stipulated in: a) Workplace policies (company and site); b) Supplier information; c) Manufacturer''s instructions'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',3,'Be able to apply methods and procedures to ensure work on site is in accordance with health and safety legislation','3.3','Comply with information, warning, mandatory instruction, and prohibition notices'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',3,'Be able to apply methods and procedures to ensure work on site is in accordance with health and safety legislation','3.4','Apply procedures to ensure the safety of the work location through the correct use of guards, barriers and notices'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',3,'Be able to apply methods and procedures to ensure work on site is in accordance with health and safety legislation','3.5','Use access equipment correctly: a) Ladder; b) Tower scaffold or MEWP; c) Stepladder; d) Platform'),
('601/7345/2','NETP3-01','Apply Health, Safety and Environmental Considerations',4,'Be able to work in accordance with environmental legislation for electrical services','4.1','Demonstrate appropriate procedures for the safe handling, storage and disposal of hazardous materials and products: a) Environmental Protection Act; b) Hazardous Waste Regulations; c) Pollution Prevention and Control Act; d) Control of Pollution Act; e) Control of Noise at Work Regulations; f) Environment Act');

-- NETP3-03  Organise and Oversee the Electrical Work Environment (12 GLH) · Ofqual J/507/7343 · performance · verify=pass · 6 LOs / 18 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',1,'Be able to provide relevant people with technical and functional information for work on electrical systems and equipment','1.1','Liaise with relevant people to evaluate the information they require to ensure that systems, equipment or components can be operated safely and effectively'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',1,'Be able to provide relevant people with technical and functional information for work on electrical systems and equipment','1.2','Identify appropriate technical and functional information that is required for the work activity'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',1,'Be able to provide relevant people with technical and functional information for work on electrical systems and equipment','1.3','Provide information in a timely, courteous, suitable and professional manner in accordance with organisational procedures and engineering standards'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',2,'Be able to oversee Health and Safety during work on electrical systems and equipment','2.1','Produce, or revise generic, risk assessments and method statements, to cover their own work and others working the area (colleagues and other operatives) in accordance with their level of responsibility'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',2,'Be able to oversee Health and Safety during work on electrical systems and equipment','2.2','Implement suitable procedures to confirm that work is being completed in accordance with health and safety legislation and industry standards'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',3,'Be able to coordinate liaison with other relevant persons during work activities','3.1','Select effective procedures to ensure coordination with other workers/contractors, including steps to resolve issues which are outside the scope of their job role'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',3,'Be able to coordinate liaison with other relevant persons during work activities','3.2','Evaluate and apply communication techniques that are clear, accurate and appropriate to the situation'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',3,'Be able to coordinate liaison with other relevant persons during work activities','3.3','Demonstrate working effectively with colleagues to enhance performance'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',4,'Be able to organise and oversee work activities and operations','4.1','Organise operatives by allocating duties and responsibilities to make the best use of their competence and skill'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',4,'Be able to organise and oversee work activities and operations','4.2','Monitor the work of operatives to ensure it is in accordance with: a. Industry working practices; b. The programme of work; c. Health and Safety requirements; d. Cost effectiveness; e. Environmental considerations'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',4,'Be able to organise and oversee work activities and operations','4.3','Evaluate and apply appropriate procedures to correct issues that arise during work activities'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',5,'Be able to organise a programme for working on electrical systems and equipment','5.1','Produce a simple programme of work from the work specification, including requirements for the following: a. An estimation of the amount of time required for completion of the work; b. Where liaison with other trades may be necessary'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',5,'Be able to organise a programme for working on electrical systems and equipment','5.2','Communicate with others clearly and concisely'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',5,'Be able to organise a programme for working on electrical systems and equipment','5.3','Assess situations when it is necessary to liaise with other relevant parties to resolve issues'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',6,'Be able to organise the resource requirements for work on electrical systems and equipment','6.1','Organise the provision of resources (such as materials, fixings, plant, labour or tools)'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',6,'Be able to organise the resource requirements for work on electrical systems and equipment','6.2','Confirm that the materials available are: a. The right type; b. Fit for purpose; c. In the correct quantity; d. Suitable for work to be completed cost-efficiently'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',6,'Be able to organise the resource requirements for work on electrical systems and equipment','6.3','Ensure that resources are undamaged at the point of delivery'),
('601/7345/2','NETP3-03','Organise and Oversee the Electrical Work Environment',6,'Be able to organise the resource requirements for work on electrical systems and equipment','6.4','Demonstrate effective measures which ensure the safe and effective storage of materials, tools and equipment in the work location');

-- NETP3-04A  Apply Design and Installation Practices and Procedures (20 GLH) · Ofqual T/650/7477 · performance (optional: Installation pathway) · verify=pass · 4 LOs / 13 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',1,'Prepare to install wiring systems, enclosures and associated equipment','1.1','Assess and apply appropriate procedures to include: a) Adopting appropriate PPE; b) Following a safe system of work (e.g. working in accordance with a risk assessment and method statement); c) Selecting appropriate tools/equipment for the installation work'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',1,'Prepare to install wiring systems, enclosures and associated equipment','1.2','Prepare to install wiring systems, enclosures and associated equipment, to include: a) Confirm secure site storage facilities for tools, equipment, materials and components; b) Select materials (equipment and components) in accordance with the installation specification; c) Report any pre-work damage/defects to existing equipment or building features, to the relevant person (Such as: customer/client, site/line manager); d) Confirm site readiness for installation work to begin; e) Confirm authorisation for the installation work to start'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',1,'Prepare to install wiring systems, enclosures and associated equipment','1.3','Use documentation to confirm that materials and equipment is of the correct quantity and is free from damage'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',1,'Prepare to install wiring systems, enclosures and associated equipment','1.4','Ensure the planned locations for the wiring system and associated equipment are compatible with other building services (e.g. gas, water or other electrical services)'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',1,'Prepare to install wiring systems, enclosures and associated equipment','1.5','Check the planned locations for the wiring system in terms of: a) Cosmetic appearance; b) External influences'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',2,'Interpret appropriate information for the installation of wiring systems, enclosures and associated equipment','2.1','Use sources of information to enable the installation of wiring systems, enclosures and associated equipment to be carried out including: a) Specifications; b) Work schedules/programmes; c) Manufacturer instructions; d) Layout Drawings; e) Other appropriate source of information (e.g. BS 7671, other plans or diagrams, ''approved documents'', building regulations)'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.1','Use appropriate measuring and marking out techniques which are appropriate to the wiring system, wiring enclosure and/or associated equipment that is being installed'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.2','Install cables in accordance with BS 7671, the installation specification and programme of work: Cover Five a) Single-core cable (singles); b) Multicore insulated cable; c) PVC/PVC flat profile cable (twin and earth); d) MICC cable; e) Fire performance (such as FP200 etc.); f) SWA cable; g) GSWB galvanised steel wire braid (SY); h) Data/PoE; i) DC cabling'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.3','Install the following in accordance with BS 7671, the installation specification and agreed planned programme of work: PVC Containment - Minimum of ONE a) PVC trunking; b) PVC conduit; AND Metallic Containment - Minimum of ONE c) Metallic conduit; d) Metallic trunking; AND Minimum of ONE from the following e) Cable tray; f) Cable basket; g) Ladder systems; h) Ducting; i) Modular wiring systems; j) Busbar systems or powertrack'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.4','Install the following types of electrical equipment and accessories, in accordance with BS 7671, the installation specification, manufacturers'' instructions and the programme of work: Cover five a) Isolators/switches; b) Socket-outlets; c) Distribution-boards/consumer control units; d) Overcurrent protective devices; e) Luminaires; f) Data socket-outlets/Wi-Fi router; g) Electric vehicle charging point; h) Other appropriate equipment (Such as: heating system components, control equipment, fire detection components, smart camera, smart lighting or heating control (N.B. An individual smart lamp is not sufficient))'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.5','Communicate with others professionally and appropriately to aid the effective installation of the wiring system/equipment'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',3,'Install wiring systems and equipment in accordance with current relevant statutory and non-statutory regulations','3.6','Dispose of waste materials in accordance with site procedures and statutory requirements'),
('601/7345/2','NETP3-04A','Apply Design and Installation Practices and Procedures',4,'Confirm the quality of the completed work','4.1','Ensure the installed wiring system/s and enclosure/s meet specified requirements, including that they: a) Are the correct type and fit for purpose; b) Are installed in accordance with BS 7671; c) Meet the installation specification/other relevant plans/instructions; d) Are installed in accordance with any relevant manufacturer instructions');

-- NETP3-05  Termination and Connection of Conductors (12 GLH) · Ofqual Y/650/7478 (current eq. NETP3-05A) · performance · verify=pass · 2 LOs / 7 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-05','Termination and Connection of Conductors',1,'Prepare to terminate and connect cables and conductors','1.1','Evaluate and apply appropriate procedures to include: a) selecting appropriate tools/equipment to enable termination and connection; b) adopting appropriate PPE; c) following a safe system of work (e.g. risk assessment, method statement, permit to work procedure)'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',1,'Prepare to terminate and connect cables and conductors','1.2','Assess and confirm it is safe to complete termination and connection in terms of: a) checking for presence of supply/carrying out safe isolation; b) mechanical soundness of the electrical equipment to be connected to; c) checking for unsafe situations'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',2,'Terminate and connect conductors and cables','2.1','Terminate and connect cables and conductors in accordance with manufacturers instructions, BS 7671, and any relevant drawing or specification: a) single core cable (singles); b) multicore insulated cable; c) PVC / PVC flat profile cable (twin and earth); d) MICC cable; e) fire performance (such as FP 200 etc.); f) SWA cable; g) GSWB galvanised steel wire braid; h) data cable'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',2,'Terminate and connect conductors and cables','2.2','Connect to electrical equipment in accordance with manufacturers instructions, BS 7671, and any relevant drawing or specification: a) isolators/switches; b) socket outlets; c) distribution-boards / consumer control units; d) luminaires; e) electric motors / motor control equipment; f) overcurrent protective devices; g) earthing terminals; h) control panels; i) data socket outlets or data connections; j) fire detection/alarm components; k) other appropriate equipment (such as: heating system components etc.)'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',2,'Terminate and connect conductors and cables','2.3','Terminate and connect conductors, using appropriate methods: a) screwing; b) crimping; c) soldering; d) non-screw compression; e) insulation displacement'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',2,'Terminate and connect conductors and cables','2.4','Ensure that terminations and connections are electrically and mechanically sound (e.g. by simple inspecting and testing terminations)'),
('601/7345/2','NETP3-05','Termination and Connection of Conductors',2,'Terminate and connect conductors and cables','2.5','Ensure cables have appropriate identification in accordance with BS 7671');

-- NETP3-06  Inspect, Test and Commission Electrical Systems (16 GLH) · Ofqual R/507/7345 · performance · verify=pass · 3 LOs / 12 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',1,'Be able to confirm the safety of the system and equipment prior to completion of inspection, testing and commissioning in accordance with statutory and non-statutory regulations','1.1','Carry out safe isolation procedures in accordance with regulatory requirements for electrical installations'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',1,'Be able to confirm the safety of the system and equipment prior to completion of inspection, testing and commissioning in accordance with statutory and non-statutory regulations','1.2','Ensure the health and safety of themselves and others within the work location during inspection, testing and commissioning'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',1,'Be able to confirm the safety of the system and equipment prior to completion of inspection, testing and commissioning in accordance with statutory and non-statutory regulations','1.3','Check the safety of electrical systems prior to the commencement of inspection, testing and commissioning'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',2,'Be able to inspect electrical systems and equipment','2.1','Assess whether the safe system of work is appropriate to the work activity'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',2,'Be able to inspect electrical systems and equipment','2.2','Carry out a visual inspection in accordance with the requirements of the installation specification, BS 7671 and IET Guidance Note 3'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',2,'Be able to inspect electrical systems and equipment','2.3','Complete a schedule of inspections in accordance with BS 7671 and IET Guidance Note 3 making technical decisions'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.1','Select the correct test instruments and their accessories for tests'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.2','Carry out tests in accordance with the installation specification and BS 7671 and manufacturers'' instructions: a) Continuity; b) Insulation resistance; c) Polarity; d) Earth fault loop impedance/earth electrode resistance; e) Prospective fault current; f) RCD operation; g) Functional testing'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.3','Analyse and verify test results reporting all findings to relevant persons, as appropriate: a) Representatives of other services/colleagues; b) Customers/clients'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.4','Complete in accordance with BS 7671 and IET Guidance Note 3: a) An Electrical Installation Certificate, complete with related schedules; b) A Minor Electrical Installation Works Certificate'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.5','Complete the handover of electrical systems and equipment to relevant persons including the provision of accurate and complete documentation regarding the completed inspection, testing, commissioning and customer satisfaction'),
('601/7345/2','NETP3-06','Inspect, Test and Commission Electrical Systems',3,'Be able to test and commission electrical systems and equipment','3.6','Demonstrate to the customer/client that the operation of the circuits, equipment and components are in accordance with the installation specification and customer/client requirements');

-- NETP3-07  Apply Fault Diagnosis and Rectification (10 GLH) · Ofqual Y/507/7346 · performance · verify=pass · 3 LOs / 18 ACs
INSERT INTO qualification_requirements (qualification_code, unit_code, unit_title, lo_number, lo_text, ac_code, ac_text) VALUES
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',1,'Prepare to carry out fault diagnosis','1.1','Check it is safe to carry out fault diagnosis'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',1,'Prepare to carry out fault diagnosis','1.2','Inform the relevant personnel of the fault diagnosis work (such as personnel on the premises, users of electrical equipment)'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',1,'Prepare to carry out fault diagnosis','1.3','Carry out the safe isolation procedure'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',1,'Prepare to carry out fault diagnosis','1.4','Evaluate and apply appropriate methods to ensure the safety of themselves and others when diagnosing and correcting electrical faults'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.1','Communicate effectively with relevant personnel (e.g. customer, premises manager) to ascertain the nature of the fault'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.2','Select and interpret appropriate documents (e.g. layout drawings, schematic diagrams etc) which relate to the electrical systems and equipment being worked upon'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.3','Assess and communicate potential disruption that may be a consequence of fault diagnosis and correction work to relevant people (such as other workers/colleagues Customers/clients)'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.4','Carry out relevant inspections of electrical equipment analysing findings'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.5','Confirm test instruments are fit for purpose, functioning correctly and are correctly calibrated'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.6','Perform suitable diagnostic tests, based on engineering decision, to identify electrical faults: a) loss of supply; b) overload; c) short-circuit; d) earth fault; e) incorrect phase rotation; f) high resistance joints/loose terminations; g) component, accessory or equipment faults; h) open circuit; i) signal faults'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.7','Use appropriate methods for locating faults including: a) using a logical approach; b) using safe working practices; c) interpretation of test readings'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',2,'Carry out fault diagnosis','2.8','Use appropriate instruments correctly to carry out fault diagnosis: a) voltage indicator; b) low resistance ohm meter; c) insulation resistance tester; d) EFLI and PFC tester; e) RCD tester; f) ammeter; g) phase rotation tester; h) other appropriate instrument'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.1','Assess the appropriate repairs, removals and replacements and their implications with relevant people: a) other workers/colleagues; b) customers/clients'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.2','Perform fault correction procedures correctly and safely using appropriate tools, equipment and material'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.3','Assess and verify that replacement components and associated equipment maintain: a) ease of access to enable future maintenance; b) compliance with relevant regulations; c) compliance with manufacturer’s instructions/organisational procedures'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.4','Apply appropriate procedures to ensure electrical equipment and components are left safe, in accordance with industry regulations, if the fault cannot be corrected immediately based on technical assessment.'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.5','Establish and perform an appropriate inspection and testing procedure to confirm that circuits/equipment/components are functioning correctly after completion of fault correction work'),
('601/7345/2','NETP3-07','Apply Fault Diagnosis and Rectification',3,'Carry out fault rectification','3.6','Record test results and other appropriate information regarding the fault correction work clearly and accurately and report it to relevant people: a) other workers/colleagues; b) customers/clients; c) representatives of other services');

-- 5) Repoint every EAL qualification that referenced the retired EAL-NETP3
--    backbone onto the new authoritative 601/7345/2 requirement set.
DELETE FROM qualification_requirement_mappings WHERE requirement_code='EAL-NETP3';
INSERT INTO qualification_requirement_mappings (qualification_code, requirement_code, is_primary)
SELECT q, '601/7345/2', true
FROM (VALUES
  ('603/3929/9'),  -- EAL L3 Electrotechnical (Installation) NVQ
  ('603/3928/7'),  -- EAL L3 Electrotechnical (Maintenance) NVQ
  ('603/3895/8'),  -- Installation & Maintenance Electrician Apprenticeship (ST0152)
  ('603/0149/3'),  -- BSE Craftsperson (Electrical)
  ('603/5806/9'),  -- BSE Installer (Electrical) Apprenticeship
  ('603/4027/6'),  -- Electrotechnical Experienced Worker
  ('600/4337/4'),  -- Electrotechnical Occupational Competence (AM2 Gateway)
  ('603/5933/7'),  -- EAL T Level BSE - Electrical Installation
  ('EAL-NETP3')    -- retired code, keep resolvable
) AS v(q)
WHERE NOT EXISTS (
  SELECT 1 FROM qualification_requirement_mappings m
  WHERE m.qualification_code=v.q AND m.requirement_code='601/7345/2'
);

COMMIT;

-- Total: 13 units, 304 ACs
-- 6) AFTER COMMIT: backfill embeddings (rows are NULL-embedded on INSERT by the
--    qualification_requirements_clear_embedding trigger; invisible to
--    match_qualification_acs until embedded). text-embedding-3-small, 1536-dim:
--      POST /functions/v1/embed-qualification-requirements  (service-role JWT or X-Admin-Key)
--    or via SQL using pg_net + vault:
--      SELECT net.http_post(
--        url := '<project>/functions/v1/embed-qualification-requirements',
--        headers := jsonb_build_object('Content-Type','application/json',
--          'Authorization','Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='service_role_key')),
--        body := '{}'::jsonb);
