-- ELE-1904: every criterion links to the lesson that teaches it and the
-- practice questions that test it.
--
-- ac_study_links holds mappings people already made; nothing here is new
-- content and nothing is guessed:
--   study     a Study Centre lesson page whose author wrote "Maps to C&G
--             <qual> / Unit N / LO n / AC x.y" (or "Layered depth: …") in its
--             header. Extracted by scripts/college/ac-study-links/extract.mjs;
--             every key checked against qualification_requirements.
--   practise  the module question bank's questions that the mock exams'
--             content-matched question → page table (mockTopicLessons.ts,
--             ELE-1815) sends to that lesson's section page. Section level,
--             not AC level, and labelled as such on screen.
--
-- Criteria with identical wording in another City & Guilds qualification
-- (qualification_requirements.canonical_ac_id, an existing link, followed up
-- to three hops) inherit the other one's links when they have none of their
-- own (via = 'same_wording').
-- EAL criteria have no canonical links by design, so they get none.

create table if not exists public.ac_study_links (
  id uuid primary key default gen_random_uuid(),
  qualification_code text not null,
  unit_code text not null,
  lo_number integer,
  ac_code text not null,
  kind text not null check (kind in ('study', 'practise')),
  route text not null,
  title text,
  minutes integer,
  question_count integer,
  bank_slug text,
  source text not null,
  source_ref text,
  created_at timestamptz not null default now(),
  unique (qualification_code, unit_code, ac_code, kind, route)
);

comment on table public.ac_study_links is
  '[COLLEGE] ELE-1904. Criterion → Study Centre lesson (kind study, from the page''s own "Maps to" header) and → practice questions (kind practise, from the mock exams'' content-matched question → page table). Generated by scripts/college/ac-study-links/extract.mjs; re-run it, never hand-edit. Read through study_links_for() / catalogue_for().';

create index if not exists ac_study_links_key_idx
  on public.ac_study_links (qualification_code, unit_code, ac_code);

alter table public.ac_study_links enable row level security;

drop policy if exists "Signed-in users read study links" on public.ac_study_links;
create policy "Signed-in users read study links" on public.ac_study_links
  for select to authenticated using (true);

revoke all on public.ac_study_links from anon;
revoke insert, update, delete on public.ac_study_links from authenticated;
grant select on public.ac_study_links to authenticated;

-- Links for every criterion of one requirement code (the code the AC rows
-- are stored under, e.g. 2365-03), own links first, then same-wording ones.
create or replace function public._ac_study_links_for(p_requirement_code text)
returns table (
  requirement_id uuid,
  unit_code text,
  ac_code text,
  kind text,
  route text,
  title text,
  minutes integer,
  question_count integer,
  bank_slug text,
  via text,
  via_qualification text
)
language sql
stable
security definer
set search_path = public
as $$
  with recursive own as (
    select r.id as requirement_id, r.unit_code, r.ac_code, l.kind, l.route, l.title,
           l.minutes, l.question_count, l.bank_slug, 'direct'::text as via,
           l.qualification_code as via_qualification
      from public.qualification_requirements r
      join public.ac_study_links l
        on l.qualification_code = r.qualification_code
       and l.unit_code = r.unit_code
       and l.ac_code = r.ac_code
     where r.qualification_code = p_requirement_code
  ),
  -- Follow identical-wording links (canonical_ac_id) up to three hops, e.g.
  -- 2346-03 → 5357 → 2365-03. Wording is identical at every hop.
  chain as (
    select r.id as requirement_id, r.canonical_ac_id as target, 1 as hop
      from public.qualification_requirements r
     where r.qualification_code = p_requirement_code
       and r.canonical_ac_id is not null and r.canonical_ac_id <> r.id
    union all
    select c.requirement_id, t.canonical_ac_id, c.hop + 1
      from chain c
      join public.qualification_requirements t on t.id = c.target
     where c.hop < 3 and t.canonical_ac_id is not null and t.canonical_ac_id <> t.id
  ),
  inherited as (
    select distinct on (ch.requirement_id, l.kind, l.route)
           ch.requirement_id, r.unit_code, r.ac_code, l.kind, l.route, l.title,
           l.minutes, l.question_count, l.bank_slug, 'same_wording'::text,
           l.qualification_code
      from chain ch
      join public.qualification_requirements r on r.id = ch.requirement_id
      join public.qualification_requirements c on c.id = ch.target
      join public.ac_study_links l
        on l.qualification_code = c.qualification_code
       and l.unit_code = c.unit_code
       and l.ac_code = c.ac_code
     where not exists (select 1 from own o where o.requirement_id = ch.requirement_id and o.kind = l.kind)
     order by ch.requirement_id, l.kind, l.route, ch.hop
  )
  select * from own
  union all
  select * from inherited;
$$;

revoke all on function public._ac_study_links_for(text) from public, anon, authenticated;

comment on function public._ac_study_links_for(text) is
  '[COLLEGE] ELE-1904 internal: study/practise links for every criterion of a requirement code, own links first then same-wording (canonical_ac_id) ones. Called by study_links_for() and catalogue_for().';

-- The read API for the learner's coverage screen and the evidence detail.
-- Takes the learner's qualification code OR its requirement code; aliases
-- (e.g. 3529 → 2365-03) resolve through qualification_requirement_mappings.
create or replace function public.study_links_for(p_qualification_code text)
returns table (
  unit_code text,
  ac_code text,
  kind text,
  route text,
  title text,
  minutes integer,
  question_count integer,
  bank_slug text,
  via text,
  via_qualification text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_req text;
begin
  if auth.uid() is null then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  select m.requirement_code into v_req
    from public.qualification_requirement_mappings m
   where m.qualification_code = p_qualification_code
   order by m.is_primary desc nulls last
   limit 1;
  return query
    select l.unit_code, l.ac_code, l.kind, l.route, l.title, l.minutes,
           l.question_count, l.bank_slug, l.via, l.via_qualification
      from public._ac_study_links_for(coalesce(v_req, p_qualification_code)) l
     order by l.unit_code, l.ac_code, l.kind, (l.via = 'direct') desc, l.route;
end;
$$;

revoke all on function public.study_links_for(text) from public, anon;
grant execute on function public.study_links_for(text) to authenticated;

comment on function public.study_links_for(text) is
  '[COLLEGE] ELE-1904. Study (lesson page) and Practise (question bank section) links for every criterion of a qualification, alias-resolved. Signed-in users only; the links are not personal data.';
